### PR TITLE
fix access invalid memory for Aggregation

### LINKED ISSUE #10001: fix asan failed unit test
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
`SpillAggregationTestRunner.AggWithSpecialGroupKey` failed for asan

```
  SUMMARY: AddressSanitizer: heap-buffer-overflow /llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:63:3 in __asan_memcpy
  Shadow bytes around the buggy address:
    0x521002d7ca80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x521002d7cb00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x521002d7cb80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x521002d7cc00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x521002d7cc80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  =>0x521002d7cd00:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    0x521002d7cd80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    0x521002d7ce00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    0x521002d7ce80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    0x521002d7cf00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    0x521002d7cf80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  Shadow byte legend (one shadow byte represents 8 application bytes):
    Addressable:           00
    Partially addressable: 01 02 03 04 05 06 07
    Heap left redzone:       fa
    Freed heap region:       fd
    Stack left redzone:      f1
    Stack mid redzone:       f2
    Stack right redzone:     f3
    Stack after return:      f5
    Stack use after scope:   f8
    Global redzone:          f9
    Global init order:       f6
    Poisoned by user:        f7
    Container overflow:      fc
    Array cookie:            ac
    Intra object redzone:    bb
    ASan internal:           fe
    Left alloca redzone:     ca
    Right alloca redzone:    cb
```

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #10001

Problem Summary:

### What is changed and how it works?

```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by yibin87 — APPROVED** [review]
LGTM

File: dbms/src/Columns/IColumn.h [hunk 1]
```diff
@@ -316,9 +316,9 @@ class IColumn : public COWPtr<IColumn>
     /// Deserialize and insert data from pos and forward each pos[i] to the end of serialized data.
     /// Note:
     /// 1. The pos pointer must not be nullptr.
-    /// 2. The memory of pos must be accessible to overflow 15 bytes(i.e. PaddedPODArray) for speeding up memcpy.(e.g. for ColumnString)
-    /// 3. If use_nt_align_buffer is true and AVX2 is enabled, non-temporal store may be used when data memory is aligned to FULL_VECTOR_SIZE_AVX2(64 bytes).
-    /// 4. If non-temporal store is used, the data will be copied to a align_buffer firstly and then flush to column data if full. After the
+    /// 2. If use_nt_align_buffer is true and AVX2 is enabled, non-temporal store may be used when data memory is aligned to FULL_VECTOR_SIZE_AVX2(64 bytes).
+    ///    NOTE: The memory of pos must be accessible to **overflow 15 bytes**(i.e. PaddedPODArray) when use_nt_align_buffer is true.
```
Comment (gengliqi) [inline dbms/src/Columns/IColumn.h:320]:
```suggestion
    /// 2. If use_nt_align_buffer is true and AVX2 is enabled, non-temporal store may be used when data memory is aligned to FULL_VECTOR_SIZE_AVX2(64 bytes).
    ///    The memory of pos must be accessible to **overflow 15 bytes**(i.e. PaddedPODArray) for speeding up memcpy when use_nt_align_buffer is true.
```

**Review by gengliqi — APPROVED** [review]
