### PR TITLE
Fix big endian issue for StringHashTable

### LINKED ISSUE #6555: StringHashTable only works correctly on little-endian arch
## Bug Report
Current StringHashTable doesn't work correctly on big-endian arch. The problem might occur when aggregate keys' number is 1, and the key is non-nullable string.

### PR DESCRIPTION
**Pull request by yibin87**
Signed-off-by: yibin <huyibin@pingcap.com>

### What problem does this PR solve?

Issue Number: close #6555

Problem Summary:

### Check List

Tests 
Simple fix, no tests.
- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/IO/Endian.h [hunk 1]
```diff
@@ -18,6 +18,11 @@
 
 namespace DB
 {
+inline constexpr bool isLittleEndian()
```
Comment (bestwoody) [inline dbms/src/IO/Endian.h:21]: is `constexpr` means it's decided at comiler time?

Comment (yibin87) [reply dbms/src/IO/Endian.h:21]: Yes

Comment (bestwoody) [reply dbms/src/IO/Endian.h:21]: however, ref to doc, I found `native` is determined at execution environment

Comment (bestwoody) [reply dbms/src/IO/Endian.h:21]: The value of order::native shall be:

equal to order::big if the **execution environment** is big endian, otherwise

equal to order::little if the **execution environment** is little endian, otherwise

unequal to both order::little and order::big.

Comment (yibin87) [reply dbms/src/IO/Endian.h:21]: I'll check it.

Comment (yibin87) [reply dbms/src/IO/Endian.h:21]: From contrib/boost/boost/endian/detail/order.hpp, it looks like the native value can be initialized to either big or little from compilation environments.

Comment (bestwoody) [reply dbms/src/IO/Endian.h:21]: ok

Comment (yibin87) [reply dbms/src/IO/Endian.h:21]: Oh, there is a third possibility: __ORDER_PDP_ENDIAN__, seems mixture of little and big, which I think we'd not support now.

File: dbms/src/Common/HashTable/StringHashTable.h [hunk 2]
```diff
@@ -296,13 +295,19 @@ class StringHashTable : private boost::noncopyable
             if ((reinterpret_cast<uintptr_t>(p) & 2048) == 0)
             {
                 memcpy(&n[0], p, 8);
-                n[0] &= -1ul >> s;
+                if constexpr (DB::isLittleEndian())
+                    n[0] &= (-1ULL >> s);
```
Comment (bestwoody) [inline dbms/src/Common/HashTable/StringHashTable.h:299]: it seem the old one use `-1ul`, while the new one use `-1ull`. is it expected?

Comment (yibin87) [reply dbms/src/Common/HashTable/StringHashTable.h:299]: > 

Yes, it should be 8 bytes integer.

**Review by bestwoody — APPROVED** [review]
lgtm

File: dbms/src/Common/HashTable/StringHashTable.h [hunk 3]
```diff
@@ -296,13 +295,19 @@ class StringHashTable : private boost::noncopyable
...
+                else
+                    n[0] &= (-1ULL << s);
             }
             else
             {
                 const char * lp = x.data + x.size - 8;
                 memcpy(&n[0], lp, 8);
-                n[0] >>= s;
+                if constexpr (DB::isLittleEndian())
```
Comment (mengxin9014) [inline dbms/src/Common/HashTable/StringHashTable.h:307]: Whether the same fix is needed in TwoLevelStringHashTable?

Comment (yibin87) [reply dbms/src/Common/HashTable/StringHashTable.h:307]: Good catch, I'll apply it also.

**Review by mengxin9014 — APPROVED** [review]
LGTM

**Review by ywqzzy — APPROVED** [review]

**Comment by ywqzzy** [comment]
Do we need to check the runtime endian is exact the same as the compilation endian?
