### PR TITLE
Performance optimization of SegmentReadTaskScheduler

### LINKED ISSUE #5960: Snapshot can't be released for one hour when high currency query
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

89b8f5d6-dd9a-4a83-a722-6f55b3a81e2d
the normal store size is less than 10G, but it will inrease more than 200G for the long snapshot lifetime
origin_img_v2_320cc3a2-8066-48cb-961b-a478c5f9fbfg

### 4. What is your TiFlash version? (Required)
master

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #5960

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by flowbehappy** [comment]
Can you implement a micro bench for the scheduler?

File: dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h [hunk 1]
```diff
@@ -227,6 +231,8 @@ class SegmentReadTaskPool : private boost::noncopyable
     // The memory tracker of MPPTask.
     MemoryTrackerPtr mem_tracker;
 
+    std::once_flag add_to_scheduler;
```
Comment (flowbehappy) [inline dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h:234]: Is there any chance that a taskpool be added twice since we already do protection by `task_pool_added`?

File: dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp [hunk 2]
```diff
@@ -196,12 +194,38 @@ bool SegmentReadTaskScheduler::isStop() const
...
+        std::tie(merged_task, run_sche) = scheduleMergedTask();
+        if (merged_task != nullptr)
+        {
+            count++;
+            auto elapsed_ms = sw_sche_once.elapsedMilliseconds();
+            if (elapsed_ms >= 5)
+            {
+                LOG_FMT_DEBUG(log, "scheduleMergedTask segment_id={} pool_ids={} cost={}ms pool_count={}", merged_task->getSegmentId(), merged_task->getPoolIds(), elapsed_ms, pool_count);
+            }
+            SegmentReaderPoolManager::instance().addTask(std::move(merged_task));
```
Comment (flowbehappy) [inline dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp:218]: Haven't we designed any hints from ReaderPool about too many tasks?

File: dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h [hunk 3]
```diff
@@ -80,7 +82,7 @@ class UnorderedInputStream : public IProfilingBlockInputStream
         while (true)
         {
             FAIL_POINT_PAUSE(FailPoints::pause_when_reading_from_dt_stream);
-
+            addReadTaskPoolToScheduler();
```
Comment (flowbehappy) [inline dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h:85]: I think put it before `while(true)` is better.

File: dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h (hunk 1 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h:234]: @flowbehappy there could be multiple `UnorderedInputStream` hold the same ptr to one `SegmentReadTaskPool `
https://github.com/pingcap/tiflash/blob/master/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp#L1003-L1014

Comment (JaySon-Huang) [reply dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h:234]: Add some comments to explain the var here?

File: dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp [hunk 4]
```diff
@@ -125,8 +125,7 @@ SegmentReadTaskPools SegmentReadTaskScheduler::getPoolsUnlock(const std::vector<
 
 SegmentReadTaskPoolPtr SegmentReadTaskScheduler::scheduleSegmentReadTaskPoolUnlock()
 {
-    auto [valid, invalid] = read_pools.count(0);
-    auto pool_count = valid + invalid; // Invalid read task pool also need to be scheduled for clean MergedTaskPool.
+    int64_t pool_count = read_pools.size(); // All read task pool need to be scheduled, include invalid read task pool.
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp:128]:
```suggestion
    int64_t pool_count = read_pools.size(); // All read task pool need to be scheduled, including invalid read task pool.
```

File: dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp [hunk 5]
```diff
@@ -154,6 +154,8 @@ std::unordered_map<uint64_t, std::vector<uint64_t>>::const_iterator SegmentReadT
     {
         return target;
     }
+    static constexpr int max_iter_count = 32;
```
[the remark this answers is not in the document]
Comment (flowbehappy) [reply dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp:157]: Yes. Please don't return iterator.

**Review by flowbehappy — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]
lgtm
