### PR TITLE
Fix sync schema after schema version key be removed

### LINKED ISSUE #7071: Storage can not be removed after delete range in TiKV
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. run tiflash in apiv2 and multi-tenant mode
2. create database and table
3. add tiflash replica
4. delete placement rules and delete the whole keyspace range to tikv
5. tiflash can not sync schema and storage can not be removed

### 2. What did you expect to see? (Required)

tiflash can remove storage after delete range in tikv.

### 3. What did you see instead (Required)

tiflash storage can not be removed and GC

### 4. What is your TiFlash version? (Required)

master

### PR DESCRIPTION
**Pull request by yongman**
### What problem does this PR solve?

Issue Number: close #7071 

Problem Summary:

### What is changed and how it works?

If schema version key for keyspace not exists, load all schema and tombstone tables and databases in this keyspace.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 1]
```diff
@@ -110,14 +116,27 @@ struct TiDBSchemaSyncer : public SchemaSyncer
         auto getter = createSchemaGetter(keyspace_id);
 
         Int64 version = getter.getVersion();
-        if (version <= cur_version)
+        if (version == -1 && cur_version == version)
+        {
+            // Tables and databases are already tombstoned and waiting for GC.
+            return false;
+        }
```
Comment (iosmanthus) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:123]: I think it's too implicit, the reader does not know the table's dropped in `builder.syncAllSchemas`. How about constructing a builder here and calling applyDropSchema for each table/database explicitly?

Comment (JaySon-Huang) [reply dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:123]: Is there a chance that `SchemaGetter::getVersion` get `-1`, but the tables and databases metadata on TiKV does not get cleaned yet?

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 2]
```diff
@@ -102,6 +102,12 @@ struct TiDBSchemaSyncer : public SchemaSyncer
         return it->second;
     }
 
+    void removeCurrentVersion(KeyspaceID keyspace_id) override
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:105]:
```suggestion
    // After all tables have been physical dropped, remove the `cur_version` of given keyspace
    void removeCurrentVersion(KeyspaceID keyspace_id) override
```

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h (hunk 1 above)
Comment (yongman) [reply dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:123]: > Is there a chance that `SchemaGetter::getVersion` get `-1`, but the tables and databases metadata on TiKV does not get fully cleaned yet?

I think  partial deletion of an entire keyspace is illegal.

Comment (JaySon-Huang) [reply dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:123]: how do the Regions of a "deleted" keyspace get removed from TiKV? Are they removed one by one?

Comment (yongman) [reply dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:123]: @JaySon-Huang No, the keyspace range will be delete in two `UnsafeDestroyRange` request, one for transaction kv space, the other for raw kv space.

Comment (yongman) [reply dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:123]: I agree that it's better make the logic more direct, the logic now is to treat the `version=-1` as same as `version>=0` to sync schema, but return ASAP in `tryLoadSchemaDiffs` if `version is -1`. 
I wonder is it necessary to implement a branch to `syncAllSchemas` and maintain the metrics ? 🤦 /cc @JaySon-Huang @iosmanthus

Comment (yongman) [reply dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:124]: Considering of possibility inconsistency of `getVersion` and `listDBs` after `UnsafeDestroyRange`, we do not need to `listDB` or `listTables` if the schema version key not exists. It‘s neccessary to run shortcut logic in this case. We can add a new method `SchemaBuilder::dropAllSchema()` to resolve this. /cc @JaySon-Huang @iosmanthus

Comment (JaySon-Huang) [reply dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:124]: LGTM

**Comment by yongman** [comment]
@JaySon-Huang @iosmanthus PTAL

File: dbms/src/TiDB/Schema/SchemaBuilder.cpp [hunk 3]
```diff
@@ -1379,6 +1379,42 @@ void SchemaBuilder<Getter, NameMapper>::syncAllSchema()
     LOG_INFO(log, "Loaded all schemas.");
 }
 
+template <typename Getter, typename NameMapper>
+void SchemaBuilder<Getter, NameMapper>::dropAllSchema()
+{
+    LOG_INFO(log, "Droping all schemas.");
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/SchemaBuilder.cpp:1385]:
```suggestion
    LOG_INFO(log, "Dropping all schemas.");
```

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 4]
```diff
@@ -110,37 +117,53 @@ struct TiDBSchemaSyncer : public SchemaSyncer
...
         {
-            GET_METRIC(tiflash_schema_apply_count, type_full).Increment();
-            version_after_load_diff = loadAllSchema(getter, version, context);
+            // Tables and databases are already tombstoned and waiting for GC.
+            if (version == cur_version)
+                return false;
+
+            LOG_INFO(ks_log, "Start to drop schemas. schema version key not exists, keyspace should be deleted");
+
+            dropAllSchema(getter, context);
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:137]:
```suggestion
            // The key range of the given keyspace is deleted by `UnsafeDestroyRange`, so the return result
            // of `SchemaGetter::listDBs` is not reliable. Directly mark all databases and tables of this keyspace
            // as a tombstone and let the SchemaSyncService drop them physically.
            dropAllSchema(getter, context);
```

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 5]
```diff
@@ -110,37 +117,53 @@ struct TiDBSchemaSyncer : public SchemaSyncer
...
-        // to X-1 and try to fetch the schema diff X next time.
-        Int64 version_after_load_diff = 0;
-        if (version_after_load_diff = tryLoadSchemaDiffs(getter, cur_version, version, context, ks_log); version_after_load_diff == -1)
+        // If the schema version not exists, drop all schemas.
+        if (version == -1)
         {
-            GET_METRIC(tiflash_schema_apply_count, type_full).Increment();
-            version_after_load_diff = loadAllSchema(getter, version, context);
+            // Tables and databases are already tombstoned and waiting for GC.
+            if (version == cur_version)
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:132]: Better name "-1" as a constant "SchemaVersionNotExist" and use it here

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h (hunk 4 above)
Comment (JaySon-Huang) [reply dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:137]: And add metrics in `TiFlashMetrics.h` and report it here

`GET_METRIC(tiflash_schema_apply_count, type_drop_keyspace).Increment();`

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 6]
```diff
@@ -102,6 +102,13 @@ struct TiDBSchemaSyncer : public SchemaSyncer
...
+    // After all tables have been physical dropped, remove the `cur_version` of given keyspace
+    void removeCurrentVersion(KeyspaceID keyspace_id) override
+    {
+        std::lock_guard lock(schema_mutex);
+        cur_versions.erase(keyspace_id);
+    }
+
     bool syncSchemas(Context & context, KeyspaceID keyspace_id) override
     {
         std::lock_guard lock(schema_mutex);
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:114]: Out of topic: Now all keyspace wait on the same `schema_mutex`, which means If a keyspace (ks1) takes a long time to synchronize schema, and another keyspace (ks2) triggers a SchemaSync while processing read requests, the read requests of ks2 may be blocked by ks1.

Maybe we can create an improvement issue for it and resolve it later.

Comment (yongman) [reply dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:114]: New issue https://github.com/pingcap/tiflash/issues/7074

File: dbms/src/TiDB/Schema/SchemaGetter.h [hunk 7]
```diff
@@ -129,6 +129,8 @@ struct SchemaDiff
 
 struct SchemaGetter
 {
+    static constexpr int SchemaVersionNotExist = -1;
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/SchemaGetter.h:132]:
```suggestion
    static constexpr Int64 SchemaVersionNotExist = -1;
```

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 8]
```diff
@@ -110,37 +117,57 @@ struct TiDBSchemaSyncer : public SchemaSyncer
...
-        // to X-1 and try to fetch the schema diff X next time.
-        Int64 version_after_load_diff = 0;
-        if (version_after_load_diff = tryLoadSchemaDiffs(getter, cur_version, version, context, ks_log); version_after_load_diff == -1)
+        // If the schema version not exists, drop all schemas.
+        if (version == SchemaGetter::SchemaVersionNotExist)
         {
-            GET_METRIC(tiflash_schema_apply_count, type_full).Increment();
-            version_after_load_diff = loadAllSchema(getter, version, context);
+            // Tables and databases are already tombstoned and waiting for GC.
+            if (version == cur_version)
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:132]:
```suggestion
            if (SchemaGetter::SchemaVersionNotExist == cur_version)
```
It would be more clear

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 9]
```diff
@@ -110,37 +117,57 @@ struct TiDBSchemaSyncer : public SchemaSyncer
...
+                return false;
+
+            LOG_INFO(ks_log, "Start to drop schemas. schema version key not exists, keyspace should be deleted");
+            GET_METRIC(tiflash_schema_apply_count, type_drop_keyspace).Increment();
+
+            // The key range of the given keyspace is deleted by `UnsafeDestroyRange`, so the return result
+            // of `SchemaGetter::listDBs` is not reliable. Directly mark all databases and tables of this keyspace
+            // as a tombstone and let the SchemaSyncService drop them physically.
+            dropAllSchema(getter, context);
+            cur_versions[keyspace_id] = version;
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:142]:
```suggestion
            cur_versions[keyspace_id] = SchemaGetter::SchemaVersionNotExist;
```
ditto

**Review by JaySon-Huang — APPROVED** [review]
The rest LGTM

File: dbms/src/TiDB/Schema/SchemaBuilder.cpp [hunk 10]
```diff
@@ -1379,6 +1379,42 @@ void SchemaBuilder<Getter, NameMapper>::syncAllSchema()
...
+    for (auto it = storage_map.begin(); it != storage_map.end(); it++)
+    {
+        auto table_info = it->second->getTableInfo();
+        if (table_info.keyspace_id != keyspace_id)
+        {
+            continue;
+        }
+        applyDropPhysicalTable(it->second->getDatabaseName(), table_info.id);
+        LOG_DEBUG(log, "Table {}.{} dropped during drop all schemas", it->second->getDatabaseName(), name_mapper.debugTableName(table_info));
+    }
```
Comment (Lloyd-Pottiger) [inline dbms/src/TiDB/Schema/SchemaBuilder.cpp:1400]: better to use [Range-based for loop](https://en.cppreference.com/w/cpp/language/range-for)

Comment (yongman) [reply dbms/src/TiDB/Schema/SchemaBuilder.cpp:1400]: @Lloyd-Pottiger This code block if copied from syncAllSchemas,  we should keep the code style same?

Comment (Lloyd-Pottiger) [reply dbms/src/TiDB/Schema/SchemaBuilder.cpp:1400]: no, improve it, I think.

Comment (yongman) [reply dbms/src/TiDB/Schema/SchemaBuilder.cpp]: PTAL~

**Review by Lloyd-Pottiger — APPROVED** [review]
