### PR TITLE
Storages: Refine SegmentReadTaskScheduler::add to reduce lock contention

### LINKED ISSUE #9024: `SegmentReadTaskScheduler::add` took too long.
## Bug Report

[2024/05/02 14:11:37.563 +00:00] [INFO] [SegmentReadTaskScheduler.cpp:58] ["Added, pool_id=47879 table_id=7511 block_slots=48 segment_count=4 pool_count=123 cost=120437219.576us do_add_cost=7.705us"] [thread_id=929]

120s

v7.5.1

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #9024

### What is changed and how it works?

- Add `pending_pools`: pools from computational layer will be added to `pending_pools` and can return immediately.
- `sched_thread` will reap `pending_pools` before calling `scheduleOneRound`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  - Run queries without any exceptions. 
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp [hunk 1]
```diff
@@ -39,32 +39,63 @@ SegmentReadTaskScheduler::~SegmentReadTaskScheduler()
 }
 
 void SegmentReadTaskScheduler::add(const SegmentReadTaskPoolPtr & pool)
+{
+    std::lock_guard lock(add_mtx);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp:43]: Do we still need this guard on `add_mtx`? Seems that `submitPendingPool` is thread-safe

File: dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp [hunk 2]
```diff
@@ -39,32 +39,63 @@ SegmentReadTaskScheduler::~SegmentReadTaskScheduler()
...
+void SegmentReadTaskScheduler::reapPendingPools()
+{
+    SegmentReadTaskPools pools;
+    {
+        std::lock_guard lock(pending_mtx);
+        pools.swap(pending_pools);
+    }
+    if (!pools.empty())
+    {
+        addPools(pools);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp:97]: We can directly put the for-loop here and remove the function `addPools`
```suggestion
        for (const auto & pool : pools)
        {
            addPool(pool);
        }
        LOG_INFO(log, "Added, pool_ids={}, pool_count={}", pools, read_pools.size());
```

File: dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp (hunk 1 above)
Comment (SeaRise) [reply dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp:43]: Please add comments like `To avoid schedule from always failing to acquire the pending_mtx`

**Review by SeaRise — APPROVED** [review]
Others LGTM

**Review by JaySon-Huang — APPROVED** [review]
LGTM
