### PR TITLE
DDL: Use Column Name Instead of Offset to Find the common handle cluster index

### LINKED ISSUE #5154: TiFlash crash after dropping a column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table test (A int, B varchar(20), C int, D int, PRIMARY KEY(A,C) CLUSTERED);
# drop column before the column composing clustered index
mysql> insert into test values (1,'1',1,1),(2,'2',2,2);
mysql> alter table test drop column B;
# insert some rows
mysql> insert into test values (3,3,3),(4,4,4);
mysql> insert into test values (5,5,5),(6,6,6);
mysql> insert into test values (7,7,7),(8,8,8);
mysql> alter table test set tiflash replica 1;
```

### 2. What did you expect to see? (Required)
TiFlash run normally

### 3. What did you see instead (Required)
```
[2022/06/15 17:42:56.574 +08:00] [ERROR] [Exception.cpp:85] ["DB::EngineStoreApplyRes DB::HandleWriteRaftCmd(const DB::EngineStoreServerWrap *, DB::WriteCmdsView, DB::RaftCmdHeader):Code: 12, e.displayText() = DB::Exception:
Parameters start = 0, length = 1 are out of bound in ColumnVector<T>::insertRangeFrom method (data.size() = 0)., e.what() = DB::Exception, Stack trace:


       0x1d272d3    StackTrace::StackTrace() [tiflash+30569171]
                    dbms/src/Common/StackTrace.cpp:23
       0x1d248d6    DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+30558422]
                    dbms/src/Common/Exception.h:41
       0x768eafa    DB::ColumnVector<unsigned long>::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) [tiflash+124316410]
                    dbms/src/Columns/ColumnVector.cpp:199
       0x789403b    DB::DM::ColumnFileInMemory::append(DB::DM::DMContext&, DB::Block const&, unsigned long, unsigned long, unsigned long) [tiflash+126435387]
                    dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp:82
       0x78bce78    DB::DM::MemTableSet::appendToCache(DB::DM::DMContext&, DB::Block const&, unsigned long, unsigned long) [tiflash+126602872]
                    dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp:149
       0x78aa731    DB::DM::DeltaValueSpace::appendToCache(DB::DM::DMContext&, DB::Block const&, unsigned long, unsigned long) [tiflash+126527281]
                    dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:118
       0x77c3aac    DB::DM::Segment::writeToCache(DB::DM::DMContext&, DB::Block const&, unsigned long, unsigned long) [tiflash+125581996]
                    dbms/src/Storages/DeltaMerge/Segment.cpp:306
       0x778ec09    DB::DM::DeltaMergeStore::write(DB::Context const&, DB::Settings const&, DB::Block&) [tiflash+125365257]
                    dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:653
       0x79170f2    DB::writeRegionDataToStorage(DB::Context&, DB::RegionPtrWithBlock const&, std::__1::vector<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> >, std::__1::allocator<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> > > >&, Poco::Logger*)::$_0::operator()(bool) const [tiflash+126972146]
                    dbms/src/Storages/Transaction/PartitionStreams.cpp:145
       0x7912fa1    DB::writeRegionDataToStorage(DB::Context&, DB::RegionPtrWithBlock const&, std::__1::vector<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> >, std::__1::allocator<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> > > >&, Poco::Logger*) [tiflash+126955425]
                    dbms/src/Storages/Transaction/PartitionStreams.cpp:178
       0x7912c9c    DB::RegionTable::writeBlockByRegion(DB::Context&, DB::RegionPtrWithBlock const&, std::__1::vector<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> >, std::__1::allocator<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> > > >&, Poco::Logger*, bool) [tiflash+126954652]
                    dbms/src/Storages/Transaction/PartitionStreams.cpp:348
       0x79351ff    DB::Region::handleWriteRaftCmd(DB::WriteCmdsView const&, unsigned long, unsigned long, DB::TMTContext&) [tiflash+127095295]
                    dbms/src/Storages/Transaction/Region.cpp:712
       0x7901910    DB::KVStore::handleWriteRaftCmd(DB::WriteCmdsView const&, unsigned long, unsigned long, unsigned long, DB::TMTContext&) [tiflash+126884112]
                    dbms/src/Storages/Transaction/KVStore.cpp:285
       0x791b822    HandleWriteRaftCmd [tiflash+126990370]
                    dbms/src/Storages/Transaction/ProxyFFI.cpp:92
  0x7f0223e736e0    raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::process_raft_cmd::h4c8bba241d5ee4d4 [libtiflash_proxy.so+28567264]
  0x7f0223e70d6c    raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::handle_raft_committed_entries::h478c4bad834ddec7 [libtiflash_proxy.so+28556652]
  0x7f0223e90f91    raftstore::store::fsm::apply::ApplyFsm$LT$EK$GT$::handle_apply::he4c0b1137ae7cad9 [libtiflash_proxy.so+28688273]
  0x7f0223e93bfe    raftstore::store::fsm::apply::ApplyFsm$LT$EK$GT$::handle_tasks::h5b138e5889c69e66 [libtiflash_proxy.so+28699646]
  0x7f0223e96510    _$LT$raftstore..store..fsm..apply..ApplyPoller$LT$EK$GT$$u20$as$u20$batch_system..batch..PollHandler$LT$raftstore..store..fsm..apply..ApplyFsm$LT$EK$GT$$C$raftstore..store..fsm..apply..ControlFsm$GT$$GT$::handle_normal::he20c24833a37424f [libtiflash_proxy.so+28710160]
  0x7f0223b0925f    batch_system::batch::Poller$LT$N$C$C$C$Handler$GT$::poll::hec57674a22fdcc30 [libtiflash_proxy.so+24986207]
  0x7f02241b2cd8    std::sys_common::backtrace::__rust_begin_short_backtrace::h189c0b2868fa537c [libtiflash_proxy.so+31972568]
  0x7f02239eaec1    core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h7c53021c905641b6 [libtiflash_proxy.so+23813825]
  0x7f02243c8fca    std::sys::unix::thread::Thread::new::thread_start::hd39c5f08bdcda277 [libtiflash_proxy.so+34160586]
  0x7f0221a12ea5    start_thread [libpthread.so.0+32421]
                    /usr/src/debug/glibc-2.17-c758a686/nptl/pthread_create.c:307
  0x7f0221525b0d    <unknown symbol> [libc.so.6+1043213]
                    /usr/src/debug////////glibc-2.17-c758a686/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111"] [thread_id=14]
```

### 4. What is your TiFlash version? (Required)
v6.1.0

### PR DESCRIPTION
**Pull request by hongyunyan**
### What problem does this PR solve?

Issue Number: close #5154 

Problem Summary:

### What is changed and how it works?

in decodingSchemaSnapshot, we use column name instead of offset to find cluster index id of the common handle. Because in tiflash, we don't update the indexinfo of table_info except rename ddl action. Thus, the offset of tidb_table_info is not correctly in sometimes.

Besides, I add two DDL tests based on issue #5154, concerning about clustered index.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the TiFlash crash issue that occurs after dropping a column of a table with clustered indexes under some situations.
```

### CODE REVIEW

**Comment by hongyunyan** [comment]
cc @JaySon-Huang @lidezhu

File: dbms/src/Storages/Transaction/TiDB.h [hunk 1]
```diff
@@ -179,6 +179,10 @@ struct ColumnInfo
 
     ColumnID id = -1;
     String name;
+
+    /// please be very careful when you have to use offset,
+    /// because we never update offset when DDL action changes.
+    /// Thus, our offset will not exactly correspond the order of columns.
     Int32 offset = -1;
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Transaction/TiDB.h:186]: can we make `ColumnInfo.offset` and `IndexColumnInfo.offset` to be private to avoid them being used unexpectedly?

File: dbms/src/Debug/dbgTools.cpp [hunk 2]
```diff
@@ -330,11 +330,18 @@ void insert( //
...
+        }
+
         for (size_t i = 0; i < table_info.getPrimaryIndexInfo().idx_cols.size(); i++)
         {
-            const auto & idx_col = table_info.getPrimaryIndexInfo().idx_cols[i];
-            const auto & column_info = table_info.columns[idx_col.offset];
-            auto start_field = RegionBench::convertField(column_info, fields[idx_col.offset]);
+            const auto & idx_col = column_name_columns_index_map[table_info.getPrimaryIndexInfo().idx_cols[i].name];
+            const auto & column_info = table_info.columns[idx_col];
+            auto start_field = RegionBench::convertField(column_info, fields[idx_col]);
```
Comment (JaySon-Huang) [inline dbms/src/Debug/dbgTools.cpp:344]:
```suggestion
            const auto & col_idx = column_name_columns_index_map[table_info.getPrimaryIndexInfo().idx_cols[i].name];
            const auto & column_info = table_info.columns[col_idx];
            auto start_field = RegionBench::convertField(column_info, fields[col_idx]);
```

**Review by JaySon-Huang — COMMENTED** [review]
maybe also add a check in `RegionBlockReader::readImpl` before returning true to ensure all the columns in the decode block have the same row number?

https://github.com/pingcap/tiflash/blob/164eda5296fe0714ba3e7a30f0ffd7a562b378be/dbms/src/Storages/Transaction/RegionBlockReader.cpp#L211

File: tests/fullstack-test-dt/clustered_index/ddl.test [hunk 3]
```diff
@@ -66,3 +66,87 @@ mysql> set session tidb_isolation_read_engines='tiflash'; select * from test.t_2
 
 mysql> drop table test.t_1;
 mysql> drop table test.t_2;
+
+
+### about issue 5154 to check whether add column/drop column will effect the cluster index decode
+### drop the column between two columns that are cluster index columns 
+
+mysql> drop table if exists test.t_3;
+mysql> set session tidb_isolation_read_engines='tiflash';
```
Comment (JaySon-Huang) [inline tests/fullstack-test-dt/clustered_index/ddl.test:75]:
```suggestion
```

File: tests/fullstack-test-dt/clustered_index/ddl.test [hunk 4]
```diff
@@ -66,3 +66,87 @@ mysql> set session tidb_isolation_read_engines='tiflash'; select * from test.t_2
...
+mysql> create table test.t_3 (A int, B varchar(20), C int, D int, PRIMARY KEY(A,C) CLUSTERED);
+mysql> insert into test.t_3 values (1,'1',1,1),(2,'2',2,2);
+
+mysql> alter table test.t_3 set tiflash replica 1;
+
+mysql> select * from test.t_3;
```
Comment (JaySon-Huang) [inline tests/fullstack-test-dt/clustered_index/ddl.test:81]:
```suggestion
mysql> set session tidb_isolation_read_engines='tiflash';select * from test.t_3;
```

File: tests/fullstack-test-dt/clustered_index/ddl.test [hunk 5]
```diff
@@ -66,3 +66,87 @@ mysql> set session tidb_isolation_read_engines='tiflash'; select * from test.t_2
...
++---+---+---+---+
+| A | B | C | D |
++---+---+---+---+
+| 1 | 1 | 1 | 1 |
+| 2 | 2 | 2 | 2 |
++---+---+---+---+
+
+mysql> alter table test.t_3 drop column B;
+
+mysql> select * from test.t_3;
```
Comment (JaySon-Huang) [inline tests/fullstack-test-dt/clustered_index/ddl.test:91]:
```suggestion
mysql> set session tidb_isolation_read_engines='tiflash';select * from test.t_3;
```

File: tests/fullstack-test-dt/clustered_index/ddl.test [hunk 6]
```diff
@@ -66,3 +66,87 @@ mysql> set session tidb_isolation_read_engines='tiflash'; select * from test.t_2
...
+| A | C | D |
++---+---+---+
+| 1 | 1 | 1 |
+| 2 | 2 | 2 |
++---+---+---+
+
+# insert some rows
+mysql> insert into test.t_3 values (3,3,3),(4,4,4);
+
+mysql> select * from test.t_3;
```
Comment (JaySon-Huang) [inline tests/fullstack-test-dt/clustered_index/ddl.test:102]:
```suggestion
mysql> set session tidb_isolation_read_engines='tiflash';select * from test.t_3;
```

File: tests/fullstack-test-dt/clustered_index/ddl.test [hunk 7]
```diff
@@ -66,3 +66,87 @@ mysql> set session tidb_isolation_read_engines='tiflash'; select * from test.t_2
...
+
+### add the column between two columns that are cluster index columns 
+mysql> drop table if exists test.t_4
+mysql> create table test.t_4 (A int, B varchar(20), C int, D int, PRIMARY KEY(A,C) CLUSTERED);
+
+mysql> insert into test.t_4 values (1,'1',1,1),(2,'2',2,2);
+
+mysql> alter table test.t_4 set tiflash replica 1;
+
+mysql> select * from test.t_4;
```
Comment (JaySon-Huang) [inline tests/fullstack-test-dt/clustered_index/ddl.test:122]:
```suggestion
mysql> set session tidb_isolation_read_engines='tiflash';select * from test.t_4;
```

File: tests/fullstack-test-dt/clustered_index/ddl.test [hunk 8]
```diff
@@ -66,3 +66,87 @@ mysql> set session tidb_isolation_read_engines='tiflash'; select * from test.t_2
...
++---+---+---+---+
+| A | B | C | D |
++---+---+---+---+
+| 1 | 1 | 1 | 1 |
+| 2 | 2 | 2 | 2 |
++---+---+---+---+
+
+mysql> alter table test.t_4 Add column E int after B;
+
+mysql> select * from test.t_4;
```
Comment (JaySon-Huang) [inline tests/fullstack-test-dt/clustered_index/ddl.test:132]:
```suggestion
mysql> set session tidb_isolation_read_engines='tiflash';select * from test.t_4;
```

File: tests/fullstack-test-dt/clustered_index/ddl.test [hunk 9]
```diff
@@ -66,3 +66,87 @@ mysql> set session tidb_isolation_read_engines='tiflash'; select * from test.t_2
...
++---+---+------+---+---+
+| A | B |  E   | C | D |
++---+---+------+---+---+
+| 1 | 1 | NULL | 1 | 1 |
+| 2 | 2 | NULL | 2 | 2 |
++---+---+------+---+---+
+
+mysql> insert into test.t_4 values (3,'3',3,3,3),(4,'4',4,4,4);
+
+mysql> select * from test.t_4;
```
Comment (JaySon-Huang) [inline tests/fullstack-test-dt/clustered_index/ddl.test:142]:
```suggestion
mysql> set session tidb_isolation_read_engines='tiflash';select * from test.t_4;
```

**Review by JaySon-Huang — COMMENTED** [review]
You have to set the session variable for each line you want the query is executed by tiflash. Cause each line will start a new session to tidb.

File: dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h [hunk 10]
```diff
@@ -100,10 +102,14 @@ struct DecodingStorageSchemaSnapshot
...
-            for (size_t i = 0; i < primary_index_info.idx_cols.size(); i++)
+            /// we will not update the IndexInfo except Rename DDL.
+            /// When the add column / drop column action happenes, the offset of each column may change
+            /// Thus, we should not use offset to get the column we want,
+            /// but use to compare the column name to get the column id.
+            const auto & primary_index_cols = table_info_.getPrimaryIndexInfo().idx_cols;
+            for (const auto & col : primary_index_cols)
             {
-                auto pk_column_id = table_info_.columns[primary_index_info.idx_cols[i].offset].id;
+                auto pk_column_id = column_name_id_map[col.name];
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h:112]: Maybe add a simple unittest for this test case:

* Parse tidb table info from a json string
* Get the `DecodingStorageSchemaSnapshot` by using `getDecodingStorageSchemaSnapshot` from tidb table info
* Check the member `pk_column_ids`, `pk_pos_map` etc

**Comment by JaySon-Huang** [comment]
Change the field `Release note` in the PR description to be "Fix the TiFlash crash issue that occurs after dropping a column of a table with clustered indexes under some situations"
The docs team will collect the information into the release note of the fixed version in PingCAP official website

File: dbms/src/Storages/Transaction/tests/gtest_decoding_storage_schema_snapshot.cpp [hunk 11]
```diff
@@ -0,0 +1,44 @@
...
+
+#include "RowCodecTestUtils.h"
+
+namespace DB::tests
+{
+static TableInfo getTableInfoByJson(const String & json_table_info)
+{
+    return TableInfo(json_table_info);
+}
+TEST(DecodingStorageSchemaSnapshotTest, CheckPKInfosUnderClusteredIndex)
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Transaction/tests/gtest_decoding_storage_schema_snapshot.cpp:27]: Add one more case in this PR https://github.com/hongyunyan/tiflash/pull/1, please check & merge the pr into your branch

File: dbms/src/Storages/Transaction/RegionBlockReader.cpp [hunk 12]
```diff
@@ -208,6 +208,7 @@ bool RegionBlockReader::readImpl(Block & block, const RegionDataReadInfoList & d
         }
         index++;
     }
+    block.checkNumberOfRows();
```
[the remark this answers is not in the document]
Comment (JaySon-Huang) [reply dbms/src/Storages/Transaction/RegionBlockReader.cpp:211]: `checkNumberOfRows` just iterate all columns and check the size of each column, I think the overhead is small.
But yes, a benchmark result is better.

[the remark this answers is not in the document]
Comment (flowbehappy) [reply dbms/src/Storages/Transaction/RegionBlockReader.cpp:211]: I think we can create a microbenchmark to show the performance impact. i.e. a function running many rounds of `readImpl`.

[the remark this answers is not in the document]
Comment (hongyunyan) [reply dbms/src/Storages/Transaction/RegionBlockReader.cpp]: I add a microbenchmark in bench_region_block_reader.cpp, which test the decode time with/without check under PKIsHandle/CommonHandle/PKIsNotHandle. I simulate the case with 100 rows and 6 columns, and run each case 1000 iters. The benchmark result shows the checkNumberOfRows only take very low percentage. Thus, I think we can add the checkNumberOfRows here.

Please look at the last four lines of these two figures, as the test in the first position will always take up additional overhead, thus we change the position to make these two tests.

image

image

[the remark this answers is not in the document]
Comment (hongyunyan) [reply dbms/src/Storages/Transaction/RegionBlockReader.cpp]: performance with decoding different rows
image

**Review by lidezhu — APPROVED** [review]
LGTM

File: dbms/src/Storages/Transaction/RegionBlockReader.cpp [hunk 13]
```diff
@@ -208,6 +208,11 @@ bool RegionBlockReader::readImpl(Block & block, const RegionDataReadInfoList & d
         }
         index++;
     }
+    if (with_check)
```
Comment (hongyunyan) [inline dbms/src/Storages/Transaction/RegionBlockReader.cpp:211]: should I remove the boolean variable `with_check` and remove the benchmark test now?

Comment (lidezhu) [reply dbms/src/Storages/Transaction/RegionBlockReader.cpp:211]: I think `with_check` can be removed. And the benchmark test can be kept just for the future use(no need to compare the WithCheck and WithOutCheck version).

**Review by flowbehappy — APPROVED** [review]

**Review by flowbehappy — APPROVED** [review]
