### PR TITLE
Fix `alloc_bytes` of ReadLimiter

### LINKED ISSUE #5801: Unexpected pending task by io limiter
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

TiFlash runs on ebs (2 nodes, 8vc, 287MB/s). Workload is ch-benchmark. Run AP queries after data import.

### 3. What did you see instead (Required)
Although the IO throughput is small, the fgread task is pending.
image

### 4. What is your TiFlash version? (Required)
v6.2.0

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #5801 

Problem Summary:
1. The calculation of `alloc_bytes` is not right when the burst read traffic exceeds the limit and results in the I/O limiter-tuner not working well. 
2. After the burst read traffic exceeds the limit, the `available_balance` is negative (overdrawn), `refillAndAlloc` will refresh it periodically. However, ReadLimiter may not be called for a long time and refillAndAlloc will not be called either.

### What is changed and how it works?

**Before this PR**:
image

**Include this PR:**
image

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Encryption/RateLimiter.cpp [hunk 1]
```diff
@@ -191,6 +210,7 @@ void WriteLimiter::request(Int64 bytes)
             }
         }
     }
+    LOG_FMT_DEBUG(log, "pending_us {} wait_times {} pending_count {} rate_limit_per_sec {}", sw_pending.elapsed() / 1000, wait_times, req_queue.size(), refill_balance_per_period * 1000 / refill_period_ms);
```
Comment (flowbehappy) [inline dbms/src/Encryption/RateLimiter.cpp:213]: This is too chatty. Use trace please.

Comment (flowbehappy) [reply dbms/src/Encryption/RateLimiter.cpp:213]: And perhaps report to grafana if neccesary?

File: dbms/src/Encryption/RateLimiter.cpp [hunk 2]
```diff
@@ -338,10 +362,24 @@ bool ReadLimiter::canGrant([[maybe_unused]] Int64 bytes)
...
+        UInt64 elapsed_ms = std::chrono::duration_cast<std::chrono::milliseconds>(elapsed_duration).count();
+        // At least refill one time.
+        Int64 max_refill_times = std::max(elapsed_ms, refill_period_ms) / refill_period_ms;
+        Int64 max_refill_bytes = max_refill_times * refill_balance_per_period;
+        alloc_bytes += std::min(-available_balance, max_refill_bytes);
+        available_balance = std::min(available_balance + max_refill_bytes, refill_balance_per_period);
     }
+    else
+    {
+        available_balance = refill_balance_per_period;
```
Comment (flowbehappy) [inline dbms/src/Encryption/RateLimiter.cpp:380]: Does here fix the issue "The calculation of alloc_bytes is not right when the burst read traffic exceeds the limit and results in the I/O limiter-tuner not working well." ?

**Review by flowbehappy — APPROVED** [review]
