### PR TITLE
Fix minor compaction after restart

### LINKED ISSUE #6159: Minor compaction does not work as expected
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

The logs from https://asktug.com/t/topic/994062/22

The minor compaction only compact the last two column file into one column file with 4 rows, leaving other compaction files in level 0 not merged
And move these files into level 1.

Lots of delta leaving column files unmerged, finally there are more than 32,764,491 pages on one PageStorage (`__global__.log`) instance and cause OOM. The `db/page/log/wal/log_xxx_1` take about 7.1 GB.

```
[2022/10/17 09:08:14.742 +08:00] [DEBUG] [ColumnFilePersistedSet.cpp:400] ["ColumnFilePersistedSet:ColumnFilePersistedSet [42]: 1 levels, 512 column files, 29903 rows, 7975015 bytes, 0 deletes., before commit compaction, level info:
[0]: [T_2049,T_2048,T_319,T_1,T_226,T_115,T_58,T_27,T_2,T_3453,T_3580,T_439,T_1,T_1,T_2,T_1,T_2,T_3,T_1,T_2,T_2,T_2,T_1,T_1,T_3515,T_3513,T_1793,T_465,T_33,T_13,T_1,T_231,T_62,T_28,T_1,T_1,T_2,T_2,T_1,T_1,T_1738,T_109,T_1,T_1,T_2,T_1,T_1,T_2,T_214,T_26,T_108,T_30,T_1,T_2,T_1,T_1,T_1,T_1,T_14,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_54,T_1,T_1,T_1,T_1,T_17,T_1,T_2,T_1,T_1,T_2,T_1,T_1,T_2,T_1,T_4,T_15,T_1,T_1,T_1,T_2,T_1,T_1,T_3,T_1,T_2,T_17,T_1,T_1,T_4,T_2,T_1,T_2,T_3,T_1,T_2,T_1,T_2,T_2,T_1,T_1,T_1,T_2,T_1,T_5,T_2,T_5,T_21,T_23,T_16,T_2,T_9,T_14,T_1,T_7,T_5,T_8,T_21,T_6,T_20,T_2,T_5,T_7,T_3,T_6,T_2,T_4,T_1,T_2,T_2,T_6,T_2,T_124,T_31,T_109,T_60,T_13,T_2,T_14,T_2,T_1,T_2,T_1,T_1,T_1,T_1,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_1,T_1,T_2,T_1,T_2,T_2,T_1,T_62,T_28,T_2,T_1,T_3,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_1,T_1,T_1,T_1,T_1,T_29,T_1,T_1,T_2,T_1,T_1,T_1,T_1,T_1,T_2,T_2,T_2,T_1,T_2,T_1,T_1,T_2,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_1,T_2,T_1,T_3,T_2,T_2,T_2,T_2,T_1,T_1,T_27,T_1,T_1,T_3,T_1,T_1,T_1,T_1,T_2,T_17,T_1,T_2,T_2,T_16,T_1,T_1,T_1,T_1,T_1,T_1,T_21,T_1,T_1,T_1,T_1,T_3,T_1,T_2,T_1,T_3,T_1,T_2,T_1,T_1,T_1,T_1,T_1,T_4,T_1,T_1,T_1,T_2,T_3,T_1,T_1,T_1,T_2,T_1,T_4,T_11,T_6,T_23,T_443,T_108,T_53,T_38,T_16,T_1,T_2,T_1,T_1,T_2,T_1,T_2,T_2,T_1,T_2,T_16,T_1,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_1,T_1,T_1,T_12,T_1,T_1,T_1,T_117,T_32,T_14,T_1,T_1,T_115,T_27,T_11,T_105,T_12,T_1,T_1,T_1,T_1,T_1,T_1,T_1785,T_428,T_110,T_14,T_106,T_17,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_2,T_14,T_2,T_1,T_2,T_2,T_49,T_26,T_14,T_2,T_3,T_1,T_3,T_3,T_1,T_26,T_1,T_1,T_1,T_2,T_1,T_1,T_1,T_16,T_15,T_1,T_1,T_1,T_1,T_3,T_1,T_1,T_1,T_1,T_55,T_28,T_1,T_1,T_2,T_1,T_1,T_3,T_33,T_1,T_1,T_1,T_2,T_1,T_1,T_1,T_1,T_14,T_1,T_4,T_1,T_2,T_1,T_1,T_1,T_1,T_2,T_1,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_2,T_4,T_1,T_4,T_2,T_1,T_1,T_2,T_1,T_2,T_1,T_2,T_1,T_1,T_1,T_2,T_1,T_1,T_3,T_1,T_1,T_1,T_1,T_4,T_1,T_2,T_4,T_4,T_3,T_2,T_8,T_39,T_1,T_2,T_6,T_8,T_1,T_1,T_9,T_1,T_3,T_1,T_4,T_4,T_1,T_1,T_5,T_7,T_11,T_5,T_5,T_3,T_9,T_3,T_2,T_1,T_5,T_11,T_2,T_2,T_6,T_1,T_4,T_4,T_3,T_7,T_3,T_4,T_3,T_31,T_13,T_16,T_2,T_1,T_2,T_3,T_5,T_9,T_9,T_4,T_1,T_4,T_18,T_7,T_8,T_3,T_26,T_2,T_7,T_20,T_7,T_6,T_2,T_15,T_7,T_4,T_2,T_1,T_1,T_2,T_2,T_2,T_2,T_1,T_1,T_6,T_2,T_4,T_3,T_2,T_1,T_2,T_3,T_1]"] [thread_id=34]

[2022/10/17 09:08:14.751 +08:00] [DEBUG] [ColumnFilePersistedSet.cpp:469] ["ColumnFilePersistedSet:ColumnFilePersistedSet [42]: 2 levels, 511 column files, 29903 rows, 7975015 bytes, 0 deletes., after commit compaction, level info:
[0]: []
[1]: [T_2049,T_2048,T_319,T_1,T_226,T_115,T_58,T_27,T_2,T_3453,T_3580,T_439,T_1,T_1,T_2,T_1,T_2,T_3,T_1,T_2,T_2,T_2,T_1,T_1,T_3515,T_3513,T_1793,T_465,T_33,T_13,T_1,T_231,T_62,T_28,T_1,T_1,T_2,T_2,T_1,T_1,T_1738,T_109,T_1,T_1,T_2,T_1,T_1,T_2,T_214,T_26,T_108,T_30,T_1,T_2,T_1,T_1,T_1,T_1,T_14,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_54,T_1,T_1,T_1,T_1,T_17,T_1,T_2,T_1,T_1,T_2,T_1,T_1,T_2,T_1,T_4,T_15,T_1,T_1,T_1,T_2,T_1,T_1,T_3,T_1,T_2,T_17,T_1,T_1,T_4,T_2,T_1,T_2,T_3,T_1,T_2,T_1,T_2,T_2,T_1,T_1,T_1,T_2,T_1,T_5,T_2,T_5,T_21,T_23,T_16,T_2,T_9,T_14,T_1,T_7,T_5,T_8,T_21,T_6,T_20,T_2,T_5,T_7,T_3,T_6,T_2,T_4,T_1,T_2,T_2,T_6,T_2,T_124,T_31,T_109,T_60,T_13,T_2,T_14,T_2,T_1,T_2,T_1,T_1,T_1,T_1,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_1,T_1,T_2,T_1,T_2,T_2,T_1,T_62,T_28,T_2,T_1,T_3,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_1,T_1,T_1,T_1,T_1,T_29,T_1,T_1,T_2,T_1,T_1,T_1,T_1,T_1,T_2,T_2,T_2,T_1,T_2,T_1,T_1,T_2,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_1,T_2,T_1,T_3,T_2,T_2,T_2,T_2,T_1,T_1,T_27,T_1,T_1,T_3,T_1,T_1,T_1,T_1,T_2,T_17,T_1,T_2,T_2,T_16,T_1,T_1,T_1,T_1,T_1,T_1,T_21,T_1,T_1,T_1,T_1,T_3,T_1,T_2,T_1,T_3,T_1,T_2,T_1,T_1,T_1,T_1,T_1,T_4,T_1,T_1,T_1,T_2,T_3,T_1,T_1,T_1,T_2,T_1,T_4,T_11,T_6,T_23,T_443,T_108,T_53,T_38,T_16,T_1,T_2,T_1,T_1,T_2,T_1,T_2,T_2,T_1,T_2,T_16,T_1,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_1,T_1,T_1,T_12,T_1,T_1,T_1,T_117,T_32,T_14,T_1,T_1,T_115,T_27,T_11,T_105,T_12,T_1,T_1,T_1,T_1,T_1,T_1,T_1785,T_428,T_110,T_14,T_106,T_17,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_2,T_14,T_2,T_1,T_2,T_2,T_49,T_26,T_14,T_2,T_3,T_1,T_3,T_3,T_1,T_26,T_1,T_1,T_1,T_2,T_1,T_1,T_1,T_16,T_15,T_1,T_1,T_1,T_1,T_3,T_1,T_1,T_1,T_1,T_55,T_28,T_1,T_1,T_2,T_1,T_1,T_3,T_33,T_1,T_1,T_1,T_2,T_1,T_1,T_1,T_1,T_14,T_1,T_4,T_1,T_2,T_1,T_1,T_1,T_1,T_2,T_1,T_1,T_1,T_1,T_1,T_1,T_2,T_1,T_2,T_4,T_1,T_4,T_2,T_1,T_1,T_2,T_1,T_2,T_1,T_2,T_1,T_1,T_1,T_2,T_1,T_1,T_3,T_1,T_1,T_1,T_1,T_4,T_1,T_2,T_4,T_4,T_3,T_2,T_8,T_39,T_1,T_2,T_6,T_8,T_1,T_1,T_9,T_1,T_3,T_1,T_4,T_4,T_1,T_1,T_5,T_7,T_11,T_5,T_5,T_3,T_9,T_3,T_2,T_1,T_5,T_11,T_2,T_2,T_6,T_1,T_4,T_4,T_3,T_7,T_3,T_4,T_3,T_31,T_13,T_16,T_2,T_1,T_2,T_3,T_5,T_9,T_9,T_4,T_1,T_4,T_18,T_7,T_8,T_3,T_26,T_2,T_7,T_20,T_7,T_6,T_2,T_15,T_7,T_4,T_2,T_1,T_1,T_2,T_2,T_2,T_2,T_1,T_1,T_6,T_2,T_4,T_3,T_2,T_1,T_2,T_4]"] [thread_id=34]
[2022/10/17 09:08:14.751 +08:00] [DEBUG] [DeltaValueSpace.cpp:278] ["DeltaValueSpace:Delta [42] Compacted 2 column files into 1 column files, total 4 rows."] [thread_id=34]
[2022/10/17 09:08:14.763 +08:00] [DEBUG] [DeltaMergeStore.cpp:141] ["DeltaMergeStore:db_698.t_704 Segment [41] task [Compact] add to background task pool by [BG_Compact]"] [thread_id=34]
```

### 4. What is your TiFlash version? (Required)
v6.2.0

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #6159 

Problem Summary:
1. When do serialization for `ColumnFileTiny`, we can avoid serialize the schema info if it share the same schema with previous `ColumnFileTiny`. But actually we fail to do that, so after restart all `ColumnFileTiny` has its own schema object and cannot be compacted together.
2. If there is write during segment update, the `MemTableSet` in the new segment will have a wrong `last_schema` which will make some influence on the schema share between column files.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the problem that column files in delta layer cannot be compacted after restart tiflash
```

### CODE REVIEW

File: dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp [hunk 1]
```diff
@@ -457,6 +457,58 @@ try
...
+        ingestDTFileIntoSegment(DELTA_MERGE_FIRST_SEGMENT_ID, 100);
+        writeSegment(DELTA_MERGE_FIRST_SEGMENT_ID, 100);
+    }
+    ASSERT_EQ(segments.size(), 1);
+    {
+        auto segment = segments[DELTA_MERGE_FIRST_SEGMENT_ID];
+        auto delta = segment->getDelta();
+        auto mem_table_set = delta->getMemTableSet();
+        WriteBatches wbs(dm_context->storage_pool);
+        auto column_files = mem_table_set->cloneColumnFiles(*dm_context, segment->getRowKeyRange(), wbs);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp:497]:
```suggestion
        auto column_files = mem_table_set->cloneColumnFiles(*dm_context, segment->getRowKeyRange(), wbs);
        ASSERT_FALSE(column_files.empty());
```

File: dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp [hunk 2]
```diff
@@ -457,6 +457,58 @@ try
...
+        BlockPtr last_schema;
+        for (const auto & column_file : column_files)
+        {
+            if (auto * t_file = column_file->tryToTinyFile(); t_file)
+            {
+                auto current_schema = t_file->getSchema();
+                ASSERT_TRUE(!last_schema || (last_schema == current_schema));
+                last_schema = current_schema;
+            }
+        }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp:507]:
```suggestion
        }
        // check last_schema is not nullptr after all
        ASSERT_NE(last_schema, nullptr);
```

**Review by JaySon-Huang — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]
