### PR TITLE
KVStore: introduce flexible region format

### LINKED ISSUE #8590: Use flexible format when persisting Region
## Enhancement

The format of region is currently
```
|-------------------------|
|      Region Meta        |
| Extra Region Meta Flag  |
|    Extra Region Meta    |
|       Region Data       |
|-------------------------|
```
We are going to change it to what we called **"flexible"** format.
```
|-------------------------|
|      Region Meta        |
|         flag 1          |
|        length 1         |
|        payload 1        |
|         flag 2          |
|        length 2         |
|        payload 2        |
|   ..................    |
|       Region Data       |
|-------------------------|
```

We will support several special extensions:
1. EagerTruncate is a compatibility for previous `HAS_EAGER_TRUNCATE_INDEX`. It will have no length field.
2. Finished should be the last flag of the whole extensions, when parsed, the extension flags parser will stop parsing, and hand over read buffer to RegionData parser.
3. Unrecognizable means the flag is not recognizable. It is because the flag is written from a cluster with newer version.

Some other changes:
1. We will not check if the read storage version is below current version after V3

### Benefits

Currently, we use bits from a UInt32 to mark configurations from extensions like eager gc on serverless clusters, and this strategy raises the following problems:
1. In further development of TiFlash, the 32 bits can only stand for 32 features, and it potentially to be used up. In order to mitigate this problem, a solution is to introduce the 31st bit as an extension mark which indicates to read some following structures for other extension feature data. However, it is hard to choose the pattern of "following structures". Should it be 32bit? Then what if it's used up again? Should it be 32kb? Does it waste too much? Should we use flexible format? Then why don't we use it directly now?
4. Consider downgrading. We may meet some unrecognized flags. There are two ways to fix this. One way it to move the "Extra Region Meta" stuff to behind RegionData, and read until the first unrecognized flag, and then stop reading, discard all rest data. This also relies on we use allocate bits from LSB to MSB. The other way it to change it to flexible format, with some compation we will talk later.
5. Consider we will deprecate some features in later version. If we use flexible format, we can only clean the data once, and persist region without the flag. Then we will get rid of this struct forever.
6. Consider we have many features, some are exclusive to serverless mode, some are exclusive to op mode. For example, we introduced an op-exclusive mode B after the eager gc feature which is only useful in serverless mode. When parsing feature B, we will have to parse feature A first. It won't cost too much, but is awful.

### LINKED ISSUE #8624: ThreadSanitizer detect potential deadlock in AsyncTasksTest
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)
https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/1613/pipeline/

/tiflash/gtests_dbms RegionKVStoreOldTest.ReadIndex
/tiflash/gtests_dbms AsyncTasksTest.AsyncTasksNormal
/tiflash/gtests_dbms RegionKVStoreV2Test.KVStoreSingleSnap4

```
[2023-12-28T18:33:49.691Z] [0;33mNote: Google Test filter = AsyncTasksTest.AsyncTasksNormal
[2023-12-28T18:33:49.691Z] [m[0;32m[==========] [mRunning 1 test from 1 test case.
[2023-12-28T18:33:49.691Z] [0;32m[----------] [mGlobal test environment set-up.
[2023-12-28T18:33:49.691Z] [0;32m[----------] [m1 test from AsyncTasksTest
[2023-12-28T18:33:49.691Z] [0;32m[ RUN      ] [mAsyncTasksTest.AsyncTasksNormal
[2023-12-28T18:33:49.691Z] [2023/12/29 02:33:45.464 +08:00] [INFO] [gtests_async_tasks.cpp:29] ["Cancel and addTask"] [thread_id=1]
[2023-12-28T18:33:49.691Z] [2023/12/29 02:33:45.466 +08:00] [INFO] [AsyncTasks.h:56] ["Pending 0 tasks when destructing"] [thread_id=1]
[2023-12-28T18:33:49.691Z] [2023/12/29 02:33:45.466 +08:00] [INFO] [gtests_async_tasks.cpp:56] ["Lifetime of tasks"] [thread_id=1]
[2023-12-28T18:33:49.691Z] [2023/12/29 02:33:45.466 +08:00] [DEBUG] [Ctl.cpp:34] ["Enabled: after_AsyncTasks::addTask_scheduled"] [source=SyncPointCtl] [thread_id=1]
[2023-12-28T18:33:49.691Z] [2023/12/29 02:33:45.466 +08:00] [DEBUG] [Ctl.cpp:34] ["Enabled: before_AsyncTasks::addTask_quit"] [source=SyncPointCtl] [thread_id=1]
[2023-12-28T18:33:49.692Z] [2023/12/29 02:33:45.467 +08:00] [DEBUG] [Ctl.cpp:69] ["waitAndPause(after_AsyncTasks::addTask_scheduled) waiting..."] [source=SyncPointCtl] [thread_id=98]
[2023-12-28T18:33:49.692Z] [2023/12/29 02:33:45.468 +08:00] [DEBUG] [Ctl.cpp:69] ["waitAndPause(before_AsyncTasks::addTask_quit) waiting..."] [source=SyncPointCtl] [thread_id=99]
[2023-12-28T18:33:49.692Z] [2023/12/29 02:33:46.208 +08:00] [DEBUG] [Ctl.cpp:86] ["SYNC_FOR(after_AsyncTasks::addTask_scheduled) trying... \n\n# Current Stack: \n       0x2bbc38b\t__interceptor_backtrace [gtests_dbms+45859723]\n                \t/llvm-project/compiler-rt/lib/tsan/../sanitizer_common/sanitizer_common_interceptors.inc:4202\n       0xfaba740\tStackTrace::StackTrace() [gtests_dbms+262907712]\n                \tdbms/src/Common/StackTrace.cpp:23\n       0xfb4fef1\tDB::SyncPointCtl::sync(char const*) [gtests_dbms+263519985]\n                \tdbms/src/Common/SyncPoint/Ctl.cpp:86\n       0x5b00925\tDB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>) [gtests_dbms+95422757]\n                \tdbms/src/Storages/KVStore/Utils/AsyncTasks.h:274\n       0x5affa19\tDB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTask(unsigned long, std::__1::function<void ()>) [gtests_dbms+95418905]\n                \tdbms/src/Storages/KVStore/Utils/AsyncTasks.h:285\n       0x5af6543\tDB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody() [gtests_dbms+95380803]\n                \tdbms/src/Storages/KVStore/tests/gtests_async_tasks.cpp:75\n       0xc41fbd6\tvoid testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+205650902]\n                \tcontrib/googletest/googletest/src/gtest.cc:2479\n       0xc3f9776\ttesting::Test::Run() [gtests_dbms+205494134]\n                \tcontrib/googletest/googletest/src/gtest.cc:2517\n       0xc3fafa5\ttesting::TestInfo::Run() [gtests_dbms+205500325]\n                \tcontrib/googletest/googletest/src/gtest.cc:2693\n       0xc3fbc6e\ttesting::TestCase::Run() [gtests_dbms+205503598]\n                \tcontrib/googletest/googletest/src/gtest.cc:2811\n       0xc40be21\ttesting::internal::UnitTestImpl::RunAllTests() [gtests_dbms+205569569]\n                \tcontrib/googletest/googletest/src/gtest.cc:5177\n       0xc421076\tbool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+205656182]\n                \tcontrib/googletest/googletest/src/gtest.cc:2479\n       0xc40b109\ttesting::UnitTest::Run() [gtests_dbms+205566217]\n                \tcontrib/googletest/googletest/src/gtest.cc:4786\n       0x5fd310f\tmain [gtests_dbms+100479247]\n                \tdbms/src/TestUtils/gtests_dbms_main.cpp:116\n  0x7fbf10532555\t__libc_start_main [libc.so.6+140629]\n       0x2b751a9\t<unknown symbol> [gtests_dbms+45568425]"] [source=SyncPointCtl] [thread_id=1]
[2023-12-28T18:33:49.692Z] [2023/12/29 02:33:46.208 +08:00] [DEBUG] [Ctl.cpp:92] ["SYNC_FOR(after_AsyncTasks::addTask_scheduled) matched waitAndPause(), paused until calling next()..."] [source=SyncPointCtl] [thread_id=1]
[2023-12-28T18:33:49.692Z] [2023/12/29 02:33:46.208 +08:00] [DEBUG] [Ctl.cpp:71] ["waitAndPause(after_AsyncTasks::addTask_scheduled) finished"] [source=SyncPointCtl] [thread_id=98]
[2023-12-28T18:33:49.693Z] [2023/12/29 02:33:46.208 +08:00] [DEBUG] [Ctl.cpp:77] ["next(after_AsyncTasks::addTask_scheduled) trying..."] [source=SyncPointCtl] [thread_id=98]
[2023-12-28T18:33:49.693Z] [2023/12/29 02:33:46.208 +08:00] [DEBUG] [Ctl.cpp:96] ["SYNC_FOR(after_AsyncTasks::addTask_scheduled) done"] [source=SyncPointCtl] [thread_id=1]
[2023-12-28T18:33:49.693Z] [2023/12/29 02:33:46.208 +08:00] [DEBUG] [Ctl.cpp:79] ["next(after_AsyncTasks::addTask_scheduled) done"] [source=SyncPointCtl] [thread_id=98]
[2023-12-28T18:33:49.693Z] [2023/12/29 02:33:46.208 +08:00] [DEBUG] [Ctl.cpp:50] ["Disabled: after_AsyncTasks::addTask_scheduled"] [source=SyncPointCtl] [thread_id=98]
[2023-12-28T18:33:49.693Z] [2023/12/29 02:33:46.209 +08:00] [DEBUG] [Ctl.cpp:86] ["SYNC_FOR(before_AsyncTasks::addTask_quit) trying... \n\n# Current Stack: \n       0x2bbc38b\t__interceptor_backtrace [gtests_dbms+45859723]\n                \t/llvm-project/compiler-rt/lib/tsan/../sanitizer_common/sanitizer_common_interceptors.inc:4202\n       0xfaba740\tStackTrace::StackTrace() [gtests_dbms+262907712]\n                \tdbms/src/Common/StackTrace.cpp:23\n       0xfb4fef1\tDB::SyncPointCtl::sync(char const*) [gtests_dbms+263519985]\n                \tdbms/src/Common/SyncPoint/Ctl.cpp:86\n       0x5b00a57\tDB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>) [gtests_dbms+95423063]\n                \tdbms/src/Storages/KVStore/Utils/AsyncTasks.h:279\n       0x5affa19\tDB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTask(unsigned long, std::__1::function<void ()>) [gtests_dbms+95418905]\n                \tdbms/src/Storages/KVStore/Utils/AsyncTasks.h:285\n       0x5af6543\tDB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody() [gtests_dbms+95380803]\n                \tdbms/src/Storages/KVStore/tests/gtests_async_tasks.cpp:75\n       0xc41fbd6\tvoid testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+205650902]\n                \tcontrib/googletest/googletest/src/gtest.cc:2479\n       0xc3f9776\ttesting::Test::Run() [gtests_dbms+205494134]\n                \tcontrib/googletest/googletest/src/gtest.cc:2517\n       0xc3fafa5\ttesting::TestInfo::Run() [gtests_dbms+205500325]\n                \tcontrib/googletest/googletest/src/gtest.cc:2693\n       0xc3fbc6e\ttesting::TestCase::Run() [gtests_dbms+205503598]\n                \tcontrib/googletest/googletest/src/gtest.cc:2811\n       0xc40be21\ttesting::internal::UnitTestImpl::RunAllTests() [gtests_dbms+205569569]\n                \tcontrib/googletest/googletest/src/gtest.cc:5177\n       0xc421076\tbool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+205656182]\n                \tcontrib/googletest/googletest/src/gtest.cc:2479\n       0xc40b109\ttesting::UnitTest::Run() [gtests_dbms+205566217]\n                \tcontrib/googletest/googletest/src/gtest.cc:4786\n       0x5fd310f\tmain [gtests_dbms+100479247]\n                \tdbms/src/TestUtils/gtests_dbms_main.cpp:116\n  0x7fbf10532555\t__libc_start_main [libc.so.6+140629]\n       0x2b751a9\t<unknown symbol> [gtests_dbms+45568425]"] [source=SyncPointCtl] [thread_id=1]
[2023-12-28T18:33:49.694Z] [2023/12/29 02:33:46.209 +08:00] [DEBUG] [Ctl.cpp:92] ["SYNC_FOR(before_AsyncTasks::addTask_quit) matched waitAndPause(), paused until calling next()..."] [source=SyncPointCtl] [thread_id=1]
[2023-12-28T18:33:49.694Z] [2023/12/29 02:33:46.209 +08:00] [DEBUG] [Ctl.cpp:71] ["waitAndPause(before_AsyncTasks::addTask_quit) finished"] [source=SyncPointCtl] [thread_id=99]
[2023-12-28T18:33:49.694Z] [2023/12/29 02:33:46.209 +08:00] [DEBUG] [Ctl.cpp:77] ["next(before_AsyncTasks::addTask_quit) trying..."] [source=SyncPointCtl] [thread_id=99]
[2023-12-28T18:33:49.694Z] [2023/12/29 02:33:46.209 +08:00] [DEBUG] [Ctl.cpp:79] ["next(before_AsyncTasks::addTask_quit) done"] [source=SyncPointCtl] [thread_id=99]
[2023-12-28T18:33:49.694Z] [2023/12/29 02:33:46.209 +08:00] [DEBUG] [Ctl.cpp:96] ["SYNC_FOR(before_AsyncTasks::addTask_quit) done"] [source=SyncPointCtl] [thread_id=1]
[2023-12-28T18:33:49.694Z] [2023/12/29 02:33:46.209 +08:00] [DEBUG] [Ctl.cpp:50] ["Disabled: before_AsyncTasks::addTask_quit"] [source=SyncPointCtl] [thread_id=99]
[2023-12-28T18:33:49.694Z] [2023/12/29 02:33:46.260 +08:00] [INFO] [AsyncTasks.h:56] ["Pending 1 tasks when destructing"] [thread_id=1]
[2023-12-28T18:33:49.694Z] [2023/12/29 02:33:46.260 +08:00] [INFO] [gtests_async_tasks.cpp:82] ["Cancel in queue"] [thread_id=1]
[2023-12-28T18:33:49.694Z] ==================
[2023-12-28T18:33:49.694Z] WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=467053)
[2023-12-28T18:33:49.694Z]   Cycle in lock order graph: M52569 (0x7ffdc4b02ff8) => M52572 (0x7b10000b7718) => M52569
[2023-12-28T18:33:49.694Z] 
[2023-12-28T18:33:49.694Z]   Mutex M52572 acquired here while holding mutex M52569 in main thread:
[2023-12-28T18:33:49.694Z]     #0 pthread_mutex_lock /llvm-project/compiler-rt/lib/tsan/../sanitizer_common/sanitizer_common_interceptors.inc:4249:3 (gtests_dbms+0x2bbc7d8)
[2023-12-28T18:33:49.694Z]     #1 std::__1::mutex::lock() <null> (libc++.so.1+0x66f45)
[2023-12-28T18:33:49.694Z]     #2 DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTask(unsigned long, std::__1::function<void ()>) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/Utils/AsyncTasks.h:285:16 (gtests_dbms+0x5affa18)
[2023-12-28T18:33:49.694Z]     #3 DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/tests/gtests_async_tasks.cpp:90:34 (gtests_dbms+0x5af6966)
[2023-12-28T18:33:49.694Z]     #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xc41fbd5)
[2023-12-28T18:33:49.694Z]     #5 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xc41fbd5)
[2023-12-28T18:33:49.694Z]     #6 testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5 (gtests_dbms+0xc3f9775)
[2023-12-28T18:33:49.694Z]     #7 testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xc3fafa4)
[2023-12-28T18:33:49.694Z]     #8 testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xc3fbc6d)
[2023-12-28T18:33:49.694Z]     #9 testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xc40be20)
[2023-12-28T18:33:49.694Z]     #10 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xc421075)
[2023-12-28T18:33:49.694Z]     #11 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xc421075)
[2023-12-28T18:33:49.694Z]     #12 testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xc40b108)
[2023-12-28T18:33:49.695Z]     #13 RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x5fd310e)
[2023-12-28T18:33:49.695Z]     #14 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:116:16 (gtests_dbms+0x5fd310e)
[2023-12-28T18:33:49.695Z] 
[2023-12-28T18:33:49.695Z]     Hint: use TSAN_OPTIONS=second_deadlock_stack=1 to get more informative warning message
[2023-12-28T18:33:49.695Z] 
[2023-12-28T18:33:49.695Z]   Mutex M52569 acquired here while holding mutex M52572 in thread T105:
[2023-12-28T18:33:49.695Z]     #0 pthread_mutex_lock /llvm-project/compiler-rt/lib/tsan/../sanitizer_common/sanitizer_common_interceptors.inc:4249:3 (gtests_dbms+0x2bbc7d8)
[2023-12-28T18:33:49.695Z]     #1 std::__1::mutex::lock() <null> (libc++.so.1+0x66f45)
[2023-12-28T18:33:49.695Z]     #2 std::__1::__function::__value_func<void ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:498:16 (gtests_dbms+0x5b042c4)
[2023-12-28T18:33:49.695Z]     #3 std::__1::function<void ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:1175:12 (gtests_dbms+0x5b042c4)
[2023-12-28T18:33:49.695Z]     #4 decltype(static_cast<std::__1::function<void ()>&>(fp)()) std::__1::__invoke<std::__1::function<void ()>&>(std::__1::function<void ()>&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0x5b042c4)
[2023-12-28T18:33:49.695Z]     #5 std::__1::__packaged_task_func<std::__1::function<void ()>, std::__1::allocator<std::__1::function<void ()> >, void ()>::operator()() /usr/local/bin/../include/c++/v1/future:1687:12 (gtests_dbms+0x5b042c4)
[2023-12-28T18:33:49.695Z]     #6 std::__1::__packaged_task_function<void ()>::operator()() const /usr/local/bin/../include/c++/v1/future:1869:12 (gtests_dbms+0x2caa2bd)
[2023-12-28T18:33:49.695Z]     #7 std::__1::packaged_task<void ()>::operator()() /usr/local/bin/../include/c++/v1/future:2089:9 (gtests_dbms+0x2caa2bd)
[2023-12-28T18:33:49.695Z]     #8 DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/Utils/AsyncTasks.h:270:13 (gtests_dbms+0x5b04738)
[2023-12-28T18:33:49.695Z]     #9 decltype(static_cast<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()&>(fp)()) std::__1::__invoke<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()&>(DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0x5b045dd)
[2023-12-28T18:33:49.695Z]     #10 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()&>(DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()&) /usr/local/bin/../include/c++/v1/__functional/invoke.h:61:9 (gtests_dbms+0x5b045dd)
[2023-12-28T18:33:49.695Z]     #11 std::__1::__function::__alloc_func<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'(), std::__1::allocator<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()>, void ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:171:16 (gtests_dbms+0x5b045dd)
[2023-12-28T18:33:49.695Z]     #12 std::__1::__function::__func<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'(), std::__1::allocator<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()>, void ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:345:12 (gtests_dbms+0x5b045dd)
[2023-12-28T18:33:49.695Z]     #13 std::__1::__function::__value_func<void ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:498:16 (gtests_dbms+0xfb14111)
[2023-12-28T18:33:49.695Z]     #14 std::__1::function<void ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:1175:12 (gtests_dbms+0xfb14111)
[2023-12-28T18:33:49.695Z]     #15 DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::worker(std::__1::__list_iterator<DB::ThreadFromGlobalPoolImpl<false>, void*>) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:306:17 (gtests_dbms+0xfb14111)
[2023-12-28T18:33:49.695Z]     #16 bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:160:73 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.695Z]     #17 decltype(static_cast<bool>(fp)()) std::__1::__invoke_constexpr<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()&>(bool&&) /usr/local/bin/../include/c++/v1/type_traits:3924:1 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.696Z]     #18 decltype(auto) std::__1::__apply_tuple_impl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(bool&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) /usr/local/bin/../include/c++/v1/tuple:1536:1 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.696Z]     #19 decltype(auto) std::__1::apply<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(bool&&, std::__1::tuple<>&) /usr/local/bin/../include/c++/v1/tuple:1545:1 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.696Z]     #20 DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'()::operator()() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.h:236:17 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.696Z]     #21 decltype(static_cast<bool>(fp)()) std::__1::__invoke<DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'()&>(bool&&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.696Z]     #22 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'()&>(DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'()&) /usr/local/bin/../include/c++/v1/__functional/invoke.h:61:9 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.696Z]     #23 std::__1::__function::__alloc_func<DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'(), std::__1::allocator<DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'()>, void ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:171:16 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.696Z]     #24 std::__1::__function::__func<DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'(), std::__1::allocator<DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'()>, void ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:345:12 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.696Z]     #25 std::__1::__function::__value_func<void ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:498:16 (gtests_dbms+0xfb1199a)
[2023-12-28T18:33:49.696Z]     #26 std::__1::function<void ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:1175:12 (gtests_dbms+0xfb1199a)
[2023-12-28T18:33:49.696Z]     #27 DB::ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:306:17 (gtests_dbms+0xfb1199a)
[2023-12-28T18:33:49.696Z]     #28 void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:160:73 (gtests_dbms+0xfb153b0)
[2023-12-28T18:33:49.696Z]     #29 decltype(static_cast<void>(fp)()) std::__1::__invoke<void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0xfb153b0)
[2023-12-28T18:33:49.696Z]     #30 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) /usr/local/bin/../include/c++/v1/thread:280:5 (gtests_dbms+0xfb153b0)
[2023-12-28T18:33:49.697Z]     #31 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) /usr/local/bin/../include/c++/v1/thread:291:5 (gtests_dbms+0xfb153b0)
[2023-12-28T18:33:49.697Z] 
[2023-12-28T18:33:49.697Z]   Thread T105 'ThreadPool' (tid=467165, running) created by main thread at:
[2023-12-28T18:33:49.697Z]     #0 pthread_create /llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:977:3 (gtests_dbms+0x2b9f4fd)
[2023-12-28T18:33:49.697Z]     #1 std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) /usr/local/bin/../include/c++/v1/__threading_support:514:10 (gtests_dbms+0xfb14de8)
[2023-12-28T18:33:49.697Z]     #2 std::__1::thread::thread<void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'(), void>(void&&) /usr/local/bin/../include/c++/v1/thread:307:16 (gtests_dbms+0xfb14de8)
[2023-12-28T18:33:49.697Z]     #3 void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:160:35 (gtests_dbms+0xfb10008)
[2023-12-28T18:33:49.697Z]     #4 DB::ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, long, unsigned long, bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:198:5 (gtests_dbms+0xfb17ef4)
[2023-12-28T18:33:49.697Z]     #5 DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.h:219:38 (gtests_dbms+0xfb17ef4)
[2023-12-28T18:33:49.697Z]     #6 bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:160:35 (gtests_dbms+0xfb12b80)
[2023-12-28T18:33:49.697Z]     #7 DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::trySchedule(std::__1::function<void ()>, long, unsigned long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:188:12 (gtests_dbms+0xfb1279a)
[2023-12-28T18:33:49.697Z]     #8 DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/Utils/AsyncTasks.h:273:33 (gtests_dbms+0x5b008c8)
[2023-12-28T18:33:49.697Z]     #9 DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTask(unsigned long, std::__1::function<void ()>) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/Utils/AsyncTasks.h:285:16 (gtests_dbms+0x5affa18)
[2023-12-28T18:33:49.697Z]     #10 DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/tests/gtests_async_tasks.cpp:37:22 (gtests_dbms+0x5af5cfa)
[2023-12-28T18:33:49.697Z]     #11 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xc41fbd5)
[2023-12-28T18:33:49.697Z]     #12 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xc41fbd5)
[2023-12-28T18:33:49.697Z]     #13 testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5 (gtests_dbms+0xc3f9775)
[2023-12-28T18:33:49.697Z]     #14 testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xc3fafa4)
[2023-12-28T18:33:49.697Z]     #15 testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xc3fbc6d)
[2023-12-28T18:33:49.697Z]     #16 testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xc40be20)
[2023-12-28T18:33:49.697Z]     #17 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xc421075)
[2023-12-28T18:33:49.697Z]     #18 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xc421075)
[2023-12-28T18:33:49.698Z]     #19 testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xc40b108)
[2023-12-28T18:33:49.698Z]     #20 RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x5fd310e)
[2023-12-28T18:33:49.698Z]     #21 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:116:16 (gtests_dbms+0x5fd310e)
[2023-12-28T18:33:49.698Z] 
[2023-12-28T18:33:49.698Z] SUMMARY: ThreadSanitizer: lock-order-inversion (potential deadlock) (/usr/local/lib/x86_64-unknown-linux-gnu/libc++.so.1+0x66f45) in std::__1::mutex::lock()
[2023-12-28T18:33:49.698Z] ==================
[2023-12-28T18:33:49.698Z] LLVMSymbolizer: error reading file: No such file or directory
[2023-12-28T18:33:49.698Z] ==================
[2023-12-28T18:33:49.698Z] WARNING: ThreadSanitizer: data race (pid=467053)
[2023-12-28T18:33:49.698Z]   Write of size 1 at 0x7ffdc4b030a0 by thread T105:
[2023-12-28T18:33:49.698Z]     #0 DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody()::$_10::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/tests/gtests_async_tasks.cpp:99:30 (gtests_dbms+0x5afad66)
[2023-12-28T18:33:49.698Z]     #1 decltype(static_cast<DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody()::$_10&>(fp)()) std::__1::__invoke<DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody()::$_10&>(DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody()::$_10&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0x5afad66)
[2023-12-28T18:33:49.698Z]     #2 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody()::$_10&>(DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody()::$_10&) /usr/local/bin/../include/c++/v1/__functional/invoke.h:61:9 (gtests_dbms+0x5afad66)
[2023-12-28T18:33:49.698Z]     #3 std::__1::__function::__alloc_func<DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody()::$_10, std::__1::allocator<DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody()::$_10>, void ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:171:16 (gtests_dbms+0x5afad66)
[2023-12-28T18:33:49.698Z]     #4 std::__1::__function::__func<DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody()::$_10, std::__1::allocator<DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody()::$_10>, void ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:345:12 (gtests_dbms+0x5afad66)
[2023-12-28T18:33:49.698Z]     #5 std::__1::__function::__value_func<void ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:498:16 (gtests_dbms+0x5b04769)
[2023-12-28T18:33:49.698Z]     #6 std::__1::function<void ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:1175:12 (gtests_dbms+0x5b04769)
[2023-12-28T18:33:49.698Z]     #7 DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/Utils/AsyncTasks.h:264:17 (gtests_dbms+0x5b04769)
[2023-12-28T18:33:49.698Z]     #8 decltype(static_cast<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()&>(fp)()) std::__1::__invoke<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()&>(DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0x5b045dd)
[2023-12-28T18:33:49.698Z]     #9 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()&>(DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()&) /usr/local/bin/../include/c++/v1/__functional/invoke.h:61:9 (gtests_dbms+0x5b045dd)
[2023-12-28T18:33:49.698Z]     #10 std::__1::__function::__alloc_func<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'(), std::__1::allocator<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()>, void ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:171:16 (gtests_dbms+0x5b045dd)
[2023-12-28T18:33:49.698Z]     #11 std::__1::__function::__func<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'(), std::__1::allocator<DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>)::'lambda'()>, void ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:345:12 (gtests_dbms+0x5b045dd)
[2023-12-28T18:33:49.698Z]     #12 std::__1::__function::__value_func<void ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:498:16 (gtests_dbms+0xfb14111)
[2023-12-28T18:33:49.699Z]     #13 std::__1::function<void ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:1175:12 (gtests_dbms+0xfb14111)
[2023-12-28T18:33:49.699Z]     #14 DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::worker(std::__1::__list_iterator<DB::ThreadFromGlobalPoolImpl<false>, void*>) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:306:17 (gtests_dbms+0xfb14111)
[2023-12-28T18:33:49.699Z]     #15 bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:160:73 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.699Z]     #16 decltype(static_cast<bool>(fp)()) std::__1::__invoke_constexpr<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()&>(bool&&) /usr/local/bin/../include/c++/v1/type_traits:3924:1 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.699Z]     #17 decltype(auto) std::__1::__apply_tuple_impl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(bool&&, std::__1::tuple<>&, std::__1::__tuple_indices<>) /usr/local/bin/../include/c++/v1/tuple:1536:1 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.699Z]     #18 decltype(auto) std::__1::apply<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()&, std::__1::tuple<>&>(bool&&, std::__1::tuple<>&) /usr/local/bin/../include/c++/v1/tuple:1545:1 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.699Z]     #19 DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'()::operator()() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.h:236:17 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.699Z]     #20 decltype(static_cast<bool>(fp)()) std::__1::__invoke<DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'()&>(bool&&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.699Z]     #21 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'()&>(DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'()&) /usr/local/bin/../include/c++/v1/__functional/invoke.h:61:9 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.699Z]     #22 std::__1::__function::__alloc_func<DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'(), std::__1::allocator<DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'()>, void ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:171:16 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.699Z]     #23 std::__1::__function::__func<DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'(), std::__1::allocator<DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&)::'lambda'()>, void ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:345:12 (gtests_dbms+0xfb1837c)
[2023-12-28T18:33:49.699Z]     #24 std::__1::__function::__value_func<void ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:498:16 (gtests_dbms+0xfb1199a)
[2023-12-28T18:33:49.699Z]     #25 std::__1::function<void ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:1175:12 (gtests_dbms+0xfb1199a)
[2023-12-28T18:33:49.699Z]     #26 DB::ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:306:17 (gtests_dbms+0xfb1199a)
[2023-12-28T18:33:49.699Z]     #27 void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:160:73 (gtests_dbms+0xfb153b0)
[2023-12-28T18:33:49.700Z]     #28 decltype(static_cast<void>(fp)()) std::__1::__invoke<void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0xfb153b0)
[2023-12-28T18:33:49.700Z]     #29 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<>) /usr/local/bin/../include/c++/v1/thread:280:5 (gtests_dbms+0xfb153b0)
[2023-12-28T18:33:49.700Z]     #30 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) /usr/local/bin/../include/c++/v1/thread:291:5 (gtests_dbms+0xfb153b0)
[2023-12-28T18:33:49.700Z] 
[2023-12-28T18:33:49.700Z]   Previous read of size 1 at 0x7ffdc4b030a0 by main thread:
[2023-12-28T18:33:49.700Z]     #0 DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/tests/gtests_async_tasks.cpp:108:17 (gtests_dbms+0x5af6b91)
[2023-12-28T18:33:49.700Z]     #1 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xc41fbd5)
[2023-12-28T18:33:49.700Z]     #2 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xc41fbd5)
[2023-12-28T18:33:49.700Z]     #3 testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5 (gtests_dbms+0xc3f9775)
[2023-12-28T18:33:49.700Z]     #4 testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xc3fafa4)
[2023-12-28T18:33:49.700Z]     #5 testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xc3fbc6d)
[2023-12-28T18:33:49.700Z]     #6 testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xc40be20)
[2023-12-28T18:33:49.700Z]     #7 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xc421075)
[2023-12-28T18:33:49.700Z]     #8 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xc421075)
[2023-12-28T18:33:49.700Z]     #9 testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xc40b108)
[2023-12-28T18:33:49.700Z]     #10 RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x5fd310e)
[2023-12-28T18:33:49.700Z]     #11 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:116:16 (gtests_dbms+0x5fd310e)
[2023-12-28T18:33:49.700Z] 
[2023-12-28T18:33:49.700Z]   Location is stack of main thread.
[2023-12-28T18:33:49.700Z] 
[2023-12-28T18:33:49.700Z]   Location is global '??' at 0x7ffdc4ae5000 ([stack]+0x00000001e0a0)
[2023-12-28T18:33:49.700Z] 
[2023-12-28T18:33:49.700Z]   Thread T105 'ThreadPool' (tid=467165, running) created by main thread at:
[2023-12-28T18:33:49.700Z]     #0 pthread_create /llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:977:3 (gtests_dbms+0x2b9f4fd)
[2023-12-28T18:33:49.700Z]     #1 std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) /usr/local/bin/../include/c++/v1/__threading_support:514:10 (gtests_dbms+0xfb14de8)
[2023-12-28T18:33:49.700Z]     #2 std::__1::thread::thread<void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'(), void>(void&&) /usr/local/bin/../include/c++/v1/thread:307:16 (gtests_dbms+0xfb14de8)
[2023-12-28T18:33:49.700Z]     #3 void DB::ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:160:35 (gtests_dbms+0xfb10008)
[2023-12-28T18:33:49.700Z]     #4 DB::ThreadPoolImpl<std::__1::thread>::scheduleOrThrow(std::__1::function<void ()>, long, unsigned long, bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:198:5 (gtests_dbms+0xfb17ef4)
[2023-12-28T18:33:49.701Z]     #5 DB::ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(bool&&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.h:219:38 (gtests_dbms+0xfb17ef4)
[2023-12-28T18:33:49.701Z]     #6 bool DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::scheduleImpl<bool>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:160:35 (gtests_dbms+0xfb12b80)
[2023-12-28T18:33:49.701Z]     #7 DB::ThreadPoolImpl<DB::ThreadFromGlobalPoolImpl<false> >::trySchedule(std::__1::function<void ()>, long, unsigned long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/UniThreadPool.cpp:188:12 (gtests_dbms+0xfb1279a)
[2023-12-28T18:33:49.701Z]     #8 DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTaskWithCancel(unsigned long, std::__1::function<void ()>, std::__1::function<void ()>) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/Utils/AsyncTasks.h:273:33 (gtests_dbms+0x5b008c8)
[2023-12-28T18:33:49.701Z]     #9 DB::AsyncTasks<unsigned long, std::__1::function<void ()>, void>::addTask(unsigned long, std::__1::function<void ()>) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/Utils/AsyncTasks.h:285:16 (gtests_dbms+0x5affa18)
[2023-12-28T18:33:49.701Z]     #10 DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/tests/gtests_async_tasks.cpp:37:22 (gtests_dbms+0x5af5cfa)
[2023-12-28T18:33:49.701Z]     #11 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xc41fbd5)
[2023-12-28T18:33:49.701Z]     #12 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xc41fbd5)
[2023-12-28T18:33:49.701Z]     #13 testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5 (gtests_dbms+0xc3f9775)
[2023-12-28T18:33:49.701Z]     #14 testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xc3fafa4)
[2023-12-28T18:33:49.701Z]     #15 testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xc3fbc6d)
[2023-12-28T18:33:49.701Z]     #16 testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xc40be20)
[2023-12-28T18:33:49.701Z]     #17 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xc421075)
[2023-12-28T18:33:49.701Z]     #18 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xc421075)
[2023-12-28T18:33:49.701Z]     #19 testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xc40b108)
[2023-12-28T18:33:49.701Z]     #20 RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x5fd310e)
[2023-12-28T18:33:49.701Z]     #21 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:116:16 (gtests_dbms+0x5fd310e)
[2023-12-28T18:33:49.701Z] 
[2023-12-28T18:33:49.701Z] SUMMARY: ThreadSanitizer: data race /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/KVStore/tests/gtests_async_tasks.cpp:99:30 in DB::tests::AsyncTasksTest_AsyncTasksNormal_Test::TestBody()::$_10::operator()() const
[2023-12-28T18:33:49.701Z] ==================
[2023-12-28T18:33:49.701Z] [2023/12/29 02:33:47.110 +08:00] [INFO] [AsyncTasks.h:56] ["Pending 1 tasks when destructing"] [thread_id=1]
[2023-12-28T18:33:49.701Z] [2023/12/29 02:33:47.110 +08:00] [INFO] [gtests_async_tasks.cpp:120] ["Block cancel"] [thread_id=1]
[2023-12-28T18:33:49.701Z] ==================
...
[2023-12-28T18:33:49.732Z] SUMMARY: ThreadSanitizer: lock-order-inversion (potential deadlock) (/usr/local/lib/x86_64-unknown-linux-gnu/libc++.so.1+0x66f45) in std::__1::mutex::lock()
[2023-12-28T18:33:49.732Z] ==================
```
### 4. What is your TiFlash version? (Required)
master

### LINKED ISSUE #8625: unstable test RegionKVStoreV2Test.KVStoreSingleSnap4
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)
https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-unit-tests/detail/tiflash-ghpr-unit-tests/12407/pipeline/
```
[1238/2415] RegionKVStoreV2Test.KVStoreSingleSnap4 (1849 ms)
... ......
[0;33mNote: Google Test filter = RegionKVStoreV2Test.KVStoreSingleSnap4
[m[0;32m[==========] [mRunning 1 test from 1 test case.
[0;32m[----------] [mGlobal test environment set-up.
[0;32m[----------] [m1 test from RegionKVStoreV2Test
[0;32m[ RUN      ] [mRegionKVStoreV2Test.KVStoreSingleSnap4
[2023/12/29 09:33:16.443 +08:00] [INFO] [TiFlashTestEnv.cpp:258] ["Clean path /tmp-memfs/tiflash-tests/tmp/region_kvs_v2_test for bootstrap"] [source=Test] [thread_id=1]
[2023/12/29 09:33:16.443 +08:00] [WARN] [ProxyFFI.cpp:895] ["Set mock rust ptr gc function"] [source=MockSetRustGcHelper] [thread_id=1]
[2023/12/29 09:33:16.444 +08:00] [INFO] [KVStore.cpp:70] ["KVStore inited, eager_raft_log_gc_enabled=false"] [thread_id=1]
[2023/12/29 09:33:16.444 +08:00] [INFO] [PageStorageImpl.cpp:56] ["PageStorageImpl start. Config{ PageStorageConfig {blob_file_limit_size: 268435456, blob_spacemap_type: 2, blob_heavy_gc_valid_rate: 0.500, blob_heavy_gc_valid_rate_raft_data: 0.050, blob_block_alignment_bytes: 0, wal_roll_size: 2097152, wal_max_persisted_log_files: 4} }"] [source=RegionPersister] [thread_id=1]
[2023/12/29 09:33:16.444 +08:00] [INFO] [PageDirectoryFactory.cpp:68] ["PageDirectory restored, max_page_id=0 max_applied_ver=0"] [source=RegionPersister] [thread_id=1]
[2023/12/29 09:33:16.444 +08:00] [INFO] [RegionPersister.cpp:381] ["RegionPersister running. Current Run Mode is ONLY_V3"] [thread_id=1]
[2023/12/29 09:33:16.444 +08:00] [INFO] [KVStore.cpp:84] ["Restored 0 regions"] [thread_id=1]
[2023/12/29 09:33:16.445 +08:00] [INFO] [KVStore.cpp:131] ["Parsed proxy config snap_handle_pool_size 4"] [thread_id=1]
[2023/12/29 09:33:16.449 +08:00] [INFO] [KVStore.cpp:616] ["Set store info id: 1234"] [thread_id=1]
[2023/12/29 09:33:16.449 +08:00] [INFO] [kvstore_helper.h:100] ["Finished setup"] [source=RegionKVStoreV2Test] [thread_id=1]
[2023/12/29 09:33:16.449 +08:00] [WARN] [Context.cpp:1732] ["GlobalStoragePool has already been initialized."] [source=Context] [thread_id=1]
[2023/12/29 09:33:16.449 +08:00] [INFO] [PageStorageImpl.cpp:56] ["PageStorageImpl start. Config{ PageStorageConfig {blob_file_limit_size: 268435456, blob_spacemap_type: 2, blob_heavy_gc_valid_rate: 0.500, blob_heavy_gc_valid_rate_raft_data: 0.050, blob_block_alignment_bytes: 0, wal_roll_size: 2097152, wal_max_persisted_log_files: 4} }"] [source=__global__.log] [thread_id=1]
[2023/12/29 09:33:16.449 +08:00] [INFO] [PageStorageImpl.cpp:56] ["PageStorageImpl start. Config{ PageStorageConfig {blob_file_limit_size: 268435456, blob_spacemap_type: 2, blob_heavy_gc_valid_rate: 0.500, blob_heavy_gc_valid_rate_raft_data: 0.050, blob_block_alignment_bytes: 0, wal_roll_size: 2097152, wal_max_persisted_log_files: 4} }"] [source=__global__.data] [thread_id=1]
[2023/12/29 09:33:16.449 +08:00] [INFO] [PageStorageImpl.cpp:56] ["PageStorageImpl start. Config{ PageStorageConfig {blob_file_limit_size: 268435456, blob_spacemap_type: 2, blob_heavy_gc_valid_rate: 0.500, blob_heavy_gc_valid_rate_raft_data: 0.050, blob_block_alignment_bytes: 0, wal_roll_size: 2097152, wal_max_persisted_log_files: 4} }"] [source=__global__.meta] [thread_id=1]
[2023/12/29 09:33:16.450 +08:00] [INFO] [PageDirectoryFactory.cpp:68] ["PageDirectory restored, max_page_id=0 max_applied_ver=0"] [source=__global__.log] [thread_id=1]
[2023/12/29 09:33:16.450 +08:00] [INFO] [PageDirectoryFactory.cpp:68] ["PageDirectory restored, max_page_id=0 max_applied_ver=0"] [source=__global__.data] [thread_id=1]
[2023/12/29 09:33:16.450 +08:00] [INFO] [PageDirectoryFactory.cpp:68] ["PageDirectory restored, max_page_id=0 max_applied_ver=0"] [source=__global__.meta] [thread_id=1]
[2023/12/29 09:33:16.450 +08:00] [INFO] [TiDBSchemaSyncer.cpp:74] ["Start to sync schemas. current version is: 0 and try to sync schema version to: 4"] [source="keyspace=4294967295"] [thread_id=1]
[2023/12/29 09:33:16.450 +08:00] [INFO] [SchemaBuilder.cpp:1258] ["Sync all schemas begin"] [source="keyspace=4294967295"] [thread_id=1]
[2023/12/29 09:33:16.451 +08:00] [INFO] [SchemaBuilder.cpp:889] ["Create database default begin, database_id=0"] [source="keyspace=4294967295"] [thread_id=98]
[2023/12/29 09:33:16.451 +08:00] [INFO] [SchemaBuilder.cpp:889] ["Create database d begin, database_id=1"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.481 +08:00] [INFO] [DatabaseTiFlash.cpp:130] ["Total 0 tables in database db_0"] [source="DatabaseTiFlash (db_0)"] [thread_id=98]
[2023/12/29 09:33:16.481 +08:00] [INFO] [SchemaBuilder.cpp:902] ["Create database default end, database_id=0"] [source="keyspace=4294967295"] [thread_id=98]
[2023/12/29 09:33:16.481 +08:00] [INFO] [SchemaBuilder.cpp:1290] ["Database default created during sync all schemas, database_id=0"] [source="keyspace=4294967295"] [thread_id=98]
[2023/12/29 09:33:16.485 +08:00] [INFO] [DatabaseTiFlash.cpp:130] ["Total 0 tables in database db_1"] [source="DatabaseTiFlash (db_1)"] [thread_id=99]
[2023/12/29 09:33:16.485 +08:00] [INFO] [SchemaBuilder.cpp:902] ["Create database d end, database_id=1"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.486 +08:00] [INFO] [SchemaBuilder.cpp:1290] ["Database d created during sync all schemas, database_id=1"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.486 +08:00] [INFO] [SchemaBuilder.cpp:1301] ["Table d.prevt1804289383 syncing during sync all schemas, database_id=1 table_id=30"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.486 +08:00] [DEBUG] [SchemaBuilder.cpp:1320] ["register table to table_id_map, database_id=1 table_id=30"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.486 +08:00] [INFO] [SchemaBuilder.cpp:1088] ["Create table db_1.prevt1804289383 begin, database_id=1, table_id=30"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.486 +08:00] [INFO] [SchemaBuilder.cpp:780] ["Storage instance does not exist, tryRecoverPhysicalTable is ignored, table_id=30"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.488 +08:00] [DEBUG] [SchemaBuilder.cpp:1030] ["Analyzing table info : {\"cols\":[{\"comment\":\"\",\"default\":null,\"default_bit\":null,\"id\":1,\"name\":{\"L\":\"a\",\"O\":\"a\"},\"offset\":-1,\"origin_default\":null,\"state\":0,\"type\":{\"Charset\":null,\"Collate\":null,\"Decimal\":0,\"Elems\":null,\"Flag\":4097,\"Flen\":0,\"Tp\":8}}],\"comment\":\"Mocked.\",\"id\":30,\"index_info\":[],\"is_common_handle\":false,\"keyspace_id\":4294967295,\"name\":{\"L\":\"prevt1804289383\",\"O\":\"prevt1804289383\"},\"partition\":null,\"pk_is_handle\":false,\"schema_version\":-1,\"state\":0,\"tiflash_replica\":{\"Count\":0},\"update_timestamp\":1703813596450655}"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.491 +08:00] [INFO] [SchemaBuilder.cpp:1122] ["Create table db_1.prevt1804289383 (database_id=1 table_id=30) with statement: CREATE TABLE `db_1`.`t_30`(`a` Int64, `_tidb_rowid` Int64) Engine = DeltaMerge((`_tidb_rowid`), '{\"cols\":[{\"comment\":\"\",\"default\":null,\"default_bit\":null,\"id\":1,\"name\":{\"L\":\"a\",\"O\":\"a\"},\"offset\":-1,\"origin_default\":null,\"state\":0,\"type\":{\"Charset\":null,\"Collate\":null,\"Decimal\":0,\"Elems\":null,\"Flag\":4097,\"Flen\":0,\"Tp\":8}}],\"comment\":\"Mocked.\",\"id\":30,\"index_info\":[],\"is_common_handle\":false,\"keyspace_id\":4294967295,\"name\":{\"L\":\"prevt1804289383\",\"O\":\"prevt1804289383\"},\"partition\":null,\"pk_is_handle\":false,\"schema_version\":-1,\"state\":0,\"tiflash_replica\":{\"Count\":0},\"update_timestamp\":1703813596450655}', 0)"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.496 +08:00] [INFO] [StorageDeltaMerge.cpp:126] ["updateTableColumnInfo, table_name=t_30 ordinary=\"columns format version: 1\n2 columns:\n`a` Int64\n`_tidb_rowid` Int64\n\" materialized=\"columns format version: 1\n0 columns:\n\""] [source=db_1.t_30] [thread_id=99]
[2023/12/29 09:33:16.497 +08:00] [INFO] [SchemaBuilder.cpp:1166] ["Creat table db_1.prevt1804289383 end, database_id=1 table_id=30"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.497 +08:00] [INFO] [SchemaBuilder.cpp:1301] ["Table d.t846930886 syncing during sync all schemas, database_id=1 table_id=31"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.497 +08:00] [DEBUG] [SchemaBuilder.cpp:1320] ["register table to table_id_map, database_id=1 table_id=31"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.497 +08:00] [INFO] [SchemaBuilder.cpp:1088] ["Create table db_1.t846930886 begin, database_id=1, table_id=31"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.498 +08:00] [INFO] [SchemaBuilder.cpp:780] ["Storage instance does not exist, tryRecoverPhysicalTable is ignored, table_id=31"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.499 +08:00] [DEBUG] [SchemaBuilder.cpp:1030] ["Analyzing table info : {\"cols\":[{\"comment\":\"\",\"default\":null,\"default_bit\":null,\"id\":1,\"name\":{\"L\":\"a\",\"O\":\"a\"},\"offset\":-1,\"origin_default\":null,\"state\":0,\"type\":{\"Charset\":null,\"Collate\":null,\"Decimal\":0,\"Elems\":null,\"Flag\":4097,\"Flen\":0,\"Tp\":8}}],\"comment\":\"Mocked.\",\"id\":31,\"index_info\":[],\"is_common_handle\":false,\"keyspace_id\":4294967295,\"name\":{\"L\":\"t846930886\",\"O\":\"t846930886\"},\"partition\":null,\"pk_is_handle\":false,\"schema_version\":-1,\"state\":0,\"tiflash_replica\":{\"Count\":0},\"update_timestamp\":1703813596450655}"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.501 +08:00] [INFO] [SchemaBuilder.cpp:1122] ["Create table db_1.t846930886 (database_id=1 table_id=31) with statement: CREATE TABLE `db_1`.`t_31`(`a` Int64, `_tidb_rowid` Int64) Engine = DeltaMerge((`_tidb_rowid`), '{\"cols\":[{\"comment\":\"\",\"default\":null,\"default_bit\":null,\"id\":1,\"name\":{\"L\":\"a\",\"O\":\"a\"},\"offset\":-1,\"origin_default\":null,\"state\":0,\"type\":{\"Charset\":null,\"Collate\":null,\"Decimal\":0,\"Elems\":null,\"Flag\":4097,\"Flen\":0,\"Tp\":8}}],\"comment\":\"Mocked.\",\"id\":31,\"index_info\":[],\"is_common_handle\":false,\"keyspace_id\":4294967295,\"name\":{\"L\":\"t846930886\",\"O\":\"t846930886\"},\"partition\":null,\"pk_is_handle\":false,\"schema_version\":-1,\"state\":0,\"tiflash_replica\":{\"Count\":0},\"update_timestamp\":1703813596450655}', 0)"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.504 +08:00] [INFO] [StorageDeltaMerge.cpp:126] ["updateTableColumnInfo, table_name=t_31 ordinary=\"columns format version: 1\n2 columns:\n`a` Int64\n`_tidb_rowid` Int64\n\" materialized=\"columns format version: 1\n0 columns:\n\""] [source=db_1.t_31] [thread_id=99]
[2023/12/29 09:33:16.505 +08:00] [INFO] [SchemaBuilder.cpp:1166] ["Creat table db_1.t846930886 end, database_id=1 table_id=31"] [source="keyspace=4294967295"] [thread_id=99]
[2023/12/29 09:33:16.505 +08:00] [INFO] [SchemaBuilder.cpp:1383] ["Sync all schemas end"] [source="keyspace=4294967295"] [thread_id=1]
[2023/12/29 09:33:16.505 +08:00] [INFO] [TiDBSchemaSyncer.cpp:108] ["End sync schema, version has been updated to 4"] [source="keyspace=4294967295"] [thread_id=1]
[2023/12/29 09:33:16.506 +08:00] [INFO] [RegionTable.cpp:49] ["get new table, keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.516 +08:00] [DEBUG] [PartitionStreams.cpp:451] ["Get schema, keyspace=4294967295 table_id=31"] [source="std::tuple<TableLockHolder, std::shared_ptr<StorageDeltaMerge>, DecodingStorageSchemaSnapshotConstPtr> DB::AtomicGetStorageSchema(const DB::RegionPtr &, DB::TMTContext &)"] [thread_id=1]
[2023/12/29 09:33:16.516 +08:00] [INFO] [DeltaMergeStore.cpp:238] ["Restore DeltaMerge Store start"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.516 +08:00] [DEBUG] [DeltaMergeStore.cpp:1966] ["Loading dt files"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.517 +08:00] [TRACE] [StoragePool.cpp:806] ["Finished StoragePool restore. [current_run_mode=ONLY_V3] [ns_id=31] [max_log_page_id=0] [max_data_page_id=0] [max_meta_page_id=0]"] [source=db_1.t_31] [thread_id=1]
[2023/12/29 09:33:16.517 +08:00] [INFO] [DeltaMergeStore.cpp:308] ["Restore DeltaMerge Store end, ps_run_mode=ONLY_V3"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.518 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=18446744073709551615"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.518 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Default to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=18446744073709551615"] [source=MonoSSTReader] [thread_id=1]
[2023/12/29 09:33:16.518 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=18446744073709551615"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.518 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Write to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=18446744073709551615"] [source=MonoSSTReader] [thread_id=1]
[2023/12/29 09:33:16.518 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:129] ["Finish Construct MultiSSTReader, write=1 lock=0 default=1 region_id=2 snapshot_index=6"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.519 +08:00] [INFO] [PrehandleSnapshot.cpp:388] ["getSplitKey result 7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90:7480000000000000FF1F5F728000000000FF0000310000000000FAFFFFFFFFFFFFFF90:7480000000000000FF1F5F728000000000FF0000490000000000FAFFFFFFFFFFFFFF90, total_concurrency=4 ongoing=1 total_split_parts=4 split_keys=3 region_range=[7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] approx_bytes=1980 region_id=2"] [thread_id=1]
[2023/12/29 09:33:16.519 +08:00] [DEBUG] [PrehandleSnapshot.cpp:78] ["Prehandle resource meet, limit=4, current=4, region_id=2"] [source=PreHandlingTrace] [thread_id=1]
[2023/12/29 09:33:16.519 +08:00] [INFO] [PrehandleSnapshot.cpp:511] ["Parallel prehandling for single big region, range=[7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA], split keys=3, region_id=2"] [thread_id=1]
[2023/12/29 09:33:16.519 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=0"] [source="keyspace=4294967295 table_id=31"] [thread_id=98]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Default to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=0"] [source=MonoSSTReader] [thread_id=98]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=0"] [source="keyspace=4294967295 table_id=31"] [thread_id=98]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Write to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=0"] [source=MonoSSTReader] [thread_id=98]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=1"] [source="keyspace=4294967295 table_id=31"] [thread_id=99]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:129] ["Finish Construct MultiSSTReader, write=1 lock=0 default=1 region_id=2 snapshot_index=6"] [source="keyspace=4294967295 table_id=31"] [thread_id=98]
[2023/12/29 09:33:16.520 +08:00] [INFO] [PrehandleSnapshot.cpp:135] ["Add prehandle task split_id=0 limit=7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90:7480000000000000FF1F5F728000000000FF0000310000000000FAFFFFFFFFFFFFFF90"] [thread_id=98]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Default to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=1"] [source=MonoSSTReader] [thread_id=99]
[2023/12/29 09:33:16.520 +08:00] [INFO] [PrehandleSnapshot.cpp:135] ["Add prehandle task split_id=18446744073709551615 limit=:7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90"] [thread_id=1]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=1"] [source="keyspace=4294967295 table_id=31"] [thread_id=99]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Write to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=1"] [source=MonoSSTReader] [thread_id=99]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:129] ["Finish Construct MultiSSTReader, write=1 lock=0 default=1 region_id=2 snapshot_index=6"] [source="keyspace=4294967295 table_id=31"] [thread_id=99]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:476] ["Re-Seek after start_raw 7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90 start_pk 8000000000000019 to 7480000000000000FF1F5F728000000000FF00001A0000000000FAFFFFFFFFFFFFFF90, current_pk = 800000000000001A, cf=Write, split_id=0, region_id=2"] [source="keyspace=4294967295 table_id=31"] [thread_id=98]
[2023/12/29 09:33:16.520 +08:00] [INFO] [PrehandleSnapshot.cpp:135] ["Add prehandle task split_id=1 limit=7480000000000000FF1F5F728000000000FF0000310000000000FAFFFFFFFFFFFFFF90:7480000000000000FF1F5F728000000000FF0000490000000000FAFFFFFFFFFFFFFF90"] [thread_id=99]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=2"] [source="keyspace=4294967295 table_id=31"] [thread_id=100]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Default to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=2"] [source=MonoSSTReader] [thread_id=100]
[2023/12/29 09:33:16.520 +08:00] [DEBUG] [DMVersionFilterBlockInputStream.h:83] ["Total rows: 0, pass: -nan%, complete pass: -nan%, complete not pass: -nan%, not clean: -nan%, is deleted: -nan%, effective: -nan%, start_ts: 0"] [source="mode=COMPACT"] [thread_id=98]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=2"] [source="keyspace=4294967295 table_id=31"] [thread_id=100]
[2023/12/29 09:33:16.520 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Write to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=2"] [source=MonoSSTReader] [thread_id=100]
[2023/12/29 09:33:16.521 +08:00] [INFO] [PrehandleSnapshot.cpp:451] ["Finished extra parallel prehandle task limit 7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90:7480000000000000FF1F5F728000000000FF0000310000000000FAFFFFFFFFFFFFFF90 write cf 0 lock cf 0 default cf 0 dmfiles 0 error ErrUpdateSchema, split_id=0 region_id=2"] [thread_id=98]
[2023/12/29 09:33:16.521 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:129] ["Finish Construct MultiSSTReader, write=1 lock=0 default=1 region_id=2 snapshot_index=6"] [source="keyspace=4294967295 table_id=31"] [thread_id=100]
[2023/12/29 09:33:16.521 +08:00] [INFO] [PrehandleSnapshot.cpp:135] ["Add prehandle task split_id=2 limit=7480000000000000FF1F5F728000000000FF0000490000000000FAFFFFFFFFFFFFFF90:"] [thread_id=100]
[2023/12/29 09:33:16.521 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:476] ["Re-Seek after start_raw 7480000000000000FF1F5F728000000000FF0000310000000000FAFFFFFFFFFFFFFF90 start_pk 8000000000000031 to 7480000000000000FF1F5F728000000000FF0000320000000000FAFFFFFFFFFFFFFF90, current_pk = 8000000000000032, cf=Write, split_id=1, region_id=2"] [source="keyspace=4294967295 table_id=31"] [thread_id=99]
[2023/12/29 09:33:16.521 +08:00] [INFO] [SSTFilesToDTFilesOutputStream.cpp:130] ["Transformed snapshot in SSTFile to DTFiles, region=[region_id=2 applied_term=5 applied_index=6] job_type=ApplySnapshot cost_ms=0 rows=0 bytes=0 bytes_on_disk=0 write_cf_keys=0 default_cf_keys=0 lock_cf_keys=0 splid_id=1 dt_files=[files_num=0 ]"] [source="keyspace=4294967295 table_id=31"] [thread_id=99]
[2023/12/29 09:33:16.521 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:476] ["Re-Seek after start_raw 7480000000000000FF1F5F728000000000FF0000490000000000FAFFFFFFFFFFFFFF90 start_pk 8000000000000049 to 7480000000000000FF1F5F728000000000FF00004A0000000000FAFFFFFFFFFFFFFF90, current_pk = 800000000000004A, cf=Write, split_id=2, region_id=2"] [source="keyspace=4294967295 table_id=31"] [thread_id=100]
[2023/12/29 09:33:16.521 +08:00] [DEBUG] [DMVersionFilterBlockInputStream.h:83] ["Total rows: 0, pass: -nan%, complete pass: -nan%, complete not pass: -nan%, not clean: -nan%, is deleted: -nan%, effective: -nan%, start_ts: 0"] [source="mode=COMPACT"] [thread_id=99]
[2023/12/29 09:33:16.521 +08:00] [INFO] [SSTFilesToDTFilesOutputStream.cpp:130] ["Transformed snapshot in SSTFile to DTFiles, region=[region_id=2 applied_term=5 applied_index=6] job_type=ApplySnapshot cost_ms=0 rows=0 bytes=0 bytes_on_disk=0 write_cf_keys=0 default_cf_keys=0 lock_cf_keys=0 splid_id=2 dt_files=[files_num=0 ]"] [source="keyspace=4294967295 table_id=31"] [thread_id=100]
[2023/12/29 09:33:16.521 +08:00] [DEBUG] [DMVersionFilterBlockInputStream.h:83] ["Total rows: 0, pass: -nan%, complete pass: -nan%, complete not pass: -nan%, not clean: -nan%, is deleted: -nan%, effective: -nan%, start_ts: 0"] [source="mode=COMPACT"] [thread_id=100]
[2023/12/29 09:33:16.521 +08:00] [INFO] [PrehandleSnapshot.cpp:451] ["Finished extra parallel prehandle task limit 7480000000000000FF1F5F728000000000FF0000490000000000FAFFFFFFFFFFFFFF90: write cf 0 lock cf 0 default cf 0 dmfiles 0 error ErrUpdateSchema, split_id=2 region_id=2"] [thread_id=100]
[2023/12/29 09:33:16.521 +08:00] [INFO] [PrehandleSnapshot.cpp:451] ["Finished extra parallel prehandle task limit 7480000000000000FF1F5F728000000000FF0000310000000000FAFFFFFFFFFFFFFF90:7480000000000000FF1F5F728000000000FF0000490000000000FAFFFFFFFFFFFFFF90 write cf 0 lock cf 0 default cf 0 dmfiles 0 error ErrUpdateSchema, split_id=1 region_id=2"] [thread_id=99]
[2023/12/29 09:33:16.522 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:516] ["Reach end for split :7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90 current 7480000000000000FF1F5F728000000000FF00001A0000000000FAFFFFFFFFFFFFFF90 pk 800000000000001A end_limit 8000000000000019, cf=Write split_id=18446744073709551615 region_id=2"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.524 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:516] ["Reach end for split :7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90 current 7480000000000000FF1F5F728000000000FF00001A0000000000FAFFFFFFFFFFFFFF90 pk 800000000000001A end_limit 8000000000000019, cf=Default split_id=18446744073709551615 region_id=2"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.524 +08:00] [DEBUG] [SSTFilesToBlockInputStream.cpp:298] ["Done loading all kvpairs, CF=default offset=25 processed_bytes=1325 write_cf_offset=25 region_id=2 split_id=18446744073709551615 snapshot_index=6"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.524 +08:00] [DEBUG] [SSTFilesToBlockInputStream.cpp:298] ["Done loading all kvpairs, CF=lock offset=0 processed_bytes=0 write_cf_offset=25 region_id=2 split_id=18446744073709551615 snapshot_index=6"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.526 +08:00] [DEBUG] [SSTFilesToBlockInputStream.cpp:298] ["Done loading all kvpairs, CF=default offset=25 processed_bytes=1325 write_cf_offset=25 region_id=2 split_id=18446744073709551615 snapshot_index=6"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.526 +08:00] [DEBUG] [SSTFilesToBlockInputStream.cpp:298] ["Done loading all kvpairs, CF=lock offset=0 processed_bytes=0 write_cf_offset=25 region_id=2 split_id=18446744073709551615 snapshot_index=6"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.526 +08:00] [WARN] [StoragePool.cpp:985] ["The DTFile is already exists, continute to acquire another ID. [call=std::tuple<String, PageIdU64> DB::DM::DeltaMergeStore::preAllocateIngestFile()][path=<mock for existed path>] [id=1]"] [source=db_1.t_31] [thread_id=1]
[2023/12/29 09:33:16.534 +08:00] [DEBUG] [SSTFilesToDTFilesOutputStream.cpp:202] ["Create new DTFile for snapshot data, region_id=2 file_idx=0 file=/tmp-memfs/tiflash-tests/tmp/20079/data/t_31/stable/.tmp.dmf_2"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.537 +08:00] [DEBUG] [PathPool.cpp:553] ["added new dtfile. [id=2] [path=/tmp-memfs/tiflash-tests/tmp/20079/data/t_31] [real_size=1445] [reported_size=249]"] [thread_id=1]
[2023/12/29 09:33:16.538 +08:00] [INFO] [SSTFilesToDTFilesOutputStream.cpp:238] ["Finished writing DTFile from snapshot data, region=[region_id=2 applied_term=5 applied_index=6] file_idx=0 file_rows=25 file_bytes=625 data_range=[1,26) file_bytes_on_disk=249 file=/tmp-memfs/tiflash-tests/tmp/20079/data/t_31/stable/dmf_2"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.538 +08:00] [INFO] [SSTFilesToDTFilesOutputStream.cpp:130] ["Transformed snapshot in SSTFile to DTFiles, region=[region_id=2 applied_term=5 applied_index=6] job_type=ApplySnapshot cost_ms=17 rows=25 bytes=625 bytes_on_disk=249 write_cf_keys=25 default_cf_keys=25 lock_cf_keys=0 splid_id=18446744073709551615 dt_files=[files_num=1 dmf_2]"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.539 +08:00] [DEBUG] [DMVersionFilterBlockInputStream.h:83] ["Total rows: 25, pass: 100.00%, complete pass: 100.00%, complete not pass: 0.00%, not clean: 0.00%, is deleted: 0.00%, effective: 100.00%, start_ts: 0"] [source="mode=COMPACT"] [thread_id=1]
[2023/12/29 09:33:16.539 +08:00] [INFO] [PrehandleSnapshot.cpp:565] ["Finished extra parallel prehandle task limit :7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90 write cf 25 lock cf 0 default cf 25 dmfiles 0 error ErrUpdateSchema, split_id=18446744073709551615, region_id=2"] [thread_id=1]
[2023/12/29 09:33:16.539 +08:00] [DEBUG] [PrehandleSnapshot.cpp:572] ["Try fetch prehandle task split_id=0, region_id=2"] [thread_id=1]
[2023/12/29 09:33:16.539 +08:00] [DEBUG] [PrehandleSnapshot.cpp:572] ["Try fetch prehandle task split_id=1, region_id=2"] [thread_id=1]
[2023/12/29 09:33:16.539 +08:00] [DEBUG] [PrehandleSnapshot.cpp:572] ["Try fetch prehandle task split_id=2, region_id=2"] [thread_id=1]
[2023/12/29 09:33:16.539 +08:00] [INFO] [AsyncTasks.h:56] ["Pending 0 tasks when destructing"] [thread_id=1]
[2023/12/29 09:33:16.539 +08:00] [INFO] [PrehandleSnapshot.cpp:761] ["Decoding Region snapshot data meet error, sync schema and try to decode again [region_id=2 applied_term=5 applied_index=6] [error=]"] [thread_id=1]
[2023/12/29 09:33:16.539 +08:00] [INFO] [TiDBSchemaSyncer.cpp:234] ["Sync table schema begin, table_id=31"] [source="keyspace=4294967295"] [thread_id=1]
[2023/12/29 09:33:16.540 +08:00] [INFO] [SchemaBuilder.cpp:1493] ["Alter table db_1.t846930886 begin, database_id=1 table_id=31"] [source="keyspace=4294967295"] [thread_id=1]
[2023/12/29 09:33:16.541 +08:00] [DEBUG] [StorageDeltaMerge.cpp:1521] ["Update table_info: {\"cols\":[{\"comment\":\"\",\"default\":null,\"default_bit\":null,\"id\":1,\"name\":{\"L\":\"a\",\"O\":\"a\"},\"offset\":-1,\"origin_default\":null,\"state\":0,\"type\":{\"Charset\":null,\"Collate\":null,\"Decimal\":0,\"Elems\":null,\"Flag\":4097,\"Flen\":0,\"Tp\":8}}],\"comment\":\"Mocked.\",\"id\":31,\"index_info\":[],\"is_common_handle\":false,\"keyspace_id\":4294967295,\"name\":{\"L\":\"t846930886\",\"O\":\"t846930886\"},\"partition\":null,\"pk_is_handle\":false,\"schema_version\":-1,\"state\":0,\"tiflash_replica\":{\"Count\":0},\"update_timestamp\":1703813596450655} => {\"cols\":[{\"comment\":\"\",\"default\":null,\"default_bit\":null,\"id\":1,\"name\":{\"L\":\"a\",\"O\":\"a\"},\"offset\":-1,\"origin_default\":null,\"state\":0,\"type\":{\"Charset\":null,\"Collate\":null,\"Decimal\":0,\"Elems\":null,\"Flag\":4097,\"Flen\":0,\"Tp\":8}}],\"comment\":\"Mocked.\",\"id\":31,\"index_info\":[],\"is_common_handle\":false,\"keyspace_id\":4294967295,\"name\":{\"L\":\"t846930886\",\"O\":\"t846930886\"},\"partition\":null,\"pk_is_handle\":false,\"schema_version\":-1,\"state\":0,\"tiflash_replica\":{\"Count\":0},\"update_timestamp\":1703813596450655}"] [source=db_1.t_31] [thread_id=1]
[2023/12/29 09:33:16.544 +08:00] [INFO] [SchemaBuilder.cpp:1508] ["Alter table db_1.t846930886 end, database_id=1 table_id=31"] [source="keyspace=4294967295"] [thread_id=1]
[2023/12/29 09:33:16.544 +08:00] [INFO] [TiDBSchemaSyncer.cpp:243] ["Sync table schema end, table_id=31"] [source="keyspace=4294967295"] [thread_id=1]
[2023/12/29 09:33:16.544 +08:00] [DEBUG] [PartitionStreams.cpp:451] ["Get schema, keyspace=4294967295 table_id=31"] [source="std::tuple<TableLockHolder, std::shared_ptr<StorageDeltaMerge>, DecodingStorageSchemaSnapshotConstPtr> DB::AtomicGetStorageSchema(const DB::RegionPtr &, DB::TMTContext &)"] [thread_id=1]
[2023/12/29 09:33:16.544 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=18446744073709551615"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.544 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Default to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=18446744073709551615"] [source=MonoSSTReader] [thread_id=1]
[2023/12/29 09:33:16.544 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=18446744073709551615"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.544 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Write to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=18446744073709551615"] [source=MonoSSTReader] [thread_id=1]
[2023/12/29 09:33:16.544 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:129] ["Finish Construct MultiSSTReader, write=1 lock=0 default=1 region_id=2 snapshot_index=6"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.545 +08:00] [INFO] [PrehandleSnapshot.cpp:388] ["getSplitKey result 7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90:7480000000000000FF1F5F728000000000FF0000310000000000FAFFFFFFFFFFFFFF90:7480000000000000FF1F5F728000000000FF0000490000000000FAFFFFFFFFFFFFFF90, total_concurrency=4 ongoing=1 total_split_parts=4 split_keys=3 region_range=[7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] approx_bytes=1980 region_id=2"] [thread_id=1]
[2023/12/29 09:33:16.545 +08:00] [DEBUG] [PrehandleSnapshot.cpp:78] ["Prehandle resource meet, limit=4, current=4, region_id=2"] [source=PreHandlingTrace] [thread_id=1]
[2023/12/29 09:33:16.545 +08:00] [INFO] [PrehandleSnapshot.cpp:511] ["Parallel prehandling for single big region, range=[7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA], split keys=3, region_id=2"] [thread_id=1]
[2023/12/29 09:33:16.545 +08:00] [INFO] [PrehandleSnapshot.cpp:135] ["Add prehandle task split_id=18446744073709551615 limit=:7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90"] [thread_id=1]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=0"] [source="keyspace=4294967295 table_id=31"] [thread_id=98]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=1"] [source="keyspace=4294967295 table_id=31"] [thread_id=100]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Default to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=0"] [source=MonoSSTReader] [thread_id=98]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Default to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=1"] [source=MonoSSTReader] [thread_id=100]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=0"] [source="keyspace=4294967295 table_id=31"] [thread_id=98]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=1"] [source="keyspace=4294967295 table_id=31"] [thread_id=100]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Write to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=0"] [source=MonoSSTReader] [thread_id=98]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Write to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=1"] [source=MonoSSTReader] [thread_id=100]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:129] ["Finish Construct MultiSSTReader, write=1 lock=0 default=1 region_id=2 snapshot_index=6"] [source="keyspace=4294967295 table_id=31"] [thread_id=98]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTFilesToDTFilesOutputStream.cpp:130] ["Transformed snapshot in SSTFile to DTFiles, region=[region_id=2 applied_term=5 applied_index=6] job_type=ApplySnapshot cost_ms=0 rows=0 bytes=0 bytes_on_disk=0 write_cf_keys=0 default_cf_keys=0 lock_cf_keys=0 splid_id=18446744073709551615 dt_files=[files_num=0 ]"] [source="keyspace=4294967295 table_id=31"] [thread_id=1]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:129] ["Finish Construct MultiSSTReader, write=1 lock=0 default=1 region_id=2 snapshot_index=6"] [source="keyspace=4294967295 table_id=31"] [thread_id=100]
[2023/12/29 09:33:16.545 +08:00] [INFO] [PrehandleSnapshot.cpp:135] ["Add prehandle task split_id=0 limit=7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90:7480000000000000FF1F5F728000000000FF0000310000000000FAFFFFFFFFFFFFFF90"] [thread_id=98]
[2023/12/29 09:33:16.545 +08:00] [DEBUG] [DMVersionFilterBlockInputStream.h:83] ["Total rows: 0, pass: -nan%, complete pass: -nan%, complete not pass: -nan%, not clean: -nan%, is deleted: -nan%, effective: -nan%, start_ts: 0"] [source="mode=COMPACT"] [thread_id=1]
[2023/12/29 09:33:16.545 +08:00] [INFO] [PrehandleSnapshot.cpp:135] ["Add prehandle task split_id=1 limit=7480000000000000FF1F5F728000000000FF0000310000000000FAFFFFFFFFFFFFFF90:7480000000000000FF1F5F728000000000FF0000490000000000FAFFFFFFFFFFFFFF90"] [thread_id=100]
[2023/12/29 09:33:16.545 +08:00] [INFO] [PrehandleSnapshot.cpp:565] ["Finished extra parallel prehandle task limit :7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90 write cf 0 lock cf 0 default cf 0 dmfiles 0 error ErrUpdateSchema, split_id=18446744073709551615, region_id=2"] [thread_id=1]
[2023/12/29 09:33:16.545 +08:00] [DEBUG] [PrehandleSnapshot.cpp:572] ["Try fetch prehandle task split_id=0, region_id=2"] [thread_id=1]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=2"] [source="keyspace=4294967295 table_id=31"] [thread_id=99]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:476] ["Re-Seek after start_raw 7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90 start_pk 8000000000000019 to 7480000000000000FF1F5F728000000000FF00001A0000000000FAFFFFFFFFFFFFFF90, current_pk = 800000000000001A, cf=Write, split_id=0, region_id=2"] [source="keyspace=4294967295 table_id=31"] [thread_id=98]
[2023/12/29 09:33:16.545 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:476] ["Re-Seek after start_raw 7480000000000000FF1F5F728000000000FF0000310000000000FAFFFFFFFFFFFFFF90 start_pk 8000000000000031 to 7480000000000000FF1F5F728000000000FF0000320000000000FAFFFFFFFFFFFFFF90, current_pk = 8000000000000032, cf=Write, split_id=1, region_id=2"] [source="keyspace=4294967295 table_id=31"] [thread_id=100]
[2023/12/29 09:33:16.546 +08:00] [INFO] [SSTFilesToDTFilesOutputStream.cpp:130] ["Transformed snapshot in SSTFile to DTFiles, region=[region_id=2 applied_term=5 applied_index=6] job_type=ApplySnapshot cost_ms=0 rows=0 bytes=0 bytes_on_disk=0 write_cf_keys=0 default_cf_keys=0 lock_cf_keys=0 splid_id=0 dt_files=[files_num=0 ]"] [source="keyspace=4294967295 table_id=31"] [thread_id=98]
[2023/12/29 09:33:16.546 +08:00] [INFO] [SSTFilesToDTFilesOutputStream.cpp:130] ["Transformed snapshot in SSTFile to DTFiles, region=[region_id=2 applied_term=5 applied_index=6] job_type=ApplySnapshot cost_ms=0 rows=0 bytes=0 bytes_on_disk=0 write_cf_keys=0 default_cf_keys=0 lock_cf_keys=0 splid_id=1 dt_files=[files_num=0 ]"] [source="keyspace=4294967295 table_id=31"] [thread_id=100]
[2023/12/29 09:33:16.546 +08:00] [DEBUG] [DMVersionFilterBlockInputStream.h:83] ["Total rows: 0, pass: -nan%, complete pass: -nan%, complete not pass: -nan%, not clean: -nan%, is deleted: -nan%, effective: -nan%, start_ts: 0"] [source="mode=COMPACT"] [thread_id=98]
[2023/12/29 09:33:16.546 +08:00] [DEBUG] [DMVersionFilterBlockInputStream.h:83] ["Total rows: 0, pass: -nan%, complete pass: -nan%, complete not pass: -nan%, not clean: -nan%, is deleted: -nan%, effective: -nan%, start_ts: 0"] [source="mode=COMPACT"] [thread_id=100]
[2023/12/29 09:33:16.546 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Default to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=2"] [source=MonoSSTReader] [thread_id=99]
[2023/12/29 09:33:16.546 +08:00] [INFO] [PrehandleSnapshot.cpp:451] ["Finished extra parallel prehandle task limit 7480000000000000FF1F5F728000000000FF0000190000000000FAFFFFFFFFFFFFFF90:7480000000000000FF1F5F728000000000FF0000310000000000FAFFFFFFFFFFFFFF90 write cf 0 lock cf 0 default cf 0 dmfiles 0 error ErrUpdateSchema, split_id=0 region_id=2"] [thread_id=98]
[2023/12/29 09:33:16.546 +08:00] [INFO] [PrehandleSnapshot.cpp:451] ["Finished extra parallel prehandle task limit 7480000000000000FF1F5F728000000000FF0000310000000000FAFFFFFFFFFFFFFF90:7480000000000000FF1F5F728000000000FF0000490000000000FAFFFFFFFFFFFFFF90 write cf 0 lock cf 0 default cf 0 dmfiles 0 error ErrUpdateSchema, split_id=1 region_id=2"] [thread_id=100]
[2023/12/29 09:33:16.546 +08:00] [DEBUG] [PrehandleSnapshot.cpp:572] ["Try fetch prehandle task split_id=1, region_id=2"] [thread_id=1]
[2023/12/29 09:33:16.546 +08:00] [DEBUG] [PrehandleSnapshot.cpp:572] ["Try fetch prehandle task split_id=2, region_id=2"] [thread_id=1]
[2023/12/29 09:33:16.546 +08:00] [INFO] [SSTReader.h:190] ["Open sst file first !2_multi_0 range [7480000000000000FF1F5F728000000000FF0000000000000000FA,7480000000000000FF1F5F728000000000FF00005A0000000000FA] split_id=2"] [source="keyspace=4294967295 table_id=31"] [thread_id=99]
[2023/12/29 09:33:16.546 +08:00] [INFO] [SSTReader.cpp:132] ["Seek cf Write to 7480000000000000FF1F5F728000000000FF0000000000000000FA, split_id=2"] [source=MonoSSTReader] [thread_id=99]
[2023/12/29 09:33:16.546 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:129] ["Finish Construct MultiSSTReader, write=1 lock=0 default=1 region_id=2 snapshot_index=6"] [source="keyspace=4294967295 table_id=31"] [thread_id=99]
[2023/12/29 09:33:16.546 +08:00] [INFO] [PrehandleSnapshot.cpp:135] ["Add prehandle task split_id=2 limit=7480000000000000FF1F5F728000000000FF0000490000000000FAFFFFFFFFFFFFFF90:"] [thread_id=99]
[2023/12/29 09:33:16.548 +08:00] [INFO] [SSTFilesToBlockInputStream.cpp:476] ["Re-Seek after start_raw 7480000000000000FF1F5F728000000000FF0000490000000000FAFFFFFFFFFFFFFF90 start_pk 8000000000000049 to 7480000000000000FF1F5F728000000000FF00004A0000000000FAFFFFFFFFFFFFFF90, current_pk = 800000000000004A, cf=Write, split_id=2, region_id=2"] [source="keyspace=4294967295 table_id=31"] [thread_id=99]
[2023/12/29 09:33:16.548 +08:00] [INFO] [SSTFilesToDTFilesOutputStream.cpp:130] ["Transformed snapshot in SSTFile to DTFiles, region=[region_id=2 applied_term=5 applied_index=6] job_type=ApplySnapshot cost_ms=0 rows=0 bytes=0 bytes_on_disk=0 write_cf_keys=0 default_cf_keys=0 lock_cf_keys=0 splid_id=2 dt_files=[files_num=0 ]"] [source="keyspace=4294967295 table_id=31"] [thread_id=99]
[2023/12/29 09:33:16.548 +08:00] [DEBUG] [DMVersionFilterBlockInputStream.h:83] ["Total rows: 0, pass: -nan%, complete pass: -nan%, complete not pass: -nan%, not clean: -nan%, is deleted: -nan%, effective: -nan%, start_ts: 0"] [source="mode=COMPACT"] [thread_id=99]
[2023/12/29 09:33:16.549 +08:00] [INFO] [PrehandleSnapshot.cpp:451] ["Finished extra parallel prehandle task limit 7480000000000000FF1F5F728000000000FF0000490000000000FAFFFFFFFFFFFFFF90: write cf 0 lock cf 0 default cf 0 dmfiles 0 error ErrUpdateSchema, split_id=2 region_id=2"] [thread_id=99]
[2023/12/29 09:33:16.549 +08:00] [INFO] [AsyncTasks.h:56] ["Pending 0 tasks when destructing"] [thread_id=1]
[2023/12/29 09:33:16.549 +08:00] [INFO] [PrehandleSnapshot.cpp:880] ["After prehandle, orphan keys remains=0 removed=0 ongoing_prehandle=0 region_id=2"] [thread_id=1]
/home/jenkins/agent/workspace/tiflash-build-common/tiflash/dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp:804: Failure
Failed
Code: 9009. DB::Exception: keyspace=4294967295 physical_table_id=31: (while preHandleSnapshot region_id=2, index=6, term=5)

Stack trace:

      0x11355fae StackTrace::StackTrace() [gtests_dbms+288710574]
       0x490bc22 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [gtests_dbms+76594210]
       0xdfdce63 DB::KVStore::preHandleSSTsToDTFiles(std::__1::shared_ptr<DB::Region>, DB::SSTViewVec, unsigned long, unsigned long, DB::DM::FileConvertJobType, DB::TMTContext&) [gtests_dbms+234737251]
       0xdfdb893 DB::KVStore::preHandleSnapshotToFiles(std::__1::shared_ptr<DB::Region>, DB::SSTViewVec, unsigned long, unsigned long, std::__1::optional<unsigned long>, DB::TMTContext&) [gtests_dbms+234731667]
       0xeef49c5 DB::MockRaftStoreProxy::snapshot(DB::KVStore&, DB::TMTContext&, unsigned long, std::__1::vector<DB::MockSSTGenerator, std::__1::allocator<DB::MockSSTGenerator> >&&, unsigned long, unsigned long, std::__1::optional<unsigned long>, bool) [gtests_dbms+250563013]
       0x77be1f8 DB::tests::RegionKVStoreV2Test_KVStoreSingleSnap4_Test::TestBody() [gtests_dbms+125559288]
       0xe172a7b void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+236399227]
       0xe15fe8a void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+236322442]
       0xe1453dc testing::Test::Run() [gtests_dbms+236213212]
       0xe145efa testing::TestInfo::Run() [gtests_dbms+236216058]
       0xe1464b3 testing::TestCase::Run() [gtests_dbms+236217523]
       0xe150663 testing::internal::UnitTestImpl::RunAllTests() [gtests_dbms+236258915]
       0xe1762ab bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+236413611]
       0xe161e8a bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+236330634]
       0xe150376 testing::UnitTest::Run() [gtests_dbms+236258166]
       0x7dc6711 RUN_ALL_TESTS() [gtests_dbms+131884817]
       0x7dc2744 main [gtests_dbms+131868484]
  0x7fd3c9d9e555 __libc_start_main [libc.so.6+140629]
       0x4900ce9 <unknown symbol> [gtests_dbms+76549353]

[2023/12/29 09:33:16.729 +08:00] [INFO] [KVStore.cpp:654] ["Destroy KVStore"] [thread_id=1]
[0;31m[  FAILED  ] [mRegionKVStoreV2Test.KVStoreSingleSnap4 (286 ms)
```

### 4. What is your TiFlash version? (Required)
master

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #8590 close #8624 close #8625

Problem Summary:

The idea is mainly explained in #8590.

Also fix some problems.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
    upgrade test 
    image
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 1]
```diff
@@ -0,0 +1,279 @@
...
+        // Try serialize extra flags
+        if (binary_version >= 2)
+        {
+            static_assert(sizeof(eager_truncated_index) == sizeof(UInt64));
+            WriteBufferFromOwnString sub_buf;
+            auto sub_size = writeBinary2(eager_truncated_index, sub_buf);
+            RUNTIME_CHECK(sub_size, sizeof(UInt64));
+            auto s = sub_buf.releaseStr();
+            total_size += writePersistExtension(buf, RegionPersistFormat::EagerTruncate, s.data(), s.size());
+        }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:151]: In the current branch, the binary format of extra flags is
```
| UINT32 |               UINT64 |
|  flags | eager_truncate_index |
```

https://github.com/pingcap/tiflash/blob/43f809fffde22d0af4c519be4546a5bf4dde30a2/dbms/src/Storages/KVStore/Region.cpp#L178-L185

But in this commit, the binary format is
```
|               UINT64 | UINT32 |
| eager_truncate_index | flag |
```

Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:151]: It actually writes `sub_buf` rather than `buf`

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 2]
```diff
@@ -0,0 +1,272 @@
...
+                {
+                    auto bundle = std::any_cast<bundle_type>(v.value());
+                    if (bundle.first & 1)
+                    {
+                        if (extension_type == magic_enum::enum_underlying(RegionPersistExtension::TEST))
+                        {
+                            RUNTIME_CHECK(length == 4);
+                            RUNTIME_CHECK(readStringWithLength(buf, 4) == "abcd");
+                            debug_continue = true;
+                            *(bundle.second) += 1;
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:237]:
```suggestion
                            *(bundle.second) += 1;
                            continue;
```
I think you can directly write "continue;" here rather than defining a `debug_continue` and apply "continue" outside the `fiu_do_on`?

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 3]
```diff
@@ -0,0 +1,272 @@
...
+static constexpr UInt32 HAS_EAGER_TRUNCATE_INDEX = 0x01;
+// The upper bits are used to store length of extensions. DO NOT USE!
+} // namespace RegionPersistFormat
+
+using MaybeRegionPersistExtension = UInt32;
+enum class RegionPersistExtension : MaybeRegionPersistExtension
+{
+    TEST = 2,
+    // It should always be equal to the maximum supported type + 1
+    MaxKnownFlag = 3,
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:54]:
```suggestion
enum class RegionPersistExtension : MaybeRegionPersistExtension
{
    Reserved1 = 1,
    ReservedForTest = 2,
    // It should always be equal to the maximum supported type + 1
    MaxKnownFlag = 3,
```

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 4]
```diff
@@ -0,0 +1,272 @@
...
+};
+
+constexpr MaybeRegionPersistExtension UNUSED_EXTENSION_NUMBER_FOR_TEST = 99999;
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:57]: Better use `UINT32_MAX` instead of the magic number 99999

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 5]
```diff
@@ -0,0 +1,272 @@
...
+                    }
+                }
+            });
+
+            if (debug_continue)
+            {
+                continue;
+            }
+
+            if (extension_type >= magic_enum::enum_underlying(RegionPersistExtension::MaxKnownFlag))
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:252]:
```suggestion
            //Throw away unknown extension data
            if (extension_type >= magic_enum::enum_underlying(RegionPersistExtension::MaxKnownFlag))
```

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 6]
```diff
@@ -0,0 +1,272 @@
...
+            {
+                buf.ignore(length);
+                continue;
+            }
+
+            RUNTIME_CHECK_MSG(false, "Unhandled extension {} length={}", extension_type, length);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:258]:
```suggestion
            RUNTIME_CHECK_MSG(false, "Unhandled extension, type={} length={}", extension_type, length);
```

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 7]
```diff
@@ -0,0 +1,272 @@
...
+        const auto [meta_size, index] = meta.serialize(buf);
+        total_size += meta_size;
+        applied_index = index;
+
+        // Try serialize extra flags
+        if (binary_version >= 2)
+        {
+            static_assert(sizeof(eager_truncated_index) == sizeof(UInt64));
+            UInt32 flags = RegionPersistFormat::HAS_EAGER_TRUNCATE_INDEX;
+            flags |= (expected_extension_count << 1);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:119]: Brilliant!

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp (hunk 2 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:237]: It won't work, will go to `Check false failed: Unhandled extension 2 length=4`

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp (hunk 4 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:57]: fixed

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp (hunk 3 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:54]: fixed

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 8]
```diff
@@ -0,0 +1,276 @@
...
+    V2, // For eager gc
+};
+
+namespace RegionPersistFormat
+{
+static constexpr UInt32 HAS_EAGER_TRUNCATE_INDEX = 0x01;
+// The upper bits are used to store length of extensions. DO NOT USE!
+} // namespace RegionPersistFormat
+
+using MaybeRegionPersistExtension = UInt32;
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:49]: It may be a value bigger than MaybeRegionPersistExtension

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 9]
```diff
@@ -0,0 +1,276 @@
...
+enum class RegionPersistExtension : MaybeRegionPersistExtension
+{
+    Reserved1 = 1,
+    ReservedForTest = 2,
+    // It should always be equal to the maximum supported type + 1
+    MaxKnownFlag = 3,
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:55]: I want a manual check here. Consider it we deprecated some enums like
```
enum class {
    A = 1,
    // B = 2, // deprecated since V100
    C = 3,
}
```
It could result in silent error.

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 10]
```diff
@@ -0,0 +1,279 @@
...
+
+constexpr MaybeRegionPersistExtension UNUSED_EXTENSION_NUMBER_FOR_TEST = UINT32_MAX / 2;
+static_assert(!magic_enum::enum_contains<RegionPersistExtension>(UNUSED_EXTENSION_NUMBER_FOR_TEST));
+static_assert(std::is_same_v<MaybeRegionPersistExtension, UInt32>);
+static_assert(magic_enum::enum_underlying(RegionPersistExtension::MaxKnownFlag) <= UINT32_MAX / 2);
+static_assert(
+    magic_enum::enum_count(RegionPersistExtension)
+    == magic_enum::enum_underlying(RegionPersistExtension::MaxKnownFlag));
+
+constexpr UInt32 Region::CURRENT_VERSION = static_cast<UInt64>(RegionPersistVersion::V2);
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:66]:
```suggestion
constexpr UInt32 Region::CURRENT_VERSION = static_cast<UInt32>(RegionPersistVersion::V2);
```

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 11]
```diff
@@ -0,0 +1,279 @@
...
+        {
+            std::tie(binary_version, expected_extension_count) = std::any_cast<bundle_type>(v.value());
+            LOG_WARNING(
+                Logger::get(),
+                "Failpoint force_region_persist_version set region binary version, value={}, "
+                "expected_extension_count={}",
+                binary_version,
+                expected_extension_count);
+        }
+    });
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:108]: and it is better to add some comments about the failpoint

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 12]
```diff
@@ -0,0 +1,279 @@
...
+                    std::string s = "zzz";
+                    total_size += writePersistExtension(
+                        actual_extension_count,
+                        buf,
+                        UNUSED_EXTENSION_NUMBER_FOR_TEST,
+                        s.data(),
+                        s.size());
+                }
+            }
+        });
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:166]: seems too hacky...

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 13]
```diff
@@ -0,0 +1,279 @@
...
+        const auto [meta_size, index] = meta.serialize(buf);
+        total_size += meta_size;
+        applied_index = index;
+
+        // Try serialize extra flags
+        if (binary_version >= 2)
+        {
+            static_assert(sizeof(eager_truncated_index) == sizeof(UInt64));
+            UInt32 flags = RegionPersistFormat::HAS_EAGER_TRUNCATE_INDEX;
+            flags |= (expected_extension_count << 1);
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:125]: I perfer

```suggestion
            // The upper 31 bits are used to store the length of extensions, and the lowest bit is flag of eager gc.
            UInt32 flags = (expected_extension_count << 1) + 1;
```

File: dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp [hunk 14]
```diff
@@ -245,6 +248,220 @@ try
...
+    auto ext_cnt_1 = 0;
+    auto ext_cnt_2 = 0;
+    auto ext_cnt_3 = 1;
+    auto ext_cnt_4 = 2;
+    {
+        auto counter = std::make_shared<int>(0);
+        // V3 store, V3 load, no unrecognized fields
+        auto region = std::make_shared<Region>(createRegionMeta(1001, 1));
+        region->updateRaftLogEagerIndex(5678);
+        FailPointHelper::enableFailPoint(FailPoints::force_region_persist_version, std::make_pair(3, ext_cnt_3));
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp:264]:
```suggestion
        // V2 store, V2 load, no unrecognized fields
        auto region = std::make_shared<Region>(createRegionMeta(1001, 1));
        region->updateRaftLogEagerIndex(5678);
        FailPointHelper::enableFailPoint(FailPoints::force_region_persist_version, std::make_pair(2, ext_cnt_3));
```

File: dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp [hunk 15]
```diff
@@ -245,6 +248,220 @@ try
...
+        ASSERT_EQ(*counter, 1);
+
+        FailPointHelper::disableFailPoint(FailPoints::force_region_persist_version);
+        FailPointHelper::disableFailPoint(FailPoints::force_region_read_version);
+        FailPointHelper::disableFailPoint(FailPoints::force_region_persist_extension_field);
+        FailPointHelper::disableFailPoint(FailPoints::force_region_read_extension_field);
+    }
+    {
+        auto counter = std::make_shared<int>(0);
+        // Downgrade. V4(whatever) store, V3 load, UNUSED_EXTENSION_NUMBER_FOR_TEST unrecognized.
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp:288]:
```suggestion
        // Downgrade. V4(whatever) store, V2 load, UNUSED_EXTENSION_NUMBER_FOR_TEST unrecognized.
```

File: dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp [hunk 16]
```diff
@@ -245,6 +248,220 @@ try
...
+        // In V2, will also write UNUSED_EXTENSION_NUMBER_FOR_TEST.
+        FailPointHelper::enableFailPoint(FailPoints::force_region_persist_extension_field, static_cast<int>(1 | 2));
+        const auto path = dir_path + "/region2.test";
+        WriteBufferFromFile write_buf(path, DBMS_DEFAULT_BUFFER_SIZE, O_WRONLY | O_CREAT);
+        size_t region_ser_size = std::get<0>(region->serialize(write_buf));
+        write_buf.next();
+        write_buf.sync();
+        ASSERT_EQ(region_ser_size, (size_t)Poco::File(path).getSize());
+
+        FailPointHelper::enableFailPoint(FailPoints::force_region_read_version, static_cast<UInt64>(3));
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp:301]:
```suggestion
        FailPointHelper::enableFailPoint(FailPoints::force_region_read_version, static_cast<UInt64>(2));
```

**Review by JaySon-Huang — COMMENTED** [review]
Seems the tests are not updated after you remove the version 3

File: dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp (hunk 14 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp:264]: The test to test if we can successfully save and load the extension fields when we have a V3 in the future

File: dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp (hunk 15 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp:288]: These tests assume we have Test in V3 and UNUSED_EXTENSION_NUMBER_FOR_TEST in V4

File: dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp (hunk 16 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp:301]: ditto

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp (hunk 13 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:125]: I think `(expected_extension_count << 1) | RegionPersistFormat::HAS_EAGER_TRUNCATE_INDEX` is better.

File: dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp (hunk 14 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp:264]: But we need to ensure everything work well when reading with v2

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp (hunk 13 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:125]: The better add some more obvious comments, now the code makes me confused.

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp (hunk 12 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:166]: I found no better idea

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 17]
```diff
@@ -0,0 +1,279 @@
...
+                        actual_extension_count,
+                        buf,
+                        UNUSED_EXTENSION_NUMBER_FOR_TEST,
+                        s.data(),
+                        s.size());
+                }
+            }
+        });
+        RUNTIME_CHECK(
+            expected_extension_count == actual_extension_count,
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:168]: Because there is currently no extension. However, we have to support them here, because this will be picked into 7.5.1

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 18]
```diff
@@ -0,0 +1,279 @@
...
+        throw Exception(
+            ErrorCodes::LOGICAL_ERROR,
+            "Don't support downgrading from {} to {}",
+            binary_version,
+            current_version);
+    }
+    const auto binary_version_decoded = magic_enum::enum_cast<RegionPersistVersion>(binary_version);
+    if (!binary_version_decoded.has_value())
+    {
+        LOG_DEBUG(DB::Logger::get(), "Maybe downgrade from {} to {}", binary_version, current_version);
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:212]: If there is 30000 region, we could print 30000 times. However, I think this information may be not necessary. Because downgrading may be a common operation later.

File: dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp (hunk 14 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp:264]: There is already a test about V4 -> V2. Do you mean we should have another test for V2 -> V2.

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp (hunk 13 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:125]: How about I assert `static_assert(RegionPersistFormat::HAS_EAGER_TRUNCATE_INDEX == 0x01);` here?

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp (hunk 2 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:245]: I got it. Because there is a `do ... while(false)` in the macro `fiu_do_on()` :(

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp (hunk 12 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:182]: separate `serialize()` into 

```
serializeMeta()
serializeExtraFlag()
serializeExtension()
serializeData()
```

and then we can mock serializeExtension just in ut?

Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:182]: I can introduce a function for `serializeExtension`. However, the test for Region::serialize and Region::deserialize should be end-to-end. Because what I want to solve is compatibility between former different versions. I am can't split here, and test the mocked `serializeExtension`.

Comment (Lloyd-Pottiger) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:182]: ok, I have a better idea

```cpp
template<UInt32 version>
std::tuple<size_t, UInt64> Region::serialize(WriteBuffer & buf) const
{
    .......
    serializeExtension<version>(buf)
    .......
}

template<UInt32 version>
size_t serializeExtension(WriteBuffer & buf) const
{
    if constexpr (version >= 1)
    {
        // serialize Extension 1
        // you can mock some features here, just remove it and change to the real code when ungrade version.
    }
    if constexpr (version >= 2)
    {
        // serialize Extension 2
    }
    ......
}
```

**Review by Lloyd-Pottiger — APPROVED** [review]
Others LGTM

https://github.com/pingcap/tiflash/pull/8614#discussion_r1438252302

**Comment by Lloyd-Pottiger** [comment]
> Others LGTM
> 
> [#8614 (comment)](https://github.com/pingcap/tiflash/pull/8614#discussion_r1438252302)

https://github.com/CalvinNeo/tics/pull/6 I open a PR for this

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 19]
```diff
@@ -0,0 +1,176 @@
...
+        const auto [meta_size, index] = meta.serialize(buf);
+        total_size += meta_size;
+        applied_index = index;
+
+        // Try serialize extra flags
+        if (binary_version >= 2)
+        {
+            static_assert(sizeof(eager_truncated_index) == sizeof(UInt64));
+            // The upper 31 bits are used to store the length of extensions, and the lowest bit is flag of eager gc.
+            UInt32 flags = (expected_extension_count << 1) | RegionPersistFormat::HAS_EAGER_TRUNCATE_INDEX;
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:81]:
```
UInt32 flags = (expected_extension_count << 1) | magic_enum::enum_underlying(RegionPersistExtension::EagerTruncateIndex);
```
Maybe merge `EagerTruncateIndex = 1` into `RegionPersistExtension` and we can remove the `RegionPersistFormat`.

**Review by JaySon-Huang — APPROVED** [review]
LGTM with a non-blocking comment

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp (hunk 19 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:81]: This is kind of strange. Since if `EagerTruncateIndex = 1` is in `RegionPersistExtension`, other developers may wonder why we don't handle this in `deserializeImpl` and `serializeImpl`?

Comment (JaySon-Huang) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:81]: OK

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 20]
```diff
@@ -666,7 +666,7 @@ PrehandleResult KVStore::preHandleSSTsToDTFiles(
             if (unlikely(storage == nullptr))
             {
                 // The storage must be physically dropped, throw exception and do cleanup.
-                throw Exception("", ErrorCodes::TABLE_IS_DROPPED);
+                throw Exception("Can't get table", ErrorCodes::TABLE_IS_DROPPED);
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:669]: It is already added in an outer catch

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 21]
```diff
@@ -0,0 +1,176 @@
...
+}
+
+std::tuple<size_t, UInt64> Region::serializeImpl(
+    UInt32 binary_version,
+    UInt32 expected_extension_count,
+    std::function<size_t(UInt32 &, WriteBuffer &)> extra_handler,
+    WriteBuffer & buf) const
+{
+    size_t total_size = writeBinary2(binary_version, buf);
+    UInt64 applied_index = -1;
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:66]: fixed

**Review by Lloyd-Pottiger — APPROVED** [review]

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 22]
```diff
@@ -750,7 +750,9 @@ PrehandleResult KVStore::preHandleSSTsToDTFiles(
                 if (force_decode)
                 {
                     // Can not decode data with `force_decode == true`, must be something wrong
-                    throw Exception(result.extra_msg, ErrorCodes::REGION_DATA_SCHEMA_UPDATED);
+                    throw Exception(
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:753]: fixed

File: dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp [hunk 23]
```diff
@@ -0,0 +1,170 @@
...
+    WriteBuffer & buf) const
+{
+    size_t total_size = writeBinary2(binary_version, buf);
+
+    std::shared_lock<std::shared_mutex> lock(mutex);
+
+    // Serialize meta
+    const auto [meta_size, index] = meta.serialize(buf);
+    total_size += meta_size;
+    UInt64 applied_index = applied_index = index;
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp:72]:
```suggestion
    UInt64 applied_index = index;
```

Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp]: just remove `index`

**Comment by CalvinNeo** [comment]
```

**Comment by CalvinNeo** [comment]
```
[2024/01/03 01:45:31.814 +08:00] [ERROR] [SegmentReader.cpp:118] ["ErrMsg: Argument at index 1 for function fromUnixTime must be constant StackTrace \n       0x42ad38e\tStackTrace::StackTrace() [tiflash+69915534]\n       0x429bb62\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+69843810]\n       0x459a481\tDB::Exception::Exception<unsigned long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) [tiflash+72983681]\n       0xdf315f8\tDB::IExecutableFunction::defaultImplementationForConstantArguments(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long) const [tiflash+234034680]\n       0xdf31ec1\tDB::IExecutableFunction::execute(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long) const [tiflash+234036929]\n       0x478c45e\tDB::IFunctionBase::execute(DB::Block&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long) const [tiflash+75023454]\n       0xcb3cb4a\tDB::ExpressionAction::execute(DB::Block&) const [tiflash+213109578]\n       0xcb3e6aa\tDB::ExpressionActions::execute(DB::Block&) const [tiflash+213116586]\n       0xc72ffee\tDB::FilterTransformAction::FilterTransformAction(DB::Block const&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [tiflash+208863214]\n       0xc72d4c6\tDB::FilterBlockInputStream::FilterBlockInputStream(std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [tiflash+208852166]\n       0xc44dbe7\tDB::FilterBlockInputStream* std::__1::construct_at<DB::FilterBlockInputStream, std::__1::shared_ptr<DB::IBlockInputStream>&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::FilterBlockInputStream*>(DB::FilterBlockInputStream*, std::__1::shared_ptr<DB::IBlockInputStream>&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [tiflash+205839335]\n       0xc44d990\tvoid std::__1::allocator_traits<std::__1::allocator<DB::FilterBlockInputStream> >::construct<DB::FilterBlockInputStream, std::__1::shared_ptr<DB::IBlockInputStream>&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void, void>(std::__1::allocator<DB::FilterBlockInputStream>&, DB::FilterBlockInputStream*, std::__1::shared_ptr<DB::IBlockInputStream>&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [tiflash+205838736]\n       0xc44d683\tstd::__1::__shared_ptr_emplace<DB::FilterBlockInputStream, std::__1::allocator<DB::FilterBlockInputStream> >::__shared_ptr_emplace<std::__1::shared_ptr<DB::IBlockInputStream>&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::allocator<DB::FilterBlockInputStream>, std::__1::shared_ptr<DB::IBlockInputStream>&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [tiflash+205837955]\n       0xc44d495\tstd::__1::shared_ptr<DB::FilterBlockInputStream> std::__1::allocate_shared<DB::FilterBlockInputStream, std::__1::allocator<DB::FilterBlockInputStream>, std::__1::shared_ptr<DB::IBlockInputStream>&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void>(std::__1::allocator<DB::FilterBlockInputStream> const&, std::__1::shared_ptr<DB::IBlockInputStream>&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [tiflash+205837461]\n       0xc3cc15c\tstd::__1::shared_ptr<DB::FilterBlockInputStream> std::__1::make_shared<DB::FilterBlockInputStream, std::__1::shared_ptr<DB::IBlockInputStream>&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void>(std::__1::shared_ptr<DB::IBlockInputStream>&, std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [tiflash+205308252]\n       0xc3ba9fc\tDB::DM::Segment::getLateMaterializationStream(std::__1::shared_ptr<DB::DM::BitmapFilter>&&, DB::DM::DMContext const&, std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > const&, std::__1::shared_ptr<DB::DM::SegmentSnapshot> const&, std::__1::vector<DB::DM::RowKeyRange, std::__1::allocator<DB::DM::RowKeyRange> > const&, std::__1::shared_ptr<DB::DM::PushDownFilter> const&, unsigned long, unsigned long) [tiflash+205236732]\n       0xc3a4818\tDB::DM::Segment::getBitmapFilterInputStream(DB::DM::DMContext const&, std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > const&, std::__1::shared_ptr<DB::DM::SegmentSnapshot> const&, std::__1::vector<DB::DM::RowKeyRange, std::__1::allocator<DB::DM::RowKeyRange> > const&, std::__1::shared_ptr<DB::DM::PushDownFilter> const&, unsigned long, unsigned long, unsigned long) [tiflash+205146136]\n       0xc3a28e2\tDB::DM::Segment::getInputStream(DB::DM::ReadMode const&, DB::DM::DMContext const&, std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > const&, std::__1::shared_ptr<DB::DM::SegmentSnapshot> const&, std::__1::vector<DB::DM::RowKeyRange, std::__1::allocator<DB::DM::RowKeyRange> > const&, std::__1::shared_ptr<DB::DM::PushDownFilter> const&, unsigned long, unsigned long) [tiflash+205138146]\n       0xc476727\tDB::DM::SegmentReadTask::doInitInputStream(std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > const&, unsigned long, std::__1::shared_ptr<DB::DM::PushDownFilter> const&, DB::DM::ReadMode, unsigned long) [tiflash+206006055]\n       0xc4761ef\tDB::DM::SegmentReadTask::doInitInputStreamWithErrorFallback(std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > const&, unsigned long, std::__1::shared_ptr<DB::DM::PushDownFilter> const&, DB::DM::ReadMode, unsigned long, bool) [tiflash+206004719]\n       0xc475fba\tDB::DM::SegmentReadTask::initInputStream(std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > const&, unsigned long, std::__1::shared_ptr<DB::DM::PushDownFilter> const&, DB::DM::ReadMode, unsigned long, bool) [tiflash+206004154]\n       0xc4af9fe\tDB::DM::SegmentReadTaskPool::buildInputStream(std::__1::shared_ptr<DB::DM::SegmentReadTask>&) [tiflash+206240254]\n       0xc65c4c1\tDB::DM::MergedTask::initOnce() [tiflash+207996097]\n       0xc65c3d9\tDB::DM::MergedTask::readBlock() [tiflash+207995865]\n       0xc66bacb\tDB::DM::SegmentReader::readSegments() [tiflash+208059083]\n       0xc66adde\tDB::DM::SegmentReader::run() [tiflash+208055774]\n       0xc66de59\tdecltype(*(static_cast<DB::DM::SegmentReader*>(fp0)).*fp()) std::__1::__invoke<void (DB::DM::SegmentReader::*)(), DB::DM::SegmentReader*, void>(void (DB::DM::SegmentReader::*&&)(), DB::DM::SegmentReader*&&) [tiflash+208068185]\n       0xc66ddde\tvoid std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::DM::SegmentReader::*)(), DB::DM::SegmentReader*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::DM::SegmentReader::*)(), DB::DM::SegmentReader*>&, std::__1::__tuple_indices<2ul>) [tiflash+208068062]\n       0xc66daf2\tvoid* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::DM::SegmentReader::*)(), DB::DM::SegmentReader*> >(void*) [tiflash+208067314]\n  0x7f4e388e1ea5\tstart_thread [libpthread.so.0+32421]\n  0x7f4e381f096d\t__clone [libc.so.6+1042797]"] [source="MPP<gather_id:1, query_ts:1704217531646343366, local_query_id:302, server_id:173, start_ts:446750400603750405,task_id:1> table_id=525"] [thread_id=36]

```

**Comment by JaySon-Huang** [comment]
https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-integration-tests/detail/tiflash-ghpr-integration-tests/15729/pipeline/265
```
[2024-01-03T01:12:33.468Z]   File: fullstack-test2/ddl/flashback/flashback_database.test
[2024-01-03T01:12:33.468Z]   Error line: 167
[2024-01-03T01:12:33.468Z]   Error: set session tidb_isolation_read_engines='tiflash'; select * from d1_new.t2 order by id;
[2024-01-03T01:12:33.468Z]   Result:
[2024-01-03T01:12:33.468Z]     ERROR 1105 (HY000) at line 1: DB::TiFlashException: Failed to register MPP Task MPP<gather_id:1, query_ts:1704244343012329513, local_query_id:248, server_id:132, start_ts:446757429042216965,task_id:1>, reason: task is already registered
[2024-01-03T01:12:33.468Z]   Expected:
[2024-01-03T01:12:33.468Z]     +----+------+------+
[2024-01-03T01:12:33.468Z]     | id | name | b    |
[2024-01-03T01:12:33.468Z]     +----+------+------+
[2024-01-03T01:12:33.468Z]     |  1 | abc  | NULL |
[2024-01-03T01:12:33.468Z]     |  2 | cde  | NULL |
[2024-01-03T01:12:33.468Z]     | 53 | efg  | NULL |
[2024-01-03T01:12:33.468Z]     +----+------+------+
```
