### PR TITLE
*: Fix build astToExecutorUtils

### LINKED ISSUE #5907: tiflash build failed on Ubuntu 20.04
### 1. Minimal reproduce step (Required)
After updating 5ddccf4c8a1, the build failed on ubuntu20.04.
```c++
[0/2] Re-checking globbed directories...
[1/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/TimezoneInfo.cpp.o
[2/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/SettingsCommon.cpp.o
[3/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Debug/MockExecutor/astToExecutorUtils.cpp.o
FAILED: dbms/CMakeFiles/dbms.dir/src/Debug/MockExecutor/astToExecutorUtils.cpp.o 
/usr/bin/clang++-13 -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB -DBOOST_CONTEXT_STATIC_LINK -DBOOST_FIBER_NO_LIB -DBOOST_FIBER_STATIC_LINK -DBOOST_SYSTEM_NO_DEPRECATED -DCARES_STATICLIB -DFIU_ENABLE -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DMULTIPLE_CONTEXT_GTEST -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DSTACK_LINE_READER_BUFFER_SIZE=1024 -DTIFLASH_COMPILER_VPCLMULQDQ_SUPPORT=1 -DTIFLASH_ENABLE_AVX512_SUPPORT=1 -DTIFLASH_ENABLE_AVX_SUPPORT=1 -DTIFLASH_SOURCE_PREFIX=\"/home/simple/tiflash\" -I/home/simple/tiflash/contrib/libsparsehash -I/home/simple/tiflash/contrib/libdivide -I/home/simple/tiflash/dbms/src -I/home/simple/tiflash/contrib/tiflash-proxy/raftstore-proxy/ffi/src -I/home/simple/tiflash/build/dbms/src -I/home/simple/tiflash/contrib/double-conversion -I/home/simple/tiflash/contrib/boost -I/home/simple/tiflash/contrib/xxHash -I/home/simple/tiflash/contrib/libpcg-random/include -I/home/simple/tiflash/contrib/libcityhash/include -I/home/simple/tiflash/libs/libcommon/include -I/home/simple/tiflash/build/libs/libcommon/include -I/home/simple/tiflash/libs/libpocoext/include -I/home/simple/tiflash/contrib/poco/Data/include -I/home/simple/tiflash/contrib/poco/Foundation/include -I/home/simple/tiflash/contrib/zlib-ng -I/home/simple/tiflash/build/contrib/zlib-ng -I/home/simple/tiflash/contrib/poco/Util/include -I/home/simple/tiflash/contrib/poco/XML/include -I/home/simple/tiflash/contrib/poco/JSON/include -I/home/simple/tiflash/contrib/poco/Net/include -I/home/simple/tiflash/contrib/cctz/include -I/home/simple/tiflash/contrib/jemalloc/include -I/home/simple/tiflash/contrib/jemalloc-cmake/include -I/home/simple/tiflash/contrib/cpu_features/include -I/home/simple/tiflash/contrib/libcpuid/include -I/home/simple/tiflash/contrib/lz4/lib -I/home/simple/tiflash/contrib/zstd/lib -I/home/simple/tiflash/contrib/client-c/third_party/libfiu/libfiu -I/home/simple/tiflash/contrib/prometheus-cpp/core/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/core/include -I/home/simple/tiflash/contrib/prometheus-cpp/push/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/push/include -I/home/simple/tiflash/contrib/prometheus-cpp/pull/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/pull/include -I/home/simple/tiflash/contrib/cpptoml -I/home/simple/tiflash/contrib/magic_enum/include -I/home/simple/tiflash/contrib/poco/NetSSL_OpenSSL/include -I/home/simple/tiflash/contrib/poco/Crypto/include -I/home/simple/tiflash/contrib/xxHash/cmake_unofficial/.. -I/home/simple/tiflash/build/contrib/kvproto/cpp -I/home/simple/tiflash/build/contrib/kvproto/cpp/kvproto -I/home/simple/tiflash/contrib/grpc/include -I/home/simple/tiflash/contrib/abseil-cpp -I/home/simple/tiflash/contrib/client-c/include -I/home/simple/tiflash/build/contrib/grpc/third_party/cares/cares -I/home/simple/tiflash/contrib/grpc/third_party/cares/cares -I/home/simple/tiflash/build/contrib/tipb/cpp -I/home/simple/tiflash/build/dbms/src/Storages/DeltaMerge/File/dtpb -I/home/simple/tiflash/contrib/libbtrie/include -isystem /home/simple/tiflash/contrib/fmtlib-cmake/../fmtlib/include -isystem /home/simple/tiflash/libs/libsymbolization/include -isystem /home/simple/tiflash/contrib/protobuf/src -isystem /home/simple/tiflash/contrib/re2 -isystem /home/simple/tiflash/build/contrib/re2-cmake -D__GLIBCXX_BITSIZE_INT_N_0=128 -D__GLIBCXX_TYPE_INT_N_0=__int128  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor  -Wextra -Werror -g -g3 -ggdb3 -O0 -fverbose-asm -fno-inline  -fPIC -DDUMMY_BACKTRACE -pthread -std=gnu++17 -MD -MT dbms/CMakeFiles/dbms.dir/src/Debug/MockExecutor/astToExecutorUtils.cpp.o -MF dbms/CMakeFiles/dbms.dir/src/Debug/MockExecutor/astToExecutorUtils.cpp.o.d -o dbms/CMakeFiles/dbms.dir/src/Debug/MockExecutor/astToExecutorUtils.cpp.o -c /home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutorUtils.cpp
In file included from /home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutorUtils.cpp:15:
/home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutorUtils.h:40:6: error: no template named '__wrap_iter' in namespace 'std'
std::__wrap_iter<const std::pair<std::string, TiDB::ColumnInfo> *> checkSchema(const DAGSchema & input, String checked_column);
~~~~~^
/home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutorUtils.cpp:45:6: error: no template named '__wrap_iter' in namespace 'std'
std::__wrap_iter<const std::pair<std::string, TiDB::ColumnInfo> *> checkSchema(const DAGSchema & input, String checked_column)
~~~~~^
/home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutorUtils.cpp:55:12: error: no viable conversion from returned value of type '__gnu_cxx::__normal_iterator<const std::pair<std::basic_string<char>, TiDB::ColumnInfo> *, std::vector<std::pair<std::basic_string<char>, TiDB::ColumnInfo>>>' to function return type 'int'
    return ft;
           ^~
3 errors generated.
[4/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/SecurityManager.cpp.o
[5/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/TablesStatus.cpp.o
[6/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/Settings.cpp.o
[7/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/WindowDescription.cpp.o
[8/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/convertFieldToType.cpp.o
[9/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/SetVariants.cpp.o
[10/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/Users.cpp.o
[11/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/castColumn.cpp.o
[12/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/createBlockSelector.cpp.o
[13/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/Set.cpp.o
[14/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Interpreters/evaluateConstantExpression.cpp.o
[15/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Debug/DBGInvoker.cpp.o
FAILED: dbms/CMakeFiles/dbms.dir/src/Debug/DBGInvoker.cpp.o 
/usr/bin/clang++-13 -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB -DBOOST_CONTEXT_STATIC_LINK -DBOOST_FIBER_NO_LIB -DBOOST_FIBER_STATIC_LINK -DBOOST_SYSTEM_NO_DEPRECATED -DCARES_STATICLIB -DFIU_ENABLE -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DMULTIPLE_CONTEXT_GTEST -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DSTACK_LINE_READER_BUFFER_SIZE=1024 -DTIFLASH_COMPILER_VPCLMULQDQ_SUPPORT=1 -DTIFLASH_ENABLE_AVX512_SUPPORT=1 -DTIFLASH_ENABLE_AVX_SUPPORT=1 -DTIFLASH_SOURCE_PREFIX=\"/home/simple/tiflash\" -I/home/simple/tiflash/contrib/libsparsehash -I/home/simple/tiflash/contrib/libdivide -I/home/simple/tiflash/dbms/src -I/home/simple/tiflash/contrib/tiflash-proxy/raftstore-proxy/ffi/src -I/home/simple/tiflash/build/dbms/src -I/home/simple/tiflash/contrib/double-conversion -I/home/simple/tiflash/contrib/boost -I/home/simple/tiflash/contrib/xxHash -I/home/simple/tiflash/contrib/libpcg-random/include -I/home/simple/tiflash/contrib/libcityhash/include -I/home/simple/tiflash/libs/libcommon/include -I/home/simple/tiflash/build/libs/libcommon/include -I/home/simple/tiflash/libs/libpocoext/include -I/home/simple/tiflash/contrib/poco/Data/include -I/home/simple/tiflash/contrib/poco/Foundation/include -I/home/simple/tiflash/contrib/zlib-ng -I/home/simple/tiflash/build/contrib/zlib-ng -I/home/simple/tiflash/contrib/poco/Util/include -I/home/simple/tiflash/contrib/poco/XML/include -I/home/simple/tiflash/contrib/poco/JSON/include -I/home/simple/tiflash/contrib/poco/Net/include -I/home/simple/tiflash/contrib/cctz/include -I/home/simple/tiflash/contrib/jemalloc/include -I/home/simple/tiflash/contrib/jemalloc-cmake/include -I/home/simple/tiflash/contrib/cpu_features/include -I/home/simple/tiflash/contrib/libcpuid/include -I/home/simple/tiflash/contrib/lz4/lib -I/home/simple/tiflash/contrib/zstd/lib -I/home/simple/tiflash/contrib/client-c/third_party/libfiu/libfiu -I/home/simple/tiflash/contrib/prometheus-cpp/core/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/core/include -I/home/simple/tiflash/contrib/prometheus-cpp/push/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/push/include -I/home/simple/tiflash/contrib/prometheus-cpp/pull/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/pull/include -I/home/simple/tiflash/contrib/cpptoml -I/home/simple/tiflash/contrib/magic_enum/include -I/home/simple/tiflash/contrib/poco/NetSSL_OpenSSL/include -I/home/simple/tiflash/contrib/poco/Crypto/include -I/home/simple/tiflash/contrib/xxHash/cmake_unofficial/.. -I/home/simple/tiflash/build/contrib/kvproto/cpp -I/home/simple/tiflash/build/contrib/kvproto/cpp/kvproto -I/home/simple/tiflash/contrib/grpc/include -I/home/simple/tiflash/contrib/abseil-cpp -I/home/simple/tiflash/contrib/client-c/include -I/home/simple/tiflash/build/contrib/grpc/third_party/cares/cares -I/home/simple/tiflash/contrib/grpc/third_party/cares/cares -I/home/simple/tiflash/build/contrib/tipb/cpp -I/home/simple/tiflash/build/dbms/src/Storages/DeltaMerge/File/dtpb -I/home/simple/tiflash/contrib/libbtrie/include -isystem /home/simple/tiflash/contrib/fmtlib-cmake/../fmtlib/include -isystem /home/simple/tiflash/libs/libsymbolization/include -isystem /home/simple/tiflash/contrib/protobuf/src -isystem /home/simple/tiflash/contrib/re2 -isystem /home/simple/tiflash/build/contrib/re2-cmake -D__GLIBCXX_BITSIZE_INT_N_0=128 -D__GLIBCXX_TYPE_INT_N_0=__int128  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor  -Wextra -Werror -g -g3 -ggdb3 -O0 -fverbose-asm -fno-inline  -fPIC -DDUMMY_BACKTRACE -pthread -std=gnu++17 -MD -MT dbms/CMakeFiles/dbms.dir/src/Debug/DBGInvoker.cpp.o -MF dbms/CMakeFiles/dbms.dir/src/Debug/DBGInvoker.cpp.o.d -o dbms/CMakeFiles/dbms.dir/src/Debug/DBGInvoker.cpp.o -c /home/simple/tiflash/dbms/src/Debug/DBGInvoker.cpp
In file included from /home/simple/tiflash/dbms/src/Debug/DBGInvoker.cpp:19:
In file included from /home/simple/tiflash/dbms/src/Debug/dbgFuncCoprocessor.h:19:
In file included from /home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutor.h:19:
/home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutorUtils.h:40:6: error: no template named '__wrap_iter' in namespace 'std'
std::__wrap_iter<const std::pair<std::string, TiDB::ColumnInfo> *> checkSchema(const DAGSchema & input, String checked_column);
~~~~~^
1 error generated.
[16/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Debug/dbgNaturalDag.cpp.o
FAILED: dbms/CMakeFiles/dbms.dir/src/Debug/dbgNaturalDag.cpp.o 
/usr/bin/clang++-13 -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB -DBOOST_CONTEXT_STATIC_LINK -DBOOST_FIBER_NO_LIB -DBOOST_FIBER_STATIC_LINK -DBOOST_SYSTEM_NO_DEPRECATED -DCARES_STATICLIB -DFIU_ENABLE -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DMULTIPLE_CONTEXT_GTEST -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DSTACK_LINE_READER_BUFFER_SIZE=1024 -DTIFLASH_COMPILER_VPCLMULQDQ_SUPPORT=1 -DTIFLASH_ENABLE_AVX512_SUPPORT=1 -DTIFLASH_ENABLE_AVX_SUPPORT=1 -DTIFLASH_SOURCE_PREFIX=\"/home/simple/tiflash\" -I/home/simple/tiflash/contrib/libsparsehash -I/home/simple/tiflash/contrib/libdivide -I/home/simple/tiflash/dbms/src -I/home/simple/tiflash/contrib/tiflash-proxy/raftstore-proxy/ffi/src -I/home/simple/tiflash/build/dbms/src -I/home/simple/tiflash/contrib/double-conversion -I/home/simple/tiflash/contrib/boost -I/home/simple/tiflash/contrib/xxHash -I/home/simple/tiflash/contrib/libpcg-random/include -I/home/simple/tiflash/contrib/libcityhash/include -I/home/simple/tiflash/libs/libcommon/include -I/home/simple/tiflash/build/libs/libcommon/include -I/home/simple/tiflash/libs/libpocoext/include -I/home/simple/tiflash/contrib/poco/Data/include -I/home/simple/tiflash/contrib/poco/Foundation/include -I/home/simple/tiflash/contrib/zlib-ng -I/home/simple/tiflash/build/contrib/zlib-ng -I/home/simple/tiflash/contrib/poco/Util/include -I/home/simple/tiflash/contrib/poco/XML/include -I/home/simple/tiflash/contrib/poco/JSON/include -I/home/simple/tiflash/contrib/poco/Net/include -I/home/simple/tiflash/contrib/cctz/include -I/home/simple/tiflash/contrib/jemalloc/include -I/home/simple/tiflash/contrib/jemalloc-cmake/include -I/home/simple/tiflash/contrib/cpu_features/include -I/home/simple/tiflash/contrib/libcpuid/include -I/home/simple/tiflash/contrib/lz4/lib -I/home/simple/tiflash/contrib/zstd/lib -I/home/simple/tiflash/contrib/client-c/third_party/libfiu/libfiu -I/home/simple/tiflash/contrib/prometheus-cpp/core/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/core/include -I/home/simple/tiflash/contrib/prometheus-cpp/push/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/push/include -I/home/simple/tiflash/contrib/prometheus-cpp/pull/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/pull/include -I/home/simple/tiflash/contrib/cpptoml -I/home/simple/tiflash/contrib/magic_enum/include -I/home/simple/tiflash/contrib/poco/NetSSL_OpenSSL/include -I/home/simple/tiflash/contrib/poco/Crypto/include -I/home/simple/tiflash/contrib/xxHash/cmake_unofficial/.. -I/home/simple/tiflash/build/contrib/kvproto/cpp -I/home/simple/tiflash/build/contrib/kvproto/cpp/kvproto -I/home/simple/tiflash/contrib/grpc/include -I/home/simple/tiflash/contrib/abseil-cpp -I/home/simple/tiflash/contrib/client-c/include -I/home/simple/tiflash/build/contrib/grpc/third_party/cares/cares -I/home/simple/tiflash/contrib/grpc/third_party/cares/cares -I/home/simple/tiflash/build/contrib/tipb/cpp -I/home/simple/tiflash/build/dbms/src/Storages/DeltaMerge/File/dtpb -I/home/simple/tiflash/contrib/libbtrie/include -isystem /home/simple/tiflash/contrib/fmtlib-cmake/../fmtlib/include -isystem /home/simple/tiflash/libs/libsymbolization/include -isystem /home/simple/tiflash/contrib/protobuf/src -isystem /home/simple/tiflash/contrib/re2 -isystem /home/simple/tiflash/build/contrib/re2-cmake -D__GLIBCXX_BITSIZE_INT_N_0=128 -D__GLIBCXX_TYPE_INT_N_0=__int128  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor  -Wextra -Werror -g -g3 -ggdb3 -O0 -fverbose-asm -fno-inline  -fPIC -DDUMMY_BACKTRACE -pthread -std=gnu++17 -MD -MT dbms/CMakeFiles/dbms.dir/src/Debug/dbgNaturalDag.cpp.o -MF dbms/CMakeFiles/dbms.dir/src/Debug/dbgNaturalDag.cpp.o.d -o dbms/CMakeFiles/dbms.dir/src/Debug/dbgNaturalDag.cpp.o -c /home/simple/tiflash/dbms/src/Debug/dbgNaturalDag.cpp
In file included from /home/simple/tiflash/dbms/src/Debug/dbgNaturalDag.cpp:17:
In file included from /home/simple/tiflash/dbms/src/Debug/dbgFuncCoprocessor.h:19:
In file included from /home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutor.h:19:
/home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutorUtils.h:40:6: error: no template named '__wrap_iter' in namespace 'std'
std::__wrap_iter<const std::pair<std::string, TiDB::ColumnInfo> *> checkSchema(const DAGSchema & input, String checked_column);
~~~~~^
1 error generated.
[17/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Debug/dbgFuncCoprocessor.cpp.o
FAILED: dbms/CMakeFiles/dbms.dir/src/Debug/dbgFuncCoprocessor.cpp.o 
/usr/bin/clang++-13 -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB -DBOOST_CONTEXT_STATIC_LINK -DBOOST_FIBER_NO_LIB -DBOOST_FIBER_STATIC_LINK -DBOOST_SYSTEM_NO_DEPRECATED -DCARES_STATICLIB -DFIU_ENABLE -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DMULTIPLE_CONTEXT_GTEST -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DSTACK_LINE_READER_BUFFER_SIZE=1024 -DTIFLASH_COMPILER_VPCLMULQDQ_SUPPORT=1 -DTIFLASH_ENABLE_AVX512_SUPPORT=1 -DTIFLASH_ENABLE_AVX_SUPPORT=1 -DTIFLASH_SOURCE_PREFIX=\"/home/simple/tiflash\" -I/home/simple/tiflash/contrib/libsparsehash -I/home/simple/tiflash/contrib/libdivide -I/home/simple/tiflash/dbms/src -I/home/simple/tiflash/contrib/tiflash-proxy/raftstore-proxy/ffi/src -I/home/simple/tiflash/build/dbms/src -I/home/simple/tiflash/contrib/double-conversion -I/home/simple/tiflash/contrib/boost -I/home/simple/tiflash/contrib/xxHash -I/home/simple/tiflash/contrib/libpcg-random/include -I/home/simple/tiflash/contrib/libcityhash/include -I/home/simple/tiflash/libs/libcommon/include -I/home/simple/tiflash/build/libs/libcommon/include -I/home/simple/tiflash/libs/libpocoext/include -I/home/simple/tiflash/contrib/poco/Data/include -I/home/simple/tiflash/contrib/poco/Foundation/include -I/home/simple/tiflash/contrib/zlib-ng -I/home/simple/tiflash/build/contrib/zlib-ng -I/home/simple/tiflash/contrib/poco/Util/include -I/home/simple/tiflash/contrib/poco/XML/include -I/home/simple/tiflash/contrib/poco/JSON/include -I/home/simple/tiflash/contrib/poco/Net/include -I/home/simple/tiflash/contrib/cctz/include -I/home/simple/tiflash/contrib/jemalloc/include -I/home/simple/tiflash/contrib/jemalloc-cmake/include -I/home/simple/tiflash/contrib/cpu_features/include -I/home/simple/tiflash/contrib/libcpuid/include -I/home/simple/tiflash/contrib/lz4/lib -I/home/simple/tiflash/contrib/zstd/lib -I/home/simple/tiflash/contrib/client-c/third_party/libfiu/libfiu -I/home/simple/tiflash/contrib/prometheus-cpp/core/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/core/include -I/home/simple/tiflash/contrib/prometheus-cpp/push/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/push/include -I/home/simple/tiflash/contrib/prometheus-cpp/pull/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/pull/include -I/home/simple/tiflash/contrib/cpptoml -I/home/simple/tiflash/contrib/magic_enum/include -I/home/simple/tiflash/contrib/poco/NetSSL_OpenSSL/include -I/home/simple/tiflash/contrib/poco/Crypto/include -I/home/simple/tiflash/contrib/xxHash/cmake_unofficial/.. -I/home/simple/tiflash/build/contrib/kvproto/cpp -I/home/simple/tiflash/build/contrib/kvproto/cpp/kvproto -I/home/simple/tiflash/contrib/grpc/include -I/home/simple/tiflash/contrib/abseil-cpp -I/home/simple/tiflash/contrib/client-c/include -I/home/simple/tiflash/build/contrib/grpc/third_party/cares/cares -I/home/simple/tiflash/contrib/grpc/third_party/cares/cares -I/home/simple/tiflash/build/contrib/tipb/cpp -I/home/simple/tiflash/build/dbms/src/Storages/DeltaMerge/File/dtpb -I/home/simple/tiflash/contrib/libbtrie/include -isystem /home/simple/tiflash/contrib/fmtlib-cmake/../fmtlib/include -isystem /home/simple/tiflash/libs/libsymbolization/include -isystem /home/simple/tiflash/contrib/protobuf/src -isystem /home/simple/tiflash/contrib/re2 -isystem /home/simple/tiflash/build/contrib/re2-cmake -D__GLIBCXX_BITSIZE_INT_N_0=128 -D__GLIBCXX_TYPE_INT_N_0=__int128  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor  -Wextra -Werror -g -g3 -ggdb3 -O0 -fverbose-asm -fno-inline  -fPIC -DDUMMY_BACKTRACE -pthread -std=gnu++17 -MD -MT dbms/CMakeFiles/dbms.dir/src/Debug/dbgFuncCoprocessor.cpp.o -MF dbms/CMakeFiles/dbms.dir/src/Debug/dbgFuncCoprocessor.cpp.o.d -o dbms/CMakeFiles/dbms.dir/src/Debug/dbgFuncCoprocessor.cpp.o -c /home/simple/tiflash/dbms/src/Debug/dbgFuncCoprocessor.cpp
In file included from /home/simple/tiflash/dbms/src/Debug/dbgFuncCoprocessor.cpp:23:
In file included from /home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutor.h:19:
/home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutorUtils.h:40:6: error: no template named '__wrap_iter' in namespace 'std'
std::__wrap_iter<const std::pair<std::string, TiDB::ColumnInfo> *> checkSchema(const DAGSchema & input, String checked_column);
~~~~~^
1 error generated.
[18/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Debug/MockExecutor/astToExecutor.cpp.o
FAILED: dbms/CMakeFiles/dbms.dir/src/Debug/MockExecutor/astToExecutor.cpp.o 
/usr/bin/clang++-13 -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB -DBOOST_CONTEXT_STATIC_LINK -DBOOST_FIBER_NO_LIB -DBOOST_FIBER_STATIC_LINK -DBOOST_SYSTEM_NO_DEPRECATED -DCARES_STATICLIB -DFIU_ENABLE -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DMULTIPLE_CONTEXT_GTEST -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DSTACK_LINE_READER_BUFFER_SIZE=1024 -DTIFLASH_COMPILER_VPCLMULQDQ_SUPPORT=1 -DTIFLASH_ENABLE_AVX512_SUPPORT=1 -DTIFLASH_ENABLE_AVX_SUPPORT=1 -DTIFLASH_SOURCE_PREFIX=\"/home/simple/tiflash\" -I/home/simple/tiflash/contrib/libsparsehash -I/home/simple/tiflash/contrib/libdivide -I/home/simple/tiflash/dbms/src -I/home/simple/tiflash/contrib/tiflash-proxy/raftstore-proxy/ffi/src -I/home/simple/tiflash/build/dbms/src -I/home/simple/tiflash/contrib/double-conversion -I/home/simple/tiflash/contrib/boost -I/home/simple/tiflash/contrib/xxHash -I/home/simple/tiflash/contrib/libpcg-random/include -I/home/simple/tiflash/contrib/libcityhash/include -I/home/simple/tiflash/libs/libcommon/include -I/home/simple/tiflash/build/libs/libcommon/include -I/home/simple/tiflash/libs/libpocoext/include -I/home/simple/tiflash/contrib/poco/Data/include -I/home/simple/tiflash/contrib/poco/Foundation/include -I/home/simple/tiflash/contrib/zlib-ng -I/home/simple/tiflash/build/contrib/zlib-ng -I/home/simple/tiflash/contrib/poco/Util/include -I/home/simple/tiflash/contrib/poco/XML/include -I/home/simple/tiflash/contrib/poco/JSON/include -I/home/simple/tiflash/contrib/poco/Net/include -I/home/simple/tiflash/contrib/cctz/include -I/home/simple/tiflash/contrib/jemalloc/include -I/home/simple/tiflash/contrib/jemalloc-cmake/include -I/home/simple/tiflash/contrib/cpu_features/include -I/home/simple/tiflash/contrib/libcpuid/include -I/home/simple/tiflash/contrib/lz4/lib -I/home/simple/tiflash/contrib/zstd/lib -I/home/simple/tiflash/contrib/client-c/third_party/libfiu/libfiu -I/home/simple/tiflash/contrib/prometheus-cpp/core/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/core/include -I/home/simple/tiflash/contrib/prometheus-cpp/push/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/push/include -I/home/simple/tiflash/contrib/prometheus-cpp/pull/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/pull/include -I/home/simple/tiflash/contrib/cpptoml -I/home/simple/tiflash/contrib/magic_enum/include -I/home/simple/tiflash/contrib/poco/NetSSL_OpenSSL/include -I/home/simple/tiflash/contrib/poco/Crypto/include -I/home/simple/tiflash/contrib/xxHash/cmake_unofficial/.. -I/home/simple/tiflash/build/contrib/kvproto/cpp -I/home/simple/tiflash/build/contrib/kvproto/cpp/kvproto -I/home/simple/tiflash/contrib/grpc/include -I/home/simple/tiflash/contrib/abseil-cpp -I/home/simple/tiflash/contrib/client-c/include -I/home/simple/tiflash/build/contrib/grpc/third_party/cares/cares -I/home/simple/tiflash/contrib/grpc/third_party/cares/cares -I/home/simple/tiflash/build/contrib/tipb/cpp -I/home/simple/tiflash/build/dbms/src/Storages/DeltaMerge/File/dtpb -I/home/simple/tiflash/contrib/libbtrie/include -isystem /home/simple/tiflash/contrib/fmtlib-cmake/../fmtlib/include -isystem /home/simple/tiflash/libs/libsymbolization/include -isystem /home/simple/tiflash/contrib/protobuf/src -isystem /home/simple/tiflash/contrib/re2 -isystem /home/simple/tiflash/build/contrib/re2-cmake -D__GLIBCXX_BITSIZE_INT_N_0=128 -D__GLIBCXX_TYPE_INT_N_0=__int128  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor  -Wextra -Werror -g -g3 -ggdb3 -O0 -fverbose-asm -fno-inline  -fPIC -DDUMMY_BACKTRACE -pthread -std=gnu++17 -MD -MT dbms/CMakeFiles/dbms.dir/src/Debug/MockExecutor/astToExecutor.cpp.o -MF dbms/CMakeFiles/dbms.dir/src/Debug/MockExecutor/astToExecutor.cpp.o.d -o dbms/CMakeFiles/dbms.dir/src/Debug/MockExecutor/astToExecutor.cpp.o -c /home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutor.cpp
In file included from /home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutor.cpp:18:
In file included from /home/simple/tiflash/dbms/src/Debug/MockComputeServerManager.h:19:
In file included from /home/simple/tiflash/dbms/src/Server/FlashGrpcServerHolder.h:19:
In file included from /home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutor.h:19:
/home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutorUtils.h:40:6: error: no template named '__wrap_iter' in namespace 'std'
std::__wrap_iter<const std::pair<std::string, TiDB::ColumnInfo> *> checkSchema(const DAGSchema & input, String checked_column);
~~~~~^
1 error generated.
[19/532] Building CXX object dbms/CMakeFiles/dbms.dir/src/Debug/MockComputeServerManager.cpp.o
FAILED: dbms/CMakeFiles/dbms.dir/src/Debug/MockComputeServerManager.cpp.o 
/usr/bin/clang++-13 -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB -DBOOST_CONTEXT_STATIC_LINK -DBOOST_FIBER_NO_LIB -DBOOST_FIBER_STATIC_LINK -DBOOST_SYSTEM_NO_DEPRECATED -DCARES_STATICLIB -DFIU_ENABLE -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DMULTIPLE_CONTEXT_GTEST -DPOCO_STATIC -DPOCO_UNBUNDLED_ZLIB -DSTACK_LINE_READER_BUFFER_SIZE=1024 -DTIFLASH_COMPILER_VPCLMULQDQ_SUPPORT=1 -DTIFLASH_ENABLE_AVX512_SUPPORT=1 -DTIFLASH_ENABLE_AVX_SUPPORT=1 -DTIFLASH_SOURCE_PREFIX=\"/home/simple/tiflash\" -I/home/simple/tiflash/contrib/libsparsehash -I/home/simple/tiflash/contrib/libdivide -I/home/simple/tiflash/dbms/src -I/home/simple/tiflash/contrib/tiflash-proxy/raftstore-proxy/ffi/src -I/home/simple/tiflash/build/dbms/src -I/home/simple/tiflash/contrib/double-conversion -I/home/simple/tiflash/contrib/boost -I/home/simple/tiflash/contrib/xxHash -I/home/simple/tiflash/contrib/libpcg-random/include -I/home/simple/tiflash/contrib/libcityhash/include -I/home/simple/tiflash/libs/libcommon/include -I/home/simple/tiflash/build/libs/libcommon/include -I/home/simple/tiflash/libs/libpocoext/include -I/home/simple/tiflash/contrib/poco/Data/include -I/home/simple/tiflash/contrib/poco/Foundation/include -I/home/simple/tiflash/contrib/zlib-ng -I/home/simple/tiflash/build/contrib/zlib-ng -I/home/simple/tiflash/contrib/poco/Util/include -I/home/simple/tiflash/contrib/poco/XML/include -I/home/simple/tiflash/contrib/poco/JSON/include -I/home/simple/tiflash/contrib/poco/Net/include -I/home/simple/tiflash/contrib/cctz/include -I/home/simple/tiflash/contrib/jemalloc/include -I/home/simple/tiflash/contrib/jemalloc-cmake/include -I/home/simple/tiflash/contrib/cpu_features/include -I/home/simple/tiflash/contrib/libcpuid/include -I/home/simple/tiflash/contrib/lz4/lib -I/home/simple/tiflash/contrib/zstd/lib -I/home/simple/tiflash/contrib/client-c/third_party/libfiu/libfiu -I/home/simple/tiflash/contrib/prometheus-cpp/core/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/core/include -I/home/simple/tiflash/contrib/prometheus-cpp/push/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/push/include -I/home/simple/tiflash/contrib/prometheus-cpp/pull/include -I/home/simple/tiflash/build/contrib/prometheus-cpp-cmake/pull/include -I/home/simple/tiflash/contrib/cpptoml -I/home/simple/tiflash/contrib/magic_enum/include -I/home/simple/tiflash/contrib/poco/NetSSL_OpenSSL/include -I/home/simple/tiflash/contrib/poco/Crypto/include -I/home/simple/tiflash/contrib/xxHash/cmake_unofficial/.. -I/home/simple/tiflash/build/contrib/kvproto/cpp -I/home/simple/tiflash/build/contrib/kvproto/cpp/kvproto -I/home/simple/tiflash/contrib/grpc/include -I/home/simple/tiflash/contrib/abseil-cpp -I/home/simple/tiflash/contrib/client-c/include -I/home/simple/tiflash/build/contrib/grpc/third_party/cares/cares -I/home/simple/tiflash/contrib/grpc/third_party/cares/cares -I/home/simple/tiflash/build/contrib/tipb/cpp -I/home/simple/tiflash/build/dbms/src/Storages/DeltaMerge/File/dtpb -I/home/simple/tiflash/contrib/libbtrie/include -isystem /home/simple/tiflash/contrib/fmtlib-cmake/../fmtlib/include -isystem /home/simple/tiflash/libs/libsymbolization/include -isystem /home/simple/tiflash/contrib/protobuf/src -isystem /home/simple/tiflash/contrib/re2 -isystem /home/simple/tiflash/build/contrib/re2-cmake -D__GLIBCXX_BITSIZE_INT_N_0=128 -D__GLIBCXX_TYPE_INT_N_0=__int128  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor  -Wextra -Werror -g -g3 -ggdb3 -O0 -fverbose-asm -fno-inline  -fPIC -DDUMMY_BACKTRACE -pthread -std=gnu++17 -MD -MT dbms/CMakeFiles/dbms.dir/src/Debug/MockComputeServerManager.cpp.o -MF dbms/CMakeFiles/dbms.dir/src/Debug/MockComputeServerManager.cpp.o.d -o dbms/CMakeFiles/dbms.dir/src/Debug/MockComputeServerManager.cpp.o -c /home/simple/tiflash/dbms/src/Debug/MockComputeServerManager.cpp
In file included from /home/simple/tiflash/dbms/src/Debug/MockComputeServerManager.cpp:15:
In file included from /home/simple/tiflash/dbms/src/Debug/MockComputeServerManager.h:19:
In file included from /home/simple/tiflash/dbms/src/Server/FlashGrpcServerHolder.h:19:
In file included from /home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutor.h:19:
/home/simple/tiflash/dbms/src/Debug/MockExecutor/astToExecutorUtils.h:40:6: error: no template named '__wrap_iter' in namespace 'std'
std::__wrap_iter<const std::pair<std::string, TiDB::ColumnInfo> *> checkSchema(const DAGSchema & input, String checked_column);
~~~~~^
1 error generated.

```

### 2. What did you expect to see? (Required)

Build succeeds like before 5ddccf4c8a1

### 3. What did you see instead (Required)

Build errors are located in [astToExecutorUtils.cpp](https://github.com/pingcap/tiflash/blob/5ddccf4c8a1f7ed475be731daf0ecdfb24eed0f4/dbms/src/Debug/MockExecutor/astToExecutorUtils.cpp#L45) and [astToExecutorUtils.h](https://github.com/pingcap/tiflash/blob/5ddccf4c8a1f7ed475be731daf0ecdfb24eed0f4/dbms/src/Debug/MockExecutor/astToExecutorUtils.h#L40)

### 4. What is your TiFlash version? (Required)
ubuntu20.04 x86_64
**tiflash:** master
**cmake:** 3.22.1
**clang:** 13

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: close #5907 

Problem Summary:
 
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by LittleFall — APPROVED** [review]

**Review by SeaRise — APPROVED** [review]

File: dbms/src/Debug/MockExecutor/astToExecutorUtils.cpp [hunk 1]
```diff
@@ -42,7 +42,7 @@ ColumnName splitQualifiedName(const String & s)
 }
 
 
-std::__wrap_iter<const std::pair<std::string, TiDB::ColumnInfo> *> checkSchema(const DAGSchema & input, String checked_column)
+DAGSchema::const_iterator checkSchema(const DAGSchema & input, String checked_column)
 {
     auto ft = std::find_if(input.begin(), input.end(), [&](const auto & field) {
```
Comment (Lloyd-Pottiger) [inline dbms/src/Debug/MockExecutor/astToExecutorUtils.cpp:47]: maybe just & checked_column ?

File: dbms/src/Debug/MockExecutor/astToExecutorUtils.cpp [hunk 2]
```diff
@@ -42,7 +42,7 @@ ColumnName splitQualifiedName(const String & s)
 }
 
 
-std::__wrap_iter<const std::pair<std::string, TiDB::ColumnInfo> *> checkSchema(const DAGSchema & input, String checked_column)
+DAGSchema::const_iterator checkSchema(const DAGSchema & input, const String & checked_column)
 {
     auto ft = std::find_if(input.begin(), input.end(), [&](const auto & field) {
```
Comment (Lloyd-Pottiger) [inline dbms/src/Debug/MockExecutor/astToExecutorUtils.cpp:47]:
```suggestion
    auto ft = std::find_if(input.begin(), input.end(), [&checked_column](const auto & field) {
```

emmm, and capture checked_column is enough?
