### PR TITLE
Test: Mock window function, refactor window function tests

### LINKED ISSUE #5081: Unit test failed when run function related test with  Interpreter Tests.
## Bug Report

Thanks to @SchrodingerZhu. He ran across this bug and helped me figure out how it happened.

### 1. Minimal reproduce step (Required)
```
./dbms/gtests_dbms --gtest_filter="*Date*:*Join*"
```

### 2. What did you expect to see? (Required)
All test passed.
### 3. What did you see instead (Required)
origin_img_v2_97b2d9b1-cc41-4d6b-af1b-f2d3e0c9fa1g

### 4. What is your TiFlash version? (Required)
Nightly

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: ref #4609  close #5081

Problem Summary:
Mock window and sort executors.
Rewrite window function tests in new test framework.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Lloyd-Pottiger** [comment]
you can try gmock to do mock test which has embedded in gtest

File: dbms/src/Debug/astToExecutor.cpp [hunk 1]
```diff
@@ -1343,6 +1347,111 @@ void Join::toMPPSubPlan(size_t & executor_index, const DAGProperties & propertie
...
+        end->set_type(std::get<0>(frame.end.value()));
+    }
+
+    mut_frame->set_type(frame.type);
+    auto * children_executor = window->mutable_child();
+    return children[0]->toTiPBExecutor(children_executor, collator_id, mpp_info, context);
+}
+
+void Window::columnPrune(std::unordered_set<String> & used_columns)
+{
```
Comment (SeaRise) [inline dbms/src/Debug/astToExecutor.cpp:1421]: `window.schema != children[0]->schema`.
You can refer to `aggregate::columnPrune`

File: dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp [hunk 2]
```diff
@@ -148,7 +148,10 @@ bool collectForExecutor(std::vector<tipb::FieldType> & output_field_types, const
         // Window will only be pushed down in mpp mode.
         // In mpp mode, ExchangeSender or Sender will return output_field_types directly.
         // If not in mpp mode, window executor type is invalid.
-        throw TiFlashException("Window executor type is invalid in non-mpp mode, should not reach here.", Errors::Coprocessor::Internal);
+        // ywq todo: Question: why only MPP?
```
Comment (SeaRise) [inline dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp:151]: Because currently tidb only supports pushing the window function on mpp mode

File: dbms/src/Flash/Coprocessor/DAGQueryBlock.cpp [hunk 3]
```diff
@@ -40,6 +40,7 @@ bool isSourceNode(const tipb::Executor * root)
         || root->tp() == tipb::ExecType::TypePartitionTableScan
         || root->tp() == tipb::ExecType::TypeWindow
         || (root->tp() == tipb::ExecType::TypeSort && root->sort().ispartialsort());
+    // ywq test: question: why is_partialsort.
```
Comment (SeaRise) [inline dbms/src/Flash/Coprocessor/DAGQueryBlock.cpp:43]: `partial sort` is only for the window function.
Currently TiFlash does not support distributed sort.

**Comment by ywqzzy** [comment]
> you can try gmock to do mock test which has embedded in gtest

It's not my intention to this pr.
But great idea, I will feature out a way to mock data using gmock for future.

File: dbms/src/Debug/astToExecutor.cpp [hunk 4]
```diff
@@ -1561,11 +1721,97 @@ ExecutorPtr compileExchangeSender(ExecutorPtr input, size_t & executor_index, ti
...
+            TiDB::ColumnInfo ci;
+            if (func->name == "RowNumber" || func->name == "Rank" || func->name == "DenseRank")
+            {
+                ci.tp = TiDB::TypeLongLong;
+                ci.flag = TiDB::ColumnFlagBinary;
+            }
+            else
+            {
+                throw Exception("Unsupported window function " + func->name, ErrorCodes::LOGICAL_ERROR);
+            }
```
Comment (SeaRise) [inline dbms/src/Debug/astToExecutor.cpp:1758]:
```suggestion
           switch (func->name)
           {
               case "RowNumber":
               case "Rank":
               case "DenseRank":
               {
                   ci.tp = TiDB::TypeLongLong;
                   ci.flag = TiDB::ColumnFlagBinary;
                   break;
               }
               default:
                    throw Exception(fmt::format("Unsupported window function {}", func->name), ErrorCodes::LOGICAL_ERROR);
           }
```

File: dbms/src/Debug/astToExecutor.cpp [hunk 5]
```diff
@@ -1561,11 +1721,97 @@ ExecutorPtr compileExchangeSender(ExecutorPtr input, size_t & executor_index, ti
...
+            output_schema.emplace_back(std::make_pair(func->getColumnName(), ci));
+        }
+    }
+    if (partition_by_expr_list != nullptr)
+    {
+        for (const auto & child : partition_by_expr_list->children)
+        {
+            auto * elem = typeid_cast<ASTOrderByElement *>(child.get());
+            if (!elem)
+                throw Exception("Invalid order by element", ErrorCodes::LOGICAL_ERROR);
```
[the remark this answers is not in the document]
Comment (ywqzzy) [reply dbms/src/Debug/astToExecutor.cpp:1769]: I will change it to partition by

**Comment by ywqzzy** [comment]
I will write the test in a more easier way after https://github.com/pingcap/tiflash/pull/5041 get merged. So This pr is still in progress.

File: dbms/src/TestUtils/mockExecutor.h [hunk 6]
```diff
@@ -96,6 +97,13 @@ class DAGRequestBuilder
     DAGRequestBuilder & aggregation(ASTPtr agg_func, ASTPtr group_by_expr);
     DAGRequestBuilder & aggregation(MockAsts agg_funcs, MockAsts group_by_exprs);
 
+    // window
+    DAGRequestBuilder & window(ASTPtr window_func, MockOrderByItem order_by, MockOrderByItem partition_by, MockWindowFrame frame);
+    DAGRequestBuilder & window(MockAsts window_funcs, MockOrderByItems order_by_list, MockOrderByItems partition_by_list, MockWindowFrame frame);
```
Comment (SeaRise) [inline dbms/src/TestUtils/mockExecutor.h:102]: can we use a new type `MocPartitionByItems` for `partition_by_list`?

File: dbms/src/TestUtils/ExecutorTestUtils.cpp [hunk 7]
```diff
@@ -37,12 +40,29 @@ void ExecutorTest::SetUpTestCase()
     try
     {
         DB::registerFunctions();
+    }
+    catch (DB::Exception &)
```
Comment (SeaRise) [inline dbms/src/TestUtils/ExecutorTestUtils.cpp:44]: how about wraping a lambda like
```
auto xxx = [](std::function<void()> func) {
       try
    {
        func();
    }
    catch (DB::Exception &)
   {
}
}
```

File: dbms/src/TestUtils/mockExecutor.h (hunk 6 above)
Comment (ywqzzy) [reply dbms/src/TestUtils/mockExecutor.h:102]: Good idea!

File: dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp [hunk 8]
```diff
@@ -628,6 +628,7 @@ void DAGQueryBlockInterpreter::executeImpl(DAGPipeline & pipeline)
     }
     else if (query_block.source->tp() == tipb::ExecType::TypeWindow)
     {
+        std::cout << "ywq window here" << std::endl;
```
Comment (ywqzzy) [inline dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp:631]: remove

File: dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp [hunk 9]
```diff
@@ -689,6 +690,10 @@ void DAGQueryBlockInterpreter::executeImpl(DAGPipeline & pipeline)
     }
 
     // execute final project action
+    for (const auto & col : final_project)
```
Comment (ywqzzy) [inline dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp:693]: remove

File: dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp [hunk 10]
```diff
@@ -1216,6 +1218,7 @@ String DAGExpressionAnalyzer::appendCastIfNeeded(
     {
         DataTypePtr expected_type = getDataTypeByFieldTypeForComputingLayer(expr.field_type());
         DataTypePtr actual_type = actions->getSampleBlock().getByName(expr_name).type;
+        std::cout << "append cast, expected_type:" << expected_type->getName() << ", actual_type: " << actual_type->getName() << std::endl;
```
Comment (ywqzzy) [inline dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp:1221]: remove

File: dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp [hunk 11]
```diff
@@ -1131,6 +1132,7 @@ NamesWithAliases DAGExpressionAnalyzer::appendFinalProjectForRootQueryBlock(
     const String & column_prefix,
     bool keep_session_timezone_info)
 {
+    std::cout << "call for root" << std::endl;
```
Comment (ywqzzy) [inline dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp:1135]: remove

File: dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp [hunk 12]
```diff
@@ -711,6 +716,7 @@ void DAGQueryBlockInterpreter::executeImpl(DAGPipeline & pipeline)
 
 void DAGQueryBlockInterpreter::executeProject(DAGPipeline & pipeline, NamesWithAliases & project_cols, const String & extra_info)
 {
+    std::cout << "extra info: " << extra_info << std::endl;
```
Comment (ywqzzy) [inline dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp:719]: remove

File: dbms/src/Flash/Coprocessor/InterpreterUtils.cpp [hunk 13]
```diff
@@ -97,7 +97,10 @@ ExpressionActionsPtr generateProjectExpressionActions(
 {
     NamesAndTypesList input_column;
     for (const auto & column : stream->getHeader())
+    {
```
Comment (ywqzzy) [inline dbms/src/Flash/Coprocessor/InterpreterUtils.cpp:100]: remove

File: dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp [hunk 14]
```diff
@@ -16,6 +16,9 @@
 #include <Flash/Coprocessor/collectOutputFieldTypes.h>
 #include <common/types.h>
 
+#include "tipb/executor.pb.h"
```
Comment (ywqzzy) [inline dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp:19]: remove

File: dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp [hunk 15]
```diff
@@ -58,6 +61,32 @@ bool collectForAgg(std::vector<tipb::FieldType> & output_field_types, const tipb
...
 }
 
+bool collectForExecutor(std::vector<tipb::FieldType> & output_field_types, const tipb::Executor & executor);
+bool collectForWindow(std::vector<tipb::FieldType> & output_field_types, const tipb::Executor & executor)
+{
+    // collect output_field_types of children
+    std::vector<std::vector<tipb::FieldType>> children_output_field_types;
+    size_t child_index = 0;
+    children_output_field_types.resize(1);
+    // for join, dag_request.has_root_executor() == true, can use getChildren and traverseExecutorTree directly.
```
Comment (ywqzzy) [inline dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp:71]: remove

File: dbms/src/TestUtils/ExecutorTestUtils.cpp [hunk 16]
```diff
@@ -117,14 +137,25 @@ void ExecutorTest::executeStreams(const std::shared_ptr<tipb::DAGRequest> & requ
     context.context.setDAGContext(&dag_context);
     // Currently, don't care about regions information in tests.
     DAGQuerySource dag(context.context);
-    readBlock(executeQuery(dag, context.context, false, QueryProcessingStage::Complete).in, expect_columns);
+    std::cout << "expected columns size: " << expect_columns.size() << std::endl;
```
Comment (ywqzzy) [inline dbms/src/TestUtils/ExecutorTestUtils.cpp:140]: remove

File: dbms/src/TestUtils/FunctionTestUtils.cpp [hunk 17]
```diff
@@ -25,6 +25,10 @@
 #include <TestUtils/TiFlashTestBasic.h>
 #include <fmt/core.h>
 
+#include <cstddef>
```
Comment (ywqzzy) [inline dbms/src/TestUtils/FunctionTestUtils.cpp:28]: remove

File: dbms/src/TestUtils/FunctionTestUtils.cpp [hunk 18]
```diff
@@ -86,6 +90,14 @@ ::testing::AssertionResult columnEqual(
     {
         auto expected_field = (*expected)[i];
         auto actual_field = (*actual)[i];
+        if (expected_field != actual_field)
```
Comment (ywqzzy) [inline dbms/src/TestUtils/FunctionTestUtils.cpp:93]: remove

File: dbms/src/TestUtils/FunctionTestUtils.cpp [hunk 19]
```diff
@@ -108,13 +120,17 @@ void blockEqual(
     const Block & actual)
 {
     size_t columns = actual.columns();
-
+    std::cout << "actual columns: " << actual.columns() << std::endl;
```
Comment (ywqzzy) [inline dbms/src/TestUtils/FunctionTestUtils.cpp:123]: remove

File: dbms/src/TestUtils/mockExecutor.cpp [hunk 20]
```diff
@@ -96,6 +103,8 @@ DAGRequestBuilder & DAGRequestBuilder::mockTable(const String & db, const String
         TiDB::ColumnInfo ret;
         ret.tp = column.second;
         ret.name = column.first;
+        if (ret.tp == TiDB::TP::TypeNewDecimal)
+            ret.flen = 65;
```
Comment (ywqzzy) [inline dbms/src/TestUtils/mockExecutor.cpp:107]: Just a hack, I will test more about decimal in following pr.

File: dbms/src/TestUtils/ExecutorTestUtils.cpp [hunk 21]
```diff
@@ -34,15 +38,20 @@ void ExecutorTest::initializeContext()
...
-    try
-    {
-        DB::registerFunctions();
-        DB::registerAggregateFunctions();
-    }
-    catch (DB::Exception &)
-    {
-        // Maybe another test has already registered, ignore exception here.
-    }
+    auto register_func = [](std::function<void()> func) {
```
Comment (ywqzzy) [inline dbms/src/TestUtils/ExecutorTestUtils.cpp:41]: also fixed the bug in #5081

File: dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp [hunk 22]
```diff
@@ -58,6 +58,27 @@ bool collectForAgg(std::vector<tipb::FieldType> & output_field_types, const tipb
     return false;
 }
 
+bool collectForExecutor(std::vector<tipb::FieldType> & output_field_types, const tipb::Executor & executor);
+bool collectForWindow(std::vector<tipb::FieldType> & output_field_types, const tipb::Executor & executor)
+{
+    // collect output_field_types of child
+    std::vector<tipb::FieldType> child_output_field_types;
```
Comment (SeaRise) [inline dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp:65]: use `output_field_types` directly?

File: dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp [hunk 23]
```diff
@@ -58,6 +58,27 @@ bool collectForAgg(std::vector<tipb::FieldType> & output_field_types, const tipb
...
+    getChildren(executor).forEach([&child_output_field_types](const tipb::Executor & child) {
+        traverseExecutorTree(child, [&child_output_field_types](const tipb::Executor & e) { return collectForExecutor(child_output_field_types, e); });
+    });
+    for (auto & field_type : child_output_field_types)
+    {
+        output_field_types.push_back(field_type);
+    }
+    for (const auto & expr : executor.window().func_desc())
+    {
+        if (!exprHasValidFieldType(expr))
```
Comment (SeaRise) [inline dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp:75]:
```suggestion
        if (unlikely(!exprHasValidFieldType(expr)))
```

File: dbms/src/TestUtils/ExecutorTestUtils.cpp [hunk 24]
```diff
@@ -117,17 +126,78 @@ void ExecutorTest::executeStreams(const std::shared_ptr<tipb::DAGRequest> & requ
...
+    String source_name;
+    switch (type)
+    {
+    case TableScan:
+        source_name = "table_scan_0";
+        break;
+    case ExchangeReceiver:
+        source_name = "exchange_receiver_0";
+        break;
+    }
```
Comment (SeaRise) [inline dbms/src/TestUtils/ExecutorTestUtils.cpp:152]: how about `getName(type)`?

File: dbms/src/TestUtils/ExecutorTestUtils.cpp [hunk 25]
```diff
@@ -117,17 +126,78 @@ void ExecutorTest::executeStreams(const std::shared_ptr<tipb::DAGRequest> & requ
...
+    for (const auto & value_str : v)
+    {
+        Field value = parseMyDateTime(value_str, fsp);
+        vec.push_back(value.template safeGet<UInt64>());
+    }
+    DataTypePtr data_type = std::make_shared<DataTypeMyDateTime>(fsp);
+    return {makeColumn<MyDateTime>(data_type, vec), data_type, name, 0};
+}
+
+ColumnWithTypeAndName toNullableDatetimeVec(String name, const std::vector<String> & v, int fsp)
```
Comment (SeaRise) [inline dbms/src/TestUtils/ExecutorTestUtils.cpp:184]: move to FunctionTestUtils?

**Comment by ywqzzy** [comment]
Ops, Forgot to modify the test result.

**Comment by ywqzzy** [comment]
> Ops, Forgot to modify the test result.

Fixed.

File: dbms/src/Debug/astToExecutor.cpp [hunk 26]
```diff
@@ -1343,6 +1349,139 @@ void Join::toMPPSubPlan(size_t & executor_index, const DAGProperties & propertie
...
+        {
+            const auto * window_func = typeid_cast<const ASTFunction *>(func.get());
+            if (window_func != nullptr)
+            {
+                for (auto & child : window_func->arguments->children)
+                    collectUsedColumnsFromExpr(children[0]->output_schema, child, used_input_columns);
+            }
+        }
+    }
+    children[0]->columnPrune(used_input_columns);
```
Comment (SeaRise) [inline dbms/src/Debug/astToExecutor.cpp:1454]: and then reset `output_schema`?

File: dbms/src/Debug/astToExecutor.cpp [hunk 27]
```diff
@@ -1561,11 +1700,100 @@ ExecutorPtr compileExchangeSender(ExecutorPtr input, size_t & executor_index, ti
...
+                throw Exception(fmt::format("Unsupported window function {}", func->name), ErrorCodes::LOGICAL_ERROR);
+            }
+            output_schema.emplace_back(std::make_pair(func->getColumnName(), ci));
+        }
+    }
+    if (partition_by_expr_list != nullptr)
+    {
+        for (const auto & child : partition_by_expr_list->children)
+        {
+            auto * elem = typeid_cast<ASTOrderByElement *>(child.get());
```
Comment (SeaRise) [inline dbms/src/Debug/astToExecutor.cpp:1749]: add `using ASTPartitionByElement = ASTOrderByElement`？

File: dbms/src/TestUtils/ExecutorTestUtils.cpp [hunk 28]
```diff
@@ -117,14 +126,24 @@ void ExecutorTest::executeStreams(const std::shared_ptr<tipb::DAGRequest> & requ
     context.context.setDAGContext(&dag_context);
     // Currently, don't care about regions information in tests.
     DAGQuerySource dag(context.context);
-    readBlock(executeQuery(dag, context.context, false, QueryProcessingStage::Complete).in, expect_columns);
+    auto res = executeQuery(dag, context.context, false, QueryProcessingStage::Complete);
+    FmtBuffer fb;
+    res.in->dumpTree(fb);
```
Comment (SeaRise) [inline dbms/src/TestUtils/ExecutorTestUtils.cpp:131]: why this change?

File: dbms/src/Debug/astToExecutor.cpp [hunk 29]
```diff
@@ -1343,6 +1349,141 @@ void Join::toMPPSubPlan(size_t & executor_index, const DAGProperties & propertie
...
+        expr->mutable_field_type()->set_flen(11);
+        expr->mutable_field_type()->set_decimal(0);
+        expr->mutable_field_type()->set_charset("binary");
+        expr->mutable_field_type()->set_collate(63);
+        astToPB(children[0]->output_schema, elem->children[0], expr, collator_id, context);
+    }
+
+    for (const auto & child : partition_by_exprs)
+    {
+        auto * elem = typeid_cast<ASTOrderByElement *>(child.get());
```
Comment (SeaRise) [inline dbms/src/Debug/astToExecutor.cpp:1399]:
```suggestion
        auto * elem = typeid_cast<ASTPartitionByElement *>(child.get());
```

File: dbms/src/Debug/astToExecutor.cpp [hunk 30]
```diff
@@ -1343,6 +1349,141 @@ void Join::toMPPSubPlan(size_t & executor_index, const DAGProperties & propertie
...
+        if (!elem)
+            throw Exception("Invalid order by element", ErrorCodes::LOGICAL_ERROR);
```
Comment (SeaRise) [inline dbms/src/Debug/astToExecutor.cpp:1401]:
```suggestion
            throw Exception("Invalid partition by element", ErrorCodes::LOGICAL_ERROR);
```

File: dbms/src/Debug/astToExecutor.cpp [hunk 31]
```diff
@@ -1343,6 +1349,141 @@ void Join::toMPPSubPlan(size_t & executor_index, const DAGProperties & propertie
...
+            if (window_func != nullptr)
+            {
+                for (auto & child : window_func->arguments->children)
+                    collectUsedColumnsFromExpr(children[0]->output_schema, child, used_input_columns);
+            }
+        }
+    }
+    children[0]->columnPrune(used_input_columns);
+    /// update output schema after column prune
+    output_schema = children[0]->output_schema;
```
Comment (SeaRise) [inline dbms/src/Debug/astToExecutor.cpp:1456]: after `columnPrune`, `output_schema  = children[0]->output_schema + window functions`

File: dbms/src/TestUtils/ExecutorTestUtils.h [hunk 32]
```diff
@@ -52,6 +50,27 @@ class ExecutorTest : public ::testing::Test
...
+    {
+        String source_name;
+        switch (type)
+        {
+        case TableScan:
+            source_name = "table_scan_0";
+            break;
+        case ExchangeReceiver:
+            source_name = "exchange_receiver_0";
+            break;
```
Comment (SeaRise) [inline dbms/src/TestUtils/ExecutorTestUtils.h:69]: add comment like 
```
for single source query, the source executor name is ${type}_0
```

File: dbms/src/TestUtils/mockExecutor.cpp (hunk 20 above)
Comment (SeaRise) [reply dbms/src/TestUtils/mockExecutor.cpp:107]: add some comments?

File: dbms/src/Debug/astToExecutor.cpp [hunk 33]
```diff
@@ -1343,6 +1349,113 @@ void Join::toMPPSubPlan(size_t & executor_index, const DAGProperties & propertie
...
+        auto * elem = typeid_cast<ASTOrderByElement *>(child.get());
+        if (!elem)
+            throw Exception("Invalid order by element", ErrorCodes::LOGICAL_ERROR);
+        tipb::ByItem * by = window->add_order_by();
+        by->set_desc(elem->direction < 0);
+        tipb::Expr * expr = by->mutable_expr();
+        expr->mutable_field_type()->set_flen(11);
+        expr->mutable_field_type()->set_decimal(0);
+        expr->mutable_field_type()->set_charset("binary");
+        expr->mutable_field_type()->set_collate(63);
```
Comment (SeaRise) [inline dbms/src/Debug/astToExecutor.cpp:1393]: What does it do?

File: dbms/src/Debug/astToExecutor.cpp [hunk 34]
```diff
@@ -1343,6 +1349,113 @@ void Join::toMPPSubPlan(size_t & executor_index, const DAGProperties & propertie
...
+    sort->set_ispartialsort(is_partial_sort);
+
+    for (const auto & child : by_exprs)
+    {
+        auto * elem = typeid_cast<ASTOrderByElement *>(child.get());
+        if (!elem)
+            throw Exception("Invalid order by element", ErrorCodes::LOGICAL_ERROR);
+        tipb::ByItem * by = sort->add_byitems();
+        by->set_desc(elem->direction < 0);
+        tipb::Expr * expr = by->mutable_expr();
```
Comment (SeaRise) [inline dbms/src/Debug/astToExecutor.cpp:1451]: should we 
```
        expr->mutable_field_type()->set_flen(11);
        expr->mutable_field_type()->set_decimal(0);
        expr->mutable_field_type()->set_charset("binary");
        expr->mutable_field_type()->set_collate(63);
```
?

**Comment by SeaRise** [comment]
other LGTM

**Comment by SeaRise** [comment]
maybe we can remove `#ifndef DBMS_PUBLIC_GTEST` in https://github.com/pingcap/tiflash/blob/1e3207d3794d8870fc8afad895017191851e4cca/dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h#L57-L59

File: dbms/src/Debug/astToExecutor.cpp [hunk 35]
```diff
@@ -1561,11 +1666,100 @@ ExecutorPtr compileExchangeSender(ExecutorPtr input, size_t & executor_index, ti
...
     ExecutorPtr exchange_receiver = std::make_shared<mock::ExchangeReceiver>(executor_index, schema);
     return exchange_receiver;
 }
 
+ExecutorPtr compileWindow(ExecutorPtr input, size_t & executor_index, ASTPtr func_desc_list, ASTPtr partition_by_expr_list, ASTPtr order_by_expr_list, mock::MockWindowFrame frame)
+{
+    std::vector<ASTPtr> window_exprs;
+    std::vector<ASTPtr> order_columns;
+    std::vector<ASTPtr> partition_columns;
+    DAGSchema output_schema;
```
Comment (SeaRise) [inline dbms/src/Debug/astToExecutor.cpp:1680]: Seems like the schema is wrong?
schema = input->schema + window functions

File: dbms/src/Interpreters/WindowDescription.cpp [hunk 36]
```diff
@@ -60,4 +60,30 @@ void WindowDescription::setWindowFrame(const tipb::WindowFrame & frame_)
...
+{
+    switch (type)
+    {
+    case WindowFrame::FrameType::Rows:
+        return "Rows";
+    case WindowFrame::FrameType::Groups:
+        return "Groups";
+    case WindowFrame::FrameType::Ranges:
+        return "Ranges";
+    }
```
Comment (SeaRise) [inline dbms/src/Interpreters/WindowDescription.cpp:74]: add default and throw exception

File: dbms/src/Interpreters/WindowDescription.cpp [hunk 37]
```diff
@@ -60,4 +60,30 @@ void WindowDescription::setWindowFrame(const tipb::WindowFrame & frame_)
...
+{
+    switch (type)
+    {
+    case WindowFrame::BoundaryType::Unbounded:
+        return "Unbounded";
+    case WindowFrame::BoundaryType::Current:
+        return "Current";
+    case WindowFrame::BoundaryType::Offset:
+        return "Offset";
+    }
```
Comment (SeaRise) [inline dbms/src/Interpreters/WindowDescription.cpp:87]: ditto

File: dbms/src/Interpreters/WindowDescription.h [hunk 38]
```diff
@@ -87,6 +87,10 @@ struct WindowFrame
             && other.end_preceding == end_preceding;
     }
 };
+
+String frameTypeToString(WindowFrame::FrameType type);
+String boundaryTypeToString(WindowFrame::BoundaryType type);
```
Comment (SeaRise) [inline dbms/src/Interpreters/WindowDescription.h:92]: how about `const Type &`

File: dbms/src/TestUtils/ExecutorTestUtils.h [hunk 39]
```diff
@@ -52,6 +50,28 @@ class ExecutorTest : public ::testing::Test
...
+        }
+        return source_name;
+    }
```
Comment (SeaRise) [inline dbms/src/TestUtils/ExecutorTestUtils.h:73]:
```suggestion
    {
        switch (type)
        {
        case TableScan:
           return "table_scan_0";
        case ExchangeReceiver:
           return "exchange_receiver_0";
        default:
           throw Exception
        }
    }
```

File: dbms/src/Debug/astToExecutor.cpp (hunk 35 above)
Comment (ywqzzy) [reply dbms/src/Debug/astToExecutor.cpp:1680]: Wow, I forget to change it! Thanks!

File: dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h [hunk 40]
```diff
@@ -54,9 +54,6 @@ class DAGQueryBlockInterpreter
 
     BlockInputStreams execute();
 
-#ifndef DBMS_PUBLIC_GTEST
-private:
```
Comment (SeaRise) [inline dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h:58]: `private` need to keep..

File: dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h [hunk 41]
```diff
@@ -151,11 +151,8 @@ class DAGExpressionAnalyzer : private boost::noncopyable
     void appendCastAfterWindow(
         const ExpressionActionsPtr & actions,
         const tipb::Window & window,
-        const size_t window_columns_start_index);
+        size_t window_columns_start_index);
 
-#ifndef DBMS_PUBLIC_GTEST
-private:
```
Comment (SeaRise) [inline dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h:157]: `private` need to keep..

File: dbms/src/Debug/astToExecutor.cpp [hunk 42]
```diff
@@ -1561,11 +1666,101 @@ ExecutorPtr compileExchangeSender(ExecutorPtr input, size_t & executor_index, ti
...
+        {
+            auto * elem = typeid_cast<ASTOrderByElement *>(child.get());
+            if (!elem)
+                throw Exception("Invalid order by element", ErrorCodes::LOGICAL_ERROR);
+            order_columns.push_back(child);
+            compileExpr(input->output_schema, elem->children[0]);
+        }
+    }
+
+    output_schema.insert(output_schema.end(), input->output_schema.begin(), input->output_schema.end());
```
Comment (SeaRise) [inline dbms/src/Debug/astToExecutor.cpp:1735]: output_schema will be `window functions + child.schema`?

Comment (ywqzzy) [reply dbms/src/Debug/astToExecutor.cpp:1735]: I add a test to show that.

File: dbms/src/Flash/tests/gtest_interpreter.cpp [hunk 43]
```diff
@@ -93,6 +93,11 @@ CATCH
 TEST_F(InterpreterExecuteTest, MultipleQueryBlockWithSource)
 try
 {
+    context.scan("test_db", "test_table_1")
```
Comment (ywqzzy) [inline dbms/src/Flash/tests/gtest_interpreter.cpp:96]: remove it

Comment (SeaRise) [reply dbms/src/Flash/tests/gtest_interpreter.cpp:96]: why?

Comment (ywqzzy) [reply dbms/src/Flash/tests/gtest_interpreter.cpp]: > why?

I accidently add the code, it is not tested.

**Review by SeaRise — APPROVED** [review]

File: dbms/src/Debug/astToExecutor.cpp [hunk 44]
```diff
@@ -1561,11 +1666,101 @@ ExecutorPtr compileExchangeSender(ExecutorPtr input, size_t & executor_index, ti
...
-
 ExecutorPtr compileExchangeReceiver(size_t & executor_index, DAGSchema schema)
 {
     ExecutorPtr exchange_receiver = std::make_shared<mock::ExchangeReceiver>(executor_index, schema);
     return exchange_receiver;
 }
 
+ExecutorPtr compileWindow(ExecutorPtr input, size_t & executor_index, ASTPtr func_desc_list, ASTPtr partition_by_expr_list, ASTPtr order_by_expr_list, mock::MockWindowFrame frame)
+{
+    std::vector<ASTPtr> window_exprs;
```
Comment (Lloyd-Pottiger) [inline dbms/src/Debug/astToExecutor.cpp:1677]: create a new variable just before it will be used?

File: dbms/src/TestUtils/ExecutorTestUtils.h [hunk 45]
```diff
@@ -52,6 +50,28 @@ class ExecutorTest : public ::testing::Test
...
+    static String getSourceName(SourceType type)
+    {
+        switch (type)
+        {
+        case TableScan:
+            return "table_scan_0";
+        case ExchangeReceiver:
+            return "exchange_receiver_0";
+        default:
+            throw Exception(ErrorCodes::BAD_ARGUMENTS,
```
Comment (Lloyd-Pottiger) [inline dbms/src/TestUtils/ExecutorTestUtils.h:69]: In those cases, do we really need to throw an exception? maybe just ignoring is enough?

File: dbms/src/TestUtils/FunctionTestUtils.cpp [hunk 46]
```diff
@@ -242,5 +242,35 @@ ColumnWithTypeAndName createOnlyNullColumn(size_t size, const String & name)
     return {std::move(col), data_type, name};
 }
 
+ColumnWithTypeAndName toDatetimeVec(String name, const std::vector<String> & v, int fsp)
+{
+    std::vector<typename TypeTraits<MyDateTime>::FieldType> vec;
```
Comment (Lloyd-Pottiger) [inline dbms/src/TestUtils/FunctionTestUtils.cpp:247]:
```suggestion
    std::vector<typename TypeTraits<MyDateTime>::FieldType> vec;
    vec.reserve(v.size());
```

File: dbms/src/TestUtils/FunctionTestUtils.cpp [hunk 47]
```diff
@@ -242,5 +242,35 @@ ColumnWithTypeAndName createOnlyNullColumn(size_t size, const String & name)
...
+        Field value = parseMyDateTime(value_str, fsp);
+        vec.push_back(value.template safeGet<UInt64>());
+    }
+    DataTypePtr data_type = std::make_shared<DataTypeMyDateTime>(fsp);
+    return {makeColumn<MyDateTime>(data_type, vec), data_type, name, 0};
+}
+
+ColumnWithTypeAndName toNullableDatetimeVec(String name, const std::vector<String> & v, int fsp)
+{
+    std::vector<std::optional<typename TypeTraits<MyDateTime>::FieldType>> vec;
```
Comment (Lloyd-Pottiger) [inline dbms/src/TestUtils/FunctionTestUtils.cpp:259]: ditto

**Review by Lloyd-Pottiger — APPROVED** [review]
LGTM

**Review by mengxin9014 — APPROVED** [review]
