### PR TITLE
fix RegionKVStoreTest

### LINKED ISSUE #6767: Test cast RegionKVStoreTest.KVStoreSnapshot fail
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
unknown file: Failure
C++ exception with description "DB::Exception" thrown in the test body.
```

### 4. What is your TiFlash version? (Required)
 master

### PR DESCRIPTION
**Pull request by flowbehappy**
### What problem does this PR solve?

Issue Number: close #6767

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/Transaction/tests/kvstore_helper.h [hunk 1]
```diff
@@ -123,9 +126,9 @@ class RegionKVStoreTest : public ::testing::Test
         }
         String path = TiFlashTestEnv::getContext().getPath();
         auto p = path + "/metadata/";
-        TiFlashTestEnv::tryRemovePath(p, /*recreate=*/true);
+        TiFlashTestEnv::tryCreatePath(p);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Transaction/tests/kvstore_helper.h:129]: Why don't we clean up the existing files that the previous run may leave?

**Review by Lloyd-Pottiger — APPROVED** [review]

**Review by CalvinNeo — APPROVED** [review]
lgtm

File: dbms/src/Storages/Transaction/tests/kvstore_helper.h (hunk 1 above)
Comment (flowbehappy) [reply dbms/src/Storages/Transaction/tests/kvstore_helper.h:129]: When we run two test cases in one process, the old logic will remove the folders generated by previous cases. But since the Context instance is already created, the removed folders won't be created again, which causes exceptions by the following logic.
And seems not removing those folders won't cause problems.

**Comment by flowbehappy** [comment]
/run-/integration-test

**Review by ywqzzy — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]
