### PR TITLE
Get correct cpu cores in k8s pod

### LINKED ISSUE #6429: Port codes related to cpu cores from clickhouse

### LINKED ISSUE #6434: TiFlash get wrong cpu cores in k8s pod
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

A automate test runing k8s arm env failed for the error of `"Error 1105: other error for mpp stream: From MPP\\u003cquery:437820758481174532,task:130\\u003e: Code: 0, e.displayText() = DB::Exception: Receiver state: ERROR, error message: Exchange receiver meet error : From MPP\\u003cquery:437820758481174532,task:57\\u003e: Code: 0, e.displayText() = DB::Exception: threads are unavailable for the query 437820758481174532 (is min_tso 437820758481174532) when directly schedule it, need 391, but used 9803 of the thread hard limit 10000, 1 active and 0 waiting queries., e.what() = DB::Exception,, e.what() = DB::Exception,\":true`. 
The tiflash get cpu cores from physical machine instead of pod.

### 4. What is your TiFlash version? (Required)
master

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #6434

Problem Summary:

max_streams of xxxxInputStream is determined by Context's max_threads which is initialized by `getNumberofPhysicalCPUCores()`. In x86 virtual environment, we get max_threads as 48 which is physical cpu cores while getting max_threads as 128 which is logical cpu cores in arm virtual environment. 128 is much larger than 48, so it will use more threads and exceed the limit more easily.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by yibin87 — COMMENTED** [review]
Add test_infra tests to check?

File: dbms/src/Common/getNumberOfPhysicalCPUCores.cpp [hunk 1]
```diff
@@ -15,51 +15,67 @@
...
-    cpu_id_t data;
-    if (0 == cpuid_get_raw_data(&raw_data) && 0 == cpu_identify(&raw_data, &data) && data.num_logical_cpus != 0)
-    {
-        res = data.num_cores * data.total_logical_cpus / data.num_logical_cpus;
-    }
+#if defined(__x86_64__)
+    /// Let's limit ourself to the number of physical cores.
+    /// But if the number of logical cores is small - maybe it is a small machine
+    /// or very limited cloud instance and it is reasonable to use all the cores.
+    if (cpu_count >= 32)
```
Comment (yibin87) [inline dbms/src/Common/getNumberOfPhysicalCPUCores.cpp:65]: A little weired here, this cpu_count = 32, its max stream will be 16, smaller than cpu_count = 24. That's machine with more cpus has smaller max_streams.

**Review by zanmato1984 — APPROVED** [review]
LGTM

**Comment by Lloyd-Pottiger** [comment]
can use the value in server info https://github.com/pingcap/tiflash/blob/master/dbms/src/Server/ServerInfo.h which is more accurate and compatible.

**Comment by xzhangxian1008** [comment]
> can use the value in server info https://github.com/pingcap/tiflash/blob/master/dbms/src/Server/ServerInfo.h which is more accurate and compatible.

values in ServerInfo is calculated by this function, so ServerInfo can't help us.

**Comment by Lloyd-Pottiger** [comment]
> > can use the value in server info https://github.com/pingcap/tiflash/blob/master/dbms/src/Server/ServerInfo.h which is more accurate and compatible.
> 
> values in ServerInfo is calculated by this function, so ServerInfo can't help us.

no, actually it reuse the logic from tivk https://github.com/tikv/tikv/blob/master/components/tikv_util/src/sys/cgroup.rs

**Comment by JaySon-Huang** [comment]
1. We can get the `server_info` from tikv as @Lloyd-Pottiger said, which is more portable than the CH's one. https://github.com/pingcap/tiflash/issues/4879
2. I did not get why this PR is related to https://github.com/pingcap/tiflash/issues/6434, can you elaborate more about it?

**Comment by xzhangxian1008** [comment]
> 



> 1. We can get the `server_info` from tikv as @Lloyd-Pottiger said, which is more portable than the CH's one. [feat: add a function to get number of logical cpu cores #4879](https://github.com/pingcap/tiflash/issues/4879)
> 2. I did not get why this PR cause the error in [TiFlash get wrong cpu cores in k8s pod #6434](https://github.com/pingcap/tiflash/issues/6434), can you elaborate more about it?

max_streams of xxxxInputStream is determined by Context's max_threads which is initialized by `getNumberofPhysicalCPUCores()`. In x86 virtual environment, we get max_threads as 48 which is physical cpu cores while getting max_threads as 128 which is logical cpu cores in arm virtual environment. 128 is much larger than 48, so it will use more threads and exceed the limit more easily.

File: dbms/src/Interpreters/SettingsCommon.h [hunk 2]
```diff
@@ -25,7 +25,7 @@
 #include <IO/WriteHelpers.h>
 #include <Poco/String.h>
 #include <Poco/Timespan.h>
-
+#include <memory>
```
Comment (Lloyd-Pottiger) [inline dbms/src/Interpreters/SettingsCommon.h:28]:
```suggestion
```

File: dbms/src/Interpreters/SettingsCommon.h [hunk 3]
```diff
@@ -127,7 +127,7 @@ struct SettingMaxThreads
 
     void set(UInt64 x)
     {
-        value = x ? x : getAutoValue();
+        value = x ? x : getNumberOfLogicalCPUCores();
```
Comment (Lloyd-Pottiger) [inline dbms/src/Interpreters/SettingsCommon.h:130]: why not call `getAutoValue()`?

File: dbms/src/Interpreters/SettingsCommon.h [hunk 4]
```diff
@@ -162,22 +162,16 @@ struct SettingMaxThreads
 
     void setAuto()
     {
-        value = getAutoValue();
+        value = getNumberOfLogicalCPUCores();
```
Comment (Lloyd-Pottiger) [inline dbms/src/Interpreters/SettingsCommon.h:165]: ditto

File: dbms/src/Server/Server.cpp [hunk 5]
```diff
@@ -201,6 +200,10 @@ namespace Debug
 extern void setServiceAddr(const std::string & addr);
 }
 
+// It's used for the initialization of Context, so we need to ensure
+// that context in Server is created after ServerInfo has set this variable.
+UInt16 max_logical_cpu_cores = 0;
```
Comment (Lloyd-Pottiger) [inline dbms/src/Server/Server.cpp:205]:
```suggestion
UInt16 max_logical_cpu_cores;
```

maybe no need to init?

File: dbms/src/Server/ServerInfo.h [hunk 6]
```diff
@@ -38,7 +37,7 @@ class ServerInfo
         /// number of logical CPU cores
         UInt16 logical_cores = std::thread::hardware_concurrency();
         /// number of physical CPU cores
-        UInt16 physical_cores = getNumberOfPhysicalCPUCores();
+        UInt16 physical_cores = std::thread::hardware_concurrency();
```
Comment (Lloyd-Pottiger) [inline dbms/src/Server/ServerInfo.h:40]: actually `std::thread::hardware_concurrency();` get the total logical cpu cores, maybe set `UInt16 physical_cores = std::thread::hardware_concurrency() / 2;`

File: cmake/target.cmake [hunk 7]
```diff
@@ -14,6 +14,7 @@
 
 if (CMAKE_SYSTEM MATCHES "Linux")
     set (OS_LINUX 1)
+    add_definitions(-D OS_LINUX)
```
Comment (JaySon-Huang) [inline cmake/target.cmake:17]: seems we don't need this now

File: dbms/src/Common/getNumberOfLogicalCPUCores.h [hunk 8]
```diff
@@ -14,6 +14,13 @@
 
 #pragma once
 
-/// Get number of CPU cores without hyper-threading.
-/// Note: do not support environment under resource isolation mechanism like Docker, CGroup.
-unsigned getNumberOfPhysicalCPUCores();
+#include <thread>
+
+extern UInt16 max_logical_cpu_cores;
```
Comment (JaySon-Huang) [inline dbms/src/Common/getNumberOfLogicalCPUCores.h:19]: I think it is a bad idea to define a global var without any namespace. And it is only defined in `Server.cpp`, I wonder it will cause compile error on ut binary.

better define it as a static var under `namespace details::cpu_info { ... }`

File: dbms/src/Common/getNumberOfLogicalCPUCores.h [hunk 9]
```diff
@@ -14,6 +14,20 @@
 
 #pragma once
 
-/// Get number of CPU cores without hyper-threading.
-/// Note: do not support environment under resource isolation mechanism like Docker, CGroup.
-unsigned getNumberOfPhysicalCPUCores();
+#include <common/types.h>
+
+#include <thread>
```
Comment (Lloyd-Pottiger) [inline dbms/src/Common/getNumberOfLogicalCPUCores.h:19]:
```suggestion
```

File: dbms/src/Server/Server.cpp [hunk 10]
```diff
@@ -1187,6 +1189,9 @@ int Server::main(const std::vector<std::string> & /*args*/)
     }
     LOG_DEBUG(log, "Load metadata done.");
 
+    LOG_INFO(log, "MyDebug: max_threads {}", settings.max_threads);
+    LOG_INFO(log, "MyDebug: max_streams {}", global_context->getMaxStreams());
+
```
Comment (Lloyd-Pottiger) [inline dbms/src/Server/Server.cpp:1194]:
```suggestion
```

File: dbms/src/Flash/Mpp/MinTSOScheduler.cpp [hunk 11]
```diff
@@ -35,7 +36,7 @@ MinTSOScheduler::MinTSOScheduler(UInt64 soft_limit, UInt64 hard_limit, UInt64 ac
     , active_set_soft_limit(active_set_soft_limit_)
     , log(Logger::get())
 {
-    auto cores = getNumberOfPhysicalCPUCores();
+    auto cores = getNumberOfLogicalCPUCores();
```
Comment (Lloyd-Pottiger) [inline dbms/src/Flash/Mpp/MinTSOScheduler.cpp:39]: the value become larger, please confirm it is reasonable /cc @windtalker

**Review by Lloyd-Pottiger — APPROVED** [review]
Rest LGTM

File: dbms/src/Common/getNumberOfLogicalCPUCores.h [hunk 12]
```diff
@@ -14,6 +14,18 @@
...
-/// Get number of CPU cores without hyper-threading.
-/// Note: do not support environment under resource isolation mechanism like Docker, CGroup.
-unsigned getNumberOfPhysicalCPUCores();
+#include <common/types.h>
+
+inline UInt16 getNumberOfLogicalCPUCores(UInt16 max_logical_cpu_cores = 0)
+{
+    static UInt64 n = max_logical_cpu_cores;
+    return n;
+}
```
Comment (JaySon-Huang) [inline dbms/src/Common/getNumberOfLogicalCPUCores.h:23]: I think it is dangerous to set the static var in function `getNumberOfLogicalCPUCores`. For example, creating a `SettingMaxThreads` will call `getNumberOfLogicalCPUCores(0)` by default, which unexpectedly makes it to be 0.

https://github.com/pingcap/tiflash/blob/269e77b1b5697af03e3f4f40408bf2ba3fab336f/dbms/src/Interpreters/SettingsCommon.h#L109-L112

Can we get the correct threads number from global_settings now?

Comment (Lloyd-Pottiger) [reply dbms/src/Common/getNumberOfLogicalCPUCores.h:23]: we declare global_context after setNumberOfLogicalCPUCores ?

Comment (xzhangxian1008) [reply dbms/src/Common/getNumberOfLogicalCPUCores.h:23]: > I think it is dangerous to set the static var in function `getNumberOfLogicalCPUCores`. For example, creating a `SettingMaxThreads` will call `getNumberOfLogicalCPUCores(0)` by default, which unexpectedly makes it to be 0.
> 
> https://github.com/pingcap/tiflash/blob/269e77b1b5697af03e3f4f40408bf2ba3fab336f/dbms/src/Interpreters/SettingsCommon.h#L109-L112
> 
> Can we get the correct threads number from global_settings now?

maybe we can throw exception when the returned value is 0?

**Review by JaySon-Huang — APPROVED** [review]

**Review by yibin87 — APPROVED** [review]
LGTM
