### PR TITLE
Do not use extra threads when cancel mpp query

### LINKED ISSUE #5631: Sync MPPTunnel hangs when it meet error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
After #5286, sync MPPTunnel will hangs forever if it meet error:
1. Time 0: Sync MPPTunnel is connected, and after connected, `waitForFinish` will be called immediately.
https://github.com/pingcap/tiflash/blob/4ab1564a17c2ed8bd78b5255f721def878fdd296/dbms/src/Flash/FlashService.cpp#L308-L310
2. Time 1: After `waitForFinish`, the tunnel state will be set to `WaitingForSenderFinish`
https://github.com/pingcap/tiflash/blob/4ab1564a17c2ed8bd78b5255f721def878fdd296/dbms/src/Flash/Mpp/MPPTunnel.cpp#L246
3. Time 2: Some error happens, and the tunnel is closed, as L134 shows, if the current tunnel state is `WaitingForSenderFinish`, `close` will do nothing except `waitForSenderFinish`
https://github.com/pingcap/tiflash/blob/4ab1564a17c2ed8bd78b5255f721def878fdd296/dbms/src/Flash/Mpp/MPPTunnel.cpp#L105-L143
4. Clearly, no one will finish the `send_queue`, so the sender will hangs forever, and `waitForSenderFinish` never returns.

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: ref #5095, close #5631

Problem Summary:

### What is changed and how it works?
1. Refine `MPPTask::abortTunnels` to make `MPPTask::abort()` non-blocking
2. Don't use extra threads when cancel mpp query
3. Delete some outdated failpoints
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  - run random failpoints tests more than 12 hours
  - run mpp kill tests more than 12 hours
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/EstablishCall.cpp [hunk 1]
```diff
@@ -207,6 +207,16 @@ void EstablishCallData::trySendOneMsg()
     case GRPCSendQueueRes::FINISHED:
         writeDone("", grpc::Status::OK);
         return;
+    case GRPCSendQueueRes::CANCELLED:
```
Comment (yibin87) [inline dbms/src/Flash/EstablishCall.cpp:210]: When does it come into this case?

File: dbms/src/Flash/Mpp/MPPTunnel.cpp [hunk 2]
```diff
@@ -87,34 +86,13 @@ MPPTunnel::~MPPTunnel()
...
     });
-    try
-    {
-        close("");
-    }
-    catch (...)
-    {
-        tryLogCurrentException(log, "Error in destructor function of MPPTunnel");
-    }
+    close("", true);
```
Comment (yibin87) [inline dbms/src/Flash/Mpp/MPPTunnel.cpp:89]: Suggest to keep the try/catch protection, or should introduce mechanisms like "no except" to guarantee that close won't throw any exceptions.

Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTunnel.cpp:89]: OK, I will add no except for `MPPTunnel::close()`

File: dbms/src/Flash/Mpp/MPPTunnel.cpp [hunk 3]
```diff
@@ -98,23 +97,9 @@ MPPTunnel::~MPPTunnel()
...
-    }
-}
-
 /// exit abnormally, such as being cancelled.
-void MPPTunnel::close(const String & reason)
+void MPPTunnel::close(const String & reason, bool wait_sender_finish)
 {
-    SCOPE_EXIT({
-        finishSendQueue(true); // drain the send_queue when close, to release useless memory
-    });
```
Comment (gengliqi) [inline dbms/src/Flash/Mpp/MPPTunnel.cpp:117]: Seems `cancelWith` doesn't free the memory. Is it expected?

File: dbms/src/Flash/Mpp/MPPTunnel.cpp [hunk 4]
```diff
@@ -359,14 +331,24 @@ void SyncTunnelSender::sendJob(PacketWriter * writer)
...
+        while (result = send_queue.pop(res), result == MPMCQueueResult::OK)
         {
             if (!writer->write(res->packet))
             {
                 err_msg = "grpc writes failed.";
                 break;
             }
         }
+        /// write the last error packet if needed
+        if (result == MPMCQueueResult::CANCELLED)
```
Comment (gengliqi) [inline dbms/src/Flash/Mpp/MPPTunnel.cpp:344]: How about `send_queue.isCancelled()`?

File: dbms/src/Flash/Mpp/MPPTunnel.cpp (hunk 3 above)
Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTunnel.cpp:117]: Yes, since each TrackedMPPPacket holds a shared ptr of memory tracker, there is no need to drian the queue when cancel it.

File: dbms/src/Flash/Mpp/MPPTunnel.cpp (hunk 4 above)
Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTunnel.cpp]: Updated.

**Review by SeaRise — APPROVED** [review]
The rest LGTM

File: dbms/src/Flash/Mpp/GRPCSendQueue.h [hunk 5]
```diff
@@ -120,6 +120,21 @@ class GRPCSendQueue
         return ret;
     }
 
+    bool cancelWith(const String & reason)
```
Comment (gengliqi) [inline dbms/src/Flash/Mpp/GRPCSendQueue.h:123]: Add some comments here?

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp [hunk 6]
```diff
@@ -183,37 +141,21 @@ std::pair<bool, String> MPPTaskManager::registerTask(MPPTaskPtr task)
...
         mpp_query_map[task->id.start_ts]->task_map.emplace(task->id, task);
     }
-    task->manager = this;
+    task->registered = true;
     cv.notify_all();
     return {true, ""};
 }
 
-void MPPTaskManager::waitUntilQueryStartsAbort(UInt64 query_id)
+std::pair<bool, String> MPPTaskManager::unregisterTask(MPPTask * task)
```
Comment (gengliqi) [inline dbms/src/Flash/Mpp/MPPTaskManager.cpp:149]: Seems this function only need `task.id`. Passing a `task` pointer is excessive.

File: dbms/src/Flash/Mpp/MPPTunnel.cpp [hunk 7]
```diff
@@ -124,59 +109,46 @@ void MPPTunnel::close(const String & reason)
             cv_for_status_changed.notify_all();
             return;
         case TunnelStatus::Connected:
+        case TunnelStatus::WaitingForSenderFinish:
```
Comment (gengliqi) [inline dbms/src/Flash/Mpp/MPPTunnel.cpp:112]: I think `WaitingForSenderFinish` is no use. Maybe we should remove it.

**Review by gengliqi — APPROVED** [review]
Rest LGTM

File: dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp [hunk 8]
```diff
@@ -174,6 +174,23 @@ class MockAsyncCallData : public IAsyncCallData
             case GRPCSendQueueRes::FINISHED:
                 async_tunnel_sender->consumerFinish("");
                 return;
+            case GRPCSendQueueRes::CANCELLED:
+                if (async_tunnel_sender->getCancelReason().empty())
+                {
+                    async_tunnel_sender->consumerFinish("");
+                    return;
+                }
```
[the remark this answers is not in the document]
Comment (windtalker) [reply dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp:182]: OK

File: dbms/src/Flash/Mpp/MPPTunnel.cpp (hunk 7 above)
Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTunnel.cpp:112]: Looks like you are right, but let's remove it in a seperated pr.

File: dbms/src/Flash/Mpp/MPPTunnel.cpp [hunk 9]
```diff
@@ -393,12 +374,23 @@ void SyncTunnelSender::startSendThread(PacketWriter * writer)
...
+    if (result == MPMCQueueResult::OK)
     {
         // switch tunnel's memory tracker into receiver's
         res->switchMemTracker(current_memory_tracker);
         return res;
     }
+    else if (result == MPMCQueueResult::CANCELLED)
+    {
+        RUNTIME_ASSERT(!send_queue.getCancelReason().empty(), "Tunnel sender cancelled without reason");
+        if (!send_cancel_reason)
```
[the remark this answers is not in the document]
Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTunnel.cpp:387]: Done

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp (hunk 6 above)
Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTaskManager.cpp:149]: Updated.
