### PR TITLE
Fix ref a del id failed in mix mode.

### LINKED ISSUE #4923: PageStorage V3 frequently prints error logs in Mixmode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy and start TiFlash with format_version: 3
2. write some data
3. modify the  format_version to 4 and restart the TiFlash

### 2. What did you expect to see? (Required)
TiFlash run normally without so much error logs.
### 3. What did you see instead (Required)
PageStorage V3 frequently prints error logs in Mixmode:

```
[2022/05/18 19:29:28.442 +08:00] [ERROR] [WriteBatches.h:69] ["WriteBatches:!!!=========================Modifications in meta haven't persisted=========================!!! Stack trace: \n       0x1d083a3\tStackTrace::StackTrace() [tiflash+30442403]\n                \tdbms/src/Common/StackTrace.cpp:23\n       0x7779c1f\tDB::DM::WriteBatches::~WriteBatches()::'lambda'(DB::WriteBatch const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::operator()(DB::WriteBatch const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const [tiflash+125279263]\n                \tdbms/src/Storages/DeltaMerge/WriteBatches.h:65\n       0x777606d\tDB::DM::WriteBatches::~WriteBatches() [tiflash+125263981]\n                \tdbms/src/Storages/DeltaMerge/WriteBatches.h:74\n       0x77660dc\tDB::DM::DeltaMergeStore::segmentMergeDelta(DB::DM::DMContext&, std::__1::shared_ptr<DB::DM::Segment> const&, DB::DM::DeltaMergeStore::TaskRunThread, std::__1::shared_ptr<DB::DM::SegmentSnapshot>) [tiflash+125198556]\n                \tdbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:2157\n       0x77692cb\tDB::DM::DeltaMergeStore::handleBackgroundTask(bool) [tiflash+125211339]\n                \tdbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1557\n       0x76a2da1\tDB::BackgroundProcessingPool::threadFunction() [tiflash+124399009]\n                \tdbms/src/Storages/BackgroundProcessingPool.cpp:233\n       0x76a3721\tvoid* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2> >(void*) [tiflash+124401441]\n                \t/data1/chentongli/tiflash-env/sysroot/bin/../include/c++/v1/thread:291\n  0x7fdf19143ea5\tstart_thread [libpthread.so.0+32421]\n                \t/usr/src/debug/glibc-2.17-c758a686/nptl/pthread_create.c:307\n  0x7fdf18c568dd\t<unknown symbol> [libc.so.6+1042653]\n                \t/usr/src/debug////////glibc-2.17-c758a686/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111"] [thread_id=34]
[2022/05/18 19:29:28.442 +08:00] [ERROR] [DeltaMergeStore.cpp:1590] ["DeltaMergeStore:db_372.t_375 Task MergeDelta on Segment [122] failed. Error msg: Can't find origin entry in V2 and V3, [ns_id=375, ori_page_id=1999]"] [thread_id=34]
```
### 4. What is your TiFlash version? (Required)
43b25fc844817725e668812631fc7345ceddda0e

### PR DESCRIPTION
**Pull request by jiaqizho**
### What problem does this PR solve?

Issue Number: close #4923 

Problem Summary:

- `getNormalId` won't resolve page id if page type is external.
- Can't ref V2 external page in MIX Mode
- If ref a page id which also in current `writebatch`, will be error.

### What is changed and how it works?

- Migrate the external and ref pages from V2 to V3 when the table is first inited under Mixed mode
- DeltaTree engine add reference to the data id instead of file id
- check whether the page id is in current writebatch or not

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/Page/PageStorage.cpp [hunk 1]
```diff
@@ -493,57 +496,104 @@ void PageWriter::writeIntoMixMode(WriteBatch && write_batch, WriteLimiterPtr wri
         }
         case WriteBatch::WriteType::REF:
         {
+            // 1. Check external page exist or not.
+            if (storage_v3->isPageIdExist(ns_id, write.ori_page_id, /*snapshot*/ nullptr))
```
Comment (hehechen) [inline dbms/src/Storages/Page/PageStorage.cpp:500]: Why getNormalPageId can't get external page since there is related processing code here:
https://github.com/pingcap/tiflash/blob/bb572eba5d4cf4db000861b7ccfb70ac32df11a9/dbms/src/Storages/Page/V3/PageDirectory.cpp#L326

Comment (jiaqizho) [reply dbms/src/Storages/Page/PageStorage.cpp:500]: If `check_prev` is false. Then after `del`,`getNormalPageId `  will get `del`.

File: dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp [hunk 2]
```diff
@@ -490,5 +490,68 @@ try
...
+        batch.putRefPage(2012, 1999);
+        ASSERT_NO_THROW(page_writer_mix->write(std::move(batch), nullptr));
+    }
+
+    {
+        // Revert v3
+        WriteBatch batch;
+        batch.delPage(2012);
+        batch.delPage(2001);
+        page_writer_mix->write(std::move(batch), nullptr);
```
Comment (hehechen) [inline dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp:523]: Test the read result after write？

**Review by hehechen — APPROVED** [review]

File: dbms/src/Storages/DeltaMerge/StoragePool.cpp [hunk 3]
```diff
@@ -244,6 +248,7 @@ StoragePool::StoragePool(Context & global_ctx, NamespaceId ns_id_, StoragePathPo
 
 void StoragePool::forceTransformMetaV2toV3()
 {
+    assert(run_mode == PageStorageRunMode::MIX_MODE);
```
Comment (flowbehappy) [inline dbms/src/Storages/DeltaMerge/StoragePool.cpp:251]: Plz use exception instead of `assert`.

File: dbms/src/Storages/DeltaMerge/StoragePool.cpp [hunk 4]
```diff
@@ -288,6 +293,67 @@ void StoragePool::forceTransformMetaV2toV3()
...
+toV2ConcreteSnapshot(const DB::PageStorage::SnapshotPtr & ptr)
+{
+    return dynamic_cast<DB::PS::V2::PageEntriesVersionSetWithDelta::Snapshot *>(ptr.get());
+}
+
+void StoragePool::forceTransformDataV2toV3()
+{
+    assert(run_mode == PageStorageRunMode::MIX_MODE);
+    assert(data_storage_v2 != nullptr);
+    assert(data_storage_v3 != nullptr);
```
Comment (flowbehappy) [inline dbms/src/Storages/DeltaMerge/StoragePool.cpp:306]: The same.

**Review by flowbehappy — APPROVED** [review]
