### PR TITLE
*: Fix set cancel test tsan.

### LINKED ISSUE #5884: ThreadSanitizer reports data race of test_mode in gtests_dbms
## Bug Report
```
SUMMARY: ThreadSanitizer: data race /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Interpreters/Context.cpp:1856:15 in DB::Context::setCancelTest()
```

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: close #5884 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by ywqzzy** [comment]
> /run-sanitizer-test tsan

Here is the test result. https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/519/pipeline

**Comment by ywqzzy** [comment]
> > /run-sanitizer-test tsan
> 
> Here is the test result. https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/519/pipeline

Find more race. PTAL @breezewish

**Review by SeaRise — DISMISSED** [review]

File: dbms/src/Interpreters/Context.cpp [hunk 1]
```diff
@@ -1838,56 +1838,67 @@ size_t Context::getMaxStreams() const
...
 
 MockMPPServerInfo Context::mockMPPServerInfo() const
 {
+    auto lock = getLock();
     return mpp_server_info;
 }
 
 void Context::setMockMPPServerInfo(MockMPPServerInfo & info)
 {
+    auto lock = getLock();
```
Comment (SeaRise) [inline dbms/src/Interpreters/Context.cpp:1901]: Can we use `std::atomic<TestMode> test_mode = non_test;`? I'm a little concerned about the effect of `shared->lock` on different queries

Comment (ywqzzy) [reply dbms/src/Interpreters/Context.cpp:1901]: > Can we use `std::atomic<TestMode> test_mode = non_test;`? I'm a little concerned about the effect of `shared->lock` on different queries

Good idea.

File: log [hunk 2]
```diff
@@ -0,0 +1 @@
+zsh: no such file or directory: ./dbms/gtests_dbms
```
Comment (breezewish) [inline log:1]: remove this log line?

File: tests/sanitize/tsan.suppression [hunk 3]
```diff
@@ -1 +1,2 @@
 race:dbms/src/Common/TiFlashMetrics.h
+race:DB::Context::setCancelTest
```
Comment (breezewish) [inline tests/sanitize/tsan.suppression:2]: Why is it suppressed?

Comment (ywqzzy) [reply tests/sanitize/tsan.suppression:2]: > Why is it suppressed?

Since the test_mode only make sense in UT, and we don't want to add more locks in Interpreter critical path.

File: log (hunk 2 above)
Comment (ywqzzy) [reply log:1]: > remove this log line?

Ops, I will remove it.

**Comment by SeaRise** [comment]
> /run-sanitizer-test tsan

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/536/pipeline/

**Comment by JaySon-Huang** [comment]
@ywqzzy @SeaRise can we get this pr merged?

**Comment by SeaRise** [comment]
> @ywqzzy @SeaRise can we get this pr merged?

Still need to verify if it actually works...

**Comment by SeaRise** [comment]
> /run-sanitizer-test tsan

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/553/pipeline

**Comment by SeaRise** [comment]
> > /run-sanitizer-test tsan
> 
> https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/553/pipeline

seems to work

**Review by SeaRise — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]
