### PR TITLE
Fix check fail when cancel parallel prehandling

### LINKED ISSUE #8201: TiFlash crash for Check soft_limit.has_value() failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2023/10/18 03:35:09.605 +08:00] [ERROR] [Exception.cpp:91] ["Code: 49, e.displayText() = DB::Exception: Check soft_limit.has_value() failed: soft_limit.has_value(): keyspace=4294967295 physical_table_id=253: (while preHandleSnapshot region_id=145395, index=6, term=6), e.what() = DB::Exception, Stack trace:
       0x1e9760e  DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+32077326]
                    dbms/src/Common/Exception.h:46
       0x8a695b8  DB::DM::SSTFilesToBlockInputStream::checkFinishedState(std::__1::unique_ptr<DB::SSTReader, std::__1::default_delete<DB::SSTReader> >&) [tiflash+145135032]
                    dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp:149
       0x8a696e9  DB::DM::SSTFilesToBlockInputStream::readSuffix() [tiflash+145135337]
                  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp:156
       0x8a64a59    DB::DM::PKSquashingBlockInputStream<true>::readSuffix() [tiflash+145115737]
                 dbms/src/Storages/DeltaMerge/PKSquashingBlockInputStream.h:64
       0x1d8d649    DB::DM::DMVersionFilterBlockInputStream<1>::readSuffix() [tiflash+30987849]
                 dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp:38
       0x1e656bf  DB::DM::SSTFilesToDTFilesOutputStream<std::__1::shared_ptr<DB::DM::BoundedSSTFilesToBlockInputStream> >::writeSuffix() [tiflash+31872703]
                 dbms/src/Storages/DeltaMerge/Decode/SSTFilesToDTFilesOutputStream.cpp:82
       0x8a5a7b9 DB::executeTransform(std::__1::shared_ptr<DB::Logger>, std::__1::shared_ptr<DB::Region> const&, std::__1::shared_ptr<DB::PreHandlingTrace::Item> const&, DB::DM::FileConvertJobType, std::__1::shared_ptr<DB::StorageDeltaMerge> const&, std::__1::shared_ptr<DB::DM::SSTFilesToBlockInputStream> const&, DB::DM::SSTFilesToBlockInputStreamOpts const&, DB::TMTContext&) [tiflash+145074105]
                    dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:131
       0x8a53822   DB::KVStore::preHandleSSTsToDTFiles(std::__1::shared_ptr<DB::Region>, DB::SSTViewVec, unsigned long, unsigned long, DB::DM::FileConvertJobType, DB::TMTContext&) [tiflash+145045538]
                   dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:625
       0x8a517fe  DB::KVStore::preHandleSnapshotToFiles(std::__1::shared_ptr<DB::Region>, DB::SSTViewVec, unsigned long, unsigned long, std::__1::optional<unsigned long>, DB::TMTContext&) [tiflash+145037310]
                 dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:201
       0x8a35613    PreHandleSnapshot [tiflash+144922131]
                   dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp:672
  0x7f58e957c71c proxy_ffi::engine_store_helper_impls::_$LT$impl$u20$proxy_ffi..interfaces..root..DB..EngineStoreServerHelper$GT$::pre_handle_snapshot::hab1c0a0a4ab0e51b [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+26048284]
  0x7f58e90a0f2e   engine_store_ffi::core::forward_raft::snapshot::pre_handle_snapshot_impl::h0f4793d5d00197e2 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+20954926]
  0x7f58e9c8a266  yatp::task::future::RawTask$LT$F$GT$::poll::h1973aa5ea2716d33 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+33444454]
  0x7f58eb7f849b   _$LT$yatp..task..future..Runner$u20$as$u20$yatp..pool..runner..Runner$GT$::handle::hb21645385c0bc4a1 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+62207131]
  0x7f58eb7e8eec std::sys_common::backtrace::__rust_begin_short_backtrace::h051089b45fd1366c [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+62144236]
  0x7f58eb7e996c    core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h97006f1ac1ae8af1 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+62146924]
  0x7f58eaee4075  std::sys::unix::thread::Thread::new::thread_start::hd2791a9cabec1fda [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+52686965]
                    /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/)
  0x7f58e7974802 start_thread [libc.so.6+653314]
  0x7f58e7914450  __clone3 [libc.so.6+259152]"] [source="DB::RawCppPtr DB::PreHandleSnapshot(DB::EngineStoreServerWrap *, DB::BaseBuffView, uint64_t, DB::SSTViewVec, uint64_t, uint64_t)"] [thread_id=128]

[2023/10/18 03:35:09.607 +08:00] [ERROR] [BaseDaemon.cpp:370] [########################################] [source=BaseDaemon] [thread_id=1549]
[2023/10/18 03:35:09.607 +08:00] [ERROR] [BaseDaemon.cpp:371] ["(from thread 1080) Received signal Segmentation fault(11)."] [source=BaseDaemon] [thread_id=1549]
[2023/10/18 03:35:09.607 +08:00] [ERROR] [BaseDaemon.cpp:401] ["Address: 0x40"] [source=BaseDaemon] [thread_id=1549]
[2023/10/18 03:35:09.607 +08:00] [ERROR] [BaseDaemon.cpp:407] ["Access: read."] [source=BaseDaemon] [thread_id=1549]
[2023/10/18 03:35:09.607 +08:00] [ERROR] [BaseDaemon.cpp:416] ["Address not mapped to object."] [source=BaseDaemon] [thread_id=1549]
```
### 4. What is your TiFlash version? (Required)
master

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #8201

Problem Summary:

When prehandling is actively cancelled from upper layer, reader is not seeked to end, make check panic

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp [hunk 1]
```diff
@@ -139,23 +141,29 @@ SSTFilesToBlockInputStream::~SSTFilesToBlockInputStream() = default;
...
+    if (prehandle_task->abort_flag.load())
+        return;
+
+    RUNTIME_CHECK_MSG(soft_limit.has_value(), "soft_limit.has_value(), cf={}", magic_enum::enum_name(cf));
     BaseBuffView cur = reader->keyView();
-    RUNTIME_CHECK_MSG(buffToStrView(cur) > soft_limit.value().raw_end, "cur > raw_end");
+    RUNTIME_CHECK_MSG(
+        buffToStrView(cur) > soft_limit.value().raw_end,
+        "cur > raw_end, cf={}",
+        magic_enum::enum_name(cf));
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp:159]: As we will call `reader->seekToLast();` in `maybeStopBySoftLimit`. Is this check still necessary?
https://github.com/pingcap/tiflash/blob/33ac2fd7e7c253882f9650499ababdf769485bd8/dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp#L516-L517

Comment (CalvinNeo) [reply dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp:160]: This check guards the invariance property that all data is properly handled when `readSuffix`. If this check fires, there must be some newly added/modified logic that changed this behavior and fails to handle all the data, which can lead to data inconsistence. The logic of consuming this stream depends on this invariance property.

`reader->seekToLast()` in `maybeStopBySoftLimit` means all the rest data is no longer necessary, so we can stop read and seek to last, which is a behavior this check forces. If we don't conform to this behavior, then there can be some abundant calls, if someone only checks `->remained()`.

Why not just put the `soft_limit` into `SSTReader`, and make the `->remained` the only check for ending? We don't do this since `soft_limit` is a hint that co-works with the encoding of TiKVKey, however, the SSTReader only handles plain string. So IMO the best place for `soft_limit` is `SSTFilesToBlockInputStream`.

**Review by JaySon-Huang — APPROVED** [review]
