### PR TITLE
Avoid duplicate column names for multiple windows.

### LINKED ISSUE #5616: No such name in Block::erase
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

The test https://github.com/pingcap/endless/blob/master/testcase/tiflash/li_auto/li_auto_test.go failed for the error:
```
Error 1105: other error for mpp stream: Code: 10, e.displayText() = DB::Exception: No such name in Block::erase(): 'CAST(row_number()_collator , Nullable(Int64)_String)_collator_0 ', e.what() = DB::Exception,\":true}"]
```
### 4. What is your TiFlash version? (Required)
master

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #5616

Problem Summary:

### What is changed and how it works?

for
```
select count(*)
from (
SELECT 
ROW_NUMBER() OVER (PARTITION BY `c2` ORDER BY  `c1`),
ROW_NUMBER() OVER (PARTITION BY `c2` ORDER BY  `c1` DESC)
FROM `test`.`t2`
)t1;
```
before this pr, the block after multi-windows will be
```
{
	"name": "c1",
	"id": 0,
	"type": "Int64",
	"column": null
}, {
	"name": "c2",
	"id": 0,
	"type": "String",
	"column": null
}, {
	"name": "CAST(row_number()_collator , Nullable(Int64)_String)_collator_0 ",
	"id": 0,
	"type": "Nullable(Int64)",
	"column": null
}, {
	"name": "CAST(row_number()_collator , Nullable(Int64)_String)_collator_0 ",
	"id": 0,
	"type": "Nullable(Int64)",
	"column": null
}, {
	"name": "1_UInt8",
	"id": 0,
	"type": "UInt8",
	"column": "Const(size = 1, UInt8(size = 1))"
}
```
column name `CAST(row_number()_collator , Nullable(Int64)_String)_collator_0 ` duplicate.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/tests/gtest_window_executor.cpp [hunk 1]
```diff
@@ -215,4 +223,29 @@ try
 }
 CATCH
 
+TEST_F(WindowExecutorTestRunner, multiWindowSortThenAgg)
+try
+{
+    /*
+    select count(1)from (
```
Comment (SeaRise) [inline dbms/src/Flash/tests/gtest_window_executor.cpp:230]:
```suggestion
    select count(1) from (
```

File: dbms/src/Flash/Planner/plans/PhysicalAggregation.cpp [hunk 2]
```diff
@@ -69,8 +69,11 @@ PhysicalPlanNodePtr PhysicalAggregation::build(
     analyzer.reset(aggregated_columns);
     analyzer.appendCastAfterAgg(expr_after_agg_actions, aggregation);
     /// project action after aggregation to remove useless columns.
-    const NamesAndTypes & schema = analyzer.getCurrentInputColumns();
-    expr_after_agg_actions->add(ExpressionAction::project(DB::toNames(schema)));
+    auto schema = PhysicalPlanHelper::addProjectAction(
+        expr_after_agg_actions,
+        analyzer.getCurrentInputColumns(),
```
Comment (ywqzzy) [inline dbms/src/Flash/Planner/plans/PhysicalAggregation.cpp:74]: Why not pass analyzer into the function?

Comment (ywqzzy) [reply dbms/src/Flash/Planner/plans/PhysicalAggregation.cpp:74]: Others LGTM

Comment (ywqzzy) [reply dbms/src/Flash/Planner/plans/PhysicalAggregation.cpp:74]: > Why not pass analyzer into the function?

I mean if we pass analyzer into the function, the caller of the function will not consider what the before_schema is.

File: dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp [hunk 3]
```diff
@@ -201,8 +201,8 @@ try
     execute(
         request,
         /*expected_physical_plan=*/R"(
-<Projection, aggregation_1> | is_tidb_operator: false, schema: <aggregation_1_max(s2)_collator_46 , Nullable(String)>, <aggregation_1_any(s1)_collator_46 , Nullable(String)>
- <Aggregation, aggregation_1> | is_tidb_operator: true, schema: <max(s2)_collator_46 , Nullable(String)>, <any(s1)_collator_46 , Nullable(String)>
+<Projection, aggregation_1> | is_record_profile_streams: false, schema: <aggregation_1_max(s2)_collator_46 , Nullable(String)>, <aggregation_1_any(s1)_collator_46 , Nullable(String)>
+ <Aggregation, aggregation_1> | is_record_profile_streams: true, schema: <max(s2)_collator_46 , Nullable(String)>, <any(s1)_collator_46 , Nullable(String)>
```
Comment (SeaRise) [inline dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp:205]:
```suggestion
<Projection, aggregation_1> | is_tidb_operator: false, schema: <aggregation_1_max(s2)_collator_46 , Nullable(String)>, <aggregation_1_any(s1)_collator_46 , Nullable(String)>
 <Aggregation, aggregation_1> | is_tidb_operator: true, schema: <max(s2)_collator_46 , Nullable(String)>, <any(s1)_collator_46 , Nullable(String)>
```

File: dbms/src/Flash/Planner/PhysicalPlanHelper.cpp [hunk 4]
```diff
@@ -12,6 +12,7 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
+#include <Flash/Coprocessor/DAGExpressionAnalyzer.h>
```
Comment (SeaRise) [inline dbms/src/Flash/Planner/PhysicalPlanHelper.cpp:15]:
```suggestion
```

File: dbms/src/Flash/Planner/plans/PhysicalAggregation.cpp (hunk 2 above)
Comment (SeaRise) [reply dbms/src/Flash/Planner/plans/PhysicalAggregation.cpp]: Refactored to not use analyzer.

File: dbms/src/Flash/tests/gtest_window_executor.cpp [hunk 5]
```diff
@@ -215,4 +223,75 @@ try
...
+
+    /*
+    select count(1)from (
+        SELECT 
+            ROW_NUMBER() OVER (PARTITION BY `c2` ORDER BY  `c1`),
+            ROW_NUMBER() OVER (PARTITION BY `c2` ORDER BY  `c1`)
+        FROM `test_db`.`table2`
+    )t1;
+    */
+    request = context
```
Comment (ywqzzy) [inline dbms/src/Flash/tests/gtest_window_executor.cpp:255]: Not run?

File: dbms/src/Flash/tests/gtest_window_executor.cpp [hunk 6]
```diff
@@ -215,4 +223,75 @@ try
...
+                       .sort({{"c2", false}, {"c1", true}}, true)
+                       .window(RowNumber(), {"c1", true}, {"c2", false}, buildDefaultRowsFrame())
+                       .sort({{"c2", false}, {"c1", false}}, true)
+                       .window(RowNumber(), {"c1", false}, {"c2", false}, buildDefaultRowsFrame())
+                       .aggregation({Count(lit(Field(static_cast<UInt64>(1))))}, {})
+                       .build(context);
+    executeWithConcurrency(request, createColumns({toVec<UInt64>({4})}));
+
+    /*
+    select count(1)from (
```
Comment (ywqzzy) [inline dbms/src/Flash/tests/gtest_window_executor.cpp:248]:
```suggestion
    select count(1) from (
```

File: dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp [hunk 7]
```diff
@@ -105,6 +105,24 @@ DataTypePtr findDuplicateAggFunc(
     return nullptr;
 }
 
+/// return `duplicated window function`->getReturnType if duplicated.
+/// or not return nullptr.
+DataTypePtr findDuplicateWindowFunc(
```
Comment (ywqzzy) [inline dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp:110]: maybe wrap findDuplicateWindowFunc and findDuplicateAggFunc into one function since they have the same logic.

Comment (SeaRise) [reply dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp:110]: It doesn't seem easy to merge into one function because of the difference between `window_functions_description.window_function` and `aggregated.function`

Comment (SeaRise) [reply dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp]: merged to `findDuplicateAggWindowFunc`

File: dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp [hunk 8]
```diff
@@ -295,13 +295,13 @@ try
     execute(
         request,
         /*expected_physical_plan=*/R"(
-<Projection, window_2> | is_tidb_operator: false, schema: <window_2_partition, Nullable(Int64)>, <window_2_order, Nullable(Int64)>, <window_2_CAST(row_number()_collator , Nullable(Int64)_String)_collator_0 , Nullable(Int64)>
- <Window, window_2> | is_tidb_operator: true, schema: <partition, Nullable(Int64)>, <order, Nullable(Int64)>, <CAST(row_number()_collator , Nullable(Int64)_String)_collator_0 , Nullable(Int64)>
+<Projection, window_2> | is_tidb_operator: false, schema: <window_2_window_2_partition, Nullable(Int64)>, <window_2_window_2_order, Nullable(Int64)>, <window_2_window_2_CAST(row_number()_collator , Nullable(Int64)_String)_collator_0 , Nullable(Int64)>
```
Comment (windtalker) [inline dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp:298]: Why there is two `window_2_` ?

File: dbms/src/Flash/tests/gtest_aggregation_executor.cpp [hunk 9]
```diff
@@ -117,13 +122,12 @@ class ExecutorAggTestRunner : public DB::tests::ExecutorTest
     void executeWithConcurrency(const std::shared_ptr<tipb::DAGRequest> & request, const ColumnsWithTypeAndName & expect_columns)
     {
         WRAP_FOR_DIS_ENABLE_PLANNER_BEGIN
-        for (size_t i = 1; i <= max_concurrency; i += step)
-            ASSERT_COLUMNS_EQ_UR(expect_columns, executeStreams(request, i));
+        ASSERT_COLUMNS_EQ_UR(expect_columns, executeStreams(request));
```
Comment (windtalker) [inline dbms/src/Flash/tests/gtest_aggregation_executor.cpp:125]: Why change this?

File: dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp (hunk 8 above)
Comment (SeaRise) [reply dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp:298]: the first `window_2_` is the column prefix of Window
the second `window_2_` is the column prefix of FinalProjection

File: dbms/src/Flash/tests/gtest_aggregation_executor.cpp (hunk 9 above)
Comment (SeaRise) [reply dbms/src/Flash/tests/gtest_aggregation_executor.cpp:125]: I feel like it was a waste of resources.
`ASSERT_COLUMNS_EQ_UR(expect_columns, executeStreams(request, 10));` is similar to `ASSERT_COLUMNS_EQ_UR(expect_columns, executeStreams(request, 8));`

Comment (SeaRise) [reply dbms/src/Flash/tests/gtest_aggregation_executor.cpp:125]: Maybe we only need to test single-threaded and multi-threaded cases?

Comment (SeaRise) [reply dbms/src/Flash/tests/gtest_aggregation_executor.cpp:125]: However, this pr can also not be modified here

Comment (SeaRise) [reply dbms/src/Flash/tests/gtest_aggregation_executor.cpp]: reverted

**Review by windtalker — APPROVED** [review]
LGTM

**Review by ywqzzy — APPROVED** [review]
LGTM
