### PR TITLE
MergeSortingBlockInputStream use spiller

### LINKED ISSUE #6611: gtest_dbms can not compile successfully in mac m1
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

cmake .. -GNinja -DCMAKE_BUILD_TYPE=DEBUG
ninja gtests_dbms

### 2. What did you expect to see? (Required)

compile successfully

### 3. What did you see instead (Required)

/Users/hongyunyan/Desktop/origin_tiflash/tiflash/dbms/src/Common/tests/gtest_spiller.cpp:59:36: error: reference to type 'const DB::Field' could not bind to an lvalue of type 'size_t' (aka 'unsigned long')
                    column->insert(k);
                                   ^
/Users/hongyunyan/Desktop/origin_tiflash/tiflash/dbms/src/Columns/IColumn.h:130:39: note: passing argument to parameter 'x' here
    virtual void insert(const Field & x) = 0;
                                      ^
/Users/hongyunyan/Desktop/origin_tiflash/tiflash/dbms/src/Common/tests/gtest_spiller.cpp:76:36: error: reference to type 'const DB::Field' could not bind to an rvalue of type 'unsigned long'
                    column->insert(k + i * 100);
                                   ^~~~~~~~~~~
/Users/hongyunyan/Desktop/origin_tiflash/tiflash/dbms/src/Columns/IColumn.h:130:39: note: passing argument to parameter 'x' here
    virtual void insert(const Field & x) = 0;
                                      ^
2 errors generated.

### 4. What is your TiFlash version? (Required)

master

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: ref #6528, close #6611

Problem Summary:

### What is changed and how it works?
1. `MergeSortingBlockInputStream` use spiller
2. Spiller uses `FileProvider` since the tmp data also need to be encrypted
3. add a simple test case for spill sort
4. move `Spiller` from `dbms/Common` to `dbms/Core` since I meet some link issues
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Core/Spiller.cpp [hunk 1]
```diff
@@ -46,35 +47,43 @@ SpilledFile::~SpilledFile()
...
+        return;
+    has_spilled_data = true;
     auto spilled_file_name = nextSpillFileName(partition_id);
+    LOG_INFO(logger, "Spilling part of data into temporary file {}", spilled_file_name);
     try
     {
         auto spilled_file = std::make_unique<SpilledFile>(spilled_file_name);
         RUNTIME_CHECK_MSG(!spilled_file->exists(), "Duplicated spilled file: {}, should not happens", spilled_file_name);
-        WriteBufferFromFile file_buf(spilled_file_name);
+        WriteBufferFromFileProvider file_buf(config.file_provider, spilled_file_name, EncryptionPath(spilled_file_name, ""));
```
Comment (lidezhu) [inline dbms/src/Core/Spiller.cpp:86]: Please use `FileProvider::deleteRegularFile(spilled_file_path, EncryptionPath(spilled_file_path, "")` to delete the spilled files in the destructor of `SpilledFile`.

Comment (windtalker) [reply dbms/src/Core/Spiller.cpp:86]: OK, updated the code.

File: dbms/src/Core/Spiller.h [hunk 2]
```diff
@@ -45,23 +47,24 @@ struct SpilledFiles
 class Spiller
 {
 public:
-    Spiller(const String & id, bool is_input_sorted, size_t partition_num, const String & spill_dir, const Block & input_schema, const LoggerPtr & logger);
-    bool spillBlocks(const Blocks & blocks, size_t partition_id);
+    Spiller(const SpillConfig & config, bool is_input_sorted, size_t partition_num, const Block & input_schema, const LoggerPtr & logger);
+    void spillBlocks(const Blocks & blocks, size_t partition_id);
     BlockInputStreams restoreBlocks(size_t partition_id, size_t max_stream_size);
```
Comment (SeaRise) [inline dbms/src/Core/Spiller.h:52]:
```suggestion
    BlockInputStreams restoreBlocks(size_t partition_id, size_t max_stream_size = 0);
```
ref: `max_stream_size == 0 means the spiller choose the stream size automatically`

File: dbms/src/DataStreams/copyData.cpp [hunk 3]
```diff
@@ -70,24 +70,41 @@ inline void doNothing(const Block &) {}
...
+    {
+        if (isAtomicSet(is_cancelled))
+            break;
+        ret.push_back(block);
+    }
+
+    if (isAtomicSet(is_cancelled))
+        return {};
+
+    from.readSuffix();
```
Comment (SeaRise) [inline dbms/src/DataStreams/copyData.cpp:95]: move to L91

File: dbms/src/Flash/tests/gtest_spill_sort.cpp [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+
+    auto request = context
+                       .scan("spill_sort_test", "simple_table")
+                       .topN(order_by_items, table_rows)
+                       .build(context);
+    context.context.setSetting("max_block_size", Field(max_block_size));
+    /// disable spill
+    context.context.setSetting("max_bytes_before_external_sort", Field(static_cast<UInt64>(0)));
+    auto ref_blocks = getExecuteStreamsReturnBlocks(request, original_max_streams);
+    auto ref_block = mergeBlocks(std::move(ref_blocks));
```
Comment (SeaRise) [inline dbms/src/Flash/tests/gtest_spill_sort.cpp:63]:
```suggestion
    auto ref_columns = executeStreams(request, original_max_streams);
```

File: dbms/src/Flash/tests/gtest_spill_sort.cpp [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+    /// enable spill
+    context.context.setSetting("max_bytes_before_external_sort", Field(static_cast<UInt64>(total_data_size / 10)));
+    auto result_blocks = getExecuteStreamsReturnBlocks(request, original_max_streams);
+    /// the block size is different with and without spill, so has to merge all the blocks into one block before compare
+    auto result_block = mergeBlocks(std::move(result_blocks));
+    ASSERT_BLOCK_EQ(ref_block, result_block);
```
Comment (SeaRise) [inline dbms/src/Flash/tests/gtest_spill_sort.cpp:69]:
```suggestion
    executeAndAssertColumnsEqual(request, ref_columns);
```
And then we can test different block size, concurrency and etc in `executeAndAssertColumnsEqual`.

File: dbms/src/DataStreams/MergeSortingBlockInputStream.cpp [hunk 6]
```diff
@@ -125,41 +126,33 @@ Block MergeSortingBlockInputStream::readImpl()
...
-                WriteBufferFromFile file_buf(path);
-                CompressedWriteBuffer compressed_buf(file_buf);
-                NativeBlockOutputStream block_out(compressed_buf, 0, header_without_constants);
                 MergeSortingBlocksBlockInputStream block_in(blocks, description, log->identifier(), max_merged_block_size, limit);
-
-                LOG_INFO(log, "Sorting and writing part of data into temporary file {}", path);
-                copyData(block_in, block_out, &is_cancelled); /// NOTE. Possibly limit disk usage.
-                LOG_INFO(log, "Done writing part of data into temporary file {}", path);
-
+                auto all_blocks = readAllData(block_in, &is_cancelled);
```
Comment (SeaRise) [inline dbms/src/DataStreams/MergeSortingBlockInputStream.cpp:130]: Is there a sub-batch to be considered here?
Feels like there is a risk of oom.

Comment (mengxin9014) [reply dbms/src/DataStreams/MergeSortingBlockInputStream.cpp:130]: > Is there a sub-batch to be considered here? Feels like there is a risk of oom.
MergeSortingBlocksBlockInputStream holds reference of blocks, readAllData will handle all blocks and move to all_blocks, I think it may hold at most the memory used by blocks.

Comment (mengxin9014) [reply dbms/src/DataStreams/MergeSortingBlockInputStream.cpp:130]: > Is there a sub-batch to be considered here? Feels like there is a risk of oom.

MergeSortingBlocksBlockInputStream holds reference of blocks, readAllData will handle all blocks and move to all_blocks, I think it may hold at most the memory used by blocks.

Comment (windtalker) [reply dbms/src/DataStreams/MergeSortingBlockInputStream.cpp:130]: The peak memory usage after the pr will be `2 * bytes_of(blocks)`, and before this pr the peak memory usage is `bytes_of(blocks) + bytes_of(block)`. In order to avoid oom, I will split the spill into multiple rounds, each round, the spilled data is `max_bytes`, so the peak memory usage will reduced to `bytes_of(blocks) + max_bytes`.

File: dbms/src/DataStreams/copyData.cpp (hunk 3 above)
Comment (windtalker) [reply dbms/src/DataStreams/copyData.cpp:95]: This piece of code is copied from `copyDataImpl`, in `copyDataImpl`, if the execution is cancelled, `from.readSuffix()` is not called.

Comment (SeaRise) [reply dbms/src/DataStreams/copyData.cpp:95]: ok

**Review by lidezhu — COMMENTED** [review]
The usage of `FileProvider` LGTM.

File: dbms/src/Core/Spiller.cpp [hunk 7]
```diff
@@ -37,44 +38,52 @@ SpilledFile::~SpilledFile()
...
+    Poco::File spill_dir(config.spill_dir);
+    if (!spill_dir.exists())
+    {
+        /// just for test, usually the tmp path should be created when server starting
+        spill_dir.createDirectories();
+    }
+    else
+    {
+        if (!spill_dir.isDirectory())
+            throw Exception(fmt::format("Spilled dir {} is a file", spill_dir.path()));
```
[the remark this answers is not in the document]
Comment (windtalker) [reply dbms/src/Core/Spiller.cpp]: Done

File: dbms/src/DataStreams/MergeSortingBlockInputStream.cpp (hunk 6 above)
Comment (windtalker) [reply dbms/src/DataStreams/MergeSortingBlockInputStream.cpp]: I've added a new spill function to split the spill into multiple rounds.

**Comment by mengxin9014** [comment]
It seems some tests didn't pass， others LGTM.

**Comment by windtalker** [comment]
> It seems some tests didn't pass， others LGTM.

The newly added unit test is unstable, ref #6622 for details. I've updated the test now.

File: dbms/src/Flash/tests/gtest_spill_sort.cpp [hunk 8]
```diff
@@ -0,0 +1,74 @@
...
+// Unless required by applicable law or agreed to in writing, software
+// distributed under the License is distributed on an "AS IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+#include <TestUtils/ExecutorTestUtils.h>
+#include <TestUtils/mockExecutor.h>
+
+#include "TestUtils/ColumnGenerator.h"
```
Comment (SeaRise) [inline dbms/src/Flash/tests/gtest_spill_sort.cpp:18]:
```suggestion
#include <TestUtils/ColumnGenerator.h>
```

**Review by SeaRise — APPROVED** [review]
lgtm

**Review by mengxin9014 — APPROVED** [review]
