### PR TITLE
Fix address alignment error

### LINKED ISSUE #10163: TiFlash meet bus error and crash in some specific env
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
CPU: Kunpeng-920(arm)
OS: 
```
Kylin Linux Advanced Server release V10 (Sword)
Linux localhost.localdomain 4.19.90-24.4.v2101.ky10.aarch64 #1 SMP Mon May 24 14:45:37 CST 2021 aarch64 aarch64 aarch64 GNU/Linux
```
log
```
[2025/05/14 01:46:18.005 +08:00] [ERROR] [BaseDaemon.cpp:366] [########################################] [source=BaseDaemon] [thread_id=780]
[2025/05/14 01:46:18.005 +08:00] [ERROR] [BaseDaemon.cpp:367] ["(from thread 632) Received signal Bus error(7)."] [source=BaseDaemon] [thread_id=780]
[2025/05/14 01:46:18.005 +08:00] [ERROR] [BaseDaemon.cpp:426] ["Invalid address alignment."] [source=BaseDaemon] [thread_id=780]
[2025/05/14 01:46:22.843 +08:00] [ERROR] [BaseDaemon.cpp:559] ["\n  0xaaad99324274\tfaultSignalHandler(int, siginfo_t*, void*) [tiflash+121258612]\n                \tlibs/libdaemon/src/BaseDaemon.cpp:210\n  0xfffd2ce107c0\t<unknown symbol> [linux-vdso.so.1+1984]\n  0xff991e4fc4a8\t<unknown symbol>"] [source=BaseDaemon] [thread_id=780]
```
After some debug, we found the crash point is in
https://github.com/pingcap/tiflash/blob/5c59a514c5fec73b26e6773b57b968f2f59afb7f/dbms/src/Interpreters/JoinPartition.cpp#L1137

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #10163

Problem Summary:

Ref to #10163
### What is changed and how it works?

Use `alignAlloc` instead `alloc` to alloc memory for `CachedColumnInfo`
```commit-message
Fix TiFlash crash due to invalid address alignment
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Interpreters/JoinPartition.cpp [hunk 1]
```diff
@@ -45,7 +45,7 @@ void insertRowToList(JoinArenaPool & pool, List * list, Elem * elem, size_t cach
         if unlikely (cache_columns_threshold == list->list_length)
         {
             auto * cached_column_info
-                = reinterpret_cast<CachedColumnInfo *>(pool.arena.alloc(sizeof(CachedColumnInfo)));
+                = reinterpret_cast<CachedColumnInfo *>(pool.arena.alignedAlloc(sizeof(CachedColumnInfo), 16));
```
Comment (gengliqi) [inline dbms/src/Interpreters/JoinPartition.cpp:48]: It's recommended to use `alignof(std::max_align_t)` instead of 16 for better portability. https://en.cppreference.com/w/cpp/types/max_align_t

**Review by guo-shaoge — APPROVED** [review]

File: dbms/src/Common/tests/gtest_arena.cpp [hunk 2]
```diff
@@ -0,0 +1,32 @@
+// Copyright 2023 PingCAP, Inc.
```
Comment (guo-shaoge) [inline dbms/src/Common/tests/gtest_arena.cpp:1]:
```suggestion
// Copyright 2025 PingCAP, Inc.
```
