### PR TITLE
Optimize string sort for default collation `UTF8MB4_BIN`

### LINKED ISSUE #5366: Wrong behavior when handle `strcmp` with default collation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
drop table if exists t;
create table t (a varchar(100)) CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
alter table t set tiflash replica 1;

insert into t values('1   '), ('1\n'), ('1');
select hex(min(a)) from t;
```

MySQL version

```
mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.29    |
+-----------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)

```
MySQL [test]> select hex(min(a)) from t;
+-------------+
| hex(min(a)) |
+-------------+
| 31202020    |
+-------------+
```

### 3. What did you see instead (Required)

```
MySQL [test]> select hex(min(a)) from t;
+-------------+
| hex(min(a)) |
+-------------+
| 31          |
+-------------+
```

### 4. What is your TiFlash version? (Required)

master

### TiDB behavior

For mysql

```
mysql> SET NAMES utf8mb4 COLLATE utf8mb4_bin;
Query OK, 0 rows affected (0.00 sec)

mysql> select strcmp('1\0', '1');
+--------------------+
| strcmp('1\0', '1') |
+--------------------+
|                 -1 |
+--------------------+
1 row in set (0.00 sec)
```

For tidb

```
MySQL [test]> SET NAMES utf8mb4 COLLATE utf8mb4_bin;
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> select strcmp('1\0', '1');
+--------------------+
| strcmp('1\0', '1') |
+--------------------+
|                  1 |
+--------------------+
1 row in set (0.00 sec)
```

MySQL cmp '1\0' and '1':
- get min length of both string is 1;
- '1' and '1' are equal;
- the remain str in '1\0' is '\0', cmp '\0' with whit space ' ';
- cmp '\0' and ' ', same like cmp 0x0 and 0x20, got -1;

---

According to https://docs.pingcap.com/tidb/dev/character-set-and-collation, the tidb choose to remove tail space.
 
### Bug in tiflash

https://github.com/pingcap/tiflash/blob/432c153b3d708f680cdcd28f4fc6e794564130d6/dbms/src/Columns/ColumnString.cpp#L317-L318

tiflash show remove tail '\0'.

### PR DESCRIPTION
**Pull request by solotzg**
### What problem does this PR solve?

Issue Number: close #5366 ref #5294

Problem Summary:

- #5366: the original string contains '\0' at the end. To compare it under tidb collation, it must not be contained.

### What is changed and how it works?

- devirtualize function call when collation is `UTF8MB4_BIN`, which is the default one.

----

Tail '\0' doesn't be removed in those parts.

https://github.com/pingcap/tiflash/blob/3674439a1f1aeb09c70ad67f70cf5c2e961bd01a/dbms/src/Columns/ColumnString.h#L249
https://github.com/pingcap/tiflash/blob/3674439a1f1aeb09c70ad67f70cf5c2e961bd01a/dbms/src/Columns/ColumnString.h#L270
https://github.com/pingcap/tiflash/blob/432c153b3d708f680cdcd28f4fc6e794564130d6/dbms/src/Columns/ColumnString.cpp#L317-L318

### Benchmark

ENV:
- tpch100
- 1 tiflash
- limit cpu up to 200%
- original commit: 97342db2a1dd705b1bd98f3481d51f48a4f0300d

----

SQL
```
select min(L_SHIPMODE) from lineitem;
```

Time(s) | Original | Optimized | NoCollation |   |  
-- | -- | -- | -- | -- | --
  | 11.35 | 9.98 | 9.81 |   |  
  | 11.33 | 9.98 | 9.88 |   |  
  | 11.23 | 10 | 9.84 |   |  
  | 11.22 | 9.82 | 9.73 | NoCollation : Original | 15.22%
  | 11.58 | 9.95 | 9.96 | Optimized : Original | 14.04%
AVG | 11.342 | 9.946 | 9.844 | NoCollation : Optimized | 1.04%

----

SQL
```
select max(L_SHIPMODE) from lineitem;
```

Time(s) | Original | Optimized | NoCollation |   |  
-- | -- | -- | -- | -- | --
  | 13.56 | 12.62 | 12.77 |   |  
  | 13.74 | 12.51 | 12.27 |   |  
  | 13.35 | 12.61 | 12.32 |   |  
  | 13.63 | 12.63 | 12.45 | NoCollation : Original | 9.13%
  | 13.52 | 12.66 | 12.32 | Optimized : Original | 7.57%
AVG | 13.56 | 12.606 | 12.426 | NoCollation : Optimized | 1.45%

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/Transaction/Collator.h [hunk 1]
```diff
@@ -91,4 +119,119 @@ extern TiDBCollators dummy_collators;
...
+
+    explicit TiDBCollatorPtrImpl(class ITiDBCollator const * ptr_)
+        : TiDBCollatorID(ptr_ ? ptr_->getCollatorId() : 0)
+        , ptr(ptr_)
+    {
+    }
+
+    ALWAYS_INLINE inline int compare(const char * s1, size_t length1, const char * s2, size_t length2) const
+    {
+        if (likely(canUseFastPath()))
```
Comment (windtalker) [inline dbms/src/Storages/Transaction/Collator.h:140]: Will this `likely` hurt the performance of non-utf8mb4_bin collator?

File: dbms/src/Storages/Transaction/Collator.h [hunk 2]
```diff
@@ -91,4 +119,119 @@ extern TiDBCollators dummy_collators;
...
+        }
+        else
+        {
+            return compareIndirect(s1, length1, s2, length2);
+        }
+    }
+
+    ALWAYS_INLINE inline int compareIndirect(const char * s1, size_t length1, const char * s2, size_t length2) const
+    {
+        return ptr->compare(s1, length1, s2, length2);
```
Comment (windtalker) [inline dbms/src/Storages/Transaction/Collator.h:152]: Don't need to check if `ptr` is nullptr?

Comment (solotzg) [reply dbms/src/Storages/Transaction/Collator.h:152]: No need to check. Just like previous way, the caller must guarantee the pointer `class ITiDBCollator const *` is not null. `TiDBCollatorPtrImpl` is a wrap for raw poiner.

File: dbms/src/Storages/Transaction/Collator.h (hunk 1 above)
Comment (solotzg) [reply dbms/src/Storages/Transaction/Collator.h:140]: I think it will not hurt performance because the cost of local branch-jump is lower than virtual call.
`likely` is a **hint** for compiler to put branch closer to current instrument.

for example, with likely, maybe:
```
mov %eax,%esi // result = canUseFastPath()
test  %eax,%eax
je    ..... // jump to the branch DO NOT use fast path
.... // fast path branch
```

File: dbms/src/Storages/Transaction/Collator.h (hunk 2 above)
Comment (solotzg) [reply dbms/src/Storages/Transaction/Collator.h]: rollback those modifications.

File: dbms/src/Columns/ColumnString.cpp [hunk 3]
```diff
@@ -321,54 +323,94 @@ int ColumnString::compareAtWithCollationImpl(size_t n, size_t m, const IColumn &
...
+    // optimize path for default collator `UTF8MB4_BIN`
+    if (TiDB::ITiDBCollator::getCollator(TiDB::ITiDBCollator::UTF8MB4_BIN) == &collator)
     {
-        if (reverse)
-            std::sort(res.begin(), res.end(), lessWithCollation<false>(*this, collator));
-        else
-            std::sort(res.begin(), res.end(), lessWithCollation<true>(*this, collator));
+        Utf8MB4BinCmp cmp_impl;
+        PermutationWithCollationUtils::getPermutationWithCollationImpl(*this, cmp_impl, reverse, limit, res);
+        ///
```
Comment (windtalker) [inline dbms/src/Columns/ColumnString.cpp:408]: useless comment here?

File: dbms/src/Columns/ColumnString.cpp [hunk 4]
```diff
@@ -379,35 +421,73 @@ void ColumnString::updateWeakHash32(WeakHash32 & hash, const TiDB::TiDBCollatorP
...
+                auto sort_key = collator->sortKey(view.data(), view.size(), sort_key_container);
+                *hash_data = ::updateWeakHash32(reinterpret_cast<const UInt8 *>(sort_key.data), sort_key.size, *hash_data);
+                ++hash_data;
+            });
+        }
+    }
+    else
+    {
+        // Skip last zero byte.
+        LoopOneColumn(chars, offsets, offsets.size(), [&](const std::string_view & view, size_t) {
```
Comment (windtalker) [inline dbms/src/Columns/ColumnString.cpp:450]: Both `updateHashWithValues` and `updateHashWithValue` don't remove the last zero byte if `collator == nullptr`, I think we should also keep the last zero byte here, otherwise, it may make the others confused.

**Review by windtalker — APPROVED** [review]
LGTM

File: dbms/src/Columns/ColumnString.cpp (hunk 4 above)
Comment (solotzg) [reply dbms/src/Columns/ColumnString.cpp:450]: No change here. https://github.com/pingcap/tiflash/blob/99d9eb0646c077cbb186e8b8b31ae96f705bff5f/dbms/src/Columns/ColumnString.cpp#L484-L491.

The web of github show mistake.

**Review by zanmato1984 — APPROVED** [review]
LGTM
