### PR TITLE
.* introduce query executor

### LINKED ISSUE #4577: Tracing: the runtime statistics for fail task is empty
## Enhancement

For fail tasks, `mpp_task_statistics.collectRuntimeStatistics()` is skipped.
All tasks should call `mpp_task_statistics.collectRuntimeStatistics()`

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: ref #5900 close #4577

Problem Summary:

### What is changed and how it works?
- To hide the BlockInputStream from MPPTask, introduce the QueryExecutor.
- In https://github.com/pingcap/tiflash/pull/3687 we hold the BlockIO in DAGContext to make sure that process_list_entry destruct  after BlockInputStream. But now we hold the process_list_entry in DAGContext directly and no longer need to hold the BlockIO.
- Calling `collectRuntimeStatistics` even if stream execution fails.
- replace some `assert` by `RUNTIME_CHECK` in ExecutorStatistics.
- spilt `RemoteReader->getThreadCnt` from `TiRemoteBlockInputStream`

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/Mpp/MPPTask.cpp [hunk 1]
```diff
@@ -365,24 +369,22 @@ void MPPTask::runImpl()
...
-            continue;
 
-        // finish DataStream
-        from->readSuffix();
-        // finish receiver
-        receiver_set->close();
-        // finish MPPTunnel
-        finishWrite();
+        auto result = query_executor_holder.get().execute();
+        if (!result.is_success)
```
Comment (ywqzzy) [inline dbms/src/Flash/Mpp/MPPTask.cpp:374]:
```suggestion
        if (unlikely(!result.is_success))
```

File: dbms/src/Flash/Mpp/MPPTask.cpp [hunk 2]
```diff
@@ -510,11 +512,11 @@ bool MPPTask::scheduleThisTask(ScheduleState state)
 
 int MPPTask::estimateCountOfNewThreads()
 {
-    if (dag_context == nullptr || dag_context->getBlockIO().in == nullptr || dag_context->tunnel_set == nullptr)
+    if (!query_executor_holder.isHolding() || dag_context->tunnel_set == nullptr)
```
Comment (ywqzzy) [inline dbms/src/Flash/Mpp/MPPTask.cpp:515]: ditto

File: dbms/src/Flash/executeQuery.h [hunk 3]
```diff
@@ -16,9 +16,11 @@
 
 #include <Core/QueryProcessingStage.h>
 #include <DataStreams/BlockIO.h>
+#include <Flash/Executor/QueryExecutor.h>
 #include <Interpreters/Context.h>
 
 namespace DB
 {
 BlockIO executeQuery(Context & context, bool internal = false);
```
Comment (ywqzzy) [inline dbms/src/Flash/executeQuery.h:24]: Can we delete executeQuery?

Comment (SeaRise) [reply dbms/src/Flash/executeQuery.h:24]: Currently `DAGDriver` is still using this function.:(

File: dbms/src/Flash/Mpp/MPPTask.cpp (hunk 1 above)
Comment (SeaRise) [reply dbms/src/Flash/Mpp/MPPTask.cpp]: updated

File: dbms/src/Flash/Statistics/ExchangeReceiverImpl.cpp [hunk 4]
```diff
@@ -48,15 +48,16 @@ void ExchangeReceiverStatistics::collectExtraRuntimeDetail()
     {
         for (const auto & io_stream : it->second)
         {
-            auto * exchange_receiver_stream = dynamic_cast<ExchangeReceiverInputStream *>(io_stream.get());
             /// InBoundIOInputStream of ExchangeReceiver should be ExchangeReceiverInputStream
-            assert(exchange_receiver_stream);
-            const auto & connection_profile_infos = exchange_receiver_stream->getConnectionProfileInfos();
-            assert(connection_profile_infos.size() == partition_num);
-            for (size_t i = 0; i < partition_num; ++i)
+            if (auto * exchange_receiver_stream = dynamic_cast<ExchangeReceiverInputStream *>(io_stream.get()); exchange_receiver_stream)
```
Comment (windtalker) [inline dbms/src/Flash/Statistics/ExchangeReceiverImpl.cpp:52]: when will `exchange_receiver_stream` be nullptr?

Comment (SeaRise) [reply dbms/src/Flash/Statistics/ExchangeReceiverImpl.cpp:52]: Currently `exchange_receiver_stream` must not be nullptr.
This is just to avoid a tiflash crash in any case.

**Review by windtalker — APPROVED** [review]
LGTM

File: dbms/src/Flash/Executor/QueryExecutor.h [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+
+    virtual String dump() const = 0;
+
+    virtual int estimateNewThreadCount() = 0;
+
+protected:
+    virtual ExecutionResult execute(ResultHandler) = 0;
+
+protected:
+    ProcessListEntryPtr process_list_entry;
```
Comment (ywqzzy) [inline dbms/src/Flash/Executor/QueryExecutor.h:72]: When use it?

Comment (SeaRise) [reply dbms/src/Flash/Executor/QueryExecutor.h:72]: To make sure that process_list_entry destruct after BlockInputStream, just like BlockIO, although DAGContext already holds process_list_entry ...

**Review by ywqzzy — APPROVED** [review]
