### PR TITLE
fix tls ipv6 metric

### LINKED ISSUE #6734: Tiflash can't startup after enable tls and  set  preferIPv6 to True
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
config k8s cluster as following.
ipFamilyPolicy: PreferDualStack
ipFamilies:

IPv6
IPv4

Config tc as followings:
spec:
  preferIPv6: true
  tlsCluster:
    enabled: true
  version: master
...

deploy it in the k8s cluster.

### 2. What did you expect to see? (Required)
tiflash works fine.

### 3. What did you see instead (Required)
tiflash can't startup.
➜  ~ kubectl -n user-py get pod
NAME                               READY   STATUS             RESTARTS   AGE
basic-discovery-7c5945c84d-bmdb5   1/1     Running            0          136m
basic-monitor-0                    4/4     Running            0          139m
basic-pd-0                         1/1     Running            0          136m
basic-pd-1                         1/1     Running            0          136m
basic-pd-2                         1/1     Running            0          136m
basic-tidb-0                       2/2     Running            0          135m
basic-tidb-1                       2/2     Running            0          135m
basic-tiflash-0                    3/4     CrashLoopBackOff   28         122m
basic-tiflash-1                    3/4     CrashLoopBackOff   28         122m

### 4. What is your TiFlash version? (Required)
master

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: close #6734 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Server/MetricsPrometheus.cpp [hunk 1]
```diff
@@ -126,8 +126,8 @@ std::shared_ptr<Poco::Net::HTTPServer> getHTTPServer(
     Poco::Net::SecureServerSocket socket(context);
 
     Poco::Net::HTTPServerParams::Ptr http_params = new Poco::Net::HTTPServerParams;
-
-    Poco::Net::SocketAddress addr("0.0.0.0", std::stoi(metrics_port));
+    Poco::Net::SocketAddress addr;
+    addr = Poco::Net::SocketAddress(address);
```
Comment (LittleFall) [inline dbms/src/Server/MetricsPrometheus.cpp:130]:
```suggestion
    Poco::Net::SocketAddress addr = Poco::Net::SocketAddress(address);
```

File: dbms/src/Server/MetricsPrometheus.cpp [hunk 2]
```diff
@@ -137,6 +137,17 @@ std::shared_ptr<Poco::Net::HTTPServer> getHTTPServer(
 constexpr Int64 MILLISECOND = 1000;
 constexpr Int64 INIT_DELAY = 5;
 
+namespace
+{
+inline bool isIPv6(const String & input_address)
+{
+    char str[INET6_ADDRSTRLEN];
+    if (input_address.empty())
+        return false;
```
Comment (LittleFall) [inline dbms/src/Server/MetricsPrometheus.cpp:146]:
```suggestion
    if (input_address.empty())
        return false;
    char str[INET6_ADDRSTRLEN];
```

**Review by LittleFall — APPROVED** [review]

**Review by SeaRise — APPROVED** [review]
lgtm
