### PR TITLE
fix the schema version error in sync schema when latest schema diff is empty

### LINKED ISSUE #5397: May unexpectly run into storage.schema_version > tiflash_instance.schema_version
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

After https://github.com/pingcap/tiflash/pull/5245, we may run into a corner case that storage.schema_version > TiDBSchemaSyncer.cur_version.

Background:
After the feature [concurrent DDL](https://github.com/pingcap/tidb/issues/32031), TiDB does `update schema version` before `set schema diff`, and they are done in separate transactions.
So TiFlash may see a schema version X but no schema diff X, meaning that the transaction of schema diff X has not been committed or has been aborted.
However, TiDB makes sure that if we get a schema version X, then the schema diff X-1 must exist. Otherwise the transaction of schema diff X-1 is aborted and we can safely ignore it.
Since TiDB can not make sure the schema diff of the latest schema version X is not empty, under this situation we should set the `cur_version` to X-1 and try to fetch the schema diff X next time.

However, even if the last schema diff X is empty, the schema builder is now still constructed with X but not X-1. So we will update table.schema_version to X but TiDBSchemaSyncer.cur_version to X-1. That will make some queries fail unexpectedly.

https://github.com/pingcap/tiflash/blob/709918497fe6588369a73aaf8b6570c0635641c4/dbms/src/TiDB/Schema/TiDBSchemaSyncer.h#L170-L181
https://github.com/pingcap/tiflash/blob/709918497fe6588369a73aaf8b6570c0635641c4/dbms/src/TiDB/Schema/TiDBSchemaSyncer.h#L248-L252

Codes snippets for updating storage.table_info.schema_version
https://github.com/pingcap/tiflash/blob/709918497fe6588369a73aaf8b6570c0635641c4/dbms/src/TiDB/Schema/SchemaBuilder.h#L38-L44
https://github.com/pingcap/tiflash/blob/709918497fe6588369a73aaf8b6570c0635641c4/dbms/src/TiDB/Schema/SchemaBuilder.cpp#L383-L384
https://github.com/pingcap/tiflash/blob/709918497fe6588369a73aaf8b6570c0635641c4/dbms/src/TiDB/Schema/SchemaBuilder.cpp#L1061-L1062

### 2. What did you expect to see? (Required)
- For `tryLoadSchemaDiffs`
We should first fetch the schema diff and check whether the schema diff of X is empty or not before creating the `SchemaBuilder` instance. If the schema diff of X is empty, we should set `SchemaBuilder.target_version` to be X-1
- For `loadAllSchema`
We should check the diff by `getter.checkSchemaDiffExists` before creating the `SchemaBuilder` instance. Not do the check after `loadAllSchema` is done.

And we should add some unit test cases

### 4. What is your TiFlash version? (Required)
master

### LINKED ISSUE #5499: Detect data inconsistency after switching table mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

case 情况与日志
https://github.com/pingcap/endless/blob/d8015156435e768921a3c1a2e48bcc2b59267dba/testcase/tiflash/consistency/consistency_test.go#L98

[2022/07/28 19:22:15.051 +08:00] [INFO] [consistency_test.go:515] ["convert tiflash mode"] ["db name"=test] ["table names"="[t]"] [mode=fast]
[2022/07/28 19:22:15.206 +08:00] [INFO] [consistency_test.go:504] ["convert tiflash mode"] ["db name"=test] ["table names"="[t]"] [mode=normal]
[2022/07/28 19:22:15.832 +08:00] [INFO] [verify.go:127] ["verify successfully"] [tikv="[100000000]"] [tiflash="[100000000]"]
[2022/07/28 19:22:25.833 +08:00] [INFO] [consistency_test.go:515] ["convert tiflash mode"] ["db name"=test] ["table names"="[t]"] [mode=fast]
[2022/07/28 19:22:25.992 +08:00] [INFO] [consistency_test.go:504] ["convert tiflash mode"] ["db name"=test] ["table names"="[t]"] [mode=normal]
[2022/07/28 19:22:26.633 +08:00] [INFO] [verify.go:127] ["verify successfully"] [tikv="[100000000]"] [tiflash="[100000000]"]
[2022/07/28 19:22:36.635 +08:00] [INFO] [consistency_test.go:515] ["convert tiflash mode"] ["db name"=test] ["table names"="[t]"] [mode=fast]
[2022/07/28 19:22:36.788 +08:00] [INFO] [consistency_test.go:504] ["convert tiflash mode"] ["db name"=test] ["table names"="[t]"] [mode=normal]
[2022/07/28 19:22:37.475 +08:00] [INFO] [verify.go:127] ["verify successfully"] [tikv="[100000000]"] [tiflash="[100000000]"]
[2022/07/28 19:22:47.475 +08:00] [INFO] [consistency_test.go:515] ["convert tiflash mode"] ["db name"=test] ["table names"="[t]"] [mode=fast]
[2022/07/28 19:22:47.629 +08:00] [INFO] [consistency_test.go:504] ["convert tiflash mode"] ["db name"=test] ["table names"="[t]"] [mode=normal]
[2022/07/28 19:22:48.229 +08:00] [ERROR] [consistency_test.go:508] ["check consistence error"] ["db name"=test] [sql="select count(*) from t"] [error="result inconsistent tso 434898827405164654, tikv: [100000000], tiflash [100000750]"]

### 4. What is your TiFlash version? (Required)
v6.2

### PR DESCRIPTION
**Pull request by hongyunyan**
### What problem does this PR solve?

Issue Number: close #5499 close #5397 

Problem Summary:

### What is changed and how it works?

In schemaBuilder.apply(schema diff), we will update the storageDeltaMerge schema version based on the global schema version. 
Thus we need to check whether the latest schema diff is empty before apply diff (in this case we need to update version = version - 1 first)

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 1]
```diff
@@ -180,6 +178,16 @@ struct TiDBSchemaSyncer : public SchemaSyncer
         }
         LOG_FMT_DEBUG(log, "End load schema diffs with total {} entries.", diffs.size());
 
+
+        // Since the latest schema diff may be empty, and schemaBuilder may need to update the latest version for storageDeltaMerge,
+        // Thus we need check whehter latest schema diff is empty or not before begin to builder.applyDiff.
```
Comment (lidezhu) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:183]:
```suggestion
        // Thus we need check whether latest schema diff is empty or not before begin to builder.applyDiff.
```

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 2]
```diff
@@ -180,6 +178,16 @@ struct TiDBSchemaSyncer : public SchemaSyncer
...
+        if (!diffs.back())
```
Comment (lidezhu) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:184]: Maybe we can pop back the last diff here. And also update `used_version` and add some comment here.
And later logic can be changed to something like
```
for (size_t diff_index = 0; diff_index < diffs.size(); ++diff_index)
{
     const auto & schema_diff = diffs[diff_index];
     if (!schema_diff)
     {
          /// some comment
          LOG_FMT_WARNING(log, "Skip the schema diff from version {}. ", cur_version + diff_index + 1);
          continue;
     }
     builder.applyDiff(*schema_diff);
}
return used_version;
```
This just looks more clear to me.

Comment (hongyunyan) [reply dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:184]: Yes, I think it's better, and I change the logic follow this.

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 3]
```diff
@@ -180,6 +178,18 @@ struct TiDBSchemaSyncer : public SchemaSyncer
         }
         LOG_FMT_DEBUG(log, "End load schema diffs with total {} entries.", diffs.size());
 
+
+        // Since the latest schema diff may be empty, and schemaBuilder may need to update the latest version for storageDeltaMerge,
+        // Thus we need check whether latest schema diff is empty or not before begin to builder.applyDiff.
+        if (!diffs.back())
+        {
+            --latest_version;
```
Comment (lidezhu) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:186]: No need update `latest_version` because we can just use `used_version` later.

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 4]
```diff
@@ -180,6 +178,18 @@ struct TiDBSchemaSyncer : public SchemaSyncer
...
+            --used_version;
+            diffs.pop_back();
+        }
+
+        SchemaBuilder<Getter, NameMapper> builder(getter, context, databases, latest_version);
```
Comment (lidezhu) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:191]:
```suggestion
        SchemaBuilder<Getter, NameMapper> builder(getter, context, databases, used_version);
```

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 5]
```diff
@@ -188,25 +198,10 @@ struct TiDBSchemaSyncer : public SchemaSyncer
...
-                    //  - The schema diff of schema version 10 is empty, Then we should just apply version into 9
-                    if (diff_index != diffs.size() - 1)
-                    {
-                        LOG_FMT_WARNING(log, "Skip the schema diff from version {}. ", cur_version + diff_index + 1);
-                        continue;
-                    }
-
-                    // if diff_index == diffs.size() - 1, return used_version - 1;
-                    return used_version - 1;
+                    // If `schema diff` got empty `schema diff`(it's not the latest one, due to we check it before), we should just skip it.
```
Comment (lidezhu) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:201]:
```suggestion
                    // If `schema diff` got empty `schema diff`(it's not the latest one, due to we check it before), we should just skip it.
                    //
                    // example:
                    //  - `cur_version` is 1, `latest_version` is 10
                    //  - The schema diff of schema version [2,4,6] is empty, Then we just skip it.
                    //  - The schema diff of schema version 10 is empty, Then we should just apply version into 9
```

**Review by lidezhu — APPROVED** [review]
LGTM with minor comment

**Review by flowbehappy — APPROVED** [review]

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 6]
```diff
@@ -180,6 +178,17 @@ struct TiDBSchemaSyncer : public SchemaSyncer
         }
         LOG_FMT_DEBUG(log, "End load schema diffs with total {} entries.", diffs.size());
 
+
+        // Since the latest schema diff may be empty, and schemaBuilder may need to update the latest version for storageDeltaMerge,
+        // Thus we need check whether latest schema diff is empty or not before begin to builder.applyDiff.
+        if (!diffs.back())
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:184]: Add a sanity check that if `diffs.empty()`, then throw an exception

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 7]
```diff
@@ -124,9 +124,9 @@ struct TiDBSchemaSyncer : public SchemaSyncer
         if (version_after_load_diff = tryLoadSchemaDiffs(getter, version, context); version_after_load_diff == -1)
         {
             GET_METRIC(tiflash_schema_apply_count, type_full).Increment();
-            loadAllSchema(getter, version, context);
-            // After loadAllSchema, we need update `version_after_load_diff` by last diff value exist or not
+            // we need update `version_after_load_diff` by last diff value exist or not
             version_after_load_diff = getter.checkSchemaDiffExists(version) ? version : version - 1;
+            loadAllSchema(getter, version_after_load_diff, context);
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:129]: I think making it to be
`version_after_load_diff = loadAllSchema(getter, version, context);`
and move `getter.checkSchemaDiffExists` into the function `loadAllSchema` is better.

After that change, the two functions `tryLoadSchemaDiffs`, `loadAllSchema` handle similar problem inside the function

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 8]
```diff
@@ -245,10 +247,14 @@ struct TiDBSchemaSyncer : public SchemaSyncer
         return used_version;
     }
 
-    void loadAllSchema(Getter & getter, Int64 version, Context & context)
+    Int64 loadAllSchema(Getter & getter, Int64 version, Context & context)
     {
+        if (!getter.checkSchemaDiffExists(version)){
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:252]: format

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 9]
```diff
@@ -14,6 +14,7 @@
 
 #pragma once
 
+#include "common/logger_useful.h"
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:17]:
```suggestion
#include <common/logger_useful.h>
```

File: dbms/src/TiDB/Schema/TiDBSchemaSyncer.h [hunk 10]
```diff
@@ -180,6 +177,21 @@ struct TiDBSchemaSyncer : public SchemaSyncer
         }
         LOG_FMT_DEBUG(log, "End load schema diffs with total {} entries.", diffs.size());
 
+
+        if (diffs.empty()){
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDBSchemaSyncer.h:181]: format

**Review by JaySon-Huang — APPROVED** [review]
LGTM with some small coding style issue
