### PR TITLE
Adapt to the blocklist feature in serverless

### LINKED ISSUE #9575: Introduce blocklist mechanism on serverless TiFlash WN node
## Enhancement

When selecting TiFlash stores on batch cop tasks, we filter blocked TiFlash stores.

If no stores are available, the backoffer will eventrually throw Exceptions.

1. https://github.com/tikv/client-c/pull/198
2. https://github.com/tidbcloud/tiflash-cse/pull/308

### PR DESCRIPTION
**Pull request by CalvinNeo**
Issue Number: close #9575

Problem Summary:

The feature is not enabled on master branch.

See https://github.com/tidbcloud/tiflash-cse/pull/308 for more.

### What is changed and how it works?

```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]
lgtm

File: dbms/src/Storages/StorageDisaggregated.h [hunk 1]
```diff
@@ -154,5 +154,6 @@ class StorageDisaggregated : public IStorage
     const FilterConditions & filter_conditions;
 
     std::unique_ptr<DAGExpressionAnalyzer> analyzer;
+    std::unordered_set<uint64_t> store_id_blocklist;
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/StorageDisaggregated.h:157]: It will eventually be converted to unordered_set as an argument to a API in client-c. A better way(if necessay) is make store_id_blocklist into a sigleton.

File: dbms/src/Storages/StorageDisaggregated.cpp [hunk 2]
```diff
@@ -37,7 +37,37 @@ StorageDisaggregated::StorageDisaggregated(
     , log(Logger::get(context_.getDAGContext()->log ? context_.getDAGContext()->log->identifier() : ""))
     , sender_target_mpp_task_id(context_.getDAGContext()->getMPPTaskMeta())
     , filter_conditions(filter_conditions_)
-{}
+{
+#if SERVERLESS_PROXY == 1
+    std::istringstream iss(context.getSettingsRef().disagg_blocklist_wn_store_id);
+    std::string token;
+
+    while (std::getline(iss, token, ','))
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/StorageDisaggregated.cpp:45]: Seems the function is not applicable to unordereed_set

File: dbms/src/Storages/StorageDisaggregated.cpp [hunk 3]
```diff
@@ -37,7 +37,37 @@ StorageDisaggregated::StorageDisaggregated(
     , log(Logger::get(context_.getDAGContext()->log ? context_.getDAGContext()->log->identifier() : ""))
     , sender_target_mpp_task_id(context_.getDAGContext()->getMPPTaskMeta())
     , filter_conditions(filter_conditions_)
-{}
+{
+#if SERVERLESS_PROXY == 1
+    std::istringstream iss(context.getSettingsRef().disagg_blocklist_wn_store_id);
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/StorageDisaggregated.cpp]: fixed

File: dbms/src/Interpreters/Context.h [hunk 4]
```diff
@@ -190,6 +190,9 @@ class Context
     }};
     using DatabasePtr = std::shared_ptr<IDatabase>;
     using Databases = std::map<String, std::shared_ptr<IDatabase>>;
+
+    std::unordered_set<uint64_t> store_id_blocklist;
```
Comment (JaySon-Huang) [inline dbms/src/Interpreters/Context.h:194]: It should be a member of the `ContextShared` rather than `Context`.
`ContextShared` is set in the `global_context` and shared by all connections to the tiflash instance. While `Context` is a session level instance that these variable will be copied from the global_context and can be overwritten

File: dbms/src/Interpreters/Context.cpp [hunk 5]
```diff
@@ -2218,6 +2220,48 @@ void Context::setMockMPPServerInfo(MockMPPServerInfo & info)
...
+        {
+            // Keep empty
+            LOG_INFO(DB::Logger::get(), "Error disagg_blocklist_wn_store_id setting, {}", comma_sep_string);
+            shared->store_id_blocklist.clear();
+            return false;
+        }
+    }
+
+    if (!shared->store_id_blocklist.empty())
+        LOG_DEBUG(
```
Comment (JaySon-Huang) [inline dbms/src/Interpreters/Context.cpp:2252]: Use "INFO" level here

File: dbms/src/Interpreters/Context.cpp [hunk 6]
```diff
@@ -2218,6 +2220,48 @@ void Context::setMockMPPServerInfo(MockMPPServerInfo & info)
...
+            DB::Logger::get(),
+            "Blocklisted {} stores, which are {}",
+            shared->store_id_blocklist.size(),
+            comma_sep_string);
```
Comment (JaySon-Huang) [inline dbms/src/Interpreters/Context.cpp:2256]:
```suggestion
            "StoreIdBlockList have been set, {}",
            shared->store_id_blocklist);
```

File: dbms/src/Interpreters/Context.cpp [hunk 7]
```diff
@@ -2218,6 +2220,48 @@ void Context::setMockMPPServerInfo(MockMPPServerInfo & info)
...
+    {
+        try
+        {
+            uint64_t number = std::stoull(token);
+            shared->store_id_blocklist.insert(number);
+        }
+        catch (...)
+        {
+            // Keep empty
+            LOG_INFO(DB::Logger::get(), "Error disagg_blocklist_wn_store_id setting, {}", comma_sep_string);
```
Comment (JaySon-Huang) [inline dbms/src/Interpreters/Context.cpp:2245]:
```suggestion
            LOG_INFO(DB::Logger::get(), "StoreIdBlockList is not set, input_str={}", comma_sep_string);
```

File: dbms/src/Interpreters/Context.h (hunk 4 above)
Comment (CalvinNeo) [reply dbms/src/Interpreters/Context.h]: Fixed

File: dbms/src/Interpreters/Context.cpp (hunk 5 above)
Comment (CalvinNeo) [reply dbms/src/Interpreters/Context.cpp]: fixed

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Comment by CalvinNeo** [comment]
```

tidb-ci/force_enable_lm/timestamp_literal.test: Running

  File: tidb-ci/force_enable_lm/timestamp_literal.test

  Error line: 22

  Error: set @@tidb_isolation_read_engines='tiflash'; set time_zone = '+9:00'; select * from test.t where value = (select max(value) from test.t);

  Result:

    ERROR 1105 (HY000) at line 1: interface conversion: interface is nil, not base.Plan

  Expected:

    +------+---------------------+

    | id   | value               |

    +------+---------------------+

    |    1 | 2020-01-01 09:00:00 |

    +------+---------------------+
```
