### PR TITLE
fix unstable ut.

### LINKED ISSUE #6261: Unstable unit test improvements

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #6261 

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JaySon-Huang — APPROVED** [review]

File: dbms/src/Encryption/tests/gtest_rate_limiter.cpp [hunk 1]
```diff
@@ -368,10 +368,14 @@ TEST(ReadLimiterTest, ReadMany)
...
-    std::this_thread::sleep_for(1200ms);
     Stopwatch sw;
-    request(read_limiter, 100);
-    ASSERT_LE(sw.elapsedMilliseconds(), 1); // Not blocked.
+    request(read_limiter, 1); // About 1000ms
+    auto req_ms = sw.elapsedMilliseconds();
+    // Theoretical value of `req_ms` is 1000.
+    // But time can be affected by many factors,
+    // such as machine load, process scheduling delays, clock jitter.
+    ASSERT_GE(req_ms, 950);
```
Comment (Lloyd-Pottiger) [inline dbms/src/Encryption/tests/gtest_rate_limiter.cpp:377]: Will it be smaller than the refill period?

Comment (Lloyd-Pottiger) [reply dbms/src/Encryption/tests/gtest_rate_limiter.cpp:377]: ok, get it.

**Review by Lloyd-Pottiger — APPROVED** [review]
