### PR TITLE
fix the bug that Planner Interpreter lost the metric `Executor OPS`

### LINKED ISSUE #6276: metrics: metric `Executor OPS` is lost
## Bug Report

Please answer these questions before submitting your issue. Thanks!

img_v2_73935ea3-d2b6-47ac-a479-455a90b2e83g

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #6276

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix the bug that Planner Interpreter lost the metric `Executor OPS`
```

### CODE REVIEW

**Comment by SeaRise** [comment]
image

File: dbms/src/Flash/Planner/PhysicalPlan.cpp [hunk 1]
```diff
@@ -82,19 +83,32 @@ void PhysicalPlan::build(const tipb::DAGRequest * dag_request)
...
+    dagContext().table_scan_executor_id = executor_id;
+}
+
 void PhysicalPlan::build(const String & executor_id, const tipb::Executor * executor)
 {
     assert(executor);
     switch (executor->tp())
     {
     case tipb::ExecType::TypeLimit:
+        GET_METRIC(tiflash_coprocessor_executor_count, type_limit).Increment();
```
Comment (ywqzzy) [inline dbms/src/Flash/Planner/PhysicalPlan.cpp:102]: When will we decrease the metric?

Comment (SeaRise) [reply dbms/src/Flash/Planner/PhysicalPlan.cpp:102]: It don't need to decrease, because of https://github.com/pingcap/tiflash/blob/35bbaf0695817034d9169c8c997846f73f5c2e69/metrics/grafana/tiflash_summary.json#L2517

**Review by windtalker — APPROVED** [review]
LGTM

**Review by ywqzzy — APPROVED** [review]
