### PR TITLE
Fix unstable ut.

### LINKED ISSUE #6104: `TEST_P(DeltaMergeStoreRWTest, DMFileNameChangedInDMFileReadPool)`  is unstable
`TEST_P(DeltaMergeStoreRWTest, DMFileNameChangedInDMFileReadPool)`  is unstable:

```
[2022-10-11T04:12:46.899Z] /home/jenkins/agent/workspace/tiflash-build-common/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp:206: Failure
[2022-10-11T04:12:46.899Z] Expected: (reader) != (nullptr), actual: NULL vs (nullptr)
```

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #6104 

Problem Summary:

If a segment has very little data, it will be read very quickly and push to the block queue, `DMFileReader` will be released after that.

### What is changed and how it works?

Write more block when preparing test data and the block queue will reach limit when there is more the 3 blocks in this case, so `DMFileReader` will not be released.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp [hunk 1]
```diff
@@ -163,20 +162,24 @@ try
 
     // Ensure delta is not empty.
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp:163]:
```suggestion
    static const size_t NUMBER_OF_BLOCKS_IN_DELTA = 10;
    static const size_t NUMBER_OF_BLOCKS_IN_STABLE = 1;
    // Ensure delta is not empty.
```

File: dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp [hunk 2]
```diff
@@ -163,20 +162,24 @@ try
...
-        block.insert(DB::tests::createColumn<String>(
-            createNumberStrings(beg, end),
-            col_str_define.name,
-            col_str_define.id));
-        block.insert(DB::tests::createColumn<Int8>(
-            createSignedNumbers(beg, end),
-            col_i8_define.name,
-            col_i8_define.id));
-        store->write(*db_context, db_context->getSettingsRef(), block);
+        for (size_t i = 0; i < 10; i++)
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp:165]:
```suggestion
        for (size_t i = 0; i < NUMBER_OF_BLOCKS_IN_DELTA; ++i)
```

File: dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp [hunk 3]
```diff
@@ -163,20 +162,24 @@ try
...
+            block.insert(DB::tests::createColumn<Int8>(
+                createSignedNumbers(beg, end),
+                col_i8_define.name,
+                col_i8_define.id));
+            store->write(*db_context, db_context->getSettingsRef(), block);
+            ASSERT_TRUE(store->flushCache(*db_context, RowKeyRange::newAll(store->isCommonHandle(), store->getRowKeyColumnSize())));
+        }
         auto delta = store->id_to_segment.begin()->second->getDelta();
-        ASSERT_EQ(delta->getRows(), num_rows_write);
+        ASSERT_EQ(delta->getRows(), num_rows_write * 10);
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp:182]:
```suggestion
        ASSERT_EQ(delta->getRows(), num_rows_write * NUMBER_OF_BLOCKS_IN_DELTA);
```

File: dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp [hunk 4]
```diff
@@ -210,7 +213,7 @@ try
         ASSERT_TRUE(store->flushCache(*db_context, RowKeyRange::newAll(store->isCommonHandle(), store->getRowKeyColumnSize())));
         store->mergeDeltaAll(*db_context);
         auto stable = store->id_to_segment.begin()->second->getStable();
-        ASSERT_EQ(stable->getRows(), 2 * num_rows_write);
+        ASSERT_EQ(stable->getRows(), 11 * num_rows_write);
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp:216]:
```suggestion
        ASSERT_EQ(stable->getRows(), (NUMBER_OF_BLOCKS_IN_DELTA + NUMBER_OF_BLOCKS_IN_STABLE) * num_rows_write);
```

**Review by Lloyd-Pottiger — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]
