### PR TITLE
Disagg: Retry when the stream state of S3 is not good

### LINKED ISSUE #9695: Download data from S3 failed with: "cannot load checksum framed data from"
## Bug Report
An issue reported in the asktug (https://asktug.com/t/topic/1035389)

### 1. Minimal reproduce step (Required)
Execute statement on a large table(data size large than 1TB) with TiFlash Aggregation 

### 3. What did you see instead (Required)
```
other error for mpp stream: Code: 0, e.displayText() = DB::Exception: cannot load checksum framed data from tiflash-remote-data/s18195849145/data/t_38167/dmf_610890/2.dat (errno = 0): (while reading from DTFile: s3://s18195849145/data/t_38167/dmf_610890), e.what() = DB::Exception, - java.sql.SQLException: other error for mpp stream: Code: 0, e.displayText() = DB::Exception: cannot load checksum framed data from tiflash-remote-data/s18195849145/data/t_38167/dmf_610890/2.dat (errno = 0): (while reading from DTFile: s3://s18195849145/data/t_38167/dmf_610890), e.what() = DB::Exception
```

### 4. What is your TiFlash version? (Required)
7.5.4

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #9695

Problem Summary: 

The input stream of S3 may failed with errno is 0, but `istr.rdstat()` is abnormal. 

### What is changed and how it works?

Check the state of input stream and retry requests if state is abnormal.

```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/S3/S3RandomAccessFile.cpp [hunk 1]
```diff
@@ -64,17 +63,23 @@ std::string S3RandomAccessFile::getInitialFileName() const
     return remote_fname;
 }
 
-bool isRetryableError(int e)
+namespace
 {
-    return e == ECONNRESET || e == EAGAIN;
+static constexpr int S3UnknownError = -1;
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/S3/S3RandomAccessFile.cpp:68]: In anonymous namespace, static is not necessary?

File: dbms/src/Storages/S3/S3RandomAccessFile.cpp [hunk 2]
```diff
@@ -163,8 +171,15 @@ off_t S3RandomAccessFile::seekImpl(off_t offset_, int whence)
     auto & istr = read_result.GetBody();
     if (!istr.ignore(offset_ - cur_offset))
     {
-        LOG_ERROR(log, "Cannot ignore from istream, errmsg={}, cost={}ns", strerror(errno), sw.elapsed());
-        return -1;
+        auto state = istr.rdstate();
+        LOG_ERROR(
+            log,
+            "Cannot ignore from istream, state=0x{:02X}, errno={}, errmsg={}, cost={}ns",
```
Comment (JaySon-Huang) [inline dbms/src/Storages/S3/S3RandomAccessFile.cpp:177]:
```suggestion
            "Cannot ignore from istream, state=0x{:02X}, errno={} errmsg={} cost={}ns",
```

**Review by JaySon-Huang — COMMENTED** [review]
Rest LGTM

**Review by Lloyd-Pottiger — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]
