### PR TITLE
fix: time unit not match in ThreadMetricUtil.cpp

### LINKED ISSUE #5595: time unit not match in ThreadMetricUtil.cpp
## Bug Report

Please answer these questions before submitting your issue. Thanks!

https://github.com/pingcap/tiflash/blob/f094fa5b27156789b3ba629360396d887939de78/dbms/src/Common/ThreadMetricUtil.cpp#L27-L28

max_thds_metric_reset_interval is in seconds.

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
Signed-off-by: Lloyd-Pottiger <yan1579196623@gmail.com>

### What problem does this PR solve?

Issue Number: close #5595

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Lloyd-Pottiger** [comment]
/cc @fuzhe1989 @ywqzzy @bestwoody 
PTAL again 😭

**Review by fuzhe1989 — APPROVED** [review]

File: dbms/src/Common/ThreadMetricUtil.cpp [hunk 1]
```diff
@@ -12,24 +12,24 @@
...
 
 namespace DB
 {
 bool tryToResetMaxThreadsMetrics()
 {
-    using nanoseconds = std::chrono::duration<UInt64, std::nano>;
-    UInt64 last_max_thds_metric_reset_ts_tmp = last_max_thds_metric_reset_ts.load(std::memory_order_relaxed);
-    UInt64 now_ts = clock_gettime_ns_adjusted(last_max_thds_metric_reset_ts_tmp, CLOCK_MONOTONIC);
-    if (nanoseconds(now_ts) > nanoseconds(last_max_thds_metric_reset_ts_tmp) + max_thds_metric_reset_interval)
+    auto last_max_thds_metric_reset_ts_tmp = last_max_thds_metric_reset_ts.load(std::memory_order_relaxed);
```
Comment (bestwoody) [inline dbms/src/Common/ThreadMetricUtil.cpp:28]: is overhead of new one same as clock_monotonic？

Comment (Lloyd-Pottiger) [reply dbms/src/Common/ThreadMetricUtil.cpp:28]: actually, a little bit slower……

Comment (bestwoody) [reply dbms/src/Common/ThreadMetricUtil.cpp:28]: then I think that will be bad，why bother changing into a slower one...

Comment (Lloyd-Pottiger) [reply dbms/src/Common/ThreadMetricUtil.cpp:28]: > Class std::chrono::steady_clock represents a monotonic clock. The time points of this clock cannot decrease as physical time moves forward and the time between ticks of this clock is constant. This clock is not related to wall clock time (for example, it can be time since last reboot), **and is most suitable for measuring intervals**.

Comment (Lloyd-Pottiger) [reply dbms/src/Common/ThreadMetricUtil.cpp:28]: it is better to use `std::chrono::steady_clock` to measure intervals.

Comment (Lloyd-Pottiger) [reply dbms/src/Common/ThreadMetricUtil.cpp:28]: > actually, a little bit slower……

sorry for misleading, std::chrono::steady_clock is also CLOCK_MONOTONIC, so there is no difference in performance. Any other suggestions?

Comment (fuzhe1989) [reply dbms/src/Common/ThreadMetricUtil.cpp:28]: Guess `std::chrono::steady_clock` actually calls `clock_gettime(MONOTONIC)`. you can try to confirm it.

Comment (fuzhe1989) [reply dbms/src/Common/ThreadMetricUtil.cpp:28]: libstdc++: https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/src/c%2B%2B11/chrono.cc#L87

Comment (fuzhe1989) [reply dbms/src/Common/ThreadMetricUtil.cpp:28]: libc++: https://github.com/llvm-mirror/libcxx/blob/master/src/chrono.cpp#L220

Comment (fuzhe1989) [reply dbms/src/Common/ThreadMetricUtil.cpp:28]: please do things right.

**Review by bestwoody — APPROVED** [review]
lgtm

File: dbms/src/Common/ThreadMetricUtil.cpp (hunk 1 above)
Comment (bestwoody) [reply dbms/src/Common/ThreadMetricUtil.cpp:28]: lgtm
