### PR TITLE
Limit memory usage of RNDeltaIndexCache

### LINKED ISSUE #7835: another tiflash compute node oom after kill one tiflash compute node
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、go-tpc ch run -D tpcc --host tc-tidb.endless-ha-test-tps-1746057-1-590 -P4000 --warehouses 2000 -T 32 --acThreads 1 --queries q16 --ignore-error '2013,1213,1105,1205,8022,8028,9004,9007,1062' --time 36000m --user root --password '' --interval '10s'
2、kill one tiflash compute node
[2023/07/20 23:48:06.342 +08:00] [INFO] [chaos.go:172] ["Run chaos"] [name=kill] [selectors="[endless-ha-test-tps-1746057-1-590/secondary-tc-tiflash-0]"] [SelectorsRetainPolicy(selectors)="[endless-ha-test-tps-1746057-1-590/secondary-tc-tiflash-0]"] [targetSelectors="[nil]"] [TargetSelectorsRetainPolicy(targetSelectors)="[nil]"] [experimentSpec="ContainerKillExperimentSpec{Scheduler: <nil>}"]
[2023/07/20 23:48:08.806 +08:00] [INFO] [collection.go:295] ["[2023-07-20 15:48:08] execute run failed, err execute query q16 failed Error 1105: rpc error: code = Unavailable desc = error reading from server: EOF\r\n"]

### 2. What did you expect to see? (Required)
another tiflash compute node is normal

### 3. What did you see instead (Required)
another tiflash compute node oom after kill one tiflash compute node

### 4. What is your TiFlash version? (Required)
githash：a6fcff576c61ee3af11c7f0d6a6f0982866e0914

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #7835

Problem Summary:

Memory usage of `RNDeltaIndexCache` is too high and can only limit the number of `DeltaIndex` in  `RNDeltaIndexCache`. Limiting the memory usage by size is not supported.

### What is changed and how it works?

- `RNDeltaIndexCache` supports limiting memory usage by size. By default, it use 2% of memory capacity.
image

- Add cache hit rate monitoring.
image

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  - TiFlash is not OOM.
image
image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Server/Server.cpp [hunk 1]
```diff
@@ -1410,22 +1410,19 @@ int Server::main(const std::vector<std::string> & /*args*/)
         global_context->setMinMaxIndexCache(minmax_index_cache_size);
 
     /// Size of max memory usage of DeltaIndex, used by DeltaMerge engine.
-    /// This setting is currently a bit tricky:
     /// - In non-disaggregated mode, its default value is 0, means unlimited, and it
-    //    controls the number of total bytes keep in the memory.
-    /// - In disaggregated mode, its default value is 2000. 0 means cache is disabled, and it
-    ///   controls the **number** of trees keep in the memory. <-- Will be fixed.
+    ///   controls the number of total bytes keep in the memory.
+    /// - In disaggregated mode, its default value is memory_capacity_of_host * 0.02.
```
Comment (JaySon-Huang) [inline dbms/src/Server/Server.cpp:1415]:
```suggestion
    /// - In disaggregated mode, its default value is memory_capacity_of_host * 0.02.
    ///   0 means cache is disabled.
```
https://github.com/pingcap/tiflash/blob/bccc345b8a82f1c9c96aeaf400557e252073bfd9/dbms/src/Interpreters/SharedContexts/Disagg.cpp#L75-L83

File: dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.cpp [hunk 2]
```diff
@@ -12,18 +12,49 @@
...
+    {
+        std::lock_guard lock(mtx);
+        if (auto value = cache.get(*key); value)
+        {
+            auto new_bytes = delta_index->getBytes();
+            if (new_bytes > value->bytes)
+            {
+                cache.set(*key, std::make_shared<CacheValue>(delta_index, new_bytes));
+                CurrentMetrics::set(CurrentMetrics::DT_DeltaIndexCacheSize, cache.weight());
+            }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.cpp:55]: why only update the cache when its bytes getting bigger?

File: dbms/src/Common/TiFlashMetrics.h [hunk 3]
```diff
@@ -671,7 +671,8 @@ namespace DB
     M(tiflash_system_seconds,                                                                                                       \
       "system calls duration in seconds",                                                                                           \
       Histogram,                                                                                                                    \
-      F(type_fsync, {{"type", "fsync"}}, ExpBuckets{0.0001, 2, 20}))
+      F(type_fsync, {{"type", "fsync"}}, ExpBuckets{0.0001, 2, 20}))                                                                \
+    M(tiflash_rn_delta_index_cache, "", Counter, F(type_hit, {"type", "hit"}), F(type_miss, {"type", "miss"}))
```
Comment (JaySon-Huang) [inline dbms/src/Common/TiFlashMetrics.h:675]:
```suggestion
    M(tiflash_storage_delta_index_cache, "", Counter, F(type_hit, {"type", "hit"}), F(type_miss, {"type", "miss"}))
```

I think `tiflash_storage_` is a better prefix

File: dbms/src/Server/Server.cpp [hunk 4]
```diff
@@ -1410,22 +1410,20 @@ int Server::main(const std::vector<std::string> & /*args*/)
...
+    ///   0 means cache is disabled.
     ///   We cannot support unlimited delta index cache in disaggregated mode for now,
     ///   because cache items will be never explicitly removed.
     if (global_context->getSharedContextDisagg()->isDisaggregatedComputeMode())
     {
-        size_t n = config().getUInt64("delta_index_cache_count", 2000);
+        constexpr auto delta_index_cache_ratio = 0.02;
+        size_t n
+            = config().getUInt64("delta_index_cache_size", server_info.memory_info.capacity * delta_index_cache_ratio);
```
Comment (Lloyd-Pottiger) [inline dbms/src/Server/Server.cpp:1423]: it will be better to have a backup when memory_capacity_of_host is not obtained.

File: dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.cpp [hunk 5]
```diff
@@ -12,18 +12,45 @@
...
+} // namespace CurrentMetrics
 
 namespace DB::DM::Remote
 {
 
-DeltaIndexPtr RNDeltaIndexCache::getDeltaIndex(const RNDeltaIndexCache::CacheKey & key)
+DeltaIndexPtr RNDeltaIndexCache::getDeltaIndex(const CacheKey & key)
+{
+    auto [value, miss]
+        = cache.getOrSet(key, [&key] { return std::make_shared<CacheValue>(std::make_shared<DeltaIndex>(key), 0); });
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.cpp:30]: should we require lock here?

**Review by Lloyd-Pottiger — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Review by breezewish — APPROVED** [review]
