### PR TITLE
executor: disable runtime filter on join key type mismatch

### LINKED ISSUE #10699: May miss rows when joining different key types with the Runtime Filter.
## Bug Report

For details, refer to https://github.com/pingcap/tidb/issues/65647

### PR DESCRIPTION
**Pull request by ChangRui-Ryan**
### What problem does this PR solve?

Issue Number: close #10699

Problem Summary:

### What is changed and how it works?

```commit-message

```

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Runtime filters are now conservatively disabled when join key types, signed/unsigned flags, or decimal precision/scale differ; an informational log records the reason and empty filter lists are used to avoid incorrect pruning and preserve correct join results.

* **Tests**
  * Added tests verifying runtime filters are disabled for various type/precision mismatch scenarios and that execution plans and results remain unchanged.

### CODE REVIEW

File: dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp [hunk 1]
```diff
@@ -158,8 +158,55 @@ PhysicalPlanNodePtr PhysicalJoin::build(
...
+            if (hasUnsignedFlag(lt) != hasUnsignedFlag(rt))
+                return false;
+        }
+        return true;
+    };
+
+    const bool enable_runtime_filter = is_join_key_field_type_compatible();
+    if (!enable_runtime_filter && !join.runtime_filter_list().empty())
+    {
+        LOG_INFO(
```
Comment (windtalker) [inline dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp]: use debug log?
