### PR TITLE
Fix bug introduced by #7644

### LINKED ISSUE #7677: Check query_set != nullptr failed: query set must not be null when register task
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

ch workload
sql raise error
### 2. What did you expect to see? (Required)
no error
### 3. What did you see instead (Required)
```
[2023/06/19 04:58:37.992 +08:00] [ERROR] [local_mpp_coordinator.go:372] ["mpp dispatch response meet error"] [error="DB::TiFlashException: MPP query is already aborted, aborted reason: From MPP<query:<query_ts:1687121917969790065, local_query_id:801, server_id:3970601, start_ts:442268888050171946>,task_id:7>: DB::Exception: Check query_set != nullptr failed: query set must not be null when register task"] [timestamp=442268888050171946] [task=15] [task-mpp-version=1] [error-mpp-version=0]
[2023/06/19 04:58:37.992 +08:00] [ERROR] [local_mpp_coordinator.go:372] ["mpp dispatch response meet error"] [error="DB::TiFlashException: MPP query is already aborted, aborted reason: From MPP<query:<query_ts:1687121917969790065, local_query_id:801, server_id:3970601, start_ts:442268888050171946>,task_id:7>: DB::Exception: Check query_set != nullptr failed: query set must not be null when register task"] [timestamp=442268888050171946] [task=13] [task-mpp-version=1] [error-mpp-version=0]
[2023/06/19 04:58:37.992 +08:00] [ERROR] [local_mpp_coordinator.go:372] ["mpp dispatch response meet error"] [error="DB::Exception: Check query_set != nullptr failed: query set must not be null when register task"] [timestamp=442268888050171946] [task=7] [task-mpp-version=1] [error-mpp-version=0]
[2023/06/19 04:58:37.992 +08:00] [ERROR] [local_mpp_coordinator.go:372] ["mpp dispatch response meet error"] [error="DB::TiFlashException: MPP query is already aborted, aborted reason: From MPP<query:<query_ts:1687121917969790065, local_query_id:801, server_id:3970601, start_ts:442268888050171946>,task_id:7>: DB::Exception: Check query_set != nullptr failed: query set must not be null when register task"] [timestamp=442268888050171946] [task=3] [task-mpp-version=1] [error-mpp-version=0]
[2023/06/19 04:58:37.997 +08:00] [INFO] [conn.go:1199] ["command dispatched failed"] [conn=8731443937518026761] [connInfo="id:8731443937518026761, addr:10.200.10.72:58384 status:10, collation:utf8mb4_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="\nselect\t s_name, count(*) as numwait\nfrom\t supplier, order_line l1, orders, stock, nation\nwhere\t ol_o_id = o_id\n  and ol_w_id = o_w_id\n  and ol_d_id = o_d_id\n  and ol_w_id = s_w_id\n  and ol_i_id = s_i_id\n  and mod((s_w_id * s_i_id),10000) = s_suppkey\n  and l1.ol_delivery_d > o_entry_d\n  and not exists (select *\n                  from\torder_line l2\n                  where  l2.ol_o_id = l1.ol_o_id\n                    and l2.ol_w_id = l1.ol_w_id\n                    and l2.ol_d_id = l1.ol_d_id\n                    and l2.ol_delivery_d > l1.ol_delivery_d)\n  and s_nationkey = n_nationkey\n  and n_name = 'CHINA'\ngroup by s_name\norder by numwait desc, s_name;\n"] [txn_mode=PESSIMISTIC] [timestamp=442268888050171946] [err="DB::TiFlashException: MPP query is already aborted, aborted reason: From MPP<query:<query_ts:1687121917969790065, local_query_id:801, server_id:3970601, start_ts:442268888050171946>,task_id:7>: DB::Exception: Check query_set != nullptr failed: query set must not be null when register task\ngithub.com/pingcap/tidb/executor/internal/mpp.(*localMppCoordinator).handleDispatchReq\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/internal/mpp/local_mpp_coordinator.go:373\ngithub.com/pingcap/tidb/executor/internal/mpp.(*localMppCoordinator).dispatchAll.func2\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/internal/mpp/local_mpp_coordinator.go:300\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"]
[root@tidb-1-0 ~]# grep "not be null" -A 10 -B 10 /tiup/deploy/tidb-4000/log/tidb.log
[2023/06/19 04:58:37.987 +08:00] [INFO] [local_mpp_coordinator.go:172] ["Dispatch mpp task"] [timestamp=442268888050171946] [ID=7] [QueryTs=1687121917969790065] [LocalQueryId=801] [ServerID=3970601] [address=tiflash-2-peer:3930] [plan="RightHashJoin{Recv(3, 4, )->Recv(5, 6, )}(tpcc.supplier.s_suppkey,Column#62)(tpcc.stock.s_w_id,tpcc.order_line.ol_w_id)(tpcc.stock.s_i_id,tpcc.order_line.ol_i_id)->Send(13, 14, )"] [mpp-version=1] [exchange-compression-mode=FAST]
[2023/06/19 04:58:37.987 +08:00] [INFO] [local_mpp_coordinator.go:172] ["Dispatch mpp task"] [timestamp=442268888050171946] [ID=8] [QueryTs=1687121917969790065] [LocalQueryId=801] [ServerID=3970601] [address=tiflash-1-peer:3930] [plan="RightHashJoin{Recv(3, 4, )->Recv(5, 6, )}(tpcc.supplier.s_suppkey,Column#62)(tpcc.stock.s_w_id,tpcc.order_line.ol_w_id)(tpcc.stock.s_i_id,tpcc.order_line.ol_i_id)->Send(13, 14, )"] [mpp-version=1] [exchange-compression-mode=FAST]
[2023/06/19 04:58:37.987 +08:00] [INFO] [local_mpp_coordinator.go:172] ["Dispatch mpp task"] [timestamp=442268888050171946] [ID=9] [QueryTs=1687121917969790065] [LocalQueryId=801] [ServerID=3970601] [address=tiflash-2-peer:3930] [plan="Table(orders)->Sel([not(isnull(tpcc.orders.o_entry_d))])->Send(13, 14, )"] [mpp-version=1] [exchange-compression-mode=FAST]
[2023/06/19 04:58:37.987 +08:00] [INFO] [local_mpp_coordinator.go:172] ["Dispatch mpp task"] [timestamp=442268888050171946] [ID=10] [QueryTs=1687121917969790065] [LocalQueryId=801] [ServerID=3970601] [address=tiflash-1-peer:3930] [plan="Table(orders)->Sel([not(isnull(tpcc.orders.o_entry_d))])->Send(13, 14, )"] [mpp-version=1] [exchange-compression-mode=FAST]
[2023/06/19 04:58:37.987 +08:00] [INFO] [local_mpp_coordinator.go:172] ["Dispatch mpp task"] [timestamp=442268888050171946] [ID=11] [QueryTs=1687121917969790065] [LocalQueryId=801] [ServerID=3970601] [address=tiflash-1-peer:3930] [plan="Table(order_line)->Send(13, 14, )"] [mpp-version=1] [exchange-compression-mode=FAST]
[2023/06/19 04:58:37.987 +08:00] [INFO] [local_mpp_coordinator.go:172] ["Dispatch mpp task"] [timestamp=442268888050171946] [ID=12] [QueryTs=1687121917969790065] [LocalQueryId=801] [ServerID=3970601] [address=tiflash-2-peer:3930] [plan="Table(order_line)->Send(13, 14, )"] [mpp-version=1] [exchange-compression-mode=FAST]
[2023/06/19 04:58:37.987 +08:00] [INFO] [local_mpp_coordinator.go:172] ["Dispatch mpp task"] [timestamp=442268888050171946] [ID=13] [QueryTs=1687121917969790065] [LocalQueryId=801] [ServerID=3970601] [address=tiflash-2-peer:3930] [plan="LeftHashJoin{LeftHashJoin{Recv(7, 8, )->Recv(9, 10, )}(tpcc.order_line.ol_o_id,tpcc.orders.o_id)(tpcc.order_line.ol_w_id,tpcc.orders.o_w_id)(tpcc.order_line.ol_d_id,tpcc.orders.o_d_id)->Projection->Recv(11, 12, )}(tpcc.order_line.ol_o_id,tpcc.order_line.ol_o_id)(tpcc.order_line.ol_w_id,tpcc.order_line.ol_w_id)(tpcc.order_line.ol_d_id,tpcc.order_line.ol_d_id)->HashAgg->Send(15, 16, )"] [mpp-version=1] [exchange-compression-mode=FAST]
[2023/06/19 04:58:37.987 +08:00] [INFO] [local_mpp_coordinator.go:172] ["Dispatch mpp task"] [timestamp=442268888050171946] [ID=14] [QueryTs=1687121917969790065] [LocalQueryId=801] [ServerID=3970601] [address=tiflash-1-peer:3930] [plan="LeftHashJoin{LeftHashJoin{Recv(7, 8, )->Recv(9, 10, )}(tpcc.order_line.ol_o_id,tpcc.orders.o_id)(tpcc.order_line.ol_w_id,tpcc.orders.o_w_id)(tpcc.order_line.ol_d_id,tpcc.orders.o_d_id)->Projection->Recv(11, 12, )}(tpcc.order_line.ol_o_id,tpcc.order_line.ol_o_id)(tpcc.order_line.ol_w_id,tpcc.order_line.ol_w_id)(tpcc.order_line.ol_d_id,tpcc.order_line.ol_d_id)->HashAgg->Send(15, 16, )"] [mpp-version=1] [exchange-compression-mode=FAST]
[2023/06/19 04:58:37.987 +08:00] [INFO] [local_mpp_coordinator.go:172] ["Dispatch mpp task"] [timestamp=442268888050171946] [ID=15] [QueryTs=1687121917969790065] [LocalQueryId=801] [ServerID=3970601] [address=tiflash-2-peer:3930] [plan="Recv(13, 14, )->HashAgg->Projection->Projection->Send(-1, )"] [mpp-version=1] [exchange-compression-mode=NONE]
[2023/06/19 04:58:37.987 +08:00] [INFO] [local_mpp_coordinator.go:172] ["Dispatch mpp task"] [timestamp=442268888050171946] [ID=16] [QueryTs=1687121917969790065] [LocalQueryId=801] [ServerID=3970601] [address=tiflash-1-peer:3930] [plan="Recv(13, 14, )->HashAgg->Projection->Projection->Send(-1, )"] [mpp-version=1] [exchange-compression-mode=NONE]
[2023/06/19 04:58:37.992 +08:00] [ERROR] [local_mpp_coordinator.go:372] ["mpp dispatch response meet error"] [error="DB::TiFlashException: MPP query is already aborted, aborted reason: From MPP<query:<query_ts:1687121917969790065, local_query_id:801, server_id:3970601, start_ts:442268888050171946>,task_id:7>: DB::Exception: Check query_set != nullptr failed: query set must not be null when register task"] [timestamp=442268888050171946] [task=15] [task-mpp-version=1] [error-mpp-version=0]
[2023/06/19 04:58:37.992 +08:00] [ERROR] [local_mpp_coordinator.go:372] ["mpp dispatch response meet error"] [error="DB::TiFlashException: MPP query is already aborted, aborted reason: From MPP<query:<query_ts:1687121917969790065, local_query_id:801, server_id:3970601, start_ts:442268888050171946>,task_id:7>: DB::Exception: Check query_set != nullptr failed: query set must not be null when register task"] [timestamp=442268888050171946] [task=13] [task-mpp-version=1] [error-mpp-version=0]
[2023/06/19 04:58:37.992 +08:00] [ERROR] [local_mpp_coordinator.go:372] ["mpp dispatch response meet error"] [error="DB::Exception: Check query_set != nullptr failed: query set must not be null when register task"] [timestamp=442268888050171946] [task=7] [task-mpp-version=1] [error-mpp-version=0]
[2023/06/19 04:58:37.992 +08:00] [WARN] [mpp.go:142] ["mpp dispatch meet io error"] [error="rpc error: code = Canceled desc = context canceled"] [timestamp=442268888050171946] [task=9] [mpp-version=1]
[2023/06/19 04:58:37.992 +08:00] [ERROR] [local_mpp_coordinator.go:362] ["mpp dispatch meet error"] [error="rpc error: code = Canceled desc = context canceled"] [timestamp=442268888050171946] [task=9] [mpp-version=1]
[2023/06/19 04:58:37.992 +08:00] [WARN] [mpp.go:142] ["mpp dispatch meet io error"] [error="rpc error: code = Canceled desc = context canceled"] [timestamp=442268888050171946] [task=11] [mpp-version=1]
[2023/06/19 04:58:37.992 +08:00] [ERROR] [local_mpp_coordinator.go:362] ["mpp dispatch meet error"] [error="rpc error: code = Canceled desc = context canceled"] [timestamp=442268888050171946] [task=11] [mpp-version=1]
[2023/06/19 04:58:37.992 +08:00] [ERROR] [local_mpp_coordinator.go:372] ["mpp dispatch response meet error"] [error="DB::TiFlashException: MPP query is already aborted, aborted reason: From MPP<query:<query_ts:1687121917969790065, local_query_id:801, server_id:3970601, start_ts:442268888050171946>,task_id:7>: DB::Exception: Check query_set != nullptr failed: query set must not be null when register task"] [timestamp=442268888050171946] [task=3] [task-mpp-version=1] [error-mpp-version=0]
[2023/06/19 04:58:37.992 +08:00] [WARN] [mpp.go:142] ["mpp dispatch meet io error"] [error="rpc error: code = Canceled desc = context canceled"] [timestamp=442268888050171946] [task=12] [mpp-version=1]
[2023/06/19 04:58:37.992 +08:00] [ERROR] [local_mpp_coordinator.go:362] ["mpp dispatch meet error"] [error="rpc error: code = Canceled desc = context canceled"] [timestamp=442268888050171946] [task=12] [mpp-version=1]
[2023/06/19 04:58:37.992 +08:00] [WARN] [mpp.go:261] ["establish mpp connection meet error and cannot retry"] [error="rpc error: code = Canceled desc = context canceled"] [timestamp=442268888050171946] [task=16] [mpp-version=1]
[2023/06/19 04:58:37.993 +08:00] [WARN] [mpp.go:142] ["mpp dispatch meet io error"] [error="rpc error: code = Canceled desc = context canceled"] [timestamp=442268888050171946] [task=6] [mpp-version=1]
[2023/06/19 04:58:37.993 +08:00] [ERROR] [local_mpp_coordinator.go:362] ["mpp dispatch meet error"] [error="rpc error: code = Canceled desc = context canceled"] [timestamp=442268888050171946] [task=6] [mpp-version=1]
[2023/06/19 04:58:37.997 +08:00] [INFO] [conn.go:1199] ["command dispatched failed"] [conn=8731443937518026761] [connInfo="id:8731443937518026761, addr:10.200.10.72:58384 status:10, collation:utf8mb4_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="\nselect\t s_name, count(*) as numwait\nfrom\t supplier, order_line l1, orders, stock, nation\nwhere\t ol_o_id = o_id\n  and ol_w_id = o_w_id\n  and ol_d_id = o_d_id\n  and ol_w_id = s_w_id\n  and ol_i_id = s_i_id\n  and mod((s_w_id * s_i_id),10000) = s_suppkey\n  and l1.ol_delivery_d > o_entry_d\n  and not exists (select *\n                  from\torder_line l2\n                  where  l2.ol_o_id = l1.ol_o_id\n                    and l2.ol_w_id = l1.ol_w_id\n                    and l2.ol_d_id = l1.ol_d_id\n                    and l2.ol_delivery_d > l1.ol_delivery_d)\n  and s_nationkey = n_nationkey\n  and n_name = 'CHINA'\ngroup by s_name\norder by numwait desc, s_name;\n"] [txn_mode=PESSIMISTIC] [timestamp=442268888050171946] [err="DB::TiFlashException: MPP query is already aborted, aborted reason: From MPP<query:<query_ts:1687121917969790065, local_query_id:801, server_id:3970601, start_ts:442268888050171946>,task_id:7>: DB::Exception: Check query_set != nullptr failed: query set must not be null when register task\ngithub.com/pingcap/tidb/executor/internal/mpp.(*localMppCoordinator).handleDispatchReq\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/internal/mpp/local_mpp_coordinator.go:373\ngithub.com/pingcap/tidb/executor/internal/mpp.(*localMppCoordinator).dispatchAll.func2\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/internal/mpp/local_mpp_coordinator.go:300\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"]
```
### 4. What is your TiFlash version? (Required)
master

### LINKED ISSUE #7678: TiFlash crash in failpoint test
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2023/06/19 06:54:16.425 +08:00] [ERROR] [BaseDaemon.cpp:376] [########################################] [source=BaseDaemon] [thread_id=1585]
[2023/06/19 06:54:16.425 +08:00] [ERROR] [BaseDaemon.cpp:377] ["(from thread 263) Received signal Segmentation fault(11)."] [source=BaseDaemon] [thread_id=1585]
[2023/06/19 06:54:16.425 +08:00] [ERROR] [BaseDaemon.cpp:405] ["Address: NULL pointer."] [source=BaseDaemon] [thread_id=1585]
[2023/06/19 06:54:16.426 +08:00] [ERROR] [BaseDaemon.cpp:413] ["Access: read."] [source=BaseDaemon] [thread_id=1585]
[2023/06/19 06:54:16.426 +08:00] [ERROR] [BaseDaemon.cpp:425] ["Unknown si_code."] [source=BaseDaemon] [thread_id=1585]
[2023/06/19 06:54:16.438 +08:00] [WARN] [ExchangeReceiver.cpp:1004] ["connection end. meet error: true, err msg: Exchange receiver meet error : From MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:14>: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel14+15 which is already closed, , e.what() = DB::Exception,, current alive connections: 2"] [source="MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:16> ExchangeReceiver_69 tunnel9+16"] [thread_id=1209]
[2023/06/19 06:54:16.438 +08:00] [WARN] [ExchangeReceiver.cpp:1004] ["connection end. meet error: true, err msg: Exchange receiver meet error : From MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:14>: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel14+15 which is already closed, , e.what() = DB::Exception,, current alive connections: 2"] [source="MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:16> ExchangeReceiver_75 tunnel14+16"] [thread_id=240]
[2023/06/19 06:54:16.451 +08:00] [WARN] [ExchangeReceiver.cpp:1023] ["Finish receiver channels, meet error: true, error message: Exchange receiver meet error : From MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:14>: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel14+15 which is already closed, , e.what() = DB::Exception,"] [source="MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:16> ExchangeReceiver_69"] [thread_id=1209]
[2023/06/19 06:54:16.453 +08:00] [WARN] [ExchangeReceiver.cpp:1023] ["Finish receiver channels, meet error: true, error message: Exchange receiver meet error : From MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:14>: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel14+15 which is already closed, , e.what() = DB::Exception,"] [source="MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:16> ExchangeReceiver_75"] [thread_id=240]
[2023/06/19 06:54:16.491 +08:00] [WARN] [ExchangeReceiver.cpp:1004] ["connection end. meet error: true, err msg: Exchange receiver meet error : From MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:14>: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel14+15 which is already closed, , e.what() = DB::Exception,, current alive connections: 2"] [source="MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:19> ExchangeReceiver_139 tunnel15+19"] [thread_id=941]
[2023/06/19 06:54:16.492 +08:00] [WARN] [ExchangeReceiver.cpp:1023] ["Finish receiver channels, meet error: true, error message: Exchange receiver meet error : From MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:14>: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel14+15 which is already closed, , e.what() = DB::Exception,"] [source="MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:19> ExchangeReceiver_139"] [thread_id=941]
[2023/06/19 06:54:16.497 +08:00] [WARN] [TiRemoteBlockInputStream.h:74] ["remote reader meets error: Receiver state: ERROR, error message: Exchange receiver meet error : From MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:14>: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel14+15 which is already closed, , e.what() = DB::Exception,"] [source="TiRemote(ExchangeReceiver) MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:19> ExchangeReceiver ExchangeReceiver_139 ExchangeReceiver_139"] [thread_id=285]
[2023/06/19 06:54:16.497 +08:00] [WARN] [TiRemoteBlockInputStream.h:74] ["remote reader meets error: Receiver state: ERROR, error message: Exchange receiver meet error : From MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:14>: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel14+15 which is already closed, , e.what() = DB::Exception,"] [source="TiRemote(ExchangeReceiver) MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:19> ExchangeReceiver ExchangeReceiver_139 ExchangeReceiver_139"] [thread_id=324]
[2023/06/19 06:54:16.498 +08:00] [WARN] [TiRemoteBlockInputStream.h:74] ["remote reader meets error: Receiver state: ERROR, error message: Exchange receiver meet error : From MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:14>: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel14+15 which is already closed, , e.what() = DB::Exception,"] [source="TiRemote(ExchangeReceiver) MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:19> ExchangeReceiver ExchangeReceiver_139 ExchangeReceiver_139"] [thread_id=745]
[2023/06/19 06:54:16.498 +08:00] [WARN] [TiRemoteBlockInputStream.h:74] ["remote reader meets error: Receiver state: ERROR, error message: Exchange receiver meet error : From MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:14>: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel14+15 which is already closed, , e.what() = DB::Exception,"] [source="TiRemote(ExchangeReceiver) MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:19> ExchangeReceiver ExchangeReceiver_139 ExchangeReceiver_139"] [thread_id=330]
[2023/06/19 06:54:16.498 +08:00] [WARN] [TiRemoteBlockInputStream.h:74] ["remote reader meets error: Receiver state: ERROR, error message: Exchange receiver meet error : From MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:14>: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel14+15 which is already closed, , e.what() = DB::Exception,"] [source="TiRemote(ExchangeReceiver) MPP<query:<query_ts:1687128853723203110, local_query_id:9879, server_id:1736808, start_ts:442270706204147713>,task_id:19> ExchangeReceiver ExchangeReceiver_139 ExchangeReceiver_139"] [thread_id=343]
[2023/06/19 06:54:16.499 +08:00] [ERROR] [BaseDaemon.cpp:569] ["\n       0xad20b5d\tfaultSignalHandler(int, siginfo_t*, void*) [tiflash+181537629]\n                \tlibs/libdaemon/src/BaseDaemon.cpp:220\n  0x7f65e1cb2d90\t<unknown symbol> [libc.so.6+347536]\n       0x42b0989\tlong std::__1::__cxx_atomic_fetch_sub<long>(std::__1::__cxx_atomic_base_impl<long>*, long, std::__1::memory_order) [tiflash+69929353]\n                \t/usr/local/bin/../include/c++/v1/atomic:1082\n       0x42b06f3\tstd::__1::__atomic_base<long, true>::fetch_sub(long, std::__1::memory_order) [tiflash+69928691]\n                \t/usr/local/bin/../include/c++/v1/atomic:1736\n       0x42be7a7\tMemoryTracker::free(long) [tiflash+69986215]\n                \tdbms/src/Common/MemoryTracker.cpp:182\n       0x42be811\tMemoryTracker::free(long) [tiflash+69986321]\n                \tdbms/src/Common/MemoryTracker.cpp:197\n       0xbd6dfc9\tDB::MemTrackerWrapper::free(unsigned long) [tiflash+198631369]\n                \tdbms/src/Flash/Mpp/TrackedMppDataPacket.h:81\n       0xbd6df29\tDB::MemTrackerWrapper::freeAll() [tiflash+198631209]\n                \tdbms/src/Flash/Mpp/TrackedMppDataPacket.h:104\n       0x41ddfc5\tDB::MemTrackerWrapper::~MemTrackerWrapper() [tiflash+69066693]\n                \tdbms/src/Flash/Mpp/TrackedMppDataPacket.h:99\n       0x41e489e\tDB::TrackedMppDataPacket::~TrackedMppDataPacket() [tiflash+69093534]\n                \tdbms/src/Flash/Mpp/TrackedMppDataPacket.h:111\n       0x41e485b\tvoid std::__1::destroy_at<DB::TrackedMppDataPacket>(DB::TrackedMppDataPacket*) [tiflash+69093467]\n                \t/usr/local/bin/../include/c++/v1/__memory/construct_at.h:50\n       0x41e47f9\tvoid std::__1::allocator_traits<std::__1::allocator<DB::TrackedMppDataPacket> >::destroy<DB::TrackedMppDataPacket, void, void>(std::__1::allocator<DB::TrackedMppDataPacket>&, DB::TrackedMppDataPacket*) [tiflash+69093369]\n                \t/usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:317\n       0x41e471d\tstd::__1::__shared_ptr_emplace<DB::TrackedMppDataPacket, std::__1::allocator<DB::TrackedMppDataPacket> >::__on_zero_shared() [tiflash+69093149]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:313\n       0x42adf3c\tstd::__1::__shared_count::__release_shared() [tiflash+69918524]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177\n       0x42adef6\tstd::__1::__shared_weak_count::__release_shared() [tiflash+69918454]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219\n       0xbd6a2b0\tstd::__1::shared_ptr<DB::TrackedMppDataPacket>::~shared_ptr() [tiflash+198615728]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959\n       0xbfe8d4e\tDB::ReceivedMessage::~ReceivedMessage() [tiflash+201231694]\n                \tdbms/src/Flash/Mpp/ReceivedMessage.h:26\n       0xbfe8cfb\tvoid std::__1::destroy_at<DB::ReceivedMessage>(DB::ReceivedMessage*) [tiflash+201231611]\n                \t/usr/local/bin/../include/c++/v1/__memory/construct_at.h:50\n       0xbfe8c99\tvoid std::__1::allocator_traits<std::__1::allocator<DB::ReceivedMessage> >::destroy<DB::ReceivedMessage, void, void>(std::__1::allocator<DB::ReceivedMessage>&, DB::ReceivedMessage*) [tiflash+201231513]\n                \t/usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:317\n       0xbfe8a7d\tstd::__1::__shared_ptr_emplace<DB::ReceivedMessage, std::__1::allocator<DB::ReceivedMessage> >::__on_zero_shared() [tiflash+201230973]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:313\n       0x42adf3c\tstd::__1::__shared_count::__release_shared() [tiflash+69918524]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177\n       0x42adef6\tstd::__1::__shared_weak_count::__release_shared() [tiflash+69918454]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219\n       0xbe99c60\tstd::__1::shared_ptr<DB::ReceivedMessage>::~shared_ptr() [tiflash+199859296]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959\n       0xbfe0c95\tDB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage::~DataWithMemoryUsage() [tiflash+201198741]\n                \tdbms/src/Common/LooseBoundedMPMCQueue.h:258\n       0xbfe0c6b\tvoid std::__1::destroy_at<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage>(DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage*) [tiflash+201198699]\n                \t/usr/local/bin/../include/c++/v1/__memory/construct_at.h:50\n       0xbfe0b39\tvoid std::__1::allocator_traits<std::__1::allocator<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage> >::destroy<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage, void, void>(std::__1::allocator<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage>&, DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage*) [tiflash+201198393]\n                \t/usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:317\n       0xbfe09b4\tstd::__1::__deque_base<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage, std::__1::allocator<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage> >::clear() [tiflash+201198004]\n                \t/usr/local/bin/../include/c++/v1/deque:1253\n       0xbfe08d9\tstd::__1::__deque_base<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage, std::__1::allocator<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage> >::~__deque_base() [tiflash+201197785]\n                \t/usr/local/bin/../include/c++/v1/deque:1190\n       0xbfdf215\tstd::__1::deque<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage, std::__1::allocator<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::DataWithMemoryUsage> >::~deque() [tiflash+201191957]\n                \t/usr/local/bin/../include/c++/v1/deque:1272\n       0xbfe0e62\tDB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >::~LooseBoundedMPMCQueue() [tiflash+201199202]\n                \tdbms/src/Common/LooseBoundedMPMCQueue.h:31\n       0xbfe0deb\tvoid std::__1::destroy_at<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> > >(DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >*) [tiflash+201199083]\n                \t/usr/local/bin/../include/c++/v1/__memory/construct_at.h:50\n       0xbfe0d89\tvoid std::__1::allocator_traits<std::__1::allocator<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> > > >::destroy<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >, void, void>(std::__1::allocator<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> > >&, DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >*) [tiflash+201198985]\n                \t/usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:317\n       0xbfdda4d\tstd::__1::__shared_ptr_emplace<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> >, std::__1::allocator<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> > > >::__on_zero_shared() [tiflash+201185869]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:313\n       0x42adf3c\tstd::__1::__shared_count::__release_shared() [tiflash+69918524]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177\n       0x42adef6\tstd::__1::__shared_weak_count::__release_shared() [tiflash+69918454]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219\n       0x4200290\tstd::__1::shared_ptr<DB::LooseBoundedMPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> > >::~shared_ptr() [tiflash+69206672]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959\n       0x4200222\tDB::ReceivedMessageQueue::~ReceivedMessageQueue() [tiflash+69206562]\n                \tdbms/src/Flash/Mpp/ReceivedMessageQueue.h:37\n       0x42001d3\tstd::__1::default_delete<DB::ReceivedMessageQueue>::operator()(DB::ReceivedMessageQueue*) const [tiflash+69206483]\n                \t/usr/local/bin/../include/c++/v1/__memory/unique_ptr.h:57\n       0x4200160\tstd::__1::unique_ptr<DB::ReceivedMessageQueue, std::__1::default_delete<DB::ReceivedMessageQueue> >::reset(DB::ReceivedMessageQueue*) [tiflash+69206368]\n                \t/usr/local/bin/../include/c++/v1/__memory/unique_ptr.h:318\n       0x41dffc7\tstd::__1::unique_ptr<DB::ReceivedMessageQueue, std::__1::default_delete<DB::ReceivedMessageQueue> >::~unique_ptr() [tiflash+69074887]\n                \t/usr/local/bin/../include/c++/v1/__memory/unique_ptr.h:272\n       0x42017f1\tDB::ExchangeReceiverBase<DB::GRPCReceiverContext>::~ExchangeReceiverBase() [tiflash+69212145]\n                \tdbms/src/Flash/Mpp/ExchangeReceiver.cpp:390\n       0xb1384c5\tDB::ExchangeReceiver::~ExchangeReceiver() [tiflash+185828549]\n                \tdbms/src/Flash/Mpp/ExchangeReceiver.h:251\n       0xb13849b\tvoid std::__1::destroy_at<DB::ExchangeReceiver>(DB::ExchangeReceiver*) [tiflash+185828507]\n                \t/usr/local/bin/../include/c++/v1/__memory/construct_at.h:50\n       0xb138439\tvoid std::__1::allocator_traits<std::__1::allocator<DB::ExchangeReceiver> >::destroy<DB::ExchangeReceiver, void, void>(std::__1::allocator<DB::ExchangeReceiver>&, DB::ExchangeReceiver*) [tiflash+185828409]\n                \t/usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:317\n       0xb1376bd\tstd::__1::__shared_ptr_emplace<DB::ExchangeReceiver, std::__1::allocator<DB::ExchangeReceiver> >::__on_zero_shared() [tiflash+185824957]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:313\n       0x42adf3c\tstd::__1::__shared_count::__release_shared() [tiflash+69918524]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177\n       0x42adef6\tstd::__1::__shared_weak_count::__release_shared() [tiflash+69918454]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219\n       0xb129ae0\tstd::__1::shared_ptr<DB::ExchangeReceiver>::~shared_ptr() [tiflash+185768672]\n                \t/usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959\n       0xb139577\tDB::TiRemoteBlockInputStream<DB::ExchangeReceiver>::~TiRemoteBlockInputStream() [tiflash+185832823]\n                \tdbms/src/DataStreams/TiRemoteBlockInputStream.h:38\n       0xb13afdb\tvoid std::__1::destroy_at<DB::TiRemoteBlockInputStream<DB::ExchangeReceiver> >(DB::TiRemoteBlockInputStream<DB::ExchangeReceiver>*) [tiflash+185839579]\n                \t/usr/local/bin/../include/c++/v1/__memory/construct_at.h:50"] [source=BaseDaemon] [thread_id=1585]
```
### 4. What is your TiFlash version? (Required)
[2023/06/19 03:16:24.043 +08:00] [INFO] [client.go:514] ["Cluster version information"] [type=tikv] [version=7.2.0-alpha] [git_hash=0daa38c454c8d518a62f372f5fe679c1e858871e]
[2023/06/19 03:16:24.043 +08:00] [INFO] [client.go:514] ["Cluster version information"] [type=tidb] [version=7.2.0-alpha] [git_hash=5bd56cb5d5597e106a511007d42c93ee4fc20f50]
[2023/06/19 03:16:24.043 +08:00] [INFO] [client.go:514] ["Cluster version information"] [type=pd] [version=7.2.0-alpha] [git_hash=1c5ca17da988a71e7293a8ec2de3d5b13d841fa2]
[2023/06/19 03:16:24.043 +08:00] [INFO] [client.go:514] ["Cluster version information"] [type=tiflash] [version=7.2.0-alpha] [git_hash=7aafea8835af8f8c77f48fb197fec660eb9f850d]

### LINKED ISSUE #7687: Query with `Apply` executor may throw `query set must not be null when register task` error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
For query that contains `Apply` executor, and if the apply need to run mpp query, the query may throw error, a typical error is 
```
[2023/06/21 07:02:33.165 +00:00] [ERROR] [local_mpp_coordinator.go:372] ["mpp dispatch response meet error"] [error="DB::Exception: Check query_set != nullptr failed: query set must not be null when register task"] [timestamp=442323682909224968] [task=796] [task-mpp-version=1] [error-mpp-version=0]
```
Introduced by #7644

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #7687, close #7678, close #7677

Problem Summary:

In #7644, it introduces query level process_list_entry for mpp query, that is to say, for a mpp query, all the mpp tasks share the same process_list_entry and memory_tracker. And the `process_list_entry` is saved in `MPPQueryTaskSet` in `MPPTaskManager`.
It works fine for normal queries, but for queries that may contains multiple independent sub-mpp-queries, there is a potential data race.
Consider a query with non-correlated subquery: `select * from t where id > (select max(a) from s)`, this query contains two independent sub queries:
subquery_1: `select max(a) from s`
subquery_2: `select * from t where id > result_of_subquery_1`
subquery_1 is executed first, then a possible data race will be
| time   | description |
|--------|------------|
| t1 | subquery 1's tasks are dispatched and executing |
| t2 | subquery 2's tasks are dispatched |
| t3 | some of subquery 2's tasks call `initProcessListEntry`, and get the `process_list_entry/memory_tracker` saved in `MPPQueryTaskSet` |
| t4 | subquery 1 is finished, all its tasks called `unregisterTask`, and MPPTaskManager found that there is no active mpp tasks, so the `MPPQueryTaskSet` is also removed |
| t5 | the rest of the subquery 2's tasks call `initProcessListEntry`, it will create a new `MPPQueryTaskSet` and create new `process_list_entry/memory_tracker`|

As you can see, after t5, some of subquery 2's task still holds `process_list_entry/memory_tracker` that was generated for subquery 1.

### What is changed and how it works?
The root cause of these problem is after `initProcessListEntry`, `MPPQueryTaskSet` can still be released due to no active mpp tasks.
The pr refine the flow of `registerTask`, now for a mpp task, it will interact with MPPTaskManager as follows:
1. register task: this will register the task meta to MPPTaskManager, and get `process_list_entry/memory_tracker`, unlike the previous version of `registerTask`, in the new implementation, a task is not visible after `registerTask`.
2. make task public: this will make the task visible to other, so `establishMPPConnection` can connect to the mpp tunnel
3. unregister task: this will remove the task from MPPTaskManager

`MPPQueryTaskSet` can only be released if all the registered mpp tasks are unregistered.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
   Run random failpoint manually
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/Mpp/MPPTaskManager.h [hunk 1]
```diff
@@ -54,6 +53,35 @@ struct MPPQueryTaskSet
         return state == Normal || state == Aborted;
     }
     ~MPPQueryTaskSet();
+    MPPTask * findMPPTask(const MPPTaskId & task_id) const;
+    bool isTaskRegistered(const MPPTaskId & task_id) const
+    {
+        return task_map.find(task_id) != task_map.end();
+    }
+    void registerTask(const MPPTaskId & task_id)
```
Comment (yibin87) [inline dbms/src/Flash/Mpp/MPPTaskManager.h:61]: It will be great if we don't need to maintain three status for MPPTask: unregistered, registered, visible.

File: dbms/src/Flash/tests/gtest_compute_server.cpp [hunk 2]
```diff
@@ -22,7 +22,9 @@ namespace DB
 namespace FailPoints
 {
 extern const char exception_before_mpp_register_non_root_mpp_task[];
+extern const char exception_before_mpp_make_non_root_mpp_task_public[];
```
Comment (SeaRise) [inline dbms/src/Flash/tests/gtest_compute_server.cpp:25]: Looks like a ut can be added, send two mppquery with the same query_id

**Review by SeaRise — COMMENTED** [review]
If two different mpp queries share a query set, if one of the queries has a limit, will the other query be canceled unexpectedly?

File: dbms/src/Flash/Mpp/MPPTaskManager.h (hunk 1 above)
Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTaskManager.h:61]: There is actually two status for MPPTask, visible or not visible, register is just a internal state and a task can be unregistered mutiple times, so basically no status need to be maintained for register/unregister

**Comment by windtalker** [comment]
> her query be cancel

This could be a problems, but it is not related to this pr, I think this problem need to be solved by mpp gather level's cancel.

File: dbms/src/Flash/tests/gtest_compute_server.cpp (hunk 2 above)
Comment (windtalker) [reply dbms/src/Flash/tests/gtest_compute_server.cpp:25]: Not very easy since the task id is always start from 1, so if just send to mpp query with the same query id, it could meet task registered error.

Comment (SeaRise) [reply dbms/src/Flash/tests/gtest_compute_server.cpp:25]: ok

**Comment by SeaRise** [comment]
> > her query be cancel
> 
> This could be a problems, but it is not related to this pr, I think this problem need to be solved by mpp gather level's cancel.

ok

File: dbms/src/Common/FailPoint.cpp [hunk 3]
```diff
@@ -39,12 +39,14 @@ namespace DB
     M(exception_before_dmfile_remove_from_disk)                   \
     M(force_triggle_background_merge_delta)                       \
     M(force_triggle_foreground_flush)                             \
+    M(exception_before_mpp_make_non_root_mpp_task_public)         \
```
Comment (SeaRise) [inline dbms/src/Common/FailPoint.cpp:42]: registered and visible make me a little confused..
Or use registered and active?

**Review by SeaRise — COMMENTED** [review]
Others LGTM

File: dbms/src/Flash/Mpp/MPPTaskManager.h (hunk 1 above)
Comment (yibin87) [reply dbms/src/Flash/Mpp/MPPTaskManager.h:61]: Yeah, I mean we can try avoid the internal "registered while not visible" state.

Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTaskManager.h:61]: OK, I think I can try to refine it later.

Comment (yibin87) [reply dbms/src/Flash/Mpp/MPPTaskManager.h:61]: all right~

File: dbms/src/Common/FailPoint.cpp (hunk 3 above)
Comment (windtalker) [reply dbms/src/Common/FailPoint.cpp]: Done

File: tests/fullstack-test/mpp/mpp_fail.test [hunk 4]
```diff
@@ -67,12 +67,22 @@ mysql> use test; set @@tidb_isolation_read_engines='tiflash'; set @@tidb_allow_m
 {#REGEXP}.*Fail point FailPoints::exception_before_mpp_register_non_root_mpp_task is triggered.*
 => DBGInvoke __disable_fail_point(exception_before_mpp_register_non_root_mpp_task)
 
+=> DBGInvoke __enable_fail_point(exception_before_mpp_make_non_root_mpp_task_public)
```
[the remark this answers is not in the document]
Comment (windtalker) [reply tests/fullstack-test/mpp/mpp_fail.test]: Ok, add an apply test.

**Review by SeaRise — APPROVED** [review]
lgtm
