### PR TITLE
*: fix lead_lag test build fail.

### LINKED ISSUE #5775: Build fail on mac m1 in gtest_lead_lag.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: close #5775 

Problem Summary:  

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by SeaRise — APPROVED** [review]

**Review by SeaRise — APPROVED** [review]
LGTM

File: dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp [hunk 1]
```diff
@@ -36,10 +36,13 @@ class LeadLag : public DB::tests::ExecutorTest
     void executeWithConcurrencyAndBlockSize(const std::shared_ptr<tipb::DAGRequest> & request, const ColumnsWithTypeAndName & expect_columns)
     {
         WRAP_FOR_DIS_ENABLE_PLANNER_BEGIN
-        std::vector<size_t> block_sizes{1, 2, 3, DEFAULT_BLOCK_SIZE};
+        auto to_field = [](size_t block_size) {
```
Comment (Lloyd-Pottiger) [inline dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp:39]: seems ugly……

Comment (ywqzzy) [reply dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp:39]: > seems ugly……

leave it as todo, since we will implement a new wf test utils.

File: dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp [hunk 2]
```diff
@@ -36,10 +36,13 @@ class LeadLag : public DB::tests::ExecutorTest
...
+            return Field(static_cast<UInt64>(block_size));
+        };
+        std::vector<size_t> block_sizes{1, 2, 3, 4, DEFAULT_BLOCK_SIZE};
         for (auto block_size : block_sizes)
         {
-            context.context.setSetting("max_block_size", block_size);
+            context.context.setSetting("max_block_size", to_field(block_size));
```
Comment (gengliqi) [inline dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp:45]: Is this better?
```suggestion
            context.context.setSetting("max_block_size", Field(static_cast<UInt64>(block_size)));
```

File: dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp (hunk 1 above)
Comment (ywqzzy) [reply dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp]: > > seems ugly……
> 
> leave it as todo, since we will implement a new wf test utils.

Ops, I thought you were comment on std::vector<size_t> block_sizes{1, 2, 3, DEFAULT_BLOCK_SIZE};.

I have fixed it.

**Review by gengliqi — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]
