### PR TITLE
fix network error handling of LocalAdmissionController

### LINKED ISSUE #8074: TiFlash crash under debug mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=OFF
./dbms/src/Server/tiflash server --config-file ../tests/docker/config/tics_dt.toml
```

### 2. What did you expect to see? (Required)

No error happens. Specifically, no error happens when running `tests/delta-merge-tests`

### 3. What did you see instead (Required)

```
[2023/09/11 18:00:27.097 +08:00] [INFO] [Server.cpp:1801] ["Start to wait for terminal signal"] [thread_id=1]
[2023/09/11 18:00:28.570 +08:00] [ERROR] [BaseDaemon.cpp:361] ["(from thread 78) Terminate called after throwing an instance of pingcap::Exception\nCode: 21, e.displayText() = Exception: not implemented, e.what() = Exception\nStack trace:\n\n\n  0x5608e06e628e\tStackTrace::StackTrace() [tiflash+69567118]\n                \tdbms/src/Common/StackTrace.cpp:23\n  0x5608e87e648c\tterminate_handler() [tiflash+204833932]\n                \tlibs/libdaemon/src/BaseDaemon.cpp:628\n  0x7fc807dc2303\tstd::__terminate(void (*)()) [libc++abi.so.1+230147]\n  0x7fc807dc22b8\tstd::terminate() [libc++abi.so.1+230072]\n  0x5608eab6a663\tDB::LocalAdmissionController::startBackgroudJob() [tiflash+242075235]\n                \tdbms/src/Flash/ResourceControl/LocalAdmissionController.cpp:62\n  0x5608e07eb028\tDB::LocalAdmissionController::LocalAdmissionController(pingcap::kv::Cluster*, std::__1::shared_ptr<DB::Etcd::Client>)::'lambda'()::operator()() const [tiflash+70635560]\n                \tdbms/src/Flash/ResourceControl/LocalAdmissionController.h:376\n  0x5608e07eafe5\tdecltype(std::declval<DB::LocalAdmissionControlle"] [source=BaseDaemon] [thread_id=222]
[2023/09/11 18:00:28.570 +08:00] [ERROR] [BaseDaemon.cpp:370] [########################################] [source=BaseDaemon] [thread_id=222]
[2023/09/11 18:00:28.570 +08:00] [ERROR] [BaseDaemon.cpp:371] ["(from thread 78) Received signal Aborted(6)."] [source=BaseDaemon] [thread_id=222]
```

### 4. What is your TiFlash version? (Required)
master

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #8074

Problem Summary: 
two problems:
1. Grpc needs new a client context for each new reader/writer, otherwise may crash.
2. Network between GAC and LAC may got network error(like timeout). Need to handle it more gracefully, otherwise tiflash will crash.

two enhancements:
1. Delete `handleBackgroundError()`, because it's just a dummy wrap of `LOG_ERROR`
2. Add lock when call `refill_token_callback` to avoid RCQ been destroied when calling `refill_token_callback`

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. start cluster with tiflash
3. continuously kill pd and check tiflash should not crash
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/ResourceControl/LocalAdmissionController.h [hunk 1]
```diff
@@ -574,7 +582,7 @@ class LocalAdmissionController final : private boost::noncopyable
     ::pingcap::kv::Cluster * cluster = nullptr;
     uint64_t unique_client_id = 0;
     Etcd::ClientPtr etcd_client = nullptr;
-    grpc::ClientContext watch_gac_grpc_context;
+    std::shared_ptr<grpc::ClientContext> watch_gac_grpc_context = nullptr;
```
Comment (windtalker) [inline dbms/src/Flash/ResourceControl/LocalAdmissionController.h:585]: unique_ptr is enough ?

File: dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp [hunk 2]
```diff
@@ -95,14 +105,18 @@ void LocalAdmissionController::startBackgroudJob()
             else
                 fetchTokensForLowTokenResourceGroups();
 
-            if (local_refill_token_callback)
-                local_refill_token_callback();
+            {
+                // Need lock here to avoid RCQ has already been destroied.
+                std::lock_guard lock(mu);
+                if (refill_token_callback)
+                    refill_token_callback();
```
Comment (SeaRise) [inline dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp:112]: Why does this happen? Hasn't unregisterCallback been called before RCQ destroied?

Comment (guo-shaoge) [reply dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp:112]: The original implement use `local_refill_token_callback`, so this can happen:
1. local_refill_token_callback copied from `LAC::refill_token_callback`
2. LAC::unregisterRefillTokenCallback is called
3. RCQ is destroied
4. local_refill_token_callback is still called

Comment (SeaRise) [reply dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp:112]: ok

**Review by windtalker — APPROVED** [review]
LGTM

File: dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp [hunk 3]
```diff
@@ -363,22 +386,27 @@ void LocalAdmissionController::watchGAC()
...
+            // Create new grpc_context for each reader/writer.
+            watch_gac_grpc_context = std::make_unique<grpc::ClientContext>();
+        }
     }
 }
 
 void LocalAdmissionController::doWatch()
 {
-    auto stream = etcd_client->watch(&watch_gac_grpc_context);
+    auto stream = etcd_client->watch(watch_gac_grpc_context.get());
```
Comment (SeaRise) [inline dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp:402]: Looks like a lock is needed here
```
grpc::ClientContext * grpc_ctx;
{
    std::lock_guard lock(mu);
    grpc_ctx = watch_gac_grpc_context.get();
}
RUNTIME_ASSERT(grpc_ctx != nullptr);
```

Comment (SeaRise) [reply dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp:402]: Or using `Common/PtrHolder`

Comment (guo-shaoge) [reply dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp:402]: no need to lock here?
because write and read of `watch_gac_grpc_context` are all in watch_gac thread.

Comment (guo-shaoge) [reply dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp:401]: `TryCancel` is called in another thread, but it's thread safe

File: dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp [hunk 4]
```diff
@@ -295,27 +309,36 @@ std::vector<std::string> LocalAdmissionController::handleTokenBucketsResp(
...
         {
-            handleBackgroundError(fmt::format(
-                "expect resp.granted_r_u_tokens().size() is 1, but got {}",
-                one_resp.granted_r_u_tokens().size()));
+            LOG_ERROR(
+                log,
+                fmt::format(
+                    "expect resp.granted_r_u_tokens().size() is 1 or 0, but got {} for rg {}",
+                    one_resp.granted_r_u_tokens().size(),
+                    one_resp.resource_group_name()));
```
[the remark this answers is not in the document]
Comment (guo-shaoge) [reply dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp]: done

File: dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp (hunk 3 above)
Comment (SeaRise) [reply dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp:401]: ok

**Review by SeaRise — APPROVED** [review]
