### PR TITLE
check the accuracy of the memory track in test mode

### LINKED ISSUE #5776: check the accuracy of the memory track in test mode
## Enhancement
In order to test the accuracy of the memory track in tiflash, a test mode should be added to the memory track. 
In the test mode, if the part exceeding the tracked amount is greater than ```accuracy_diff_for_test```, an exception will be thrown.

### PR DESCRIPTION
**Pull request by Qiaolin-Yu**
### What problem does this PR solve?

Issue Number: close #5776

Problem Summary:

### What is changed and how it works?
Check the accuracy of the memory track in test mode through the following method.
- Add ```memory_tracker_accuracy_diff_for_test``` to the configuration. 
- It defaults to 0 (off state), and when it is greater than 0, it is regarded as on.
- When allocating memory, if the test mode is on and ```real_rss > accuracy_diff_for_test + current_amount```, throw an exception.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by bestwoody** [comment]
If the pr is ready，you can remove  mark `“[WIP] ”` remove the title

**Review by bestwoody — APPROVED** [review]
lgtm

File: dbms/src/Interpreters/ProcessList.h [hunk 1]
```diff
@@ -122,7 +123,10 @@ class ProcessListElement
         current_memory_tracker = memory_tracker.get();
 
         if (memory_tracker_fault_probability)
-            memory_tracker->setFaultProbability(memory_tracker_fault_probability);
+            memory_tracker.setFaultProbability(memory_tracker_fault_probability);
+            
+        if (memory_tracker_accuracy_diff_for_test)
+            memory_tracker.setAccuracyDiff(memory_tracker_accuracy_diff_for_test);
```
Comment (windtalker) [inline dbms/src/Interpreters/ProcessList.h:129]: It looks like `memory_tracker` here is only the query's memory tracker, and `memory_tracker_accuracy_diff_for_test` only affects the root memory tracker, how is this setting be set to root memory tracker?

File: dbms/src/Common/MemoryTracker.cpp [hunk 2]
```diff
@@ -69,6 +69,20 @@ void MemoryTracker::alloc(Int64 size, bool check_memory_limit)
       *  we allow exception about memory limit exceeded to be thrown only on next allocation.
       * So, we allow over-allocations.
       */
+    Int64 current_amount = amount.load(std::memory_order_relaxed);
+    if (unlikely(!next.load(std::memory_order_relaxed) && accuracy_diff_for_test && real_rss > accuracy_diff_for_test + current_amount))
```
[the remark this answers is not in the document]
Comment (Qiaolin-Yu) [reply dbms/src/Common/MemoryTracker.cpp:73]: if ```real_rss``` is not supported, it will be 0 and will not affect the if statement here.

File: dbms/src/Interpreters/ProcessList.h (hunk 1 above)
Comment (Qiaolin-Yu) [reply dbms/src/Interpreters/ProcessList.h:129]: Because ```next``` is not necessarily set in the constructor, it seems that I can't ensure whether it is a root memory tracker here.

**Review by bestwoody — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM
