### PR TITLE
Use jemalloc to trace thread allocation

### LINKED ISSUE #8589: tiflash cn always crash after kill this tiflash cn
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run ch
2、 kill one of tiflash cn （secondary-tc-tiflash-0）

### 2. What did you expect to see? (Required)
no crash

### 3. What did you see instead (Required)
tiflash cn always crash after kill this tiflash cn
image
img_v3_026g_3616ccb9-c575-4318-8ae7-6355a5df750g

[2023/12/26 15:05:00.453 +08:00] [FATAL] [[config.rs:437](http://config.rs:437/)] ["invalid configuration: Cannot find raft data set."] [thread_id=0x5]

### 4. What is your TiFlash version? (Required)
git hash：963b1e352bfa3aa98b91fb83338d75533f76e76e

### LINKED ISSUE #8835: Support thread-wise memory alloc/dealloc monitor
## Enhancement

Basicly https://github.com/tikv/tikv/issues/8235, but with some tricks to fix the two copies of jemalloc problem

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #8835, close #8589

Problem Summary:

1. WITH_JEMALLOC to enable external-jemalloc
2. Introduce reportThreadAllocInfo etc.

Basicly two modes:
1. For everlasting threads, record allocated/deallocated ptr, update according to these ptrs.
2. For non-everlasting threads, mostly comes from Proxy, update only when the thread is executing something.

We don't directly monitor at FFI boundary because:
1. There are some threads like raftstore which can't be monitored through FFI boundary.
2. Rust's thread id does not has a meaning.

See also https://github.com/pingcap/tidb-engine-ext/pull/366/files

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by CalvinNeo** [comment]
image

File: dbms/src/Storages/KVStore/KVStore.cpp [hunk 1]
```diff
@@ -483,4 +495,126 @@ RegionTaskLock KVStore::genRegionTaskLock(UInt64 region_id) const
...
+    }
+}
+
+/// For those threads with shorter life, we must only update in their call chain.
+void KVStore::reportThreadAllocBatch(std::string_view name, ReportThreadAllocateInfoBatch data)
+{
+    // Many threads have empty name, better just not handle.
+    if (name.empty())
+        return;
+    // TODO(o11y) Could be costy.
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/KVStore/KVStore.cpp:592]: IMO, o11y is not a good name...

File: dbms/src/Storages/KVStore/KVStore.cpp [hunk 2]
```diff
@@ -483,4 +495,126 @@ RegionTaskLock KVStore::genRegionTaskLock(UInt64 region_id) const
...
+    {
+        if (value == 0)
+            return;
+        auto it = memory_allocation_map.find(tname);
+        if unlikely (it == memory_allocation_map.end())
+        {
+            return;
+        }
+        it->second.deallocated_ptr = value;
+    }
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/KVStore/KVStore.cpp:552]: use switch?

File: dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp [hunk 3]
```diff
@@ -1030,4 +1030,53 @@ BaseBuffView GetLockByKey(const EngineStoreServerWrap * server, uint64_t region_
...
+{
+    try
+    {
+        UNUSED(tid);
+        if (server == nullptr)
+            return;
+        if (server->tmt == nullptr)
+            return;
+        if (server->tmt->getKVStore() == nullptr)
+            return;
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp:1072]:
```suggestion
        if (!server || !server->tmt || !server->tmt->getKVStore())
            return;
```

File: CMakeLists.txt [hunk 4]
```diff
@@ -373,6 +373,10 @@ else ()
     message (STATUS "Set jemalloc narenas ${JEMALLOC_NARENAS}")
 endif ()
 
+if (ENABLE_JEMALLOC)
+    add_compile_definitions(WITH_JEMALLOC)
+endif ()
```
Comment (Lloyd-Pottiger) [inline CMakeLists.txt:378]: Do we need to add `WITH_JEMALLOC` for all files?

File: dbms/src/Common/MemoryTrace.h [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+    uint64_t size2 = sizeof ptr2;
+    mallctl("thread.deallocatedp", (void *)&ptr2, &size2, NULL, 0);
+    return std::make_tuple(ptr1, ptr2);
+}
+#else
+std::tuple<uint64_t *, uint64_t *> getAllocDeallocPtr()
+{
+    return std::make_tuple(nullptr, nullptr);
+}
+#endif
```
Comment (Lloyd-Pottiger) [inline dbms/src/Common/MemoryTrace.h:39]:
```suggestion
std::tuple<uint64_t *, uint64_t *> getAllocDeallocPtr()
{
#ifdef WITH_JEMALLOC
    uint64_t * ptr1 = nullptr;
    uint64_t size1 = sizeof ptr1;
    mallctl("thread.allocatedp", (void *)&ptr1, &size1, NULL, 0);
    uint64_t * ptr2 = nullptr;
    uint64_t size2 = sizeof ptr2;
    mallctl("thread.deallocatedp", (void *)&ptr2, &size2, NULL, 0);
    return std::make_tuple(ptr1, ptr2);
#else
    return std::make_tuple(nullptr, nullptr);
#endif
}
```

File: dbms/src/Storages/KVStore/KVStore.cpp (hunk 1 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/KVStore.cpp:592]: fixed

File: CMakeLists.txt (hunk 4 above)
Comment (CalvinNeo) [reply CMakeLists.txt:378]: let me check, maybe USE_JEMALLOC is enough

File: dbms/src/Common/MemoryTrace.h (hunk 5 above)
Comment (CalvinNeo) [reply dbms/src/Common/MemoryTrace.h]: fixed

File: CMakeLists.txt (hunk 4 above)
Comment (CalvinNeo) [reply CMakeLists.txt:378]: fixed

File: dbms/src/Storages/KVStore/KVStore.cpp [hunk 6]
```diff
@@ -68,6 +68,17 @@ KVStore::KVStore(Context & context)
...
+    monitoring_thread = new std::thread([&]() {
+        while (true)
+        {
+            std::unique_lock l(monitoring_mut);
+            monitoring_cv.wait_for(l, 5000ms, [&]() { return is_terminated; });
+            if (is_terminated)
+                return;
+            recordThreadAllocInfo();
+        }
+    });
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/KVStore.cpp:81]: What about register a task to `BackgroundProcessingPool` rather than creating a new thread?

File: dbms/src/Storages/KVStore/KVStore.cpp (hunk 2 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/KVStore.cpp]: fixed

File: dbms/src/Storages/KVStore/KVStore.cpp (hunk 6 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/KVStore.cpp:81]: I think it brings overhead to `BackgroundProcessingPool` in scheduling.

File: dbms/src/Storages/KVStore/KVStore.cpp [hunk 7]
```diff
@@ -483,4 +495,128 @@ RegionTaskLock KVStore::genRegionTaskLock(UInt64 region_id) const
...
+}
+
+static std::string getThreadNameAggPrefix(const std::string_view & s)
+{
+    if (auto pos = s.find_last_of('-'); pos != std::string::npos)
+    {
+        return std::string(s.begin(), s.begin() + pos);
+    }
+    return std::string(s.begin(), s.end());
+}
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/KVStore.cpp:514]: Fixed

File: dbms/src/Server/Server.cpp [hunk 8]
```diff
@@ -1708,6 +1714,8 @@ int Server::main(const std::vector<std::string> & /*args*/)
                 LOG_ERROR(log, "Current status of engine-store is NOT Running, should not happen");
                 exit(-1);
             }
+            LOG_INFO(log, "Stop collecting metrics");
```
Comment (JaySon-Huang) [inline dbms/src/Server/Server.cpp:1717]:
```suggestion
            LOG_INFO(log, "Stop collecting thread alloc metrics");
```

File: dbms/src/Storages/KVStore/KVStore.cpp (hunk 6 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/KVStore/KVStore.cpp:81]: OK

File: dbms/src/Common/TiFlashMetrics.cpp [hunk 9]
```diff
@@ -96,4 +98,10 @@ void TiFlashMetrics::removeReplicaSyncRUCounter(UInt32 keyspace_id)
     registered_keyspace_sync_replica_ru_family->Remove(itr->second);
     registered_keyspace_sync_replica_ru.erase(itr);
 }
+
+double TiFlashMetrics::getProxyThreadMemory(const std::string & k)
+{
+    return registered_raft_proxy_thread_memory_usage_metrics[k]->Value();
```
Comment (JaySon-Huang) [inline dbms/src/Common/TiFlashMetrics.cpp:104]: check `k` must be present in `registered_raft_proxy_thread_memory_usage_metrics` before accessing to its `Value()`

Comment (CalvinNeo) [reply dbms/src/Common/TiFlashMetrics.cpp:104]: There is also race condition here, will fix together.

Comment (CalvinNeo) [reply dbms/src/Common/TiFlashMetrics.cpp]: fixed

**Review by JaySon-Huang — APPROVED** [review]

File: dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp [hunk 10]
```diff
@@ -1030,4 +1030,49 @@ BaseBuffView GetLockByKey(const EngineStoreServerWrap * server, uint64_t region_
...
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp:1048]:
```suggestion
        if (!server || !server->tmt || !server->tmt->getKVStore())
             return;
```

**Review by Lloyd-Pottiger — APPROVED** [review]
LGTM

File: dbms/src/Common/TiFlashMetrics.cpp [hunk 11]
```diff
@@ -96,4 +98,24 @@ void TiFlashMetrics::removeReplicaSyncRUCounter(UInt32 keyspace_id)
     registered_keyspace_sync_replica_ru_family->Remove(itr->second);
     registered_keyspace_sync_replica_ru.erase(itr);
 }
-} // namespace DB
+
+double TiFlashMetrics::getProxyThreadMemory(const std::string & k)
+{
+    std::shared_lock lock(proxy_thread_ru_mtx);
+    auto it = registered_raft_proxy_thread_memory_usage_metrics.find(k);
+    RUNTIME_CHECK(it != registered_raft_proxy_thread_memory_usage_metrics.end());
```
Comment (JaySon-Huang) [inline dbms/src/Common/TiFlashMetrics.cpp:106]:
```suggestion
    RUNTIME_CHECK(it != registered_raft_proxy_thread_memory_usage_metrics.end(), k);
```

File: dbms/src/Storages/KVStore/KVStore.cpp [hunk 12]
```diff
@@ -483,4 +495,126 @@ RegionTaskLock KVStore::genRegionTaskLock(UInt64 region_id) const
...
+    switch (type)
+    {
+    case ReportThreadAllocateInfoType::Reset:
+    {
+        {
+            auto & metrics = TiFlashMetrics::instance();
+            std::unique_lock lock(metrics.proxy_thread_ru_mtx);
+            if unlikely (!metrics.registered_raft_proxy_thread_memory_usage_metrics.count(k))
+            {
+                // Add new keyspace store usage metric
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/KVStore.cpp:522]: the comment is not correct

File: dbms/src/Storages/KVStore/KVStore.cpp [hunk 13]
```diff
@@ -483,4 +495,126 @@ RegionTaskLock KVStore::genRegionTaskLock(UInt64 region_id) const
...
+                metrics.registered_raft_proxy_thread_memory_usage_metrics.emplace(
+                    k,
+                    &metrics.registered_raft_proxy_thread_memory_usage_family->Add({{"type", k}}));
+            }
+        }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/KVStore.cpp:527]: wrap it as a method in `TiFlashMetrics` so that we won't easily miss the lock on `proxy_thread_ru_mtx`?

File: dbms/src/Common/TiFlashMetrics.h [hunk 14]
```diff
@@ -1118,6 +1121,11 @@ class TiFlashMetrics
     std::mutex replica_sync_ru_mtx;
     std::unordered_map<KeyspaceID, prometheus::Counter *> registered_keyspace_sync_replica_ru;
 
+    // TODO: Use CAS+HazPtr to remove proxy_thread_ru_mtx.
+    prometheus::Family<prometheus::Gauge> * registered_raft_proxy_thread_memory_usage_family;
+    std::shared_mutex proxy_thread_ru_mtx;
```
Comment (JaySon-Huang) [inline dbms/src/Common/TiFlashMetrics.h:1126]: What is "ru" here?

File: dbms/src/Storages/KVStore/KVStore.cpp (hunk 13 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/KVStore.cpp:527]: fixed

File: dbms/src/Storages/KVStore/KVStore.cpp (hunk 12 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/KVStore.cpp:522]: fixed

File: dbms/src/Common/TiFlashMetrics.h (hunk 14 above)
Comment (CalvinNeo) [reply dbms/src/Common/TiFlashMetrics.h:1126]: fixed

File: dbms/src/Common/MemoryTrace.cpp [hunk 15]
```diff
@@ -0,0 +1,37 @@
+// Copyright 2024 PingCAP, Inc.
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Common/MemoryTrace.cpp:1]: Changed into MemoryAllocTracker

**Comment by CalvinNeo** [comment]
```
[2024-03-18T09:33:57.596Z] 
Stopping fullstack-test_tiflash0_1 ... error

Stopping fullstack-test_tikv0_1    ... error

Stopping fullstack-test_pd0_1      ... error

Stopping fullstack-test_tidb0_1    ... done


[2024-03-18T09:33:57.596Z] ERROR: for fullstack-test_tiflash0_1  cannot stop container: 1f118e0614d4aac39cf246135f74a693a79197d56bb4142de62f0999daa734ca: tried to kill container, but did not receive an exit event

[2024-03-18T09:33:57.596Z] Removing fullstack-test_tidb0_1    ... 

[2024-03-18T09:33:57.596Z] Removing fullstack-test_tiflash0_1 ... 

[2024-03-18T09:33:57.851Z] 
Removing fullstack-test_tidb0_1    ... done

Removing fullstack-test_tiflash0_1 ... done
Removing network fullstack-test_default

[2024-03-18T09:33:57.852Z] error while removing network: network fullstack-test_default id c8d1b8608346fbdb325d6157808b9a71ad112ff4d6223204c15ac087a8c52973 has active endpoints
```
