### PR TITLE
tests: Disable some tests of inactivated features on 7.5

### LINKED ISSUE #9405: ParallelPrehandle: executeParallelTransform could return Aborted if there is ErrUpdateSchema (release-7.5)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #9405

Problem Summary:

1. SimpleWriteReadAfterRestoreFromCheckPoint is an FAP [soft error](https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tiflash/pipelines/release-7.5/pipelines/pull_unit_test/runs/84/log/?start=0) that pending investigation.
2. KVStoreSingleSnap4 is a Parallel Prehandle bug that need to be picked into cse. The issue is #9405

### What is changed and how it works?

```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]

File: dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp [hunk 1]
```diff
@@ -274,139 +274,139 @@ class DeltaMergeStoreTestFastAddPeer
...
+//         RowKeyRange::newAll(store->isCommonHandle(), store->getRowKeyColumnSize()),
+//         num_rows_write / 2 + 2 * num_rows_write);
+
+//     reload();
+
+//     verifyRows(
+//         RowKeyRange::newAll(store->isCommonHandle(), store->getRowKeyColumnSize()),
+//         num_rows_write / 2 + 2 * num_rows_write);
+// }
+// CATCH
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp:409]:
```suggestion

#if 0
TEST_P(DeltaMergeStoreTestFastAddPeer, SimpleWriteReadAfterRestoreFromCheckPoint)
try
{
    UInt64 write_store_id = current_store_id + 1;
    resetStoreId(write_store_id);
    {
        auto table_column_defines = DMTestEnv::getDefaultColumns();

        store = reload(table_column_defines);
    }

    const size_t num_rows_write = 128;
    // write DMFile
    {
        Block block = DMTestEnv::prepareSimpleWriteBlock(0, num_rows_write, false);
        store->write(*db_context, db_context->getSettingsRef(), block);
        store->flushCache(*db_context, RowKeyRange::newAll(false, 1), true);
        store->mergeDeltaAll(*db_context);
    }

    // Write ColumnFileTiny
    {
        Block block = DMTestEnv::prepareSimpleWriteBlock(num_rows_write, num_rows_write + num_rows_write, false);
        store->write(*db_context, db_context->getSettingsRef(), block);
        store->flushCache(*db_context, RowKeyRange::newAll(false, 1), true);
    }

    // write ColumnFileDeleteRange
    {
        HandleRange handle_range(0, num_rows_write / 2);
        store->deleteRange(*db_context, db_context->getSettingsRef(), RowKeyRange::fromHandleRange(handle_range));
        store->flushCache(*db_context, RowKeyRange::newAll(false, 1), true);
    }

    // write ColumnFileBig
    {
        Block block = DMTestEnv::prepareSimpleWriteBlock(
            num_rows_write + num_rows_write,
            num_rows_write + 2 * num_rows_write,
            false);
        auto dm_context = store->newDMContext(*db_context, db_context->getSettingsRef());
        auto [range, file_ids] = genDMFile(*dm_context, block);
        {
            // Mock DMFiles are uploaded to S3 in SSTFilesToDTFilesOutputStream
            auto remote_store = db_context->getSharedContextDisagg()->remote_data_store;
            ASSERT_NE(remote_store, nullptr);
            auto delegator = dm_context->path_pool->getStableDiskDelegator();
            for (const auto & file_id : file_ids)
            {
                auto dm_file = DMFile::restore(
                    db_context->getFileProvider(),
                    file_id.id,
                    file_id.id,
                    delegator.getDTFilePath(file_id.id),
                    DMFile::ReadMetaMode::all());
                remote_store->putDMFile(
                    dm_file,
                    S3::DMFileOID{
                        .store_id = write_store_id,
                        .keyspace_id = keyspace_id,
                        .table_id = store->physical_table_id,
                        .file_id = file_id.id,
                    },
                    true);
            }
        }
        store->ingestFiles(dm_context, range, file_ids, false);
        store->flushCache(*db_context, RowKeyRange::newAll(false, 1), true);
    }

    dumpCheckpoint(write_store_id);

    clearData();

    verifyRows(RowKeyRange::newAll(store->isCommonHandle(), store->getRowKeyColumnSize()), 0);

    const auto manifest_key = S3::S3Filename::newCheckpointManifest(write_store_id, upload_sequence).toFullKey();
    auto checkpoint_info = std::make_shared<CheckpointInfo>();
    checkpoint_info->remote_store_id = write_store_id;
    checkpoint_info->region_id = 1000;
    checkpoint_info->checkpoint_data_holder = buildParsedCheckpointData(*db_context, manifest_key, /*dir_seq*/ 100);
    checkpoint_info->temp_ps = checkpoint_info->checkpoint_data_holder->getUniversalPageStorage();
    resetStoreId(current_store_id);
    {
        auto table_column_defines = DMTestEnv::getDefaultColumns();

        store = reload(table_column_defines);
    }
    store->ingestSegmentsFromCheckpointInfo(
        *db_context,
        db_context->getSettingsRef(),
        RowKeyRange::newAll(false, 1),
        checkpoint_info);

    // check data file lock exists
    {
        const auto data_key = S3::S3Filename::newCheckpointData(write_store_id, upload_sequence, 0).toFullKey();
        const auto data_key_view = S3::S3FilenameView::fromKey(data_key);
        const auto lock_prefix = data_key_view.getLockPrefix();
        auto client = S3::ClientFactory::instance().sharedTiFlashClient();
        std::set<String> lock_keys;
        S3::listPrefix(*client, lock_prefix, [&](const Aws::S3::Model::Object & object) {
            const auto & lock_key = object.GetKey();
            // also store the object.GetLastModified() for removing
            // outdated manifest objects
            lock_keys.emplace(lock_key);
            return DB::S3::PageResult{.num_keys = 1, .more = true};
        });
        // 2 lock files, 1 from write store, 1 from current store
        ASSERT_EQ(lock_keys.size(), 2);
        bool current_store_lock_exist = false;
        for (const auto & lock_key : lock_keys)
        {
            auto lock_key_view = S3::S3FilenameView::fromKey(lock_key);
            ASSERT_TRUE(lock_key_view.isLockFile());
            auto lock_info = lock_key_view.getLockInfo();
            if (lock_info.store_id == current_store_id)
                current_store_lock_exist = true;
        }
        ASSERT_TRUE(current_store_lock_exist);
    }

    verifyRows(
        RowKeyRange::newAll(store->isCommonHandle(), store->getRowKeyColumnSize()),
        num_rows_write / 2 + 2 * num_rows_write);

    reload();

    verifyRows(
        RowKeyRange::newAll(store->isCommonHandle(), store->getRowKeyColumnSize()),
        num_rows_write / 2 + 2 * num_rows_write);
}
CATCH
#endif
```

File: dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp [hunk 2]
```diff
@@ -299,79 +299,79 @@ try
...
+//         HandleID sst_limit = 100;
+//         table_id = proxy_instance->bootstrapTable(ctx, kvs, ctx.getTMTContext());
+//         auto start = RecordKVFormat::genKey(table_id, 0);
+//         auto end = RecordKVFormat::genKey(table_id, table_limit);
+//         proxy_instance->bootstrapWithRegion(
+//             kvs,
+//             ctx.getTMTContext(),
+//             region_id,
+//             std::make_pair(start.toString(), end.toString()));
+//         auto r1 = proxy_instance->getRegion(region_id);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp:328]:
```suggestion
#if 0
// Test if one subtask throws.
TEST_F(RegionKVStoreTest, KVStoreSingleSnap4)
try
{
    auto ctx = TiFlashTestEnv::getGlobalContext();
    proxy_instance->cluster_ver = RaftstoreVer::V2;
    ASSERT_NE(proxy_helper->sst_reader_interfaces.fn_key, nullptr);
    ASSERT_NE(proxy_helper->fn_get_config_json, nullptr);
    UInt64 region_id = 1;
    TableID table_id;
    FailPointHelper::enableFailPoint(FailPoints::force_set_parallel_prehandle_threshold, static_cast<size_t>(0));
    SCOPE_EXIT({ FailPointHelper::disableFailPoint("force_set_parallel_prehandle_threshold"); });
    {
        region_id = 2;
        initStorages();
        KVStore & kvs = getKVS();
        HandleID table_limit = 90;
        HandleID sst_limit = 100;
        table_id = proxy_instance->bootstrapTable(ctx, kvs, ctx.getTMTContext());
        auto start = RecordKVFormat::genKey(table_id, 0);
        auto end = RecordKVFormat::genKey(table_id, table_limit);
        proxy_instance->bootstrapWithRegion(
            kvs,
            ctx.getTMTContext(),
            region_id,
            std::make_pair(start.toString(), end.toString()));
        auto r1 = proxy_instance->getRegion(region_id);
```

File: dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp [hunk 3]
```diff
@@ -299,79 +299,79 @@ try
...
+//             default_cf.finish_file(SSTFormatKind::KIND_TABLET);
+//             default_cf.freeze();
+//             MockRaftStoreProxy::Cf write_cf{region_id, table_id, ColumnFamilyType::Write};
+//             for (HandleID h = 1; h < sst_limit; h++)
+//             {
+//                 auto k = RecordKVFormat::genKey(table_id, h, 111);
+//                 write_cf.insert_raw(k, value_write);
+//             }
+//             write_cf.finish_file(SSTFormatKind::KIND_TABLET);
+//             write_cf.freeze();
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp:348]:
```suggestion
        auto [value_write, value_default] = proxy_instance->generateTiKVKeyValue(111, 999);
        {
            MockSSTReader::getMockSSTData().clear();
            MockRaftStoreProxy::Cf default_cf{region_id, table_id, ColumnFamilyType::Default};
            for (HandleID h = 1; h < sst_limit; h++)
            {
                auto k = RecordKVFormat::genKey(table_id, h, 111);
                default_cf.insert_raw(k, value_default);
            }
            default_cf.finish_file(SSTFormatKind::KIND_TABLET);
            default_cf.freeze();
            MockRaftStoreProxy::Cf write_cf{region_id, table_id, ColumnFamilyType::Write};
            for (HandleID h = 1; h < sst_limit; h++)
            {
                auto k = RecordKVFormat::genKey(table_id, h, 111);
                write_cf.insert_raw(k, value_write);
            }
            write_cf.finish_file(SSTFormatKind::KIND_TABLET);
            write_cf.freeze();
```

File: dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp [hunk 4]
```diff
@@ -299,79 +299,79 @@ try
...
+//                 fpv->store(2);
+//                 EXPECT_THROW(
+//                     proxy_instance
+//                         ->snapshot(kvs, ctx.getTMTContext(), region_id, {default_cf, write_cf}, 0, 0, std::nullopt),
+//                     Exception);
+//             }
+//         }
+//     }
+// }
+// CATCH
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp:374]:
```suggestion
            auto fpv = std::make_shared<std::atomic_uint64_t>(0);
            FailPointHelper::enableFailPoint(FailPoints::force_raise_prehandle_exception, fpv);
            SCOPE_EXIT({ FailPointHelper::disableFailPoint("force_raise_prehandle_exception"); });
            {
                LOG_INFO(log, "Try decode when meet the first ErrUpdateSchema");
                fpv->store(1);
                FailPointHelper::enableFailPoint(FailPoints::force_raise_prehandle_exception, fpv);
                auto [kvr1, res]
                    = proxy_instance
                          ->snapshot(kvs, ctx.getTMTContext(), region_id, {default_cf, write_cf}, 0, 0, std::nullopt);
                // After retried.
                ASSERT_EQ(res.stats.parallels, 4);
            }
            {
                LOG_INFO(log, "Try decode when always meet ErrUpdateSchema");
                fpv->store(2);
                EXPECT_THROW(
                    proxy_instance
                        ->snapshot(kvs, ctx.getTMTContext(), region_id, {default_cf, write_cf}, 0, 0, std::nullopt),
                    Exception);
            }
        }
    }
}
CATCH
#endif
```

**Review by JaySon-Huang — APPROVED** [review]
