### PR TITLE
Fix the issue that window function returns incorrect result when range type frame end is preceding

### LINKED ISSUE #10236: Window function returns incorrect result when range type frame end is preceding
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. `create table t (p int, o int, v int);`
2. Insert many same rows into table and ensure that we need at least two blocks to contain them when executing
3. `select p, o, v, count(v) over (partition by p order by o range between 0 preceding and 0 preceding) as c from t;`

### 2. What did you expect to see? (Required)

all rows have same result

### 3. What did you see instead (Required)

some rows get different result

### 4. What is your TiFlash version? (Required)

nightly(1d5ca44e2776ed32)

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #10236

Problem Summary:

### What is changed and how it works?

```commit-message
Remove a wrong judgement
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the issue that window function returns incorrect result when range type frame end is preceding
```

### CODE REVIEW

**Review by guo-shaoge — APPROVED** [review]

File: dbms/src/WindowFunctions/tests/gtest_agg.cpp [hunk 1]
```diff
@@ -738,4 +738,32 @@ try
...
+        static_cast<Int64>(0));
+    frame.end = buildRangeFrameBound(
+        tipb::WindowBoundType::Preceding,
+        tipb::RangeCmpDataType::Int,
+        ORDER_COL_NAME,
+        false,
+        static_cast<Int64>(0));
+
+
+    executeFunctionAndAssert(
```
Comment (guo-shaoge) [inline dbms/src/WindowFunctions/tests/gtest_agg.cpp]: maybe change `profiles.default.max_block_size` to a smaller value? like 5?

File: dbms/src/DataStreams/WindowTransformAction.cpp [hunk 2]
```diff
@@ -660,7 +660,7 @@ std::tuple<RowNumber, bool> WindowTransformAction::stepToStartForRangeFrame()
 
 std::tuple<RowNumber, bool> WindowTransformAction::stepToEndForRangeFrame()
 {
-    if (!window_description.frame.end_preceding && !partition_ended)
+    if (!partition_ended)
         // If we find the frame end and the partition_ended is false.
```
Comment (guo-shaoge) [inline dbms/src/DataStreams/WindowTransformAction.cpp]: NOTE: for `expr` in `expr preceding`, `expr` can only be positive number, so no need to change `stepToStartForRangeFrame`

File: dbms/src/DataStreams/WindowTransformAction.cpp [hunk 3]
```diff
@@ -660,7 +660,7 @@ std::tuple<RowNumber, bool> WindowTransformAction::stepToStartForRangeFrame()
 
 std::tuple<RowNumber, bool> WindowTransformAction::stepToEndForRangeFrame()
 {
-    if (!window_description.frame.end_preceding && !partition_ended)
+    if (!partition_ended)
```
Comment (guo-shaoge) [inline dbms/src/DataStreams/WindowTransformAction.cpp]: Better add comments:
`
Still return false even when end_preceding is true, because there may still same rows as current_row in the next block.
So we cannot stop find the frame end until got the partition end(or got the first row that is greater than current_row).
`

Comment (xzhangxian1008) [reply dbms/src/DataStreams/WindowTransformAction.cpp]: > Better add comments: `Still return false even when end_preceding is true, because there may still same rows as current_row in the next block. So we cannot stop find the frame end until got the partition end(or got the first row that is greater than current_row).`

added

File: dbms/src/DataStreams/WindowTransformAction.cpp [hunk 4]
```diff
@@ -660,10 +660,15 @@ std::tuple<RowNumber, bool> WindowTransformAction::stepToStartForRangeFrame()
...
```
Comment (gengliqi) [inline dbms/src/DataStreams/WindowTransformAction.cpp]: How about
```suggestion
    bool end_preceding = window_description.frame.end_preceding;
    if ((!end_preceding || (end_preceding && frame.end_offset == 0)) && !partition_ended)
```

File: contrib/tipb
Comment (gengliqi) [inline contrib/tipb:1]: Why update tipb?
