### PR TITLE
Fix ExpressionAction Project miss block start offset

### LINKED ISSUE #10264: DB::Exception: Check rest_column_block.startOffset() == filter_column_block.startOffset() failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->

```
mysql> show create table t9ecf5a4a;
+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table     | Create Table                                                                                                                                                                                                                                                                                                            |
+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t9ecf5a4a | CREATE TABLE `t9ecf5a4a` (
  `col_62` time NOT NULL,
  `col_63` json NOT NULL,
  KEY `idx_43` ((cast(`col_63` as binary(64) array)),`col_62`),
  KEY `idx_44` ((cast(`col_63` as binary(64) array))),
  KEY `idx_45` ((cast(`col_63` as binary(64) array)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select /*+ read_from_storage(tiflash[ t9ecf5a4a ]) */ /*+ use_index_merge( t9ecf5a4a ) */ /*+ agg_to_cop() stream_agg() */  bit_and( t9ecf5a4a.col_62 ) as r0 from t9ecf5a4a where not( JSON_CONTAINS( t9ecf5a4a.col_63 , '\"OlcsCWSB3tiKzwahhMQbF9K0aHGEcIhFrNfMPbr4sZqJiWfJ6y1UzXaAmrdJhlds\"' ) ) and t9ecf5a4a.col_62 between '08:20:09.00' and '11:11:36.00' group by t9ecf5a4a.col_63

```

### 2. What did you expect to see? (Required)

### 3. What did you see instead (Required)

```
ERROR: Error 1105 (HY000): other error for mpp stream: Code: 49, e.displayText() = DB::Exception: Check rest_column_block.startOffset() == filter_column_block.startOffset() failed: Late materialization meets unexpected block unmatched, filter_column_block: [start_offset=0, rows=1], rest_column_block: [start_offset=3, rows=1], pass_count=1, e.what() = DB::Exception
```

### 4. What is your TiFlash version? (Required)

master

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #10264

Problem Summary:

### What is changed and how it works?

https://github.com/pingcap/tiflash/pull/9956 swap `start_offset` in `Block::swap`.

```
void Block::swap(Block & other) noexcept
{
    std::swap(info, other.info);
    data.swap(other.data);
    index_by_name.swap(other.index_by_name);
+    std::swap(start_offset, other.start_offset);
    std::swap(segment_row_id_col, other.segment_row_id_col);
    std::swap(rs_result, other.rs_result);
}
```

`new_block.startOffset()` has default value 0, after swap, `block.startOffset()` will be change to 0. Therefore, the block returned by `ExpressionBlockInputStream` if there is a `Project` action will always have `block.startOffset() == 0`.

Note: Only changes in dbms/src/Interpreters/ExpressionActions.cpp can fix this bug. Other changes are refactor.

```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Interpreters/ExpressionActions.cpp [hunk 1]
```diff
@@ -403,6 +403,7 @@ void ExpressionAction::execute(Block & block) const
             new_block.insert(std::move(column));
         }
         new_block.setRSResult(block.getRSResult());
+        new_block.setStartOffset(block.startOffset());
```
Comment (JaySon-Huang) [inline dbms/src/Interpreters/ExpressionActions.cpp]: Can you elaborate more on why the missing row causes the query to fail?

File: dbms/src/Core/Block.h [hunk 2]
```diff
@@ -153,7 +153,10 @@ class Block
     Block sortColumns() const;
 
     void clear();
+    // swap all data.
     void swap(Block & other) noexcept;
+    // only swap column data.
```
Comment (JinheLin) [inline dbms/src/Core/Block.h]: It needs to clarify when to use swap and when to use swapColumnData.

File: dbms/src/DataStreams/ExpandTransformAction.cpp [hunk 3]
```diff
@@ -36,7 +35,7 @@ bool ExpandTransformAction::tryOutput(Block & block)
     if (!block_cache || i_th_project >= expand->getLevelProjectionNum())
         return false;
     auto res_block = expand->next(block_cache, i_th_project++);
-    block.swap(res_block);
+    block.swapCloumnData(res_block);
```
Comment (gengliqi) [inline dbms/src/DataStreams/ExpandTransformAction.cpp]: How about `block = expand->next(block_cache, i_th_project++);`？

File: dbms/src/DataStreams/ExpandTransformAction.cpp [hunk 4]
```diff
@@ -52,6 +51,6 @@ void ExpandTransformAction::transform(Block & block)
     block_cache = block;
     i_th_project = 0;
     auto res_block = expand->next(block_cache, i_th_project++);
-    block.swap(res_block);
+    block.swapCloumnData(res_block);
```
Comment (gengliqi) [inline dbms/src/DataStreams/ExpandTransformAction.cpp]: ditto

File: dbms/src/DataStreams/ExpandTransformAction.cpp (hunk 3 above)
Comment (Lloyd-Pottiger) [reply dbms/src/DataStreams/ExpandTransformAction.cpp]: done

File: dbms/src/Core/Block.h (hunk 2 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Core/Block.h]:
```cpp
    // The following functions will swap two block.
    // `swap` will swap all data in blocks.
    // And `swapCloumnData` will only swap column data,
    // `start_offset` and `rs_result` will keep unchanged.
    void swap(Block & other) noexcept;
    void swapCloumnData(Block & other) noexcept;
```

**Review by gengliqi — APPROVED** [review]
