### PR TITLE
Fix integration test of parallel prehandling

### LINKED ISSUE #8246: Integration test of parallel prehandling is not stable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #8246

Problem Summary:

The problem is when a retryable exception is thrown in a thread, it will notify other thread to abort. As a result, other thread will abort. If the abort result is captured before the retryable result by head split, it will abort directly without retry.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 1]
```diff
@@ -189,7 +181,10 @@ static inline std::tuple<ReadFromStreamResult, PrehandleResult> executeTransform
         if (stream->isAbort())
         {
             stream->cancel();
-            res = ReadFromStreamResult{.error = ReadFromStreamError::Aborted, .extra_msg = "", .region = new_region};
+            res = ReadFromStreamResult{
```
Comment (CalvinNeo) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:184]: When abort, we will use abort_error, which is by default Aborted, but sometimes could be other value.

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 2]
```diff
@@ -567,7 +563,6 @@ void executeParallelTransform(
         LOG_DEBUG(log, "Try fetch prehandle task split_id={}, region_id={}", extra_id, new_region->id());
         async_tasks.fetchResult(extra_id);
     }
-    if (head_result.error == ReadFromStreamError::Ok)
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:570]: Why must we run through the codes below if the "head split" is not OK now?

**Comment by JaySon-Huang** [comment]
which unstable test case is caused by this issue?

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 3]
```diff
@@ -448,6 +443,7 @@ static void runInParallel(
         if (part_result.error == ReadFromStreamError::ErrUpdateSchema)
         {
             prehandle_task->abort_flag.store(true);
+            prehandle_task->abort_error.store(ReadFromStreamError::ErrUpdateSchema);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:446]: I think this fix could lead to the same issue again:

Thread A: run `prehandle_task->abort_flag.store(true)` and CPU yield before `prehandle_task->abort_error.store(ReadFromStreamError::ErrUpdateSchema);`
Thread B: read `prehandle_task->abort_error.load()` and see the reason is "abort"
Thread A: resume and set the reason is "update schema"

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp (hunk 2 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp]: fixed

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp (hunk 3 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp]: fixed by using a single atomic variable

File: dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h [hunk 4]
```diff
@@ -22,14 +22,35 @@
 
 namespace DB
 {
+enum class ReadFromStreamError
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h:25]: I think `PrehandleError` or `PrehandleStatus` is a more reasonable name here

**Comment by JaySon-Huang** [comment]
The fix of https://github.com/pingcap/tiflash/pull/8199#discussion_r1372552881 is not pushed?

File: dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h (hunk 4 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h]: Renamed to `PrehandleTransformStatus`, because there is a `PrehandleResult` for the whole prehandle process

**Review by JaySon-Huang — APPROVED** [review]
LGTM
