### PR TITLE
fix the issue that the RU returned by the DataStreamExecutor was too large

### LINKED ISSUE #6678: Collect cpu time second for tiflash compute

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #6678

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/Executor/DataStreamExecutor.cpp [hunk 1]
```diff
@@ -65,11 +69,23 @@ String DataStreamExecutor::toString() const
...
+    UInt64 total_thread_cnt = thread_cnt_before_execute + estimate_thread_cnt;
+    size_t physical_cpu_cores = getNumberOfPhysicalCPUCores();
+    if (origin_cpu_time_ns <= 0 || total_thread_cnt <= physical_cpu_cores)
+        return toRU(origin_cpu_time_ns);
+
+    // When the number of threads is greater than the number of cpu cores,
+    // BlockInputStream's estimated cpu time will be much greater than the actual value.
+    double per_thread_cpu_time_ns = static_cast<double>(origin_cpu_time_ns) / estimate_thread_cnt;
+    // It can be assumed that per_core_cpu_time = per_thread_cpu_time_ns * (total_thread_cnt / physical_cpu_cores).
+    UInt64 per_core_cpu_time_ns = ceil(per_thread_cpu_time_ns / total_thread_cnt) * physical_cpu_cores;
```
Comment (yibin87) [inline dbms/src/Flash/Executor/DataStreamExecutor.cpp:87]: It seems not the same for comment and code here?

Comment (SeaRise) [reply dbms/src/Flash/Executor/DataStreamExecutor.cpp:87]: fixed

**Review by yibin87 — APPROVED** [review]
LGTM

**Review by bestwoody — APPROVED** [review]

**Comment by bestwoody** [comment]
LGTM

File: dbms/src/Flash/Executor/DataStreamExecutor.cpp [hunk 2]
```diff
@@ -65,11 +69,23 @@ String DataStreamExecutor::toString() const
...
 int DataStreamExecutor::estimateNewThreadCount()
 {
-    return data_stream->estimateNewThreadCount();
+    return estimate_thread_cnt;
 }
 
 RU DataStreamExecutor::collectRequestUnit()
 {
-    return toRU(data_stream->estimateCPUTimeNs());
+    auto origin_cpu_time_ns = data_stream->estimateCPUTimeNs();
```
Comment (bestwoody) [inline dbms/src/Flash/Executor/DataStreamExecutor.cpp:77]: origin_cpu_time_ns = estimate_threads * perThreadCpuTime ?

File: dbms/src/Flash/Executor/DataStreamExecutor.cpp [hunk 3]
```diff
@@ -65,11 +69,23 @@ String DataStreamExecutor::toString() const
...
+    UInt64 total_thread_cnt = thread_cnt_before_execute + estimate_thread_cnt;
+    size_t physical_cpu_cores = getNumberOfPhysicalCPUCores();
+    if (origin_cpu_time_ns <= 0 || total_thread_cnt <= physical_cpu_cores)
+        return toRU(origin_cpu_time_ns);
+
+    // When the number of threads is greater than the number of cpu cores,
+    // BlockInputStream's estimated cpu time will be much greater than the actual value.
+    double per_thread_cpu_time_ns = static_cast<double>(origin_cpu_time_ns) / estimate_thread_cnt;
```
Comment (bestwoody) [inline dbms/src/Flash/Executor/DataStreamExecutor.cpp:85]: why the final result is origin_cpu_time_ns / estimate_thread_cnt/ (estimate_thread_cnt+K) * physical_cpu_cores * physical_cpu_cores ?

File: dbms/src/Flash/Executor/DataStreamExecutor.cpp (hunk 2 above)
Comment (SeaRise) [reply dbms/src/Flash/Executor/DataStreamExecutor.cpp:77]: The cputime returned by `BlockInputSrream` is a count of the execution time of each thread. So here we use `cputime / thread_cnt` to get the average cputime of each thread.
However, `per_thread_cputime` is still imprecise and is affected by thread scheduling and `condition_cv.wait`.
The following attempts to eliminate the effects of thread scheduling.

File: dbms/src/Flash/Executor/DataStreamExecutor.cpp (hunk 3 above)
Comment (SeaRise) [reply dbms/src/Flash/Executor/DataStreamExecutor.cpp:85]: Since a cpu core executes several threads, think of `execute_time_of_thread_A = cputime_of_thread_A + cputime_of_other_thread`.
Assuming that the cputime of other threads is the same as thread A, then we have `execute_time_of_thread_A = total_thread_cnt * cputime_of_thread_A`.
Assuming that the number of threads is divided equally among all cpu cores, then `the number of threads allocated to cpu core A = total_thread_cnt / cpu core num`.

File: dbms/src/Flash/Executor/DataStreamExecutor.cpp [hunk 4]
```diff
@@ -65,11 +69,23 @@ String DataStreamExecutor::toString() const
...
 }
 
 RU DataStreamExecutor::collectRequestUnit()
 {
-    return toRU(data_stream->estimateCPUTimeNs());
+    auto origin_cpu_time_ns = data_stream->estimateCPUTimeNs();
+    UInt64 total_thread_cnt = thread_cnt_before_execute + estimate_thread_cnt;
+    size_t physical_cpu_cores = getNumberOfPhysicalCPUCores();
+    if (origin_cpu_time_ns <= 0 || total_thread_cnt <= physical_cpu_cores)
+        return toRU(origin_cpu_time_ns);
```
Comment (Lloyd-Pottiger) [inline dbms/src/Flash/Executor/DataStreamExecutor.cpp:81]: why is physical cpu cores

File: dbms/src/Flash/Executor/DataStreamExecutor.cpp (hunk 3 above)
Comment (SeaRise) [reply dbms/src/Flash/Executor/DataStreamExecutor.cpp:85]: But there is still no way to eliminate the effect of `condition_cv.wait` here...

File: dbms/src/Flash/Executor/DataStreamExecutor.cpp (hunk 4 above)
Comment (SeaRise) [reply dbms/src/Flash/Executor/DataStreamExecutor.cpp:81]: Oh, maybe local cpu core is more appropriate

File: dbms/src/Flash/Executor/DataStreamExecutor.cpp (hunk 3 above)
Comment (SeaRise) [reply dbms/src/Flash/Executor/DataStreamExecutor.cpp]: I've added some derivations to the comments.
Now the final result is `ceil(static_cast<double>(execute_time_ns) / total_thread_cnt * logical_cpu_cores)`

File: dbms/src/Flash/Executor/DataStreamExecutor.cpp [hunk 5]
```diff
@@ -65,11 +69,44 @@ String DataStreamExecutor::toString() const
...
+    //                       = per_thread_execute_time_ns / total_thread_cnt * estimate_thread_cnt
+    // So that we have
+    //     cputime_ns = per_core_cpu_time * logical_cpu_cores
+    //                = per_thread_execute_time_ns / total_thread_cnt * estimate_thread_cnt * logical_cpu_cores
+    //                = execute_time_ns / total_thread_cnt / estimate_thread_cnt * estimate_thread_cnt * logical_cpu_cores
+    //                = execute_time_ns / total_thread_cnt * logical_cpu_cores
+    auto cpu_time_ns = static_cast<double>(execute_time_ns) / total_thread_cnt * logical_cpu_cores;
+    // But there is still no way to eliminate the effect of `condition_cv.wait` here...
+    // We can assume `condition.wait` takes half of datastream execute time.
+    cpu_time_ns /= 2;
```
Comment (bestwoody) [inline dbms/src/Flash/Executor/DataStreamExecutor.cpp:109]: add a TODO to make  `cpu_time_ns /= 2` more reasonable？

Comment (SeaRise) [reply dbms/src/Flash/Executor/DataStreamExecutor.cpp:110]: yes, you are right, comment `TODO find a more reasonable ratio for `condition.wait`.` added.
