### PR TITLE
Storages: Fix AddressSanitizer error of RateLimiter

### LINKED ISSUE #10087: AddressSanitizer error of RateLimiter
```
[2025-04-06T19:13:37.192Z] =================================================================
[2025-04-06T19:13:37.192Z] ==7548==ERROR: AddressSanitizer: container-overflow on address 0x5210000f03a0 at pc 0x55d0c2de81cc bp 0x7f10d5e652f0 sp 0x7f10d5e652e8
[2025-04-06T19:13:37.192Z] READ of size 8 at 0x5210000f03a0 thread T29
[2025-04-06T19:13:37.192Z]     #0 0x55d0c2de81cb in DB::WriteLimiter::request(long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/IO/BaseFile/RateLimiter.cpp:224:23
[2025-04-06T19:13:37.192Z]     #1 0x55d0a7d51ab0 in DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0::operator()(std::__1::shared_ptr<DB::WriteLimiter> const&, unsigned long) const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/IO/BaseFile/tests/gtest_rate_limiter.cpp:49:28
[2025-04-06T19:13:37.192Z]     #2 0x55d0a7d51ab0 in decltype(std::declval<DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0>()(std::declval<std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>>(), std::declval<unsigned long>())) std::__1::__invoke[abi:ue170006]<DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>, unsigned long>(DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0&&, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>&&, unsigned long&&) /usr/local/bin/../include/c++/v1/__type_traits/invoke.h:340:25
[2025-04-06T19:13:37.193Z]     #3 0x55d0a7d51ab0 in void std::__1::__thread_execute[abi:ue170006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>, unsigned long, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>, unsigned long>&, std::__1::__tuple_indices<2ul, 3ul>) /usr/local/bin/../include/c++/v1/__thread/thread.h:221:5
[2025-04-06T19:13:37.193Z]     #4 0x55d0a7d51ab0 in void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>, unsigned long>>(void*) /usr/local/bin/../include/c++/v1/__thread/thread.h:232:5
[2025-04-06T19:13:37.193Z]     #5 0x55d0a0a4eaca in asan_thread_start(void*) /llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:225:31
[2025-04-06T19:13:37.193Z]     #6 0x7f10eaebfea4 in start_thread pthread_create.c
[2025-04-06T19:13:37.193Z]     #7 0x7f10ea7b8b0c in clone (/lib64/libc.so.6+0xfeb0c) (BuildId: 9470e279388f7f9cb2ed3b2872d0c2095b191ff4)
[2025-04-06T19:13:37.193Z] 
[2025-04-06T19:13:37.193Z] 0x5210000f03a0 is located 672 bytes inside of 4096-byte region [0x5210000f0100,0x5210000f1100)
[2025-04-06T19:13:37.193Z] allocated by thread T26 here:
[2025-04-06T19:13:37.193Z]     #0 0x55d0a0a8d91d in operator new(unsigned long) /llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
[2025-04-06T19:13:37.193Z]     #1 0x55d0c2dfd9df in void* std::__1::__libcpp_operator_new[abi:ue170006]<unsigned long>(unsigned long) /usr/local/bin/../include/c++/v1/new:268:10
[2025-04-06T19:13:37.193Z]     #2 0x55d0c2dfd9df in std::__1::__libcpp_allocate[abi:ue170006](unsigned long, unsigned long) /usr/local/bin/../include/c++/v1/new:294:10
[2025-04-06T19:13:37.193Z]     #3 0x55d0c2dfd9df in std::__1::allocator<DB::WriteLimiter::Request*>::allocate[abi:ue170006](unsigned long) /usr/local/bin/../include/c++/v1/__memory/allocator.h:114:38
[2025-04-06T19:13:37.193Z]     #4 0x55d0c2dfd9df in std::__1::allocator_traits<std::__1::allocator<DB::WriteLimiter::Request*>>::allocate[abi:ue170006](std::__1::allocator<DB::WriteLimiter::Request*>&, unsigned long) /usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:268:20
[2025-04-06T19:13:37.193Z]     #5 0x55d0c2dfd9df in std::__1::deque<DB::WriteLimiter::Request*, std::__1::allocator<DB::WriteLimiter::Request*>>::__add_back_capacity() /usr/local/bin/../include/c++/v1/deque:2473:13
[2025-04-06T19:13:37.193Z]     #6 0x55d0c2de7164 in std::__1::deque<DB::WriteLimiter::Request*, std::__1::allocator<DB::WriteLimiter::Request*>>::push_back(DB::WriteLimiter::Request*&&) /usr/local/bin/../include/c++/v1/deque:1757:9
[2025-04-06T19:13:37.193Z]     #7 0x55d0c2de7164 in DB::WriteLimiter::request(long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/IO/BaseFile/RateLimiter.cpp:183:15
[2025-04-06T19:13:37.193Z]     #8 0x55d0a7d51ab0 in DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0::operator()(std::__1::shared_ptr<DB::WriteLimiter> const&, unsigned long) const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/IO/BaseFile/tests/gtest_rate_limiter.cpp:49:28
[2025-04-06T19:13:37.193Z]     #9 0x55d0a7d51ab0 in decltype(std::declval<DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0>()(std::declval<std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>>(), std::declval<unsigned long>())) std::__1::__invoke[abi:ue170006]<DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>, unsigned long>(DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0&&, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>&&, unsigned long&&) /usr/local/bin/../include/c++/v1/__type_traits/invoke.h:340:25
[2025-04-06T19:13:37.193Z]     #10 0x55d0a7d51ab0 in void std::__1::__thread_execute[abi:ue170006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>, unsigned long, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>, unsigned long>&, std::__1::__tuple_indices<2ul, 3ul>) /usr/local/bin/../include/c++/v1/__thread/thread.h:221:5
[2025-04-06T19:13:37.194Z]     #11 0x55d0a7d51ab0 in void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>, unsigned long>>(void*) /usr/local/bin/../include/c++/v1/__thread/thread.h:232:5
[2025-04-06T19:13:37.194Z]     #12 0x55d0a0a4eaca in asan_thread_start(void*) /llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:225:31
[2025-04-06T19:13:37.194Z] 
[2025-04-06T19:13:37.194Z] Thread T29 created by T0 here:
[2025-04-06T19:13:37.194Z]     #0 0x55d0a0a369fd in pthread_create /llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:237:3
[2025-04-06T19:13:37.194Z]     #1 0x55d0a7d16eb9 in std::__1::__libcpp_thread_create[abi:ue170006](unsigned long*, void* (*)(void*), void*) /usr/local/bin/../include/c++/v1/__threading_support:371:10
[2025-04-06T19:13:37.194Z]     #2 0x55d0a7d16eb9 in std::__1::thread::thread<DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0&, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>, unsigned long, void>(DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0&, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>&&, unsigned long&&) /usr/local/bin/../include/c++/v1/__thread/thread.h:248:16
[2025-04-06T19:13:37.194Z]     #3 0x55d0a7d16eb9 in DB::tests::WriteLimiterTest_Rate_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/IO/BaseFile/tests/gtest_rate_limiter.cpp:63:25
[2025-04-06T19:13:37.194Z]     #4 0x55d0ba4b7eb1 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10
[2025-04-06T19:13:37.194Z]     #5 0x55d0ba4b7eb1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14
[2025-04-06T19:13:37.194Z]     #6 0x55d0ba4584f5 in testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5
[2025-04-06T19:13:37.194Z]     #7 0x55d0ba45ba5a in testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11
[2025-04-06T19:13:37.194Z]     #8 0x55d0ba45d10f in testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28
[2025-04-06T19:13:37.194Z]     #9 0x55d0ba48860a in testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43
[2025-04-06T19:13:37.194Z]     #10 0x55d0ba4ba5f1 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10
[2025-04-06T19:13:37.194Z]     #11 0x55d0ba4ba5f1 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14
[2025-04-06T19:13:37.194Z]     #12 0x55d0ba4878a6 in testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10
[2025-04-06T19:13:37.194Z]     #13 0x55d0aa89031f in RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46
[2025-04-06T19:13:37.194Z]     #14 0x55d0aa89031f in main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:118:16
[2025-04-06T19:13:37.194Z]     #15 0x7f10ea6dc554 in __libc_start_main (/lib64/libc.so.6+0x22554) (BuildId: 9470e279388f7f9cb2ed3b2872d0c2095b191ff4)
[2025-04-06T19:13:37.194Z] 
[2025-04-06T19:13:37.194Z] Thread T26 created by T0 here:
[2025-04-06T19:13:37.194Z]     #0 0x55d0a0a369fd in pthread_create /llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:237:3
[2025-04-06T19:13:37.194Z]     #1 0x55d0a7d16eb9 in std::__1::__libcpp_thread_create[abi:ue170006](unsigned long*, void* (*)(void*), void*) /usr/local/bin/../include/c++/v1/__threading_support:371:10
[2025-04-06T19:13:37.194Z]     #2 0x55d0a7d16eb9 in std::__1::thread::thread<DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0&, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>, unsigned long, void>(DB::tests::WriteLimiterTest_Rate_Test::TestBody()::$_0&, std::__1::reference_wrapper<std::__1::shared_ptr<DB::WriteLimiter>>&&, unsigned long&&) /usr/local/bin/../include/c++/v1/__thread/thread.h:248:16
[2025-04-06T19:13:37.195Z]     #3 0x55d0a7d16eb9 in DB::tests::WriteLimiterTest_Rate_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/IO/BaseFile/tests/gtest_rate_limiter.cpp:63:25
[2025-04-06T19:13:37.195Z]     #4 0x55d0ba4b7eb1 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10
[2025-04-06T19:13:37.195Z]     #5 0x55d0ba4b7eb1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14
[2025-04-06T19:13:37.195Z]     #6 0x55d0ba4584f5 in testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5
[2025-04-06T19:13:37.195Z]     #7 0x55d0ba45ba5a in testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11
[2025-04-06T19:13:37.195Z]     #8 0x55d0ba45d10f in testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28
[2025-04-06T19:13:37.195Z]     #9 0x55d0ba48860a in testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43
[2025-04-06T19:13:37.195Z]     #10 0x55d0ba4ba5f1 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10
[2025-04-06T19:13:37.195Z]     #11 0x55d0ba4ba5f1 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14
[2025-04-06T19:13:37.195Z]     #12 0x55d0ba4878a6 in testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10
[2025-04-06T19:13:37.195Z]     #13 0x55d0aa89031f in RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46
[2025-04-06T19:13:37.195Z]     #14 0x55d0aa89031f in main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:118:16
[2025-04-06T19:13:37.195Z]     #15 0x7f10ea6dc554 in __libc_start_main (/lib64/libc.so.6+0x22554) (BuildId: 9470e279388f7f9cb2ed3b2872d0c2095b191ff4)
[2025-04-06T19:13:37.195Z] 
[2025-04-06T19:13:37.195Z] HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_container_overflow=0.
[2025-04-06T19:13:37.195Z] If you suspect a false positive see also: https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow.
[2025-04-06T19:13:37.195Z] SUMMARY: AddressSanitizer: container-overflow /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/IO/BaseFile/RateLimiter.cpp:224:23 in DB::WriteLimiter::request(long)
[2025-04-06T19:13:37.195Z] Shadow bytes around the buggy address:
[2025-04-06T19:13:37.195Z]   0x5210000f0100: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
[2025-04-06T19:13:37.195Z]   0x5210000f0180: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
[2025-04-06T19:13:37.195Z]   0x5210000f0200: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
[2025-04-06T19:13:37.195Z]   0x5210000f0280: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
[2025-04-06T19:13:37.195Z]   0x5210000f0300: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
[2025-04-06T19:13:37.195Z] =>0x5210000f0380: fc fc fc fc[fc]fc fc fc fc fc fc fc fc fc fc fc
[2025-04-06T19:13:37.195Z]   0x5210000f0400: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
[2025-04-06T19:13:37.195Z]   0x5210000f0480: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
[2025-04-06T19:13:37.195Z]   0x5210000f0500: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
[2025-04-06T19:13:37.195Z]   0x5210000f0580: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
[2025-04-06T19:13:37.195Z]   0x5210000f0600: fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc fc
[2025-04-06T19:13:37.195Z] Shadow byte legend (one shadow byte represents 8 application bytes):
[2025-04-06T19:13:37.195Z]   Addressable:           00
[2025-04-06T19:13:37.195Z]   Partially addressable: 01 02 03 04 05 06 07
[2025-04-06T19:13:37.195Z]   Heap left redzone:       fa
[2025-04-06T19:13:37.195Z]   Freed heap region:       fd
[2025-04-06T19:13:37.195Z]   Stack left redzone:      f1
[2025-04-06T19:13:37.196Z]   Stack mid redzone:       f2
[2025-04-06T19:13:37.196Z]   Stack right redzone:     f3
[2025-04-06T19:13:37.196Z]   Stack after return:      f5
[2025-04-06T19:13:37.196Z]   Stack use after scope:   f8
[2025-04-06T19:13:37.196Z]   Global redzone:          f9
[2025-04-06T19:13:37.196Z]   Global init order:       f6
[2025-04-06T19:13:37.196Z]   Poisoned by user:        f7
[2025-04-06T19:13:37.196Z]   Container overflow:      fc
[2025-04-06T19:13:37.196Z]   Array cookie:            ac
[2025-04-06T19:13:37.196Z]   Intra object redzone:    bb
[2025-04-06T19:13:37.196Z]   ASan internal:           fe
[2025-04-06T19:13:37.196Z]   Left alloca redzone:     ca
[2025-04-06T19:13:37.196Z]   Right alloca redzone:    cb
[2025-04-06T19:13:37.196Z] ==7548==ABORTING
[2025-04-06T19:13:37.196Z] [829/3128] WriteLimiterTest.Rate returned/aborted with exit code 1 (10439 ms)
```

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #10087

Problem summary:

1. Initial State: `req_queue` is initialized as empty.
2. Step 1: Add `req0` to `req_queue`, then wait in [L201](https://github.com/pingcap/tiflash/blob/7032457eeaef6abf9c63096144f5f02fff35d10b/dbms/src/IO/BaseFile/RateLimiter.cpp#L201).
3. Step 2: Add `req1` to `req_queue`, then wait in [L212](https://github.com/pingcap/tiflash/blob/7032457eeaef6abf9c63096144f5f02fff35d10b/dbms/src/IO/BaseFile/RateLimiter.cpp#L212).
4. Step 3:
  - `req0` times out while waiting, enters [refillAndAlloc](https://github.com/pingcap/tiflash/blob/7032457eeaef6abf9c63096144f5f02fff35d10b/dbms/src/IO/BaseFile/RateLimiter.cpp#L226C13-L226C27).
  - `refillAndAlloc` [pops](https://github.com/pingcap/tiflash/blob/7032457eeaef6abf9c63096144f5f02fff35d10b/dbms/src/IO/BaseFile/RateLimiter.cpp#L305) both `req0` and `req1` from `req_queue`, then [wakes up](https://github.com/pingcap/tiflash/blob/7032457eeaef6abf9c63096144f5f02fff35d10b/dbms/src/IO/BaseFile/RateLimiter.cpp#L308) req1.
  - Result: The `req_queue` becomes empty.
5. Step 4:
  - `req1` is awakened and proceeds to execute until line [L224](https://github.com/pingcap/tiflash/blob/7032457eeaef6abf9c63096144f5f02fff35d10b/dbms/src/IO/BaseFile/RateLimiter.cpp#L224), triggering the reported error.

### What is changed and how it works?

```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/IO/BaseFile/RateLimiter.cpp [hunk 1]
```diff
@@ -221,7 +221,7 @@ void WriteLimiter::request(Int64 bytes)
         }
 
         // time to do refill
-        if (req_queue.front() == &r && timed_out)
+        if (!req_queue.empty() && req_queue.front() == &r && timed_out)
```
Comment (JaySon-Huang) [inline dbms/src/IO/BaseFile/RateLimiter.cpp:224]: Is this comment right?
```suggestion
        // The `req_queue` could be empty because the responsible thread meets `timed_out` and clear the queue in `refillAndAlloc`
        if (!req_queue.empty() && req_queue.front() == &r && timed_out)
```

**Review by Lloyd-Pottiger — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]
