### PR TITLE
fix unittests tsan warnings.

### LINKED ISSUE #5881: ThreadSanitizer reports data race of SegmentReader in gtests_dbms
```
[2022-09-14T03:43:58.480Z] WARNING: ThreadSanitizer: data race (pid=10733)
[2022-09-14T03:43:58.480Z]   Write of size 8 at 0x7b1c00022ac0 by main thread:
[2022-09-14T03:43:58.480Z]     #0 operator delete(void*) /llvm-project/compiler-rt/lib/tsan/rtl/tsan_new_delete.cpp:126:3 (gtests_dbms+0x2561610)
[2022-09-14T03:43:58.480Z]     #1 void std::__1::__libcpp_operator_delete<void*>(void*) /usr/local/bin/../include/c++/v1/new:245:3 (gtests_dbms+0x3cacc79)
[2022-09-14T03:43:58.480Z]     #2 void std::__1::__do_deallocate_handle_size<>(void*, unsigned long) /usr/local/bin/../include/c++/v1/new:269:10 (gtests_dbms+0x3cacc79)
[2022-09-14T03:43:58.480Z]     #3 std::__1::__libcpp_deallocate(void*, unsigned long, unsigned long) /usr/local/bin/../include/c++/v1/new:285:14 (gtests_dbms+0x3cacc79)
[2022-09-14T03:43:58.480Z]     #4 std::__1::allocator<std::__1::__shared_ptr_emplace<DB::DM::DeltaIndex, std::__1::allocator<DB::DM::DeltaIndex> > >::deallocate(std::__1::__shared_ptr_emplace<DB::DM::DeltaIndex, std::__1::allocator<DB::DM::DeltaIndex> >*, unsigned long) /usr/local/bin/../include/c++/v1/__memory/allocator.h:117:13 (gtests_dbms+0x3cacc79)
[2022-09-14T03:43:58.480Z]     #5 std::__1::allocator_traits<std::__1::allocator<std::__1::__shared_ptr_emplace<DB::DM::DeltaIndex, std::__1::allocator<DB::DM::DeltaIndex> > > >::deallocate(std::__1::allocator<std::__1::__shared_ptr_emplace<DB::DM::DeltaIndex, std::__1::allocator<DB::DM::DeltaIndex> > >&, std::__1::__shared_ptr_emplace<DB::DM::DeltaIndex, std::__1::allocator<DB::DM::DeltaIndex> >*, unsigned long) /usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:282:13 (gtests_dbms+0x3cacc79)
[2022-09-14T03:43:58.480Z]     #6 std::__1::__shared_ptr_emplace<DB::DM::DeltaIndex, std::__1::allocator<DB::DM::DeltaIndex> >::__on_zero_shared_weak() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:324:9 (gtests_dbms+0x3cacc79)
[2022-09-14T03:43:58.480Z]     #7 std::__1::weak_ptr<DB::DM::DeltaIndex>::~weak_ptr() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:1486:19 (gtests_dbms+0xb11a571)
[2022-09-14T03:43:58.480Z]     #8 DB::DM::DeltaIndexManager::Holder::~Holder() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/DeltaIndexManager.h:39:12 (gtests_dbms+0xb11a571)
[2022-09-14T03:43:58.480Z]     #9 std::__1::pair<unsigned long const, DB::DM::DeltaIndexManager::Holder>::~pair() /usr/local/bin/../include/c++/v1/__utility/pair.h:42:29 (gtests_dbms+0xb11a571)
[2022-09-14T03:43:58.480Z]     #10 void std::__1::allocator_traits<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, DB::DM::DeltaIndexManager::Holder>, void*> > >::destroy<std::__1::pair<unsigned long const, DB::DM::DeltaIndexManager::Holder>, void, void>(std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, DB::DM::DeltaIndexManager::Holder>, void*> >&, std::__1::pair<unsigned long const, DB::DM::DeltaIndexManager::Holder>*) /usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:319:15 (gtests_dbms+0xb11a571)
[2022-09-14T03:43:58.480Z]     #11 std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, DB::DM::DeltaIndexManager::Holder>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, DB::DM::DeltaIndexManager::Holder>, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, DB::DM::DeltaIndexManager::Holder>, std::__1::equal_to<unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, DB::DM::DeltaIndexManager::Holder> > >::__deallocate_node(std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, DB::DM::DeltaIndexManager::Holder>, void*>*>*) /usr/local/bin/../include/c++/v1/__hash_table:1580:9 (gtests_dbms+0xb11a571)
[2022-09-14T03:43:58.480Z]     #12 std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, DB::DM::DeltaIndexManager::Holder>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, DB::DM::DeltaIndexManager::Holder>, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, DB::DM::DeltaIndexManager::Holder>, std::__1::equal_to<unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, DB::DM::DeltaIndexManager::Holder> > >::~__hash_table() /usr/local/bin/../include/c++/v1/__hash_table:1519:5 (gtests_dbms+0xb11a571)
[2022-09-14T03:43:58.480Z]     #13 std::__1::unordered_map<unsigned long, DB::DM::DeltaIndexManager::Holder, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<std::__1::pair<unsigned long const, DB::DM::DeltaIndexManager::Holder> > >::~unordered_map() /usr/local/bin/../include/c++/v1/unordered_map:1047:5 (gtests_dbms+0xb11a571)
[2022-09-14T03:43:58.480Z]     #14 DB::DM::DeltaIndexManager::~DeltaIndexManager() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/DeltaIndexManager.h:26:7 (gtests_dbms+0xb11a571)
[2022-09-14T03:43:58.480Z]     #15 std::__1::__shared_ptr_emplace<DB::DM::DeltaIndexManager, std::__1::allocator<DB::DM::DeltaIndexManager> >::__on_zero_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:315:24 (gtests_dbms+0xb11a571)
[2022-09-14T03:43:58.481Z]     #16 std::__1::__shared_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177:9 (gtests_dbms+0xb110f52)
[2022-09-14T03:43:58.481Z]     #17 std::__1::__shared_weak_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219:27 (gtests_dbms+0xb110f52)
[2022-09-14T03:43:58.481Z]     #18 std::__1::shared_ptr<DB::DM::DeltaIndexManager>::~shared_ptr() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959:19 (gtests_dbms+0xb110f52)
[2022-09-14T03:43:58.481Z]     #19 DB::ContextShared::~ContextShared() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Interpreters/Context.cpp:233:5 (gtests_dbms+0xb110f52)
[2022-09-14T03:43:58.481Z]     #20 std::__1::__shared_ptr_emplace<DB::ContextShared, std::__1::allocator<DB::ContextShared> >::__on_zero_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:315:24 (gtests_dbms+0xb10f1cd)
[2022-09-14T03:43:58.481Z]     #21 std::__1::__shared_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177:9 (gtests_dbms+0xb0f95a1)
[2022-09-14T03:43:58.481Z]     #22 std::__1::__shared_weak_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219:27 (gtests_dbms+0xb0f95a1)
[2022-09-14T03:43:58.481Z]     #23 std::__1::shared_ptr<DB::ContextShared>::~shared_ptr() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959:19 (gtests_dbms+0xb0f95a1)
[2022-09-14T03:43:58.481Z]     #24 DB::Context::~Context() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Interpreters/Context.cpp:303:1 (gtests_dbms+0xb0f95a1)
[2022-09-14T03:43:58.481Z]     #25 std::__1::__shared_ptr_emplace<DB::Context, std::__1::allocator<DB::Context> >::__on_zero_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:315:24 (gtests_dbms+0x44d7b0d)
[2022-09-14T03:43:58.481Z]     #26 std::__1::__shared_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177:9 (gtests_dbms+0x44d380a)
[2022-09-14T03:43:58.481Z]     #27 std::__1::__shared_weak_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219:27 (gtests_dbms+0x44d380a)
[2022-09-14T03:43:58.481Z]     #28 std::__1::shared_ptr<DB::Context>::~shared_ptr() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959:19 (gtests_dbms+0x44d380a)
[2022-09-14T03:43:58.481Z]     #29 std::__1::shared_ptr<DB::Context>::reset() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:1054:5 (gtests_dbms+0x44d380a)
[2022-09-14T03:43:58.481Z]     #30 DB::tests::TiFlashTestEnv::shutdown() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/TiFlashTestEnv.cpp:164:17 (gtests_dbms+0x44d380a)
[2022-09-14T03:43:58.481Z]     #31 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:80:5 (gtests_dbms+0x432759d)
[2022-09-14T03:43:58.481Z] 
[2022-09-14T03:43:58.481Z]   Previous read of size 8 at 0x7b1c00022ac0 by thread T57:
[2022-09-14T03:43:58.481Z]     #0 std::__1::__shared_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177:9 (gtests_dbms+0xb9e6383)
[2022-09-14T03:43:58.481Z]     #1 std::__1::__shared_weak_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219:27 (gtests_dbms+0xb9e6383)
[2022-09-14T03:43:58.481Z]     #2 std::__1::shared_ptr<DB::DM::DeltaIndex>::~shared_ptr() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959:19 (gtests_dbms+0xb9e6383)
[2022-09-14T03:43:58.481Z]     #3 DB::DM::DeltaValueSnapshot::~DeltaValueSnapshot() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h:304:5 (gtests_dbms+0xb9e6383)
[2022-09-14T03:43:58.481Z]     #4 std::__1::__shared_ptr_emplace<DB::DM::DeltaValueSnapshot, std::__1::allocator<DB::DM::DeltaValueSnapshot> >::__on_zero_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:315:24 (gtests_dbms+0xb9e61dd)
[2022-09-14T03:43:58.481Z]     #5 std::__1::__shared_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177:9 (gtests_dbms+0x3dc1a93)
[2022-09-14T03:43:58.481Z]     #6 std::__1::__shared_weak_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219:27 (gtests_dbms+0x3dc1a93)
[2022-09-14T03:43:58.481Z]     #7 std::__1::shared_ptr<DB::DM::DeltaValueSnapshot>::~shared_ptr() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959:19 (gtests_dbms+0x3dc1a93)
[2022-09-14T03:43:58.481Z]     #8 DB::DM::DeltaValueReader::~DeltaValueReader() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h:332:7 (gtests_dbms+0x3dc1a93)
[2022-09-14T03:43:58.481Z]     #9 std::__1::default_delete<DB::DM::DeltaValueReader>::operator()(DB::DM::DeltaValueReader*) const /usr/local/bin/../include/c++/v1/__memory/unique_ptr.h:57:5 (gtests_dbms+0xbafae1b)
[2022-09-14T03:43:58.481Z]     #10 std::__1::__shared_ptr_pointer<DB::DM::DeltaValueReader*, std::__1::shared_ptr<DB::DM::DeltaValueReader>::__shared_ptr_default_delete<DB::DM::DeltaValueReader, DB::DM::DeltaValueReader>, std::__1::allocator<DB::DM::DeltaValueReader> >::__on_zero_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:267:5 (gtests_dbms+0xbafae1b)
[2022-09-14T03:43:58.481Z]     #11 std::__1::__shared_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177:9 (gtests_dbms+0xb9cf9c5)
[2022-09-14T03:43:58.481Z]     #12 std::__1::__shared_weak_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219:27 (gtests_dbms+0xb9cf9c5)
[2022-09-14T03:43:58.481Z]     #13 std::__1::shared_ptr<DB::DM::DeltaValueReader>::~shared_ptr() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959:19 (gtests_dbms+0xb9cf9c5)
[2022-09-14T03:43:58.482Z]     #14 DB::DM::DeltaMergeBlockInputStream<DB::DM::DeltaValueReader, DB::DM::DTCompactedEntries<55ul, 20ul, 3ul>::Iterator, false>::~DeltaMergeBlockInputStream() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/DeltaMerge.h:36:7 (gtests_dbms+0xb9cf9c5)
[2022-09-14T03:43:58.482Z]     #15 std::__1::__shared_ptr_emplace<DB::DM::DeltaMergeBlockInputStream<DB::DM::DeltaValueReader, DB::DM::DTCompactedEntries<55ul, 20ul, 3ul>::Iterator, false>, std::__1::allocator<DB::DM::DeltaMergeBlockInputStream<DB::DM::DeltaValueReader, DB::DM::DTCompactedEntries<55ul, 20ul, 3ul>::Iterator, false> > >::__on_zero_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:315:24 (gtests_dbms+0xb9cf4dd)
[2022-09-14T03:43:58.482Z]     #16 std::__1::__shared_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177:9 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #17 std::__1::__shared_weak_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219:27 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #18 std::__1::shared_ptr<DB::IBlockInputStream>::~shared_ptr() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959:19 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #19 std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> >::destroy(std::__1::shared_ptr<DB::IBlockInputStream>*) /usr/local/bin/../include/c++/v1/__memory/allocator.h:159:15 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #20 void std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> > >::destroy<std::__1::shared_ptr<DB::IBlockInputStream>, void>(std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> >&, std::__1::shared_ptr<DB::IBlockInputStream>*) /usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:309:13 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #21 std::__1::__vector_base<std::__1::shared_ptr<DB::IBlockInputStream>, std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> > >::__destruct_at_end(std::__1::shared_ptr<DB::IBlockInputStream>*) /usr/local/bin/../include/c++/v1/vector:450:9 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #22 std::__1::__vector_base<std::__1::shared_ptr<DB::IBlockInputStream>, std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> > >::clear() /usr/local/bin/../include/c++/v1/vector:374:29 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #23 std::__1::__vector_base<std::__1::shared_ptr<DB::IBlockInputStream>, std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> > >::~__vector_base() /usr/local/bin/../include/c++/v1/vector:487:9 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #24 std::__1::vector<std::__1::shared_ptr<DB::IBlockInputStream>, std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> > >::~vector() /usr/local/bin/../include/c++/v1/vector:579:5 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #25 DB::IBlockInputStream::~IBlockInputStream() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/DataStreams/IBlockInputStream.h:111:42 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #26 DB::DM::DMRowKeyFilterBlockInputStream<true>::~DMRowKeyFilterBlockInputStream() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/RowKeyFilter.h:161:7 (gtests_dbms+0xb9d3fc0)
[2022-09-14T03:43:58.482Z]     #27 std::__1::__shared_ptr_emplace<DB::DM::DMRowKeyFilterBlockInputStream<true>, std::__1::allocator<DB::DM::DMRowKeyFilterBlockInputStream<true> > >::__on_zero_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:315:24 (gtests_dbms+0xb9d2f28)
[2022-09-14T03:43:58.482Z]     #28 std::__1::__shared_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177:9 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #29 std::__1::__shared_weak_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219:27 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #30 std::__1::shared_ptr<DB::IBlockInputStream>::~shared_ptr() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959:19 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #31 std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> >::destroy(std::__1::shared_ptr<DB::IBlockInputStream>*) /usr/local/bin/../include/c++/v1/__memory/allocator.h:159:15 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #32 void std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> > >::destroy<std::__1::shared_ptr<DB::IBlockInputStream>, void>(std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> >&, std::__1::shared_ptr<DB::IBlockInputStream>*) /usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:309:13 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #33 std::__1::__vector_base<std::__1::shared_ptr<DB::IBlockInputStream>, std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> > >::__destruct_at_end(std::__1::shared_ptr<DB::IBlockInputStream>*) /usr/local/bin/../include/c++/v1/vector:450:9 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #34 std::__1::__vector_base<std::__1::shared_ptr<DB::IBlockInputStream>, std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> > >::clear() /usr/local/bin/../include/c++/v1/vector:374:29 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #35 std::__1::__vector_base<std::__1::shared_ptr<DB::IBlockInputStream>, std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> > >::~__vector_base() /usr/local/bin/../include/c++/v1/vector:487:9 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #36 std::__1::vector<std::__1::shared_ptr<DB::IBlockInputStream>, std::__1::allocator<std::__1::shared_ptr<DB::IBlockInputStream> > >::~vector() /usr/local/bin/../include/c++/v1/vector:579:5 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.482Z]     #37 DB::IBlockInputStream::~IBlockInputStream() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/DataStreams/IBlockInputStream.h:111:42 (gtests_dbms+0x3c4b2bc)
[2022-09-14T03:43:58.483Z]     #38 DB::DM::DMVersionFilterBlockInputStream<0>::~DMVersionFilterBlockInputStream() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h:81:5 (gtests_dbms+0x3f473de)
[2022-09-14T03:43:58.483Z]     #39 std::__1::__shared_ptr_emplace<DB::DM::DMVersionFilterBlockInputStream<0>, std::__1::allocator<DB::DM::DMVersionFilterBlockInputStream<0> > >::__on_zero_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:315:24 (gtests_dbms+0x3f46a58)
[2022-09-14T03:43:58.483Z]     #40 std::__1::__shared_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:177:9 (gtests_dbms+0xbb12831)
[2022-09-14T03:43:58.483Z]     #41 std::__1::__shared_weak_count::__release_shared() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:219:27 (gtests_dbms+0xbb12831)
[2022-09-14T03:43:58.483Z]     #42 std::__1::shared_ptr<DB::IBlockInputStream>::~shared_ptr() /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:959:19 (gtests_dbms+0xbb12831)
[2022-09-14T03:43:58.483Z]     #43 std::__1::shared_ptr<DB::IBlockInputStream>::operator=(std::__1::shared_ptr<DB::IBlockInputStream>&&) /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:990:5 (gtests_dbms+0xbb12831)
[2022-09-14T03:43:58.483Z]     #44 DB::DM::MergedTask::setStreamFinished(unsigned long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h:121:29 (gtests_dbms+0xbb12831)
[2022-09-14T03:43:58.483Z]     #45 DB::DM::MergedTask::readOneBlock() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp:74:13 (gtests_dbms+0xbb0ebad)
[2022-09-14T03:43:58.483Z]     #46 DB::DM::MergedTask::readBlock() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp:21:12 (gtests_dbms+0xbb0e781)
[2022-09-14T03:43:58.483Z]     #47 DB::DM::SegmentReader::readSegments() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp:108:39 (gtests_dbms+0xbb1a0b2)
[2022-09-14T03:43:58.483Z]     #48 DB::DM::SegmentReader::run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp:152:13 (gtests_dbms+0xbb19a67)
[2022-09-14T03:43:58.483Z]     #49 decltype(*(static_cast<DB::DM::SegmentReader*>(fp0)).*fp()) std::__1::__invoke<void (DB::DM::SegmentReader::*)(), DB::DM::SegmentReader*, void>(void (DB::DM::SegmentReader::*&&)(), DB::DM::SegmentReader*&&) /usr/local/bin/../include/c++/v1/type_traits:3859:1 (gtests_dbms+0xbb1b0b3)
[2022-09-14T03:43:58.483Z]     #50 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::DM::SegmentReader::*)(), DB::DM::SegmentReader*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::DM::SegmentReader::*)(), DB::DM::SegmentReader*>&, std::__1::__tuple_indices<2ul>) /usr/local/bin/../include/c++/v1/thread:280:5 (gtests_dbms+0xbb1b0b3)
[2022-09-14T03:43:58.483Z]     #51 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::DM::SegmentReader::*)(), DB::DM::SegmentReader*> >(void*) /usr/local/bin/../include/c++/v1/thread:291:5 (gtests_dbms+0xbb1b0b3)
[2022-09-14T03:43:58.483Z] 
[2022-09-14T03:43:58.483Z]   Thread T57 'SegmentReader' (tid=11081, running) created by main thread at:
[2022-09-14T03:43:58.483Z]     #0 pthread_create /llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:977:3 (gtests_dbms+0x24ec37d)
[2022-09-14T03:43:58.483Z]     #1 std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) /usr/local/bin/../include/c++/v1/__threading_support:514:10 (gtests_dbms+0xbb19b45)
[2022-09-14T03:43:58.483Z]     #2 std::__1::thread::thread<void (DB::DM::SegmentReader::*)(), DB::DM::SegmentReader*, void>(void (DB::DM::SegmentReader::*&&)(), DB::DM::SegmentReader*&&) /usr/local/bin/../include/c++/v1/thread:307:16 (gtests_dbms+0xbb19b45)
[2022-09-14T03:43:58.483Z]     #3 DB::DM::SegmentReader::SegmentReader(DB::DM::WorkQueue<std::__1::shared_ptr<DB::DM::MergedTask> >&, std::__1::vector<int, std::__1::allocator<int> > const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp:35:13 (gtests_dbms+0xbb1995b)
[2022-09-14T03:43:58.483Z]     #4 std::__1::__unique_if<DB::DM::SegmentReader>::__unique_single std::__1::make_unique<DB::DM::SegmentReader, DB::DM::WorkQueue<std::__1::shared_ptr<DB::DM::MergedTask> >&, std::__1::vector<int, std::__1::allocator<int> > const&>(DB::DM::WorkQueue<std::__1::shared_ptr<DB::DM::MergedTask> >&, std::__1::vector<int, std::__1::allocator<int> > const&) /usr/local/bin/../include/c++/v1/__memory/unique_ptr.h:728:32 (gtests_dbms+0xbb12be6)
[2022-09-14T03:43:58.483Z]     #5 DB::DM::SegmentReaderPool::SegmentReaderPool(int, std::__1::vector<int, std::__1::allocator<int> > const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp:179:27 (gtests_dbms+0xbb12be6)
[2022-09-14T03:43:58.483Z]     #6 std::__1::__unique_if<DB::DM::SegmentReaderPool>::__unique_single std::__1::make_unique<DB::DM::SegmentReaderPool, int&, std::__1::vector<int, std::__1::allocator<int> > const&>(int&, std::__1::vector<int, std::__1::allocator<int> > const&) /usr/local/bin/../include/c++/v1/__memory/unique_ptr.h:728:32 (gtests_dbms+0xbb13848)
[2022-09-14T03:43:58.483Z]     #7 DB::DM::SegmentReaderPoolManager::init(DB::ServerInfo const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp:218:32 (gtests_dbms+0xbb13848)
[2022-09-14T03:43:58.483Z]     #8 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:66:50 (gtests_dbms+0x4327489)
[2022-09-14T03:43:58.484Z] 
[2022-09-14T03:43:58.484Z] SUMMARY: ThreadSanitizer: data race /llvm-project/compiler-rt/lib/tsan/rtl/tsan_new_delete.cpp:126:3 in operator delete(void*)
```

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #5881 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.h [hunk 1]
```diff
@@ -66,6 +66,10 @@ class SegmentReaderPoolManager
     void addTask(MergedTaskPtr && task);
     bool isSegmentReader() const;
 
+    // Explicitly, release reader_pools and reader_ids.
+    // The destructor will do this automatically.
+    // This function is for unittests.
+    void stop();
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.h:72]: should we also call this method in Server.cpp?
https://github.com/pingcap/tiflash/blob/master/dbms/src/Server/Server.cpp#L1219-L1228

**Review by breezewish — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]
