### PR TITLE
Fix some fail cases when enable TASN

### LINKED ISSUE #5085: Some of UTs failed when enable TASN.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. when build with TASN + gcc
some of error from build
```
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:2221:108: sorry, unimplemented: non-trivial designated initializers not supported
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:2221:108: sorry, unimplemented: non-trivial designated initializers not supported
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:2222:107: sorry, unimplemented: non-trivial designated initializers not supported
     PageEntryV3 entry_5_v1{.file_id = file_id2, .size = 255, .tag = 0, .offset = 0x100, .checksum = 0x4567};
                                                                                                           ^
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:2222:107: sorry, unimplemented: non-trivial designated initializers not supported
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:2222:107: sorry, unimplemented: non-trivial designated initializers not supported
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:2223:107: sorry, unimplemented: non-trivial designated initializers not supported
     PageEntryV3 entry_5_v2{.file_id = file_id2, .size = 255, .tag = 0, .offset = 0x400, .checksum = 0x4567};
                                                                                                           ^
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:2223:107: sorry, unimplemented: non-trivial designated initializers not supported
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:2223:107: sorry, unimplemented: non-trivial designated initializers not supported
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp: In member function ‘virtual void DB::PS::V3::tests::PageDirectoryGCTest_CleanAfterDecreaseRef_Test::TestBody()’:
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:2278:101: sorry, unimplemented: non-trivial designated initializers not supported
     PageEntryV3 entry_50_1{.file_id = 1, .size = 7890, .tag = 0, .offset = 0x123, .checksum = 0x4567};
                                                                                                     ^
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:2278:101: sorry, unimplemented: non-trivial designated initializers not supported
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:2278:101: sorry, unimplemented: non-trivial designated initializers not supported
tics-dev/dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:2279:101: sorry, unimplemented: non-trivial designated initializers not supported
     PageEntryV3 entry_50_2{.file_id = 2, .size = 7890, .tag = 0, .offset = 0x123, .checksum = 0x4567};
                                                                                                     ^
....
tics-dev/dbms/src/TestUtils/ColumnsToTiPBExpr.cpp: In function ‘void DB::tests::{anonymous}::columnToTiPBExpr(tipb::Expr*, DB::ColumnWithTypeAndName, size_t)’:
tics-dev/dbms/src/TestUtils/ColumnsToTiPBExpr.cpp:38:36: error: unused variable ‘null_map’ [-Werror=unused-variable]
                 auto [col, null_map] = removeNullable(column.column.get());
                                    ^
tics-dev/dbms/src/TestUtils/ColumnsToTiPBExpr.cpp: In function ‘void DB::tests::{anonymous}::columnsToTiPBExprForTiDBCast(tipb::Expr*, const String&, const ColumnNumbers&, const ColumnsWithTypeAndName&, const TiDB::ITiDBCollator* const&)’:
tics-dev/dbms/src/TestUtils/ColumnsToTiPBExpr.cpp:99:36: error: unused variable ‘null_map’ [-Werror=unused-variable]
                 auto [col, null_map] = removeNullable(type_column.column.get());
                                    ^
...
```
2. some of test case will be failed
```
[2022-06-07T18:12:59.993Z] FAILED TESTS (4/1272):

[2022-06-07T18:12:59.993Z]     2513 ms: /tiflash/gtests_dbms DynamicThreadPoolTest.testAutoExpanding
[2022-06-07T18:12:59.993Z]     2633 ms: /tiflash/gtests_dbms DynamicThreadPoolTest.testDynamicShrink
[2022-06-07T18:12:59.993Z]     2499 ms: /tiflash/gtests_dbms DynamicThreadPoolTest.testTaskDestruct
[2022-06-07T18:12:59.993Z]     2280 ms: /tiflash/gtests_dbms StorageDeltaMergeTest.RestoreAfterClearData

```

### 4. What is your TiFlash version? (Required)

`master`

### PR DESCRIPTION
**Pull request by jiaqizho**
### What problem does this PR solve?

Issue Number: close #5085 

Problem Summary:

```
[2022-06-07T18:08:51.401Z] ==================
[2022-06-07T18:08:51.401Z] WARNING: ThreadSanitizer: data race (pid=36394)
[2022-06-07T18:08:51.401Z]   Read of size 8 at 0x000011762fb8 by thread T26:
[2022-06-07T18:08:51.401Z]     #0 DB::DM::StoragePool::newDataPageIdForDTFile(DB::StableDiskDelegator&, char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/StoragePool.cpp:626:9 (gtests_dbms+0xc57ce94)
[2022-06-07T18:08:51.401Z]     #1 DB::DM::createNewStable(DB::DM::DMContext&, std::__1::shared_ptr<std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > > const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, unsigned long, DB::DM::WriteBatches&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/Segment.cpp:163:45 (gtests_dbms+0xc51d687)
[2022-06-07T18:08:51.401Z]     #2 DB::DM::Segment::prepareSplitPhysical(DB::DM::DMContext&, std::__1::shared_ptr<std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > > const&, std::__1::shared_ptr<DB::DM::SegmentSnapshot> const&, DB::DM::WriteBatches&) const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/Segment.cpp:1031:25 (gtests_dbms+0xc52d9de)
[2022-06-07T18:08:51.401Z]     #3 DB::DM::Segment::prepareSplit(DB::DM::DMContext&, std::__1::shared_ptr<std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > > const&, std::__1::shared_ptr<DB::DM::SegmentSnapshot> const&, DB::DM::WriteBatches&) const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/Segment.cpp:872:16 (gtests_dbms+0xc526476)
[2022-06-07T18:08:51.402Z]     #4 DB::DM::DeltaMergeStore::segmentSplit(DB::DM::DMContext&, std::__1::shared_ptr<DB::DM::Segment> const&, bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1895:36 (gtests_dbms+0xc4e9850)
[2022-06-07T18:08:51.402Z]     #5 DB::DM::DeltaMergeStore::handleBackgroundTask(bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1590:37 (gtests_dbms+0xc4e80bf)
[2022-06-07T18:08:51.402Z]     #6 DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:345:90 (gtests_dbms+0xc4f6cb8)
[2022-06-07T18:08:51.402Z]     #7 decltype(static_cast<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65&>(fp)()) std::__1::__invoke<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65&>(DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0xc4f6cb8)
[2022-06-07T18:08:51.402Z]     #8 bool std::__1::__invoke_void_return_wrapper<bool, false>::__call<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65&>(DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65&) /usr/local/bin/../include/c++/v1/__functional/invoke.h:30:16 (gtests_dbms+0xc4f6cb8)
[2022-06-07T18:08:51.402Z]     #9 std::__1::__function::__alloc_func<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65, std::__1::allocator<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65>, bool ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:171:16 (gtests_dbms+0xc4f6cb8)
[2022-06-07T18:08:51.402Z]     #10 std::__1::__function::__func<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65, std::__1::allocator<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65>, bool ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:345:12 (gtests_dbms+0xc4f6cb8)
[2022-06-07T18:08:51.402Z]     #11 std::__1::__function::__value_func<bool ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:498:16 (gtests_dbms+0xc3c6c4a)
[2022-06-07T18:08:51.402Z]     #12 std::__1::function<bool ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:1175:12 (gtests_dbms+0xc3c6c4a)
[2022-06-07T18:08:51.402Z]     #13 DB::BackgroundProcessingPool::threadFunction() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/BackgroundProcessingPool.cpp:233:33 (gtests_dbms+0xc3c6c4a)
[2022-06-07T18:08:51.402Z]     #14 DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/BackgroundProcessingPool.cpp:94:39 (gtests_dbms+0xc3c77f0)
[2022-06-07T18:08:51.402Z]     #15 decltype(static_cast<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2>(fp)()) std::__1::__invoke<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2>(DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2&&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0xc3c77f0)
[2022-06-07T18:08:51.402Z]     #16 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2>&, std::__1::__tuple_indices<>) /usr/local/bin/../include/c++/v1/thread:280:5 (gtests_dbms+0xc3c77f0)
[2022-06-07T18:08:51.402Z]     #17 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2> >(void*) /usr/local/bin/../include/c++/v1/thread:291:5 (gtests_dbms+0xc3c77f0)
[2022-06-07T18:08:51.402Z] 
[2022-06-07T18:08:51.402Z]   Previous write of size 8 at 0x000011762fb8 by thread T19:
[2022-06-07T18:08:51.402Z]     #0 DB::DM::StoragePool::newDataPageIdForDTFile(DB::StableDiskDelegator&, char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/StoragePool.cpp:626:9 (gtests_dbms+0xc57cee9)
[2022-06-07T18:08:51.402Z]     #1 DB::DM::createNewStable(DB::DM::DMContext&, std::__1::shared_ptr<std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > > const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, unsigned long, DB::DM::WriteBatches&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/Segment.cpp:163:45 (gtests_dbms+0xc51d687)
[2022-06-07T18:08:51.402Z]     #2 DB::DM::Segment::prepareSplitPhysical(DB::DM::DMContext&, std::__1::shared_ptr<std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > > const&, std::__1::shared_ptr<DB::DM::SegmentSnapshot> const&, DB::DM::WriteBatches&) const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/Segment.cpp:1031:25 (gtests_dbms+0xc52d9de)
[2022-06-07T18:08:51.403Z]     #3 DB::DM::Segment::prepareSplit(DB::DM::DMContext&, std::__1::shared_ptr<std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > > const&, std::__1::shared_ptr<DB::DM::SegmentSnapshot> const&, DB::DM::WriteBatches&) const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/Segment.cpp:872:16 (gtests_dbms+0xc526476)
[2022-06-07T18:08:51.403Z]     #4 DB::DM::DeltaMergeStore::segmentSplit(DB::DM::DMContext&, std::__1::shared_ptr<DB::DM::Segment> const&, bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1895:36 (gtests_dbms+0xc4e9850)
[2022-06-07T18:08:51.403Z]     #5 DB::DM::DeltaMergeStore::handleBackgroundTask(bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1590:37 (gtests_dbms+0xc4e80bf)
[2022-06-07T18:08:51.403Z]     #6 DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:345:90 (gtests_dbms+0xc4f6cb8)
[2022-06-07T18:08:51.403Z]     #7 decltype(static_cast<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65&>(fp)()) std::__1::__invoke<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65&>(DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0xc4f6cb8)
[2022-06-07T18:08:51.403Z]     #8 bool std::__1::__invoke_void_return_wrapper<bool, false>::__call<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65&>(DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65&) /usr/local/bin/../include/c++/v1/__functional/invoke.h:30:16 (gtests_dbms+0xc4f6cb8)
[2022-06-07T18:08:51.403Z]     #9 std::__1::__function::__alloc_func<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65, std::__1::allocator<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65>, bool ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:171:16 (gtests_dbms+0xc4f6cb8)
[2022-06-07T18:08:51.403Z]     #10 std::__1::__function::__func<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65, std::__1::allocator<DB::DM::DeltaMergeStore::setUpBackgroundTask(std::__1::shared_ptr<DB::DM::DMContext> const&)::$_65>, bool ()>::operator()() /usr/local/bin/../include/c++/v1/__functional/function.h:345:12 (gtests_dbms+0xc4f6cb8)
[2022-06-07T18:08:51.403Z]     #11 std::__1::__function::__value_func<bool ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:498:16 (gtests_dbms+0xc3c6c4a)
[2022-06-07T18:08:51.403Z]     #12 std::__1::function<bool ()>::operator()() const /usr/local/bin/../include/c++/v1/__functional/function.h:1175:12 (gtests_dbms+0xc3c6c4a)
[2022-06-07T18:08:51.403Z]     #13 DB::BackgroundProcessingPool::threadFunction() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/BackgroundProcessingPool.cpp:233:33 (gtests_dbms+0xc3c6c4a)
[2022-06-07T18:08:51.403Z]     #14 DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/BackgroundProcessingPool.cpp:94:39 (gtests_dbms+0xc3c77f0)
[2022-06-07T18:08:51.403Z]     #15 decltype(static_cast<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2>(fp)()) std::__1::__invoke<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2>(DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2&&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0xc3c77f0)
[2022-06-07T18:08:51.403Z]     #16 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2>&, std::__1::__tuple_indices<>) /usr/local/bin/../include/c++/v1/thread:280:5 (gtests_dbms+0xc3c77f0)
[2022-06-07T18:08:51.403Z]     #17 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2> >(void*) /usr/local/bin/../include/c++/v1/thread:291:5 (gtests_dbms+0xc3c77f0)
[2022-06-07T18:08:51.403Z] 
[2022-06-07T18:08:51.403Z]   Location is global 'DB::DM::StoragePool::newDataPageIdForDTFile(DB::StableDiskDelegator&, char const*)::fail_point_called' of size 8 at 0x000011762fb8 (gtests_dbms+0x000011762fb8)
[2022-06-07T18:08:51.403Z] 
```
### What is changed and how it works?
- Fix TASN build
- Fix broken ut in TASN

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/DeltaMerge/StoragePool.cpp [hunk 1]
```diff
@@ -624,6 +624,7 @@ PageId StoragePool::newDataPageIdForDTFile(StableDiskDelegator & delegator, cons
 
         auto existed_path = delegator.getDTFilePath(dtfile_id, /*throw_on_not_exist=*/false);
         fiu_do_on(FailPoints::force_set_dtfile_exist_when_acquire_id, {
+            std::lock_guard lock_for_fail_point(mutex_for_fail_point);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/StoragePool.cpp:627]: don't need to add a lock_guard to StoragePool, I think just make `fail_point_called` to be `static atomic<size_t> fail_point_called` is ok

Comment (jiaqizho) [reply dbms/src/Storages/DeltaMerge/StoragePool.cpp]: done

File: dbms/src/Flash/Management/tests/gtest_manual_compact.cpp [hunk 2]
```diff
@@ -117,7 +117,7 @@ class BasicManualCompactTest
 
     DM::tests::DMTestEnv::PkType pk_type;
 
-    [[maybe_unused]] Poco::Logger * log;
+    Poco::Logger * log;
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Management/tests/gtest_manual_compact.cpp:120]: Use `MAYBE_UNUSED_MEMBER` or it may get error under mac os. https://github.com/pingcap/tiflash/pull/4700/files
Or just remove this variable since we don't need it?

File: dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp [hunk 3]
```diff
@@ -3608,7 +3608,7 @@ class DeltaMergeStoreMergeDeltaBySegmentTest
     UInt64 ps_ver;
     DMTestEnv::PkType pk_type;
 
-    [[maybe_unused]] Poco::Logger * log;
+    Poco::Logger * log;
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp:3611]: ditto

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Review by CalvinNeo — APPROVED** [review]
lgtm
