### PR TITLE
Skip read `regenerate_schema_map` is not present

### LINKED ISSUE #6580: Invalid access: Can not convert empty value
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

daily run window function and the failed sql is  `select i, i, row_number()  over w from window_function_0 window w as (partition by i order by id, i) order by 1, 2, 3`, the full error info is `Error 1105: other error for mpp stream: From MPP<query:<query_ts:0, local_query_id:0, server_id:0, start_ts:438529181194125313>,task_id:1>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Invalid access: Can not convert empty value., e.what() = Invalid access`.

### PR DESCRIPTION
**Pull request by CalvinNeo**
Signed-off-by: CalvinNeo <calvinneo1995@gmail.com>

### What problem does this PR solve?

Issue Number: close #6580

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]

File: dbms/src/TiDB/Schema/SchemaGetter.cpp [hunk 1]
```diff
@@ -172,7 +172,13 @@ void SchemaDiff::deserialize(const String & data)
...
         old_schema_id = obj->getValue<Int64>("old_schema_id");
 
-        regenerate_schema_map = obj->getValue<bool>("regenerate_schema_map");
+        if (obj->has("regenerate_schema_map"))
+        {
+            regenerate_schema_map = obj->getValue<bool>("regenerate_schema_map");
+        }
+
+        // Note If you want to add new fields here, please firstly check if it is present.
+        // Otherwise it will break when doing upgrading test.
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/SchemaGetter.cpp:181]: We'd better add a ut for parsing JSON string without "regenerate_schema_map". And it can avoid others adding fields without checking field existence.

File: dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp [hunk 2]
```diff
@@ -179,6 +178,14 @@ class SchemaSyncTest : public ::testing::Test
     Context & global_ctx;
 };
 
+TEST_F(SchemaSyncTest, SchemaDiff)
+try
+{
+    SchemaDiff diff;
+    std::string data = "{\"version\":40,\"type\":31,\"schema_id\":69,\"table_id\":71,\"old_table_id\":0,\"old_schema_id\":0,\"affected_options\":null}";
+    diff.deserialize(data);
+}
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp:187]:
```suggestion
}
CATCH
```

File: dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp [hunk 3]
```diff
@@ -179,6 +178,14 @@ class SchemaSyncTest : public ::testing::Test
     Context & global_ctx;
 };
 
+TEST_F(SchemaSyncTest, SchemaDiff)
+try
+{
+    SchemaDiff diff;
+    std::string data = "{\"version\":40,\"type\":31,\"schema_id\":69,\"table_id\":71,\"old_table_id\":0,\"old_schema_id\":0,\"affected_options\":null}";
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp:185]:
```suggestion
    // Note that we should keep backward compatibility for parsing old version schema diff.
    // Or it will lead to exception thrown after upgraded.
    std::string data = "{\"version\":40,\"type\":31,\"schema_id\":69,\"table_id\":71,\"old_table_id\":0,\"old_schema_id\":0,\"affected_options\":null}";
```

File: dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp [hunk 4]
```diff
@@ -179,6 +178,14 @@ class SchemaSyncTest : public ::testing::Test
...
+    diff.deserialize(data);
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp:186]:
```suggestion
    ASSERT_NO_THROW(diff.deserialize(data));
```

**Review by JaySon-Huang — APPROVED** [review]
lgtm
