### PR TITLE
Revert "Use safe_ts to determine whether the peer's data synchronizat…

### LINKED ISSUE #5905: TiFlash OOM when region count more than 700k per TiFlash node
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Split region in an empty table, make the number of regions more than 700k.

### 2. What did you expect to see? (Required)
TiFlash status is `Up`.
### 3. What did you see instead (Required)
TiFlash OOM.
image
image
image
image
tiflash 51_78

### 4. What is your TiFlash version? (Required)
f07fe50d19db40ee3244665213226d94288ab853

introduced by https://github.com/pingcap/tiflash/pull/5866

### PR DESCRIPTION
**Pull request by hehechen**
…ion progress is far behind the leader. (#5866)"

This reverts commit f07fe50d19db40ee3244665213226d94288ab853.

### What problem does this PR solve?

Issue Number: close #5905

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/Transaction/ProxyFFI.h [hunk 1]
```diff
@@ -176,7 +175,6 @@ inline EngineStoreServerHelper GetEngineStoreServerHelper(
         .fn_get_config = GetConfig,
         .fn_set_store = SetStore,
         .fn_set_pb_msg_by_bytes = SetPBMsByBytes,
-        .fn_handle_safe_ts_update = HandleSafeTSUpdate,
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Transaction/ProxyFFI.h:179]: should we explicitly set it to be nullptr?

**Review by JaySon-Huang — APPROVED** [review]
lgtm with a comment

File: dbms/src/Storages/Transaction/ProxyFFI.h (hunk 1 above)
Comment (CalvinNeo) [reply dbms/src/Storages/Transaction/ProxyFFI.h:179]: Better be a dummy function in case `fn_handle_safe_ts_update.is_some()` will panic in proxy.

File: dbms/src/Storages/Transaction/ProxyFFI.cpp [hunk 2]
```diff
@@ -560,11 +560,8 @@ raft_serverpb::RegionLocalState TiFlashRaftProxyHelper::getRegionLocalState(uint
     return state;
 }
 
-void HandleSafeTSUpdate(EngineStoreServerWrap * server, uint64_t region_id, uint64_t self_safe_ts, uint64_t leader_safe_ts)
+// just a dummy function to avoid poxy fn_handle_safe_ts_update.is_some() panic.
```
Comment (CalvinNeo) [inline dbms/src/Storages/Transaction/ProxyFFI.cpp:563]:
```suggestion
// just a dummy function to avoid proxy fn_handle_safe_ts_update.is_some() panic.
```

**Review by CalvinNeo — APPROVED** [review]
lgtm with a typo to fix
