### PR TITLE
fix In ScalarFunc in RoughSetFilter

### LINKED ISSUE #8631: In rough set filter works occasionally incorrectly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
mysql> create table t (a int, b int);
mysql> insert into t values(10,30);
mysql> insert into t values(50,60);
mysql> alter table t set tiflash replica 1;
mysql> set session tidb_isolation_read_engines='tiflash';
mysql> select * from t where not a not in (0, cast(+ a as signed));

### 2. What did you expect to see? (Required)
Always return 2 results:
+------+------+
| a    | b    |
+------+------+
|   10 |   30 |
|   50 |   60 |
+------+------+

### 3. What did you see instead (Required)
After try about 20-30 times, it returns empty result set, and then always return empty set.
+----------------------------+---------+---------+--------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------+-----------+------+
| id                         | estRows | actRows | task         | access object | execution info                                                                                                                                                                                                                                                                                                                                                                                                          | operator info                                            | memory    | disk |
+----------------------------+---------+---------+--------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------+-----------+------+
| TableReader_13             | 1.60    | 0       | root         |               | time:7.99ms, loops:1, RU:0.000000, cop_task: {num: 1, max: 0s, proc_keys: 0, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                                | MppVersion: 2, data:ExchangeSender_12                    | 305 Bytes | N/A  |
| └─ExchangeSender_12        | 1.60    | 0       | mpp[tiflash] |               | tiflash_task:{time:6.75ms, loops:0, threads:8}                                                                                                                                                                                                                                                                                                                                                                          | ExchangeType: PassThrough                                | N/A       | N/A  |
|   └─Selection_11           | 1.60    | 0       | mpp[tiflash] |               | tiflash_task:{time:6.75ms, loops:0, threads:8}                                                                                                                                                                                                                                                                                                                                                                          | in(test.t.a, 0, cast(test.t.a, bigint(22) BINARY))       | N/A       | N/A  |
|     └─TableFullScan_10     | 2.00    | 0       | mpp[tiflash] | table:t       | tiflash_task:{time:6.75ms, loops:0, threads:8}, tiflash_scan:{dtfile:{total_scanned_packs:0, total_skipped_packs:1, total_scanned_rows:0, total_skipped_rows:2, total_rs_index_check_time: 0ms, total_read_time: 0ms, total_disagg_read_cache_hit_size: 0, total_disagg_read_cache_miss_size: 0}, total_create_snapshot_time: 0ms, total_local_region_num: 1, total_remote_region_num: 0, total_learner_read_time: 0ms} | pushed down filter:empty, keep order:false, stats:pseudo | N/A       | N/A  |
+----------------------------+---------+---------+--------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------+-----------+------+

### 4. What is your TiFlash version? (Required)
Git hash: ce42814e493e62731172774d783c294c76de3afe

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #8631

Problem Summary:

### What is changed and how it works?

reject all children which are not `ColumnRef` or `Literal`.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the wrong result when executing queries with a filter like `ColumnRef in (Literal, Func...)`
```

### CODE REVIEW

File: dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp [hunk 1]
```diff
@@ -178,6 +178,12 @@ inline RSOperatorPtr parseTiCompareExpr( //
             }
             values.push_back(value);
         }
+        else
+        {
+            return createUnsupported(
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp:183]:
```suggestion
            // Nested column like `cast(a as signed)` is not supported
            return createUnsupported(
```

Comment (JaySon-Huang) [reply dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp:183]: And line 199 should be 
```
// For In type, the first child must be ColumnRef
```

**Review by JaySon-Huang — APPROVED** [review]

**Comment by JaySon-Huang** [comment]
Please update the "Release note" to descript what problem it fixes

File: dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp (hunk 1 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp:185]: done

**Comment by JaySon-Huang** [comment]
> fix expression like `ColumnRef in (Literal, Func...)` in rough set filter.

Your release note describes "what codes you changed" but not "what problem you fixed". Suggest using "Fix the wrong result when executing queries with filter `IN CAST(.. AS ..)`"

**Comment by Lloyd-Pottiger** [comment]
> > fix expression like `ColumnRef in (Literal, Func...)` in rough set filter.
> 
> Your release note describes "what codes you changed" but not "what problem you fixed". Suggest using "Fix the wrong result when executing queries with filter `IN CAST(.. AS ..)`"

change to:

Fix the wrong result when executing queries with a filter like `ColumnRef in (Literal, Func...)`
