### PR TITLE
*.: Use String as the common type for Decimal in join when an Exception occurs

### LINKED ISSUE #4519: There is no supertype for types Decimal(65,0), Decimal(20,20) because the least supertype is Decimal(85,20)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
mysql -uroot -P52324 -h172.16.4.97 -D subquery_agg_decimal3000

SELECT    table1 . `col_decimal_65_not_null_key` AS field1 , table2 . `col_decimal_30_10_unsigned_key` AS field2 , table2 . `col_decimal_20_20_unsigned_key` AS field3 FROM ( A AS table1 INNER JOIN B AS table2 ON (( table2 . `col_decimal_65_key` = table1 . `col_decimal_2
    0_20_not_null` ) AND ( table2 . `col_decimal` = table1 . `col_decimal_30_10_key` ) ) ) WHERE ( table1 . `col_decimal_key`  BETWEEN 131 AND ( 131 + 47 ) OR ( table1 . `col_decimal_65_10_key` NOT IN (131, 79, 164, 139) OR table1 . `col_int_key` > 131 AND table1 . `col_int    _key` < ( 131 + 64 ) ) ) OR table1 . `col_decimal_30_not_null` <= -8.16  GROUP BY field1, field2, field3  ORDER BY field1, field2, field3 , table1 . `col_decimal_65_not_null_key`  ;

### 2. What did you expect to see? (Required)
mysql and  tidb+tikv run ok

### 3. What did you see instead (Required)
`ERROR 1105 (HY000) at line 1: other error for mpp stream: DB::Exception: Exchange receiver meet error : DB::Exception: There is no supertype for types Decimal(65,0), Decimal(20,20) because the least supertype is Decimal(85,20)`

### 4. What is your TiFlash version? (Required)
nightly

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #4519

Problem Summary:

### What is changed and how it works?
- Use `String` as the common type for `Decimal` in join when an Exception occurs
- Use `FunctionFormatDecimal` to make different decimal strings have the same format.
  ```
  `abc.def` ==> 'fed.cba'
  `-abc.def` ==> '-fed.cba'
  `abc.def0000` ==> 'fed.cba'
  `-abc.def0000` ==> '-fed.cba'
  `abc.de0000f` ==> 'f0000ed.cba'
  `-abc.de0000f` ==> '-f0000ed.cba'
  `abc.de0000f0000` ==> 'f0000ed.cba'
  `-abc.de0000f0000` ==> '-f0000ed.cba'
  `0.def` ==> 'fed.'
  `-0.def` ==> '-fed.'
  `0.def0000` ==> 'fed.'
  `-0.def0000` ==> '-fed.'
  `0.de0000f` ==> 'f0000ed.'
  `-0.de0000f` ==> '-f0000ed.'
  `0.de0000f0000` ==> 'f0000ed.'
  `-0.de0000f0000` ==> '-f0000ed.'
  `abc` ==> 'cba'
  `-abc` ==> '-cba'
  `abc.00` ==> 'cba'
  `-abc.00` ==> '-cba'
  `abc0000` ==> '0000cba'
  `-abc0000` ==> '-0000cba'
  `abc0000.00` ==> '0000cba'
  `-abc0000.00` ==> '-0000cba'
  `0` ==> ''
  `0.00` ==> ''
  ```

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix the bug that throw Exception `There is no supertype for types Decimal(65,0), Decimal(20,20) because the least supertype is Decimal(85,20)` in join
```

### CODE REVIEW

File: dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp [hunk 1]
```diff
@@ -939,11 +939,16 @@ std::pair<bool, Names> DAGExpressionAnalyzer::buildJoinKey(
...
+        const auto & join_key_type = join_key_types[i];
+        if (!removeNullable(current_type)->equals(*removeNullable(join_key_type.key_type)))
         {
             /// need to convert to key type
-            key_name = appendCast(key_types[i], actions, key_name);
+            key_name = appendCast(join_key_type.key_type, actions, key_name);
             has_actions = true;
+            if (join_key_type.is_incompatible_decimal)
+            {
+                key_name = applyFunction("formatDecimalStr", {key_name}, actions, nullptr);
```
Comment (windtalker) [inline dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp:950]: Since we always have to add a new function to do the format, why not just add a function to format from deciml directly instead of convert decimal to string and format the result string?

Comment (SeaRise) [reply dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp:950]: you're right, let me try :)

Comment (SeaRise) [reply dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp]: done

File: dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp [hunk 2]
```diff
@@ -99,32 +107,58 @@ std::pair<ASTTableJoin::Kind, size_t> getJoinKindAndBuildSideIndex(const tipb::J
...
+    }
+    catch (DB::Exception & e)
+    {
+        if (e.code() == ErrorCodes::NO_COMMON_TYPE
+            && removeNullable(left_type)->isDecimal()
+            && removeNullable(right_type)->isDecimal())
+        {
+            // fix https://github.com/pingcap/tiflash/issues/4519
+            // String is the common type for all types, it is always safe to choose String.
+            // But then we need to use `FormatDecimalStrImpl` to remove the `0` and `.` at the end of the string.
```
Comment (SeaRise) [inline dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp:124]:
```suggestion
            // But then we need to use `FunctionFormatDecimal` to format decimal.
```

File: dbms/src/Functions/FunctionsString.cpp [hunk 3]
```diff
@@ -5782,6 +5781,161 @@ class FunctionElt : public IFunction
...
+        auto & data = col->getData();
+        size_t size = data.size();
+        res_data.resize(size * (precision + 3));
+        res_offsets.resize(size);
+
+        ColumnString::Offset cur_offset = 0;
+        for (size_t i = 0; i < size; ++i)
+        {
+            const auto & decimal = data[i];
+            Int256 value = decimal.value;
```
Comment (windtalker) [inline dbms/src/Functions/FunctionsString.cpp:5894]: Can we use more specific Integer type here? Int256 has very bad performance compare to Int128/Int64/Int32

Comment (SeaRise) [reply dbms/src/Functions/FunctionsString.cpp]: ok, updated.

File: dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp [hunk 4]
```diff
@@ -99,32 +107,58 @@ std::pair<ASTTableJoin::Kind, size_t> getJoinKindAndBuildSideIndex(const tipb::J
...
 {
     TiDB::TiDBCollators collators;
     size_t join_key_size = join_key_types.size();
     if (join.probe_types_size() == static_cast<int>(join_key_size) && join.build_types_size() == join.probe_types_size())
         for (size_t i = 0; i < join_key_size; ++i)
         {
-            if (removeNullable(join_key_types[i])->isString())
+            if (removeNullable(join_key_types[i].key_type)->isString())
             {
                 if (unlikely(join.probe_types(i).collate() != join.build_types(i).collate()))
```
Comment (windtalker) [inline dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp:163]: Don't need to check the collate if the original type is Decimal

File: dbms/src/Functions/FunctionsString.cpp [hunk 5]
```diff
@@ -5782,6 +5781,176 @@ class FunctionElt : public IFunction
...
+                    add_dot = true;
+                    break;
+                }
+            }
+            for (; value > 0 && scale_i < scale; ++scale_i)
+            {
+                int d = static_cast<int>(value % 10);
+                value /= 10;
+                res_data[cur_offset++] = d + '0';
+                add_dot = true;
```
Comment (windtalker) [inline dbms/src/Functions/FunctionsString.cpp:5938]: Looks like there is no need to set `add_dot` to true here.

File: dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp (hunk 4 above)
Comment (SeaRise) [reply dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp:164]: ok, updated.

File: dbms/src/Functions/FunctionsString.cpp (hunk 5 above)
Comment (SeaRise) [reply dbms/src/Functions/FunctionsString.cpp]: good point!
updated.

**Review by windtalker — APPROVED** [review]
LGTM

**Review by guo-shaoge — APPROVED** [review]
