### PR TITLE
fix tiflash resource control low token signal miss

### LINKED ISSUE #10137: tiflash resource control triggers unexpected throttling for periodically high-traffic workload
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Image

As shown in the image above, the token usage rate (i.e., avg_speed) exhibits periodic spikes followed by gradual declines, indicating that users periodically generate high-load demands for tokens.

However, we have many pending pipeline tasks during the above spike, which means the user has been throttled by resource control. But the `RU_PER_SEC` is very large, (in this cause, user set it as 56000), which means we should not throttle the user workload.

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #10137

Problem Summary:
before
1. low token notify doesn't work becuase `wait_for` ignore low token signal
2. 5s for computing avg speed is too long, which may not reflect the latest ru speed.
3. acquire token from GAC every 5s

after:
1. `mainLoop` thread will compute ru speed every 1s
2. `requestGACLoop` thread is dedicated to sending gac thread
4. only acquire token from GAC when got low token signal
5. change `min_wait_dura_ms ` from 100ms to 10ms.

### What is changed and how it works?

```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. create tidb cluster with 2 tiflash(16c)
6. load tpch50g workload
7. run the following scripts: https://github.com/guo-shaoge/tiflash_resource_control_test_tool, detailed test report is internal
    1. [high.change.sh](https://github.com/guo-shaoge/tiflash_resource_control_test_tool/blob/master/high.change.sh)
        
        image

    4. [periodically.change.sh](https://github.com/guo-shaoge/tiflash_resource_control_test_tool/blob/master/periodically.change.sh) 
    
        image

    6. [priority.change.sh](https://github.com/guo-shaoge/tiflash_resource_control_test_tool/blob/master/priority.change.sh)
        image

    8. [burstable.change.sh](https://github.com/guo-shaoge/tiflash_resource_control_test_tool/blob/master/burstable.change.sh)
        image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix tiflash resource control low token signal miss
```

### CODE REVIEW

File: dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.cpp [hunk 1]
```diff
@@ -114,22 +114,12 @@ bool ResourceControlQueue<NestedTaskQueueType>::take(TaskPtr & task)
         if unlikely (updateResourceGroupInfosWithoutLock())
             continue;
 
-        UInt64 wait_dura = LocalAdmissionController::DEFAULT_FETCH_GAC_INTERVAL_MS;
+        UInt64 wait_dura = LocalAdmissionController::DEFAULT_MAX_EST_WAIT_DURATION.count();
```
Comment (guo-shaoge) [inline dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.cpp:117]: todo: throw error throttled when est wait dura too long

**Review by solotzg — APPROVED** [review]

File: dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp [hunk 2]
```diff
@@ -363,11 +642,23 @@ std::vector<std::string> LocalAdmissionController::handleTokenBucketsResp(
         }
 
         int64_t trickle_ms = granted_token_bucket.trickle_time_ms();
-        RUNTIME_CHECK(trickle_ms >= 0);
+        RUNTIME_CHECK_MSG(trickle_ms >= 0, "{}, expect trickle_ms >= 0, but got: {}", err_msg, trickle_ms);
```
Comment (JaySon-Huang) [inline dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp:645]: There could be multiple resource group in one `TokenBucketsResponse`, throwing an exception when handling one resource group will let tiflash can not handle the resp of other resource group.
What about just log an error for this resource group and continue handle the next resource group?

File: dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp [hunk 3]
```diff
@@ -363,11 +642,23 @@ std::vector<std::string> LocalAdmissionController::handleTokenBucketsResp(
...
+        const auto now = SteadyClock::now();
 
+        double added_tokens = granted_token_bucket.granted_tokens().tokens();
+        RUNTIME_CHECK_MSG(added_tokens >= 0, "{}, expect added_tokens >= 0, but got: {}", err_msg, added_tokens);
+        const auto trickle_left_tokens = resource_group->getTrickleLeftTokens(now);
+        RUNTIME_CHECK_MSG(
+            trickle_left_tokens >= 0,
+            "{}, expect trickle_left_tokens >= 0, but got: {}",
+            err_msg,
+            trickle_left_tokens);
```
Comment (JaySon-Huang) [inline dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp:656]: ditto

File: dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp [hunk 4]
```diff
@@ -376,44 +667,58 @@ std::vector<std::string> LocalAdmissionController::handleTokenBucketsResp(
             GET_RESOURCE_GROUP_METRIC(tiflash_resource_group, type_gac_resp_capacity, name).Set(capacity);
 
         // fill_rate should never be setted.
-        RUNTIME_CHECK(granted_token_bucket.granted_tokens().settings().fill_rate() == 0);
+        {
+            const auto fill_rate = granted_token_bucket.granted_tokens().settings().fill_rate();
+            RUNTIME_CHECK_MSG(fill_rate == 0, "{}, expect fill_rate is 0, but got: {}", err_msg, fill_rate);
```
Comment (JaySon-Huang) [inline dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp:672]: ditto

**Review by JaySon-Huang — COMMENTED** [review]
There could be multiple resource group in one `TokenBucketsResponse`, throwing an exception when handling one resource group will let tiflash can not handle the remaining `one_resp` on `resp.responses()`.
What about just log an error for this resource group and continue handle the next resource group?

**Comment by JaySon-Huang** [comment]
And I've filed a PR with small code refine for better trobuleshooting https://github.com/guo-shaoge/tiflash/pull/1

**Review by JaySon-Huang — APPROVED** [review]
LGTM
