### PR TITLE
Test: support qualified column reference in writing tests

### LINKED ISSUE #5510: Failed to use qualified format to reference table column in executor test framework
## Bug Report

Current executor test framework fails to support qualified column reference. ex. "select t.a from t;"

### 1. Minimal reproduce step (Required)

By writing a gtest case

```cpp
TEST_F(ExecutorTestRunner, Filter)
try
{
    context.addMockTable({"test_db", "test_table"},
                            {{"s1", TiDB::TP::TypeString}, {"s2", TiDB::TP::TypeString}},
                            {toNullableVec<String>("s1", {"banana", {}, "banana"}),
                            toNullableVec<String>("s2", {"apple", {}, "banana"})});

    auto request = context
                       .scan("test_db", "test_table")
                       .filter(eq(col("test_table.s1"), col("test_table.s2")))
                       .build(context);
    {
        ASSERT_COLUMNS_EQ_R(executeStreams(request),
                            createColumns({toNullableVec<String>({"banana"}),
                                           toNullableVec<String>({"banana"})}));
    }
}
CATCH
```

### 2. What did you expect to see? (Required)

test passed

### 3. What did you see instead (Required)

program threw exception

```shell
Code: 16. DB::Exception: No such column test_table.s1

Stack trace:

     0x110e04b00        StackTrace::StackTrace() [gtests_dbms+4497509120]
                        dbms/src/Common/StackTrace.cpp:23
     0x110e04b3c        StackTrace::StackTrace() [gtests_dbms+4497509180]
                        dbms/src/Common/StackTrace.cpp:22
     0x104ce5f30        DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [gtests_dbms+4295008048]
                        dbms/src/Common/Exception.h:32
     0x104ce5088        DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [gtests_dbms+4295004296]
                        dbms/src/Common/Exception.h:34
     0x10db25a9c        DB::(anonymous namespace)::compileExpr(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, TiDB::ColumnInfo>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, TiDB::ColumnInfo> > > const&, std::__1::shared_ptr<DB::IAST>) [gtests_dbms+4444166812]
                        dbms/src/Debug/astToExecutor.cpp:613
     0x10db263b8        DB::(anonymous namespace)::compileExpr(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, TiDB::ColumnInfo>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, TiDB::ColumnInfo> > > const&, std::__1::shared_ptr<DB::IAST>) [gtests_dbms+4444169144]
                        dbms/src/Debug/astToExecutor.cpp:731
     0x10db254f0        DB::(anonymous namespace)::compileFilter(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, TiDB::ColumnInfo>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, TiDB::ColumnInfo> > > const&, std::__1::shared_ptr<DB::IAST>, std::__1::vector<std::__1::shared_ptr<DB::IAST>, std::__1::allocator<std::__1::shared_ptr<DB::IAST> > >&) [gtests_dbms+4444165360]
                        dbms/src/Debug/astToExecutor.cpp:787
     0x10db252cc        DB::compileSelection(std::__1::shared_ptr<DB::mock::Executor>, unsigned long&, std::__1::shared_ptr<DB::IAST>) [gtests_dbms+4444164812]
                        dbms/src/Debug/astToExecutor.cpp:1507
     0x106e69c08        DB::tests::DAGRequestBuilder::filter(std::__1::shared_ptr<DB::IAST>) [gtests_dbms+4330150920]
                        dbms/src/TestUtils/mockExecutor.cpp:174
     0x1050463bc        DB::tests::ExecutorTestRunner_Filter_Test::TestBody() [gtests_dbms+4298548156]
                        dbms/src/Flash/tests/gtest_executor.cpp:44
     0x10cb78800        void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+4427728896]
                        contrib/googletest/googletest/src/gtest.cc:2443
     0x10cb4d90c        void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+4427553036]
                        contrib/googletest/googletest/src/gtest.cc:2479
     0x10cb4d868        testing::Test::Run() [gtests_dbms+4427552872]
                        contrib/googletest/googletest/src/gtest.cc:2517
     0x10cb4e6f0        testing::TestInfo::Run() [gtests_dbms+4427556592]
                        contrib/googletest/googletest/src/gtest.cc:2693
     0x10cb4f404        testing::TestCase::Run() [gtests_dbms+4427559940]
                        contrib/googletest/googletest/src/gtest.cc:2811
     0x10cb58a0c        testing::internal::UnitTestImpl::RunAllTests() [gtests_dbms+4427598348]
                        contrib/googletest/googletest/src/gtest.cc:5177
     0x10cb7d3f8        bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+4427748344]
                        contrib/googletest/googletest/src/gtest.cc:2443
     0x10cb5858c        bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+4427597196]
                        contrib/googletest/googletest/src/gtest.cc:2479
     0x10cb58484        testing::UnitTest::Run() [gtests_dbms+4427596932]
                        contrib/googletest/googletest/src/gtest.cc:4786
     0x106cfe6e0        RUN_ALL_TESTS() [gtests_dbms+4328662752]
                        contrib/googletest/googletest/include/gtest/gtest.h:2341
     0x106cfe41c        main [gtests_dbms+4328662044]
                        dbms/src/TestUtils/gtests_dbms_main.cpp:77
     0x185029430        <unknown symbol> [libdyld.dylib+6445634608]

[  FAILED  ] ExecutorTestRunner.Filter (883 ms)
[----------] 1 test from ExecutorTestRunner (883 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (887 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ExecutorTestRunner.Filter
```

### 4. What is your TiFlash version? (Required)

master

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: close #5510 

Problem Summary:

### What is changed and how it works?
Modify qualified name into three parts, add a new struct to hold the column name.
```
struct ColumnName
{
    String db_name;
    String table_name;
    String column_name;
};
```
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/tests/gtest_split_tasks.cpp [hunk 1]
```diff
@@ -95,15 +95,15 @@ try
 
     size_t task_size = tasks.size();
     std::vector<String> executors = {
-        "exchange_sender_6 | type:Hash, {<0, String>}\n"
-        " table_scan_1 | {<0, String>}",
+        "exchange_sender_6 | type:Hash, {<0, String>, <1, String>}\n"
```
Comment (ywqzzy) [inline dbms/src/Flash/tests/gtest_split_tasks.cpp:98]: because we can distinguish the column name by table_name and column_name, so the columnPrune result is different.

File: dbms/src/Flash/tests/gtest_executor.cpp [hunk 2]
```diff
@@ -62,5 +62,20 @@ try
 }
 CATCH
 
+TEST_F(ExecutorTestRunner, FilterWithQualifiedFormat)
```
Comment (SeaRise) [inline dbms/src/Flash/tests/gtest_executor.cpp:65]: It seems that it can be renamed to `FilterExecutorTestRunner`

File: dbms/src/Flash/tests/gtest_split_tasks.cpp [hunk 3]
```diff
@@ -95,15 +95,15 @@ try
...
+        " table_scan_1 | {<0, String>, <1, String>}",
         "exchange_sender_5 | type:Hash, {<0, String>, <1, String>}\n"
         " table_scan_0 | {<0, String>, <1, String>}",
         "exchange_sender_4 | type:PassThrough, {<0, String>, <1, String>, <2, String>}\n"
```
Comment (SeaRise) [inline dbms/src/Flash/tests/gtest_split_tasks.cpp:102]: It looks like the output of `exchange_sender_4` is wrong, it should be 4 columns

File: dbms/src/Debug/dbgFuncCoprocessor.cpp [hunk 4]
```diff
@@ -767,13 +767,14 @@ std::pair<ExecutorPtr, bool> compileQueryBlock(
                     }
                 }
             }
-            root_executor = compileTableScan(executor_index, table_info, table_alias, append_pk_column);
+            String empty;
+            root_executor = compileTableScan(executor_index, table_info, empty, table_alias, append_pk_column);
```
Comment (SeaRise) [inline dbms/src/Debug/dbgFuncCoprocessor.cpp:771]:
```suggestion
            root_executor = compileTableScan(executor_index, table_info, "", table_alias, append_pk_column);
```

File: dbms/src/Debug/dbgFuncCoprocessor.cpp [hunk 5]
```diff
@@ -813,23 +814,24 @@ std::pair<ExecutorPtr, bool> compileQueryBlock(
...
-                        throw Exception("Unknown table alias: " + names.first);
+                        throw Exception("Unknown table alias: " + names.table_name);
                 }
             }
         }
-        auto left_ts = compileTableScan(executor_index, left_table_info, left_table_alias, left_append_pk_column);
-        auto right_ts = compileTableScan(executor_index, right_table_info, right_table_alias, right_append_pk_column);
+        String empty;
+        auto left_ts = compileTableScan(executor_index, left_table_info, empty, left_table_alias, left_append_pk_column);
+        auto right_ts = compileTableScan(executor_index, right_table_info, empty, right_table_alias, right_append_pk_column);
```
Comment (SeaRise) [inline dbms/src/Debug/dbgFuncCoprocessor.cpp:834]: ditto

File: dbms/src/Flash/tests/gtest_split_tasks.cpp (hunk 3 above)
Comment (ywqzzy) [reply dbms/src/Flash/tests/gtest_split_tasks.cpp:102]: > It looks like the output of `exchange_sender_4` is wrong, it should be 4 columns

Ops, also solved in another pr, I will move the solution to this pr.

File: dbms/src/TestUtils/tests/gtest_mock_executors.cpp [hunk 6]
```diff
@@ -195,6 +236,32 @@ try
...
+                                 .topN({{"r_table.r_b", false}}, 10);
+
+        auto left_builder = context.scan("test_db", "l_table")
+                                .topN({{"l_table.l_a", false}}, 10)
+                                .join(right_builder, tipb::JoinType::TypeLeftOuterJoin, {col("join_c")}) // todo ensure the join is legal.
+                                .limit(10);
+        request = left_builder.build(context);
+        {
+            String expected = "limit_8 | 10\n"
+                              " Join_7 | LeftOuterJoin, HashJoin. left_join_keys: {<0, String>}, right_join_keys: {<0, String>}\n"
```
Comment (SeaRise) [inline dbms/src/TestUtils/tests/gtest_mock_executors.cpp:254]: why `<0, String>` or not `<3, String>`?

Comment (ywqzzy) [reply dbms/src/TestUtils/tests/gtest_mock_executors.cpp:254]: > why `<0, String>` or not `<3, String>`?
Probably related to executorSerializer.cpp:50, toString function print the column from index 0.

Comment (ywqzzy) [reply dbms/src/TestUtils/tests/gtest_mock_executors.cpp:254]: > why `<0, String>` or not `<3, String>`?

Related to executorSerializer.cpp:50, toString function print the column from index 0.

**Review by SeaRise — APPROVED** [review]

File: dbms/src/Flash/tests/gtest_split_tasks.cpp [hunk 7]
```diff
@@ -95,15 +95,15 @@ try
 
     size_t task_size = tasks.size();
```
Comment (Willendless) [inline dbms/src/Flash/tests/gtest_split_tasks.cpp:96]: ditto

**Comment by Willendless** [comment]
According to the struct definition

```cpp
struct ColumnName
{
    String db_name;
    String table_name;
    String column_name;
};
```

our qualified format seems to be "db_name.table_name.column_name", can you add some tests about this kind?

File: dbms/src/Debug/astToExecutor.h [hunk 8]
```diff
@@ -50,7 +50,14 @@ extern String LOCAL_HOST;
...
 
-std::pair<String, String> splitQualifiedName(const String & s);
+struct ColumnName
+{
+    String db_name;
+    String table_name;
+    String column_name;
+};
+
+ColumnName splitQualifiedName(const String & s);
```
[the remark this answers is not in the document]
Comment (ywqzzy) [reply dbms/src/Debug/astToExecutor.h:63]: > maybe use `const` modifier?

Can't pass the static analyze.

[the remark this answers is not in the document]
Comment (Willendless) [reply dbms/src/Debug/astToExecutor.h:63]: may be use `const` within the struct?

struct ColumnName
{
    const String db_name;
    const String table_name;
    const String column_name;
};

**Comment by xzhangxian1008** [comment]
lgtm

**Review by Lloyd-Pottiger — APPROVED** [review]
