### PR TITLE
ensure every record in wal is only applied once when restart

### LINKED ISSUE #7915: TiFlash crash after restart for Trying to add ref to non-exist page
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

consistency test and chaos tiflash failure
```
[2023/08/08 05:46:24.768 +08:00] [ERROR] [Exception.cpp:90] ["Code: 0, e.displayText() = DB::Exception: Trying to add ref to non-exist page [page_id=173.996173] [ori_id=173.14901] [ver=2312646.0] [resolve_id=0.0] [resolve_ver=0.0]:  [type=REF] [page_id=173.996173] [ver=2312646.0], e.what() = DB::Exception, Stack trace:\n\n\n       0x1c4b4ce\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+29668558]\n                \tdbms/src/Common/Exception.h:46\n       0x1b8062c\tDB::PS::V3::PageDirectory<DB::PS::V3::u128::PageDirectoryTrait>::applyRefEditRecord(std::__1::map<DB::UInt128, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> >, std::__1::less<DB::UInt128>, std::__1::allocator<std::__1::pair<DB::UInt128 const, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> > > > >&, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> > const&, DB::PS::V3::PageEntriesEdit<DB::UInt128>::EditRecord const&, DB::PS::V3::PageVersion const&) [tiflash+28837420]\n                \tdbms/src/Storages/Page/V3/PageDirectory.cpp:1421\n       0x1b95bac\tDB::PS::V3::PageDirectoryFactory<DB::PS::V3::u128::FactoryTrait>::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::FileProvider>&, std::__1::shared_ptr<DB::PSDiskDelegator>&, DB::PS::V3::WALConfig const&) [tiflash+28924844]\n                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:40\n       0x761ab42\tDB::PS::V3::PageStorageImpl::restore() [tiflash+123841346]\n                \tdbms/src/Storages/Page/V3/PageStorageImpl.cpp:80\n       0x749192b\tDB::DM::GlobalStoragePool::restore() [tiflash+122231083]\n                \tdbms/src/Storages/DeltaMerge/StoragePool.cpp:116\n       0x77d9091\tDB::Context::initializeGlobalStoragePoolIfNeed(DB::PathPool const&) [tiflash+125669521]\n                \tdbms/src/Interpreters/Context.cpp:1688\n       0x1cfd749\tDB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) [tiflash+30398281]\n                \tdbms/src/Server/Server.cpp:1262\n       0x8a27d6a\tPoco::Util::Application::run() [tiflash+144866666]\n                \tcontrib/poco/Util/src/Application.cpp:335\n       0x1cf2dca\tDB::Server::run() [tiflash+30354890]\n                \tdbms/src/Server/Server.cpp:265\n       0x8a32654\tPoco::Util::ServerApplication::run(int, char**) [tiflash+144909908]\n                \tcontrib/poco/Util/src/ServerApplication.cpp:618\n       0x1d0c9b9\tmainEntryClickHouseServer(int, char**) [tiflash+30460345]\n                \tdbms/src/Server/Server.cpp:1742\n       0x1c378ec\tmain [tiflash+29587692]\n                \tdbms/src/Server/main.cpp:167\n  0x7f5ebf3e2eb0\t__libc_start_call_main [libc.so.6+261808]\n  0x7f5ebf3e2f60\t__libc_start_main_impl [libc.so.6+261984]\n       0x19274a9\t<unknown symbol> [tiflash+26375337]"] [source="bool DB::Context::initializeGlobalStoragePoolIfNeed(const DB::PathPool &)"] [thread_id=1]
[2023/08/08 05:46:25.040 +08:00] [ERROR] [<unknown>] ["DB::Exception: Trying to add ref to non-exist page [page_id=173.996173] [ori_id=173.14901] [ver=2312646.0] [resolve_id=0.0] [resolve_ver=0.0]:  [type=REF] [page_id=173.996173] [ver=2312646.0]"] [source=Application] [thread_id=1]
[2023/08/08 05:51:36.825 +08:00] [ERROR] [Exception.cpp:90] ["Code: 0, e.displayText() = DB::Exception: Trying to add ref to non-exist page [page_id=173.996173] [ori_id=173.14901] [ver=2312646.0] [resolve_id=0.0] [resolve_ver=0.0]:  [type=REF] [page_id=173.996173] [ver=2312646.0], e.what() = DB::Exception, Stack trace:\n\n\n       0x1c4b4ce\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+29668558]\n                \tdbms/src/Common/Exception.h:46\n       0x1b8062c\tDB::PS::V3::PageDirectory<DB::PS::V3::u128::PageDirectoryTrait>::applyRefEditRecord(std::__1::map<DB::UInt128, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> >, std::__1::less<DB::UInt128>, std::__1::allocator<std::__1::pair<DB::UInt128 const, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> > > > >&, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> > const&, DB::PS::V3::PageEntriesEdit<DB::UInt128>::EditRecord const&, DB::PS::V3::PageVersion const&) [tiflash+28837420]\n                \tdbms/src/Storages/Page/V3/PageDirectory.cpp:1421\n       0x1b95bac\tDB::PS::V3::PageDirectoryFactory<DB::PS::V3::u128::FactoryTrait>::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::FileProvider>&, std::__1::shared_ptr<DB::PSDiskDelegator>&, DB::PS::V3::WALConfig const&) [tiflash+28924844]\n                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:40\n       0x761ab42\tDB::PS::V3::PageStorageImpl::restore() [tiflash+123841346]\n                \tdbms/src/Storages/Page/V3/PageStorageImpl.cpp:80\n       0x749192b\tDB::DM::GlobalStoragePool::restore() [tiflash+122231083]\n                \tdbms/src/Storages/DeltaMerge/StoragePool.cpp:116\n       0x77d9091\tDB::Context::initializeGlobalStoragePoolIfNeed(DB::PathPool const&) [tiflash+125669521]\n                \tdbms/src/Interpreters/Context.cpp:1688\n       0x1cfd749\tDB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) [tiflash+30398281]\n                \tdbms/src/Server/Server.cpp:1262\n       0x8a27d6a\tPoco::Util::Application::run() [tiflash+144866666]\n                \tcontrib/poco/Util/src/Application.cpp:335\n       0x1cf2dca\tDB::Server::run() [tiflash+30354890]\n                \tdbms/src/Server/Server.cpp:265\n       0x8a32654\tPoco::Util::ServerApplication::run(int, char**) [tiflash+144909908]\n                \tcontrib/poco/Util/src/ServerApplication.cpp:618\n       0x1d0c9b9\tmainEntryClickHouseServer(int, char**) [tiflash+30460345]\n                \tdbms/src/Server/Server.cpp:1742\n       0x1c378ec\tmain [tiflash+29587692]\n                \tdbms/src/Server/main.cpp:167\n  0x7f4d99c07eb0\t__libc_start_call_main [libc.so.6+261808]\n  0x7f4d99c07f60\t__libc_start_main_impl [libc.so.6+261984]\n       0x19274a9\t<unknown symbol> [tiflash+26375337]"] [source="bool DB::Context::initializeGlobalStoragePoolIfNeed(const DB::PathPool &)"] [thread_id=1]
[2023/08/08 05:51:37.113 +08:00] [ERROR] [<unknown>] ["DB::Exception: Trying to add ref to non-exist page [page_id=173.996173] [ori_id=173.14901] [ver=2312646.0] [resolve_id=0.0] [resolve_ver=0.0]:  [type=REF] [page_id=173.996173] [ver=2312646.0]"] [source=Application] [thread_id=1]
[2023/08/08 05:56:47.823 +08:00] [ERROR] [Exception.cpp:90] ["Code: 0, e.displayText() = DB::Exception: Trying to add ref to non-exist page [page_id=173.996173] [ori_id=173.14901] [ver=2312646.0] [resolve_id=0.0] [resolve_ver=0.0]:  [type=REF] [page_id=173.996173] [ver=2312646.0], e.what() = DB::Exception, Stack trace:\n\n\n       0x1c4b4ce\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+29668558]\n                \tdbms/src/Common/Exception.h:46\n       0x1b8062c\tDB::PS::V3::PageDirectory<DB::PS::V3::u128::PageDirectoryTrait>::applyRefEditRecord(std::__1::map<DB::UInt128, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> >, std::__1::less<DB::UInt128>, std::__1::allocator<std::__1::pair<DB::UInt128 const, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> > > > >&, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> > const&, DB::PS::V3::PageEntriesEdit<DB::UInt128>::EditRecord const&, DB::PS::V3::PageVersion const&) [tiflash+28837420]\n                \tdbms/src/Storages/Page/V3/PageDirectory.cpp:1421\n       0x1b95bac\tDB::PS::V3::PageDirectoryFactory<DB::PS::V3::u128::FactoryTrait>::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::FileProvider>&, std::__1::shared_ptr<DB::PSDiskDelegator>&, DB::PS::V3::WALConfig const&) [tiflash+28924844]\n                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:40\n       0x761ab42\tDB::PS::V3::PageStorageImpl::restore() [tiflash+123841346]\n                \tdbms/src/Storages/Page/V3/PageStorageImpl.cpp:80\n       0x749192b\tDB::DM::GlobalStoragePool::restore() [tiflash+122231083]\n                \tdbms/src/Storages/DeltaMerge/StoragePool.cpp:116\n       0x77d9091\tDB::Context::initializeGlobalStoragePoolIfNeed(DB::PathPool const&) [tiflash+125669521]\n                \tdbms/src/Interpreters/Context.cpp:1688\n       0x1cfd749\tDB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) [tiflash+30398281]\n                \tdbms/src/Server/Server.cpp:1262\n       0x8a27d6a\tPoco::Util::Application::run() [tiflash+144866666]\n                \tcontrib/poco/Util/src/Application.cpp:335\n       0x1cf2dca\tDB::Server::run() [tiflash+30354890]\n                \tdbms/src/Server/Server.cpp:265\n       0x8a32654\tPoco::Util::ServerApplication::run(int, char**) [tiflash+144909908]\n                \tcontrib/poco/Util/src/ServerApplication.cpp:618\n       0x1d0c9b9\tmainEntryClickHouseServer(int, char**) [tiflash+30460345]\n                \tdbms/src/Server/Server.cpp:1742\n       0x1c378ec\tmain [tiflash+29587692]\n                \tdbms/src/Server/main.cpp:167\n  0x7f0bb4cabeb0\t__libc_start_call_main [libc.so.6+261808]\n  0x7f0bb4cabf60\t__libc_start_main_impl [libc.so.6+261984]\n       0x19274a9\t<unknown symbol> [tiflash+26375337]"] [source="bool DB::Context::initializeGlobalStoragePoolIfNeed(const DB::PathPool &)"] [thread_id=1]
[2023/08/08 05:56:47.924 +08:00] [ERROR] [<unknown>] ["DB::Exception: Trying to add ref to non-exist page [page_id=173.996173] [ori_id=173.14901] [ver=2312646.0] [resolve_id=0.0] [resolve_ver=0.0]:  [type=REF] [page_id=173.996173] [ver=2312646.0]"] [source=Application] [thread_id=1]
[2023/08/08 06:02:04.853 +08:00] [ERROR] [Exception.cpp:90] ["Code: 0, e.displayText() = DB::Exception: Trying to add ref to non-exist page [page_id=173.996173] [ori_id=173.14901] [ver=2312646.0] [resolve_id=0.0] [resolve_ver=0.0]:  [type=REF] [page_id=173.996173] [ver=2312646.0], e.what() = DB::Exception, Stack trace:\n\n\n       0x1c4b4ce\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+29668558]\n                \tdbms/src/Common/Exception.h:46\n       0x1b8062c\tDB::PS::V3::PageDirectory<DB::PS::V3::u128::PageDirectoryTrait>::applyRefEditRecord(std::__1::map<DB::UInt128, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> >, std::__1::less<DB::UInt128>, std::__1::allocator<std::__1::pair<DB::UInt128 const, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> > > > >&, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> > const&, DB::PS::V3::PageEntriesEdit<DB::UInt128>::EditRecord const&, DB::PS::V3::PageVersion const&) [tiflash+28837420]\n                \tdbms/src/Storages/Page/V3/PageDirectory.cpp:1421\n       0x1b95bac\tDB::PS::V3::PageDirectoryFactory<DB::PS::V3::u128::FactoryTrait>::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::FileProvider>&, std::__1::shared_ptr<DB::PSDiskDelegator>&, DB::PS::V3::WALConfig const&) [tiflash+28924844]\n                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:40\n       0x761ab42\tDB::PS::V3::PageStorageImpl::restore() [tiflash+123841346]\n                \tdbms/src/Storages/Page/V3/PageStorageImpl.cpp:80\n       0x749192b\tDB::DM::GlobalStoragePool::restore() [tiflash+122231083]\n                \tdbms/src/Storages/DeltaMerge/StoragePool.cpp:116\n       0x77d9091\tDB::Context::initializeGlobalStoragePoolIfNeed(DB::PathPool const&) [tiflash+125669521]\n                \tdbms/src/Interpreters/Context.cpp:1688\n       0x1cfd749\tDB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) [tiflash+30398281]\n                \tdbms/src/Server/Server.cpp:1262\n       0x8a27d6a\tPoco::Util::Application::run() [tiflash+144866666]\n                \tcontrib/poco/Util/src/Application.cpp:335\n       0x1cf2dca\tDB::Server::run() [tiflash+30354890]\n                \tdbms/src/Server/Server.cpp:265\n       0x8a32654\tPoco::Util::ServerApplication::run(int, char**) [tiflash+144909908]\n                \tcontrib/poco/Util/src/ServerApplication.cpp:618\n       0x1d0c9b9\tmainEntryClickHouseServer(int, char**) [tiflash+30460345]\n                \tdbms/src/Server/Server.cpp:1742\n       0x1c378ec\tmain [tiflash+29587692]\n                \tdbms/src/Server/main.cpp:167\n  0x7fb8fd53eeb0\t__libc_start_call_main [libc.so.6+261808]\n  0x7fb8fd53ef60\t__libc_start_main_impl [libc.so.6+261984]\n       0x19274a9\t<unknown symbol> [tiflash+26375337]"] [source="bool DB::Context::initializeGlobalStoragePoolIfNeed(const DB::PathPool &)"] [thread_id=1]
[2023/08/08 06:02:05.048 +08:00] [ERROR] [<unknown>] ["DB::Exception: Trying to add ref to non-exist page [page_id=173.996173] [ori_id=173.14901] [ver=2312646.0] [resolve_id=0.0] [resolve_ver=0.0]:  [type=REF] [page_id=173.996173] [ver=2312646.0]"] [source=Application] [thread_id=1]
[2023/08/08 06:07:14.860 +08:00] [ERROR] [Exception.cpp:90] ["Code: 0, e.displayText() = DB::Exception: Trying to add ref to non-exist page [page_id=173.996173] [ori_id=173.14901] [ver=2312646.0] [resolve_id=0.0] [resolve_ver=0.0]:  [type=REF] [page_id=173.996173] [ver=2312646.0], e.what() = DB::Exception, Stack trace:\n\n\n       0x1c4b4ce\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+29668558]\n                \tdbms/src/Common/Exception.h:46\n       0x1b8062c\tDB::PS::V3::PageDirectory<DB::PS::V3::u128::PageDirectoryTrait>::applyRefEditRecord(std::__1::map<DB::UInt128, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> >, std::__1::less<DB::UInt128>, std::__1::allocator<std::__1::pair<DB::UInt128 const, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> > > > >&, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries<DB::PS::V3::u128::PageDirectoryTrait> > const&, DB::PS::V3::PageEntriesEdit<DB::UInt128>::EditRecord const&, DB::PS::V3::PageVersion const&) [tiflash+28837420]\n                \tdbms/src/Storages/Page/V3/PageDirectory.cpp:1421\n       0x1b95bac\tDB::PS::V3::PageDirectoryFactory<DB::PS::V3::u128::FactoryTrait>::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::FileProvider>&, std::__1::shared_ptr<DB::PSDiskDelegator>&, DB::PS::V3::WALConfig const&) [tiflash+28924844]\n                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:40\n       0x761ab42\tDB::PS::V3::PageStorageImpl::restore() [tiflash+123841346]\n                \tdbms/src/Storages/Page/V3/PageStorageImpl.cpp:80\n       0x749192b\tDB::DM::GlobalStoragePool::restore() [tiflash+122231083]\n                \tdbms/src/Storages/DeltaMerge/StoragePool.cpp:116\n       0x77d9091\tDB::Context::initializeGlobalStoragePoolIfNeed(DB::PathPool const&) [tiflash+125669521]\n                \tdbms/src/Interpreters/Context.cpp:1688\n       0x1cfd749\tDB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) [tiflash+30398281]\n                \tdbms/src/Server/Server.cpp:1262\n       0x8a27d6a\tPoco::Util::Application::run() [tiflash+144866666]\n                \tcontrib/poco/Util/src/Application.cpp:335\n       0x1cf2dca\tDB::Server::run() [tiflash+30354890]\n                \tdbms/src/Server/Server.cpp:265\n       0x8a32654\tPoco::Util::ServerApplication::run(int, char**) [tiflash+144909908]\n                \tcontrib/poco/Util/src/ServerApplication.cpp:618\n       0x1d0c9b9\tmainEntryClickHouseServer(int, char**) [tiflash+30460345]\n                \tdbms/src/Server/Server.cpp:1742\n       0x1c378ec\tmain [tiflash+29587692]\n                \tdbms/src/Server/main.cpp:167\n  0x7fb04af61eb0\t__libc_start_call_main [libc.so.6+261808]\n  0x7fb04af61f60\t__libc_start_main_impl [libc.so.6+261984]\n       0x19274a9\t<unknown symbol> [tiflash+26375337]"] [source="bool DB::Context::initializeGlobalStoragePoolIfNeed(const DB::PathPool &)"] [thread_id=1]
```
### 4. What is your TiFlash version? (Required)
master

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #7915 

Problem Summary:
After dumping snapshot to checkpoint file, we only remove log files which max sequence is smaller than the sequence used to dump snapshot.
So the remaining wal files may have some overlap with the checkpoint file.
And at restart, we will apply all records in the checkpoint file and other wal files which will cause some records to be applied more than once.
This may cause some problem like the following picture.

image

Because page 88 was already deleted, it is not shown in the checkpoint file `log_100_1`. But the operation `ref 90 -> 88` is still in later log files. So at restart, when it try to apply this record, it will fail to complete the ref operation.

### What is changed and how it works?
Record the snap sequence used to dump checkpoint in the filename of checkpoint file. Specifically, change it from `log_100_1` to `log_100_1_400`.
When restart, after apply all records in checkpoint file, we will skip later record which sequence is smaller than the snap sequence in the checkpoint file name.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility
  - Can not downgrade to a version earlier than v7.4.0

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the problem that tiflash may fail to restart under some cases.
```

### CODE REVIEW

File: dbms/src/Storages/Page/V3/WAL/WALReader.cpp [hunk 1]
```diff
@@ -242,14 +248,14 @@ std::optional<String> WALStoreReader::next()
         std::tie(ok, record) = reader->readRecord();
         if (ok)
         {
-            return record;
+            return std::make_pair(reading_checkpoint_file, record);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/WAL/WALReader.cpp:251]: Can we use `!checkpoint_read_done` instead of `reading_checkpoint_file` here?

Comment (lidezhu) [reply dbms/src/Storages/Page/V3/WAL/WALReader.cpp:251]: `checkpoint_read_done`  is actually mean whether we need to create a reader from checkpoint file. After create the reader, it will be set to true first before read it.

Comment (lidezhu) [reply dbms/src/Storages/Page/V3/WAL/WALReader.cpp:251]: If we want to eliminate the member `reading_checkpoint_file`, we can make it a return value of `openNextFile` instead.

File: dbms/src/Storages/Page/V3/LogFile/LogFilename.h [hunk 2]
```diff
@@ -44,11 +45,13 @@ struct LogFilename
     inline String filename(LogFileStage file_stage) const
     {
         assert(file_stage != LogFileStage::Invalid);
+        auto suffix = (snap_seq == 0) ? "" : fmt::format("_{}", snap_seq);
         return fmt::format(
-            "{}_{}_{}",
+            "{}_{}_{}{}",
```
Comment (flowbehappy) [inline dbms/src/Storages/Page/V3/LogFile/LogFilename.h:50]: Why not `{}_{}_{}_{}`?

**Comment by flowbehappy** [comment]
https://github.com/pingcap/docs-cn/blob/master/tiflash-upgrade-guide.md
https://github.com/pingcap/docs/blob/master/tiflash-upgrade-guide.md

Please also update those two docs

File: dbms/src/Storages/Page/V3/WAL/WALReader.cpp (hunk 1 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/Page/V3/WAL/WALReader.cpp:251]: OK

**Comment by lidezhu** [comment]
> https://github.com/pingcap/docs-cn/blob/master/tiflash-upgrade-guide.md https://github.com/pingcap/docs/blob/master/tiflash-upgrade-guide.md
> 
> Please also update those two docs

OK.

**Comment by lidezhu** [comment]
> https://github.com/pingcap/docs-cn/blob/master/tiflash-upgrade-guide.md https://github.com/pingcap/docs/blob/master/tiflash-upgrade-guide.md
> 
> Please also update those two docs

https://github.com/pingcap/docs-cn/pull/14751
https://github.com/pingcap/docs/pull/14479

File: dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp [hunk 3]
```diff
@@ -1318,6 +1318,106 @@ try
...
+    }
+    {
+        auto snap = dir->createSnapshot();
+        auto normal_id = getNormalPageIdU64(dir, 3, snap);
+        EXPECT_EQ(normal_id, 1);
+    }
+
+    auto sp_after_create_snap_for_dump = SyncPointCtl::enableInScope("after_PageDirectory::create_snap_for_dump");
+    auto th_dump = std::async([&]() {
+        ASSERT_TRUE(dir->tryDumpSnapshot(nullptr, true));
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp:1348]: we should execute dir->gcInMem to ensure the deleted page is actually removed in the dumped snapshot

File: dbms/src/Storages/Page/V3/LogFile/LogFilename.cpp [hunk 4]
```diff
@@ -29,28 +29,29 @@ LogFilename LogFilename::parseFrom(const String & parent_path, const String & fi
     if (!startsWith(filename, LOG_FILE_PREFIX_TEMP) && !startsWith(filename, LOG_FILE_PREFIX_NORMAL))
     {
         LOG_INFO(log, "Ignore not log file [dir={}] [file={}]", parent_path, filename);
-        return {LogFileStage::Invalid, 0, 0, 0, ""};
+        return {LogFileStage::Invalid, 0, 0, 0, 0, ""};
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/LogFile/LogFilename.cpp:32]: We'd better throw exception when meet unknown filename in the directory in `WALStoreReader::listAllFiles`

**Review by JaySon-Huang — COMMENTED** [review]
I've file a PR to fix some issue: https://github.com/lidezhu/tics/pull/11

**Review by flowbehappy — APPROVED** [review]
