### PR TITLE
Fix exception `Illegal type MyDuration(0) of first argument of function` when remote read occur

### LINKED ISSUE #7892: tiflash report "[MPPTask.cpp:575] ["task running meets error: Code: 43, e.displayText() = DB::Exception: Illegal type MyDuration(0) of first argument of function "
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. 7.1.0 upgrade to master，arm env
2. create table and import 1000 records, create tiflash replica, 
3. after replica is available, use tiflash to execute sql, check consistency.
4. insert new records to table, and check
5. create another table and import 1000 records, create tiflash replica, after replica is available, use tiflash to execute sql, check consistency

### 2. What did you expect to see? (Required)
tiflash run normally
### 3. What did you see instead (Required)
```
[2023/08/02 23:00:41.712 +00:00] [ERROR] [MPPTask.cpp:575] ["task running meets error: Code: 43, e.displayText() = DB::Exception: Illegal type MyDuration(0) of first argument of function FunctionConvertDurationFromNanos, e.what() = DB::Exception, Stack trace:\n\n\n       0x1923364\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+26358628]\n                \tdbms/src/Common/Exception.h:46\n       0x2acadcc\tDB::FunctionConvertDurationFromNanos::getReturnTypeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const [tiflash+44871116]\n       0x74c4208\tDB::IFunctionBuilder::getReturnType(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const [tiflash+122438152]\n                \tdbms/src/Functions/IFunction.cpp:263\n       0x6e89bc4\tDB::ExpressionActions::addImpl(DB::ExpressionAction, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) [tiflash+115907524]\n                \tdbms/src/Interpreters/ExpressionActions.cpp:516\n       0x6e8b91c\tDB::ExpressionActions::add(DB::ExpressionAction const&) [tiflash+115915036]\n                \tdbms/src/Interpreters/ExpressionActions.cpp:495\n       0x7547224\tDB::DAGExpressionAnalyzer::applyFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::ExpressionActions> const&, TiDB::ITiDBCollator const* const&) [tiflash+122974756]\n                \tdbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp:677\n       0x754a0d4\tDB::DAGExpressionAnalyzer::buildExtraCastsAfterTS(std::__1::shared_ptr<DB::ExpressionActions> const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, std::__1::vector<TiDB::ColumnInfo, std::__1::allocator<TiDB::ColumnInfo> > const&) [tiflash+122986708]\n                \tdbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp:936\n       0x754a758\tDB::DAGExpressionAnalyzer::appendExtraCastsAfterTS(DB::ExpressionActionsChain&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, DB::TiDBTableScan const&) [tiflash+122988376]\n                \tdbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp:957\n       0x75a9878\tDB::(anonymous namespace)::addExtraCastsAfterTs(DB::DAGExpressionAnalyzer&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, DB::TiDBTableScan const&) [tiflash+123377784]\n                \tdbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp:213\n       0x75a7134\tDB::DAGStorageInterpreter::executeImpl(DB::PipelineExecutorContext&, DB::PipelineExecGroupBuilder&) [tiflash+123367732]\n                \tdbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp:388\n       0x7761310\tDB::PhysicalTableScan::buildPipeline(DB::PipelineBuilder&, DB::Context&, DB::PipelineExecutorContext&) [tiflash+125178640]\n                \tdbms/src/Flash/Planner/Plans/PhysicalTableScan.cpp:134\n       0x76dd288\tDB::PhysicalPlanNode::buildPipeline(DB::PipelineBuilder&, DB::Context&, DB::PipelineExecutorContext&) [tiflash+124637832]\n                \tdbms/src/Flash/Planner/PhysicalPlanNode.cpp:109\n       0x76dd288\tDB::PhysicalPlanNode::buildPipeline(DB::PipelineBuilder&, DB::Context&, DB::PipelineExecutorContext&) [tiflash+124637832]\n                \tdbms/src/Flash/Planner/PhysicalPlanNode.cpp:109\n       0x76d8728\tDB::PhysicalPlan::toPipeline(DB::PipelineExecutorContext&, DB::Context&) [tiflash+124618536]\n                \tdbms/src/Flash/Planner/PhysicalPlan.cpp:290\n       0x76a3ea4\tDB::PipelineExecutor::PipelineExecutor(std::__1::shared_ptr<MemoryTracker> const&, DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) [tiflash+124403364]\n                \tdbms/src/Flash/Executor/PipelineExecutor.cpp:39\n       0x753a308\tDB::(anonymous namespace)::executeAsPipeline(DB::Context&, bool) [tiflash+122921736]\n                \tdbms/src/Flash/executeQuery.cpp:148\n       0x7539c14\tDB::queryExecute(DB::Context&, bool) [tiflash+122919956]\n                \tdbms/src/Flash/executeQuery.cpp:184\n       0x76550bc\tDB::MPPTask::runImpl() [tiflash+124080316]\n                \tdbms/src/Flash/Mpp/MPPTask.cpp:476\n       0x1a1b670\tauto DB::wrapInvocable<std::__1::function<void ()> >(bool, std::__1::function<void ()>&&)::'lambda'()::operator()() [tiflash+27375216]\n                \tdbms/src/Common/wrapInvocable.h:36\n       0x1931824\tDB::DynamicThreadPool::executeTask(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&) [tiflash+26417188]\n                \tdbms/src/Common/DynamicThreadPool.cpp:123\n       0x1931170\tDB::DynamicThreadPool::fixedWork(unsigned long) [tiflash+26415472]\n                \tdbms/src/Common/DynamicThreadPool.cpp:137\n       0x193301c\tvoid* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(unsigned long), DB::DynamicThreadPool*, unsigned long&>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(unsigned long), DB::DynamicThreadPool*&&, unsigned long&)::'lambda'(auto&&...), DB::DynamicThreadPool*, unsigned long> >(void*) [tiflash+26423324]\n                \t/usr/local/bin/../include/c++/v1/thread:291\n  0xfffc15322a28\tstart_thread [libc.so.6+535080]\n  0xfffc152cbb9c\tthread_start [libc.so.6+179100]"] [source="MPP<gather_id:<gather_id:1, query_ts:1691017241592654524, local_query_id:1365, server_id:1720, start_ts:443290023778582536>,task_id:2>"] [thread_id=326]

[2023/08/02 23:00:22.723 +00:00] [ERROR] [MPPTask.cpp:575] ["task running meets error: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel2+-1 which is already closed, tunnel2+-1: unexpectedWriteDone called, e.what() = DB::Exception, Stack trace:\n\n\n       0x1923364\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+26358628]\n                \tdbms/src/Common/Exception.h:46\n       0x7670b70\tDB::MPPTunnel::forceWrite(std::__1::shared_ptr<DB::TrackedMppDataPacket>&&) [tiflash+124193648]\n                \tdbms/src/Flash/Mpp/MPPTunnel.cpp:193\n       0x18fe6ec\tDB::MPPTunnelSetBase<DB::MPPTunnel>::forceWrite(tipb::SelectResponse&, unsigned long) [tiflash+26207980]\n                \tdbms/src/Flash/Mpp/MPPTunnelSet.cpp:67\n       0x18f3b50\tDB::StreamingDAGResponseWriter<std::__1::shared_ptr<DB::AsyncMPPTunnelSetWriter> >::encodeThenWriteBlocks() [tiflash+26164048]\n                \tdbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp:146\n       0x7723c9c\tDB::ExchangeSenderSinkOp::writeImpl(DB::Block&&) [tiflash+124927132]\n                \tdbms/src/Operators/ExchangeSenderSinkOp.cpp:38\n       0x76b4720\tDB::SinkOp::write(DB::Block&&) [tiflash+124471072]\n                \tdbms/src/Operators/Operator.cpp:176\n       0x76b16a8\tDB::PipelineExec::executeImpl() [tiflash+124458664]\n                \tdbms/src/Flash/Pipeline/Exec/PipelineExec.cpp:127\n       0x76c767c\tDB::PipelineTask::executeImpl() [tiflash+124548732]\n                \tdbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.cpp:72\n       0x76ca7b0\tDB::Task::execute() [tiflash+124561328]\n                \tdbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp:133\n       0x1900dd8\tDB::TaskThreadPool<DB::CPUImpl>::loop(unsigned long) [tiflash+26217944]\n                \tdbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPool.cpp:59\n       0x190142c\tvoid* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::TaskThreadPool<DB::CPUImpl>::*)(unsigned long), DB::TaskThreadPool<DB::CPUImpl>*, unsigned long> >(void*) [tiflash+26219564]\n                \t/usr/local/bin/../include/c++/v1/thread:291\n  0xfffc15322a28\tstart_thread [libc.so.6+535080]\n  0xfffc152cbb9c\tthread_start [libc.so.6+179100]"] [source="MPP<gather_id:<gather_id:1, query_ts:1691017222173595139, local_query_id:1339, server_id:1720, start_ts:443290018680143894>,task_id:2>"] [thread_id=258]
[2023/08/02 23:00:22.723 +00:00] [WARN] [MPPTaskManager.cpp:213] ["Begin to abort gather: <gather_id:1, query_ts:1691017222173595139, local_query_id:1339, server_id:1720, start_ts:443290018680143894>, abort type: ONERROR, reason: From MPP<gather_id:<gather_id:1, query_ts:1691017222173595139, local_query_id:1339, server_id:1720, start_ts:443290018680143894>,task_id:2>: Code: 0, e.displayText() = DB::Exception: write to tunnel tunnel2+-1 which is already closed, tunnel2+-1: unexpectedWriteDone called, e.what() = DB::Exception,"] [thread_id=258]
```
### 4. What is your TiFlash version? (Required)
2023/08/02 22:39:52.955 +00:00] [INFO] [BaseDaemon.cpp:1176] ["TiFlash build info: TiFlash\nRelease Version: v7.3.0-alpha\nEdition:         Community\nGit Commit Hash: a4ce33b2114362b1a391ffbe40dd0f81af65b9e2\nGit Branch:      heads/refs/tags/v7.3.0-alpha\nUTC Build Time:  2023-08-02 12:26:23\nEnable Features: jemalloc sm4(GmSSL) asimd unwind thinlto\nProfile:         RELWITHDEBINFO\n"] [thread_id=1]

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #7892

Problem Summary:

### What is changed and how it works?
- The reason for the error is mistakenly using `remote_source_op->getHeader()` as the source_columns for the analyzer.
    - https://github.com/pingcap/tiflash/blob/ef6ff95d60fe506ac4f1fa3ebbcaa977c0115c16/dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp#L369-L374
    - https://github.com/pingcap/tiflash/blob/ef6ff95d60fe506ac4f1fa3ebbcaa977c0115c16/dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.cpp#L129-L134
- refactor the code of `DAGStorageInterpreter::executeImpl` like
```
/*** stage1 build for local storage ***/
...

/*** stage2 build for remote read ***/
...

/*** stage3 build null source op if group_builder is empty after building for local/remote ***/
...

    for (const auto & lock : drop_locks)
        dagContext().addTableLock(lock);
```
- remove useless member `DAGStorageInterpreter::analyzer`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/Coprocessor/InterpreterUtils.cpp [hunk 1]
```diff
@@ -372,43 +372,35 @@ std::tuple<ExpressionActionsPtr, String, ExpressionActionsPtr> buildPushDownFilt
...
     LoggerPtr log)
 {
     auto [before_where, filter_column_name, project_after_where] = ::DB::buildPushDownFilter(filter_conditions.conditions, analyzer);
 
-    assert(remote_read_sources_start_index <= group_builder.concurrency());
     auto input_header = group_builder.getCurrentHeader();
-
-    // for remote read, filter had been pushed down, don't need to execute again.
-    for (size_t i = 0; i < remote_read_sources_start_index; ++i)
+    for (size_t i = 0; i < group_builder.concurrency(); ++i)
```
Comment (SeaRise) [inline dbms/src/Flash/Coprocessor/InterpreterUtils.cpp:403]: Use `for each` instead of `transform` just to make the compiler happy :(
https://stackoverflow.com/questions/46114214/lambda-implicit-capture-fails-with-variable-declared-from-structured-binding

File: dbms/src/Flash/Coprocessor/InterpreterUtils.cpp [hunk 2]
```diff
@@ -372,43 +372,35 @@ std::tuple<ExpressionActionsPtr, String, ExpressionActionsPtr> buildPushDownFilt
...
     {
-        auto & stream = pipeline.streams[i];
         stream = std::make_shared<FilterBlockInputStream>(stream, before_where, filter_column_name, log->identifier());
         // todo link runtime filter
         stream->setExtraInfo("push down filter");
         // after filter, do project action to keep the schema of local streams and remote streams the same.
         stream = std::make_shared<ExpressionBlockInputStream>(stream, project_after_where, log->identifier());
         stream->setExtraInfo("projection after push down filter");
-    }
+    };
```
Comment (Lloyd-Pottiger) [inline dbms/src/Flash/Coprocessor/InterpreterUtils.cpp:390]:
```suggestion
    }
```

**Review by Lloyd-Pottiger — APPROVED** [review]

File: dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp [hunk 3]
```diff
@@ -309,12 +309,38 @@ void DAGStorageInterpreter::executeImpl(PipelineExecutorContext & exec_context,
...
+            /// handle generated column if necessary.
+            executeGeneratedColumnPlaceholder(exec_context, group_builder, generated_column_infos, log);
+
+            DAGExpressionAnalyzer analyzer{group_builder.getCurrentHeader(), context};
+
+            /// handle timezone/duration cast for local table scan.
+            executeCastAfterTableScan(exec_context, group_builder, analyzer);
+            dag_context.addOperatorProfileInfos(table_scan.getTableScanExecutorID(), group_builder.getCurProfileInfos(), /*is_append=*/true);
+
+            /// handle filter conditions for local and remote table scan.
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp:330]:
```suggestion
            /// handle filter conditions for local table scan.
```

File: dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp [hunk 4]
```diff
@@ -343,67 +369,76 @@ void DAGStorageInterpreter::executeImpl(PipelineExecutorContext & exec_context,
...
+            /// handle generated column if necessary.
+            executeGeneratedColumnPlaceholder(generated_column_infos, log, pipeline);
+
+            DAGExpressionAnalyzer analyzer{pipeline.firstStream()->getHeader(), context};
+
+            /// handle timezone/duration cast for local and remote table scan.
+            executeCastAfterTableScan(pipeline, analyzer);
+            recordProfileStreams(pipeline, table_scan.getTableScanExecutorID());
+
+            /// handle filter conditions for local and remote table scan.
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp:428]:
```suggestion
            /// handle filter conditions for local table scan.
```

**Review by JaySon-Huang — APPROVED** [review]
LGTM with small comments
