### PR TITLE
ddl: fix query partition table failed after rename column

### LINKED ISSUE #9787: Query partition table failed after rename column
## Bug Report

Ref: https://github.com/pingcap/tidb/issues/58388

### 1. Minimal reproduce step (Required)

```
mysql> CREATE TABLE `t6f9b1fca` (
    ->   `col5def` mediumint DEFAULT '1398811',
    ->   `colb0ec` datetime DEFAULT '8060-08-20 09:18:05',
    ->   `colc4d2` year(4) DEFAULT '2123',
    ->   `colf318` enum('vzd','f1y','wndk','bdw9','qkg','pj','z3','6pj2q','zgm','x5qj','uiyv') DEFAULT 'bdw9',
    ->   `3f60e6b3` decimal(33,25) DEFAULT '-66552329.3166265233570726682245357',
    ->   `colf8a2` bigint DEFAULT '600923851820286643',
    ->   `col9e6f` float DEFAULT '1.9193193',
    ->   `col972e` mediumint DEFAULT '-74934',
    ->   `col9328` varchar(109) DEFAULT 'hkq8osq',
    ->   `col8e36` double DEFAULT '1.5676352034154104'
    -> ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin /*T! SHARD_ROW_ID_BITS=1 */ COMMENT='27f3f141'
    -> PARTITION BY HASH (`colf8a2`) PARTITIONS 9;
Query OK, 0 rows affected (0.11 sec)

mysql> insert into t6f9b1fca values ();
Query OK, 1 row affected (0.00 sec)

mysql> alter table t6f9b1fca set tiflash replica 1;
Query OK, 0 rows affected (0.03 sec)

mysql> select * from t6f9b1fca;
Empty set (0.16 sec)

mysql> alter table t6f9b1fca change 3f60e6b3 3f60e6b2 decimal(33,25) DEFAULT '-66552329.3166265233570726682245357';
Query OK, 0 rows affected (0.02 sec)

mysql> set tidb_enforce_mpp=1; select * from `t6f9b1fca`;
ERROR 1105 (HY000): other error for mpp stream: Code: 10, e.displayText() = DB::Exception: Not found column 3f60e6b3 in block. There are only columns: _tidb_rowid, _INTERNAL_VERSION, _INTERNAL_DELMARK, col5def, colb0ec, col7211, colc4d2, colf318, col7579, 3f60e6b2, colf8a2, col9e6f, col972e, col9328, col8e36: (while creating read sources from storage, keyspace_id=4294967295 table_id=119 logical_table_id=110), e.what() = DB::Exception,
```

### 2. What did you expect to see? (Required)

success

### 3. What did you see instead (Required)

failed

### 4. What is your TiFlash version? (Required)

master

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #9787

Problem Summary:

### What is changed and how it works?

```commit-message
Sync schema for all partitions if the schema of one of physical tables is different from the logical table.
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix query partition table failed after rename column
```

### CODE REVIEW

File: dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp [hunk 1]
```diff
@@ -1433,6 +1438,20 @@ std::unordered_map<TableID, DAGStorageInterpreter::StorageWithStructureLock> DAG
...
+            need_sync_table_ids.clear();
+            table_storages.clear();
+            table_locks.clear();
+            need_sync_table_ids.reserve(table_scan.getPhysicalTableIDs().size() + 1);
+            need_sync_table_ids.push_back(logical_table_id);
+            for (auto const physical_table_id : table_scan.getPhysicalTableIDs())
+                need_sync_table_ids.push_back(physical_table_id);
+        }
+
         if (need_sync_table_ids.empty())
```
Comment (CalvinNeo) [inline dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp:1455]: Do we need a log here?

**Review by CalvinNeo — APPROVED** [review]
lgtm

File: dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp [hunk 2]
```diff
@@ -1450,20 +1480,24 @@ std::unordered_map<TableID, DAGStorageInterpreter::StorageWithStructureLock> DAG
...
+            for (size_t i = 0; i < storages.size(); ++i)
+            {
+                auto const table_id = storages[i]->getTableInfo().id;
+                storages_with_lock[table_id] = {std::move(storages[i]), std::move(locks[i])};
+            }
+            LOG_DEBUG(log, "OK, no syncing required.");
+            return true;
+        }
+
+        LOG_DEBUG(log, "not OK, syncing schemas for keyspace={} table_ids={}", keyspace_id, need_sync_table_ids);
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp:1500]: Use info level for this logging?
