### PR TITLE
Fix wal may dump write diff type in same page_id

### LINKED ISSUE #4849: Exception when PageStorage V3 restore
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Enable PageStorage V3, run the UT:
https://github.com/pingcap/tiflash/blob/1e1bf1f1fd315edf88552b1092b606ee8686d58c/dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp#L1417

### 2. What did you expect to see? (Required)
Pass all the cases.
### 3. What did you see instead (Required)
Exception when PageStorage V3 restore.
`[2022/05/09 20:02:17.580 +08:00] [ERROR] [Exception.cpp:85] ["bool DB::Context::initializeGlobalStoragePoolIfNeed(const DB::PathPool &, bool):Code: 0, e.displayText() = DB::Exception: try to create ref version with invalid state [ver=<9,0>] [ori_page_id=101.1] [state={type:5, create_ver: <0,0>, is_deleted: false, delete_ver: <0,0>, ori_page_id: 0.0, being_ref_count: 1, num_entries: 4}]:  [type=2] [page_id=101.2] [ver=<9,0>], e.what() = DB::Exception, Stack trace:\n\n\n     0x10cf20078\tStackTrace::StackTrace() [gtests_dbms+4495769720]\n                \tdbms/src/Common/StackTrace.cpp:23\n     0x10cf200b4\tStackTrace::StackTrace() [gtests_dbms+4495769780]\n                \tdbms/src/Common/StackTrace.cpp:22\n     0x100fa9674\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [gtests_dbms+4295005812]\n                \tdbms/src/Common/Exception.h:41\n     0x100fa86ec\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [gtests_dbms+4295001836]\n                \tdbms/src/Common/Exception.h:43\n     0x10baafce8\tDB::PS::V3::VersionedPageEntries::createNewRef(DB::PS::V3::PageVersionType const&, DB::UInt128) [gtests_dbms+4474338536]\n                \tdbms/src/Storages/Page/V3/PageDirectory.cpp:250\n     0x10bab6054\tDB::PS::V3::PageDirectory::applyRefEditRecord(std::__1::map<DB::UInt128, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries>, std::__1::less<DB::UInt128>, std::__1::allocator<std::__1::pair<DB::UInt128 const, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries> > > >&, std::__1::shared_ptr<DB::PS::V3::VersionedPageEntries> const&, DB::PS::V3::PageEntriesEdit::EditRecord const&, DB::PS::V3::PageVersionType const&) [gtests_dbms+4474363988]\n                \tdbms/src/Storages/Page/V3/PageDirectory.cpp:963\n     0x10badf2ac\tDB::PS::V3::PageDirectoryFactory::loadEdit(std::__1::unique_ptr<DB::PS::V3::PageDirectory, std::__1::default_delete<DB::PS::V3::PageDirectory> > const&, DB::PS::V3::PageEntriesEdit const&) [gtests_dbms+4474532524]\n                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:158\n     0x10bade5d8\tDB::PS::V3::PageDirectoryFactory::loadFromDisk(std::__1::unique_ptr<DB::PS::V3::PageDirectory, std::__1::default_delete<DB::PS::V3::PageDirectory> > const&, std::__1::shared_ptr<DB::PS::V3::WALStoreReader>&&) [gtests_dbms+4474529240]\n                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:189\n     0x10bade224\tDB::PS::V3::PageDirectoryFactory::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::FileProvider>&, std::__1::shared_ptr<DB::PSDiskDelegator>&, DB::PS::V3::WALStore::Config) [gtests_dbms+4474528292]\n                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:29\n     0x10bae8e3c\tDB::PS::V3::PageStorageImpl::restore() [gtests_dbms+4474572348]\n                \tdbms/src/Storages/Page/V3/PageStorageImpl.cpp:55\n     0x10b3f0864\tDB::DM::GlobalStoragePool::restore() [gtests_dbms+4467263588]\n                \tdbms/src/Storages/DeltaMerge/StoragePool.cpp:117\n     0x10a926ccc\tDB::Context::initializeGlobalStoragePoolIfNeed(DB::PathPool const&, bool) [gtests_dbms+4455951564]\n                \tdbms/src/Interpreters/Context.cpp:1595\n     0x102d178a8\tDB::tests::TiFlashTestEnv::getContext(DB::Settings const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >) [gtests_dbms+4325865640]\n                \tdbms/src/TestUtils/TiFlashTestEnv.cpp:96\n     0x10240483c\tDB::base::TiFlashStorageTestBasic::reload(DB::Settings&&) [gtests_dbms+4316350524]\n                \tdbms/src/Storages/tests/TiFlashStorageTestBasic.h:113\n     0x1024e0148\tDB::DM::tests::DeltaMergeStoreRWTest::reload(std::__1::shared_ptr<std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > > const&, bool, unsigned long) [gtests_dbms+4317249864]\n                \tdbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp:160\n     0x1024f4ca4\tDB::DM::tests::DeltaMergeStoreRWTest_Split_Test::TestBody() [gtests_dbms+4317334692]\n                \tdbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp:1678\n     0x108a70608\tvoid testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+4423747080]\n                \tcontrib/googletest/googletest/src/gtest.cc:2401\n     0x108a48ce8\tvoid testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+4423585000]\n                \tcontrib/googletest/googletest/src/gtest.cc:2437\n     0x108a48c44\ttesting::Test::Run() [gtests_dbms+4423584836]\n                \tcontrib/googletest/googletest/src/gtest.cc:2473\n     0x108a49a7c\ttesting::TestInfo::Run() [gtests_dbms+4423588476]\n                \tcontrib/googletest/googletest/src/gtest.cc:2655\n     0x108a4a774\ttesting::TestCase::Run() [gtests_dbms+4423591796]\n                \tcontrib/googletest/googletest/src/gtest.cc:2773\n     0x108a51234\ttesting::internal::UnitTestImpl::RunAllTests() [gtests_dbms+4423619124]\n                \tcontrib/googletest/googletest/src/gtest.cc:4673\n     0x108a753e8\tbool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+4423767016]\n                \tcontrib/googletest/googletest/src/gtest.cc:2401\n     0x108a50d6c\tbool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+4423617900]\n                \tcontrib/googletest/googletest/src/gtest.cc:2437\n     0x108a50c64\ttesting::UnitTest::Run() [gtests_dbms+4423617636]\n                \tcontrib/googletest/googletest/src/gtest.cc:4281\n     0x102bdb0b8\tRUN_ALL_TESTS() [gtests_dbms+4324569272]\n                \tcontrib/googletest/googletest/include/gtest/gtest.h:2237\n     0x102bdafec\tmain [gtests_dbms+4324569068]\n                \tdbms/src/TestUtils/gtests_dbms_main.cpp:36\n     0x195de1430\t<unknown symbol> [libdyld.dylib+6445634608]"] [thread_id=1]
`
### 4. What is your TiFlash version? (Required)
1e1bf1f

### PR DESCRIPTION
**Pull request by jiaqizho**
### What problem does this PR solve?

Issue Number: close #4849

Problem Summary:
- WALStore may write two diff types in the same page_id. for example:
   - Do updates: E1, E2, X1, X2 
   - shutdown and `restore()`
      - in this time, we still persist E1 and E2 into disk.
   - in `restore()`, we will call the `gcInMemEntries()` will clean up `del` id in MVCC
      -  now MVCC will NOT have any entries in it, because `gcInMemEntries()` has cleaned them up.
   - DT call the `getMaxId()` will get 0.
   - Do updates: E1, Ref(2 -> 1)
   - shutdown and `restore()`(no dump happened, the disk data don't get compacted)
      -  in this time, we will persist E1 and R2 into disk.
   - MVCC Try to restore. But found page_id 2 have two type(external and ref). it will be wrong.

### What is changed and how it works?
- we should call `getMaxId()` before MVCC GC. But we can't do that, Because MVCC will be ready after `restore()`.
- Changes
   - In V2, we will get max id from MVCC(in the end of `restore()`), it won't be a problem.
   - In V3, the basic idea is we record the max_ids of each namespace_ids before applying MVCC GC in memory. 
   - Also after DT call the `restore()`, it never call the `getMaxId()`. So we removed `getMaxId`. Instead, we use `restore()` to return the max_ids.

- Will disable rename in delta-merge-tests
  - `rename` in delta-merge-tests will make `DeltaMergeStore` shutdown and restore. But it won't make `GlobalPathPool` restore.
  - So after `StrogaePool` restore, max_id will be wrong.
  - It only affects tests, and won't affect online operations(different rename logical in `DeltaMergeStore`).
  - it will be fixed in the future

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp [hunk 1]
```diff
@@ -727,6 +736,24 @@ try
...
+    {
+        WriteBatch batch;
+        batch.putExternal(1, 0);
+        batch.putExternal(2, 0);
+        batch.delPage(1);
+        batch.delPage(2);
+        storage->write(std::move(batch));
+    }
+
+    auto [page_storage, max_ids] = reopen();
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp:751]:
```suggestion
    storage = nullptr;
    auto [page_storage, max_ids] = reopen();
```
reset the opened storage before reopen

File: dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp [hunk 2]
```diff
@@ -105,6 +105,15 @@ void PageDirectoryFactory::loadEdit(const PageDirectoryPtr & dir, const PageEntr
...
     for (const auto & r : edit.getRecords())
     {
+        if (const auto it = max_apply_page_ids.find(r.page_id.high); it == max_apply_page_ids.end())
+        {
+            max_apply_page_ids[r.page_id.high] = r.page_id.low;
+        }
+        else
+        {
+            max_apply_page_ids[it->first] = std::max(max_apply_page_ids[it->first], r.page_id.low);
+        }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:115]:
```suggestion
        if (auto it = max_apply_page_ids.find(r.page_id.high); it == max_apply_page_ids.end())
        {
            max_apply_page_ids[r.page_id.high] = r.page_id.low;
        }
        else
        {
            it->second = std::max(it->second, r.page_id.low);
        }
```

File: dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp [hunk 3]
```diff
@@ -1300,5 +1310,40 @@ try
...
+        WriteBatch batch3{TEST_NAMESPACE_ID + 2};
+        batch3.putExternal(1, 0);
+        batch3.putExternal(2, 0);
+        batch3.putRefPage(3, 1);
+        batch3.putRefPage(10, 2);
+        batch3.delPage(10);
+        page_storage->write(std::move(batch3));
+    }
+
+    auto [page_storage, max_ids] = reopen();
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp:1340]:
```suggestion
    page_storage = nullptr;
    auto [restored_page_storage, max_ids] = reopen();
```

File: dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp [hunk 4]
```diff
@@ -1300,5 +1310,40 @@ try
...
+    ASSERT_EQ(max_ids.size(), 3);
+    ASSERT_EQ(max_ids[TEST_NAMESPACE_ID], 2);
+    ASSERT_EQ(max_ids[TEST_NAMESPACE_ID + 1], 100);
+    ASSERT_EQ(max_ids[TEST_NAMESPACE_ID + 2], 10);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp:1344]:
```suggestion
    ASSERT_EQ(max_ids[TEST_NAMESPACE_ID + 2], 10); // page 10 is marked as deleted, but we can still restore it
```

File: dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp [hunk 5]
```diff
@@ -1300,5 +1310,40 @@ try
...
+        batch3.putExternal(2, 0);
+        batch3.putRefPage(3, 1);
+        batch3.putRefPage(10, 2);
+        batch3.delPage(10);
+        page_storage->write(std::move(batch3));
+    }
+
+    auto [page_storage, max_ids] = reopen();
+    ASSERT_EQ(max_ids.size(), 3);
+    ASSERT_EQ(max_ids[TEST_NAMESPACE_ID], 2);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp:1342]:
```suggestion
    ASSERT_EQ(max_ids[TEST_NAMESPACE_ID], 2);  // external page 2 is marked as deleted, but we can still restore it
```

**Review by hehechen — APPROVED** [review]

File: dbms/src/Storages/DeltaMerge/StoragePool.cpp [hunk 6]
```diff
@@ -187,21 +187,58 @@ StoragePool::StoragePool(NamespaceId ns_id_, const GlobalStoragePool & global_st
...
     if (owned_storage)
     {
-        log_storage->restore();
-        data_storage->restore();
-        meta_storage->restore();
+        auto log_max_ids = log_storage->restore();
+        auto data_max_ids = data_storage->restore();
+        auto meta_max_ids = meta_storage->restore();
+
+        assert(log_max_ids.size() == 1);
```
Comment (flowbehappy) [inline dbms/src/Storages/DeltaMerge/StoragePool.cpp:204]: We don't use assert in normal logic besides test cases. Manually throw exceptions instead.

Comment (jiaqizho) [reply dbms/src/Storages/DeltaMerge/StoragePool.cpp:204]: That make no sense if `log_max_ids.size() != 1`. And I don't think using `exception` replace `assert` is a good thing.
IMO: 
1. If it's logically clear and you do know it inited where. Then used `assert` to check .
2. If some value changes a lot of time, Then the `exception` will replace the `assert` to avoid some problems.

So back to this `assert`, it's clear to know that `log_max_ids` from V2 must have `size 1`. So I think just adding an assert is ok to avoid logical error?

File: dbms/src/Storages/Page/V2/PageStorage.cpp [hunk 7]
```diff
@@ -349,17 +349,14 @@ void PageStorage::restore()
...
-        size_t num_pages = snapshot->version()->numPages();
-        LOG_FMT_INFO(log, "{} restore {} pages, write batch sequence: {}, {}", storage_name, num_pages, write_batch_seq, statistics.toString());
-    }
-}
 
-PageId PageStorage::getMaxId(NamespaceId /*ns_id*/)
-{
-    std::lock_guard write_lock(write_mutex);
-    return versioned_page_entries.getSnapshot("")->version()->maxId();
+    // No need lock here
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V2/PageStorage.cpp:353]:
```suggestion
```

File: dbms/src/Storages/Page/PageStorage.h [hunk 8]
```diff
@@ -211,12 +211,18 @@ class PageStorage : private boost::noncopyable
...
 
-    virtual void restore() = 0;
+    // Return the map[ns_id, max_applied_page_id]
+    // The different between max_applied_page_id and max_page_id is that:
+    //
+    // 1. In V2, it means same thing.
+    // Also ns_id will be 0, because V2 will not use ns_id to distinguish different tables
+    // 2. In V3, max_applied_page_id can be a del id. In V3, we do not allow writebatch type reuse of the same page_id.
+    // So we need get the max_page_id before MVCC do the memory GC.
+    // The max_page_id before MVCC GC in restore, we called max_applied_page_id.
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/PageStorage.h:221]:
```suggestion
    // Return the map[ns_id, max_page_id]
    // The caller should ensure that it only allocate new id that is larger than `max_page_id`. Reusing the
    // same ID for different kind of write (put/ref/put_external) would make PageStorage run into unexpected error.
    //
    // Note that for V2, we always return a map with only one element: <ns_id=0, max_id> cause V2 have no
    // idea about ns_id.
```

**Review by JaySon-Huang — APPROVED** [review]
LGTM with small comment

File: dbms/src/Storages/DeltaMerge/StoragePool.cpp (hunk 6 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/DeltaMerge/StoragePool.cpp:204]: I think assert is OK here
