### PR TITLE
Storages: fix a series of data race issues

### LINKED ISSUE #9961: Thread Sanitizer Failure
## Bug Report

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/2489/pipeline

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #9961

Problem Summary:

### What is changed and how it works?

```commit-message
1. We should not reuse anything which is not thread-safe between different queries, so do not reuse `ann_query_info` in unit tests.
2. Fix `FileCache::bgDownload` may still be running after `FileCache::shutdown`.
3. Suppress false positive alarm in `~shared_ptr`  and `re2::RE2::NumberOfCapturingGroups`.
4. Suppress alarm in `TiFlashStorageTestBasic::reload` which is only used in unit tests.
5. Fix data race between `DeltaMergeStore::segmentWaitDeltaLocalIndexReady` and `ColumnFilePersistedSet::updatePersistedColumnFilesAfterAddingIndex`
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Run the unit test cases with TSAN built binary
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix a data race issue by waiting for all background task done when shutting down under disagg arch
```

### CODE REVIEW

File: dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp [hunk 1]
```diff
@@ -965,10 +965,11 @@ bool DeltaMergeStore::segmentWaitDeltaLocalIndexReady(const SegmentPtr & segment
         {
             for (const auto & column_file : column_file_persisted_set->getFiles())
             {
-                auto * tiny_file = column_file->tryToTinyFile();
-                if (!tiny_file)
-                    continue;
-                all_indexes_built = all_indexes_built && (tiny_file->hasIndex(index.index_id));
+                if (auto * tiny_file = column_file->tryToTinyFile(); tiny_file)
```
[the remark this answers is not in the document]
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp:968]: thread A try to update index_info in tiny_file, meanwhile thread B call `hasIndex`

File: dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp [hunk 2]
```diff
@@ -383,14 +383,20 @@ bool DeltaValueSpace::flush(DMContext & context)
         return true;
     }
 
+    String simple_info;
+    {
+        std::scoped_lock lock(mutex);
+        simple_info = simpleInfo();
```
[the remark this answers is not in the document]
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp]: fixed

File: dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp:968]: Just lock `DeltaValueSpace` is ok. `segmentWaitDeltaLocalIndexReady` only used in UT.

File: dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp [hunk 3]
```diff
@@ -276,18 +283,14 @@ try
             stream,
             createColumnNames(),
             createColumnData({
-                createColumn<Int64>({2}),
-                createVecFloat32Column<Array>({{1.0, 2.0, 3.5}}),
+                createColumn<Int64>({0}),
+                createVecFloat32Column<Array>({{1.0, 2.0, 3.0}}),
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp:287]: why the result in here is changed?

File: dbms/src/Storages/S3/FileCache.h [hunk 4]
```diff
@@ -228,7 +230,19 @@ class FileCache
...
+    // When the task is scheduled in another thread, it will try to lock the weak_ptr to get the shared_ptr.
+    // If the global_file_cache_instance is destructed before the task is scheduled, the weak_ptr will be expired.
+    // If there are still tasks running, the `global_file_cache_instance` should wait until all tasks are finished.
+    static void shutdown()
+    {
+        global_file_cache_initialized.store(false, std::memory_order_release);
+        while (global_file_cache_instance.use_count() > 1)
+        {
+            std::this_thread::sleep_for(std::chrono::milliseconds(10));
+        }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/S3/FileCache.h:243]: What about add a `S3FileCachePool::shutdown()` here instead if making `global_file_cache_instance` a shared_ptr? That shutdown should wait until all the job in `S3FileCachePool` finished.
https://github.com/pingcap/tiflash/blob/3cda2f61923f47c89db026bd118eded90e76c625/dbms/src/Common/UniThreadPool.cpp#L236-L260

File: dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp (hunk 3 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp]: A naive mistake made by AI, fixed.

File: dbms/src/Storages/S3/FileCache.h (hunk 4 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/S3/FileCache.h]: fixed

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h [hunk 5]
```diff
@@ -50,15 +50,15 @@ class ColumnFileTiny : public ColumnFilePersisted
...
+    const PageIdU64 data_page_id;
 
     /// HACK: Currently this field is only available when ColumnFileTiny is restored from remote proto.
     /// It is not available when ColumnFileTiny is constructed or restored locally.
     /// Maybe we should just drop this field, and store the data_page_size in somewhere else.
     UInt64 data_page_size = 0;
 
     /// The index information of this file.
-    IndexInfosPtr index_infos;
+    const IndexInfosPtr index_infos;
```
[the remark this answers is not in the document]
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h:61]: fixed.

File: dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp [hunk 6]
```diff
@@ -961,14 +963,16 @@ bool DeltaMergeStore::segmentWaitDeltaLocalIndexReady(const SegmentPtr & segment
         if (!column_file_persisted_set)
             return false; // ColumnFilePersistedSet is not exist, return false
         bool all_indexes_built = true;
-        for (const auto & index : *build_info.indexes_to_build)
         {
-            for (const auto & column_file : column_file_persisted_set->getFiles())
+            auto lock = delta_weak_ptr.lock()->getLock();
```
[the remark this answers is not in the document]
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp]: fixed

[the remark this answers is not in the document]
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp]: Unexpected behavior, just crash.

**Comment by JaySon-Huang** [comment]
> Fix the existing index infoes in ColumnFileTiny are missed after add new indexes.

I think you need a separate issue and fix PR for this problem

File: dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp]: It is a function which only used in UT.

**Comment by Lloyd-Pottiger** [comment]
> > Fix the existing index infoes in ColumnFileTiny are missed after add new indexes.
> 
> I think you need a separate issue and fix PR for this problem

Open a separate, but IMO fix in this PR is ok, since other changes also need pick to release-8.5.

File: dbms/src/Storages/S3/FileCache.h [hunk 7]
```diff
@@ -228,7 +229,11 @@ class FileCache
                                                                              : nullptr;
     }
 
-    static void shutdown() { global_file_cache_instance = nullptr; }
+    static void shutdown()
+    {
+        S3FileCachePool::shutdown();
```
Comment (JaySon-Huang) [inline dbms/src/Storages/S3/FileCache.h:234]:
```suggestion
        // wait for all tasks done
        S3FileCachePool::shutdown();
```

File: dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp [hunk 8]
```diff
@@ -958,6 +896,111 @@ try
...
+
+    // write [0, 128) to store
+    write(0, num_rows_write);
+    // trigger mergeDelta for all segments
+    triggerMergeDelta();
+
+    // write [128, 256) to store
+    write(num_rows_write, num_rows_write * 2);
+
+    // trigger FlushCache for all segments
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp:918]:
```suggestion
    // trigger FlushCache for all segments
    // so that some data are stored at DeltaVS's persisted_file_set
    // that will build vector index
```

File: dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp [hunk 9]
```diff
@@ -958,6 +896,111 @@ try
...
+            index.vector_index = TiDB::VectorIndexDefinitionPtr(new TiDB::VectorIndexDefinition{
+                .kind = tipb::VectorIndexKind::HNSW,
+                .dimension = 1,
+                .distance_metric = metrics[i],
+            });
+            new_table_info_with_vector_index.index_infos.emplace_back(index);
+        }
+        // apply local index change, shuold
+        // - create the local index
+        // - generate the background tasks for building index on stable
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp:944]:
```suggestion
        // - generate the background tasks for building index on stable and delta
```

File: dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp [hunk 10]
```diff
@@ -958,6 +896,111 @@ try
...
+        {
+            const auto ann_query_info = createANNQueryInfo(vec_column_id, metric, 1, {222.1}, index_id);
+            auto filter = std::make_shared<PushDownExecutor>(ann_query_info);
+
+            read(range, filter, createVecFloat32Column<Array>(result_2));
+        }
+    };
+
+    // Add COSINE vector index
+    add_vector_index({1}, {tipb::VectorDistanceMetric::COSINE});
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp:982]: Maybe call `DeltaMergeStore::getStoreStats` and check that StableVS and DeltaVS has built vector index?

File: dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp [hunk 11]
```diff
@@ -961,16 +964,23 @@ bool DeltaMergeStore::segmentWaitDeltaLocalIndexReady(const SegmentPtr & segment
         if (!column_file_persisted_set)
             return false; // ColumnFilePersistedSet is not exist, return false
         bool all_indexes_built = true;
-        for (const auto & index : *build_info.indexes_to_build)
+        if (auto lock = delta_weak_ptr.lock()->getLock(); lock)
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp:967]: If `delta_weak_ptr.lock()` return nullptr, we'd better let it throw exception or let it return false to skip the task rather than just crash

File: dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp (hunk 8 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp:918]: no, there is no index info yet.

**Comment by JaySon-Huang** [comment]
/hold
wait for https://github.com/pingcap/tiflash/pull/9975 merge first

File: dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp (hunk 10 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp:982]: If there is no index, all rows will be returned, so just check the query result is enough.

**Review by JaySon-Huang — APPROVED** [review]
LGTM
