### PR TITLE
KVStore: neglect TransferLeader for nextgen compatibility

### LINKED ISSUE #10734: [next gen] TiFlash crash for unsupported admin command type TransferLeader
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2026/03/06 06:02:16.864 +08:00] [FATAL] [Exception.cpp:98] ["Code: 49, e.displayText() = DB::Exception: unsupported admin command type TransferLeader, e.what() = DB::Exception, Stack trace:\n\n\n  0x55c6840a1f33\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) [tiflash+37682995]\n                \tdbms/src/Common/StackTrace.cpp:25\n  0x55c68bc1638f\tDB::RegionRaftCommandDelegate::handleAdminRaftCmd(raft_cmdpb::AdminRequest const&, raft_cmdpb::AdminResponse const&, unsigned long, unsigned long, DB::KVStore const&, DB::RegionTable&, DB::RaftCommandResult&) [tiflash+167134095]\n                \tdbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp:280\n  0x55c68bc1edbb\tDB::KVStore::handleAdminRaftCmd(raft_cmdpb::AdminRequest&&, raft_cmdpb::AdminResponse&&, unsigned long, unsigned long, unsigned long, DB::TMTContext&) [tiflash+167169467]\n                \tdbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp:221\n  0x55c68bba8a69\tHandleAdminRaftCmd [tiflash+166685289]\n                \tdbms/src/Storages/KVStore/FFI/ProxyFFI.cpp:123\n  0x7fc5efd43791\tproxy_ffi::engine_store_helper_impls::_$LT$impl$u20$proxy_ffi..interfaces..root..DB..EngineStoreServerHelper$GT$::handle_admin_raft_cmd::h9c07ce60e70cf0c9 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+26273681]\n  0x7fc5efe5e8ae\t_$LT$engine_store_ffi..observer..TiFlashObserver$LT$T$C$ER$GT$$u20$as$u20$raftstore..coprocessor..AdminObserver$GT$::post_exec_admin::h3efae9ab297f22e1 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+27433134]\n  0x7fc5f0c1c740\traftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::process_raft_cmd::hccf4673cefb05378 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+41842496]\n  0x7fc5f0c24123\traftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::handle_raft_committed_entries::h99122f5e14aa60c4 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+41873699]\n  0x7fc5f0bfd139\traftstore::store::fsm::apply::ApplyFsm$LT$EK$GT$::handle_apply::h5ebdbdc48ab0c9d5 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+41713977]\n  0x7fc5f0c01993\traftstore::store::fsm::apply::ApplyFsm$LT$EK$GT$::handle_tasks::h297e23ede1b5b1f0 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+41732499]\n  0x7fc5eff6cbe5\t_$LT$raftstore..store..fsm..apply..ApplyPoller$LT$EK$GT$$u20$as$u20$batch_system..batch..PollHandler$LT$raftstore..store..fsm..apply..ApplyFsm$LT$EK$GT$$C$raftstore..store..fsm..apply..ControlFsm$GT$$GT$::handle_normal::h94499c390d84dbe7 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+28539877]\n  0x7fc5efedfa25\tbatch_system::batch::Poller$LT$N$C$C$C$Handler$GT$::poll::h3cfc6addfa4de40c [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+27961893]\n  0x7fc5effa4945\tstd::sys_common::backtrace::__rust_begin_short_backtrace::h20f7ac87f05251c9 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+28768581]\n  0x7fc5efff6e89\tcore::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h28a824920b627230 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+29105801]\n  0x7fc5f1560246\tstd::sys::unix::thread::Thread::new::thread_start::hd01330a228cdd35d [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+51556934]\n                \t/rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/)\n  0x7fc5ee0f02ea\tstart_thread [libc.so.6+570090]\n  0x7fc5ee1753c0\t__GI___clone3 [libc.so.6+1115072]"] [source="EngineStoreApplyRes DB::HandleAdminRaftCmd(const EngineStoreServerWrap *, BaseBuffView, BaseBuffView, RaftCmdHeader)"] [thread_id=67]
```

### 4. What is your TiFlash version? (Required)
Welcome to TiFlash"] [thread_id=1]                                                                                                                                       
TiFlash build info: TiFlash\nRelease Version: v9.0.0-beta.2.pre-126-g661e9b588\nEdition:         Enterprise\nGit Commit Hash: 661e9b5887144636797a3e6e583d5a383ebfd17e\nG
p"] [source=Application]

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #10734

Problem Summary:

neglect TransferLeader for next-gen compatibility. Also downgrade logging level about transfer leader from error to info

* https://github.com/pingcap/tidb-engine-ext/pull/451
* https://github.com/tidbcloud/cloud-storage-engine/pull/4720

### What is changed and how it works?

```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved handling of admin commands (including TransferLeader and peer update flows) to avoid unnecessary operations during leadership and peer transitions.

* **Tests**
  * Added test coverage validating TransferLeader routing and adjusted test flow to reflect the new handling.

### CODE REVIEW

File: dbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp [hunk 1]
```diff
@@ -183,6 +183,9 @@ EngineStoreApplyRes KVStore::handleAdminRaftCmd(
     case raft_cmdpb::AdminCmdType::PrepareFlashback:
     case raft_cmdpb::AdminCmdType::FinishFlashback:
     case raft_cmdpb::AdminCmdType::BatchSwitchWitness:
+    // Initialy, with tiflash-proxy, TransferLeader will be rewrited into empty write cmd,
+    // so this case is not possible. However, nextgen-proxy implements in another way, so we have to workaround here.
+    case raft_cmdpb::AdminCmdType::TransferLeader:
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp:188]: Do we need to ignore the `InvalidAdmin` and `UpdateGcPeer` too?
https://github.com/pingcap/tiflash/issues/10734#issuecomment-4011095361

Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp:188]: fixed

File: dbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp [hunk 2]
```diff
@@ -183,6 +183,10 @@ EngineStoreApplyRes KVStore::handleAdminRaftCmd(
     case raft_cmdpb::AdminCmdType::PrepareFlashback:
     case raft_cmdpb::AdminCmdType::FinishFlashback:
     case raft_cmdpb::AdminCmdType::BatchSwitchWitness:
+    // Initialy, with tiflash-proxy, TransferLeader will be rewrited into empty write cmd,
+    // so this case is not possible. However, nextgen-proxy implements in another way, so we have to workaround here.
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp]:
```suggestion
    // so this case is not possible. However, tiflash-proxy-next-gen will dispatch the TransferLeader to tiflash, so we have to workaround here.
```

**Comment by JaySon-Huang** [comment]
Wait for the proxy logging downgrade pr to be merged. In order to reduce the efforts to do when cherry-pick
