### PR TITLE
join be aware of cancel signal

### LINKED ISSUE #9430: join should be aware of cancel signal
## Bug Report

Please answer these questions before submitting your issue. Thanks!
Currently, inside `join`, it does not aware of cancel signal, so if you wants to cancel a query that contains `join`, it can only wait until `joinBlock` returns

https://github.com/pingcap/tiflash/blob/v8.3.0/dbms/src/Interpreters/Join.h#L201

If `joinBlock()` takes a long time(it could happen in some extrame cases, like cross join with a lot of build side data), the query can not be cancelled for a long time

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #9430

Problem Summary:

### What is changed and how it works?
Check cancel signal inside join
```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Cancel a query with a cross join
```
mysql> select count(*) from t1;
+----------+
| count(*) |
+----------+
|  8000392 |
+----------+
mysql> explain select count(*) from t1 where id not in (select id from t1);
+------------------------------------------+------------+--------------+---------------+-----------------------------------------------------------------+
| id                                       | estRows    | task         | access object | operator info                                                   |
+------------------------------------------+------------+--------------+---------------+-----------------------------------------------------------------+
| HashAgg_35                               | 1.00       | root         |               | funcs:count(Column#8)->Column#7                                 |
| └─TableReader_37                         | 1.00       | root         |               | MppVersion: 2, data:ExchangeSender_36                           |
|   └─ExchangeSender_36                    | 1.00       | mpp[tiflash] |               | ExchangeType: PassThrough                                       |
|     └─HashAgg_13                         | 1.00       | mpp[tiflash] |               | funcs:count(1)->Column#8                                        |
|       └─HashJoin_34                      | 6400313.60 | mpp[tiflash] |               | CARTESIAN anti semi join, other cond:eq(test.t1.id, test.t1.id) |
|         ├─ExchangeReceiver_21(Build)     | 8000392.00 | mpp[tiflash] |               |                                                                 |
|         │ └─ExchangeSender_20            | 8000392.00 | mpp[tiflash] |               | ExchangeType: Broadcast, Compression: FAST                      |
|         │   └─TableFullScan_19           | 8000392.00 | mpp[tiflash] | table:t1      | keep order:false                                                |
|         └─TableFullScan_18(Probe)        | 8000392.00 | mpp[tiflash] | table:t1      | keep order:false                                                |
+------------------------------------------+------------+--------------+---------------+-----------------------------------------------------------------+
```

Before this pr
屏幕截图 2024-09-20 165644

After this pr
屏幕截图 2024-09-20 170114

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix bug that join can not be cancelled timely.
```

### CODE REVIEW

File: dbms/src/Interpreters/Join.cpp [hunk 1]
```diff
@@ -1486,6 +1488,10 @@ Block Join::joinBlockCross(ProbeProcessInfo & probe_process_info) const
 
     while (true)
     {
+        if (is_cancelled())
+        {
+            return {};
+        }
```
Comment (gengliqi) [inline dbms/src/Interpreters/Join.cpp:1494]:
``` suggestion
            return {};
```

**Review by yibin87 — APPROVED** [review]
LGTM
