### PR TITLE
*: fix tipb::ColumnInfo to TiDB::ColumnInfo

### LINKED ISSUE #9084: Wrong default value behavior in disaggregated mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```shell
tiup playground:nightly nightly --mode=tidb-cse
```

```
mysql> create table c(a int);
Query OK, 0 rows affected (0.06 sec)

mysql> insert into c values (1);
Query OK, 1 row affected (0.00 sec)

mysql> alter table c set tiflash replica 1;
Query OK, 0 rows affected (0.04 sec)

mysql> select * from information_schema.tiflash_replica;
+--------------+------------+----------+---------------+-----------------+-----------+----------+
| TABLE_SCHEMA | TABLE_NAME | TABLE_ID | REPLICA_COUNT | LOCATION_LABELS | AVAILABLE | PROGRESS |
+--------------+------------+----------+---------------+-----------------+-----------+----------+
| test         | c          |      104 |             1 |                 |         1 |        1 |
+--------------+------------+----------+---------------+-----------------+-----------+----------+
1 row in set (0.00 sec)

mysql> alter table c add column test_c1 int default 0;
Query OK, 0 rows affected (0.10 sec)

mysql> set @@tidb_isolation_read_engines="tidb,tiflash";
Query OK, 0 rows affected (0.00 sec)

mysql> select count(*) from c where test_c1 = 0;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.04 sec)

mysql> select count(*) from c where test_c1 is null;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.01 sec)

mysql> set @@tidb_isolation_read_engines="tidb,tikv";
Query OK, 0 rows affected (0.00 sec)

mysql> select count(*) from c where test_c1 = 0;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.01 sec)

mysql> select count(*) from c where test_c1 is null;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.01 sec)
```

### 2. What did you expect to see? (Required)

TiFlash and TiKV should produce same result.

### 4. What is your TiFlash version? (Required)

nightly

### LINKED ISSUE #9085: Disaggrate TiFlash query result is wrong when query missing columns with default value
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
CREATE TABLE `relationships` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id2` int(11) NOT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci AUTO_INCREMENT=90001;
insert into relationships (id2) values (1), (2), (3);
insert into relationships (id2) select id2 from relationships;
insert into relationships (id2) select id2 from relationships;
insert into relationships (id2) select id2 from relationships;
insert into relationships (id2) select id2 from relationships;
insert into relationships (id2) select id2 from relationships;
insert into relationships (id2) select id2 from relationships;
alter table relationships set tiflash replica 1;
alter table relationships add column weight int default '0';
select * from information_schema.tiflash_replica where TABLE_NAME = 'relationships';
set @@tidb_isolation_read_engines='tiflash'; select count(*) from relationships where weight = 0;
```

### 2. What did you expect to see? (Required)

```
set @@tidb_isolation_read_engines='tiflash'; select count(*) from relationships where weight = 0;
+----------+
| count(*) |
+----------+
|      192 |
+----------+
```

### 3. What did you see instead (Required)

```
set @@tidb_isolation_read_engines='tiflash'; select count(*) from relationships where weight = 0;
+----------+
| count(*) |
+----------+
|      0 |
+----------+
```

### 4. What is your TiFlash version? (Required)
master

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #9084

Problem Summary:

### What is changed and how it works?

```commit-message
fix the issue that query result may be wrong when query missing columns with default value in Disaggrate TiFlash.
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the issue that query result may be wrong when query missing columns with default value in Disaggrate TiFlash.
```

### CODE REVIEW

File: dbms/src/TiDB/Schema/TiDB.cpp [hunk 1]
```diff
@@ -1264,6 +1264,8 @@ ColumnInfo toTiDBColumnInfo(const tipb::ColumnInfo & tipb_column_info)
     tidb_column_info.flag = tipb_column_info.flag();
     tidb_column_info.flen = tipb_column_info.columnlen();
     tidb_column_info.decimal = tipb_column_info.decimal();
+    tidb_column_info.origin_default_value = tipb_column_info.default_val();
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDB.cpp:1267]: add comments about why we need to set `origin_default_value` but not `default_value`

File: dbms/src/TiDB/Schema/TiDB.cpp [hunk 2]
```diff
@@ -1264,6 +1264,10 @@ ColumnInfo toTiDBColumnInfo(const tipb::ColumnInfo & tipb_column_info)
     tidb_column_info.flag = tipb_column_info.flag();
     tidb_column_info.flen = tipb_column_info.columnlen();
     tidb_column_info.decimal = tipb_column_info.decimal();
+    // TiFlash get default value from origin_default_value, check `Field ColumnInfo::defaultValueToField() const`
+    // So we need to set origin_default_value to tipb_column_info.default_val()
```
Comment (JaySon-Huang) [inline dbms/src/TiDB/Schema/TiDB.cpp:1268]:
```suggestion
    // TiFlash get default value from origin_default_value, check `Field ColumnInfo::defaultValueToField() const`
    // So we need to set origin_default_value to tipb_column_info.default_val()
    // Related logic in tidb, https://github.com/pingcap/tidb/blob/45318da24d8e4c0c6aab836d291a33f949dd18bf/pkg/table/tables/tables.go#L2303-L2329
```

**Review by JaySon-Huang — APPROVED** [review]
