### PR TITLE
Fix memory leak in aggregation function in window

### LINKED ISSUE #9930: Memory leak in aggregation function in window
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. build tiflash ut with address sanitizer
2. run the following tests
  - ExecutorWindowAgg.Min
  - ExecutorWindowAgg.Max
  - WindowAggFuncTest.Min
  - WindowAggFuncTest.Max
 

### 2. What did you expect to see? (Required)

no leak

### 3. What did you see instead (Required)

leak

### 4. What is your TiFlash version? (Required)

nightly(d6de21220a809456)

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #9930

Problem Summary:

### What is changed and how it works?

```commit-message

```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix memory leak in aggregation function in window
```

### CODE REVIEW

**Review by windtalker — COMMENTED** [review]
no test?

File: dbms/src/AggregateFunctions/tests/gtest_window_agg.cpp [hunk 1]
```diff
@@ -662,6 +662,8 @@ void ExecutorWindowAgg::executeWindowAggTest(TestCase<Op> & test_case)
         }
     }
 
+    agg_func->reset(agg_state.data());
```
Comment (windtalker) [inline dbms/src/AggregateFunctions/tests/gtest_window_agg.cpp:665]: why not use destroy here?

Comment (xzhangxian1008) [reply dbms/src/AggregateFunctions/tests/gtest_window_agg.cpp]: > why not use destroy here?

done

**Comment by xzhangxian1008** [comment]
> no test?

Origin tests could cover the memory leak case.

**Review by windtalker — APPROVED** [review]
lgtm

**Review by yibin87 — APPROVED** [review]
LGTM
