### PR TITLE
*: Fix allocateptr call from Proxy

### LINKED ISSUE #9038: Panic when allocate memory
## Bug Report

Please answer these questions before submitting your issue. Thanks!

```

    
{"namespace":"endless-htap-spill-random-failpoint-tps-7578098-1-153","level":"ERROR","log":"[BaseDaemon.cpp:560] [\"
       0xb34613d    faultSignalHandler(int, siginfo_t*, void*) [tiflash+187982141]
                    libs/libdaemon/src/BaseDaemon.cpp:211
  0x7f189d080db0    <unknown symbol> [libc.so.6+347568]
       0xb6d20dc    std::__1::shared_ptr<DB::JointThreadInfoJeallocMap>::operator->() const [tiflash+191701212]
                    /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:586
       0xcbe183c    DB::KVStore::reportThreadAllocBatch(std::__1::basic_string_view<char, std::__1::char_traits<char> >, DB::ReportThreadAllocateInfoBatch) [tiflash+213784636]
                    dbms/src/Storages/KVStore/KVStore.cpp:500
       0xcc493b5    ReportThreadAllocateBatch [tiflash+214209461]
                    dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp:1065
  0x7f18a6b9fad3    proxy_ffi::engine_store_helper_impls::_$LT$impl$u20$proxy_ffi..interfaces..root..DB..EngineStoreServerHelper$GT$::directly_report_jemalloc_alloc::_$u7b$$u7b$closure$u7d$$u7d$::h5a934a3fae521d24 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+158964435]
                    contrib/tiflash-proxy/proxy_components/proxy_ffi/src/[engine_store_helper_impls.rs:126](http://engine_store_helper_impls.rs:126/)
  0x7f18a6b61db9    std::thread::local::LocalKey$LT$T$GT$::try_with::h2738826456343c58 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+158711225]
                    /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/thread/[local.rs:446](http://local.rs:446/)
  0x7f18a6b613d4    std::thread::local::LocalKey$LT$T$GT$::with::h2465f6bf8302d3ab [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+158708692]
                    /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/thread/[local.rs:422](http://local.rs:422/)
  0x7f18a6b8d5b5    proxy_ffi::engine_store_helper_impls::_$LT$impl$u20$proxy_ffi..interfaces..root..DB..EngineStoreServerHelper$GT$::directly_report_jemalloc_alloc::hdd4749ff932e4711 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+158889397]
                    contrib/tiflash-proxy/proxy_components/proxy_ffi/src/[engine_store_helper_impls.rs:111](http://engine_store_helper_impls.rs:111/)
  0x7f18a6b8d93f    proxy_ffi::engine_store_helper_impls::_$LT$impl$u20$proxy_ffi..interfaces..root..DB..EngineStoreServerHelper$GT$::handle_get_engine_store_server_status::ha6984cf31bf144cc [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+158890303]
                    contrib/tiflash-proxy/proxy_components/proxy_ffi/src/[engine_store_helper_impls.rs:189](http://engine_store_helper_impls.rs:189/)
  0x7f18a1c1747d    proxy_server::run::run_impl::h962ac6a36e3ad152 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+75568253]
                    contrib/tiflash-proxy/proxy_components/proxy_server/src/[run.rs:267](http://run.rs:267/)
  0x7f18a1c29b92    proxy_server::run::run_tikv_proxy::h720991976c6255d7 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+75643794]
                    contrib/tiflash-proxy/proxy_components/proxy_server/src/[run.rs:389](http://run.rs:389/)
  0x7f18a1c0906c    proxy_server::proxy::run_proxy::h94e865f8dce71ddb [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+75509868]
                    contrib/tiflash-proxy/proxy_components/proxy_server/src/[proxy.rs:325](http://proxy.rs:325/)
  0x7f18a0aea0e8    run_raftstore_proxy_ffi [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+57557224]
                    contrib/tiflash-proxy/raftstore-proxy/src/[lib.rs:19](http://lib.rs:19/)
       0x48e2632    DB::RaftStoreProxyRunner::runRaftStoreProxyFFI(void*) [tiflash+76424754]
                    dbms/src/Server/Server.cpp:530
  0x7f189d0cb802    start_thread [libc.so.6+653314]\"] [source=BaseDaemon] [thread_id=118]","pod":"tc-tiflash-0","container":"data0"}
```

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #9038

Problem Summary:

The `global_context` will be released before proxy_runner ends, which make `tiflash_instance_wrap.tmt` be a dangling pointer when shutting down

### What is changed and how it works?

Reset the `tiflash_instance_wrap.tmt` before `global_context` get released

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/KVStore/KVStore.cpp [hunk 1]
```diff
@@ -497,7 +497,8 @@ void KVStore::reportThreadAllocInfo(std::string_view v, ReportThreadAllocateInfo
 
 void KVStore::reportThreadAllocBatch(std::string_view v, ReportThreadAllocateInfoBatch data)
 {
-    joint_memory_allocation_map->reportThreadAllocBatchForKVStore(v, data);
+    // Initialize Context before RaftStoreProxyRunner, if it should be changed into non-static method.
+    JointThreadInfoJeallocMap::reportThreadAllocBatchForKVStore(v, data);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/KVStore.cpp:501]: I don't get it.

If KVStore is not inited, then it should be block by 
https://github.com/pingcap/tiflash/blob/23784449d406b46009ce7e63f7eea547ac76d621/dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp#L1062-L1065

If KVStore is inited, then there is no code to reset `joint_memory_allocation_map`?

https://github.com/pingcap/tiflash/blob/23784449d406b46009ce7e63f7eea547ac76d621/dbms/src/Storages/KVStore/KVStore.cpp#L56-L76

File: dbms/src/Storages/KVStore/KVStore.cpp
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/KVStore.cpp:1]: we should revert these change? This is not the root cause

Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/KVStore.cpp:1]: Yes, no root cause here. However, it could still be made to `static`

Comment (JaySon-Huang) [reply dbms/src/Storages/KVStore/KVStore.cpp:1]: If we make the method static, then I'll keep the opinion that we should remove the `KVStore::joint_memory_allocation_map` and only keep the `global_context::joint_memory_allocation_map`

Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/KVStore.cpp:1]: https://github.com/pingcap/tiflash/pull/9003#discussion_r1595075949 is for recordThreadAllocInfo which relies on the lifetime of joint_memory_allocation_map. reportThreadAllocBatch does not rely on the life of joint_memory_allocation_map.

However, whether use `static` makes no differences for now in function. I can change back to non-static.

**Review by yibin87 — APPROVED** [review]
LGTM

File: dbms/src/Server/Server.cpp [hunk 2]
```diff
@@ -1085,6 +1085,13 @@ int Server::main(const std::vector<std::string> & /*args*/)
       *  settings, available functions, data types, aggregate functions, databases...
       */
     global_context = Context::createGlobal();
+    SCOPE_EXIT({
+        if (!proxy_conf.is_proxy_runnable)
+            return;
+
+        LOG_INFO(log, "Unlink tiflash_instance_wrap.tmt");
+        tiflash_instance_wrap.tmt = nullptr;
```
Comment (JaySon-Huang) [inline dbms/src/Server/Server.cpp:1093]:
```suggestion
        // Reset the `tiflash_instance_wrap.tmt` before `global_context` get released, or it will be a dangling pointer
        tiflash_instance_wrap.tmt = nullptr;
```

**Review by JaySon-Huang — APPROVED** [review]
LGTM
