### PR TITLE
Donot reserve memory for non-fixed type columns in decodeAndSquash

### LINKED ISSUE #7416: String column decode reserved much larger memory than needed
## Bug Report

When decode columns, we use IColumn's reserve(size_t rows) interface to avoid reallocating memories each time. However, for string columns, the element size is not fixed, and we used 64 bytes as default value. This will lead to much larger memory usage when actual element size is much smaller than 64 bytes.
This problem will be worsen for Join operator, since build side's all blocks will be in memory for a while.

### PR DESCRIPTION
**Pull request by yibin87**
### What problem does this PR solve?

Issue Number: close #7416 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the issue that the query might use much larger memories than actual needed when Join build side data is very large and contains many small-size string type columns. 
```

### CODE REVIEW

File: dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp [hunk 1]
```diff
@@ -96,12 +97,20 @@ static inline void decodeColumnsByBlock(ReadBuffer & istr, Block & res, size_t r
...
-        else
-            column->reserve(rows_to_read + column->size());
+    const auto & name_and_type_list = res.getColumnsWithTypeAndName();
+    size_t column_size = mutable_columns.size();
+    for (size_t i = 0; i < column_size; ++i)
+    {
+        auto && column = mutable_columns[i];
+        /// For non-fixed size type, reserve function might cause too much memory usage, i.e. string type column reserves 64 bytes
+        /// size for each element.
+        if (removeNullable(name_and_type_list[i].type)->isValueUnambiguouslyRepresentedInFixedSizeContiguousMemoryRegion())
```
Comment (windtalker) [inline dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp:107]: maybe add a new function? `isValueUnambiguouslyRepresentedInFixedSizeContiguousMemoryRegion` return `false` for `decimal64` based type

File: dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp [hunk 2]
```diff
@@ -96,12 +97,20 @@ static inline void decodeColumnsByBlock(ReadBuffer & istr, Block & res, size_t r
...
-        if (reserve_size > 0)
-            column->reserve(std::max(rows_to_read, reserve_size));
-        else
-            column->reserve(rows_to_read + column->size());
+    const auto & name_and_type_list = res.getColumnsWithTypeAndName();
+    size_t column_size = mutable_columns.size();
+    for (size_t i = 0; i < column_size; ++i)
+    {
+        auto && column = mutable_columns[i];
+        /// For non-fixed size type, reserve function might cause too much memory usage, i.e. string type column reserves 64 bytes
```
Comment (solotzg) [inline dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp:105]: Maybe we can change the codec format and add field about data size for the columns with non-fixed size type. But such way need to change codec & mpp version.

Comment (yibin87) [reply dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp:105]: Yes, nice suggestion, I plan to introduce some mechanism to "guess" the every data size, since we need to reserve the column size before knowning how many blocks will be squashed.

**Review by solotzg — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM
