### PR TITLE
Fix an invalid default value cause bootstrap failed

### LINKED ISSUE #3157: Bootstrap failed because of an invalid default value to the corresponding type
TiFlash build info: TiFlash\nRelease Version: v5.1.1\nEdition:         Community\nGit Commit Hash: c8fabfb50fe28db17cc5118133a69be255c40efd\nGit Branch:      heads/refs/tags/v5.1.1\nUTC Build Time:  2021-07-28 11:18:00\nProfile:         RELWITHDEBINFO

```
[2021/09/26 19:30:33.375 +08:00] [INFO] [<unknown>] ["SchemaBuilder: Creating table db_ysb_salesmen(26465).ts_salesmen_task(28972) with statement: CREATE TABLE `db_26465`.`t_28972`(`user_id` Int32, `month` Int32, `user_type` Int8, `sys_cash` Decimal(16,2), `individual_cash` Decimal(10,2), `indiv_cash_fr` Decimal(10,2), `indiv_cash_fr_min` Decimal(10,2), `sys_group_cash` Decimal(16,2), `group_cash` Decimal(16,2), `group_cash_fr` Decimal(16,2), `individ_store_cash` Decimal(10,2), `group_store_cash` Decimal(16,2), `individ_hall_cash` Decimal(10,2), `group_hall_cash` Decimal(16,2), `adjust_cash` Decimal(10,2), `sys_store_cnt` UInt32, `indiv_store_cnt` UInt32, `indiv_store_cnt_wt` Decimal(5,4), `sys_group_store_cnt` UInt32, `group_store_cnt` UInt32, `sys_new_store_cnt` Int32, `indiv_new_store_cnt` Int32, `indiv_new_store_cnt_wt` Decimal(5,4), `sys_group_new_store_cnt` Int32, `group_new_store_cnt` Int32, `group_signed_store_cnt` Int32, `indiv_signed_store_cnt` Int32, `sys_struct_cnt` Int32, `indiv_struct_cnt` Int32, `indiv_struct_cnt_wt` Decimal(5,4), `sys_group_struct_cnt` Int32, `group_struct_cnt` Int32, `struct_stage` Int32, `mtime` MyDateTime(0), `ctime` Int32, `indiv_self_cash` Int32, `group_self_cash` Int32, `individ_proxy_cash` Decimal(8,2), `individ_proxy_drug` Int16, `b_spe_user` Int8, `b_spe_cash` Int8, `spe_dis_cash` Decimal(10,2), `b_spe_cnt` Int8, `spe_ref_cnt` Decimal(10,2), `teambuy_valid_store_cnt` Int32, `newstore_perbd` Int8, `new_store_cnt` UInt32, `self_cash_quota` Decimal(12,2), `note` Nullable(String), `plan_new_staff` Nullable(Int32), `fr_spe_cash` Int8, `fr_spe_dis_cash` Decimal(10,2), `hrbp_cash_cnt` Decimal(10,2), `hrbp_drugstore_cnt` Int32, `hrbp_fr_cash_cnt` Decimal(10,2), `hrbp_cover_rate_cnt` Decimal(4,2), `_tidb_rowid` Int64) Engine = DeltaMerge((`_tidb_rowid`), '{\"cols\":[{\"comment\":\"\\\\u4F9D\\\\u8D56user_type\\\\u5B57\\\\u6BB5\\\\uFF0C \\\\u7528\\\\u6237id\\\\u6216\\\\u8005\\\\u57CE\\\\u5E02id\\\\u6216\\\\u8005\\\\u7701\\\\u533Aid\",\"default\":null,\"default_bit\":null,\"id\":1,\"name\":{\"L\":\"user_id\",\"O\":\"user_id\"},\"offset\":0,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":4099,\"Flen\":11,\"Tp\":3}},{\"comment\":\"\\\\u6574\\\\u6570\\\\uFF0Cyyyymm\\\\u683C\\\\u5F0F\",\"default\":\"0\",\"default_bit\":null,\"id\":2,\"name\":{\"L\":\"month\",\"O\":\"month\"},\"offset\":1,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":3,\"Flen\":11,\"Tp\":3}},{\"comment\":\"0-\\\\u9500\\\\u552E\\\\u7528\\\\u6237 1-\\\\u57CE\\\\u5E02id 2-\\\\u7701\\\\u533A\\\\u6307\\\\u6807\",\"default\":\"0\",\"default_bit\":null,\"id\":3,\"name\":{\"L\":\"user_type\",\"O\":\"user_type\"},\"offset\":2,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":3,\"Flen\":4,\"Tp\":1}},{\"comment\":\"\\\\u7CFB\\\\u7EDF\\\\u8BA1\\\\u7B97\\\\u7684\\\\u4E2A\\\\u4EBA\\\\u73B0\\\\u91D1\\\\u989D\\\\u4EFB\\\\u52A1\\\\u6307\\\\u6807 \",\"default\":\"0.00\",\"default_bit\":null,\"id\":4,\"name\":{\"L\":\"sys_cash\",\"O\":\"sys_cash\"},\"offset\":3,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":16,\"Tp\":246}},{\"comment\":\"\\\\u4E2A\\\\u4EBA\\\\u73B0\\\\u91D1\\\\u989D\\\\u4EFB\\\\u52A1\\\\u6307\\\\u6807 \",\"default\":\"0.00\",\"default_bit\":null,\"id\":5,\"name\":{\"L\":\"individual_cash\",\"O\":\"individual_cash\"},\"offset\":4,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":246}},{\"comment\":\"\\\\u4E2A\\\\u4EBA\\\\u9996\\\\u63A8\\\\u54C1\\\\u79CD\\\\u73B0\\\\u91D1\\\\u989D\\\\u4EFB\\\\u52A1\\\\u6307\\\\u6807\",\"default\":\"0.00\",\"default_bit\":null,\"id\":6,\"name\":{\"L\":\"indiv_cash_fr\",\"O\":\"indiv_cash_fr\"},\"offset\":5,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":246}},{\"comment\":\"\\\\u4E2A\\\\u4EBA\\\\u9996\\\\u63A8\\\\u54C1\\\\u79CD\\\\u73B0\\\\u91D1\\\\u989D\\\\u4EFB\\\\u52A1\\\\u6307\\\\u6807\\\\u6700\\\\u4F4E\\\\u8FBE\\\\u6210\\\\u73B0\\\\u91D1\",\"default\":\"0.00\",\"default_bit\":null,\"id\":7,\"name\":{\"L\":\"indiv_cash_fr_min\",\"O\":\"indiv_cash_fr_min\"},\"offset\":6,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":246}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u7CFB\\\\u7EDF\\\\u8BA1\\\\u7B97\\\\u7684\\\\u56E2\\\\u961F\\\\u73B0\\\\u91D1\\\\u989D\\\\u4EFB\\\\u52A1\\\\u6307\\\\u6807\",\"default\":\"0.00\",\"default_bit\":null,\"id\":8,\"name\":{\"L\":\"sys_group_cash\",\"O\":\"sys_group_cash\"},\"offset\":7,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":16,\"Tp\":246}},{\"comment\":\"\\\\u56E2\\\\u961F\\\\u73B0\\\\u91D1\\\\u989D\\\\u4EFB\\\\u52A1\\\\u6307\\\\u6807\",\"default\":\"0.00\",\"default_bit\":null,\"id\":9,\"name\":{\"L\":\"group_cash\",\"O\":\"group_cash\"},\"offset\":8,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":16,\"Tp\":246}},{\"comment\":\"\\\\u56E2\\\\u961F\\\\u9996\\\\u63A8\\\\u54C1\\\\u79CD\\\\u73B0\\\\u91D1\\\\u989D\\\\u4EFB\\\\u52A1\\\\u6307\\\\u6807\",\"default\":\"0.00\",\"default_bit\":null,\"id\":10,\"name\":{\"L\":\"group_cash_fr\",\"O\":\"group_cash_fr\"},\"offset\":9,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":16,\"Tp\":246}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u65D7\\\\u8230\\\\u5E97\\\\u4E2A\\\\u4EBA\\\\u73B0\\\\u91D1\\\\u6307\\\\u6807\",\"default\":\"0.00\",\"default_bit\":null,\"id\":11,\"name\":{\"L\":\"individ_store_cash\",\"O\":\"individ_store_cash\"},\"offset\":10,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":246}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u65D7\\\\u8230\\\\u5E97\\\\u56E2\\\\u961F\\\\u73B0\\\\u91D1\\\\u6307\\\\u6807\",\"default\":\"0.00\",\"default_bit\":null,\"id\":12,\"name\":{\"L\":\"group_store_cash\",\"O\":\"group_store_cash\"},\"offset\":11,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":16,\"Tp\":246}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u9500\\\\u552E\\\\u987E\\\\u95EE\\\\u6BCF\\\\u4E2A\\\\u4EBA\\\\u4E13\\\\u5E97\\\\u7C7B\\\\u578B\\\\u65D7\\\\u8230\\\\u5E97\\\\u7684\\\\u73B0\\\\u91D1\\\\u989D\\\\uFF08\\\\u53BB\\\\u9664\\\\u9000\\\\u6B3E\\\\uFF09\\\\uFF0C\\\\u7ECF\\\\u7406\\\\u4E5F\\\\u6709\\\\u4E2A\\\\u4EBA\\\\u90E8\\\\u5206\",\"default\":\"0.00\",\"default_bit\":null,\"id\":13,\"name\":{\"L\":\"individ_hall_cash\",\"O\":\"individ_hall_cash\"},\"offset\":12,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":246}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u9500\\\\u552E\\\\u7ECF\\\\u7406\\\\u6240\\\\u8D1F\\\\u8D23\\\\u7684\\\\u56E2\\\\u4F53\\\\u7684\\\\u4E13\\\\u9986\\\\u7684\\\\u73B0\\\\u91D1\\\\u989D\\\\uFF08\\\\u53BB\\\\u9664\\\\u9000\\\\u6B3E\\\\uFF09\\\\uFF0C\\\\u4E0D\\\\u5305\\\\u62EC\\\\u7ECF\\\\u7406\\\\u81EA\\\\u8EAB\\\\uFF0C\\\\u53EA\\\\u53D6\\\\u76F4\\\\u5C5E\\\\u4E8E\\\\u81EA\\\\u5DF1\\\\u7684\\\\u4EE3\\\\u8868\\\\u548C\\\\u7EC4\\\\u957F\\\\uFF0C\\\\u82E5\\\\u4E0B\\\\u5C5E\\\\u4E2D\\\\u6709\\\\u7ECF\\\\u7406\\\\u53CA\\\\u8BE5\\\\u7ECF\\\\u7406\\\\u7684\\\\u4E0B\\\\u5C5E\\\\uFF0C\\\\u8FD9\\\\u90E8\\\\u5206\\\\u4EBA\\\\u4E0D\\\\u53D6\\\\u3002\",\"default\":\"0.00\",\"default_bit\":null,\"id\":14,\"name\":{\"L\":\"group_hall_cash\",\"O\":\"group_hall_cash\"},\"offset\":13,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":16,\"Tp\":246}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u8C03\\\\u6574\\\\u73B0\\\\u91D1\\\\u989D\",\"default\":\"0.00\",\"default_bit\":null,\"id\":15,\"name\":{\"L\":\"adjust_cash\",\"O\":\"adjust_cash\"},\"offset\":14,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":246}},{\"comment\":\"\\\\u7CFB\\\\u7EDF\\\\u8BA1\\\\u7B97\\\\u7684\\\\u4E2A\\\\u4EBA\\\\u836F\\\\u5E97\\\\u6570\\\\u6307\\\\u6807\",\"default\":\"0\",\"default_bit\":null,\"id\":16,\"name\":{\"L\":\"sys_store_cnt\",\"O\":\"sys_store_cnt\"},\"offset\":15,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":33,\"Flen\":255,\"Tp\":3}},{\"comment\":\"\\\\u4E2A\\\\u4EBA\\\\u836F\\\\u5E97\\\\u6570\",\"default\":\"0\",\"default_bit\":null,\"id\":17,\"name\":{\"L\":\"indiv_store_cnt\",\"O\":\"indiv_store_cnt\"},\"offset\":16,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":33,\"Flen\":255,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u4E2A\\\\u4EBA\\\\u603B\\\\u5E97\\\\u6570\\\\u6743\\\\u91CD\",\"default\":\"0.0000\",\"default_bit\":null,\"id\":18,\"name\":{\"L\":\"indiv_store_cnt_wt\",\"O\":\"indiv_store_cnt_wt\"},\"offset\":17,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":4,\"Elems\":null,\"Flag\":1,\"Flen\":5,\"Tp\":246}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u7CFB\\\\u7EDF\\\\u8BA1\\\\u7B97\\\\u7684\\\\u56E2\\\\u961F\\\\u836F\\\\u5E97\\\\u6570\\\\u6307\\\\u6807\",\"default\":\"0\",\"default_bit\":null,\"id\":19,\"name\":{\"L\":\"sys_group_store_cnt\",\"O\":\"sys_group_store_cnt\"},\"offset\":18,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":33,\"Flen\":255,\"Tp\":3}},{\"comment\":\"\\\\u56E2\\\\u961F\\\\u836F\\\\u5E97\\\\u6570\",\"default\":\"0\",\"default_bit\":null,\"id\":20,\"name\":{\"L\":\"group_store_cnt\",\"O\":\"group_store_cnt\"},\"offset\":19,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":33,\"Flen\":255,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u7CFB\\\\u7EDF\\\\u8BA1\\\\u7B97\\\\u7684\\\\u4E2A\\\\u4EBA\\\\u65B0\\\\u5E97\\\\u4EFB\\\\u52A1\\\\u6307\\\\u6807\",\"default\":\"0\",\"default_bit\":null,\"id\":21,\"name\":{\"L\":\"sys_new_store_cnt\",\"O\":\"sys_new_store_cnt\"},\"offset\":20,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":11,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u4E2A\\\\u4EBA\\\\u65B0\\\\u5E97\\\\u4EFB\\\\u52A1\\\\u6307\\\\u6807\",\"default\":\"0\",\"default_bit\":null,\"id\":22,\"name\":{\"L\":\"indiv_new_store_cnt\",\"O\":\"indiv_new_store_cnt\"},\"offset\":21,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":11,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u4E2A\\\\u4EBA\\\\u65B0\\\\u5E97\\\\u6570\\\\u6743\\\\u91CD\",\"default\":\"0.0000\",\"default_bit\":null,\"id\":23,\"name\":{\"L\":\"indiv_new_store_cnt_wt\",\"O\":\"indiv_new_store_cnt_wt\"},\"offset\":22,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":4,\"Elems\":null,\"Flag\":1,\"Flen\":5,\"Tp\":246}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u7CFB\\\\u7EDF\\\\u8BA1\\\\u7B97\\\\u7684\\\\u56E2\\\\u4F53\\\\u65B0\\\\u5E97\\\\u4EFB\\\\u52A1\\\\u6307\\\\u6807\",\"default\":\"0\",\"default_bit\":null,\"id\":24,\"name\":{\"L\":\"sys_group_new_store_cnt\",\"O\":\"sys_group_new_store_cnt\"},\"offset\":23,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":11,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u56E2\\\\u4F53\\\\u65B0\\\\u5E97\\\\u4EFB\\\\u52A1\\\\u6307\\\\u6807\",\"default\":\"0\",\"default_bit\":null,\"id\":25,\"name\":{\"L\":\"group_new_store_cnt\",\"O\":\"group_new_store_cnt\"},\"offset\":24,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":11,\"Tp\":3}},{\"comment\":\"\\\\u56E2\\\\u4F53\\\\/\\\\u57CE\\\\u5E02\\\\u6708\\\\u5EA6\\\\u7B7E\\\\u5230\\\\u5E97\\\\u6570\\\\u6307\\\\u6807\",\"default\":\"0\",\"default_bit\":null,\"id\":26,\"name\":{\"L\":\"group_signed_store_cnt\",\"O\":\"group_signed_store_cnt\"},\"offset\":25,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":11,\"Tp\":3}},{\"comment\":\"\\\\u4E2A\\\\u4EBA\\\\u6708\\\\u5EA6\\\\u7B7E\\\\u5230\\\\u5E97\\\\u6570\\\\u6307\\\\u6807\",\"default\":\"0\",\"default_bit\":null,\"id\":27,\"name\":{\"L\":\"indiv_signed_store_cnt\",\"O\":\"indiv_signed_store_cnt\"},\"offset\":26,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":11,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u7CFB\\\\u7EDF\\\\u8BA1\\\\u7B97\\\\u7684\\\\u4E2A\\\\u4EBA\\\\u7ED3\\\\u6784\\\\u5316\\\\u5E97\\\\u6570\",\"default\":\"0\",\"default_bit\":null,\"id\":28,\"name\":{\"L\":\"sys_struct_cnt\",\"O\":\"sys_struct_cnt\"},\"offset\":27,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u4E2A\\\\u4EBA\\\\u7ED3\\\\u6784\\\\u5316\\\\u5E97\\\\u6570\",\"default\":\"0\",\"default_bit\":null,\"id\":29,\"name\":{\"L\":\"indiv_struct_cnt\",\"O\":\"indiv_struct_cnt\"},\"offset\":28,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u4E2A\\\\u4EBA\\\\u7ED3\\\\u6784\\\\u5316\\\\u5E97\\\\u6570\\\\u6743\\\\u91CD\",\"default\":\"0.0000\",\"default_bit\":null,\"id\":30,\"name\":{\"L\":\"indiv_struct_cnt_wt\",\"O\":\"indiv_struct_cnt_wt\"},\"offset\":29,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":4,\"Elems\":null,\"Flag\":1,\"Flen\":5,\"Tp\":246}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u7CFB\\\\u7EDF\\\\u8BA1\\\\u7B97\\\\u7684\\\\u56E2\\\\u961F\\\\u7ED3\\\\u6784\\\\u5316\\\\u5E97\\\\u6570\",\"default\":\"0\",\"default_bit\":null,\"id\":31,\"name\":{\"L\":\"sys_group_struct_cnt\",\"O\":\"sys_group_struct_cnt\"},\"offset\":30,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u56E2\\\\u961F\\\\u7ED3\\\\u6784\\\\u5316\\\\u5E97\\\\u6570\",\"default\":\"0\",\"default_bit\":null,\"id\":32,\"name\":{\"L\":\"group_struct_cnt\",\"O\":\"group_struct_cnt\"},\"offset\":31,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u7ED3\\\\u6784\\\\u5316\\\\u9636\\\\u6BB5\\\\u5C5E\\\\u6027,3000\\\\u8868\\\\u793A3k+,5000\\\\u8868\\\\u793A5k+,8000\\\\u8868\\\\u793A8k+\\\\uFF0C\\\\u4F9D\\\\u6B64\\\\u7C7B\\\\u63A8\",\"default\":\"0\",\"default_bit\":null,\"id\":33,\"name\":{\"L\":\"struct_stage\",\"O\":\"struct_stage\"},\"offset\":32,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":3}},{\"comment\":\"\",\"default\":\"CURRENT_TIMESTAMP\",\"default_bit\":null,\"id\":34,\"name\":{\"L\":\"mtime\",\"O\":\"mtime\"},\"offset\":33,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":8321,\"Flen\":19,\"Tp\":7}},{\"comment\":\"\",\"default\":\"0\",\"default_bit\":null,\"id\":35,\"name\":{\"L\":\"ctime\",\"O\":\"ctime\"},\"offset\":34,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":11,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u4E2A\\\\u4EBA\\\\u81EA\\\\u8425\\\\u4E1A\\\\u52A1\\\\u73B0\\\\u91D1\",\"default\":\"0\",\"default_bit\":null,\"id\":36,\"name\":{\"L\":\"indiv_self_cash\",\"O\":\"indiv_self_cash\"},\"offset\":35,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":11,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u56E2\\\\u4F53\\\\u81EA\\\\u8425\\\\u4E1A\\\\u52A1\\\\u73B0\\\\u91D1\",\"default\":\"0\",\"default_bit\":null,\"id\":37,\"name\":{\"L\":\"group_self_cash\",\"O\":\"group_self_cash\"},\"offset\":36,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":11,\"Tp\":3}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u5BC4\\\\u552E\\\\u4E2A\\\\u4EBA\\\\u91D1\\\\u989D\",\"default\":\"0.00\",\"default_bit\":null,\"id\":38,\"name\":{\"L\":\"individ_proxy_cash\",\"O\":\"individ_proxy_cash\"},\"offset\":37,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":8,\"Tp\":246}},{\"comment\":\"(\\\\u5E9F\\\\u5F03)\\\\u5BC4\\\\u552E\\\\u52A8\\\\u9500\\\\u54C1\\\\u79CD\\\\u6570\",\"default\":\"0\",\"default_bit\":null,\"id\":39,\"name\":{\"L\":\"individ_proxy_drug\",\"O\":\"individ_proxy_drug\"},\"offset\":38,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":6,\"Tp\":2}},{\"comment\":\"\\\\u662F\\\\u5426\\\\u7279\\\\u6B8A\\\\u5BA1\\\\u6279\\\\u7684\\\\u5730\\\\u63A8\\\\u8D26\\\\u53F7\\\\uFF0C0-\\\\u5426 1-\\\\u662F\\\\uFF0C\\\\u5F53user_type=0\\\\u65F6\\\\u4F7F\\\\u7528\",\"default\":\"0\",\"default_bit\":null,\"id\":40,\"name\":{\"L\":\"b_spe_user\",\"O\":\"b_spe_user\"},\"offset\":39,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":4,\"Tp\":1}},{\"comment\":\"\\\\u662F\\\\u5426\\\\u73B0\\\\u91D1\\\\u7279\\\\u6279\\\\uFF0C0-\\\\u5426 1-\\\\u662F\",\"default\":\"0\",\"default_bit\":null,\"id\":41,\"name\":{\"L\":\"b_spe_cash\",\"O\":\"b_spe_cash\"},\"offset\":40,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":4,\"Tp\":1}},{\"comment\":\"\\\\u7279\\\\u6279\\\\u73B0\\\\u91D1\\\\u6263\\\\u9664\\\\u91D1\\\\u989D\",\"default\":\"0.00\",\"default_bit\":null,\"id\":42,\"name\":{\"L\":\"spe_dis_cash\",\"O\":\"spe_dis_cash\"},\"offset\":41,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":246}},{\"comment\":\"\\\\u662F\\\\u5426\\\\u5E97\\\\u6570\\\\u7279\\\\u6279\\\\uFF0C0-\\\\u5426 1-\\\\u662F\",\"default\":\"0\",\"default_bit\":null,\"id\":43,\"name\":{\"L\":\"b_spe_cnt\",\"O\":\"b_spe_cnt\"},\"offset\":42,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":4,\"Tp\":1}},{\"comment\":\"\\\\u5E97\\\\u6570\\\\u7279\\\\u6279-\\\\u53C2\\\\u8003\\\\u5E97\\\\u6570\",\"default\":\"0.00\",\"default_bit\":null,\"id\":44,\"name\":{\"L\":\"spe_ref_cnt\",\"O\":\"spe_ref_cnt\"},\"offset\":43,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":246}},{\"comment\":\"\\\\u8BE5\\\\u6708\\\\u62FC\\\\u56E2\\\\u5E97\\\\u6570\\\\u57FA\\\\u51C6\\\\u503C\",\"default\":\"0\",\"default_bit\":null,\"id\":45,\"name\":{\"L\":\"teambuy_valid_store_cnt\",\"O\":\"teambuy_valid_store_cnt\"},\"offset\":44,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":11,\"Tp\":3}},{\"comment\":\"\\\\u56FA\\\\u5B9A\\\\u4EBA\\\\u5747\\\\u65B0\\\\u5E97\\\\u503C\",\"default\":\"0\",\"default_bit\":null,\"id\":52,\"name\":{\"L\":\"newstore_perbd\",\"O\":\"newstore_perbd\"},\"offset\":45,\"origin_default\":\"0\",\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":4,\"Tp\":1}},{\"comment\":\"\\\\u65B0\\\\u5E97\\\\u6570\\\\u76EE\\\\u6807\",\"default\":\"0\",\"default_bit\":null,\"id\":46,\"name\":{\"L\":\"new_store_cnt\",\"O\":\"new_store_cnt\"},\"offset\":46,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":33,\"Flen\":11,\"Tp\":3}},{\"comment\":\"\\\\u81EA\\\\u8425\\\\u73B0\\\\u91D1\\\\u6307\\\\u6807\",\"default\":\"0.00\",\"default_bit\":null,\"id\":47,\"name\":{\"L\":\"self_cash_quota\",\"O\":\"self_cash_quota\"},\"offset\":47,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":12,\"Tp\":246}},{\"comment\":\"\\\\u6307\\\\u6807\\\\u672A\\\\u5206\\\\u89E3\\\\u5B8C\\\\u6210\\\\u539F\\\\u56E0\\\\u5907\\\\u6CE8\",\"default\":null,\"default_bit\":null,\"id\":48,\"name\":{\"L\":\"note\",\"O\":\"note\"},\"offset\":48,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"utf8\",\"Collate\":\"utf8_bin\",\"Decimal\":0,\"Elems\":null,\"Flag\":0,\"Flen\":255,\"Tp\":15}},{\"comment\":\"\\\\u8BA1\\\\u5212\\\\u62DB\\\\u65B0\\\\u4EBA\\\\u6570\",\"default\":\"0\",\"default_bit\":null,\"id\":49,\"name\":{\"L\":\"plan_new_staff\",\"O\":\"plan_new_staff\"},\"offset\":49,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":0,\"Flen\":6,\"Tp\":9}},{\"comment\":\"\\\\u662F\\\\u5426\\\\u9996\\\\u63A8\\\\u73B0\\\\u91D1\\\\u7279\\\\u6279\\\\uFF0C0-\\\\u5426 1-\\\\u662F\",\"default\":\"0\",\"default_bit\":null,\"id\":50,\"name\":{\"L\":\"fr_spe_cash\",\"O\":\"fr_spe_cash\"},\"offset\":50,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":4,\"Tp\":1}},{\"comment\":\"\\\\u7279\\\\u6279\\\\u9996\\\\u63A8\\\\u73B0\\\\u91D1\\\\u6263\\\\u9664\\\\u91D1\\\\u989D\",\"default\":\"0.00\",\"default_bit\":null,\"id\":51,\"name\":{\"L\":\"fr_spe_dis_cash\",\"O\":\"fr_spe_dis_cash\"},\"offset\":51,\"origin_default\":null,\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":246}},{\"comment\":\"\\\\u57CE\\\\u5E02\\\\u73B0\\\\u91D1\\\\u6307\\\\u5BFC\\\\u503C\",\"default\":\"0.00\",\"default_bit\":null,\"id\":53,\"name\":{\"L\":\"hrbp_cash_cnt\",\"O\":\"hrbp_cash_cnt\"},\"offset\":52,\"origin_default\":\"0.00\",\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":246}},{\"comment\":\"\\\\u57CE\\\\u5E02\\\\u5E97\\\\u6570\\\\u6307\\\\u5BFC\\\\u503C\",\"default\":\"0.00\",\"default_bit\":null,\"id\":54,\"name\":{\"L\":\"hrbp_drugstore_cnt\",\"O\":\"hrbp_drugstore_cnt\"},\"offset\":53,\"origin_default\":\"0.00\",\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":0,\"Elems\":null,\"Flag\":1,\"Flen\":6,\"Tp\":3}},{\"comment\":\"\\\\u57CE\\\\u5E02\\\\u9996\\\\u63A8\\\\u73B0\\\\u91D1\\\\u6307\\\\u5BFC\\\\u503C\",\"default\":\"0.00\",\"default_bit\":null,\"id\":55,\"name\":{\"L\":\"hrbp_fr_cash_cnt\",\"O\":\"hrbp_fr_cash_cnt\"},\"offset\":54,\"origin_default\":\"0.00\",\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":10,\"Tp\":246}},{\"comment\":\"\\\\u57CE\\\\u5E02\\\\u9996\\\\u63A8\\\\u8986\\\\u76D6\\\\u7387\",\"default\":\"0.00\",\"default_bit\":null,\"id\":56,\"name\":{\"L\":\"hrbp_cover_rate_cnt\",\"O\":\"hrbp_cover_rate_cnt\"},\"offset\":55,\"origin_default\":\"0.00\",\"state\":5,\"type\":{\"Charset\":\"binary\",\"Collate\":\"binary\",\"Decimal\":2,\"Elems\":null,\"Flag\":1,\"Flen\":4,\"Tp\":246}}],\"comment\":\"\\\\u6BCF\\\\u6708\\\\u4EFB\\\\u52A1\\\\u6307\\\\u6807\\\\u4E0B\\\\u8FBE\\\\u8868\",\"id\":28972,\"index_info\":[],\"is_common_handle\":false,\"name\":{\"L\":\"ts_salesmen_task\",\"O\":\"ts_salesmen_task\"},\"partition\":null,\"pk_is_handle\":false,\"schema_version\":25171,\"state\":5,\"tiflash_replica\":{\"Count\":0},\"update_timestamp\":427987705934381079}')"] [thread_id=1]
[2021/09/26 19:30:33.376 +08:00] [INFO] [<unknown>] ["StorageDeltaMerge: /home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/tics/dbms/src/Storages/StorageDeltaMerge.cpp updateTableColumnInfo TableName t_28972 ordinary columns format version: 1\n57 columns:\n`user_id` Int32\n`month` Int32\n`user_type` Int8\n`sys_cash` Decimal(16,2)\n`individual_cash` Decimal(10,2)\n`indiv_cash_fr` Decimal(10,2)\n`indiv_cash_fr_min` Decimal(10,2)\n`sys_group_cash` Decimal(16,2)\n`group_cash` Decimal(16,2)\n`group_cash_fr` Decimal(16,2)\n`individ_store_cash` Decimal(10,2)\n`group_store_cash` Decimal(16,2)\n`individ_hall_cash` Decimal(10,2)\n`group_hall_cash` Decimal(16,2)\n`adjust_cash` Decimal(10,2)\n`sys_store_cnt` UInt32\n`indiv_store_cnt` UInt32\n`indiv_store_cnt_wt` Decimal(5,4)\n`sys_group_store_cnt` UInt32\n`group_store_cnt` UInt32\n`sys_new_store_cnt` Int32\n`indiv_new_store_cnt` Int32\n`indiv_new_store_cnt_wt` Decimal(5,4)\n`sys_group_new_store_cnt` Int32\n`group_new_store_cnt` Int32\n`group_signed_store_cnt` Int32\n`indiv_signed_store_cnt` Int32\n`sys_struct_cnt` Int32\n`indiv_struct_cnt` Int32\n`indiv_struct_cnt_wt` Decimal(5,4)\n`sys_group_struct_cnt` Int32\n`group_struct_cnt` Int32\n`struct_stage` Int32\n`mtime` MyDateTime(0)\n`ctime` Int32\n`indiv_self_cash` Int32\n`group_self_cash` Int32\n`individ_proxy_cash` Decimal(8,2)\n`individ_proxy_drug` Int16\n`b_spe_user` Int8\n`b_spe_cash` Int8\n`spe_dis_cash` Decimal(10,2)\n`b_spe_cnt` Int8\n`spe_ref_cnt` Decimal(10,2)\n`teambuy_valid_store_cnt` Int32\n`newstore_perbd` Int8\n`new_store_cnt` UInt32\n`self_cash_quota` Decimal(12,2)\n`note` Nullable(String)\n`plan_new_staff` Nullable(Int32)\n`fr_spe_cash` Int8\n`fr_spe_dis_cash` Decimal(10,2)\n`hrbp_cash_cnt` Decimal(10,2)\n`hrbp_drugstore_cnt` Int32\n`hrbp_fr_cash_cnt` Decimal(10,2)\n`hrbp_cover_rate_cnt` Decimal(4,2)\n`_tidb_rowid` Int64\n materialized columns format version: 1\n0 columns:\n"] [thread_id=1]
[2021/09/26 19:30:33.377 +08:00] [ERROR] [<unknown>] ["Application: Bootstrap failed because sync schema error: Syntax error: Not a valid integer: 0.00\nWe will sleep for 3 seconds and try again."] [thread_id=1]
```

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #3157

Problem Summary:

### What is changed and how it works?
when value is `0.0`, `value.convert<Int64>();` raise a error.
Convert it to `String` first, and convert String to Int64 by `std::stoull`
`static_cast<Int64>(std::stoull(value.convert<String>())); `

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Lloyd-Pottiger** [comment]
```
mysql test> create table t (a int);
-- The type of column i is int, but the default value is set to "0.00"
mysql test> alter table t add column i int not null default 0.00; 
mysql test> alter tablet t set tiflash replica 1;
mysql test> select a from t;
```

File: dbms/src/Storages/Transaction/TiDB.cpp [hunk 1]
```diff
@@ -110,14 +110,22 @@ Field ColumnInfo::defaultValueToField() const
...
     case TypeInt24:
-        return value.convert<Int64>();
+    {
+        try
+        {
+            return value.convert<Int64>();
+        }
+        catch (...)
+        {
+            return static_cast<Int64>(std::stoull(value.convert<String>()));
```
Comment (breezewish) [inline dbms/src/Storages/Transaction/TiDB.cpp:126]: Should we fix at TiDB side instead? IMO it is wired for a int column to pass a "string" default value. The casting rule may be very complicated as well.

Comment (Lloyd-Pottiger) [reply dbms/src/Storages/Transaction/TiDB.cpp:126]: I agree with you. https://github.com/pingcap/tiflash/issues/3157#issuecomment-1128606869. But we maybe still need to add a backstop strategy to support upgrade https://github.com/pingcap/tiflash/issues/3157#issuecomment-1128615478

File: dbms/src/Storages/Transaction/TiDB.cpp [hunk 2]
```diff
@@ -110,14 +110,22 @@ Field ColumnInfo::defaultValueToField() const
     }
     switch (tp)
     {
-    // TODO: Consider unsigned?
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Transaction/TiDB.cpp:113]: Can this function handle `create table t ( a int default 18446744073709551616)`? (18446744073709551616==MAX(Int64) + 1) Or will that be blocked by TiDB?

Comment (Lloyd-Pottiger) [reply dbms/src/Storages/Transaction/TiDB.cpp:113]: It will be blocked by TiDB. And
```
mysql> create table t ( a int unsigned default 4294967295);
Query OK, 0 rows affected (0.07 sec)
```
this is OK. `4294967295 == MAX(UInt32)`. TiDB distinguishes `int unsigned` from `int` by `flag` rather than `tp`. Therefore, we do not need to consider unsigned type here.

Comment (JaySon-Huang) [reply dbms/src/Storages/Transaction/TiDB.cpp:113]: add comment about the unsigned default value to the code pls

File: dbms/src/Storages/Transaction/TiDB.cpp (hunk 1 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/Transaction/TiDB.cpp:126]: If the value is "1.9", it should be parsed into integer "2". Verified under TiDB and MySQL.

```
mysql> select version();
+-------------------------+
| version()               |
+-------------------------+
| 5.7.33-0ubuntu0.16.04.1 |
+-------------------------+
1 row in set (0.00 sec)

mysql> create table td ( a int default 1.9, b int);
Query OK, 0 rows affected (0.20 sec)

mysql> show create table td;
+-------+------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                     |
+-------+------------------------------------------------------------------------------------------------------------------+
| td    | CREATE TABLE `td` (
  `a` int(11) DEFAULT '2',
  `b` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-------+------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> insert into td(b) values(1);
Query OK, 1 row affected (0.01 sec)

mysql> select * from td;
+------+------+
| a    | b    |
+------+------+
|    2 |    1 |
+------+------+
1 row in set (0.00 sec)
```

```
test> select tidb_version()
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.0.0\nEdition: Community\nGit Commit Hash: 36a9810441ca0e496cbd22064af274b3be771081\nGit Branch: heads/refs/tags/v6.0.0\nUTC Build Time: 2022-03-31 10:33:28\nGoVersion: go1.18\nRace Enabled: false\nTiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306\nCheck Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set
Time: 0.018s
test> drop table td;
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Your call!
Query OK, 0 rows affected
Time: 0.197s
test> create table td ( a int default 1.9, b int);
Query OK, 0 rows affected
Time: 0.079s
test> show create table td;
+-------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                               |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------+
| td    | CREATE TABLE `td` (\n  `a` int(11) DEFAULT '1.9',\n  `b` int(11) DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set
Time: 0.018s
test> insert into td(b) values(1);
Query OK, 1 row affected
Time: 0.009s
test> select * from td;
+---+---+
| a | b |
+---+---+
| 2 | 1 |
+---+---+
1 row in set
Time: 0.022s
```

**Review by flowbehappy — APPROVED** [review]

File: dbms/src/Storages/Transaction/TiDB.cpp (hunk 2 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/Transaction/TiDB.cpp:113]: done

**Comment by Lloyd-Pottiger** [comment]
```mysql
mysql> use test
Database changed
mysql> create table t (a int default 0.0);
Query OK, 0 rows affected (0.07 sec)

mysql> ALTER TABLE t SET TIFLASH REPLICA 1;
Query OK, 0 rows affected (0.07 sec)

mysql> show create table t;
+-------+------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                               |
+-------+------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` int(11) DEFAULT '0.0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> insert t (a) values(default);
Query OK, 1 row affected (0.01 sec)

mysql> select a from t;
+------+
| a    |
+------+
|    0 |
+------+
1 row in set (0.25 sec)

mysql> alter table t change a a int default 1.25;
Query OK, 0 rows affected (0.06 sec)

mysql> insert t (a) values(default);
Query OK, 1 row affected (0.00 sec)

mysql> select a from t;
+------+
| a    |
+------+
|    0 |
|    1 |
+------+
2 rows in set (0.02 sec)

mysql> alter table t change a a int default 2.8;
Query OK, 0 rows affected (0.06 sec)

mysql> insert t (a) values(default);
Query OK, 1 row affected (0.01 sec)

mysql> select a from t;
+------+
| a    |
+------+
|    0 |
|    1 |
|    3 |
+------+
3 rows in set (0.02 sec)
```
