### PR TITLE
Let late materialization work when read thread is not enable

### LINKED ISSUE #7486: Throw exception when not enable read thread pool
## Enhancement
Late materialization is incompatible with disabling the read thread pool, so throw an exception when not enabling the read thread pool.

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #7486

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/Planner/PhysicalPlan.cpp [hunk 1]
```diff
@@ -76,9 +76,9 @@ void PhysicalPlan::build(const tipb::DAGRequest * dag_request)
 void PhysicalPlan::buildTableScan(const String & executor_id, const tipb::Executor * executor)
 {
     TiDBTableScan table_scan(executor, executor_id, dagContext());
-    if (!table_scan.getPushedDownFilters().empty() && unlikely(!context.getSettingsRef().dt_enable_read_thread))
+    if (!table_scan.getPushedDownFilters().empty() && unlikely(!context.getSettingsRef().dt_enable_bitmap_filter))
         throw Exception(
-            "Enable late materialization but disable read thread pool, please set the config `dt_enable_read_thread` "
+            "Enable late materialization but disable read thread pool, please set the config `dt_enable_bitmap_filter` "
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Planner/PhysicalPlan.cpp:81]: the description here should be changed

File: dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp [hunk 2]
```diff
@@ -901,9 +901,9 @@ void DAGQueryBlockInterpreter::executeImpl(DAGPipeline & pipeline)
     else if (query_block.isTableScanSource())
     {
         TiDBTableScan table_scan(query_block.source, query_block.source_name, dagContext());
-        if (!table_scan.getPushedDownFilters().empty() && unlikely(!context.getSettingsRef().dt_enable_read_thread))
+        if (!table_scan.getPushedDownFilters().empty() && unlikely(!context.getSettingsRef().dt_enable_bitmap_filter))
             throw Exception("Enable late materialization but disable read thread pool, please set the config "
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp:905]: ditto

File: dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h [hunk 3]
```diff
@@ -21,6 +21,8 @@
 #include <Storages/DeltaMerge/Segment.h>
 #include <Storages/DeltaMerge/SegmentReadTaskPool.h>
 
+#include "Interpreters/Context.h"
+
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h:25]: I think this can be removed

**Comment by JaySon-Huang** [comment]
Why we can enable late materialization without read thread pool now? Which PR changed it?

**Comment by Lloyd-Pottiger** [comment]
> Why we can enable late materialization without read thread pool now? Which PR changed it?

Late materialization only require bitmap actually, so use bitmap mode even without read thread pool can work. Do not need extra work, I forget to implement this before......

File: dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h [hunk 4]
```diff
@@ -16,6 +16,7 @@
 
 #include <Common/FailPoint.h>
 #include <DataStreams/IProfilingBlockInputStream.h>
+#include <Interpreters/Context.h>
 #include <Interpreters/Context_fwd.h>
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h:20]:
```suggestion
#include <Interpreters/Context_fwd.h>
```
The `Context.h` could be removed because we have already include `Context_fwd.h`

File: dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp [hunk 5]
```diff
@@ -901,9 +901,9 @@ void DAGQueryBlockInterpreter::executeImpl(DAGPipeline & pipeline)
     else if (query_block.isTableScanSource())
     {
         TiDBTableScan table_scan(query_block.source, query_block.source_name, dagContext());
-        if (!table_scan.getPushedDownFilters().empty() && unlikely(!context.getSettingsRef().dt_enable_read_thread))
-            throw Exception("Enable late materialization but disable read thread pool, please set the config "
-                            "`dt_enable_read_thread` of TiFlash to true,"
+        if (!table_scan.getPushedDownFilters().empty() && unlikely(!context.getSettingsRef().dt_enable_bitmap_filter))
+            throw Exception("Enable late materialization but disable bitmap filter, please set the config "
+                            "`dt_enable_bitmap_filter` of TiFlash to true,"
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp:906]:
```suggestion
            throw Exception("Running late materialization but bitmap filter is disabled, please set the config "
                            "`profiles.default.dt_enable_bitmap_filter` of TiFlash to true,"
```

File: dbms/src/Flash/Planner/PhysicalPlan.cpp [hunk 6]
```diff
@@ -76,9 +76,9 @@ void PhysicalPlan::build(const tipb::DAGRequest * dag_request)
 void PhysicalPlan::buildTableScan(const String & executor_id, const tipb::Executor * executor)
 {
     TiDBTableScan table_scan(executor, executor_id, dagContext());
-    if (!table_scan.getPushedDownFilters().empty() && unlikely(!context.getSettingsRef().dt_enable_read_thread))
+    if (!table_scan.getPushedDownFilters().empty() && unlikely(!context.getSettingsRef().dt_enable_bitmap_filter))
         throw Exception(
-            "Enable late materialization but disable read thread pool, please set the config `dt_enable_read_thread` "
+            "Enable late materialization but disable bitmap filter, please set the config `dt_enable_bitmap_filter` "
             "of TiFlash to true,"
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Planner/PhysicalPlan.cpp:82]:
```suggestion
            "Running late materialization but bitmap filter is disabled, please set the config `profiles.default.dt_enable_bitmap_filter` "
            "of TiFlash to true,"
```

**Review by JaySon-Huang — APPROVED** [review]
Rest LGTM
