### PR TITLE
KVStore: fix tiflash_raft_throughput_bytes warp problem

### LINKED ISSUE #10701: tiflash_raft_throughput_bytes may warp
## Bug Report

Please answer these questi

Image

ons before submitting your issue. Thanks!

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #10701

Problem Summary:

### What is changed and how it works?

```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fixed an issue where Grafana's Raft throughput might incorrectly display very large values.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Safer storage size accounting implemented to prevent underflow/overflow on edge-case writes.
  * Size updates unified across insert paths, improving accuracy of write-size reporting and reducing risk of rare errors or crashes while preserving existing insert behavior.

### CODE REVIEW

File: dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp [hunk 1]
```diff
@@ -359,6 +359,20 @@ std::pair<EngineStoreApplyRes, DM::WriteResult> Region::handleWriteRaftCmd(
     const size_t lock_count
         = std::count_if(cmds.cmd_cf, cmds.cmd_cf + cmds.len, [](auto cf) { return cf == ColumnFamilyType::Lock; });
     deleting_lock_keys.reserve(lock_count);
+    auto update_write_size = [&](Int64 payload) {
+        if (payload > 0)
+        {
+            write_size += static_cast<size_t>(payload);
+        }
+        else if (payload < 0)
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp:367]: Why `doInsert` will return a negative `payload`?

Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp:367]: I believe it is because some kvs are rewritten. For example, a lock may be rewritten, and thus making we observe a decrease.

File: dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp [hunk 2]
```diff
@@ -385,11 +399,14 @@ std::pair<EngineStoreApplyRes, DM::WriteResult> Region::handleWriteRaftCmd(
...
+                    auto payload
+                        = doInsert(cf, std::move(tikv_key), std::move(tikv_value), DupCheck::AllowSame).payload;
+                    update_write_size(payload);
                 }
                 else
                 {
-                    write_size += doInsert(cf, std::move(tikv_key), std::move(tikv_value), DupCheck::Deny).payload;
+                    auto payload = doInsert(cf, std::move(tikv_key), std::move(tikv_value), DupCheck::Deny).payload;
+                    update_write_size(payload);
                 }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp]: Simplify the duplicated code like this
```
                // There may be orphan default key in a snapshot under raftstore v2.
                auto dup_check = is_v2 ? DupCheck::AllowSame : DupCheck::Deny;
                auto payload = doInsert(cf, std::move(tikv_key), std::move(tikv_value), dup_check).payload;
                update_write_size(payload);
```

File: dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp [hunk 3]
```diff
@@ -359,6 +359,20 @@ std::pair<EngineStoreApplyRes, DM::WriteResult> Region::handleWriteRaftCmd(
     const size_t lock_count
         = std::count_if(cmds.cmd_cf, cmds.cmd_cf + cmds.len, [](auto cf) { return cf == ColumnFamilyType::Lock; });
     deleting_lock_keys.reserve(lock_count);
+    auto update_write_size = [&](Int64 payload) {
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp]: Better only capture `write_size` explicitly
```suggestion
    auto update_write_size = [&write_size](Int64 payload) {
```

File: dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp [hunk 4]
```diff
@@ -359,6 +359,20 @@ std::pair<EngineStoreApplyRes, DM::WriteResult> Region::handleWriteRaftCmd(
...
+        if (payload > 0)
+        {
+            write_size += static_cast<size_t>(payload);
+        }
+        else if (payload < 0)
+        {
+            const auto dec = static_cast<size_t>(-(payload + 1)) + 1; // avoid INT64_MIN overflow
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp:371]:
```suggestion
            // A lock being rewritten could lead to a negative payload.
            // Try to turn the negative payload into a positive decrement on `write_size`.
            const auto dec = static_cast<size_t>(-(payload + 1)) + 1; // avoid INT64_MIN overflow
```
