### PR TITLE
Reset current_memory_tracker when WNEstablishDisaggTaskHandler finished.

### LINKED ISSUE #8173: TiFlash process crashes in MemoryTracker
img_v2_f7be2cf8-4016-459a-99df-e8de6e21bfdg

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #8173

Problem Summary:

1. In `WNEstablishDisaggTaskHandler::execute`, a `ProcessListElement` object will be created and sets `current_memory_tracker` to its `memory_tracker` member in constructor. And `current_memory_tracker`  will be reset in the destructor of  `ProcessListElement`.

2. However, objects of `ProcessListElement` are created in threads of  `WNEstablishDisaggTaskPool`, but destructed in threads of GRPC because it will be destructed with object of  `WNEstablishDisaggTaskHandler` (`handler` -> `dag_context` -> `process_list_entry`).

3. This result in `current_memory_tracker` of threads of `WNEstablishDisaggTaskPool` is not reset after task finished and other tasks may continue to use this memory tracker, although it may have already been destructed.

### What is changed and how it works?

- Reset `current_memory_tracker` after tasks of `WNEstablishDisaggTaskPool` finished.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/FlashService.cpp [hunk 1]
```diff
@@ -905,9 +902,11 @@ grpc::Status FlashService::EstablishDisaggTask(
     try
     {
         auto task = std::make_shared<std::packaged_task<void()>>(
-            [&handler, &request, &response, deadline = grpc_context->deadline()]() {
+            [db_context = db_context, &task_id, &request, &response, deadline = grpc_context->deadline()]() {
```
Comment (guo-shaoge) [inline dbms/src/Flash/FlashService.cpp:905]:
```suggestion
            [&db_context, &task_id, &request, &response, deadline = grpc_context->deadline()]() {
```
maybe better?

**Review by JaySon-Huang — APPROVED** [review]

**Review by guo-shaoge — APPROVED** [review]
