### PR TITLE
refine LAC in disaggregated mode

### LINKED ISSUE #8178: Disaggregated storage tiflash should not start LAC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

For disaggregated storage tiflash node, will not use pipeline model(a.k.a. RCQ) to execute. So no need to start LAC

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #8178

Problem Summary:
1. Do not start LAC and pipeline TaskScheduler for **WN**. Because WN will not run any queires. And for now WN doesn't support resource control.
2. Make low token threshold lower. 0.8 is too high. It may cause rpc to GAC too frequent.
3. Delete server id from GAC when LAC stopped. Because on Serverless Tier, **CN** will scale in/out frequently, so we can avoid too many server id allocated from GAC.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. start tidb cluster with one or more tiflash
2. search log(keyword: get unique_client_id succeed) to check the unique client id of LAC. Run `etcdctl get --prefix '/tidb/server_id/{client_id_of_LAC}'` to check it from GAC, should get successfully.
4. kill tiflash
5. run `etcdctl get --prefix '/tidb/server_id/{client_id_of_LAC}'` , the server id has been deleted.
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by SeaRise — APPROVED** [review]
lgtm

File: dbms/src/Flash/executeQuery.cpp [hunk 1]
```diff
@@ -155,6 +155,7 @@ std::optional<QueryExecutorPtr> executeAsPipeline(Context & context, bool intern
     }
 
     prepareForExecute(context);
+    dag_context.enableResourceControl();
```
Comment (windtalker) [inline dbms/src/Flash/executeQuery.cpp:158]: Why change this

File: dbms/src/Flash/ResourceControl/LocalAdmissionController.h [hunk 2]
```diff
@@ -580,6 +603,7 @@ class LocalAdmissionController final : private boost::noncopyable
         = std::chrono::steady_clock::now();
 
     ::pingcap::kv::Cluster * cluster = nullptr;
+    std::atomic<bool> need_reset_unique_client_id{false};
```
Comment (windtalker) [inline dbms/src/Flash/ResourceControl/LocalAdmissionController.h:606]: When will this be false? Looks like it is always true once `unique_client_id` is initialized?

Comment (guo-shaoge) [reply dbms/src/Flash/ResourceControl/LocalAdmissionController.h:606]: This is to avoid `deleteServerIDFromGAC()` is called before `acquireServerIDFromGAC()` succeed.

File: dbms/src/Flash/executeQuery.cpp (hunk 1 above)
Comment (guo-shaoge) [reply dbms/src/Flash/executeQuery.cpp:158]: We have to put it before PipelineExecutor is constructed.

**Review by windtalker — APPROVED** [review]
LGTM

File: dbms/src/Flash/ResourceControl/LocalAdmissionController.h [hunk 3]
```diff
@@ -479,6 +485,23 @@ class LocalAdmissionController final : private boost::noncopyable
             if (thread.joinable())
                 thread.join();
         }
+
+        if (need_reset_unique_client_id.load())
+        {
+            try
+            {
+                etcd_client->deleteServerIDFromGAC(unique_client_id);
```
Comment (SeaRise) [inline dbms/src/Flash/ResourceControl/LocalAdmissionController.h:493]: It looks like `unique_client_id` has a data race, use `std::atomic_uint64` instead?

Comment (guo-shaoge) [reply dbms/src/Flash/ResourceControl/LocalAdmissionController.h:493]: ok
