### PR TITLE
Rate limiter for parallel prehandling

### LINKED ISSUE #8081: [Dynamic Region] TiFlash can't catch up with TiKV when there is only one big region pending prehandle
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #8081

Problem Summary:

In the previous PR, we introduced parallel prehandling for a single big region. However, it's believed there are also some cases that has a few, but more than 1 ongoing big snapshot. In these cases, the second snapshot can't benefit from parallel prehandling.

### What is changed and how it works?

The idea is that we introduced a parallel limit, which equals to `snap-handle-pool-size`. Every **subtask** of a parallel prehandling task take a parallel unit. If a prehandling task takes more parallel units than what's left, the task will sleep, until some other prehandling subtask is finished.

| item | master | this pr |
|:-:| :-: |:-:|
| splits | 1(always) | 4+3+3 |
| lines | - | 10451012*3 |
| interval between two ddls | - | 2m38s |

| item | master | this pr |
|:-:| :-: |:-:|
| splits | 1(always) | 4+4+4 |
| lines | - | 20276455*3 |
| interval between two ddls | - | 2m42s |

Note there is much time wasted before the first snapshot is arrived.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/KVStore/KVStore.cpp [hunk 1]
```diff
@@ -51,6 +51,35 @@ extern const char force_fail_in_flush_region_data[];
 extern const char pause_passive_flush_before_persist_region[];
 } // namespace FailPoints
 
+void PreHandlingTrace::waitForSubtaskResources(uint64_t region_id, size_t parallel)
+{
+    auto parallel_subtask_limit = kvstore->getMaxParallelPrehandleSize();
+    if (ongoing_prehandle_subtask_count.load() + parallel <= parallel_subtask_limit)
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/KVStore.cpp:57]: Yes, but this rarely happens. Even if it does happen, no significant harm, because the count of vCores is limited.
However, a simple cas is more neat here, so I will fix that.

File: dbms/src/Debug/MockRaftStoreProxy.cpp [hunk 2]
```diff
@@ -180,9 +180,10 @@ static RaftstoreVer fn_get_cluster_raftstore_version(RaftStoreProxyPtr ptr, uint
 }
 
 // Must call `RustGcHelper` to gc the returned pointer in the end.
-static RustStrWithView fn_get_config_json(RaftStoreProxyPtr, uint64_t)
+static RustStrWithView fn_get_config_json(RaftStoreProxyPtr ptr, uint64_t)
 {
-    auto * s = new std::string(R"({"raftstore":{"snap-handle-pool-size":4}})");
+    auto & x = as_ref(ptr);
+    auto * s = new std::string(x.proxy_config_string);
```
Comment (JaySon-Huang) [inline dbms/src/Debug/MockRaftStoreProxy.cpp:186]: why we need to create the `x = as_ref(ptr)`? Can we directly use `auto * s = new std::string(ptr->proxy_config_string);`?

Comment (CalvinNeo) [reply dbms/src/Debug/MockRaftStoreProxy.cpp:186]: There is no `proxy_config_string` in `RaftStoreProxyPtr`.
You can consider `RaftStoreProxyPtr` as a `void*` passed between proxy and tiflash by ffi.

Comment (JaySon-Huang) [reply dbms/src/Debug/MockRaftStoreProxy.cpp:186]: ok, I see `as_ref` is a `reinterpret_cast`

File: dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h [hunk 3]
```diff
@@ -31,8 +31,19 @@ struct PreHandlingTrace : MutexLockWrap
         {}
         std::atomic_bool abort_flag;
     };
+
+    class KVStore * kvstore;
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h:35]: why we need this ptr as a member of `PreHandlingTrace`

Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h:35]: `updateProxyConfig` can only be called some time after the KVStore is constructed

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 4]
```diff
@@ -69,21 +70,27 @@ struct ReadFromStreamResult
...
     const RegionPtr & new_region,
+    PreHandlingTrace & trace,
     const std::shared_ptr<PreHandlingTrace::Item> & prehandle_task,
     DM::FileConvertJobType job_type,
     const std::shared_ptr<StorageDeltaMerge> & storage,
     const std::shared_ptr<DM::SSTFilesToBlockInputStream> & sst_stream,
     const DM::SSTFilesToBlockInputStreamOpts & opts,
     TMTContext & tmt)
 {
+    UNUSED(trace);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:81]:
```suggestion
```

File: dbms/src/Storages/KVStore/KVStore.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (JaySon-Huang) [reply dbms/src/Storages/KVStore/KVStore.cpp:57]: Yes, we should only keep the logic after `cpu_resource_cv` wait returns

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 5]
```diff
@@ -612,23 +678,32 @@ PrehandleResult KVStore::preHandleSSTsToDTFiles(
 
             // `split_keys` do not begin with 'z'.
             auto [split_keys, approx_bytes] = getSplitKey(log, this, new_region, sst_stream);
-
+            prehandling_trace.waitForSubtaskResources(region_id, split_keys.size() + 1);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:681]: what about `prehandling_trace.waitForSubtaskResources(region_id, split_keys.size() + 1, ->getMaxParallelPrehandleSize());`
and remove `KVStore * kvstore` from `PreHandlingTrace`?

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 6]
```diff
@@ -311,12 +363,15 @@ static inline std::pair<std::vector<std::string>, size_t> getSplitKey(
         LOG_INFO(
             log,
             "getSplitKey result {}, total_concurrency={} ongoing={} total_split_parts={} split_keys={} "
+            "region_range {} approx_bytes {}"
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:366]:
```suggestion
            "region_range={} approx_bytes={} "
```

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp (hunk 5 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:681]: In what class should we put `getMaxParallelPrehandleSize`?

File: dbms/src/Storages/KVStore/KVStore.cpp [hunk 7]
```diff
@@ -108,6 +138,11 @@ void KVStore::restore(PathPool & path_pool, const TiFlashRaftProxyHelper * proxy
         }
     }
 
+    updateProxyConfig(proxy_helper);
+}
+
+void KVStore::updateProxyConfig(const TiFlashRaftProxyHelper * proxy_helper)
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/KVStore.cpp:115]: fixed

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp (hunk 5 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:681]: The function here is `KVStore::preHandleSSTsToDTFiles`, it can access to `KVStore::getMaxParallelPrehandleSize` by `this-> getMaxParallelPrehandleSize()`

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 8]
```diff
@@ -66,24 +67,69 @@ struct ReadFromStreamResult
...
+        {
+            LOG_DEBUG(
+                log,
+                "Prehandle resource meet, limit={}, current={}, region_id={}",
+                parallel_subtask_limit,
+                ongoing_prehandle_subtask_count.load(),
+                region_id);
+            return;
+        }
+    }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:85]: If `parallel_subtask_limit = 16`, `current = 15`, `parallel = 4`. It will make the `ongoing_prehandle_subtask_count` = `15 + 4 == 19` which exceed the limit `16`

Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:84]: fixed

File: dbms/src/Storages/KVStore/KVStore.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/KVStore.cpp]: fixed

File: dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h [hunk 9]
```diff
@@ -31,8 +31,17 @@ struct PreHandlingTrace : MutexLockWrap
         {}
         std::atomic_bool abort_flag;
     };
+
     std::unordered_map<uint64_t, std::shared_ptr<Item>> tasks;
+    std::atomic<uint64_t> ongoing_prehandle_subtask_count{0};
+    uint64_t parallel_subtask_limit;
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h:37]:
```suggestion
```
This can be removed

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 10]
```diff
@@ -66,24 +68,70 @@ struct ReadFromStreamResult
...
+            && likely(ongoing_prehandle_subtask_count.compare_exchange_weak(current, current + parallel)))
+        {
+            LOG_DEBUG(
+                log,
+                "Prehandle resource meet, limit={}, current={}, region_id={}",
+                parallel_subtask_limit,
+                ongoing_prehandle_subtask_count.load(),
+                region_id);
+            return;
+        }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:85]:
```suggestion
        if (likely(current + parallel <= parallel_subtask_limit
            && ongoing_prehandle_subtask_count.compare_exchange_weak(current, current + parallel)))
        {
            LOG_DEBUG(
                log,
                "Prehandle resource meet, limit={} current={} parallel={} region_id={}",
                parallel_subtask_limit,
                ongoing_prehandle_subtask_count.load(),
                parallel,
                region_id);
            return;
        }
```

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 11]
```diff
@@ -66,24 +68,70 @@ struct ReadFromStreamResult
...
+    }
+    Stopwatch watch;
+    LOG_DEBUG(
+        log,
+        "Prehandle resource wait begin, limit={}, current={}, region_id={}",
+        parallel_subtask_limit,
+        ongoing_prehandle_subtask_count.load(),
+        region_id);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:93]:
```suggestion
    LOG_DEBUG(
        log,
        "Prehandle resource wait begin, limit={} current={} parallel={} region_id={}",
        parallel_subtask_limit,
        ongoing_prehandle_subtask_count.load(),
        parallel,
        region_id);
```

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 12]
```diff
@@ -66,24 +68,70 @@ struct ReadFromStreamResult
...
+        cpu_resource_cv.wait(cpu_resource_lock, [&]() {
+            return ongoing_prehandle_subtask_count.load() + parallel <= parallel_subtask_limit;
+        });
+        auto current = ongoing_prehandle_subtask_count.load();
+        if (current + parallel <= parallel_subtask_limit
+            && likely(ongoing_prehandle_subtask_count.compare_exchange_weak(current, current + parallel)))
+        {
+            break;
+        }
+    }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:106]:
```suggestion
        if (likely(current + parallel <= parallel_subtask_limit
            && ongoing_prehandle_subtask_count.compare_exchange_weak(current, current + parallel)))
        {
            break;
        }
    }
```

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 13]
```diff
@@ -66,24 +68,70 @@ struct ReadFromStreamResult
...
+    GET_METRIC(tiflash_raft_command_duration_seconds, type_apply_snapshot_predecode_parallel_wait)
+        .Observe(watch.elapsedSeconds());
+    LOG_INFO(log, "Prehandle resource acquired after {} seconds, region_id={}", watch.elapsedSeconds(), region_id);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:109]:
```suggestion
    LOG_INFO(log, "Prehandle resource acquired after {:.3f} seconds, region_id={} parallel={}", watch.elapsedSeconds(), region_id, parallel);
```

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 14]
```diff
@@ -612,23 +686,32 @@ PrehandleResult KVStore::preHandleSSTsToDTFiles(
...
             auto [split_keys, approx_bytes] = getSplitKey(log, this, new_region, sst_stream);
-
+            prehandling_trace.waitForSubtaskResources(region_id, split_keys.size() + 1, getMaxParallelPrehandleSize());
             ReadFromStreamResult result;
             if (split_keys.empty())
             {
                 LOG_INFO(
                     log,
-                    "Single threaded prehandling for single big region, range={}, region_id={}",
+                    "Single threaded prehandling for single region, range={}, region_id={}",
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:695]:
```suggestion
                    "Single threaded prehandling for single region, range={} region_id={}",
```

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 15]
```diff
@@ -517,10 +588,13 @@ void executeParallelTransform(
         }
         LOG_INFO(
             log,
-            "Finished all extra parallel prehandle task write cf {} dmfiles {} error {}, region_id={}",
+            "Finished all extra parallel prehandle task write cf {} dmfiles {} error {}, splits={}, cost={}s, "
+            "region_id={}",
```
Comment (JaySon-Huang) [inline dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:592]:
```suggestion
            "Finished all extra parallel prehandle task, write_cf={} dmfiles={} error={} splits={} cost={:.3f}s "
            "region_id={}",
```

**Review by JaySon-Huang — COMMENTED** [review]
Rest LGTM

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp (hunk 10 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:85]: Why?`current + parallel <= parallel_subtask_limit` is not `likely` if there are too many prehandle snapshot tasks from proxy.

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp (hunk 12 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:107]: ditto

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp (hunk 10 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:85]: `likely` macro works on branching prediction to let the code generator reorganize the asm code following the if condition. I think there is no meaning to marking "half" of the if condition as `likely`

Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:85]: Yes you are right, I think I should split it into two `if`s?

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp [hunk 16]
```diff
@@ -215,6 +271,21 @@ PrehandleResult KVStore::preHandleSnapshotToFiles(
     return result;
 }
 
+size_t KVStore::getMaxParallelPrehandleSize() const
+{
+    const auto & proxy_config = getProxyConfigSummay();
+    size_t total_concurrency = 0;
+    if (proxy_config.valid)
+    {
+        total_concurrency = proxy_config.snap_handle_pool_size;
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:280]: It is in https://github.com/pingcap/tidb-engine-ext/blob/521fd9dbc55e58646045d88f91c3c35db50b5981/proxy_components/proxy_server/src/config.rs#L50

The idea here is in raftstore-v2 scene, many table has only one snapshots, so if there the only region of this table is serving, TiFlash can't actually serve anything.

However, I think I can adopt the previous strategy, since it is less aggresive.

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp (hunk 10 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp:85]: Well, I think this is not the critical path for branching prediction missing, so the `likely` here does not act as an important part. So I'd like to keep the code simple.
Just one `if` with or without `likely` is OK to me.

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Comment by JaySon-Huang** [comment]
/run-integration-test

The tidb-ci tests returned with exit code 1, let's try rerun it
```
path: /home/jenkins/agent/workspace/tiflash-ghpr-integration-tests/tests/tidb-ci
— Print Message
<1s
TAG=b176a5923180e2c167fe5dc348b2253433c46aff BRANCH=master ./run.sh
— Shell Script
5s
script returned exit code 1
```

File: dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp (hunk 10 above)
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp]: Makes sense
