### PR TITLE
Storages: use default string type in DeltaMergeStore

### LINKED ISSUE #9983: The new string deserialization method is not applied to the existing table columns before upgrade
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Deploy a cluster with v8.5.1
2. Load TPC-H 50 into the cluster and create tiflash replica
3. Upgrade the cluster to nightly (20250311)

### 2. What did you expect to see? (Required)

The varchar column should utilize the new string deserialization method (introduce by https://github.com/pingcap/tiflash/issues/9673) and TPC-H performance should be better than v8.5.1

### 3. What did you see instead (Required)

The old data still use the old string deserialization method

### 4. What is your TiFlash version? (Required)

```
# ./bin/tiflash/tiflash version
TiFlash
Release Version: v9.0.0-alpha-90-g93ff0c715
Edition:         Community
Git Commit Hash: 93ff0c715db950d108d9c9bd4a4923340647d81b
Git Branch:      HEAD
UTC Build Time:  2025-03-10 10:32:41
Enable Features: jemalloc sm4(GmSSL) mem-profiling avx2 avx512 unwind thinlto hnsw.l2=skylake hnsw.cosine=skylake vec.l2=skylake vec.cos=skylake
Profile:         RELWITHDEBINFO
Compiler:        clang++ 17.0.6

Raft Proxy
Git Commit Hash:   b99342a4b000ff6d6e145d0f5f88aa9516078a6c
Git Commit Branch: HEAD
UTC Build Time:    ""
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Storage Engine:    tiflash
Prometheus Prefix: tiflash_proxy_
Profile:           release
Enable Features:   external-jemalloc portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine openssl-vendored
```

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #9983

### What is changed and how it works?

```commit-message
- Converting string type to default parameter in DeltaMergeStore
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  - Compacting tiflash replica make string data from `String` to `StringV2`. 

image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix a bug that the string serialize method of existing data does not follow `storage.format_version` after upgraded
```

### CODE REVIEW

File: dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp [hunk 1]
```diff
@@ -206,6 +206,26 @@ ColumnDefinesPtr generateStoreColumns(const ColumnDefines & table_columns, bool
...
+    static const auto default_string_type = DataTypeFactory::instance().getOrSet(DataTypeString::getDefaultName());
+    static const auto default_nullable_string_type
+        = DataTypeFactory::instance().getOrSet(DataTypeString::getNullableDefaultName());
+
+    if (removeNullable(type)->getTypeId() != TypeIndex::String)
+        return;
+    if (type->isNullable())
+        type = default_nullable_string_type;
+    else
+        type = default_string_type;
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:221]:
```suggestion
    if (removeNullable(type)->getTypeId() != TypeIndex::String)
        return;
    if (type->isNullable())
        type = DataTypeFactory::instance().getOrSet(DataTypeString::getNullableDefaultName());
    else
        type = DataTypeFactory::instance().getOrSet(DataTypeString::getDefaultName());
```

IMO, we can directly use `DataTypeFactory::getOrSet` instead of storing a static type ptr on this method. `DataTypeFactory::getOrSet` itself is lightweight enough.

**Review by JaySon-Huang — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]
