### PR TITLE
clear encryption info for temporary dmfile

### LINKED ISSUE #5979: tiflash can't start for the error of frame length mismatch for pack
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2022/09/21 17:23:58.688 +08:00] [ERROR] [Exception.cpp:89] ["DB::DM::DeltaMergeStore::DeltaMergeStore(DB::Context &, bool, const DB::String &, const DB::String &, DB::TableID, const DB::DM::ColumnDefines &, const DB::DM::ColumnDefine &, bool, size_t, const DB::DM::DeltaMergeStore::Settings &):Code: 0, e.displayText() = DB::TiFlashException: frame length (header = 16, body = 9882380890659910483, read = 4048) mismatch for /data0/db/data/t_259/stable/dmf_6486/pack, e.what() = DB::TiFlashException, Stack trace:


       0x1e867b1    DB::TiFlashException::TiFlashException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::TiFlashError const&) [tiflash+32008113]
                    dbms/src/Common/TiFlashException.h:250
       0x1dc1306    DB::FramedChecksumReadBuffer<DB::Digest::XXH3>::doSeek(long, int) [tiflash+31200006]
                    dbms/src/IO/ChecksumBuffer.h:425
       0x6e9a2be    DB::DM::DMFile::readMetadata(std::__1::shared_ptr<DB::FileProvider> const&, DB::DM::DMFile::ReadMetaMode const&) [tiflash+115974846]
                    dbms/src/Storages/DeltaMerge/File/DMFile.cpp:609
       0x6e97d9a    DB::DM::DMFile::restore(std::__1::shared_ptr<DB::FileProvider> const&, unsigned long, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DM::DMFile::ReadMetaMode const&) [tiflash+115965338]
                    dbms/src/Storages/DeltaMerge/File/DMFile.cpp:173
       0x6e571b7    DB::DM::StableValueSpace::restore(DB::DM::DMContext&, unsigned long) [tiflash+115700151]
                    dbms/src/Storages/DeltaMerge/StableValueSpace.cpp:111
       0x6dfa906    DB::DM::Segment::restoreSegment(DB::DM::DMContext&, unsigned long) [tiflash+115321094]
                    dbms/src/Storages/DeltaMerge/Segment.cpp:286
       0x6d9c74b    DB::DM::DeltaMergeStore::DeltaMergeStore(DB::Context&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, long, std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > const&, DB::DM::ColumnDefine const&, bool, unsigned long, DB::DM::DeltaMergeStore::Settings const&) [tiflash+114935627]
                    dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:261
       0x6d2c216    DB::StorageDeltaMerge::getAndMaybeInitStore() [tiflash+114475542]
                    dbms/src/Storages/StorageDeltaMerge.cpp:1526
       0x1ecdbe5    DB::initStores(DB::Context&, std::__1::shared_ptr<DB::Logger> const&, bool)::$_7::operator()() const [tiflash+32300005]
                    dbms/src/Server/Server.cpp:491
       0x1eed931    void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, DB::initStores(DB::Context&, std::__1::shared_ptr<DB::Logger> const&, bool)::$_7> >(void*) [tiflash+32430385]
                    /usr/local/bin/../include/c++/v1/thread:291
  0x7f0ec1fb3ea5    start_thread [libpthread.so.0+32421]
  0x7f0ec13b896d    __clone [libc.so.6+1042797]"] [thread_id=109]
```
### 4. What is your TiFlash version? (Required)
master 1223584da088dab0c05a179dd2f65dda5a77c73e

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #5979

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/DeltaMerge/File/DMFile.cpp [hunk 1]
```diff
@@ -712,33 +712,24 @@ std::set<UInt64> DMFile::listAllInPath(
...
-            {
-                // Clear deleted (maybe broken) DTFiles
+                // Clear temporary/deleted (maybe broken) files
+                // The encryption info use readable path. We are not sure the encryption info is deleted or not.
+                // Try to delete and ignore if it is already deleted.
                 auto res = try_parse_file_id(name);
                 if (!res)
                 {
-                    LOG_FMT_INFO(log, "Unrecognized dropped DM file, ignored: {}", name);
+                    LOG_FMT_INFO(log, "Unrecognized temporary or dropped dmfile, ignored: {}", name);
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/DeltaMerge/File/DMFile.cpp:723]: Use `LOG_INFO` instead. We will remove `LOG_FMT_XXX` which is the same as `LOG_XXX`.

Comment (lidezhu) [reply dbms/src/Storages/DeltaMerge/File/DMFile.cpp]: Fixed.

**Review by Lloyd-Pottiger — APPROVED** [review]

File: dbms/src/Storages/DeltaMerge/File/DMFile.cpp [hunk 2]
```diff
@@ -712,33 +712,24 @@ std::set<UInt64> DMFile::listAllInPath(
         // or you may delete some writing files
         if (options.clean_up)
         {
-            if (startsWith(name, details::FOLDER_PREFIX_WRITABLE))
+            if (startsWith(name, details::FOLDER_PREFIX_WRITABLE) || startsWith(name, details::FOLDER_PREFIX_DROPPED))
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/File/DMFile.cpp:715]: > From the log "[2022/09/21 00:54:23.069 +08:00] [WARN] [DMFile.cpp:721] ["DMFile:Existing temporary dmfile, removed: /data0/db/data/t_259/stable/.tmp.dmf_6486"] [thread_id=109]", it seems there is a temporary file of the same file id with the above broken file. So this issue should be caused by the absence of clearing encryption info of old temporary files.

I am still not clear why there are a `.tmp.dmf_6486` and a `dmf_6486` sharing the same encryption info.

Comment (lidezhu) [reply dbms/src/Storages/DeltaMerge/File/DMFile.cpp:715]: These two files doesn't exist at the same time. `.tmp.dmf_6486` is a temporary file which is generated by previous run and is removed at restart.
And after some investigation into the encryption key related source code, I don't find other info about this problem and realize that this is not an urgent problem and continue to dig into it will cost a lot of time. So I decide just remove the encryption info of old file which is the right thing to do and see whether the test fail again. And even the test fails again, this can help us eliminate a wrong direction

Comment (JaySon-Huang) [reply dbms/src/Storages/DeltaMerge/File/DMFile.cpp:715]: OK

**Review by JaySon-Huang — APPROVED** [review]
lgtm
