### PR TITLE
Cancel MPP task works on Mpp gather level

### LINKED ISSUE #7744: tiflash report "DB::TiFlashException: Failed to register MPP Task MPP" during query
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
when the query has a non-correlated subquery and the non-correlated subquery will end early. then tiflash will return this error:
```
[2023/07/04 01:14:02.527 +08:00] [ERROR] [upgrade_test.go:217] ["check consistence error"] [error="Error 1105: DB
::TiFlashException: Failed to register MPP Task MPP<query:<query_ts:1688404441135806359, local_query_id:167, serv
er_id:912316, start_ts:442605093804572686>,task_id:3>, reason: query is being aborted, error message = Receive ca
ncel request from TiDB"] [sql="\nselect d, count(*) as order_count, max(d) as m\nfrom t\nwhere jj >= '2007-01-02
00:00:00.000000'and jj < '2032-01-02 00:00:00.000000'and exists (select * from t where jj >= kk) and d > m - 1\ng
roup by d\norder by d limit 1000\n"]
```
### 2. What did you expect to see? (Required)
query execute successfully
### 3. What did you see instead (Required)
```
[2023/07/03 17:14:02.522 +00:00] [ERROR] [MPPHandler.cpp:97] ["dispatch task meet error : DB::TiFlashException: Failed to register MPP Task MPP<query:<query_ts:1688404441135806359, local_query_id:167, server_id:912316, start_ts:442605093804572686>,task_id:3>, reason: query is being aborted, error message = Receive cancel request from TiDB"] [thread_id=177]
[2023/07/03 17:14:02.522 +00:00] [WARN] [MPPTaskManager.cpp:187] ["Begin to abort query: <query_ts:1688404441135806359, local_query_id:167, server_id:912316, start_ts:442605093804572686>, abort type: ONERROR, reason: From MPP<query:<query_ts:1688404441135806359, local_query_id:167, server_id:912316, start_ts:442605093804572686>,task_id:3>: DB::TiFlashException: Failed to register MPP Task MPP<query:<query_ts:1688404441135806359, local_query_id:167, server_id:912316, start_ts:442605093804572686>,task_id:3>, reason: query is being aborted, error message = Receive cancel request from TiDB"] [thread_id=177]
[2023/07/03 17:14:02.522 +00:00] [WARN] [MPPTaskManager.cpp:204] ["<query_ts:1688404441135806359, local_query_id:167, server_id:912316, start_ts:442605093804572686> already in abort process, skip abort"] [thread_id=177]
[2023/07/03 17:14:02.522 +00:00] [ERROR] [MPPHandler.cpp:97] ["dispatch task meet error : DB::TiFlashException: Failed to register MPP Task MPP<query:<query_ts:1688404441135806359, local_query_id:167, server_id:912316, start_ts:442605093804572686>,task_id:2>, reason: query is being aborted, error message = Receive cancel request from TiDB"] [thread_id=175]
[2023/07/03 17:14:02.522 +00:00] [WARN] [MPPTask.cpp:658] ["Begin abort task: MPP<query:<query_ts:1688404441135806359, local_query_id:167, server_id:912316, start_ts:442605093804572686>,task_id:3>, abort type: ONERROR"] [source="MPP<query:<query_ts:1688404441135806359, local_query_id:167, server_id:912316, start_ts:442605093804572686>,task_id:3>"] [thread_id=177]
```
### 4. What is your TiFlash version? (Required)
master

### LINKED ISSUE #7746: Cancel MPPQuery should take effect in MPPGather's level
## Enhancement
Sometimes in TiDB a query will generate multiple standalone "mpp sub-queries", for example:
```
mysql> explain select * from test a join (select * from test limit 10) b on a.id = b.id;
+------------------------------------+------------+--------------+---------------+----------------------------------------------------+
| id                                 | estRows    | task         | access object | operator info                                      |
+------------------------------------+------------+--------------+---------------+----------------------------------------------------+
| HashJoin_13                        | 3506304.00 | root         |               | inner join, equal:[eq(test.test.id, test.test.id)] |
| ├─Selection_22(Build)              | 8.00       | root         |               | not(isnull(test.test.id))                          |
| │ └─Limit_25                       | 10.00      | root         |               | offset:0, count:10                                 |
| │   └─TableReader_33               | 10.00      | root         |               | MppVersion: 2, data:ExchangeSender_32              |
| │     └─ExchangeSender_32          | 10.00      | mpp[tiflash] |               | ExchangeType: PassThrough                          |
| │       └─Limit_31                 | 10.00      | mpp[tiflash] |               | offset:0, count:10                                 |
| │         └─TableFullScan_30       | 10.00      | mpp[tiflash] | table:test    | keep order:false                                   |
| └─TableReader_21(Probe)            | 524288.00  | root         |               | MppVersion: 2, data:ExchangeSender_20              |
|   └─ExchangeSender_20              | 524288.00  | mpp[tiflash] |               | ExchangeType: PassThrough                          |
|     └─Selection_19                 | 524288.00  | mpp[tiflash] |               | not(isnull(test.test.id))                          |
|       └─TableFullScan_18           | 524288.00  | mpp[tiflash] | table:a       | pushed down filter:empty, keep order:false         |
+------------------------------------+------------+--------------+---------------+----------------------------------------------------+
11 rows in set (0.00 sec)
```
`ExchangeSender_32` and `ExchangeSender_20` are actually two standalone mpp sub-queries, and each of the subqueries in TiDB side is handled by a `mpp_gather`, so this query will generate mpp tasks that belongs two different `mpp_gather`. From tidb's point of view, different `mpp_gather` has its own lifecycle, it is possible that TiDB wants to cancel one of the `mpp_gather`'s execution while keep other `mpp_gather`'s execution un-affected. For example, if `Limit_25` has enough input, TiDB will cancel the mpp_gather that opens `ExchangeSender_32`, and of cause, TiDB does not want `ExchangeSender_20` to be affected by that cancel(After #7589, it almost 100% sure that `ExchangeSender_20` will be affected by that cancel). This means when TiDB send a `CancelMPPQuery` request, it actually wants to cancel all the mpp tasks that belongs to a specific `mpp_gather`. After https://github.com/pingcap/tidb/pull/44697, TiDB already set a meaningfull value of `gather_id` in `mpp::TaskMeta`, it's time for TiFlash to support `MPPGather`' level's cancel

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #7746, close #7744

Problem Summary:

### What is changed and how it works?
- Change the organization of MPPTasks in MPPTaskManager from two-level to three-level:
  - Before this pr: `MPPTask`s => `MPPQueryTaskSet`, `MPPQueryTaskSet`s => `MPPTaskMananger` 
  - After this pr: `MPPTask`s => `MPPGatherTaskSet`, `MPPGatherTaskSet`s => `MPPQuery`, `MPPQuery`s => `MPPTaskManager`
- `Cancel/Abort` mpp task works on `MPPGather` level, cancel a mpp gather does not affect other mpp gathers that belongs to the same mpp query
- `Schedule` mpp task still works on `MPPQuery` level, which means if a mpp query is the min-tso query, all the gathers belongs to the same mpp query will be scheduled
- Refine test to support mpp gather
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  - test tpch queries
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/Mpp/MPPTask.cpp [hunk 1]
```diff
@@ -228,7 +228,9 @@ void MPPTask::registerTunnels(const mpp::DispatchTaskRequest & task_request)
         if (status != INITIALIZING)
             throw Exception(fmt::format("The tunnel {} can not be registered, because the task is not in initializing state", tunnel->id()));
 
-        tunnel_set_local->registerTunnel(MPPTaskId(task_meta), tunnel);
+        MPPTaskId task_id(task_meta);
+        RUNTIME_CHECK_MSG(id.gather_id.hasMeaningfulGatherId() == task_id.gather_id.hasMeaningfulGatherId(), "MPP query has gather id while mpp task does not have gather id, should be something wrong in TiDB side");
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/MPPTask.cpp:232]: why not `id.gather_id == task_id.gather_id`?

File: dbms/src/Flash/Mpp/MPPTaskId.h [hunk 2]
```diff
@@ -56,20 +56,34 @@ struct MPPQueryIdHash
...
+        : gather_id(task_meta.gather_id())
+        , query_id(task_meta)
+    {}
+    String toString() const
+    {
+        return fmt::format("<gather_id:{}, query_ts:{}, local_query_id:{}, server_id:{}, start_ts:{}>", gather_id, query_id.query_ts, query_id.local_query_id, query_id.server_id, query_id.start_ts);
+    }
+    bool hasMeaningfulGatherId() const
+    {
+        return gather_id > 0;
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/MPPTaskId.h:85]: Does the tidb side guarantee that the gather id must be greater than 0?

File: dbms/src/TestUtils/MPPTaskTestUtils.cpp [hunk 3]
```diff
@@ -180,18 +182,52 @@ ::testing::AssertionResult MPPTaskTestUtils::assertQueryCancelled(const MPPQuery
...
+{
+    auto seconds = std::chrono::seconds(1);
+    auto retry_times = 0;
+    for (int i = test_meta.context_idx; i < TiFlashTestEnv::globalContextSize(); ++i)
+    {
+        // wait until the task is empty for <query:start_ts>
+        while (TiFlashTestEnv::getGlobalContext(i).getTMTContext().getMPPTaskManager()->getGatherTaskSet(gather_id).first != nullptr)
+        {
+            std::this_thread::sleep_for(seconds);
+            retry_times++;
```
Comment (SeaRise) [inline dbms/src/TestUtils/MPPTaskTestUtils.cpp:195]:
```suggestion
            ++retry_times;
```

File: dbms/src/Flash/tests/gtest_compute_server.cpp [hunk 4]
```diff
@@ -885,56 +889,126 @@ try
...
+            MockComputeServerManager::instance().cancelGather(gather_id);
+        for (auto & t : running_queries)
+            if (t.joinable())
+                t.join();
+        throw;
+    }
+}
+CATCH
+
+TEST_F(ComputeServerRunner, testCancelMPPGather)
```
Comment (SeaRise) [inline dbms/src/Flash/tests/gtest_compute_server.cpp:950]: Can you add an `apply with limit` case to the fullstack test?

File: dbms/src/Flash/Mpp/MPPTaskId.h [hunk 5]
```diff
@@ -83,20 +97,20 @@ struct MPPTaskId
 {
     MPPTaskId()
         : task_id(unknown_task_id)
-        , query_id({0, 0, 0, 0}){};
+        , gather_id(0, 0, 0, 0, 0){};
```
Comment (yibin87) [inline dbms/src/Flash/Mpp/MPPTaskId.h:100]: A little strange here, gather_id has meaningful gather id, while task_id with unknown_task_id,

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp [hunk 6]
```diff
@@ -182,69 +208,69 @@ std::pair<MPPTunnelPtr, String> MPPTaskManager::findTunnelWithTimeout(const ::mp
...
-    LOG_WARNING(log, fmt::format("Begin to abort query: {}, abort type: {}, reason: {}", query_id.toString(), magic_enum::enum_name(abort_type), reason));
-    MPPQueryTaskSetPtr task_set;
+    LOG_WARNING(log, fmt::format("Begin to abort gather: {}, abort type: {}, reason: {}", gather_id.toString(), magic_enum::enum_name(abort_type), reason));
+    MPPGatherTaskSetPtr gather_task_set;
     {
         /// abort task may take a long time, so first
         /// set a flag, so we can abort task one by
         /// one without holding the lock
         std::lock_guard lock(mu);
         /// gather_id is not set by TiDB, so use 0 instead
```
Comment (yibin87) [inline dbms/src/Flash/Mpp/MPPTaskManager.cpp:220]: Update comments here

**Review by yibin87 — APPROVED** [review]
LGTM

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp [hunk 7]
```diff
@@ -93,46 +116,49 @@ std::pair<MPPTunnelPtr, String> MPPTaskManager::findAsyncTunnel(const ::mpp::Est
...
 
     std::unique_lock lock(mu);
-    auto [query_set, error_msg] = getQueryTaskSetWithoutLock(id.query_id);
+    auto [query, gather_task_set, error_msg] = getMPPQueryAndGatherTaskSet(id.gather_id);
     if (!error_msg.empty())
     {
-        /// if the query is aborted, return the error message
-        LOG_WARNING(log, fmt::format("{}: Query {} is aborted, all its tasks are invalid.", req_info, id.query_id.toString()));
+        /// if the gather is aborted, return the error message
+        LOG_WARNING(log, fmt::format("{}: Gather {} is aborted, all its tasks are invalid.", req_info, id.gather_id.toString()));
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Mpp/MPPTaskManager.cpp:123]:
```suggestion
        LOG_WARNING(log, "{}: Gather {} is aborted, all its tasks are invalid.", req_info, id.gather_id.toString());
```

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp [hunk 8]
```diff
@@ -154,20 +180,20 @@ std::pair<MPPTunnelPtr, String> MPPTaskManager::findTunnelWithTimeout(const ::mp
...
     std::unique_lock lock(mu);
     auto ret = cv.wait_for(lock, timeout, [&] {
-        auto [query_set, error_msg] = getQueryTaskSetWithoutLock(id.query_id);
+        auto [gather_task_set, error_msg] = getGatherTaskSetWithoutLock(id.gather_id);
         if (!error_msg.empty())
         {
-            /// if the query is aborted, return true to stop waiting timeout.
-            LOG_WARNING(log, fmt::format("{}: Query {} is aborted, all its tasks are invalid.", req_info, id.query_id.toString()));
+            /// if the gather is aborted, return true to stop waiting timeout.
+            LOG_WARNING(log, fmt::format("{}: Gather {} is aborted, all its tasks are invalid.", req_info, id.gather_id.toString()));
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Mpp/MPPTaskManager.cpp:187]:
```suggestion
            LOG_WARNING(log, "{}: Gather {} is aborted, all its tasks are invalid.", req_info, id.gather_id.toString());
```

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp [hunk 9]
```diff
@@ -182,69 +208,69 @@ std::pair<MPPTunnelPtr, String> MPPTaskManager::findTunnelWithTimeout(const ::mp
...
         /// gather_id is not set by TiDB, so use 0 instead
-        aborted_query_gather_cache.add(MPPGatherId(0, query_id), reason);
-        auto it = mpp_query_map.find(query_id);
-        if (it == mpp_query_map.end())
+        aborted_query_gather_cache.add(gather_id, reason);
+        auto [query, gather_task_set_local, _] = getMPPQueryAndGatherTaskSet(gather_id);
+        if (query == nullptr || gather_task_set_local == nullptr)
         {
-            LOG_WARNING(log, fmt::format("{} does not found in task manager, skip abort", query_id.toString()));
+            LOG_WARNING(log, fmt::format("{} does not found in task manager, skip abort", gather_id.toString()));
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Mpp/MPPTaskManager.cpp:225]:
```suggestion
            LOG_WARNING(log, "{} does not found in task manager, skip abort", gather_id.toString());
```

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp [hunk 10]
```diff
@@ -182,69 +208,69 @@ std::pair<MPPTunnelPtr, String> MPPTaskManager::findTunnelWithTimeout(const ::mp
...
                 alarm.second.Cancel();
         }
-        it->second->alarms.clear();
-        if (!it->second->hasMPPTask())
+        gather_task_set->alarms.clear();
+        if (!gather_task_set->hasMPPTask())
         {
-            LOG_INFO(log, fmt::format("There is no mpp task for {}, finish abort", query_id.toString()));
-            removeMPPQueryTaskSet(query_id, true);
+            LOG_INFO(log, fmt::format("There is no mpp task for {}, finish abort", gather_id.toString()));
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Mpp/MPPTaskManager.cpp:245]:
```suggestion
            LOG_INFO(log, "There is no mpp task for {}, finish abort", gather_id.toString());
```

File: dbms/src/Flash/Mpp/MPPTask.cpp (hunk 1 above)
Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTask.cpp:232]: OK

File: dbms/src/Flash/Mpp/MPPTaskId.h (hunk 2 above)
Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTaskId.h:85]: After https://github.com/pingcap/tidb/pull/45226, it is expected that all the gather_id in `TaskMeta` is greater than 0, before that pr, it is not guaranteed. In TiFlash side, I add some checks to ensure that if a mpp query has a meaningful gather id(greater that 0), then all the tasks belongs to the same mpp query must all have a meaningful gather id. That is to say, TiFlash only support two cases:
- All the mpp tasks have a meaningfull gather id
- All the mpp tasks have 0 as gather id
And luckily there is no compatibility issues since for TiDB version <= v7.2.0, all mpp tasks have 0 as the gather id, and for TiDB version >= 7.3.0, all mpp tasks should have a meaningful gather id.

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp (hunk 6 above)
Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTaskManager.cpp:220]: Done

File: dbms/src/Flash/Mpp/MPPTaskId.h (hunk 2 above)
Comment (SeaRise) [reply dbms/src/Flash/Mpp/MPPTaskId.h:85]: ok

**Review by SeaRise — APPROVED** [review]
lgtm

File: dbms/src/Flash/tests/gtest_compute_server.cpp (hunk 4 above)
Comment (windtalker) [reply dbms/src/Flash/tests/gtest_compute_server.cpp:950]: OK, add some apply tests.
