### PR TITLE
Fix tiflash crash caused by local tunnel

### LINKED ISSUE #6615: Tiflash crash when inject failpoint
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

random failpoint test
```
[2023/01/11 06:35:56.881 +08:00] [ERROR] [BaseDaemon.cpp:376] [########################################] [source=BaseDaemon] [thread_id=1936]
[2023/01/11 06:35:56.887 +08:00] [ERROR] [BaseDaemon.cpp:377] ["(from thread 742) Received signal Aborted(6)."] [source=BaseDaemon] [thread_id=1936]
[2023/01/11 06:35:56.950 +08:00] [ERROR] [BaseDaemon.cpp:569] ["
       0xa46472d    faultSignalHandler(int, siginfo_t*, void*) [tiflash+172377901]
                    libs/libdaemon/src/BaseDaemon.cpp:220
  0x7f6bc0272630    <unknown symbol> [libpthread.so.0+63024]
  0x7f6bbfab1387    gsignal [libc.so.6+222087]
  0x7f6bbfab2a78    __GI_abort [libc.so.6+227960]
  0x7f6bc9bb466f    std::__1::__libcpp_abort_debug_function(std::__1::__libcpp_debug_info const&) [libc++.so.1+464495]
       0x3b7fe5d    std::__1::vector<std::__1::shared_ptr<DB::MPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> > >, std::__1::allocator<std::__1::shared_ptr<DB::MPMCQueue<std::__1::shared_ptr<DB::ReceivedMessage> > > > >::operator[](unsigned long) [tiflash+62389853]
                    /usr/local/bin/../include/c++/v1/vector:1571
       0xb671d4c    DB::ReceiverChannelWriter::writeNonFineGrain(unsigned long, std::__1::shared_ptr<DB::TrackedMppDataPacket> const&, mpp::Error const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*) [tiflash+191307084]
                    dbms/src/Flash/Mpp/ReceiverChannelWriter.cpp:112
       0x3b6e18a    bool DB::ReceiverChannelWriter::write<false>(unsigned long, std::__1::shared_ptr<DB::TrackedMppDataPacket> const&) [tiflash+62316938]
                    dbms/src/Flash/Mpp/ReceiverChannelWriter.h:120
       0xb658e19    bool DB::LocalRequestHandler::write<false>(unsigned long, std::__1::shared_ptr<DB::TrackedMppDataPacket> const&) [tiflash+191204889]
                    dbms/src/Flash/Mpp/LocalRequestHandler.h:35
       0xb658bdf    DB::LocalTunnelSender<false>::push(std::__1::shared_ptr<DB::TrackedMppDataPacket>&&) [tiflash+191204319]
                    dbms/src/Flash/Mpp/MPPTunnel.h:281
       0xb65126c    DB::MPPTunnel::write(std::__1::shared_ptr<DB::TrackedMppDataPacket>&&) [tiflash+191173228]
                    dbms/src/Flash/Mpp/MPPTunnel.cpp:164
       0x3b844d7    DB::MPPTunnelSetBase<DB::MPPTunnel>::broadcastOrPassThroughWrite(std::__1::shared_ptr<DB::TrackedMppDataPacket>&&) [tiflash+62407895]
                    dbms/src/Flash/Mpp/MPPTunnelSet.cpp:65
       0x3b6793a    DB::BroadcastOrPassThroughWriter<std::__1::shared_ptr<DB::MPPTunnelSet> >::encodeThenWriteBlocks() [tiflash+62290234]
                    dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp:78
       0x3b676cf    DB::BroadcastOrPassThroughWriter<std::__1::shared_ptr<DB::MPPTunnelSet> >::write(DB::Block const&) [tiflash+62289615]
                    dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp:58
       0xb5bba68    DB::ExchangeSenderBlockInputStream::readImpl() [tiflash+190560872]
                    dbms/src/DataStreams/ExchangeSenderBlockInputStream.cpp:44
       0xa490530    DB::IProfilingBlockInputStream::read(DB::PODArray<unsigned char, 4096ul, Allocator<false>, 15ul, 16ul>*&, bool) [tiflash+172557616]
                    dbms/src/DataStreams/IProfilingBlockInputStream.cpp:75
       0xa4903c7    DB::IProfilingBlockInputStream::read() [tiflash+172557255]
                    dbms/src/DataStreams/IProfilingBlockInputStream.cpp:43
       0xb676b6d    DB::DataStreamExecutor::execute(DB::ResultHandler) [tiflash+191327085]
                    dbms/src/Flash/Executor/DataStreamExecutor.cpp:28
       0xb678ab6    DB::QueryExecutor::execute() [tiflash+191335094]
                    dbms/src/Flash/Executor/QueryExecutor.cpp:21
       0xb618420    DB::MPPTask::runImpl() [tiflash+190940192]
                    dbms/src/Flash/Mpp/MPPTask.cpp:401
       0xb61cf7d    DB::MPPTask::run()::$_11::operator()() const [tiflash+190959485]
                    dbms/src/Flash/Mpp/MPPTask.cpp:152
       0xb61cf45    decltype(static_cast<DB::MPPTask::run()::$_11&>(fp)()) std::__1::__invoke<DB::MPPTask::run()::$_11&>(DB::MPPTask::run()::$_11&) [tiflash+190959429]
                    /usr/local/bin/../include/c++/v1/type_traits:3918
       0xb61cefd    void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::MPPTask::run()::$_11&>(DB::MPPTask::run()::$_11&) [tiflash+190959357]
                    /usr/local/bin/../include/c++/v1/__functional/invoke.h:61
       0xb61cecd    std::__1::__function::__alloc_func<DB::MPPTask::run()::$_11, std::__1::allocator<DB::MPPTask::run()::$_11>, void ()>::operator()() [tiflash+190959309]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:171
       0xb61bff9    std::__1::__function::__func<DB::MPPTask::run()::$_11, std::__1::allocator<DB::MPPTask::run()::$_11>, void ()>::operator()() [tiflash+190955513]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:345
       0x3d36096    std::__1::__function::__value_func<void ()>::operator()() const [tiflash+64184470]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:498
       0x3d36045    std::__1::function<void ()>::operator()() const [tiflash+64184389]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:1175
       0x3d42b65    decltype(static_cast<std::__1::function<void ()>>(fp)()) std::__1::__invoke_constexpr<std::__1::function<void ()> >(std::__1::function<void ()>&&) [tiflash+64236389]
                    /usr/local/bin/../include/c++/v1/type_traits:3924
       0x3d42b41    decltype(auto) std::__1::__apply_tuple_impl<std::__1::function<void ()>, std::__1::tuple<> >(std::__1::function<void ()>&&, std::__1::tuple<>&&, std::__1::__tuple_indices<>) [tiflash+64236353]
                    /usr/local/bin/../include/c++/v1/tuple:1536
       0x3d42b11    decltype(auto) std::__1::apply<std::__1::function<void ()>, std::__1::tuple<> >(std::__1::function<void ()>&&, std::__1::tuple<>&&) [tiflash+64236305]
                    /usr/local/bin/../include/c++/v1/tuple:1545
       0x3d42aac    auto DB::wrapInvocable<std::__1::function<void ()> >(bool, std::__1::function<void ()>&&)::'lambda'()::operator()() [tiflash+64236204]
                    dbms/src/Common/wrapInvocable.h:36
       0x3d43779    DB::ExecutableTask<auto DB::wrapInvocable<std::__1::function<void ()> >(bool, std::__1::function<void ()>&&)::'lambda'()>::execute() [tiflash+64239481]
                    dbms/src/Common/ExecutableTask.h:52
       0x3d48e6d    DB::DynamicThreadPool::executeTask(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&) [tiflash+64261741]
                    dbms/src/Common/DynamicThreadPool.cpp:101
       0x3d48d33    DB::DynamicThreadPool::dynamicWork(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >) [tiflash+64261427]
                    dbms/src/Common/DynamicThreadPool.cpp:142
       0x3d4d5c0    decltype(*(static_cast<DB::DynamicThreadPool*>(fp0)).*fp(static_cast<std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >>(fp1))) std::__1::__invoke<void (DB::DynamicThreadPool::* const&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >, void>(void (DB::DynamicThreadPool::* const&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&) [tiflash+64280000]
                    /usr/local/bin/../include/c++/v1/type_traits:3859
       0x3d4d4e6    std::__1::invoke_result<void (DB::DynamicThreadPool::* const&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >::type std::__1::invoke<void (DB::DynamicThreadPool::* const&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(void (DB::DynamicThreadPool::* const&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&) [tiflash+64279782]
                    /usr/local/bin/../include/c++/v1/__functional/invoke.h:93
       0x3d4d425    auto std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&)::'lambda'(auto&&...)::operator()<DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(auto&&...) const [tiflash+64279589]
                    dbms/src/Common/ThreadFactory.h:47
       0x3d4d265    decltype(static_cast<void (DB::DynamicThreadPool::*>(fp)(static_cast<DB::DynamicThreadPool*>(fp0), static_cast<std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >>(fp0))) std::__1::__invoke<std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&)::'lambda'(auto&&...), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(void (DB::DynamicThreadPool::*&&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&) [tiflash+64279141]
                    /usr/local/bin/../include/c++/v1/type_traits:3918
       0x3d4d236    void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&)::'lambda'(auto&&...), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >, 2ul, 3ul>(std::__1::tuple<void (DB::DynamicThreadPool::*)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&)::'lambda'(auto&&...), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >&, std::__1::__tuple_indices<2ul, 3ul>) [tiflash+64279094]
                    /usr/local/bin/../include/c++/v1/thread:280
       0x3d4cecb    void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&)::'lambda'(auto&&...), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > > >(void*) [tiflash+64278219]
                    /usr/local/bin/../include/c++/v1/thread:291
  0x7f6bc026aea5    start_thread [libpthread.so.0+32421]"] [source=BaseDaemon] [thread_id=1936]
[2023/01/11 06:36:03.705 +08:00] [ERROR] [BaseDaemon.cpp:376] [########################################] [source=BaseDaemon] [thread_id=1936]
[2023/01/11 06:36:03.705 +08:00] [ERROR] [BaseDaemon.cpp:377] ["(from thread 240) Received signal Segmentation fault(11)."] [source=BaseDaemon] [thread_id=1936]
[2023/01/11 06:36:03.705 +08:00] [ERROR] [BaseDaemon.cpp:405] ["Address: NULL pointer."] [source=BaseDaemon] [thread_id=1936]
[2023/01/11 06:36:03.705 +08:00] [ERROR] [BaseDaemon.cpp:413] ["Access: read."] [source=BaseDaemon] [thread_id=1936]
[2023/01/11 06:36:03.705 +08:00] [ERROR] [BaseDaemon.cpp:425] ["Unknown si_code."] [source=BaseDaemon] [thread_id=1936]
[2023/01/11 06:36:03.819 +08:00] [ERROR] [BaseDaemon.cpp:569] ["
       0xa46472d    faultSignalHandler(int, siginfo_t*, void*) [tiflash+172377901]
                    libs/libdaemon/src/BaseDaemon.cpp:220
  0x7f6bc0272630    <unknown symbol> [libpthread.so.0+63024]
  0x7f6bbfbea721    __strlen_sse2_pminub [libc.so.6+1505057]
       0x3bace65    std::__1::char_traits<char>::length(char const*) [tiflash+62574181]
                    /usr/local/bin/../include/c++/v1/__string:338
       0x3c356b3    fmt::v8::appender fmt::v8::detail::write<char, fmt::v8::appender>(fmt::v8::appender, char const*) [tiflash+63133363]
                    contrib/fmtlib-cmake/../fmtlib/include/fmt/format.h:2147
       0x3c316e8    fmt::v8::appender fmt::v8::detail::default_arg_formatter<char>::operator()<char const*>(char const*) [tiflash+63117032]
                    contrib/fmtlib-cmake/../fmtlib/include/fmt/format.h:2197
       0x3c35aef    char const* fmt::v8::detail::parse_replacement_field<char, void fmt::v8::detail::vformat_to<char>(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<std::__1::conditional<std::is_same<fmt::v8::type_identity<char>::type, char>::value, fmt::v8::appender, std::__1::back_insert_iterator<fmt::v8::detail::buffer<fmt::v8::type_identity<char>::type> > >::type, fmt::v8::type_identity<char>::type> >, fmt::v8::detail::locale_ref)::format_handler&>(char const*, char const*, void fmt::v8::detail::vformat_to<char>(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<std::__1::conditional<std::is_same<fmt::v8::type_identity<char>::type, char>::value, fmt::v8::appender, std::__1::back_insert_iterator<fmt::v8::detail::buffer<fmt::v8::type_identity<char>::type> > >::type, fmt::v8::type_identity<char>::type> >, fmt::v8::detail::locale_ref)::format_handler&) [tiflash+63134447]
                    contrib/fmtlib-cmake/../fmtlib/include/fmt/core.h:2591
       0x3c30e03    void fmt::v8::detail::vformat_to<char>(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<std::__1::conditional<std::is_same<fmt::v8::type_identity<char>::type, char>::value, fmt::v8::appender, std::__1::back_insert_iterator<fmt::v8::detail::buffer<fmt::v8::type_identity<char>::type> > >::type, fmt::v8::type_identity<char>::type> >, fmt::v8::detail::locale_ref) [tiflash+63114755]
                    contrib/fmtlib-cmake/../fmtlib/include/fmt/format.h:2988
       0x3c3075c    std::__1::back_insert_iterator<fmt::v8::basic_memory_buffer<char, 500ul, std::__1::allocator<char> > > fmt::v8::vformat_to<std::__1::back_insert_iterator<fmt::v8::basic_memory_buffer<char, 500ul, std::__1::allocator<char> > >, 0>(std::__1::back_insert_iterator<fmt::v8::basic_memory_buffer<char, 500ul, std::__1::allocator<char> > >, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >) [tiflash+63113052]
                    contrib/fmtlib-cmake/../fmtlib/include/fmt/core.h:3128
       0x3c2e3dd    DB::FmtBuffer& DB::FmtBuffer::fmtAppend<char const*&>(fmt::v8::basic_format_string<char, fmt::v8::type_identity<char const*&>::type>, char const*&) [tiflash+63103965]
                    dbms/src/Common/FmtUtils.h:32
       0x3c2da8a    MemoryTracker::alloc(long, bool) [tiflash+63101578]
                    dbms/src/Common/MemoryTracker.cpp:115
       0xb4b439e    DB::MemTrackerWrapper::alloc(unsigned long) [tiflash+189481886]
                    dbms/src/Flash/Mpp/TrackedMppDataPacket.h:69
       0xb4b4330    DB::MemTrackerWrapper::switchMemTracker(MemoryTracker*) [tiflash+189481776]
                    dbms/src/Flash/Mpp/TrackedMppDataPacket.h:94
       0xb4acefd    DB::TrackedMppDataPacket::switchMemTracker(MemoryTracker*) [tiflash+189452029]
                    dbms/src/Flash/Mpp/TrackedMppDataPacket.h:183
       0xb657d1b    DB::LocalTunnelSender<true>::push(std::__1::shared_ptr<DB::TrackedMppDataPacket>&&) [tiflash+191200539]
                    dbms/src/Flash/Mpp/MPPTunnel.h:279
       0xb65126c    DB::MPPTunnel::write(std::__1::shared_ptr<DB::TrackedMppDataPacket>&&) [tiflash+191173228]
                    dbms/src/Flash/Mpp/MPPTunnel.cpp:164
       0x3b84abc    DB::MPPTunnelSetBase<DB::MPPTunnel>::sendExecutionSummary(tipb::SelectResponse const&) [tiflash+62409404]
                    dbms/src/Flash/Mpp/MPPTunnelSet.cpp:47
       0xb6140fc    DB::MPPTask::finishWrite() [tiflash+190923004]
                    dbms/src/Flash/Mpp/MPPTask.cpp:145
       0xb618453    DB::MPPTask::runImpl() [tiflash+190940243]
                    dbms/src/Flash/Mpp/MPPTask.cpp:407
       0xb61cf7d    DB::MPPTask::run()::$_11::operator()() const [tiflash+190959485]
                    dbms/src/Flash/Mpp/MPPTask.cpp:152
       0xb61cf45    decltype(static_cast<DB::MPPTask::run()::$_11&>(fp)()) std::__1::__invoke<DB::MPPTask::run()::$_11&>(DB::MPPTask::run()::$_11&) [tiflash+190959429]
                    /usr/local/bin/../include/c++/v1/type_traits:3918
       0xb61cefd    void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::MPPTask::run()::$_11&>(DB::MPPTask::run()::$_11&) [tiflash+190959357]
                    /usr/local/bin/../include/c++/v1/__functional/invoke.h:61
       0xb61cecd    std::__1::__function::__alloc_func<DB::MPPTask::run()::$_11, std::__1::allocator<DB::MPPTask::run()::$_11>, void ()>::operator()() [tiflash+190959309]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:171
       0xb61bff9    std::__1::__function::__func<DB::MPPTask::run()::$_11, std::__1::allocator<DB::MPPTask::run()::$_11>, void ()>::operator()() [tiflash+190955513]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:345
       0x3d36096    std::__1::__function::__value_func<void ()>::operator()() const [tiflash+64184470]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:498
       0x3d36045    std::__1::function<void ()>::operator()() const [tiflash+64184389]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:1175
       0x3d42b65    decltype(static_cast<std::__1::function<void ()>>(fp)()) std::__1::__invoke_constexpr<std::__1::function<void ()> >(std::__1::function<void ()>&&) [tiflash+64236389]
                    /usr/local/bin/../include/c++/v1/type_traits:3924
       0x3d42b41    decltype(auto) std::__1::__apply_tuple_impl<std::__1::function<void ()>, std::__1::tuple<> >(std::__1::function<void ()>&&, std::__1::tuple<>&&, std::__1::__tuple_indices<>) [tiflash+64236353]
                    /usr/local/bin/../include/c++/v1/tuple:1536
       0x3d42b11    decltype(auto) std::__1::apply<std::__1::function<void ()>, std::__1::tuple<> >(std::__1::function<void ()>&&, std::__1::tuple<>&&) [tiflash+64236305]
                    /usr/local/bin/../include/c++/v1/tuple:1545
       0x3d42aac    auto DB::wrapInvocable<std::__1::function<void ()> >(bool, std::__1::function<void ()>&&)::'lambda'()::operator()() [tiflash+64236204]
                    dbms/src/Common/wrapInvocable.h:36
       0x3d43779    DB::ExecutableTask<auto DB::wrapInvocable<std::__1::function<void ()> >(bool, std::__1::function<void ()>&&)::'lambda'()>::execute() [tiflash+64239481]
                    dbms/src/Common/ExecutableTask.h:52
       0x3d48e6d    DB::DynamicThreadPool::executeTask(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&) [tiflash+64261741]
                    dbms/src/Common/DynamicThreadPool.cpp:101
       0x3d486bf    DB::DynamicThreadPool::fixedWork(unsigned long) [tiflash+64259775]
                    dbms/src/Common/DynamicThreadPool.cpp:115
       0x3d4bd1c    decltype(*(static_cast<DB::DynamicThreadPool*>(fp0)).*fp(static_cast<unsigned long&>(fp1))) std::__1::__invoke<void (DB::DynamicThreadPool::* const&)(unsigned long), DB::DynamicThreadPool*, unsigned long&, void>(void (DB::DynamicThreadPool::* const&)(unsigned long), DB::DynamicThreadPool*&&, unsigned long&) [tiflash+64273692]
                    /usr/local/bin/../include/c++/v1/type_traits:3859
       0x3d4bc56    std::__1::invoke_result<void (DB::DynamicThreadPool::* const&)(unsigned long), DB::DynamicThreadPool*, unsigned long&>::type std::__1::invoke<void (DB::DynamicThreadPool::* const&)(unsigned long), DB::DynamicThreadPool*, unsigned long&>(void (DB::DynamicThreadPool::* const&)(unsigned long), DB::DynamicThreadPool*&&, unsigned long&) [tiflash+64273494]
                    /usr/local/bin/../include/c++/v1/__functional/invoke.h:93
       0x3d4bb95    auto std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(unsigned long), DB::DynamicThreadPool*, unsigned long&>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(unsigned long), DB::DynamicThreadPool*&&, unsigned long&)::'lambda'(auto&&...)::operator()<DB::DynamicThreadPool*, unsigned long>(auto&&...) const [tiflash+64273301]
                    dbms/src/Common/ThreadFactory.h:47
       0x3d4b9c5    decltype(static_cast<void (DB::DynamicThreadPool::*>(fp)(static_cast<DB::DynamicThreadPool*>(fp0), static_cast<unsigned long&>(fp0))) std::__1::__invoke<std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(unsigned long), DB::DynamicThreadPool*, unsigned long&>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(unsigned long), DB::DynamicThreadPool*&&, unsigned long&)::'lambda'(auto&&...), DB::DynamicThreadPool*, unsigned long>(void (DB::DynamicThreadPool::*&&)(unsigned long), DB::DynamicThreadPool*&&, unsigned long&) [tiflash+64272837]
                    /usr/local/bin/../include/c++/v1/type_traits:3918
       0x3d4b996    void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(unsigned long), DB::DynamicThreadPool*, unsigned long&>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(unsigned long), DB::DynamicThreadPool*&&, unsigned long&)::'lambda'(auto&&...), DB::DynamicThreadPool*, unsigned long, 2ul, 3ul>(std::__1::tuple<void (DB::DynamicThreadPool::*)(unsigned long), std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(unsigned long), DB::DynamicThreadPool*, unsigned long&>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(unsigned long), DB::DynamicThreadPool*&&, unsigned long&)::'lambda'(auto&&...), DB::DynamicThreadPool*, unsigned long>&, std::__1::__tuple_indices<2ul, 3ul>) [tiflash+64272790]
                    /usr/local/bin/../include/c++/v1/thread:280
       0x3d4b5fb    void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(unsigned long), DB::DynamicThreadPool*, unsigned long&>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(unsigned long), DB::DynamicThreadPool*&&, unsigned long&)::'lambda'(auto&&...), DB::DynamicThreadPool*, unsigned long> >(void*) [tiflash+64271867]
                    /usr/local/bin/../include/c++/v1/thread:291
  0x7f6bc026aea5    start_thread [libpthread.so.0+32421]"] [source=BaseDaemon] [thread_id=1936]
[2023/01/11 07:04:46.996 +08:00] [ERROR] [BaseDaemon.cpp:376] [########################################] [source=BaseDaemon] [thread_id=2429]
[2023/01/11 07:04:46.996 +08:00] [ERROR] [BaseDaemon.cpp:377] ["(from thread 2181) Received signal Segmentation fault(11)."] [source=BaseDaemon] [thread_id=2429]
[2023/01/11 07:04:46.996 +08:00] [ERROR] [BaseDaemon.cpp:405] ["Address: NULL pointer."] [source=BaseDaemon] [thread_id=2429]
[2023/01/11 07:04:46.996 +08:00] [ERROR] [BaseDaemon.cpp:413] ["Access: read."] [source=BaseDaemon] [thread_id=2429]
[2023/01/11 07:04:46.996 +08:00] [ERROR] [BaseDaemon.cpp:425] ["Unknown si_code."] [source=BaseDaemon] [thread_id=2429]
[2023/01/11 07:04:47.398 +08:00] [ERROR] [BaseDaemon.cpp:569] ["
       0xa46472d    faultSignalHandler(int, siginfo_t*, void*) [tiflash+172377901]
                    libs/libdaemon/src/BaseDaemon.cpp:220
  0x7f3a6b67a630    <unknown symbol> [libpthread.so.0+63024]
  0x7f3a6aff2721    __strlen_sse2_pminub [libc.so.6+1505057]
       0x3bace65    std::__1::char_traits<char>::length(char const*) [tiflash+62574181]
                    /usr/local/bin/../include/c++/v1/__string:338
       0x3c356b3    fmt::v8::appender fmt::v8::detail::write<char, fmt::v8::appender>(fmt::v8::appender, char const*) [tiflash+63133363]
                    contrib/fmtlib-cmake/../fmtlib/include/fmt/format.h:2147
       0x3c316e8    fmt::v8::appender fmt::v8::detail::default_arg_formatter<char>::operator()<char const*>(char const*) [tiflash+63117032]
                    contrib/fmtlib-cmake/../fmtlib/include/fmt/format.h:2197
       0x3c35aef    char const* fmt::v8::detail::parse_replacement_field<char, void fmt::v8::detail::vformat_to<char>(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<std::__1::conditional<std::is_same<fmt::v8::type_identity<char>::type, char>::value, fmt::v8::appender, std::__1::back_insert_iterator<fmt::v8::detail::buffer<fmt::v8::type_identity<char>::type> > >::type, fmt::v8::type_identity<char>::type> >, fmt::v8::detail::locale_ref)::format_handler&>(char const*, char const*, void fmt::v8::detail::vformat_to<char>(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<std::__1::conditional<std::is_same<fmt::v8::type_identity<char>::type, char>::value, fmt::v8::appender, std::__1::back_insert_iterator<fmt::v8::detail::buffer<fmt::v8::type_identity<char>::type> > >::type, fmt::v8::type_identity<char>::type> >, fmt::v8::detail::locale_ref)::format_handler&) [tiflash+63134447]
                    contrib/fmtlib-cmake/../fmtlib/include/fmt/core.h:2591
       0x3c30e03    void fmt::v8::detail::vformat_to<char>(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<std::__1::conditional<std::is_same<fmt::v8::type_identity<char>::type, char>::value, fmt::v8::appender, std::__1::back_insert_iterator<fmt::v8::detail::buffer<fmt::v8::type_identity<char>::type> > >::type, fmt::v8::type_identity<char>::type> >, fmt::v8::detail::locale_ref) [tiflash+63114755]
                    contrib/fmtlib-cmake/../fmtlib/include/fmt/format.h:2988
       0x3c3075c    std::__1::back_insert_iterator<fmt::v8::basic_memory_buffer<char, 500ul, std::__1::allocator<char> > > fmt::v8::vformat_to<std::__1::back_insert_iterator<fmt::v8::basic_memory_buffer<char, 500ul, std::__1::allocator<char> > >, 0>(std::__1::back_insert_iterator<fmt::v8::basic_memory_buffer<char, 500ul, std::__1::allocator<char> > >, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >) [tiflash+63113052]
                    contrib/fmtlib-cmake/../fmtlib/include/fmt/core.h:3128
       0x3c2e3dd    DB::FmtBuffer& DB::FmtBuffer::fmtAppend<char const*&>(fmt::v8::basic_format_string<char, fmt::v8::type_identity<char const*&>::type>, char const*&) [tiflash+63103965]
                    dbms/src/Common/FmtUtils.h:32
       0x3c2da8a    MemoryTracker::alloc(long, bool) [tiflash+63101578]
                    dbms/src/Common/MemoryTracker.cpp:115
       0xb4b439e    DB::MemTrackerWrapper::alloc(unsigned long) [tiflash+189481886]
                    dbms/src/Flash/Mpp/TrackedMppDataPacket.h:69
       0xb4b4330    DB::MemTrackerWrapper::switchMemTracker(MemoryTracker*) [tiflash+189481776]
                    dbms/src/Flash/Mpp/TrackedMppDataPacket.h:94
       0xb4acefd    DB::TrackedMppDataPacket::switchMemTracker(MemoryTracker*) [tiflash+189452029]
                    dbms/src/Flash/Mpp/TrackedMppDataPacket.h:183
       0xb658bcb    DB::LocalTunnelSender<false>::push(std::__1::shared_ptr<DB::TrackedMppDataPacket>&&) [tiflash+191204299]
                    dbms/src/Flash/Mpp/MPPTunnel.h:279
       0xb65126c    DB::MPPTunnel::write(std::__1::shared_ptr<DB::TrackedMppDataPacket>&&) [tiflash+191173228]
                    dbms/src/Flash/Mpp/MPPTunnel.cpp:164
       0x3b84976    DB::MPPTunnelSetBase<DB::MPPTunnel>::partitionWrite(std::__1::shared_ptr<DB::TrackedMppDataPacket>&&, short) [tiflash+62409078]
                    dbms/src/Flash/Mpp/MPPTunnelSet.cpp:73
       0x3b83bc4    DB::HashPartitionWriter<std::__1::shared_ptr<DB::MPPTunnelSet> >::writePackets(std::__1::vector<std::__1::shared_ptr<DB::TrackedMppDataPacket>, std::__1::allocator<std::__1::shared_ptr<DB::TrackedMppDataPacket> > >&) [tiflash+62405572]
                    dbms/src/Flash/Mpp/HashPartitionWriter.cpp:115
       0x3b83ac5    DB::HashPartitionWriter<std::__1::shared_ptr<DB::MPPTunnelSet> >::partitionAndEncodeThenWriteBlocks() [tiflash+62405317]
                    dbms/src/Flash/Mpp/HashPartitionWriter.cpp:104
       0x3b836af    DB::HashPartitionWriter<std::__1::shared_ptr<DB::MPPTunnelSet> >::write(DB::Block const&) [tiflash+62404271]
                    dbms/src/Flash/Mpp/HashPartitionWriter.cpp:65
       0xb5bba68    DB::ExchangeSenderBlockInputStream::readImpl() [tiflash+190560872]
                    dbms/src/DataStreams/ExchangeSenderBlockInputStream.cpp:44
       0xa490530    DB::IProfilingBlockInputStream::read(DB::PODArray<unsigned char, 4096ul, Allocator<false>, 15ul, 16ul>*&, bool) [tiflash+172557616]
                    dbms/src/DataStreams/IProfilingBlockInputStream.cpp:75
       0xa4903c7    DB::IProfilingBlockInputStream::read() [tiflash+172557255]
                    dbms/src/DataStreams/IProfilingBlockInputStream.cpp:43
       0xb676b6d    DB::DataStreamExecutor::execute(DB::ResultHandler) [tiflash+191327085]
                    dbms/src/Flash/Executor/DataStreamExecutor.cpp:28
       0xb678ab6    DB::QueryExecutor::execute() [tiflash+191335094]
                    dbms/src/Flash/Executor/QueryExecutor.cpp:21
       0xb618420    DB::MPPTask::runImpl() [tiflash+190940192]
                    dbms/src/Flash/Mpp/MPPTask.cpp:401
       0xb61cf7d    DB::MPPTask::run()::$_11::operator()() const [tiflash+190959485]
                    dbms/src/Flash/Mpp/MPPTask.cpp:152
       0xb61cf45    decltype(static_cast<DB::MPPTask::run()::$_11&>(fp)()) std::__1::__invoke<DB::MPPTask::run()::$_11&>(DB::MPPTask::run()::$_11&) [tiflash+190959429]
                    /usr/local/bin/../include/c++/v1/type_traits:3918
       0xb61cefd    void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::MPPTask::run()::$_11&>(DB::MPPTask::run()::$_11&) [tiflash+190959357]
                    /usr/local/bin/../include/c++/v1/__functional/invoke.h:61
       0xb61cecd    std::__1::__function::__alloc_func<DB::MPPTask::run()::$_11, std::__1::allocator<DB::MPPTask::run()::$_11>, void ()>::operator()() [tiflash+190959309]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:171
       0xb61bff9    std::__1::__function::__func<DB::MPPTask::run()::$_11, std::__1::allocator<DB::MPPTask::run()::$_11>, void ()>::operator()() [tiflash+190955513]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:345
       0x3d36096    std::__1::__function::__value_func<void ()>::operator()() const [tiflash+64184470]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:498
       0x3d36045    std::__1::function<void ()>::operator()() const [tiflash+64184389]
                    /usr/local/bin/../include/c++/v1/__functional/function.h:1175
       0x3d42b65    decltype(static_cast<std::__1::function<void ()>>(fp)()) std::__1::__invoke_constexpr<std::__1::function<void ()> >(std::__1::function<void ()>&&) [tiflash+64236389]
                    /usr/local/bin/../include/c++/v1/type_traits:3924
       0x3d42b41    decltype(auto) std::__1::__apply_tuple_impl<std::__1::function<void ()>, std::__1::tuple<> >(std::__1::function<void ()>&&, std::__1::tuple<>&&, std::__1::__tuple_indices<>) [tiflash+64236353]
                    /usr/local/bin/../include/c++/v1/tuple:1536
       0x3d42b11    decltype(auto) std::__1::apply<std::__1::function<void ()>, std::__1::tuple<> >(std::__1::function<void ()>&&, std::__1::tuple<>&&) [tiflash+64236305]
                    /usr/local/bin/../include/c++/v1/tuple:1545
       0x3d42aac    auto DB::wrapInvocable<std::__1::function<void ()> >(bool, std::__1::function<void ()>&&)::'lambda'()::operator()() [tiflash+64236204]
                    dbms/src/Common/wrapInvocable.h:36
       0x3d43779    DB::ExecutableTask<auto DB::wrapInvocable<std::__1::function<void ()> >(bool, std::__1::function<void ()>&&)::'lambda'()>::execute() [tiflash+64239481]
                    dbms/src/Common/ExecutableTask.h:52
       0x3d48e6d    DB::DynamicThreadPool::executeTask(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&) [tiflash+64261741]
                    dbms/src/Common/DynamicThreadPool.cpp:101
       0x3d48d33    DB::DynamicThreadPool::dynamicWork(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >) [tiflash+64261427]
                    dbms/src/Common/DynamicThreadPool.cpp:142
       0x3d4d5c0    decltype(*(static_cast<DB::DynamicThreadPool*>(fp0)).*fp(static_cast<std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >>(fp1))) std::__1::__invoke<void (DB::DynamicThreadPool::* const&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >, void>(void (DB::DynamicThreadPool::* const&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&) [tiflash+64280000]
                    /usr/local/bin/../include/c++/v1/type_traits:3859
       0x3d4d4e6    std::__1::invoke_result<void (DB::DynamicThreadPool::* const&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >::type std::__1::invoke<void (DB::DynamicThreadPool::* const&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(void (DB::DynamicThreadPool::* const&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&) [tiflash+64279782]
                    /usr/local/bin/../include/c++/v1/__functional/invoke.h:93
       0x3d4d425    auto std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&)::'lambda'(auto&&...)::operator()<DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(auto&&...) const [tiflash+64279589]
                    dbms/src/Common/ThreadFactory.h:47
       0x3d4d265    decltype(static_cast<void (DB::DynamicThreadPool::*>(fp)(static_cast<DB::DynamicThreadPool*>(fp0), static_cast<std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >>(fp0))) std::__1::__invoke<std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&)::'lambda'(auto&&...), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(void (DB::DynamicThreadPool::*&&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&) [tiflash+64279141]
                    /usr/local/bin/../include/c++/v1/type_traits:3918
       0x3d4d236    void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&)::'lambda'(auto&&...), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >, 2ul, 3ul>(std::__1::tuple<void (DB::DynamicThreadPool::*)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&)::'lambda'(auto&&...), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >&, std::__1::__tuple_indices<2ul, 3ul>) [tiflash+64279094]
                    /usr/local/bin/../include/c++/v1/thread:280
       0x3d4cecb    void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > >(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >), DB::DynamicThreadPool*&&, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&&)::'lambda'(auto&&...), DB::DynamicThreadPool*, std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> > > >(void*) [tiflash+64278219]
                    /usr/local/bin/../include/c++/v1/thread:291
  0x7f3a6b672ea5    start_thread [libpthread.so.0+32421]"] [source=BaseDaemon] [thread_id=2429]
```
### 4. What is your TiFlash version? (Required)
[2023/01/11 06:26:44.006 +08:00] [INFO] [client.go:487] ["Cluster version information"] [type=tiflash] [version=6.6.0-alpha] [git_hash=f9167f36641360530425459c2e0e0b4ad4750841]

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #6615 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp [hunk 1]
```diff
@@ -347,15 +347,18 @@ ExchangeReceiverBase<RPCContext>::ExchangeReceiverBase(
 template <typename RPCContext>
 ExchangeReceiverBase<RPCContext>::~ExchangeReceiverBase()
 {
+    bool wait_connection_done = false;
     try
     {
         close();
         waitAllConnectionDone();
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/ExchangeReceiver.cpp:354]: just `ExchangeReceiverBase<RPCContext>::close() noexcept` and `ExchangeReceiverBase<RPCContext>::waitAllConnectionDone() noexcept` is ok.

Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/ExchangeReceiver.cpp:354]: > just `ExchangeReceiverBase<RPCContext>::close() noexcept` and `ExchangeReceiverBase<RPCContext>::waitAllConnectionDone() noexcept` is ok.

okk

File: dbms/src/Flash/Mpp/MPPTunnel.h [hunk 2]
```diff
@@ -279,9 +282,6 @@ class LocalTunnelSender : public TunnelSender
         data->switchMemTracker(local_request_handler.recv_mem_tracker);
 
         auto res = local_request_handler.write<enable_fine_grained_shuffle>(source_index, data);
-
-        if (unlikely(!res))
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/MPPTunnel.h:283]: why remove here?

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp [hunk 3]
```diff
@@ -734,35 +734,37 @@ void ExchangeReceiverBase<RPCContext>::connectionDone(
     const String & local_err_msg,
     const LoggerPtr & log)
 {
-    Int32 copy_live_conn = -1;
+    // The whole function should be protected by the lock,
+    // because once live_connections is equal to 0, waitAllConnectionDone
+    // function will return and the ExchangeReceiver may be destructed
+    // before we leave this function.
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Mpp/ExchangeReceiver.cpp:740]: Won't `thread_manager->wait();` blocks until `connectionDone` exits?

https://github.com/pingcap/tiflash/blob/70ea5e611e2b0e3672ca589006970b0b82621e90/dbms/src/Flash/Mpp/ExchangeReceiver.cpp#L347-L354

Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/ExchangeReceiver.cpp:740]: > Won't `thread_manager->wait();` blocks until `connectionDone` exits?
> 
> https://github.com/pingcap/tiflash/blob/70ea5e611e2b0e3672ca589006970b0b82621e90/dbms/src/Flash/Mpp/ExchangeReceiver.cpp#L347-L354

No, new thread that reads data for local tunnel is no more need after this [pr](https://github.com/pingcap/tiflash/pull/6463)

File: dbms/src/Flash/Mpp/MPPTunnel.h (hunk 2 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/MPPTunnel.h:283]: > why remove here?

I think `push` should not be involved in the status management. Because returning false will trigger the throwing of exception, then MppTask will cancel the tunnel which then call the connectionDone function.

Comment (SeaRise) [reply dbms/src/Flash/Mpp/MPPTunnel.h:283]: ok

File: dbms/src/Flash/Mpp/MPPTunnel.h [hunk 4]
```diff
@@ -279,9 +282,6 @@ class LocalTunnelSender : public TunnelSender
         data->switchMemTracker(local_request_handler.recv_mem_tracker);
 
         auto res = local_request_handler.write<enable_fine_grained_shuffle>(source_index, data);
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/MPPTunnel.h:284]:
```suggestion
        return local_request_handler.write<enable_fine_grained_shuffle>(source_index, data);
```

**Review by SeaRise — APPROVED** [review]
Others LGTM

File: dbms/src/Flash/Mpp/MPPTunnel.h [hunk 5]
```diff
@@ -270,6 +270,10 @@ class LocalTunnelSender : public TunnelSender
 
     bool push(TrackedMppDataPacketPtr && data) override
     {
+        std::lock_guard lock(mu);
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/MPPTunnel.h:273]: I am concerned that this may cause performance problems here.
Maybe we can move the `isDone` to `local_request_handler`?

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp [hunk 6]
```diff
@@ -347,21 +347,24 @@ ExchangeReceiverBase<RPCContext>::ExchangeReceiverBase(
...
     {
         close();
         waitAllConnectionDone();
+        wait_all_connection_done = true;
         thread_manager->wait();
         ExchangeReceiverMetric::clearDataSizeMetric(data_size_in_queue);
     }
     catch (...)
     {
+        RUNTIME_ASSERT(wait_all_connection_done, "We should wait the close of all connections");
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/ExchangeReceiver.cpp:361]: Or
```
{
    std::lock_guard lock(mu);
    RUNTIME_ASSERT(live_connections == 0, "We should wait the close of all connections");
}
```
here?

Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/ExchangeReceiver.cpp:361]: > Or
> 
> ```
> {
>     std::lock_guard lock(mu);
>     RUNTIME_ASSERT(live_connections == 0, "We should wait the close of all connections");
> }
> ```
> 
> here?

okk

File: dbms/src/Flash/Mpp/MPPTunnel.h (hunk 5 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/MPPTunnel.h]: > I am concerned that this may cause performance problems here. Maybe we can move the `isDone` to `local_request_handler`?

I think that moving `isDone` to `local_request_handler` is still unsafe. As to performance, I will investigate it.

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp [hunk 7]
```diff
@@ -453,6 +509,8 @@ void ExchangeReceiverBase<RPCContext>::reactor(const std::vector<Request> & asyn
 {
     using AsyncHandler = AsyncRequestHandler<RPCContext, enable_fine_grained_shuffle>;
 
+    addAsyncConnectionNum();
```
Comment (windtalker) [inline dbms/src/Flash/Mpp/ExchangeReceiver.cpp:512]: only add `live_connections` by one here?

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp [hunk 8]
```diff
@@ -734,38 +794,49 @@ void ExchangeReceiverBase<RPCContext>::connectionDone(
     const String & local_err_msg,
     const LoggerPtr & log)
 {
-    Int32 copy_live_conn = -1;
+    // The whole function should be protected by the lock,
```
Comment (windtalker) [inline dbms/src/Flash/Mpp/ExchangeReceiver.cpp:797]: Is this change still needed?

File: dbms/src/Flash/Mpp/MPPTunnel.h [hunk 9]
```diff
@@ -301,25 +303,37 @@ class LocalTunnelSender : public TunnelSender
...
         bool expect = false;
         if (is_done.compare_exchange_strong(expect, true))
         {
             consumer_state.setMsg(local_err_msg);
-            local_request_handler.connectionLocalDone(meet_error, local_err_msg);
+            local_request_handler.prepareToCloseLocalConnection(meet_error, local_err_msg);
         }
     }
 
+    // It should only be called in the destructor.
```
Comment (windtalker) [inline dbms/src/Flash/Mpp/MPPTunnel.h:324]: If it is only called in the destructor, why not just call `local_request_handler.closeLocalConnection();` in the destructor?

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp (hunk 8 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/ExchangeReceiver.cpp:797]: > Is this change still needed?

yes

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp (hunk 7 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/ExchangeReceiver.cpp:512]: > only add `live_connections` by one here?

I will fix this

File: dbms/src/Flash/Mpp/MPPTunnel.h (hunk 9 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/MPPTunnel.h:324]: > If it is only called in the destructor, why not just call `local_request_handler.closeLocalConnection();` in the destructor?

Local tunnel may push to a full queue, and may be blocked, so we need to close the channel in advande otherwise the push is blocked and `closeLocalConnection` is never called.

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp [hunk 10]
```diff
@@ -347,15 +350,18 @@ ExchangeReceiverBase<RPCContext>::ExchangeReceiverBase(
...
     {
         close();
         waitAllConnectionDone();
+        wait_all_connection_done = true;
         thread_manager->wait();
         ExchangeReceiverMetric::clearDataSizeMetric(data_size_in_queue);
     }
     catch (...)
     {
+        RUNTIME_ASSERT(wait_all_connection_done, "We should wait the close of all connections");
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/ExchangeReceiver.cpp:364]: So you prefer `assert(wait_all_connection_done)` over `assert(live_connections == 0)` here?

File: dbms/src/Flash/Mpp/LocalRequestHandler.h [hunk 11]
```diff
@@ -35,13 +37,19 @@ struct LocalRequestHandler
         return channel_writer.write<enable_fine_grained_shuffle>(source_index, tracked_packet);
     }
 
-    void connectionLocalDone(bool meet_error, const String & local_err_msg) const
+    void prepareToCloseLocalConnection(bool meet_error, const String & local_err_msg) const
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/LocalRequestHandler.h:40]: I perfer to `writeDone`..

File: dbms/src/Flash/Mpp/LocalRequestHandler.h [hunk 12]
```diff
@@ -35,13 +37,19 @@ struct LocalRequestHandler
...
+    }
+
+    void closeLocalConnection() const
+    {
+        notify_receiver_close();
     }
 
     MemoryTracker * recv_mem_tracker;
-    std::function<void(bool, const String &)> notify_receiver;
+    std::function<void(bool, const String &)> notify_receiver_prepare;
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/LocalRequestHandler.h:51]:
```suggestion
    std::function<void(bool, const String &)> notify_write_done;
```

File: dbms/src/Flash/Mpp/LocalRequestHandler.h [hunk 13]
```diff
@@ -35,13 +37,19 @@ struct LocalRequestHandler
...
+    std::function<void()> notify_receiver_close;
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/LocalRequestHandler.h:52]:
```suggestion
    std::function<void()> notify_close;
```

File: dbms/src/Flash/Mpp/LocalRequestHandler.h [hunk 14]
```diff
@@ -35,13 +37,19 @@ struct LocalRequestHandler
...
     }
 
-    void connectionLocalDone(bool meet_error, const String & local_err_msg) const
+    void prepareToCloseLocalConnection(bool meet_error, const String & local_err_msg) const
     {
-        notify_receiver(meet_error, local_err_msg);
+        notify_receiver_prepare(meet_error, local_err_msg);
+    }
+
+    void closeLocalConnection() const
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/LocalRequestHandler.h:45]:
```suggestion
    void closeConnection() const
```

Comment (SeaRise) [reply dbms/src/Flash/Mpp/LocalRequestHandler.h:45]: Beacause this class is `"Local"RequestHandler`

File: dbms/src/Flash/Mpp/MPPTunnel.h [hunk 15]
```diff
@@ -256,16 +258,20 @@ class LocalTunnelSender : public TunnelSender
...
-        const String & tunnel_id_)
+        const String & tunnel_id_,
+        std::function<void()> && add_local_conn_num)
         : TunnelSender(memory_tracker_, log_, tunnel_id_, nullptr)
         , source_index(source_index_)
         , local_request_handler(local_request_handler_)
         , is_done(false)
-    {}
+    {
+        add_local_conn_num();
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/MPPTunnel.h:268]: how about `connect`

File: dbms/src/Flash/Mpp/ExchangeReceiver.h [hunk 16]
```diff
@@ -184,6 +190,7 @@ class ExchangeReceiverBase
     std::condition_variable cv;
     /// should lock `mu` when visit these members
     Int32 live_connections;
+    Int32 live_local_connections;
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/ExchangeReceiver.h:193]: Because there will only be one local tunnel, it can be replaced with `bool is_local_connectoin_alive = false`.

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp (hunk 10 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/ExchangeReceiver.cpp:364]: > So you prefer `assert(wait_all_connection_done)` over `assert(live_connections == 0)` here?

I forget to change this.

File: dbms/src/Flash/Mpp/MPPTunnel.h (hunk 15 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/MPPTunnel.h:268]: > how about `connect`

The purpose of this function is to modify the variable in `ExchangeReceiver`. I think the name `connect` can't show this purpose.

File: dbms/src/Flash/Mpp/ExchangeReceiver.h (hunk 16 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/ExchangeReceiver.h:193]: > 

I think that counting number of local tunnels could handle more situation because maybe more local tunnels will be created in the furture.

File: dbms/src/Flash/Mpp/LocalRequestHandler.h (hunk 11 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/LocalRequestHandler.h:40]: > I perfer to `writeDone`..

okk

File: dbms/src/Flash/Mpp/ExchangeReceiver.h (hunk 16 above)
Comment (SeaRise) [reply dbms/src/Flash/Mpp/ExchangeReceiver.h:193]: It is only a bug if there is more than one local tunnel.
Because these source tasks that executed on the same machine can be combine into one.

Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/ExchangeReceiver.h:193]: > It is only a bug if there is more than one local tunnel. Because these source tasks that executed on the same machine can be combine into one.

okk, I will fix it

File: dbms/src/Flash/Mpp/MPPTunnel.h (hunk 9 above)
Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTunnel.h:326]: Oh, what I wants to say is that since `closeLocalConnection` can only be called in the destructor, and this function itself is very simple, then why need to add `closeLocalConnection` as a new function, we can just call `local_request_handler.closeConnection();` in the destructor.

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp [hunk 17]
```diff
@@ -766,6 +824,14 @@ void ExchangeReceiverBase<RPCContext>::connectionDone(
         finishAllMsgChannels();
 }
 
+template <typename RPCContext>
+void ExchangeReceiverBase<RPCContext>::connectionLocalDone()
+{
+    std::lock_guard lock(mu);
+    is_local_conn_alive = false;
```
Comment (windtalker) [inline dbms/src/Flash/Mpp/ExchangeReceiver.cpp:831]: I think we need to consider that in the furture, there may be more than 1 local tunnel in one ExchangeReceiver

File: dbms/src/Flash/Mpp/MPPTunnel.h [hunk 18]
```diff
@@ -278,48 +284,58 @@ class LocalTunnelSender : public TunnelSender
...
 
 private:
+    friend class tests::TestMPPTunnel;
+
     bool checkPacketErr(TrackedMppDataPacketPtr & packet)
     {
         if (packet->hasError())
         {
-            closeLocalTunnel(true, packet->error());
+            prepareToCloseLocalTunnel(true, packet->error());
```
Comment (windtalker) [inline dbms/src/Flash/Mpp/MPPTunnel.h:308]: How about rename `prepareToCloseLocalTunnel` to `finishWrite`, which means the local tunnel will guarantee that no more call to `local_request_handler.write` after `finishWrite` is called?

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp (hunk 17 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/ExchangeReceiver.cpp:831]: > I think we need to consider that in the furture, there may be more than 1 local tunnel in one ExchangeReceiver

ok, I will fix it.

File: dbms/src/Flash/Mpp/MPPTunnel.h (hunk 18 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/MPPTunnel.h:308]: > How about rename `prepareToCloseLocalTunnel` to `finishWrite`, which means the local tunnel will guarantee that no more call to `local_request_handler.write` after `finishWrite` is called?

okk

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp (hunk 17 above)
Comment (windtalker) [reply dbms/src/Flash/Mpp/ExchangeReceiver.cpp:831]: Never mind, it is reasonable to assume that for each exchange receiver, only here is only one local tunnel.

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp [hunk 19]
```diff
@@ -356,6 +359,7 @@ ExchangeReceiverBase<RPCContext>::~ExchangeReceiverBase()
     }
     catch (...)
     {
+        RUNTIME_ASSERT(live_connections == 0, "We should wait the close of all connections");
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/ExchangeReceiver.cpp:362]:
```suggestion
        std::lock_guard lock(mu);
        RUNTIME_ASSERT(live_connections == 0, "We should wait the close of all connections");
        RUNTIME_ASSERT(!is_local_conn_alive, "We should wait the close of local connection");
```

File: dbms/src/Flash/Mpp/MPPTunnel.h [hunk 20]
```diff
@@ -256,16 +258,28 @@ class LocalTunnelSender : public TunnelSender
...
         : TunnelSender(memory_tracker_, log_, tunnel_id_, nullptr)
         , source_index(source_index_)
         , local_request_handler(local_request_handler_)
         , is_done(false)
-    {}
+    {
+        // Do not change the order of these two clause as setAlive may throw Exception.
+        // When Exception is throwed, live_connection should not be added.
+        local_request_handler.setAlive();
+        add_local_conn_num();
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/MPPTunnel.h:271]: combine into `local_request_handler.setAlive()`.

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp [hunk 21]
```diff
@@ -766,6 +826,22 @@ void ExchangeReceiverBase<RPCContext>::connectionDone(
...
+    std::lock_guard lock(mu);
+    is_local_conn_alive = false;
+    cv.notify_all();
+}
+
+template <typename RPCContext>
+void ExchangeReceiverBase<RPCContext>::setLocalAlive()
+{
+    std::lock_guard lock(mu);
+    RUNTIME_CHECK_MSG(!is_local_conn_alive, "is_local_conn_alive should only be set once");
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/ExchangeReceiver.cpp:841]:
```suggestion
    RUNTIME_ASSERT(!is_local_conn_alive, "is_local_conn_alive should only be set once");
```
Because we have no way to recover here.

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp [hunk 22]
```diff
@@ -766,6 +826,22 @@ void ExchangeReceiverBase<RPCContext>::connectionDone(
         finishAllMsgChannels();
 }
 
+template <typename RPCContext>
+void ExchangeReceiverBase<RPCContext>::connectionLocalDone()
+{
+    std::lock_guard lock(mu);
+    is_local_conn_alive = false;
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/ExchangeReceiver.cpp:833]:
```suggestion
    RUNTIME_ASSERT(is_local_conn_alive, "XXXXX");
    is_local_conn_alive = false;
```

File: dbms/src/Flash/Mpp/MPPTunnel.h [hunk 23]
```diff
@@ -278,48 +292,49 @@ class LocalTunnelSender : public TunnelSender
...
             consumer_state.setMsg(local_err_msg);
-            local_request_handler.connectionLocalDone(meet_error, local_err_msg);
+            local_request_handler.writeDone(meet_error, local_err_msg);
         }
     }
 
     size_t source_index;
     LocalRequestHandler local_request_handler;
     std::atomic_bool is_done;
+    std::mutex mu;
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/MPPTunnel.h:337]: Seems useless.

**Review by SeaRise — COMMENTED** [review]
Others LGTM

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp [hunk 24]
```diff
@@ -418,9 +459,22 @@ void ExchangeReceiverBase<RPCContext>::setUpConnection()
...
                 ReceiverChannelWriter(&(getMsgChannels()), req_info, exc_log, getDataSizeInQueue(), ReceiverMode::Local));
 
-            rpc_context->establishMPPConnectionLocal(req, req.source_index, local_request_handler, enable_fine_grained_shuffle_flag);
+            rpc_context->establishMPPConnectionLocal(
+                req,
+                req.source_index,
+                local_request_handler,
+                enable_fine_grained_shuffle_flag,
+                [this]() {
+                    this->addLocalConnectionNum();
```
Comment (windtalker) [inline dbms/src/Flash/Mpp/ExchangeReceiver.cpp:476]: Why need to `addLocalConnectionNum` after we have `setLocalAlive`?

Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/ExchangeReceiver.cpp:476]: > Why need to `addLocalConnectionNum` after we have `setLocalAlive`?

I will combine them together

File: dbms/src/Flash/Mpp/MPPTunnel.h (hunk 20 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/MPPTunnel.h:271]: > combine into `local_request_handler.setAlive()`.

okk

**Review by windtalker — APPROVED** [review]
LGTM

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp (hunk 22 above)
Comment (SeaRise) [reply dbms/src/Flash/Mpp/ExchangeReceiver.cpp:834]: It doesn't look modified?

**Review by SeaRise — APPROVED** [review]

File: dbms/src/Flash/Mpp/ExchangeReceiver.cpp (hunk 22 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/ExchangeReceiver.cpp:835]: > It doesn't look modified?

fixed
