### PR TITLE
Storages: Optimize vector search in scenarios with updates

### LINKED ISSUE #9599: Vector search lower recall when there is multiple ColumnFile in delta layer with vector index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. create a table with vector type column
2. insert more than 10K rows
3. vector search

### 2. What did you expect to see? (Required)

recall > 90%

### 3. What did you see instead (Required)

recall < 20%

### 4. What is your TiFlash version? (Required)
master

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: ref #9600 , close #9599

Problem Summary:

### What is changed and how it works?

Before, the read path of vector search is:

1. load stable vector index.
2. read all packs that contain TopK results.
3. load all ColumnFileTiny vector index.
4. read all ColumnFileTiny that contain TopK results.
5. read Memtable.

A simple example:

We have cf_0 (indexed, offset: 100-110), cf_1 (indexed, offset: 110-120), cf_3 (indexed, offset: 120-130), cf_4 (memtable, offset: 130-140), dmfile_0 (indexed, offset: 0-100, each 10 rows as a pack), to find top5:

1.  load stable vector index: top5 is [0, 10, 13, 25, 99]
2. read all packs that contain TopK results: read pack_0, pack_1, pack_2, pack_9
3. load all ColumnFileTiny vector index: top5 is [100, 101, 115, 116, 119]
4. read all ColumnFileTiny that contain TopK results: read cf_0, cf_1
5. read Memtable: read cf_4.

So, in this example, we need to read 3 packs and 3 ColumnFileTinys.

This PR changes the read path to: 

1. load stable vector index and all ColumnFileTiny vector index.
2. read all packs that contain TopK results.
3. read all ColumnFileTiny that contain TopK results.
4. read Memtable.

Still using the above example, now to find top5:

1. load stable vector index and all ColumnFileTiny vector index: top5 is [0, 10, 13, 100, 101]
2. read all packs that contain TopK results: read pack_0, pack_1
3. read all ColumnFileTiny that contain TopK results: read cf_0
4. read Memtable: read cf_4

Now, we only need to read 2 packs and 2 ColumnFileTinys.

#### Benchmark

Run [VectorDBBench](https://github.com/wd0517/VectorDBBench), about 750k stable, 250k delta with vector index, 4k delta without vector index.

Note: should disable compact tiflash replica

```diff
diff --git a/vectordb_bench/backend/clients/tidb_serverless/tidb.py b/vectordb_bench/backend/clients/tidb_serverless/tidb.py
index b927568..fe9d5e3 100644
--- a/vectordb_bench/backend/clients/tidb_serverless/tidb.py
+++ b/vectordb_bench/backend/clients/tidb_serverless/tidb.py
@@ -104,9 +104,9 @@ class TiDBServeless(VectorDB):
             else:
                 break
 
-        log.info("Begin compact tiflash replica")
-        self._compact_tiflash()
-        log.info("Successful compacted tiflash replica")
+        # log.info("Begin compact tiflash replica")
+        # self._compact_tiflash()
+        # log.info("Successful compacted tiflash replica")
 
         log_reduce_seq = 0
         while True:
```

**Without this PR (after fix #9599)**

```json
"metrics": {
    "max_load_count": 0,
    "load_duration": 747.9345,
    "qps": 71.4146,
    "serial_latency_p99": 0.1081,
    "recall": 0.9327
}
```

**With this PR**

```json
"metrics": {
    "max_load_count": 0,
    "load_duration": 778.9001,
    "qps": 125.046,
    "serial_latency_p99": 0.0851,
    "recall": 0.931
}
```

**All data are in stable**

```json
"metrics": {
    "max_load_count": 0,
    "load_duration": 0.0,
    "qps": 205.3793,
    "serial_latency_p99": 0.0282,
    "recall": 0.9016
}
```

```commit-message
Improve 75% the performance of vector search in scenarios with updates.
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by JaySon-Huang** [comment]
Can you briefly describe what changes you've done in this PR?

**Comment by Lloyd-Pottiger** [comment]
> Can you briefly describe what changes you've done in this PR?

done

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.cpp [hunk 1]
```diff
@@ -36,9 +36,10 @@ void ColumnFileTinyVectorIndexReader::read(
     vec_column->reserve(read_rows);
     std::vector<Float32> value;
     size_t current_rowid = rowid_start_offset;
-    for (const auto & [rowid, _] : read_rowids)
+    for (const auto & rowid : read_rowids)
     {
-        vec_index->get(rowid, value);
+        // Each ColomnFileTiny has its own vector index, rowid_start_offset is the offset of the ColmnFilePersistSet.
+        vec_index->get(rowid - rowid_start_offset, value);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.cpp:42]: These lines fix the recall issue: https://github.com/pingcap/tiflash/issues/9599

File: dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp [hunk 2]
```diff
@@ -140,19 +140,19 @@ SkippableBlockInputStreamPtr DMFileBlockInputStreamBuilder::tryBuildWithVectorIn
...
     // if (is_fast_scan || enable_del_clean_read || enable_handle_clean_read)
     //    return fallback();
 
     auto filter_with_ann = std::dynamic_pointer_cast<WithANNQueryInfo>(rs_filter);
-    if (filter_with_ann == nullptr)
+    if (!filter_with_ann)
         return fallback();
 
     auto ann_query_info = filter_with_ann->ann_query_info;
-    if (!ann_query_info || ann_query_info->top_k() == std::numeric_limits<UInt32>::max())
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp:155]: I think the behavior of when `ann_query_info->top_k() == std::numeric_limits<UInt32>::max()` fallback to "brute force" algo is missed after these changes?

File: dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp [hunk 3]
```diff
@@ -99,4 +99,14 @@ RSOperatorPtr wrapWithANNQueryInfo(const RSOperatorPtr & op, const ANNQueryInfoP
...
 }
 
+ANNQueryInfoPtr getANNQueryInfo(const RSOperatorPtr & op)
+{
+    if (op == nullptr)
+        return nullptr;
+    auto with_ann = std::dynamic_pointer_cast<WithANNQueryInfo>(op);
+    if (with_ann == nullptr)
+        return nullptr;
+    return with_ann->ann_query_info;
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp:109]:
```suggestion
    // invalid query info, should fallback as the `ann_query_info` is not exist
    if (with_ann->ann_query_info->top_k() == std::numeric_limits<UInt32>::max())
        return nullptr;
    return with_ann->ann_query_info;
```

File: dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp [hunk 4]
```diff
@@ -235,21 +235,15 @@ LocalIndexesStats DeltaMergeStore::getLocalIndexStats()
             const auto & delta = segment->getDelta();
             if (const auto lock = delta->getLock(); lock)
             {
-                const auto & mem_table = delta->getMemTableSet();
-                index_stats.rows_delta_not_indexed += mem_table->getRows();
+                index_stats.rows_delta_not_indexed += delta->getRows();
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp:238]: why change the logic to first set to delta->getRows, then subtract the rows of not indexed tiny_file rows?

File: dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp (hunk 2 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp:155]: https://github.com/pingcap/tidb/pull/57307 Maybe handling this behavior in TiDB is a better idea.

File: dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp (hunk 4 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp:238]: reduce virtual function calls

**Comment by CalvinNeo** [comment]
image

Seem that what is changed is the order of these operations. Could you explain more about why changing order can improve performance?

**Comment by Lloyd-Pottiger** [comment]
> image
> 
> Seem that what is changed is the order of these operations(the yellow and the green lines swapped their order). Could you explain more about why changing order can improve performance? I guess you can somehow reduce the vector index loaded from either ColumnFileTiny or Stable layer, but I am not so clear.

Add an example in PR description.

**Comment by Lloyd-Pottiger** [comment]
[tiflash_127.speedscope.json](https://github.com/user-attachments/files/17713951/tiflash_127.speedscope.json)

Flamegraph

File: dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp (hunk 2 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp:155]: As the terms of "defensive programming", I think both TiDB and TiFlash should try to prevent top_k() == UINT32_MAX for running into vector index. Because in TiFlash perspective, we can not ensure the input is always trustable, especially the "top_k" value is comes from a network package. Maybe the network packet comes from a lower version of tidb-server, cse version of tidb-server, or other clients. Or in the TiDB side, someone may remove the limitation you added in someday.
So I still think the guard in TiFlash side is necessary.

Comment (Lloyd-Pottiger) [reply dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp:155]:
```cpp
     bool is_valid_ann_query = ann_query_info->top_k() != std::numeric_limits<UInt32>::max();
     bool is_matching_ann_query = std::any_of(
         table_column_defines.begin(),
         table_column_defines.end(),
         [cid = ann_query_info->column_id()](const ColumnDefine & cd) -> bool { return cd.id == cid; });
     if (!is_valid_ann_query || !is_matching_ann_query)
         return rs_operator;

     return wrapWithANNQueryInfo(rs_operator, ann_query_info);
```

**Review by breezewish — APPROVED** [review]
