### PR TITLE
io: Fix checksum seek at end

### LINKED ISSUE #10340: Checksum seek at end cause read failed
## Bug Report

https://github.com/pingcap/tiflash/blob/dce9588b0512a6aaeaac98ac7d65e9102a664f26/dbms/src/IO/Checksum/ChecksumBuffer.h#L436-L440

If `target_frame == current_frame` && `working_buffer` is cleared. The `pos` is forwarded, then when we call `next()` after `seek`, we will read from an invalid memory.

The issue may lead to errors as follow
```
Code: 271, e.displayText() = DB::Exception: Data compressed with different methods, given method byte 0xbb, previous method byte 0x82: (while reading from DTFile: s3://s90592969/data/ks_37715_t_146/dmf_4432, column: 27:): while building stable index for index_ids=[2, 3], e.what() = DB::Exception
```

---
Maybe releated to this bug or not. Reading from S3 report errno=115
```
[2025/08/12 15:59:53.651 +00:00] [ERROR] [S3RandomAccessFile.cpp:118] ["Cannot read from istream, size=1048592 gcount=0 state=0x06 cur_offset=977287744 content_length=978111336 errno=115 errmsg=Operation now in progress cost=2896ns"] [source=s86062474/data/ks_90779_t_441/dmf_28961/7.dat] [thread_id=3925]
```

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #10340

Problem Summary:

When there are multiple NULL rows of Strings-like column or vector-like column, TiFlash may save some "empty blocks" into the DMFile. And it happen to be the "empty blocks" are stored at the end of the DMFile.

When TiFlash try to read data from disk, `DMFileReader::readFromDisk` will first call `FramedChecksumReadBuffer::doSeek` and seek to the "empty block" at the file end. The working_buffer will be release because we read to the end of the file. When TiFlash try to seek to the next "empty block", `pos` move forward the released working_buffer, leading to reading random data and cause random failure.

https://github.com/pingcap/tiflash/blob/76a4ec4e279e7c61e5e4a4e001aef3be67c6389e/dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp#L542-L555

https://github.com/pingcap/tiflash/blob/dce9588b0512a6aaeaac98ac7d65e9102a664f26/dbms/src/IO/Checksum/ChecksumBuffer.h#L436-L440

### What is changed and how it works?

```commit-message
1. In `FramedChecksumReadBuffer::doSeek`, add guard check for `working_buffer` size and `target_offset`. If the working_buffer is cleared, then re-seek the working buffer according to the offset and load data from the underlying file again.
2. In order to support the behavior above, `S3RandomAccessFile::seekImpl` support seek backward, which is implemented by reopening the file again
3. Add retry when reading from S3 meet errno=115, EINPROGRESS
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix possible read fail when column data contains lots of "NULL" values.
```

### CODE REVIEW

File: dbms/src/Storages/S3/S3RandomAccessFile.cpp [hunk 1]
```diff
@@ -166,6 +166,18 @@ off_t S3RandomAccessFile::seekImpl(off_t offset_, int whence)
...
+
+    if (offset_ < cur_offset)
+    {
+        cur_offset = offset_;
+        if (!initialize())
+        {
+            return S3StreamError;
+        }
+        return cur_offset;
+    }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/S3/S3RandomAccessFile.cpp]: why do we need to seek backward?

File: dbms/src/IO/Checksum/tests/gtest_dm_checksum_buffer.cpp [hunk 2]
```diff
@@ -372,5 +372,115 @@ TEST_STACKED_SEEKING(CRC32)
...
+    });
+    // Test data - create multiple blocks with different patterns
+    std::vector<std::string> test_blocks;
+
+    test_blocks = {
+        std::string(1500, 'A') + "BLOCK0_END",
+        std::string(800, 'B') + "BLOCK1_END",
+        "", // Block 2 is empty
+        "", // Block 3 is empty
+    };
```
Comment (JaySon-Huang) [inline dbms/src/IO/Checksum/tests/gtest_dm_checksum_buffer.cpp:394]: When will we write "empty block" to the `CompressedWriteBuffer<ChecksumWriteBuffr>`? When there are large number of "NULL" values in the block?

File: dbms/src/Storages/S3/S3RandomAccessFile.cpp (hunk 1 above)
Comment (breezewish) [reply dbms/src/Storages/S3/S3RandomAccessFile.cpp]:
```
// If we have already seek to EOF, then working_buffer was cleared
    if (target_frame == current_frame && working_buffer.size() > 0)
    {
        if (unlikely(target_offset > working_buffer.size()))
            pos = working_buffer.end();
        else
            pos = working_buffer.begin() + target_offset;
        return offset;
    }
```

If the same target frame is seeked again it is seeked in backward.

BTW it would be great if we could figure out some ways to avoid seeking backward.

File: dbms/src/IO/Checksum/tests/gtest_dm_checksum_buffer.cpp (hunk 2 above)
Comment (Lloyd-Pottiger) [reply dbms/src/IO/Checksum/tests/gtest_dm_checksum_buffer.cpp:394]: Yes.

File: dbms/src/IO/Checksum/ChecksumBuffer.cpp [hunk 3]
```diff
@@ -18,6 +18,81 @@ namespace DB
...
+
+        // body checksum examination
+        checkBody();
+
+        // update statistics
+        current_frame = target_frame;
+        if (unlikely(target_offset > working_buffer.size()))
+            pos = working_buffer.end();
+        else
+            pos = working_buffer.begin() + target_offset;
```
Comment (JaySon-Huang) [inline dbms/src/IO/Checksum/ChecksumBuffer.cpp]: The main change  in here is to change

```
        pos = working_buffer.begin() + target_offset;
```

to
```
        if (unlikely(target_offset > working_buffer.size()))
            pos = working_buffer.end();
        else
            pos = working_buffer.begin() + target_offset;
```

File: dbms/src/IO/Checksum/ChecksumBuffer.cpp [hunk 4]
```diff
@@ -18,6 +18,81 @@ namespace DB
...
+
+    // If we have already seek to EOF, then working_buffer was cleared
+    if (target_frame == current_frame && working_buffer.size() > 0)
+    {
+        if (unlikely(target_offset > working_buffer.size()))
+            pos = working_buffer.end();
+        else
+            pos = working_buffer.begin() + target_offset;
+        return offset;
+    }
```
Comment (JaySon-Huang) [inline dbms/src/IO/Checksum/ChecksumBuffer.cpp:48]: The change in here is change
```
    if (target_frame == current_frame)
    {
        pos = working_buffer.begin() + target_offset;
        return offset;
    }
```
to
```
    // If we have already seek to EOF, then working_buffer was cleared
    if (target_frame == current_frame && working_buffer.size() > 0)
    {
        if (unlikely(target_offset > working_buffer.size()))
            pos = working_buffer.end();
        else
            pos = working_buffer.begin() + target_offset;
        return offset;
    }
```

**Review by JaySon-Huang — COMMENTED** [review]
highlight what is changed

File: dbms/src/IO/Checksum/tests/gtest_dm_checksum_buffer.cpp [hunk 5]
```diff
@@ -372,5 +373,115 @@ TEST_STACKED_SEEKING(CRC32)
...
+        read_data.resize(100);
+        compressed_in->readBig(read_data.data(), 0);
+    }
+}
+
+#define TEST_COMPRESSEDSEEKABLE(ALGO)                \
+    TEST(DMChecksumBuffer##ALGO, CompressedSeekable) \
+    {                                                \
+        runStackingTest<ChecksumAlgo::ALGO>();       \
+    } // NOLINT(cert-err58-cpp)
```
Comment (JaySon-Huang) [inline dbms/src/IO/Checksum/tests/gtest_dm_checksum_buffer.cpp]: The test is not actually run the expected testing logic by a typo here
```suggestion
#define TEST_COMPRESSEDSEEKABLE(ALGO)                                \
    TEST(DMChecksumBuffer##ALGO, CompressedSeekable)                 \
    {                                                                \
        runCompressedSeekableReaderBufferTest<ChecksumAlgo::ALGO>(); \
    } // NOLINT(cert-err58-cpp)
```

**Review by JaySon-Huang — APPROVED** [review]
LGTM
