### PR TITLE
fix lock contension of consumeResource in storage layer

### LINKED ISSUE #8270: LAC::consumeResource may introduce performance regression
## Bug Report

Please answer these questions before submitting your issue. Thanks!

https://github.com/pingcap/tiflash/blob/master/dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h#L224 and https://github.com/pingcap/tiflash/blob/master/dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp#L194 will consume resource for storage layer, but there are situations that the calling of `LAC::consumeResource` are too frequent, which may introduce significant regression.

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #8270

Problem Summary:
1. Add `BytesCollector` to avoid `LAC::consumeResource()` is called too frequent.
2. Del `DAGContext::enableResourceControl()/isResourceControlEnabled()`. Check if `DAGContext::resource_group_name` is empty to decide whether collect storage bytes RU.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below): ch benchmark. waiting for the result
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp [hunk 1]
```diff
@@ -185,16 +185,12 @@ size_t ColumnFileSetReader::readRows(
             }
         }
     }
+    auto lac_bytes_collector = std::make_unique<LACBytesCollector>(context.scan_context->resource_group_name);
```
Comment (SeaRise) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp:188]: How about being member variable of `ColumnFileSetReader`?

File: dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h [hunk 2]
```diff
@@ -152,6 +152,7 @@ class ConcatSkippableBlockInputStream : public SkippableBlockInputStream
     {
         Block res;
 
+        auto lac_bytes_collector = std::make_unique<LACBytesCollector>(scan_context->resource_group_name);
```
Comment (SeaRise) [inline dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h:155]: How about being member variable of `SkippableBlockInputStream`?

File: dbms/src/Flash/Coprocessor/DAGContext.h [hunk 3]
```diff
@@ -318,8 +318,8 @@ class DAGContext
 
     KeyspaceID getKeyspaceID() const { return keyspace_id; }
     String getResourceGroupName() { return resource_group_name; }
-    void enableResourceControl() { enable_resource_control = true; }
-    bool isResourceControlEnabled() const { return enable_resource_control; }
+    // For now, only called for BlockIO execution engine to disable report RU of storage layer.
+    void clearResourceGroupName() { resource_group_name = ""; }
```
Comment (SeaRise) [inline dbms/src/Flash/Coprocessor/DAGContext.h:322]:
```suggestion
    void disableResourceControl() { resource_group_name = ""; }
```

File: dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h (hunk 2 above)
Comment (guo-shaoge) [reply dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h:155]: If being member of `SkippableBlockInputStream`, the last `LACBytesCollector::consume()` will be called when `SkippableBlockInputStream` is destructed.  Maybe it's too late?

File: dbms/src/Flash/Coprocessor/DAGContext.h (hunk 3 above)
Comment (guo-shaoge) [reply dbms/src/Flash/Coprocessor/DAGContext.h:322]: May confused with `profiles.default.enable_resource_control`

File: dbms/src/Flash/ResourceControl/LocalAdmissionController.h [hunk 4]
```diff
@@ -613,4 +613,41 @@ class LocalAdmissionController final : private boost::noncopyable
...
+    {
+        if (delta_bytes != 0)
+            consume();
+    }
+
+    void collect(uint64_t bytes)
+    {
+        delta_bytes += bytes;
+        // Call LAC::consumeResource() when accumulated to 1 RU(a.k.a. 64K) to avoid lock contension.
+        if (delta_bytes >= bytes_of_one_ru)
```
[the remark this answers is not in the document]
Comment (guo-shaoge) [reply dbms/src/Flash/ResourceControl/LocalAdmissionController.h]: FxdS87GZgR
As discuessed, Changed to 100. And add todo.

[the remark this answers is not in the document]
Comment (guo-shaoge) [reply dbms/src/Flash/ResourceControl/LocalAdmissionController.h]: And I'm testing again in benchbot

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp (hunk 1 above)
Comment (guo-shaoge) [reply dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp]: done

File: dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h (hunk 2 above)
Comment (guo-shaoge) [reply dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h]: done

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp [hunk 5]
```diff
@@ -189,12 +190,7 @@ size_t ColumnFileSetReader::readRows(
     {
         const auto delta_bytes = col->byteSize();
         context.scan_context->total_user_read_bytes += delta_bytes;
-
-        if (context.scan_context->enable_resource_control)
-            LocalAdmissionController::global_instance->consumeResource(
-                context.scan_context->resource_group_name,
-                bytesToRU(delta_bytes),
-                0);
+        lac_bytes_collector.collect(delta_bytes);
```
Comment (SeaRise) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp:193]: what about
```suggestion
    uint64_t total_read_bytes = 0;
    for (const auto & col : output_columns)
        total_read_bytes  += col->byteSize();
    context.scan_context->total_user_read_bytes += total_read_bytes ;
    lac_bytes_collector.collect(total_read_bytes);
```

File: dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h [hunk 6]
```diff
@@ -219,18 +221,14 @@ class ConcatSkippableBlockInputStream : public SkippableBlockInputStream
...
         {
             scan_context->total_user_read_bytes += bytes;
-
-            if (scan_context->enable_resource_control)
-                LocalAdmissionController::global_instance->consumeResource(
-                    scan_context->resource_group_name,
-                    bytesToRU(bytes),
-                    0);
+            lac_bytes_collector.collect(bytes);
         }
```
Comment (SeaRise) [inline dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h:225]:
```suggestion
        }
        lac_bytes_collector.collect(bytes);
```

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp (hunk 5 above)
Comment (guo-shaoge) [reply dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp]: done

File: dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h [hunk 7]
```diff
@@ -94,6 +96,8 @@ class ConcatSkippableBlockInputStream : public SkippableBlockInputStream
     {
         children.insert(children.end(), inputs_.begin(), inputs_.end());
         current_stream = children.begin();
+        if (scan_context)
+            lac_bytes_collector = std::make_unique<LACBytesCollector>(scan_context_->resource_group_name);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h:100]:
```suggestion
        if (scan_context)
            lac_bytes_collector = std::make_unique<LACBytesCollector>(scan_context->resource_group_name);
```

File: dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h [hunk 8]
```diff
@@ -82,6 +82,8 @@ class ConcatSkippableBlockInputStream : public SkippableBlockInputStream
...
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h:86]:
```suggestion
        if (scan_context)
            lac_bytes_collector = std::make_unique<LACBytesCollector>(scan_context->resource_group_name);
```

**Review by JaySon-Huang — COMMENTED** [review]
Keep it using the same pointer

File: dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h (hunk 8 above)
Comment (guo-shaoge) [reply dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h]: done

File: dbms/src/Flash/Executor/toRU.h [hunk 9]
```diff
@@ -26,4 +26,7 @@ UInt64 toCPUTimeMillisecond(UInt64 cpu_time_ns);
 // Convert cpu time nanoseconds to Request Unit.
 RU cpuTimeToRU(UInt64 cpu_time_ns);
 RU bytesToRU(UInt64 bytes);
+
+static constexpr UInt64 bytes_of_one_ru = 1024 * 64;
+static constexpr UInt64 bytes_of_one_hundred_ru = 100 * 1024 * 64;
```
Comment (SeaRise) [inline dbms/src/Flash/Executor/toRU.h:31]:
```suggestion
static constexpr UInt64 bytes_of_one_hundred_ru = 100 * bytes_of_one_ru;
```

File: dbms/src/Flash/ResourceControl/LocalAdmissionController.h [hunk 10]
```diff
@@ -613,4 +613,45 @@ class LocalAdmissionController final : private boost::noncopyable
...
+    ~LACBytesCollector()
+    {
+        if (delta_bytes != 0)
+            consume();
+    }
+
+    void collect(uint64_t bytes)
+    {
+        delta_bytes += bytes;
+        // Call LAC::consumeResource() when accumulated to 1 RU(a.k.a. 64K) to avoid lock contension.
```
Comment (SeaRise) [inline dbms/src/Flash/ResourceControl/LocalAdmissionController.h:637]:
```suggestion
        // Call LAC::consumeResource() when accumulated to `bytes_of_one_hundred_ru` to avoid lock contension.
```

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h [hunk 11]
```diff
@@ -33,6 +33,8 @@ class ColumnFileSetReader
     ColumnDefinesPtr col_defs;
     RowKeyRange segment_range;
 
+    LACBytesCollector lac_bytes_collector;
```
Comment (SeaRise) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h:36]: how about moving to L44?
I'm a bit worried that `ColumnFileReader`'s destructor might take some time.

File: dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h [hunk 12]
```diff
@@ -219,18 +223,15 @@ class ConcatSkippableBlockInputStream : public SkippableBlockInputStream
...
-                    0);
+            assert(lac_bytes_collector);
+            lac_bytes_collector->collect(bytes);
         }
     }
     BlockInputStreams::iterator current_stream;
     std::vector<size_t> rows;
     size_t precede_stream_rows;
     const ScanContextPtr scan_context;
+    LACBytesCollectorPtr lac_bytes_collector;
```
Comment (SeaRise) [inline dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h:234]: `ConcatSkippableBlockInputStream` and `ColumnFileSetReader` will be destroyed immediately after execution instead of waiting for mpptask to be destroyed, right? @JinheLin

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h (hunk 11 above)
Comment (guo-shaoge) [reply dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h]: ok

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp [hunk 13]
```diff
@@ -89,6 +89,7 @@ ColumnFileSetReader::ColumnFileSetReader(
     , snapshot(snapshot_)
     , col_defs(col_defs_)
     , segment_range(segment_range_)
+    , lac_bytes_collector(context_.scan_context->resource_group_name)
```
Comment (guo-shaoge) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp:92]: can `context_.scan_context` be nullptr here? @JinheLin

Comment (guo-shaoge) [reply dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp]: I changed to use unique_ptr instead

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h [hunk 14]
```diff
@@ -40,10 +40,15 @@ class ColumnFileSetReader
...
 
+    LACBytesCollectorPtr lac_bytes_collector;
+
 private:
     explicit ColumnFileSetReader(const DMContext & context_)
         : context(context_)
-    {}
+    {
+        if (context.scan_context)
+            lac_bytes_collector = std::make_unique<LACBytesCollector>(context.scan_context->resource_group_name);
```
Comment (SeaRise) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h:50]: maybe `lac_bytes_collector(context.scan_context ？ context.scan_context->resource_group_name : "")` is enough.
But I think it's okay.

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp [hunk 15]
```diff
@@ -185,17 +187,15 @@ size_t ColumnFileSetReader::readRows(
...
-
-        if (context.scan_context->enable_resource_control)
-            LocalAdmissionController::global_instance->consumeResource(
-                context.scan_context->resource_group_name,
-                bytesToRU(delta_bytes),
-                0);
-    }
+        delta_bytes += col->byteSize();
+
+    context.scan_context->total_user_read_bytes += delta_bytes;
```
Comment (SeaRise) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp:195]:
```suggestion
    if (likely(context.scan_context))
        context.scan_context->total_user_read_bytes += delta_bytes;
```

**Review by SeaRise — APPROVED** [review]
LGTM

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h (hunk 14 above)
Comment (guo-shaoge) [reply dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h]: changed.
