### PR TITLE
Fix mpp task hang in spill random fail point

### LINKED ISSUE #7440: MPP Task hang in spill random fail point
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

mpp task is released quickly.

### 3. What did you see instead (Required)

https://clinic.pingcap.com.cn/grafana/d/SVbh2xUWkoperatormaster/tiflash-summary-cluster-clinic?orgId=1&var-tidb_cluster=7227604775299467630&var-instance=All&var-store=All&from=1682807849000&to=1682813931000&var-tidb_version=master&var-org=31&refresh=15m

image

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #7440

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/Mpp/AsyncRequestHandler.h [hunk 1]
```diff
@@ -368,6 +369,12 @@ class AsyncRequestHandler : public AsyncRequestHandlerBase
         async_wait_rewrite_queue->push(std::make_pair(&kick_recv_tag, reader->getClientContext()->c_call()));
     }
 
+    void closeGrpcConnection()
+    {
+        RUNTIME_ASSERT(reader.use_count() <= 1, "reader should be uniquely held");
```
[the remark this answers is not in the document]
Comment (xzhangxian1008) [reply dbms/src/Flash/Mpp/AsyncRequestHandler.h:374]: > If this is always true, why not just use unique_ptr?

Because `makeAsyncReader`'s parameter type is `shared_ptr`.

File: dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp [hunk 2]
```diff
@@ -276,7 +276,7 @@ struct MockReceiverContext
 
     void makeAsyncReader(
         const Request &,
-        std::shared_ptr<AsyncReader> &,
+        std::unique_ptr<AsyncReader> &,
         grpc::CompletionQueue *,
         UnaryCallback<bool> *) const {}
```
Comment (SeaRise) [inline dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp:281]: maybe
```
std::unique_ptr<AsyncReader> makeAsyncReader(
        const Request &,
        std::shared_ptr<AsyncReader> &,
        grpc::CompletionQueue *,
        UnaryCallback<bool> *) const {}
```
is better?

**Review by SeaRise — APPROVED** [review]
Others LGTM

File: dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp (hunk 2 above)
Comment (xzhangxian1008) [reply dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp:281]: > maybe
> 
> ```
> std::unique_ptr<AsyncReader> makeAsyncReader(
>         const Request &,
>         std::shared_ptr<AsyncReader> &,
>         grpc::CompletionQueue *,
>         UnaryCallback<bool> *) const {}
> ```
> 
> is better?

I think this may cause compile error as it's function signature is different from the GRPCReceiverContext's.

Comment (SeaRise) [reply dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp:281]: ok

**Review by windtalker — APPROVED** [review]
LGTM
