### PR TITLE
Fix ilike function 

### LINKED ISSUE #6949: escape in Ilike function is not well supported

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #6949

Problem Summary:

Original implementation of ilike didn't consider the escape, we handle this situation when escape char is alphabet.

### Check List

Tests 

- [ x ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Functions/FunctionsStringSearch.h [hunk 1]
```diff
@@ -197,13 +282,11 @@ class FunctionsStringSearch : public IFunction
...
-            {
-                block.getByPosition(arguments[0]).column = (*std::move(result_block.getByPosition(arguments[0]).column)).mutate();
-                block.getByPosition(arguments[1]).column = (*std::move(result_block.getByPosition(arguments[1]).column)).mutate();
+            block.getByPosition(arguments[0]).column = (*std::move(result_block.getByPosition(arguments[0]).column)).mutate();
+            block.getByPosition(arguments[1]).column = (*std::move(result_block.getByPosition(arguments[1]).column)).mutate();
 
-                IlikeHelper::lowerAlphaASCII(block, arguments);
-            }
+            IlikeLowerHelper::lowerAlphaASCII(block, arguments);
+            IlikeLowerHelper::convertCollatorToBin(collator);
```
Comment (ywqzzy) [inline dbms/src/Functions/FunctionsStringSearch.h:289]: Why add this convert?

File: dbms/src/Functions/tests/gtest_strings_search.cpp [hunk 2]
```diff
@@ -16,6 +16,7 @@
 #include <Functions/registerFunctions.h>
 #include <Storages/Transaction/Collator.h>
 #include <TestUtils/FunctionTestUtils.h>
+#include "magic_enum.hpp"
```
Comment (ywqzzy) [inline dbms/src/Functions/tests/gtest_strings_search.cpp:19]:
```suggestion
#include <magic_enum.hpp>
```

File: dbms/src/Functions/FunctionsStringSearch.h (hunk 1 above)
Comment (xzhangxian1008) [reply dbms/src/Functions/FunctionsStringSearch.h:289]: > Why add this convert?

The following is the reasons:
- ci behaviour of ci collator is not expected by us, it will do ci for non-ascii chars
- bin collator is the fastest collator

File: dbms/src/Functions/FunctionsStringSearch.h [hunk 3]
```diff
@@ -36,61 +36,146 @@ namespace DB
...
     }
 
-    static void lowerColumnConst(ColumnConst * lowered_col_const)
+    // When escape_char is a lower char, we need to convert it to the capital char
+    // Because: when lowering "ABC" with escape 'a', after lower, "ABC" -> "abc",
+    // then 'a' will be an escape char and it is not expected.
+    // Morever, when escape char is uppered we need to tell it to the caller.
+    static void lowerStringsExcludeEscapeChar(Chars_t & chars, char escape_char)
+    {
+        if (!isAlphaASCII(escape_char))
```
Comment (yibin87) [inline dbms/src/Functions/FunctionsStringSearch.h:107]: add unlikely?

File: dbms/src/Functions/FunctionsStringSearch.h [hunk 4]
```diff
@@ -36,61 +36,146 @@ namespace DB
...
             if (isUpperAlphaASCII(chars[i]))
             {
                 chars[i] = toLowerIfAlphaASCII(chars[i]);
-                ++i;
             }
             else
             {
                 size_t utf8_len = UTF8::seqLength(chars[i]);
-                i += utf8_len;
+                i += utf8_len - 1;
```
[the remark this answers is not in the document]
Comment (xzhangxian1008) [reply dbms/src/Functions/FunctionsStringSearch.h:96]: > would UTF8::seqLength return 0 in any situation?

no, it returns at least 1.

File: dbms/src/Functions/FunctionsStringSearch.h (hunk 3 above)
Comment (xzhangxian1008) [reply dbms/src/Functions/FunctionsStringSearch.h:107]: > add unlikely?

okk

**Review by yibin87 — APPROVED** [review]
LGTM

File: dbms/src/Functions/FunctionsStringSearch.h [hunk 5]
```diff
@@ -36,61 +36,146 @@ namespace DB
...
+            lowerStrings(lowered_col_data->getChars());
+            return;
+        }
 
-        if (col_haystack_const != nullptr)
-            lowerColumnConst(col_haystack_const);
-        else
-            lowerColumnString(column_haystack);
+        const auto * col_escape_const = typeid_cast<const ColumnConst *>(&*column_escape);
+        RUNTIME_CHECK_MSG(col_escape_const != nullptr, "escape char column should be constant");
```
Comment (windtalker) [inline dbms/src/Functions/FunctionsStringSearch.h:175]: what about escape is null?

Comment (xzhangxian1008) [reply dbms/src/Functions/FunctionsStringSearch.h:175]: > what about escape is null?

TiDB will raise error when escape is null.

**Review by windtalker — APPROVED** [review]
LGTM
