### PR TITLE
Fix read duration type column failed in disaggregated mode

### LINKED ISSUE #7414: Window function got mismatch data type pack error in disaggregated tiflash mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Setup **disaggregated tiflash** cluster using `tiup cluster`(1 CN 1 WN)
2. Connect to tidb, create table and insert table. [tbl_8.txt](https://github.com/pingcap/tiflash/files/11394498/tbl_8.txt)
3. run the following sqls:
```
alter table tbl_8 set tiflash replica 1;
set tidb_isolation_read_engines = 'tiflash';
select    lag( tbl_8.col_43 , 6 ,NULL) over w as r0 from tbl_8 where not( tbl_8.col_44 between '08:17:52.00' and '05:02:37.00' )  window w as (  order by col_44,col_42,col_40,col_41,col_45,col_43 rows between 2 preceding and current    row ) order by r0 ;
```
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
run ok
### 3. What did you see instead (Required)
```
[2023/05/04 14:23:49.021 +08:00] [ERROR] [MPPTask.cpp:471] ["task running meets error: Code: 48, e.displayText() = DB::Exception: Reading mismatch data type pack. Cast from Int64 to MyDuration(0) is NOT supported!: (while reading from DTFile: s3://s4/data/t_154/dmf_19), e.what() = DB::Exception, Stack trace:
       0x1c1608e\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+29450382]
                \tdbms/src/Common/Exception.h:46
       0x74d1ad4\tDB::DM::convertColumnByColumnDefineIfNeed(std::__1::shared_ptr<DB::IDataType const> const&, COWPtr<DB::IColumn>::immutable_ptr<DB::IColumn>&&, DB::DM::ColumnDefine const&) [tiflash+122493652]
                \tdbms/src/Storages/DeltaMerge/convertColumnTypeHelpers.cpp:464
       0x74c0d0c\tDB::DM::DMFileReader::read() [tiflash+122424588]
                \tdbms/src/Storages/DeltaMerge/File/DMFileReader.cpp:625
       0x74b8145\tDB::DM::DMFileBlockInputStream::read() [tiflash+122388805]
                \tdbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h:64
       0x74258bd\tDB::DM::ConcatSkippableBlockInputStream<false>::read() [tiflash+121788605]
                \tdbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h:175
       0x744c371\tDB::DM::readBlock(std::__1::shared_ptr<DB::DM::SkippableBlockInputStream>&, std::__1::shared_ptr<DB::DM::SkippableBlockInputStream>&) [tiflash+121946993]
                \tdbms/src/Storages/DeltaMerge/ReadUtil.cpp:33
       0x747c0dc\tDB::DM::BitmapFilterBlockInputStream::readImpl(DB::PODArray<unsigned char, 4096ul, Allocator<false>, 15ul, 16ul>*&, bool) [tiflash+122142940]
                \tdbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.cpp:40
       0x747c6d4\tDB::DM::BitmapFilterBlockInputStream::readImpl() [tiflash+122144468]
                \tdbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.h:46
       0x7667285\tDB::IProfilingBlockInputStream::read(DB::PODArray<unsigned char, 4096ul, Allocator<false>, 15ul, 16ul>*&, bool) [tiflash+124154501]
                \tdbms/src/DataStreams/IProfilingBlockInputStream.cpp:75
       0x821ead7\tDB::DM::RNRemoteSegmentThreadInputStream::readImpl(DB::PODArray<unsigned char, 4096ul, Allocator<false>, 15ul, 16ul>*&, bool) [tiflash+136440535]
                \tdbms/src/Storages/DeltaMerge/Remote/RNRemoteSegmentThreadInputStream.cpp:147
       0x821f944\tDB::DM::RNRemoteSegmentThreadInputStream::readImpl() [tiflash+136444228]
                \tdbms/src/Storages/DeltaMerge/Remote/RNRemoteSegmentThreadInputStream.h:80
       0x7667285\tDB::IProfilingBlockInputStream::read(DB::PODArray<unsigned char, 4096ul, Allocator<false>, 15ul, 16ul>*&, bool) [tiflash+124154501]
                \tdbms/src/DataStreams/IProfilingBlockInputStream.cpp:75
       0x7666f75\tDB::IProfilingBlockInputStream::read() [tiflash+124153717]
                \tdbms/src/DataStreams/IProfilingBlockInputStream.cpp:43
       0x792642d\tDB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0, false>::Handler, (DB::StreamUnionMode)0>::loop(unsigned long, DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0, false>::Handler, (DB::StreamUnionMode)0>::WorkingInputs&) [tiflash+127034413]
                \tdbms/src/DataStreams/ParallelInputsProcessor.h:307
       0x792628d\tDB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0, false>::Handler, (DB::StreamUnionMode)0>::work(unsigned long, DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0, false>::Handler, (DB::StreamUnionMode)0>::WorkingInputs&) [tiflash+127033997]
                \tdbms/src/DataStreams/ParallelInputsProcessor.h:270
       0x7926202\tstd::__1::__function::__func<DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0, false>::Handler, (DB::StreamUnionMode)0>::process()::'lambda'(), std::__1::allocator<DB::ParallelInputsProcessor<DB::UnionBlockInputStream<(DB::StreamUnionMode)0, false>::Handler, (DB::StreamUnionMode)0>::process()::'lambda'()>, void ()>::operator()() [tiflash+127033858]
                \t/usr/local/bin/../include/c++/v1/__functional/function.h:345
       0x1d1de38\tauto DB::wrapInvocable<std::__1::function<void ()> >(bool, std::__1::function<void ()>&&)::'lambda'()::operator()() [tiflash+30531128]
                \tdbms/src/Common/wrapInvocable.h:36
       0x1d1df85\tstd::__1::packaged_task<void ()>::operator()() [tiflash+30531461]
                \t/usr/local/bin/../include/c++/v1/future:2089
       0x1c25fa3\tDB::DynamicThreadPool::executeTask(std::__1::unique_ptr<DB::IExecutableTask, std::__1::default_delete<DB::IExecutableTask> >&) [tiflash+29515683]
                \tdbms/src/Common/DynamicThreadPool.cpp:101
       0x1c25604\tDB::DynamicThreadPool::fixedWork(unsigned long) [tiflash+29513220]
                \tdbms/src/Common/DynamicThreadPool.cpp:115
       0x1c26b12\tvoid* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::thread DB::ThreadFactory::newThread<void (DB::DynamicThreadPool::*)(unsigned long), DB::DynamicThreadPool*, unsigned long&>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::DynamicThreadPool::*&&)(unsigned long), DB::DynamicThreadPool*&&, unsigned long&)::'lambda'(auto&&...), DB::DynamicThreadPool*, unsigned long> >(void*) [tiflash+29518610]
                \t/usr/local/bin/../include/c++/v1/thread:291
  0x7effabe46802\tstart_thread [libc.so.6+653314]
  0x7effabde6314\t__GI___clone [libc.so.6+258836]"] [source="MPP<query:<query_ts:1683181428993135345, local_query_id:32, server_id:3262309, start_ts:441235912519057409>,task_id:1>"] [thread_id=235]
```
### 4. What is your TiFlash version? (Required)
```
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                           |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.2.0-alpha
Edition: Community
Git Commit Hash: 7eff8ce629d00cf4ab1eeda82a1ecd5a4e394b02
Git Branch: heads/refs/tags/v7.2.0-alpha
UTC Build Time: 2023-05-03 14:33:44
GoVersion: go1.20.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #7414

Problem Summary:

### What is changed and how it works?

View duration type as int64 to read, and add an extra cast after read.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)

```
./bin/tiup-playground nightly --mode=tidb-disagg --disagg.s3_endpoint=xxxx:xxx --tiflash.binpath ../tiflash/tiflash/tiflash
```
	
```
create table if not exists test.t(a time(4));
insert into test.t values('700:10:10.123456');
insert into test.t values('-700:10:10.123456');
alter table test.t set tiflash replica 1;
set tidb_isolation_read_engines='tiflash'; select a from t;
set tidb_isolation_read_engines='tiflash'; select hour(a) from t;

create table t1(t varchar(100));
insert into test.t1 values('700:10:10.123456');
set tidb_isolation_read_engines='tiflash'; select t from t1;
set tidb_isolation_read_engines='tiflash'; select hour(t) from t1;
```
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp [hunk 1]
```diff
@@ -96,7 +95,8 @@ std::tuple<DM::ColumnDefinesPtr, size_t> genColumnDefinesForDisaggregatedRead(co
         const auto & column_info = table_scan.getColumns()[i];
         // Even if the id is pk_column or extra_table_id, we still output it as
         // a exchange receiver output column
-        const auto output_name = fmt::format("{}_{}", column_prefix, i);
+        const auto output_name = genNameForExchangeReceiver(i);
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp:98]:
```suggestion
        // Now the upper level seems treat disagg read as an ExchangeReceiver output, so
        // use this as output column prefix.
        const auto output_name = genNameForExchangeReceiver(i);
```

And remove line 88~89

Comment (JaySon-Huang) [reply dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp:98]: And remove line 88~89

File: dbms/src/Storages/StorageDisaggregatedRemote.cpp [hunk 2]
```diff
@@ -147,8 +148,64 @@ BlockInputStreams StorageDisaggregated::readFromWriteNode(
...
+    {
+        getColumnIDsFromExpr(expr, table_scan.getColumns(), col_id_set);
+    }
+    bool has_need_cast_column = false;
+    for (const auto & col : table_scan.getColumns())
+    {
+        if (col_id_set.contains(col.id))
+        {
+            need_cast_column.push_back(ExtraCastAfterTSMode::None);
+        }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/StorageDisaggregatedRemote.cpp:176]: can you explain why col.id is in col_id_set, then we don't need to add extra cast?

File: dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp [hunk 3]
```diff
@@ -85,18 +85,18 @@ NamesAndTypes genNamesAndTypes(const TiDBTableScan & table_scan, const StringRef
...
     for (Int32 i = 0; i < table_scan.getColumnSize(); ++i)
     {
         const auto & column_info = table_scan.getColumns()[i];
+        // Now the upper level seems treat disagg read as an ExchangeReceiver output, so
+        // use this as output column prefix.
         // Even if the id is pk_column or extra_table_id, we still output it as
         // a exchange receiver output column
-        const auto output_name = fmt::format("{}_{}", column_prefix, i);
+        const auto output_name = genNameForExchangeReceiver(i);
+        // TODO: Support generated column, which is a virtual column.
```
Comment (JaySon-Huang) [inline dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp:99]: Open an issue for it. Is there any known SQL that would cause this problem?

File: dbms/src/Storages/StorageDisaggregatedRemote.cpp (hunk 2 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/StorageDisaggregatedRemote.cpp:176]: For col in col_id_set, will add extra cast in storage layer.

File: dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp (hunk 3 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp:99]: Seems that mpp do not support virtual column at all, we can remove this TODO.

File: dbms/src/Storages/StorageDisaggregatedRemote.cpp (hunk 2 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/StorageDisaggregatedRemote.cpp:176]: Is it done in `StorageDeltaMerge::buildPushDownFilter`? Add some comments about this

**Review by JaySon-Huang — APPROVED** [review]
Rest LGTM

File: dbms/src/Storages/StorageDisaggregatedRemote.cpp (hunk 2 above)
Comment (Lloyd-Pottiger) [reply dbms/src/Storages/StorageDisaggregatedRemote.cpp:176]: yes, ok

**Review by breezewish — APPROVED** [review]
