### PR TITLE
Avoid data race in grpc alarm

### LINKED ISSUE #10107: heap-use-after-free error for ComputeServerRunner.testErrorMessage in TSAN
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
[2025-04-12T18:19:11.411Z] SUMMARY: ThreadSanitizer: heap-use-after-free /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/cpp/common/alarm.cc:45:12 in grpc::internal::AlarmImpl::FinalizeResult(void**, bool*)
[2025-04-12T18:19:11.411Z] ==================
[2025-04-12T18:19:11.411Z] ==================
[2025-04-12T18:19:11.411Z] WARNING: ThreadSanitizer: heap-use-after-free (pid=347146)
[2025-04-12T18:19:11.411Z]   Read of size 8 at 0x7b480012e6c0 by thread T2503:
[2025-04-12T18:19:11.411Z]     #0 std::__1::__function::__value_func<void (bool)>::~__value_func[abi:ue170006]() /usr/local/bin/../include/c++/v1/__functional/function.h:475:20 (gtests_dbms+0x130c4322)
[2025-04-12T18:19:11.411Z]     #1 std::__1::function<void (bool)>::~function() /usr/local/bin/../include/c++/v1/__functional/function.h:1155:43 (gtests_dbms+0x130c4322)
[2025-04-12T18:19:11.411Z]     #2 grpc::internal::AlarmImpl::~AlarmImpl() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/cpp/common/alarm.cc:43:26 (gtests_dbms+0x130c4322)
[2025-04-12T18:19:11.411Z]     #3 grpc::internal::AlarmImpl::~AlarmImpl() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/cpp/common/alarm.cc:43:25 (gtests_dbms+0x130c4322)
[2025-04-12T18:19:11.411Z]     #4 grpc::internal::AlarmImpl::Unref() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/cpp/common/alarm.cc:113:7 (gtests_dbms+0x130c43d4)
[2025-04-12T18:19:11.411Z]     #5 grpc::internal::AlarmImpl::FinalizeResult(void**, bool*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/cpp/common/alarm.cc:46:5 (gtests_dbms+0x130c43d4)
[2025-04-12T18:19:11.411Z]     #6 grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/cpp/common/completion_queue_cc.cc:157:26 (gtests_dbms+0x130c78d8)
[2025-04-12T18:19:11.411Z]     #7 grpc::CompletionQueue::Next(void**, bool*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:185:13 (gtests_dbms+0xf372cb7)
[2025-04-12T18:19:11.411Z]     #8 DB::(anonymous namespace)::handleRpcs(grpc::ServerCompletionQueue*, std::__1::shared_ptr<DB::Logger> const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Server/FlashGrpcServerHolder.cpp:53:25 (gtests_dbms+0xf372cb7)
[2025-04-12T18:19:11.411Z]     #9 DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Server/FlashGrpcServerHolder.cpp:210:78 (gtests_dbms+0xf3729f3)
[2025-04-12T18:19:11.411Z]     #10 decltype(std::declval<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1 const&>()()) std::__1::__invoke[abi:ue170006]<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1 const&>(DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1 const&) /usr/local/bin/../include/c++/v1/__type_traits/invoke.h:340:25 (gtests_dbms+0xf3729f3)
[2025-04-12T18:19:11.411Z]     #11 std::__1::invoke_result<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1 const&>::type std::__1::invoke[abi:ue170006]<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1 const&>(DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1 const&) /usr/local/bin/../include/c++/v1/__functional/invoke.h:30:12 (gtests_dbms+0xf3729f3)
[2025-04-12T18:19:11.411Z]     #12 auto std::__1::thread DB::ThreadFactory::newThread<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1&&)::'lambda'(auto&&...)::operator()<>(auto&&...) const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/ThreadFactory.h:48:26 (gtests_dbms+0xf3729f3)
[2025-04-12T18:19:11.412Z]     #13 decltype(std::declval<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1>()()) std::__1::__invoke[abi:ue170006]<std::__1::thread DB::ThreadFactory::newThread<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1&&)::'lambda'(auto&&...)>(DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1&&) /usr/local/bin/../include/c++/v1/__type_traits/invoke.h:340:25 (gtests_dbms+0xf3729f3)
[2025-04-12T18:19:11.412Z]     #14 void std::__1::__thread_execute[abi:ue170006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::thread DB::ThreadFactory::newThread<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1&&)::'lambda'(auto&&...)>(std::__1::tuple<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1, std::__1::thread DB::ThreadFactory::newThread<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1&&)::'lambda'(auto&&...)>&, std::__1::__tuple_indices<>) /usr/local/bin/../include/c++/v1/__thread/thread.h:221:5 (gtests_dbms+0xf3729f3)
[2025-04-12T18:19:11.412Z]     #15 void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::thread DB::ThreadFactory::newThread<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1&&)::'lambda'(auto&&...)>>(void*) /usr/local/bin/../include/c++/v1/__thread/thread.h:232:5 (gtests_dbms+0xf3729f3)
[2025-04-12T18:19:11.412Z] 
[2025-04-12T18:19:11.412Z]   Previous write of size 8 at 0x7b480012e6c0 by main thread (mutexes: write M0):
[2025-04-12T18:19:11.412Z]     #0 operator delete(void*) /llvm-project/compiler-rt/lib/tsan/rtl/tsan_new_delete.cpp:126:3 (gtests_dbms+0x34535ff)
[2025-04-12T18:19:11.412Z]     #1 grpc::internal::AlarmImpl::~AlarmImpl() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/cpp/common/alarm.cc:43:25 (gtests_dbms+0x130c436d)
[2025-04-12T18:19:11.412Z]     #2 grpc::internal::AlarmImpl::Unref() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/cpp/common/alarm.cc:113:7 (gtests_dbms+0x130c3803)
[2025-04-12T18:19:11.412Z]     #3 grpc::internal::AlarmImpl::Destroy() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/cpp/common/alarm.cc:106:5 (gtests_dbms+0x130c3803)
[2025-04-12T18:19:11.412Z]     #4 grpc::Alarm::~Alarm() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/cpp/common/alarm.cc:155:48 (gtests_dbms+0x130c3803)
[2025-04-12T18:19:11.412Z]     #5 std::__1::pair<long const, grpc::Alarm>::~pair() /usr/local/bin/../include/c++/v1/__utility/pair.h:81:29 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.412Z]     #6 void std::__1::__destroy_at[abi:ue170006]<std::__1::pair<long const, grpc::Alarm>, 0>(std::__1::pair<long const, grpc::Alarm>*) /usr/local/bin/../include/c++/v1/__memory/construct_at.h:69:13 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.412Z]     #7 void std::__1::destroy_at[abi:ue170006]<std::__1::pair<long const, grpc::Alarm>, 0>(std::__1::pair<long const, grpc::Alarm>*) /usr/local/bin/../include/c++/v1/__memory/construct_at.h:104:5 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.412Z]     #8 void std::__1::allocator_traits<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<long, grpc::Alarm>, void*>>>::destroy[abi:ue170006]<std::__1::pair<long const, grpc::Alarm>, void, void>(std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<long, grpc::Alarm>, void*>>&, std::__1::pair<long const, grpc::Alarm>*) /usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:323:9 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.412Z]     #9 std::__1::__hash_table<std::__1::__hash_value_type<long, grpc::Alarm>, std::__1::__unordered_map_hasher<long, std::__1::__hash_value_type<long, grpc::Alarm>, std::__1::hash<long>, std::__1::equal_to<long>, true>, std::__1::__unordered_map_equal<long, std::__1::__hash_value_type<long, grpc::Alarm>, std::__1::equal_to<long>, std::__1::hash<long>, true>, std::__1::allocator<std::__1::__hash_value_type<long, grpc::Alarm>>>::__deallocate_node(std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<long, grpc::Alarm>, void*>*>*) /usr/local/bin/../include/c++/v1/__hash_table:1367:9 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.412Z]     #10 std::__1::__hash_table<std::__1::__hash_value_type<long, grpc::Alarm>, std::__1::__unordered_map_hasher<long, std::__1::__hash_value_type<long, grpc::Alarm>, std::__1::hash<long>, std::__1::equal_to<long>, true>, std::__1::__unordered_map_equal<long, std::__1::__hash_value_type<long, grpc::Alarm>, std::__1::equal_to<long>, std::__1::hash<long>, true>, std::__1::allocator<std::__1::__hash_value_type<long, grpc::Alarm>>>::~__hash_table() /usr/local/bin/../include/c++/v1/__hash_table:1324:5 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.412Z]     #11 std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>::~unordered_map[abi:ue170006]() /usr/local/bin/../include/c++/v1/unordered_map:1258:5 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.412Z]     #12 std::__1::pair<long const, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>::~pair() /usr/local/bin/../include/c++/v1/__utility/pair.h:81:29 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.413Z]     #13 void std::__1::__destroy_at[abi:ue170006]<std::__1::pair<long const, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>, 0>(std::__1::pair<long const, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>*) /usr/local/bin/../include/c++/v1/__memory/construct_at.h:69:13 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.413Z]     #14 void std::__1::destroy_at[abi:ue170006]<std::__1::pair<long const, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>, 0>(std::__1::pair<long const, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>*) /usr/local/bin/../include/c++/v1/__memory/construct_at.h:104:5 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.413Z]     #15 void std::__1::allocator_traits<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<long, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>, void*>>>::destroy[abi:ue170006]<std::__1::pair<long const, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>, void, void>(std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<long, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>, void*>>&, std::__1::pair<long const, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>*) /usr/local/bin/../include/c++/v1/__memory/allocator_traits.h:323:9 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.413Z]     #16 std::__1::__hash_table<std::__1::__hash_value_type<long, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>, std::__1::__unordered_map_hasher<long, std::__1::__hash_value_type<long, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>, std::__1::hash<long>, std::__1::equal_to<long>, true>, std::__1::__unordered_map_equal<long, std::__1::__hash_value_type<long, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>, std::__1::equal_to<long>, std::__1::hash<long>, true>, std::__1::allocator<std::__1::__hash_value_type<long, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>>>::__deallocate_node(std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<long, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>, void*>*>*) /usr/local/bin/../include/c++/v1/__hash_table:1367:9 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.413Z]     #17 std::__1::__hash_table<std::__1::__hash_value_type<long, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>, std::__1::__unordered_map_hasher<long, std::__1::__hash_value_type<long, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>, std::__1::hash<long>, std::__1::equal_to<long>, true>, std::__1::__unordered_map_equal<long, std::__1::__hash_value_type<long, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>, std::__1::equal_to<long>, std::__1::hash<long>, true>, std::__1::allocator<std::__1::__hash_value_type<long, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>>>::clear() /usr/local/bin/../include/c++/v1/__hash_table:1594:9 (gtests_dbms+0x1176de74)
[2025-04-12T18:19:11.413Z]     #18 std::__1::unordered_map<long, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, std::__1::unordered_map<long, grpc::Alarm, std::__1::hash<long>, std::__1::equal_to<long>, std::__1::allocator<std::__1::pair<long const, grpc::Alarm>>>>>>::clear[abi:ue170006]() /usr/local/bin/../include/c++/v1/unordered_map:1454:42 (gtests_dbms+0x11761b83)
[2025-04-12T18:19:11.413Z]     #19 DB::MPPTaskManager::abortMPPGather(DB::MPPGatherId const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::AbortType) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Mpp/MPPTaskManager.cpp:320:33 (gtests_dbms+0x11761b83)
[2025-04-12T18:19:11.413Z]     #20 DB::FlashService::cancelMPPTaskForTest(mpp::CancelTaskRequest const*, mpp::CancelTaskResponse*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/FlashService.cpp:801:19 (gtests_dbms+0x1158f23d)
[2025-04-12T18:19:11.413Z]     #21 DB::tests::MockComputeServerManager::cancelGather(DB::MPPGatherId const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Debug/MockComputeServerManager.cpp:133:40 (gtests_dbms+0xf6611be)
[2025-04-12T18:19:11.413Z]     #22 DB::tests::ComputeServerRunner_testErrorMessage_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/tests/gtest_compute_server.cpp:1416:54 (gtests_dbms+0x3b0dafd)
[2025-04-12T18:19:11.413Z]     #23 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xe1552f9)
[2025-04-12T18:19:11.413Z]     #24 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xe1552f9)
[2025-04-12T18:19:11.413Z]     #25 testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5 (gtests_dbms+0xe12aa63)
[2025-04-12T18:19:11.413Z]     #26 testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xe12c27e)
[2025-04-12T18:19:11.414Z]     #27 testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xe12d263)
[2025-04-12T18:19:11.414Z]     #28 testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xe13f67a)
[2025-04-12T18:19:11.414Z]     #29 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xe15680d)
[2025-04-12T18:19:11.414Z]     #30 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xe15680d)
[2025-04-12T18:19:11.414Z]     #31 testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xe13ef44)
[2025-04-12T18:19:11.414Z]     #32 RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x7415a78)
[2025-04-12T18:19:11.414Z]     #33 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:118:16 (gtests_dbms+0x7415a78)
[2025-04-12T18:19:11.414Z] 
[2025-04-12T18:19:11.414Z]   Mutex M0 (0x7b440118bba0) created at:
[2025-04-12T18:19:11.414Z]     #0 pthread_mutex_lock /llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1339:3 (gtests_dbms+0x33cd25b)
[2025-04-12T18:19:11.414Z]     #1 std::__1::mutex::lock() <null> (libc++.so.1+0x8f7c5)
[2025-04-12T18:19:11.414Z]     #2 DB::FlashService::cancelMPPTaskForTest(mpp::CancelTaskRequest const*, mpp::CancelTaskResponse*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/FlashService.cpp:801:19 (gtests_dbms+0x1158f23d)
[2025-04-12T18:19:11.414Z]     #3 DB::tests::MockComputeServerManager::cancelGather(DB::MPPGatherId const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Debug/MockComputeServerManager.cpp:133:40 (gtests_dbms+0xf6611be)
[2025-04-12T18:19:11.414Z]     #4 DB::tests::ComputeServerRunner_testErrorMessage_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/tests/gtest_compute_server.cpp:1416:54 (gtests_dbms+0x3b0dafd)
[2025-04-12T18:19:11.414Z]     #5 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xe1552f9)
[2025-04-12T18:19:11.414Z]     #6 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xe1552f9)
[2025-04-12T18:19:11.414Z]     #7 testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5 (gtests_dbms+0xe12aa63)
[2025-04-12T18:19:11.414Z]     #8 testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xe12c27e)
[2025-04-12T18:19:11.414Z]     #9 testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xe12d263)
[2025-04-12T18:19:11.414Z]     #10 testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xe13f67a)
[2025-04-12T18:19:11.414Z]     #11 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xe15680d)
[2025-04-12T18:19:11.414Z]     #12 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xe15680d)
[2025-04-12T18:19:11.414Z]     #13 testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xe13ef44)
[2025-04-12T18:19:11.414Z]     #14 RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x7415a78)
[2025-04-12T18:19:11.414Z]     #15 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:118:16 (gtests_dbms+0x7415a78)
[2025-04-12T18:19:11.414Z] 
[2025-04-12T18:19:11.414Z]   Thread T2503 'async_poller' (tid=405374, running) created by main thread at:
[2025-04-12T18:19:11.414Z]     #0 pthread_create /llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1020:3 (gtests_dbms+0x33cb55b)
[2025-04-12T18:19:11.414Z]     #1 std::__1::__libcpp_thread_create[abi:ue170006](unsigned long*, void* (*)(void*), void*) /usr/local/bin/../include/c++/v1/__threading_support:371:10 (gtests_dbms+0xf370f05)
[2025-04-12T18:19:11.414Z]     #2 std::__1::thread::thread<std::__1::thread DB::ThreadFactory::newThread<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1&&)::'lambda'(auto&&...)&, void>(DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1&&) /usr/local/bin/../include/c++/v1/__thread/thread.h:248:16 (gtests_dbms+0xf370f05)
[2025-04-12T18:19:11.414Z]     #3 std::__1::thread DB::ThreadFactory::newThread<DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_1&&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/ThreadFactory.h:50:16 (gtests_dbms+0xf370f05)
[2025-04-12T18:19:11.414Z]     #4 DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Server/FlashGrpcServerHolder.cpp:210:17 (gtests_dbms+0xf370f05)
[2025-04-12T18:19:11.414Z]     #5 std::__1::__unique_if<DB::FlashGrpcServerHolder>::__unique_single std::__1::make_unique[abi:ue170006]<DB::FlashGrpcServerHolder, DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig&, std::__1::shared_ptr<DB::Logger> const&>(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig&, std::__1::shared_ptr<DB::Logger> const&) /usr/local/bin/../include/c++/v1/__memory/unique_ptr.h:689:30 (gtests_dbms+0xf6608ed)
[2025-04-12T18:19:11.415Z]     #6 DB::tests::MockComputeServerManager::startServers(std::__1::shared_ptr<DB::Logger> const&, int) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Debug/MockComputeServerManager.cpp:70:40 (gtests_dbms+0xf6608ed)
[2025-04-12T18:19:11.415Z]     #7 DB::tests::MPPTaskTestUtils::startServers(unsigned long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/MPPTaskTestUtils.cpp:84:42 (gtests_dbms+0x77b42d8)
[2025-04-12T18:19:11.415Z]     #8 DB::tests::ComputeServerRunner_testErrorMessage_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/tests/gtest_compute_server.cpp:1370:5 (gtests_dbms+0x3b0bc71)
[2025-04-12T18:19:11.415Z]     #9 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xe1552f9)
[2025-04-12T18:19:11.415Z]     #10 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xe1552f9)
[2025-04-12T18:19:11.415Z]     #11 testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5 (gtests_dbms+0xe12aa63)
[2025-04-12T18:19:11.415Z]     #12 testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xe12c27e)
[2025-04-12T18:19:11.415Z]     #13 testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xe12d263)
[2025-04-12T18:19:11.415Z]     #14 testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xe13f67a)
[2025-04-12T18:19:11.415Z]     #15 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xe15680d)
[2025-04-12T18:19:11.415Z]     #16 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xe15680d)
[2025-04-12T18:19:11.415Z]     #17 testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xe13ef44)
[2025-04-12T18:19:11.415Z]     #18 RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x7415a78)
[2025-04-12T18:19:11.415Z]     #19 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:118:16 (gtests_dbms+0x7415a78)
[2025-04-12T18:19:11.415Z] 
[2025-04-12T18:19:11.415Z] SUMMARY: ThreadSanitizer: heap-use-after-free /usr/local/bin/../include/c++/v1/__functional/function.h:475:20 in std::__1::__function::__value_func<void (bool)>::~__value_func[abi:ue170006]()
```

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #10107

Problem Summary:

In current implementation, `Alarm` is hold by `MPPGatherTaskSet`, and in `MPPTaskManager::abortMPPGather`, all the `Alarm` will be deconstructed since it call `gather_task_set->alarms.clear();`
But when `gather_task_set->alarms.clear();` is called, the `EstablishCallData` may still inside grpc's core, and it hold a raw pointer of `AlarmImpl`, although inside `AlarmImpl`, it use atomic to try to make it thread-safe
```
 void Ref() { gpr_ref(&refs_); }
  void Unref() {
    if (gpr_unref(&refs_)) {
      delete this;
    }
  }
```
But `Unref/Ref` is not thread safe because in grpc's implementation, if `EstablishCallData` is put back to grpc's core, it does not call `Ref` immediately, instead, looks like grpc only call `Ref` if some event happens:
```
 void Set(::grpc::CompletionQueue* cq, gpr_timespec deadline, void* tag) {
    grpc_core::ApplicationCallbackExecCtx callback_exec_ctx;
    grpc_core::ExecCtx exec_ctx;
    GRPC_CQ_INTERNAL_REF(cq->cq(), "alarm");
    cq_ = cq->cq();
    tag_ = tag;
    GPR_ASSERT(grpc_cq_begin_op(cq_, this));
    GRPC_CLOSURE_INIT(
        &on_alarm_,
        [](void* arg, grpc_error_handle error) {
          // queue the op on the completion queue
          AlarmImpl* alarm = static_cast<AlarmImpl*>(arg);
          alarm->Ref();
          // Preserve the cq and reset the cq_ so that the alarm
          // can be reset when the alarm tag is delivered.
          grpc_completion_queue* cq = alarm->cq_;
          alarm->cq_ = nullptr;
          grpc_cq_end_op(
              cq, alarm, error,
              [](void* /*arg*/, grpc_cq_completion* /*completion*/) {}, arg,
              &alarm->completion_);
          GRPC_CQ_INTERNAL_UNREF(cq, "alarm");
        },
        this, grpc_schedule_on_exec_ctx);
    grpc_timer_init(&timer_, grpc_timespec_to_millis_round_up(deadline),
                    &on_alarm_);
  }
```
So there is a case that 2 threads try to delete the AlarmImpl concurrently.
|Time      | thread 1      | thread 2 |
|--------| ----------- | ----------- |
|        1     | call `gpr_unref(&refs_)`      |        |
|        2      | `gpr_unref(&refs_)` return true(refs is 0)   |        |
|       3     |                    | call `Ref()`   |
|       4    | call `delete this` |               |
|       5    |                     | call `Unref()`, and it will also try to delete `this` |
### What is changed and how it works?
This pr let `EstablishCallData` to hold the alarm, so it will never be constructed when `EstablishCallData` is inside grpc's core.
```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/EstablishCall.h [hunk 1]
```diff
@@ -95,6 +96,8 @@ class EstablishCallData final
     grpc::ServerContext * getGrpcContext() { return &ctx; }
 
     String getResourceGroupName() const { return resource_group_name; }
+    grpc::Alarm * getAlarm();
```
Comment (gengliqi) [inline dbms/src/Flash/EstablishCall.h:99]: Better to use a reference instead of a pointer because this pointer is always not null.

Comment (windtalker) [reply dbms/src/Flash/EstablishCall.h:99]: Can't use reference here because we need to store it in a std::unordered_map in `MPPTaskManager`

Comment (gengliqi) [reply dbms/src/Flash/EstablishCall.h:99]: `std::reference_wrapper` can be used to store a reference in `unordered_map`

Comment (windtalker) [reply dbms/src/Flash/EstablishCall.h]: Done

**Review by gengliqi — APPROVED** [review]

**Review by guo-shaoge — APPROVED** [review]
