### PR TITLE
Fix "lost cancel" for mpp query

### LINKED ISSUE #6727: Cache the CancelMPPTask request if task does not exist
## Enhancement

It's an optimization for a corner case.
Suppose a query has failed on some TiFlash nodes very quickly or TiDB receives a cancel request from a MySQL client very quickly. 
In that case, it's possible that some TiFlash nodes can receive a `CancelMPPTask` request before `EstablishMPPConnection`.
Then these tasks on TiFlash nodes will be canceled after running for sometime.

In normal cases, it's not a problem.
However, if the client keeps sending this query many times, many tasks will continue to accumulate to a large amount, which may affect other normal queries.
We can introduce an LRU cache to alleviate this problem.

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: ref #7587, close #6727

Problem Summary:

### What is changed and how it works?
When TiDB cancel a mpp query, there is a chance that the `cancel` is lost:
| time | TiDB | TiFlash |
|-----|------|---------|
| t1 | Send Disptach MPPTask to TiFlash| Dispatch request is not received yet |
| t2 | Send CancelMPPTask request to TiFlash| Received CancelMPPTask, and found nothing to cancel |
| t3 |   | Receive Dispatch request of t1, then the cancel is lost | 

This pr add a `AbortedMPPGatherCache` to avoid this cancel lost
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by SeaRise** [comment]
And close https://github.com/pingcap/tiflash/issues/6727?

File: dbms/src/Flash/Mpp/MPPTaskManager.h [hunk 1]
```diff
@@ -54,6 +54,35 @@ struct MPPQueryTaskSet
...
+    AbortedMPPGatherCache(size_t capacity_)
+        : capacity(capacity_)
+    {}
+    bool exists(const MPPGatherId & id)
+    {
+        return gather_ids_set.find(id) != gather_ids_set.end();
+    }
+    void add(const MPPGatherId & id)
+    {
+        if (gather_ids_set.size() >= capacity && gather_ids_set.find(id) == gather_ids_set.end())
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/MPPTaskManager.h:75]: It looks like L81 also needs to check `gather_ids_set.find(id) == gather_ids_set.end()` first
```suggestion
        if (gather_ids_set.find(id) == gather_ids_set.end())
            return;
        if (gather_ids_set.size() >= capacity)
```

Comment (SeaRise) [reply dbms/src/Flash/Mpp/MPPTaskManager.h:75]: Or it is only written in this way, the duplicate id will also enter the cache, but the existing entry will not be eliminated?

File: dbms/src/Flash/Mpp/MPPTaskId.h [hunk 2]
```diff
@@ -55,6 +55,27 @@ struct MPPQueryIdHash
     size_t operator()(MPPQueryId const & mpp_query_id) const noexcept;
 };
 
+/// A MPP query has one or more MPPGathers, each mpp gather has one or more MPPTasks. The mpp tasks in different mpp gathers are independent
+/// to each other, so theoretically speaking, the smallest cancel/retry unit of MPP query could be MPPGather. However, MPPGathers belong to
+/// the same MPP query could have dependence to each other(e.g. for query A join B, if the join is not supported in TiFlash, TiDB will generate
+/// two mpp gathers, one is reading from A and the other is reading from B, the probe side's mpp gather depends on the build side's mpp gather),
+/// so the smallest scheduling unit in TiFlash is still the MPP query
+struct MPPGatherId
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/MPPTaskId.h:63]: I'm a little confused, isn't the current MPPQueryId at the gather level?

Comment (SeaRise) [reply dbms/src/Flash/Mpp/MPPTaskId.h:63]: As mentioned in the case, if there are gather1 join gather2, will gather2 be cancelled when gather1 is cancelled due to limit? Because the cancellation is based on MPPQueryId.

Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTaskId.h:63]: Currently, the cancel unit is MPPQuery, but we can implement mpp gather level's cancel. In this pr, all the `gather_id` is hard coded as 0, which mean even for `A join B`, TiFlash still get only one MPPGather

Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTaskId.h:63]: Add more comments.

Comment (SeaRise) [reply dbms/src/Flash/Mpp/MPPTaskId.h]: ok

File: dbms/src/Flash/Mpp/MPPTaskManager.h (hunk 1 above)
Comment (yibin87) [reply dbms/src/Flash/Mpp/MPPTaskManager.h:75]: Seems duplicated gather id will cause duplicate ids in gather_ids, a little strange

File: dbms/src/Flash/Mpp/tests/gtest_aborted_mpp_gather_cache.cpp [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+#include <Flash/Mpp/MPPTaskManager.h>
+#include <TestUtils/TiFlashTestBasic.h>
+#include <gtest/gtest.h>
+
+
+namespace DB
+{
+namespace tests
+{
+class TestAbortedMPPGatherCache : public testing::Test
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/tests/gtest_aborted_mpp_gather_cache.cpp:24]: It looks like we can construct the case described in pr in `gtest_compute_server.cpp`.
```
TEST_F(ComputeServerRunner, xxx)
try
{
    WRAP_FOR_SERVER_TEST_BEGIN
    startServers(4);
    {
        auto [query_id, holder] = prepareMPPStreams(context
                                                     .scan("test_db", "test_table_1")
                                                     .aggregation({Max(col("s1"))}, {col("s2"), col("s3")})
                                                     .project({"max(s1)"}));
        MockComputeServerManager::instance().cancelQuery(query_id);
       EXPECT_TRUE(!assertQueryActive(query_id)); 
       holder.runMPPTasks();
        EXPECT_TRUE(assertQueryCancelled(query_id));
    }
    WRAP_FOR_SERVER_TEST_END
}
CATCH
```

Comment (SeaRise) [reply dbms/src/Flash/Mpp/tests/gtest_aborted_mpp_gather_cache.cpp:24]: just an option

Comment (windtalker) [reply dbms/src/Flash/Mpp/tests/gtest_aborted_mpp_gather_cache.cpp:24]: OK, I've added a test in `gtest_compute_server.cpp`

**Review by SeaRise — APPROVED** [review]
lgtm

**Review by yibin87 — APPROVED** [review]
LGTM

**Review by yibin87 — APPROVED** [review]
LGTM

**Review by SeaRise — APPROVED** [review]

**Review by SeaRise — APPROVED** [review]

**Review by yibin87 — APPROVED** [review]
LGTM
