### PR TITLE
Fixing race condition in ThreadPoolImpl​

### LINKED ISSUE #10082: IOThreadPool.TaskChain of unit-tests may sometimes failed
```
[0;32m[       OK ] [mIOThreadPool.TaskChain (21764 ms)
[0;32m[----------] [m1 test from IOThreadPool (21764 ms total)

[0;32m[----------] [mGlobal test environment tear-down
[0;32m[==========] [m1 test from 1 test case ran. (21764 ms total)
[0;32m[  PASSED  ] [m1 test.
[2025/04/01 14:24:27.646 +08:00] [INFO] [SegmentReader.cpp:60] ["Pop fail, stop=true"] [thread_id=3]
[2025/04/01 14:24:27.650 +08:00] [INFO] [SegmentReader.cpp:60] ["Pop fail, stop=true"] [thread_id=2]
[2025/04/01 14:24:27.650 +08:00] [DEBUG] [SegmentReader.cpp:45] [Stopped] [thread_id=1]
[2025/04/01 14:24:27.651 +08:00] [DEBUG] [SegmentReader.cpp:45] [Stopped] [thread_id=1]
[2025/04/01 14:24:27.652 +08:00] [INFO] [SegmentReader.cpp:60] ["Pop fail, stop=true"] [thread_id=4]
[2025/04/01 14:24:27.654 +08:00] [INFO] [SegmentReader.cpp:60] ["Pop fail, stop=true"] [thread_id=5]
[2025/04/01 14:24:27.656 +08:00] [DEBUG] [SegmentReader.cpp:45] [Stopped] [thread_id=1]
[2025/04/01 14:24:27.656 +08:00] [DEBUG] [SegmentReader.cpp:45] [Stopped] [thread_id=1]
[2025/04/01 14:24:27.656 +08:00] [INFO] [LocalIndexerScheduler.cpp:70] ["LocalIndexerScheduler is shutting down. Waiting scheduler and tasks to finish..."] [thread_id=1]
[2025/04/01 14:24:27.657 +08:00] [INFO] [LocalIndexerScheduler.cpp:85] ["LocalIndexerScheduler is shutdown."] [thread_id=1]
[2025/04/01 14:24:27.657 +08:00] [INFO] [JointThreadAllocInfo.cpp:194] ["Stop collecting thread alloc metrics"] [thread_id=1]
[2025/04/01 14:24:27.657 +08:00] [INFO] [JointThreadAllocInfo.cpp:205] ["JointThreadInfoJeallocMap shutdown, wait thread alloc monitor join"] [thread_id=1]
[2025/04/01 14:24:27.657 +08:00] [INFO] [LocalIndexerScheduler.cpp:94] ["LocalIndexerScheduler is destroyed"] [thread_id=1]
[2025/04/01 14:24:27.779 +08:00] [INFO] [KVStore.cpp:419] ["Destroy KVStore"] [thread_id=1]
[2025/04/01 14:24:27.779 +08:00] [INFO] [ReadIndex.cpp:388] ["KVStore shutdown, deleting read index worker"] [thread_id=1]
[2025/04/01 14:24:27.779 +08:00] [INFO] [KVStore.cpp:421] ["Destroy KVStore Finished"] [thread_id=1]
[2025/04/01 14:24:27.780 +08:00] [INFO] [JointThreadAllocInfo.cpp:194] ["Stop collecting thread alloc metrics"] [thread_id=1]
Received signal Segmentation fault

      0x12f9564e	StackTrace::StackTrace() [gtests_dbms+318330446]
       0x8adc674	fault_signal_handler(int) [gtests_dbms+145606260]
  0x7ff1f39aa5b0	<unknown symbol> [libc.so.6+320944]
  0x7ff1f4e7878c	std::__1::__libcpp_thread_get_id[abi:ue170006](unsigned long const*) [libc++.so.1+395148]
  0x7ff1f4e9e935	std::__1::__libcpp_thread_isnull[abi:ue170006](unsigned long const*) [libc++.so.1+551221]
  0x7ff1f4e9e970	std::__1::thread::join() [libc++.so.1+551280]
      0x13024346	DB::ThreadPoolImpl<std::__1::thread>::finalize() [gtests_dbms+318915398]
      0x13024249	DB::ThreadPoolImpl<std::__1::thread>::~ThreadPoolImpl() [gtests_dbms+318915145]
      0x13022d39	DB::GlobalThreadPool::~GlobalThreadPool() [gtests_dbms+318909753]
      0x1302851b	std::__1::default_delete<DB::GlobalThreadPool>::operator()[abi:ue170006](DB::GlobalThreadPool*) const [gtests_dbms+318932251]
      0x1302751c	std::__1::unique_ptr<DB::GlobalThreadPool, std::__1::default_delete<DB::GlobalThreadPool>>::reset[abi:ue170006](DB::GlobalThreadPool*) [gtests_dbms+318928156]
      0x13027489	std::__1::unique_ptr<DB::GlobalThreadPool, std::__1::default_delete<DB::GlobalThreadPool>>::~unique_ptr[abi:ue170006]() [gtests_dbms+318928009]
  0x7ff1f39acccc	__run_exit_handlers [libc.so.6+330956]
  0x7ff1f39ace00	exit [libc.so.6+331264]
  0x7ff1f39967ec	__libc_start_main [libc.so.6+239596]
       0x4e9a8ee	_start [gtests_dbms+82421998]
[950/3130] IOThreadPool.TaskChain returned/aborted with exit code -11 (24823 ms)
```

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #10082

The code of [UniThreadPool.cpp#L355-L356]( https://github.com/pingcap/tiflash/blob/ea839053051550e377aaa50bc7d8e6e4241550a0/dbms/src/Common/UniThreadPool.cpp#L355-L356) and [UniThreadPool.cpp#L256-L257](https://github.com/pingcap/tiflash/blob/ea839053051550e377aaa50bc7d8e6e4241550a0/dbms/src/Common/UniThreadPool.cpp#L256-L257) may run concurrently, it is not safe.

1. When `IOThreadPool.TaskChain` is finished, it just means [UniThreadPool.cpp#L321](https://github.com/pingcap/tiflash/blob/ea839053051550e377aaa50bc7d8e6e4241550a0/dbms/src/Common/UniThreadPool.cpp#L321) is finished.
2. The process of unit-tests is going to exist: the main-thread is calling the destructor of GlobalThreadPool and eventually run into [UniThreadPool.cpp#L256-L257](https://github.com/pingcap/tiflash/blob/ea839053051550e377aaa50bc7d8e6e4241550a0/dbms/src/Common/UniThreadPool.cpp#L256-L257).
3. Work threads may run into [UniThreadPool.cpp#L355-L356](https://github.com/pingcap/tiflash/blob/ea839053051550e377aaa50bc7d8e6e4241550a0/dbms/src/Common/UniThreadPool.cpp#L355-L356).

### What is changed and how it works?

```commit-message

```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Common/UniThreadPool.cpp [hunk 1]
```diff
@@ -350,7 +350,7 @@ void ThreadPoolImpl<Thread>::worker(typename std::list<Thread>::iterator thread_
             std::lock_guard lock(mutex);
             --scheduled_jobs;
 
-            if (threads.size() > scheduled_jobs + max_free_threads)
+            if (!shutdown && threads.size() > scheduled_jobs + max_free_threads)
             {
                 thread_it->detach();
```
Comment (JaySon-Huang) [inline dbms/src/Common/UniThreadPool.cpp:355]:
```suggestion
            // If shutdown is called, let the `finalize` clear all threads
            // Otherwise reduce the allocated threads number according to the running jobs and `max_free_threads`
            if (!shutdown && threads.size() > scheduled_jobs + max_free_threads)
            {
                thread_it->detach();
```

**Review by JaySon-Huang — COMMENTED** [review]
LGTM with some adding comments

**Review by JaySon-Huang — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]
