### PR TITLE
fix that the result of expression cast(Real/Decimal)AsTime is inconsistent with TiDB

### LINKED ISSUE #3779: cast double as datetime  is not compatible with tidb/mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)
```
mysql> select cast(111 as datetime);
+-----------------------+
| cast(111 as datetime) |
+-----------------------+
| 2000-01-11 00:00:00   |
+-----------------------+
1 row in set (0.00 sec)

mysql> select cast(111.1 as datetime);
+-------------------------+
| cast(111.1 as datetime) |
+-------------------------+
| 2000-01-11 00:00:00     |
+-------------------------+
1 row in set (0.00 sec)

mysql> select cast(111.1 as datetime) from tdate;
+-------------------------+
| cast(111.1 as datetime) |
+-------------------------+
| 2000-01-11 00:00:00     |
+-------------------------+
1 row in set (0.00 sec)

mysql> set @@tidb_enforce_mpp=on;
Query OK, 0 rows affected (0.00 sec)

mysql> select cast(111.1 as datetime) from tdate;
+-------------------------+
| cast(111.1 as datetime) |
+-------------------------+
| NULL                    |
+-------------------------+
1 row in set (0.01 sec)

mysql> select cast(111 as datetime) from tdate;
+-----------------------+
| cast(111 as datetime) |
+-----------------------+
| 2000-01-11 00:00:00   |
+-----------------------+
1 row in set (0.01 sec)
```
### 4. What is your TiFlash version? (Required)
master

### PR DESCRIPTION
**Pull request by mengxin9014**
### What problem does this PR solve?

Issue Number: close #3779

Problem Summary:
fix that the result of expression casting real or decimal as time is inconsistent with mysql.
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix that the result of expression casting real or decimal as time is inconsistent with mysql.
```

### CODE REVIEW

File: dbms/src/Common/MyTime.cpp [hunk 1]
```diff
@@ -553,6 +553,15 @@ const String & MyTimeBase::monthName() const
...
 bool checkTimeValid(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
+{
+    if (year > 9999 || month <= 0 || month > 12 || day <= 0 || day > 31 || hour > 23 || minute > 59 || second > 59)
+    {
+        return false;
+    }
+    return day <= getLastDay(year, month);
+}
+
+bool checkTimeValidAllowMonthAndDayZero(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
```
Comment (yibin87) [inline dbms/src/Common/MyTime.cpp:564]: Better to reuse checkTimeValid, to avoid so many detailed check twice.

File: dbms/src/Common/MyTime.cpp [hunk 2]
```diff
@@ -616,6 +736,24 @@ std::pair<Field, bool> parseMyDateTimeAndJudgeIsDate(const String & str, int8_t
     case 1:
     {
         size_t l = seps[0].size();
+        if (isFloat)
```
Comment (yibin87) [inline dbms/src/Common/MyTime.cpp:739]: Better to add comments to explain why float is special, like an example.

File: dbms/src/Common/MyTime.cpp [hunk 3]
```diff
@@ -1097,26 +1244,29 @@ bool MyTimeBase::isValid(bool allow_zero_in_date, bool allow_invalid_date) const
         }
     }
 
-    if (year >= 9999 || month > 12)
+    if (year > 9999 || month > 12)
```
Comment (yibin87) [inline dbms/src/Common/MyTime.cpp:1247]: why do we change behavior here?

Comment (mengxin9014) [reply dbms/src/Common/MyTime.cpp:1247]: Because cast(99991111.1111111 as datetime) is valid now,  and result is 9999-11-11.

File: dbms/src/Common/MyTime.cpp (hunk 1 above)
Comment (mengxin9014) [reply dbms/src/Common/MyTime.cpp:560]: done.

File: dbms/src/Common/MyTime.cpp (hunk 2 above)
Comment (mengxin9014) [reply dbms/src/Common/MyTime.cpp:736]: done.

File: dbms/src/Common/MyTime.cpp [hunk 4]
```diff
@@ -1097,26 +1241,29 @@ bool MyTimeBase::isValid(bool allow_zero_in_date, bool allow_invalid_date) const
...
         constexpr static UInt8 max_days_in_month[12] = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
         static auto is_leap_year = [](UInt16 _year) {
             return ((_year % 4 == 0) && (_year % 100 != 0)) || (_year % 400 == 0);
         };
-        max_day = max_days_in_month[month - 1];
-        if (month == 2 && is_leap_year(year))
+        if (allow_zero_in_date && month == 0)
         {
-            max_day = 29;
+            max_day = 31;
```
Comment (yibin87) [inline dbms/src/Common/MyTime.cpp:1258]: why change this

Comment (mengxin9014) [reply dbms/src/Common/MyTime.cpp:1258]: if month = 0,  the day can be 31.

File: dbms/src/Common/MyTime.cpp [hunk 5]
```diff
@@ -683,6 +818,10 @@ std::pair<Field, bool> parseMyDateTimeAndJudgeIsDate(const String & str, int8_t
         }
         if (l == 5 || l == 6 || l == 8)
         {
+            if (isFloat)
```
Comment (yibin87) [inline dbms/src/Common/MyTime.cpp:821]: Better to add a TODO item to refact this code, to remove these isFloat branches.

**Review by windtalker — APPROVED** [review]
LGTM
