### PR TITLE
KVStore: Enhance Parallel Prehandle

### LINKED ISSUE #8081: [Dynamic Region] TiFlash can't catch up with TiKV when there is only one big region pending prehandle
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #8081

Problem Summary:

### What is changed and how it works?

```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]

File: dbms/src/Storages/KVStore/KVStore.cpp [hunk 1]
```diff
@@ -448,6 +448,10 @@ size_t KVStore::getOngoingPrehandleTaskCount() const
 {
     return std::max(0, ongoing_prehandle_task_count.load());
 }
+size_t KVStore::getOngoingPrehandleSubtaskCount() const
+{
+    return std::max(0, prehandling_trace.ongoing_prehandle_subtask_count.load());
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/KVStore/KVStore.cpp:453]: No

File: dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp [hunk 2]
```diff
@@ -282,32 +284,35 @@ void SSTFilesToBlockInputStream::loadCFDataFromSST(
             (*p_process_keys_bytes) += (key.len + value.len);
             reader->next();
         }
+        auto sec = sw.elapsedMilliseconds();
         LOG_DEBUG(
             log,
             "Done loading all kvpairs, CF={} offset={} processed_bytes={} write_cf_offset={} region_id={} split_id={} "
-            "snapshot_index={}",
+            "snapshot_index={} elapsed_sec={} speed={}",
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp:291]: this print `elapsed_sec` with milliseconds, which is confusing...

Comment (JaySon-Huang) [reply dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp:291]: Will fix in https://github.com/pingcap/tiflash/pull/9153
