### PR TITLE
keep delete entry when dump snapshot

### LINKED ISSUE #5230: Can't find BlobStat with [blob_id=29]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

After some large transaction update and restart tiflash multiple times.

### 2. What did you expect to see? (Required)
TiFlash works normally.

### 3. What did you see instead (Required)
[2022/06/24 00:47:51.725 +00:00] [ERROR] [Exception.cpp:85] ["bool DB::Context::initializeGlobalStoragePoolIfNeed(const DB::PathPool &):Code: 49, e.displayText() = DB::Exception: Can't find BlobStat with [blob_id=29], e.what() = DB::Exception, Stack trace:\n\n\n       0x1ccfeae\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+30211758]\n                \tdbms/src/Common/Exception.h:41\n       0x7407fb7\tDB::PS::V3::BlobStore::BlobStats::blobIdToStat(unsigned long, bool) [tiflash+121667511]\n                \tdbms/src/Storages/Page/V3/BlobStore.cpp:1465\n       0x7426c2a\tDB::PS::V3::PageDirectoryFactory::createFromReader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::PS::V3::WALStoreReader>, std::__1::unique_ptr<DB::PS::V3::WALStore, std::__1::default_delete<DB::PS::V3::WALStore> >) [tiflash+121793578]\n                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:65\n       0x7425e31\tDB::PS::V3::PageDirectoryFactory::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::FileProvider>&, std::__1::shared_ptr<DB::PSDiskDelegator>&, DB::PS::V3::WALStore::Config) [tiflash+121790001]\n                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:34\n       0x741e95b\tDB::PS::V3::PageStorageImpl::restore() [tiflash+121760091]\n                \tdbms/src/Storages/Page/V3/PageStorageImpl.cpp:55\n       0x71d97bb\tDB::DM::GlobalStoragePool::restore() [tiflash+119379899]\n                \tdbms/src/Storages/DeltaMerge/StoragePool.cpp:120\n       0x6bc2cde\tDB::Context::initializeGlobalStoragePoolIfNeed(DB::PathPool const&) [tiflash+112995550]\n                \tdbms/src/Interpreters/Context.cpp:1674\n       0x1d2eb45\tDB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) [tiflash+30600005]\n                \tdbms/src/Server/Server.cpp:1144\n       0x7863c1a\tPoco::Util::Application::run() [tiflash+126237722]\n                \tcontrib/poco/Util/src/Application.cpp:335\n       0x786ac04\tPoco::Util::ServerApplication::run(int, char**) [tiflash+126266372]\n                \tcontrib/poco/Util/src/ServerApplication.cpp:618\n       0x1d403fb\tmainEntryClickHouseServer(int, char**) [tiflash+30671867]\n                \tdbms/src/Server/Server.cpp:1563\n       0x1cbe6ac\tmain [tiflash+30140076]\n                \tdbms/src/Server/main.cpp:179\n  0x7f0c87cfc083\t__libc_start_main [libc.so.6+147587]\n                \t/build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308\n       0x1ad9c29\t<unknown symbol> [tiflash+28154921]"] [thread_id=1]
[2022/06/24 00:47:51.853 +00:00] [ERROR] [<unknown>] ["Application:DB::Exception: Can't find BlobStat with [blob_id=29]"] [thread_id=1]
[2022/06/24 00:48:07.282 +00:00] [WARN] [StorageConfigParser.cpp:241] ["Application:The configuration \"path\" is deprecated. Check [storage] section for new style."] [thread_id=1]
[2022/06/24 00:48:09.473 +00:00] [ERROR] [Exception.cpp:85] ["bool DB::Context::initializeGlobalStoragePoolIfNeed(const DB::PathPool &):Code: 49, e.displayText() = DB::Exception: Can't find BlobStat with [blob_id=29], e.what() = DB::Exception, Stack trace:\n\n\n       0x1ccfeae\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+30211758]\n                \tdbms/src/Common/Exception.h:41\n       0x7407fb7\tDB::PS::V3::BlobStore::BlobStats::blobIdToStat(unsigned long, bool) [tiflash+121667511]\n                \tdbms/src/Storages/Page/V3/BlobStore.cpp:1465\n       0x7426c2a\tDB::PS::V3::PageDirectoryFactory::createFromReader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::PS::V3::WALStoreReader>, std::__1::unique_ptr<DB::PS::V3::WALStore, std::__1::default_delete<DB::PS::V3::WALStore> >) [tiflash+121793578]\n                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:65\n       0x7425e31\tDB::PS::V3::PageDirectoryFactory::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::FileProvider>&, std::__1::shared_ptr<DB::PSDiskDelegator>&, DB::PS::V3::WALStore::Config) [tiflash+121790001]\n                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:34\n       0x741e95b\tDB::PS::V3::PageStorageImpl::restore() [tiflash+121760091]\n                \tdbms/src/Storages/Page/V3/PageStorageImpl.cpp:55\n       0x71d97bb\tDB::DM::GlobalStoragePool::restore() [tiflash+119379899]\n                \tdbms/src/Storages/DeltaMerge/StoragePool.cpp:120\n       0x6bc2cde\tDB::Context::initializeGlobalStoragePoolIfNeed(DB::PathPool const&) [tiflash+112995550]\n                \tdbms/src/Interpreters/Context.cpp:1674\n       0x1d2eb45\tDB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) [tiflash+30600005]\n                \tdbms/src/Server/Server.cpp:1144\n       0x7863c1a\tPoco::Util::Application::run() [tiflash+126237722]\n                \tcontrib/poco/Util/src/Application.cpp:335\n       0x786ac04\tPoco::Util::ServerApplication::run(int, char**) [tiflash+126266372]\n                \tcontrib/poco/Util/src/ServerApplication.cpp:618\n       0x1d403fb\tmainEntryClickHouseServer(int, char**) [tiflash+30671867]\n                \tdbms/src/Server/Server.cpp:1563\n       0x1cbe6ac\tmain [tiflash+30140076]\n                \tdbms/src/Server/main.cpp:179\n  0x7f4fd72e2083\t__libc_start_main [libc.so.6+147587]\n                \t/build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308\n       0x1ad9c29\t<unknown symbol> [tiflash+28154921]"] [thread_id=1]
[2022/06/24 00:48:09.629 +00:00] [ERROR] [<unknown>] ["Application:DB::Exception: Can't find BlobStat with [blob_id=29]"] [thread_id=1]

### 4. What is your TiFlash version? (Required)
master

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #5230 

Problem Summary: when enable ps v3, after doing large transaction update and restart tiflash multiple times, tiflash cannot restart correctly.

### What is changed and how it works?
Previously, when dump snapshot for PageDirectory, we will remove obsolete entries if it is marked deleted. But the entry may have an upsert entry in later wal file which is not included in the snapshot. So if we remove the delete mark for the entry, the later upsert entry cannot be deleted after restart.
So we keep the last valid entry and the delete entry when dump snapshot.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by flowbehappy — APPROVED** [review]

File: dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp [hunk 1]
```diff
@@ -1491,5 +1493,147 @@ try
...
+        WriteBatch batch;
+        batch.delPage(page_id0);
+        page_storage->write(std::move(batch));
+    }
+    {
+        WriteBatch batch;
+        batch.delPage(page_id1);
+        page_storage->write(std::move(batch));
+    }
+
```
Comment (jiaqizho) [inline dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp:1606]: So what if 
1. write page0 
2. ref page 0
3. create a snapshot0
4. del page0
5. write page0 
6. ref page 0
7. create a snapshot1
8. del page0
9. then do the same logic below.
will it still have problem?

File: dbms/src/Storages/Page/V3/BlobStore.cpp [hunk 2]
```diff
@@ -1068,26 +1068,10 @@ PageEntriesEdit BlobStore::gc(std::map<BlobFileId, PageIdAndVersionedEntries> &
     }
     LOG_FMT_INFO(log, "BlobStore gc will migrate {:.2f}MB into new Blobs", (1.0 * total_page_size / DB::MB));
 
-    const auto config_file_limit = config.file_limit_size.get();
```
[the remark this answers is not in the document]
Comment (lidezhu) [reply dbms/src/Storages/Page/V3/BlobStore.cpp:1071]: I think the declaration of variable should be close to its usage. The separation of declaration and usage by the definition of `write_blob` really make it hard to read the related code.

File: dbms/src/Storages/Page/V3/BlobStore.cpp [hunk 3]
```diff
@@ -1101,7 +1085,7 @@ PageEntriesEdit BlobStore::gc(std::map<BlobFileId, PageIdAndVersionedEntries> &
                 file_offset,
                 data_size,
                 total_page_size);
-            blob_file->write(data_beg, file_offset, data_size, write_limiter, /*background*/ true);
```
[the remark this answers is not in the document]
Comment (lidezhu) [reply dbms/src/Storages/Page/V3/BlobStore.cpp:1104]: `data_beg` is a name that takes me some time to think what it means because `beg` is a valid word and it's a little difficult to imagine that it's the abbreviation of `begin` . `data_pos` or `data_begin` is both ok for me.

[the remark this answers is not in the document]
Comment (JaySon-Huang) [reply dbms/src/Storages/Page/V3/BlobStore.cpp:1104]: `data_begin` LGTM

File: dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp [hunk 4]
```diff
@@ -34,7 +34,10 @@ PageDirectoryPtr PageDirectoryFactory::create(String storage_name, FileProviderP
     return createFromReader(storage_name, reader, std::move(wal));
 }
 
-PageDirectoryPtr PageDirectoryFactory::createFromReader(String storage_name, WALStoreReaderPtr reader, WALStorePtr wal)
+/// When create PageDirectory for dump snapshot, we should keep the last valid var_entry when it is deleted.
+/// Because there may be some upsert entry in later wal files, and we should keep the valid var_entry and the delete entry to delete the later upsert entry.
+/// And we don't restore the entries in blob store, because this PageDirectory is just read only for its entries.
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:39]: I think we should move these lines to `PageDirectory::tryDumpSnapshot`

File: dbms/src/Storages/Page/V3/PageDirectory.h [hunk 5]
```diff
@@ -358,11 +360,14 @@ class PageDirectory
...
 
-    bool tryDumpSnapshot(const ReadLimiterPtr & read_limiter = nullptr, const WriteLimiterPtr & write_limiter = nullptr);
+    bool tryDumpSnapshot(const ReadLimiterPtr & read_limiter = nullptr, const WriteLimiterPtr & write_limiter = nullptr, bool force = false);
 
     // Perform a GC for in-memory entries and return the removed entries.
     // If `return_removed_entries` is false, then just return an empty set.
-    PageEntriesV3 gcInMemEntries(bool return_removed_entries = true);
+    // When dump snapshot, we first load edit record from underlying wal files, and call gcInMemEntries to remove obsolete entries.
+    // But there may be some upsert entry in later wal files which are not included in the snapshot.
+    // So if the last valid var entry is deleted for some page, we need to keep them and its delete entry to reclaim possible future upsert entry.
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/PageDirectory.h:369]:
```suggestion
    // When dump snapshot, we need to keep the last valid entry. Check out `tryDumpSnapshot` for the reason.
```

**Review by JaySon-Huang — COMMENTED** [review]
Basically lgtm

File: dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp (hunk 4 above)
Comment (lidezhu) [reply dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp]: Fixed.

File: dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp (hunk 1 above)
Comment (JaySon-Huang) [reply dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp:1606]: Yes, the id won't be reused until it is totally deleted.

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Comment by JaySon-Huang** [comment]
We also need a cherry-pick on the release-6.1 branch?
