### PR TITLE
Fix hang for TestCTE.Concurrent test

### LINKED ISSUE #10636: Fail TSAN test: TestCTE.Concurrent hang forever
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/3102/pipeline/

In the tests, there were no useful logs other.
```
[2025-12-27T19:22:40.850Z] INTERRUPTED TESTS (1/3295):
[2025-12-27T19:22:40.850Z] Interrupted: /tiflash/gtests_dbms TestCTE.Concurrent
script returned exit code 254
```

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #10636

Problem Summary:

### What is changed and how it works?

```commit-message
In `waitForBlockAvailableForTest`, CTEReader will wait the wake of `cv_for_test`. However, we need to check if there are any available blocks before entering the wait or it will wait forever when there is no more block to be pushed.
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the issue that TestCTE.Concurrent may hang forever
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved synchronization across CTE operations to avoid deadlocks and reduce contention, enhancing stability and performance.
  * Revised wait/relock behavior to ensure safe locking order during concurrent access.

* **Tests**
  * Simplified test synchronization primitives and made test-access locking more consistent to improve test reliability.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: dbms/src/Operators/CTE.h [hunk 1]
```diff
@@ -184,6 +183,8 @@ class CTE
 
     CTEPartition & getPartitionForTest(size_t partition_idx) { return this->partitions[partition_idx]; }
 
+    std::shared_mutex * getRWLockForTest() { return &(this->rw_lock); }
```
Comment (gengliqi) [inline dbms/src/Operators/CTE.h]: How about using a reference instead of a pointer?

File: dbms/src/Operators/CTEReader.cpp [hunk 2]
```diff
@@ -55,6 +56,16 @@ CTEOpStatus CTEReader::waitForBlockAvailableForTest(size_t partition_idx)
...
         }
+        rw_lock.unlock();
+        partition.cv_for_test->wait(lock);
+        lock.unlock();
+
+        // ensure rw_lock to get lock first, or we will encounter deadlock
+        // For example: in `CTE::tryGetBlockAt`, we will lock rw_lock first then lock partition.mu.
+        // If locking partition.mu first here, `CTE::tryGetBlockAt` may have locked rw_lock. Then
+        // each of them needs to lock the other lock, but the other lock has been locked now.
+        rw_lock.lock();
```
Comment (gengliqi) [inline dbms/src/Operators/CTEReader.cpp:68]: Maybe add a sleep above this line of code?

File: dbms/src/Operators/CTE.h (hunk 1 above)
Comment (xzhangxian1008) [reply dbms/src/Operators/CTE.h]: > How about using a reference instead of a pointer?

done

File: dbms/src/Operators/CTEReader.cpp (hunk 2 above)
Comment (windtalker) [inline dbms/src/Operators/CTEReader.cpp:68]: it looks very weird to me to manually release and acquire lock after `wait`, why we need `rw_lock` here? Is it possible that we only hold `rw_lock` before while loop?

**Review by windtalker — APPROVED** [review]
lgtm
