### PR TITLE
Fix bug that mpp_task is not move to cancel thread due to llvm SOO

### LINKED ISSUE #5638: mpptask is not moved to cancel thread as expected in `MPPTaskManager::cancelMPPQuery`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
ref #5637 for details

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: ref #5095, close #5638

Problem Summary:

### What is changed and how it works?
After #5361, in `MPPTaskManager::cancelMPPQuery`, we try to move mpp task to the cancel thread so each mpp task can be destructed parallelly instead of be destructed one by one in `cancelMPPQuery` thread.
However, due to SOO in llvm(https://github.com/llvm/llvm-project/issues/32472), this move actaully failed, and there is a chance that mpp task is destructed inside the follow cancel loop:
https://github.com/pingcap/tiflash/blob/8404e6565e3ff2e47e50497550d838ea76e6e776/dbms/src/Flash/Mpp/MPPTaskManager.cpp#L102-L108

Destruct MPP inside the cancel loop means the task will be destructed before all mpp tasks are cancelled, this may cause some dead lock issues since there are some dependency between mpp tasks(especially in the case of local tunnel).

This pr fix this issue by 
- Use a Functor instead of lambda as a workaround of the SOO issues
- Save the moved Functor inside a vector to make sure mpp task never be destructed inside cancel loop, even if Functor move fails due to some unknown issues.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
run some random failpoint tests
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by gengliqi — APPROVED** [review]

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp [hunk 1]
```diff
@@ -70,6 +70,34 @@ MPPTaskPtr MPPTaskManager::findTaskWithTimeout(const mpp::TaskMeta & meta, std::
     return it->second;
 }
 
+static Poco::Logger * getLogger()
+{
+    static Poco::Logger * logger = &Poco::Logger::get("MPPTaskCancelFunctor");
+    return logger;
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/MPPTaskManager.cpp:76]: use `Logger::get("MPPTaskCancelFunctor", task->getId()->toString())`?

Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTaskManager.cpp:76]: I think we don't need to log task id here since it is not task specific, if move failed, all task's move will fail.

Comment (SeaRise) [reply dbms/src/Flash/Mpp/MPPTaskManager.cpp:76]: ok.
replace by `Logger::get("MPPTaskCancelFunctor)`?
Poco::Logger is deprecated in TiFlash.

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp [hunk 2]
```diff
@@ -97,14 +125,24 @@ void MPPTaskManager::cancelMPPQuery(UInt64 query_id, const String & reason)
...
+        // Note it is not acceptable to destruct `current_task` inside the loop, because destruct a mpp task before all
+        // other mpp tasks are cancelled may cause some deadlock issues, so `current_task` has to be moved to cancel thread.
+        // At first, we use std::move to move `current_task` to lambda like this:
+        // thread_manager->schedule(false, "CancelMPPTask", [task = std::move(current_task), &reason] { task->cancel(reason); });
+        // However, due to SOO in llvm(https://github.com/llvm/llvm-project/issues/32472), there is still a copy of `current_task`
+        // remaining in the current scope, as a workaround we add a wrap(MPPTaskCancelFunctor) here to make sure `current_task`
+        // can be moved to cancel thread. Meanwhile, also save the moved wrap in a vector to guarantee that even if cancel functors
+        // fail to move due to some other issues, it still does not destruct inside the loop
+        cancel_functors.push_back(MPPTaskCancelFunctor(std::move(current_task), reason));
+        thread_manager->schedule(false, "CancelMPPTask", std::move(cancel_functors[cancel_functors.size() - 1]));
```
Comment (yibin87) [inline dbms/src/Flash/Mpp/MPPTaskManager.cpp:145]: Maybe, take a consideration if any exception thrown during the for loop.

**Review by yibin87 — APPROVED** [review]
Others LGTM.

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp (hunk 1 above)
Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTaskManager.cpp:76]: OK

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp [hunk 3]
```diff
@@ -70,6 +70,34 @@ MPPTaskPtr MPPTaskManager::findTaskWithTimeout(const mpp::TaskMeta & meta, std::
...
+    static LoggerPtr logger = Logger::get("MPPTaskCancelFunctor");
+    return logger;
+}
+
+class MPPTaskCancelFunctor
+{
+public:
+    MPPTaskPtr task;
+    String reason;
+    MPPTaskCancelFunctor(const MPPTaskCancelFunctor & other)
```
Comment (fuzhe1989) [inline dbms/src/Flash/Mpp/MPPTaskManager.cpp:84]: why not declare it as `delete`?

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp [hunk 4]
```diff
@@ -97,14 +125,32 @@ void MPPTaskManager::cancelMPPQuery(UInt64 query_id, const String & reason)
     LOG_WARNING(log, fmt::format("Begin cancel query: {}", query_id));
     FmtBuffer fmt_buf;
     fmt_buf.fmtAppend("Remaining task in query {} are: ", query_id);
+    std::vector<std::function<void()>> cancel_functors;
```
Comment (fuzhe1989) [inline dbms/src/Flash/Mpp/MPPTaskManager.cpp:128]: guess we don't actually need this `vector`?

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp [hunk 5]
```diff
@@ -97,14 +125,32 @@ void MPPTaskManager::cancelMPPQuery(UInt64 query_id, const String & reason)
...
+            it = task_set->task_map.erase(it);
+            // Note it is not acceptable to destruct `current_task` inside the loop, because destruct a mpp task before all
+            // other mpp tasks are cancelled may cause some deadlock issues, so `current_task` has to be moved to cancel thread.
+            // At first, we use std::move to move `current_task` to lambda like this:
+            // thread_manager->schedule(false, "CancelMPPTask", [task = std::move(current_task), &reason] { task->cancel(reason); });
+            // However, due to SOO in llvm(https://github.com/llvm/llvm-project/issues/32472), there is still a copy of `current_task`
+            // remaining in the current scope, as a workaround we add a wrap(MPPTaskCancelFunctor) here to make sure `current_task`
+            // can be moved to cancel thread. Meanwhile, also save the moved wrap in a vector to guarantee that even if cancel functors
+            // fail to move due to some other issues, it still does not destruct inside the loop
+            cancel_functors.push_back(MPPTaskCancelFunctor(std::move(current_task), reason));
```
Comment (fuzhe1989) [inline dbms/src/Flash/Mpp/MPPTaskManager.cpp:146]: depend on the behavior of `std::function::move` is risky and hard to understand.

how about this?
```cpp
thread_manager->schedule(false, "CancelMPPTask", 
    [functor = new MPPTaskCancelFunctor(std::move(current_task), reason)] {
        std::unique_ptr(functor)->run(); // do not need `operator()`, just `run()`
});
```

IMO it's more stable than depending on some specific implementation of `std::function`.

File: dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp [hunk 6]
```diff
@@ -125,24 +125,30 @@ void CreatingSetsBlockInputStream::createAll()
...
                 }
             }
         }
+        catch (...)
+        {
+            thread_manager->wait();
+            throw;
+        }
 
         thread_manager->wait();
```
Comment (fuzhe1989) [inline dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp:153]: It's actually a finally:

```cpp
finally {
    thread_manager->wait();
}
```

File: dbms/src/Flash/Mpp/MPPTaskManager.cpp (hunk 5 above)
Comment (windtalker) [reply dbms/src/Flash/Mpp/MPPTaskManager.cpp:146]: Good idea, since this pr is merged, I will use another pr to refine it.
