### PR TITLE
UniPS: Catch exception when dumping incr snapshot

### LINKED ISSUE #9406: Check index.has_value():  Can not find path for PageFile file_id=221_0
## Bug Report

Please answer these questions before submitting your issue. Thanks!

```
[2024/05/23 14:30:47.741 +00:00] [ERROR] [Exception.cpp:96] ["Code: 49, e.displayText() = DB::Exception: Check index.has_value() failed: Can not find path for PageFile file_id=221_0, e.what() = DB::Exception, Stack trace:\n\n\n       0x1f5441e\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+32850974]\n                \tdbms/src/Common/Exception.h:46\n       0x80f57dc\tDB::PSDiskDelegatorGlobalMulti::getPageFilePath(std::__1::pair<unsigned long, unsigned int> const&) const [tiflash+135223260]\n                \tdbms/src/Storages/PathPool.cpp:1133\n       0x1ec5daf\tDB::PS::V3::BlobStore<DB::PS::V3::universal::BlobStoreTrait>::getBlobFile(unsigned long) [tiflash+32267695]\n                \tdbms/src/Storages/Page/V3/BlobStore.cpp:1506\n       0x1ec6e0d\tDB::PS::V3::BlobStore<DB::PS::V3::universal::BlobStoreTrait>::read(DB::UniversalPageId const&, unsigned long, unsigned long, char*, unsigned long, std::__1::shared_ptr<DB::ReadLimiter> const&, bool) [tiflash+32271885]\n                \tdbms/src/Storages/Page/V3/BlobStore.cpp:1146\n       0x1ece821\tDB::PS::V3::BlobStore<DB::PS::V3::universal::BlobStoreTrait>::read(std::__1::pair<DB::UniversalPageId, DB::PS::V3::PageEntryV3> const&, std::__1::shared_ptr<DB::ReadLimiter> const&) [tiflash+32303137]\n                \tdbms/src/Storages/Page/V3/BlobStore.cpp:1099\n       0x877a57d\tDB::PS::V3::CPFilesWriter::writeEditsAndApplyCheckpointInfo(DB::PS::V3::PageEntriesEdit<DB::UniversalPageId>&, DB::PS::V3::CPFilesWriter::CompactOptions const&, bool) [tiflash+142058877]\n                \tdbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp:185\n       0x875f83e\tDB::UniversalPageStorage::dumpIncrementalCheckpoint(DB::UniversalPageStorage::DumpCheckpointOptions const&) [tiflash+141948990]\n                \tdbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp:547\n       0x876fcca\tstd::__1::__function::__func<DB::UniversalPageStorageService::create(DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::PSDiskDelegator>, DB::PageStorageConfig const&)::$_3, std::__1::allocator<DB::UniversalPageStorageService::create(DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::PSDiskDelegator>, DB::PageStorageConfig const&)::$_3>, bool ()>::operator()() [tiflash+142015690]\n                \t/usr/local/bin/../include/c++/v1/__functional/function.h:345\n       0x80cd67b\tvoid* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, DB::BackgroundProcessingPool::BackgroundProcessingPool(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_1> >(void*) [tiflash+135059067]\n                \t/usr/local/bin/../include/c++/v1/thread:291\n  0x7fef18dcaea5\tstart_thread [libpthread.so.0+32421]\n  0x7fef186d996d\t__clone [libc.so.6+1042797]"] [source="DB::PS::V3::CPDataDumpStats DB::PS::V3::CPFilesWriter::writeEditsAndApplyCheckpointInfo(universal::PageEntriesEdit &, const CPFilesWriter::CompactOptions &, bool)"] [thread_id=511]
[2024/05/23 14:30:48.021 +00:00] [ERROR] [Exception.cpp:96] ["Code: 49, e.displayText() = DB::Exception: Check index.has_value() failed: Can not find path for PageFile file_id=221_0, e.what() = DB::Exception, Stack trace:\n\n\n       0x1f5441e\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+32850974]\n                \tdbms/src/Common/Exception.h:46\n       0x80f57dc\tDB::PSDiskDelegatorGlobalMulti::getPageFilePath(std::__1::pair<unsigned long, unsigned int> const&) const [tiflash+135223260]\n                \tdbms/src/Storages/PathPool.cpp:1133\n       0x1ec5daf\tDB::PS::V3::BlobStore<DB::PS::V3::universal::BlobStoreTrait>::getBlobFile(unsigned long) [tiflash+32267695]\n                \tdbms/src/Storages/Page/V3/BlobStore.cpp:1506\n       0x1ec6e0d\tDB::PS::V3::BlobStore<DB::PS::V3::universal::BlobStoreTrait>::read(DB::UniversalPageId const&, unsigned long, unsigned long, char*, unsigned long, std::__1::shared_ptr<DB::ReadLimiter> const&, bool) [tiflash+32271885]\n                \tdbms/src/Storages/Page/V3/BlobStore.cpp:1146\n       0x1ece821\tDB::PS::V3::BlobStore<DB::PS::V3::universal::BlobStoreTrait>::read(std::__1::pair<DB::UniversalPageId, DB::PS::V3::PageEntryV3> const&, std::__1::shared_ptr<DB::ReadLimiter> const&) [tiflash+32303137]\n                \tdbms/src/Storages/Page/V3/BlobStore.cpp:1099\n       0x877a57d\tDB::PS::V3::CPFilesWriter::writeEditsAndApplyCheckpointInfo(DB::PS::V3::PageEntriesEdit<DB::UniversalPageId>&, DB::PS::V3::CPFilesWriter::CompactOptions const&, bool) [tiflash+142058877]\n                \tdbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp:185\n       0x875f83e\tDB::UniversalPageStorage::dumpIncrementalCheckpoint(DB::UniversalPageStorage::DumpCheckpointOptions const&) [tiflash+141948990]\n                \tdbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp:547\n       0x876fcca\tstd::__1::__function::__func<DB::UniversalPageStorageService::create(DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::PSDiskDelegator>, DB::PageStorageConfig const&)::$_3, std::__1::allocator<DB::UniversalPageStorageService::create(DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::PSDiskDelegator>, DB::PageStorageConfig const&)::$_3>, bool ()>::operator()() [tiflash+142015690]\n                \t/usr/local/bin/../include/c++/v1/__functional/function.h:345\n       0x80cd67b\tvoid* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, DB::BackgroundProcessingPool::BackgroundProcessingPool(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_1> >(void*) [tiflash+135059067]\n                \t/usr/local/bin/../include/c++/v1/thread:291\n  0x7fef18dcaea5\tstart_thread [libpthread.so.0+32421]\n  0x7fef186d996d\t__clone [libc.so.6+1042797]"] [source="void DB::BackgroundProcessingPool::threadFunction(size_t)"] [thread_id=511]
```

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #9406

Problem Summary:

1. Print error message and stack
2. Print error when GetObject timeout

### What is changed and how it works?

```commit-message

```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp [hunk 1]
```diff
@@ -180,10 +181,15 @@ CPDataDumpStats CPFilesWriter::writeEditsAndApplyCheckpointInfo(
...
+        Stopwatch sw;
         try
         {
             auto page = data_source->read({rec_edit.page_id, rec_edit.entry});
-            RUNTIME_CHECK_MSG(page.isValid(), "failed to read page, record={}", rec_edit);
+            RUNTIME_CHECK_MSG(
+                page.isValid(),
+                "failed to read page, record={}, elapsed={}",
+                rec_edit,
+                sw.elapsedSeconds());
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp:192]: I am not sure if we will read a invalid page after a long time

File: dbms/src/Storages/S3/S3RandomAccessFile.cpp [hunk 2]
```diff
@@ -192,7 +192,16 @@ bool S3RandomAccessFile::initialize()
...
         {
-            LOG_ERROR(log, "S3 GetObject failed: {}, cur_retry={}", S3::S3ErrorMessage(outcome.GetError()), cur_retry);
+            auto el = sw.elapsedSeconds();
+            LOG_ERROR(
+                log,
+                "S3 GetObject failed: {}, cur_retry={}, key={}, remote_fname={}, elapsed{}={}",
+                S3::S3ErrorMessage(outcome.GetError()),
+                cur_retry,
+                req.GetKey(),
+                remote_fname,
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/S3/S3RandomAccessFile.cpp]: fixed

File: dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.h [hunk 3]
```diff
@@ -40,8 +40,9 @@ class CPManifestFileWriter : private boost::noncopyable
         return std::make_unique<CPManifestFileWriter>(std::move(options));
     }
 
-    explicit CPManifestFileWriter(Options options)
-        : file_writer(std::make_unique<WriteBufferFromFile>(options.file_path))
+    explicit CPManifestFileWriter(Options options_)
+        : options(options_)
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.h:44]: seems we can move here?

File: dbms/src/Storages/S3/S3RandomAccessFile.cpp [hunk 4]
```diff
@@ -192,7 +192,16 @@ bool S3RandomAccessFile::initialize()
...
         if (!outcome.IsSuccess())
         {
-            LOG_ERROR(log, "S3 GetObject failed: {}, cur_retry={}", S3::S3ErrorMessage(outcome.GetError()), cur_retry);
+            auto el = sw.elapsedSeconds();
+            LOG_ERROR(
+                log,
+                "S3 GetObject failed: {}, cur_retry={}, key={}, remote_fname={}, elapsed{}={}",
+                S3::S3ErrorMessage(outcome.GetError()),
+                cur_retry,
+                req.GetKey(),
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/S3/S3RandomAccessFile.cpp:201]: Is there anywhere `key_root` is printed?

File: dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.h (hunk 3 above)
Comment (CalvinNeo) [reply dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.h]: fixed

File: dbms/src/Storages/S3/S3RandomAccessFile.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply dbms/src/Storages/S3/S3RandomAccessFile.cpp:201]: Then I think we'd better also print it here, since start log could lose when a server is starting. Meanwhile, it could be hard to find if the server has been running for a long time.

File: dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp [hunk 5]
```diff
@@ -542,23 +546,49 @@ PS::V3::CPDataDumpStats UniversalPageStorage::dumpIncrementalCheckpoint(
...
+    std::vector<String> data_file_paths;
+    const auto checkpoint_dump_stats = [&]() -> std::optional<PS::V3::CPDataDumpStats> {
+        try
+        {
+            writer->writePrefix({
+                .writer = options.writer_info,
+                .sequence = snap->sequence,
+                .last_sequence = last_checkpoint_sequence,
+            });
+            PS::V3::CPFilesWriter::CompactOptions compact_opts = [&]() {
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp:558]:
```suggestion
            const PS::V3::CPFilesWriter::CompactOptions compact_opts = [&]() {
```

File: dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp [hunk 6]
```diff
@@ -542,23 +546,49 @@ PS::V3::CPDataDumpStats UniversalPageStorage::dumpIncrementalCheckpoint(
...
+            return std::nullopt;
+        }
     }();
-    // get the remote file ids that need to be compacted
-    const auto checkpoint_dump_stats
-        = writer->writeEditsAndApplyCheckpointInfo(edit_from_mem, compact_opts, options.only_upload_manifest);
-    auto data_file_paths = writer->writeSuffix();
+
+    if (!checkpoint_dump_stats.has_value())
+        return checkpoint_dump_stats;
```
Comment (Lloyd-Pottiger) [inline dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp:590]:
```suggestion
        return std::nullopt;
```

**Review by Lloyd-Pottiger — APPROVED** [review]

File: dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp [hunk 7]
```diff
@@ -580,7 +610,7 @@ PS::V3::CPDataDumpStats UniversalPageStorage::dumpIncrementalCheckpoint(
     // TODO: Currently, even when has_new_data == false,
     //   something will be written to DataFile (i.e., the file prefix).
     //   This can be avoided, as its content is useless.
-    if (checkpoint_dump_stats.has_new_data)
+    if (checkpoint_dump_stats.value().has_new_data)
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp:613]:
```suggestion
    if (checkpoint_dump_stats->has_new_data)
```

File: dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp [hunk 8]
```diff
@@ -607,8 +637,8 @@ PS::V3::CPDataDumpStats UniversalPageStorage::dumpIncrementalCheckpoint(
         copy_checkpoint_info_seconds,
         sw.elapsedSeconds(),
         sequence,
-        checkpoint_dump_stats);
-    SetMetrics(checkpoint_dump_stats);
+        checkpoint_dump_stats.value());
+    SetMetrics(checkpoint_dump_stats.value());
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp:641]:
```suggestion
        *checkpoint_dump_stats);
    SetMetrics(*checkpoint_dump_stats);
```

File: dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp [hunk 9]
```diff
@@ -282,16 +282,20 @@ bool UniversalPageStorageService::uploadCheckpointImpl(
...
+            .Increment(write_stats.value().incremental_data_bytes);
+        GET_METRIC(tiflash_storage_checkpoint_flow, type_compaction).Increment(write_stats.value().compact_data_bytes);
+
+        LOG_INFO(
+            log,
+            "Upload checkpoint success,{} upload_sequence={} incremental_bytes={} compact_bytes={}",
+            force_sync_data ? " sync_all=true" : "",
+            upload_info.upload_sequence,
+            write_stats.value().incremental_data_bytes,
+            write_stats.value().compact_data_bytes);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp:297]:
```suggestion
            write_stats->incremental_data_bytes,
            write_stats->compact_data_bytes);
```

File: dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp [hunk 10]
```diff
@@ -542,23 +546,49 @@ PS::V3::CPDataDumpStats UniversalPageStorage::dumpIncrementalCheckpoint(
...
+                if (options.compact_getter == nullptr)
+                    return PS::V3::CPFilesWriter::CompactOptions(false);
+                return PS::V3::CPFilesWriter::CompactOptions(options.compact_getter());
+            }();
+            // get the remote file ids that need to be compacted
+            const auto checkpoint_dump_stats_inner
+                = writer->writeEditsAndApplyCheckpointInfo(edit_from_mem, compact_opts, options.only_upload_manifest);
+            data_file_paths = writer->writeSuffix();
+            fiu_do_on(FailPoints::force_checkpoint_dump_throw_datafile, {
+                throw Exception(ErrorCodes::LOGICAL_ERROR, "fake checkpoint write exception");
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp:570]:
```suggestion
                throw Exception(ErrorCodes::FAIL_POINT_ERROR, "fake checkpoint write exception");
```

File: dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp [hunk 11]
```diff
@@ -207,7 +214,7 @@ CPDataDumpStats CPFilesWriter::writeEditsAndApplyCheckpointInfo(
         }
         catch (...)
         {
-            LOG_ERROR(log, "failed to read page, record={}", rec_edit);
+            LOG_ERROR(log, "failed to read and write page, record={}, elapsed={}s", rec_edit, sw.elapsedSeconds());
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp:217]:
```suggestion
            LOG_ERROR(log, "failed to read and write page, record={}, elapsed={:.3f}s", rec_edit, sw.elapsedSeconds());
```

File: dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp [hunk 12]
```diff
@@ -180,10 +182,15 @@ CPDataDumpStats CPFilesWriter::writeEditsAndApplyCheckpointInfo(
...
         // 2. For entry edits without the checkpoint info, or it is stored on an existing data file that needs compact,
         // write the entry data to the data file, and assign a new checkpoint info.
+        Stopwatch sw;
         try
         {
             auto page = data_source->read({rec_edit.page_id, rec_edit.entry});
-            RUNTIME_CHECK_MSG(page.isValid(), "failed to read page, record={}", rec_edit);
+            RUNTIME_CHECK_MSG(
+                page.isValid(),
+                "failed to read page, record={}, elapsed={}s",
```
Comment (JaySon-Huang) [inline dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp:191]:
```suggestion
                "failed to read page, record={} elapsed={:.3f}s",
```

File: dbms/src/Storages/S3/S3RandomAccessFile.cpp [hunk 13]
```diff
@@ -192,7 +192,15 @@ bool S3RandomAccessFile::initialize()
         auto outcome = client_ptr->GetObject(req);
         if (!outcome.IsSuccess())
         {
-            LOG_ERROR(log, "S3 GetObject failed: {}, cur_retry={}", S3::S3ErrorMessage(outcome.GetError()), cur_retry);
+            auto el = sw.elapsedSeconds();
+            LOG_ERROR(
+                log,
+                "S3 GetObject failed: {}, cur_retry={}, key={}, elapsed{}={}s",
```
Comment (JaySon-Huang) [inline dbms/src/Storages/S3/S3RandomAccessFile.cpp:198]:
```suggestion
                "S3 GetObject failed: {}, cur_retry={}, key={}, elapsed{}={:.3f}s",
```

File: dbms/src/Storages/S3/S3RandomAccessFile.cpp [hunk 14]
```diff
@@ -208,7 +216,14 @@ bool S3RandomAccessFile::initialize()
     }
     if (cur_retry >= max_retry && !request_succ)
     {
-        LOG_INFO(log, "S3 GetObject timeout: {}, max_retry={}", remote_fname, max_retry);
+        auto el = sw.elapsedSeconds();
+        LOG_INFO(
+            log,
+            "S3 GetObject timeout: max_retry={}, key={}, elapsed{}={}s",
```
Comment (JaySon-Huang) [inline dbms/src/Storages/S3/S3RandomAccessFile.cpp:222]:
```suggestion
            "S3 GetObject timeout: max_retry={}, key={}, elapsed{}={:.3f}s",
```

**Comment by JaySon-Huang** [comment]
@CalvinNeo  In summary:

1. [operator */operator->](https://en.cppreference.com/w/cpp/utility/optional/operator*) is a more concise way to accessing an `std::optional` instance
2. When logging down the elapsed time in seconds, better use `"{:.3f}"` to format the output. The output of a floating number using `"{}"` is not readable sometime.
here is an example: https://godbolt.org/z/qvrxT7q1Y

File: dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp (hunk 10 above)
Comment (CalvinNeo) [reply dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp:570]: It should be LOGICAL_ERROR. Because there is another error `ErrorCodes::REGION_DATA_SCHEMA_UPDATED` which could make prehandle to retry. So error codes matters here.

**Comment by CalvinNeo** [comment]
> @CalvinNeo In summary:
> 
> 1. [operator * / operator->](https://en.cppreference.com/w/cpp/utility/optional/operator*) is a more concise way to accessing an `std::optional` instance
> 2. When logging down the elapsed time in seconds, better use `"{:.3f}"` to format the output. The output of a floating number using `"{}"` is not readable sometime.
>    here is an example: https://godbolt.org/z/qvrxT7q1Y

Got it
