### PR TITLE
Change the implementation of shared_block_schemas with LRUCache

### LINKED ISSUE #6809: TSan check broken
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run Sanitizer Tests https://github.com/pingcap/tiflash#run-sanitizer-tests

### 2. What did you expect to see? (Required)
No error detected 

### 3. What did you see instead (Required)
https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/876/pipeline/

Many ASAN tests failed, here is logs for one of the failed test.
[asan.log](https://github.com/pingcap/tiflash/files/10719583/asan.log)

### 4. What is your TiFlash version? (Required)
master. should be introduced by https://github.com/pingcap/tiflash/pull/6589

### PR DESCRIPTION
**Pull request by hongyunyan**
### What problem does this PR solve?

Issue Number: close #6809

Problem Summary:

### What is changed and how it works?
1. Use LRUCache to implement SharedBlockSchemas
2. Add some metrics to record the information of SharedBlockSchemas

image

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.h [hunk 1]
```diff
@@ -13,6 +13,7 @@
 // limitations under the License.
 
 #pragma once
+#include <Common/LRUCache.h>
```
Comment (flowbehappy) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.h:16]: I wonder why we don't use `LRUCache` directly.

Comment (flowbehappy) [reply dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.h:16]: If not then maybe remove this include.

**Review by flowbehappy — APPROVED** [review]
LGTM

File: dbms/src/Interpreters/Settings.h [hunk 2]
```diff
@@ -304,7 +304,8 @@ struct Settings
     M(SettingBool, enable_planner, true, "Enable planner")                                                                                                                                                                              \
     M(SettingBool, enable_pipeline, false, "Enable pipeline model")                                                                                                                                                                     \
     M(SettingUInt64, pipeline_task_thread_pool_size, 0, "The size of task thread pool. 0 means using number_of_logical_cpu_cores.") \
-    M(SettingUInt64, local_tunnel_version, 1, "1: not refined, 2: refined")
+    M(SettingUInt64, local_tunnel_version, 1, "1: not refined, 2: refined") \
+    M(SettingUInt64, shared_block_schemas_size, 10000, "the size of shared_block_schema")
```
Comment (JaySon-Huang) [inline dbms/src/Interpreters/Settings.h:308]:
```suggestion
    M(SettingUInt64, schema_cache_size, 10000, "the cache size of shared schema")
```

Comment (JaySon-Huang) [reply dbms/src/Interpreters/Settings.h:308]: I think naming it "schema_cache_size" and use `config().getInt("schema_cache_size", 10000)` to set it in `Server.cpp` is better than add it to `Settings`. As it is

- not reloadable settings after startup
- kind of similar to "minmax_cache_size" and "mark_cache_size"

File: dbms/src/Common/TiFlashMetrics.h [hunk 3]
```diff
@@ -277,8 +277,12 @@ namespace DB
     M(tiflash_compute_request_unit, "Request Unit used by tiflash compute", Counter,                                                                \
         F(type_mpp, {{"type", "mpp"}, ComputeLabelHolder::instance().getClusterIdLabel(), ComputeLabelHolder::instance().getProcessIdLabel()}),     \
         F(type_cop, {{"type", "cop"}, ComputeLabelHolder::instance().getClusterIdLabel(), ComputeLabelHolder::instance().getProcessIdLabel()}),     \
-        F(type_batch, {{"type", "batch"}, ComputeLabelHolder::instance().getClusterIdLabel(), ComputeLabelHolder::instance().getProcessIdLabel()}))
-
+        F(type_batch, {{"type", "batch"}, ComputeLabelHolder::instance().getClusterIdLabel(), ComputeLabelHolder::instance().getProcessIdLabel()})) \
+    M(tiflash_shared_block_schemas, "statistics about shared_block_schemas", Gauge,                                                                 \
```
Comment (JaySon-Huang) [inline dbms/src/Common/TiFlashMetrics.h:281]:
```suggestion
    M(tiflash_shared_block_schemas, "statistics about shared block schemas of ColumnFiles", Gauge,                                                                 \
```

**Review by JaySon-Huang — COMMENTED** [review]
If we want to control the memory more precisely, we can
- add a method `ColumnFileSchema::approxBytes` to calculate the memory consumption of the schema object
- add a `SharedBlockSchemas::max_weight`
- add a `Holder::weight` in the LRUQueue
- respect the max_weight in `removeOverflow`

But the current implementation should be good enough for most scenarios.

rest lgtm

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp [hunk 4]
```diff
@@ -39,58 +42,90 @@ String ColumnFileSchema::toString() const
...
+            GET_METRIC(tiflash_shared_block_schemas, type_hit_count).Increment();
+            lru_queue.splice(lru_queue.end(), lru_queue, iter->second.queue_it);
+            return schema;
+        }
+        else
+        {
+            // if the weak_ptr.lock() only get nullptr, that means the schema is not used by any ColumnFiles
+            // So we need update the item
+            GET_METRIC(tiflash_shared_block_schemas, type_miss_count).Increment();
+            auto new_schema = std::make_shared<ColumnFileSchema>(block);
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp:110]: Seems we should use `std::shared_ptr<ColumnFileSchema> new_schema(new ColumnFileSchema(block));` instead of `make_shared` when we need it to be released ASAP https://stackoverflow.com/questions/32113594/weak-ptr-make-shared-and-memory-deallocation

Comment (JaySon-Huang) [reply dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp:110]: <details>
<summary> test codes </summary>
```

//////////////////////////////////////////////////////////////////////////////
//
// process_mem_usage(double &, double &) - takes two doubles by reference,
// attempts to read the system-dependent data for a process' virtual memory
// size and resident set size, and return the results in KB.
//
// On failure, returns 0.0, 0.0
void process_mem_usage(double & vm_usage, double & resident_set)
{
    using std::ifstream;
    using std::ios_base;
    using std::string;

    vm_usage = 0.0;
    resident_set = 0.0;

    // 'file' stat seems to give the most reliable results
    //
    ifstream stat_stream("/proc/self/stat", ios_base::in);

    // dummy vars for leading entries in stat that we don't care about
    //
    string pid, comm, state, ppid, pgrp, session, tty_nr;
    string tpgid, flags, minflt, cminflt, majflt, cmajflt;
    string utime, stime, cutime, cstime, priority, nice;
    string o, itrealvalue, starttime;

    // the two fields we want
    //
    UInt64 vsize;
    Int64 rss;

    stat_stream >> pid >> comm >> state >> ppid >> pgrp >> session >> tty_nr
        >> tpgid >> flags >> minflt >> cminflt >> majflt >> cmajflt
        >> utime >> stime >> cutime >> cstime >> priority >> nice
        >> o >> itrealvalue >> starttime >> vsize >> rss; // don't care about the rest

    stat_stream.close();

    Int64 page_size_kb = sysconf(_SC_PAGE_SIZE) / 1024; // in case x86-64 is configured to use 2MB pages
    vm_usage = vsize / 1024.0;
    resident_set = rss * page_size_kb;
}

struct BigMem
{
    // 1mb
    char buff[1024 * 1024];
};

const size_t n_blocks = 10240;
static constexpr double step = 1024;

TEST(WeakPtr, MakeShared)
{
    std::vector<std::shared_ptr<BigMem>> shared_blocks;
    shared_blocks.reserve(n_blocks);
    std::vector<std::weak_ptr<BigMem>> weak_blocks;
    weak_blocks.reserve(n_blocks);

    double vm_kb, rss_kb;

    process_mem_usage(vm_kb, rss_kb);
    LOG_INFO(Logger::get(), "vm={:.3f}MB rss={:.3f}MB -- init", vm_kb / step, rss_kb / step);

    for (size_t i = 0; i < n_blocks; ++i)
    {
        auto p = std::make_shared<BigMem>();
        memset(p->buff, 0xff, 1024 * 1024);
        shared_blocks.emplace_back(p);
        weak_blocks.emplace_back(p);
    }
    process_mem_usage(vm_kb, rss_kb);
    LOG_INFO(Logger::get(), "vm={:.3f}MB rss={:.3f}MB -- allocated", vm_kb / step, rss_kb / step);

    for (size_t i = 0; i < n_blocks; ++i)
    {
        shared_blocks[i].reset();
    }
    process_mem_usage(vm_kb, rss_kb);
    LOG_INFO(Logger::get(), "vm={:.3f}MB rss={:.3f}MB -- shared_ptrs realeased", vm_kb / step, rss_kb / step);

    for (size_t i = 0; i < n_blocks; ++i)
    {
        weak_blocks[i].reset();
    }
    process_mem_usage(vm_kb, rss_kb);
    LOG_INFO(Logger::get(), "vm={:.3f}MB rss={:.3f}MB -- weak_ptrs released", vm_kb / step, rss_kb / step);
}

TEST(WeakPtr, NewThenShared)
{
    std::vector<std::shared_ptr<BigMem>> shared_blocks;
    shared_blocks.reserve(n_blocks);
    std::vector<std::weak_ptr<BigMem>> weak_blocks;
    weak_blocks.reserve(n_blocks);

    double vm_kb, rss_kb;

    process_mem_usage(vm_kb, rss_kb);
    LOG_INFO(Logger::get(), "vm={:.3f}MB rss={:.3f}MB -- init", vm_kb / step, rss_kb / step);

    for (size_t i = 0; i < n_blocks; ++i)
    {
        std::shared_ptr<BigMem> p(new BigMem());
        memset(p->buff, 0xff, 1024 * 1024);
        shared_blocks.emplace_back(p);
        weak_blocks.emplace_back(p);
    }
    process_mem_usage(vm_kb, rss_kb);
    LOG_INFO(Logger::get(), "vm={:.3f}MB rss={:.3f}MB -- allocated", vm_kb / step, rss_kb / step);

    for (size_t i = 0; i < n_blocks; ++i)
    {
        shared_blocks[i].reset();
    }
    process_mem_usage(vm_kb, rss_kb);
    LOG_INFO(Logger::get(), "vm={:.3f}MB rss={:.3f}MB -- shared_ptrs realeased", vm_kb / step, rss_kb / step);

    for (size_t i = 0; i < n_blocks; ++i)
    {
        weak_blocks[i].reset();
    }
    process_mem_usage(vm_kb, rss_kb);
    LOG_INFO(Logger::get(), "vm={:.3f}MB rss={:.3f}MB -- weak_ptrs released", vm_kb / step, rss_kb / step);
}
```
</details>

```
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from WeakPtr
[ RUN      ] WeakPtr.MakeShared
[2023/02/25 17:32:36.089 +08:00] [INFO] [gtest_s3gcmanager.cpp:322] ["vm=863.047MB rss=44.629MB -- init"] [thread_id=1]
[2023/02/25 17:32:45.105 +08:00] [INFO] [gtest_s3gcmanager.cpp:332] ["vm=14179.047MB rss=12910.754MB -- allocated"] [thread_id=1]
[2023/02/25 17:32:45.126 +08:00] [INFO] [gtest_s3gcmanager.cpp:339] ["vm=14179.047MB rss=12910.789MB -- shared_ptrs realeased"] [thread_id=1]
[2023/02/25 17:32:55.808 +08:00] [INFO] [gtest_s3gcmanager.cpp:346] ["vm=14179.047MB rss=82.699MB -- weak_ptrs released"] [thread_id=1]
[       OK ] WeakPtr.MakeShared (19719 ms)
[ RUN      ] WeakPtr.NewThenShared
[2023/02/25 17:32:55.809 +08:00] [INFO] [gtest_s3gcmanager.cpp:359] ["vm=14179.047MB rss=82.699MB -- init"] [thread_id=1]
[2023/02/25 17:33:03.688 +08:00] [INFO] [gtest_s3gcmanager.cpp:369] ["vm=14179.047MB rss=10350.934MB -- allocated"] [thread_id=1]
[2023/02/25 17:33:06.908 +08:00] [INFO] [gtest_s3gcmanager.cpp:376] ["vm=14179.047MB rss=254.434MB -- shared_ptrs realeased"] [thread_id=1]
[2023/02/25 17:33:06.933 +08:00] [INFO] [gtest_s3gcmanager.cpp:383] ["vm=14179.047MB rss=247.406MB -- weak_ptrs released"] [thread_id=1]
[       OK ] WeakPtr.NewThenShared (11126 ms)
[----------] 2 tests from WeakPtr (30845 ms total)
```

Comment (JaySon-Huang) [reply dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp:110]: https://lanzkron.wordpress.com/2012/04/22/make_shared-almost-a-silver-bullet/

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp [hunk 5]
```diff
@@ -39,58 +40,90 @@ String ColumnFileSchema::toString() const
...
+            GET_METRIC(tiflash_shared_block_schemas, type_hit_count).Increment();
+            lru_queue.splice(lru_queue.end(), lru_queue, iter->second.queue_it);
+            return schema;
+        }
+        else
+        {
+            // if the weak_ptr.lock() only get nullptr, that means the schema is not used by any ColumnFiles
+            // So we need update the item
+            GET_METRIC(tiflash_shared_block_schemas, type_miss_count).Increment();
+            std::shared_ptr<ColumnFileSchema> new_schema(new ColumnFileSchema(block));
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp:108]: add some comments about why we use `std::shared_ptr (new ...)` instead of `make_shared` here

Comment (breezewish) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp:108]: prefer using make_shared

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp [hunk 6]
```diff
@@ -39,58 +40,90 @@ String ColumnFileSchema::toString() const
...
-        std::lock_guard<std::mutex> lock(mutex);
-        for (auto iter = column_file_schemas.begin(); iter != column_file_schemas.end();)
+    size_t current_size = column_file_schemas.size();
+    while (current_size > max_size)
+    {
+        const auto & digest = lru_queue.front();
+
+        auto iter = column_file_schemas.find(digest);
+        if (iter == column_file_schemas.end())
+            throw Exception(String(__FUNCTION__) + " inconsistent", ErrorCodes::LOGICAL_ERROR);
```
Comment (breezewish) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp:52]: Prefer using RUNTIME_CHECK or RUNTIME_CHECK_MSG

**Review by breezewish — APPROVED** [review]
Please also add comment why this impl is not using the existing LRUCache module. The rest LGTM.

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp (hunk 5 above)
Comment (hongyunyan) [reply dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp:107]: We don't use make_shared here, because make_shared will allocate the memory of *ptr and control block together.
Thus, the memory occupied by ColumnFileSchema will persists until all weak_ptr owners get destroyed as well.
https://lanzkron.wordpress.com/2012/04/22/make_shared-almost-a-silver-bullet/

File: dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp [hunk 7]
```diff
@@ -39,58 +40,89 @@ String ColumnFileSchema::toString() const
...
+        }
+        else
+        {
+            // if the weak_ptr.lock() only get nullptr, that means the schema is not used by any ColumnFiles
+            // So we need update the item
+            GET_METRIC(tiflash_shared_block_schemas, type_miss_count).Increment();
+            // We don't use make_shared here, because make_shared will allocate the memory of *ptr and control block together.
+            // Thus, the memory occupied by ColumnFileSchema will persists until all weak_ptr owners get destroyed as well.
+            // https://lanzkron.wordpress.com/2012/04/22/make_shared-almost-a-silver-bullet/
+            std::shared_ptr<ColumnFileSchema> new_schema(new ColumnFileSchema(block));
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp:107]:
```suggestion
            // To ensure that the memory of ColumnFileSchema is released as soon as possible, we allocate memory using new
            // and then assign it to a shared_ptr. With make_shared, the tracked object (ColumnFileSchema) and the reference counting
            // are allocated on the same memory page. However, the memory of the tracked object can only be released after
            // all weak_ptrs are removed. This is not the case with an LRUCache.
            // For more information, see https://lanzkron.wordpress.com/2012/04/22/make_shared-almost-a-silver-bullet/.
            std::shared_ptr<ColumnFileSchema> new_schema(new ColumnFileSchema(block));
```

**Review by JaySon-Huang — APPROVED** [review]
Rest LGTM
