### PR TITLE
Some refines

### LINKED ISSUE #7768: Unstable and asan fail ut: RuntimeFilterExecutorTestRunner.RuntimeFilterTes
```
[2023-07-07T07:36:12.347Z] ==159383==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffc6c9761f8 at pc 0x00001a533ab5 bp 0x7ffc6c974b10 sp 0x7ffc6c974b08
[2023-07-07T07:36:12.347Z] READ of size 4 at 0x7ffc6c9761f8 thread T0
[2023-07-07T07:36:12.347Z]     #0 0x1a533ab4 in google::protobuf::internal::RepeatedPtrFieldBase::empty() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/protobuf/src/google/protobuf/repeated_ptr_field.h:848:58
[2023-07-07T07:36:12.347Z]     #1 0x1a533ab4 in google::protobuf::RepeatedPtrField<tipb::Expr>::empty() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/protobuf/src/google/protobuf/repeated_ptr_field.h:1318:32
[2023-07-07T07:36:12.347Z]     #2 0x1a533ab4 in DB::DM::FilterParser::parseDAGQuery(DB::DAGQueryInfo const&, std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > const&, std::__1::function<DB::DM::Attr (long)>&&, std::__1::shared_ptr<DB::Logger> const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp:409:26
[2023-07-07T07:36:12.347Z]     #3 0x1e2f529d in DB::StorageDeltaMerge::buildRSOperator(std::__1::unique_ptr<DB::DAGQueryInfo, std::__1::default_delete<DB::DAGQueryInfo> > const&, std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > const&, DB::Context const&, std::__1::shared_ptr<DB::Logger> const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/StorageDeltaMerge.cpp:737:23
[2023-07-07T07:36:12.347Z]     #4 0x1e2fca11 in DB::StorageDeltaMerge::parsePushDownFilter(DB::SelectQueryInfo const&, std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine> > const&, DB::Context const&, std::__1::shared_ptr<DB::Logger> const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/StorageDeltaMerge.cpp:865:43
[2023-07-07T07:36:12.347Z]     #5 0x1e2fd349 in DB::StorageDeltaMerge::read(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum&, unsigned long, unsigned int) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Storages/StorageDeltaMerge.cpp:916:19
[2023-07-07T07:36:12.347Z]     #6 0x1cb1f85d in DB::MockStorage::getStreamFromDeltaMerge(DB::Context&, long, DB::FilterConditions const*, bool, std::__1::vector<int, std::__1::allocator<int> >, int) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Debug/MockStorage.cpp:221:42
[2023-07-07T07:36:12.347Z]     #7 0x1ef82c4b in DB::(anonymous namespace)::mockSchemaAndStreams(DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Logger> const&, DB::TiDBTableScan const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp:50:58
[2023-07-07T07:36:12.347Z]     #8 0x1ef82c4b in DB::PhysicalMockTableScan::build(DB::Context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Logger> const&, DB::TiDBTableScan const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp:102:35
[2023-07-07T07:36:12.347Z]     #9 0x1ee8bb36 in DB::PhysicalPlan::buildTableScan(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tipb::Executor const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Planner/PhysicalPlan.cpp:81:18
[2023-07-07T07:36:12.347Z]     #10 0x1ee8d1ae in DB::PhysicalPlan::build(tipb::Executor const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Planner/PhysicalPlan.cpp
[2023-07-07T07:36:12.347Z]     #11 0x1ee8ac0f in DB::PhysicalPlan::build(tipb::DAGRequest const*)::$_3::operator()(tipb::Executor const&) const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Planner/PhysicalPlan.cpp:68:13
[2023-07-07T07:36:12.347Z]     #12 0x1ee8ac0f in void DB::traverseExecutorTreePostOrder<DB::PhysicalPlan::build(tipb::DAGRequest const*)::$_3&>(tipb::Executor const&, DB::PhysicalPlan::build(tipb::DAGRequest const*)::$_3&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Statistics/traverseExecutors.h:114:5
[2023-07-07T07:36:12.347Z]     #13 0x1ee8ac0f in void DB::traverseExecutorTreePostOrder<DB::PhysicalPlan::build(tipb::DAGRequest const*)::$_3>(tipb::Executor const&, DB::PhysicalPlan::build(tipb::DAGRequest const*)::$_3&&)::'lambda'(tipb::Executor const&)::operator()(tipb::Executor const&) const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Statistics/traverseExecutors.h:113:72
[2023-07-07T07:36:12.348Z]     #14 0x1ee8ac0f in void DB::Children::forEach<void DB::traverseExecutorTreePostOrder<DB::PhysicalPlan::build(tipb::DAGRequest const*)::$_3>(tipb::Executor const&, DB::PhysicalPlan::build(tipb::DAGRequest const*)::$_3&&)::'lambda'(tipb::Executor const&)>(DB::PhysicalPlan::build(tipb::DAGRequest const*)::$_3&&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Statistics/traverseExecutors.h:47:13
[2023-07-07T07:36:12.348Z]     #15 0x1ee8ac0f in void DB::traverseExecutorTreePostOrder<DB::PhysicalPlan::build(tipb::DAGRequest const*)::$_3>(tipb::Executor const&, DB::PhysicalPlan::build(tipb::DAGRequest const*)::$_3&&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Statistics/traverseExecutors.h:113:27
[2023-07-07T07:36:12.348Z]     #16 0x1ee8ac0f in void DB::traverseExecutorsReverse<DB::PhysicalPlan::build(tipb::DAGRequest const*)::$_3>(tipb::DAGRequest const*, DB::PhysicalPlan::build(tipb::DAGRequest const*)::$_3&&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Statistics/traverseExecutors.h:129:9
[2023-07-07T07:36:12.348Z]     #17 0x1ee8ac0f in DB::PhysicalPlan::build(tipb::DAGRequest const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Planner/PhysicalPlan.cpp:65:5
[2023-07-07T07:36:12.348Z]     #18 0x1eeb6947 in DB::Planner::executeImpl(DB::DAGPipeline&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Planner/Planner.cpp:52:19
[2023-07-07T07:36:12.348Z]     #19 0x1eeb6280 in DB::Planner::execute() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Planner/Planner.cpp:36:5
[2023-07-07T07:36:12.348Z]     #20 0x1ea48327 in DB::(anonymous namespace)::doExecuteAsBlockIO(DB::IQuerySource&, DB::Context&, bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/executeQuery.cpp:98:32
[2023-07-07T07:36:12.348Z]     #21 0x1ea45888 in DB::(anonymous namespace)::executeAsBlockIO(DB::Context&, bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/executeQuery.cpp:161:16
[2023-07-07T07:36:12.348Z]     #22 0x1ea45888 in DB::queryExecute(DB::Context&, bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/executeQuery.cpp:188:12
[2023-07-07T07:36:12.348Z]     #23 0xcb64349 in DB::tests::ExecutorTest::executeStreams(DB::DAGContext*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/ExecutorTestUtils.cpp:307:5
[2023-07-07T07:36:12.348Z]     #24 0xcb64d17 in DB::tests::ExecutorTest::testForExecutionSummary(std::__1::shared_ptr<tipb::DAGRequest> const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::pair<int, int>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::pair<int, int> > > > const&, unsigned long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/ExecutorTestUtils.cpp:331:5
[2023-07-07T07:36:12.348Z]     #25 0x5abc5f8 in DB::tests::RuntimeFilterExecutorTestRunner_RuntimeFilterTest_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/tests/gtest_runtime_filter_executor.cpp:71:9
[2023-07-07T07:36:12.348Z]     #26 0x1a7b88e0 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10
[2023-07-07T07:36:12.348Z]     #27 0x1a7b88e0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14
[2023-07-07T07:36:12.348Z]     #28 0x1a757088 in testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5
[2023-07-07T07:36:12.348Z]     #29 0x1a75a217 in testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11
[2023-07-07T07:36:12.348Z]     #30 0x1a75b78f in testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28
[2023-07-07T07:36:12.348Z]     #31 0x1a7861a8 in testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43
[2023-07-07T07:36:12.348Z]     #32 0x1a7baee0 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10
[2023-07-07T07:36:12.348Z]     #33 0x1a7baee0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14
[2023-07-07T07:36:12.348Z]     #34 0x1a784a21 in testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10
[2023-07-07T07:36:12.348Z]     #35 0xc735b9f in RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46
[2023-07-07T07:36:12.348Z]     #36 0xc735b9f in main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:118:16
[2023-07-07T07:36:12.348Z]     #37 0x7f2dada21554 in __libc_start_main (/lib64/libc.so.6+0x22554)
[2023-07-07T07:36:12.348Z]     #38 0x480fee8 in _start (/tiflash/gtests_dbms+0x480fee8)
[2023-07-07T07:36:12.348Z] 
[2023-07-07T07:36:12.348Z] Address 0x7ffc6c9761f8 is located in stack of thread T0 at offset 952 in frame
[2023-07-07T07:36:12.349Z]     #0 0x1cb1e7ef in DB::MockStorage::getStreamFromDeltaMerge(DB::Context&, long, DB::FilterConditions const*, bool, std::__1::vector<int, std::__1::allocator<int> >, int) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Debug/MockStorage.cpp:187
```

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #7768

Problem Summary:

### What is changed and how it works?
- fix `stack-use-after-scope` in `MockStorage`.
- fix unstable ut `ExecutionSummaryTestRunner.*`
- refine `Pipeline::toTreeString` and cache the result of `toTreeString`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp [hunk 1]
```diff
@@ -235,7 +235,9 @@ void Event::switchStatus(EventStatus from, EventStatus to)
         magic_enum::enum_name(to),
         magic_enum::enum_name(status.load()));
 
+#ifndef NDEBUG
     LOG_DEBUG(log, "switch status: {} --> {}", magic_enum::enum_name(from), magic_enum::enum_name(to));
+#endif // !NDEBUG
```
Comment (Lloyd-Pottiger) [inline dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp:240]: I think debug level log is acceptable.

**Review by Lloyd-Pottiger — APPROVED** [review]
Others LGTM

File: dbms/src/Flash/Pipeline/Pipeline.cpp [hunk 2]
```diff
@@ -150,14 +150,25 @@ void Pipeline::toSelfString(FmtBuffer & buffer, size_t level) const
         " -> ");
 }
 
-void Pipeline::toTreeString(FmtBuffer & buffer, size_t level) const
+String Pipeline::toTreeString() const
```
Comment (gengliqi) [inline dbms/src/Flash/Pipeline/Pipeline.cpp:153]:
```suggestion
const String & Pipeline::toTreeString() const
```

File: dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp (hunk 1 above)
Comment (gengliqi) [reply dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp:240]: Info level should be the default log level in the future. At that time `#ifndef NDEBUG` is useless. It's easier to change the config instead of rebuilding the tiflash in debug mode.

Comment (SeaRise) [reply dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp:240]: Currently, the info level is only set under the cloud, and most user environments are at the debug level.
Or change the log level to trace? Because these logs are not helpful in troubleshooting in the user environment, they are only used for internal testing

File: dbms/src/Flash/Pipeline/Pipeline.h [hunk 3]
```diff
@@ -65,7 +65,7 @@ class Pipeline : public std::enable_shared_from_this<Pipeline>
 
     void addChild(const PipelinePtr & child);
 
-    void toTreeString(FmtBuffer & buffer, size_t level = 0) const;
+    String toTreeString() const;
```
Comment (SeaRise) [inline dbms/src/Flash/Pipeline/Pipeline.h:68]:
```suggestion
    const String & toTreeString() const;
```

File: dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp (hunk 1 above)
Comment (gengliqi) [reply dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp:240]: Looks good to me.

Comment (SeaRise) [inline dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp:240]:
```suggestion
    LOG_DEBUG(log, "switch status: {} --> {}", magic_enum::enum_name(from), magic_enum::enum_name(to));
```

File: dbms/src/Flash/Pipeline/Pipeline.cpp [hunk 4]
```diff
@@ -236,12 +247,16 @@ PipelineEvents Pipeline::toSelfEvents(PipelineExecutorContext & exec_context, Co
...
+#ifndef NDEBUG
         LOG_DEBUG(log, "Execute in fine grained mode and generate {} fine grained pipeline event", self_events.size());
+#endif // !NDEBUG
     }
     else
     {
         self_events.push_back(std::make_shared<PlainPipelineEvent>(exec_context, log->identifier(), context, shared_from_this(), concurrency));
+#ifndef NDEBUG
         LOG_DEBUG(log, "Execute in non fine grained mode and generate one plain pipeline event");
+#endif // !NDEBUG
```
Comment (SeaRise) [inline dbms/src/Flash/Pipeline/Pipeline.cpp:259]:
```suggestion
        LOG_DEBUG(log, "Execute in fine grained mode and generate {} fine grained pipeline event", self_events.size());
    }
    else
    {
        self_events.push_back(std::make_shared<PlainPipelineEvent>(exec_context, log->identifier(), context, shared_from_this(), concurrency));
        LOG_DEBUG(log, "Execute in non fine grained mode and generate one plain pipeline event");
```

File: dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp (hunk 1 above)
Comment (SeaRise) [reply dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp]: reverted to the origin code.

**Review by gengliqi — APPROVED** [review]
