### PR TITLE
Schedule SegmentReadTaskPool until no other component refer to it.

### LINKED ISSUE #5571: Storage snapshot is not released when dt_enable_read_thread is true.
## Bug Report

image

Storage snapshot is not released when `dt_enable_read_thread` is true.

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #5571  ref #5376

Problem Summary:
If read request early terminate,  the corresponding `SegmentReadTaskPool` object would never be schedule again that result in 
some `MergedTask` objects in `MergedTaskPool` are leaked.

### What is changed and how it works?

If there is any others refer to `SegmentReadTaskPool`, it should be scheduled. The read path code will release `MergedTask`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
    - Run some `select * from t limit xxx` concurrently.
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]

File: dbms/src/Storages/DeltaMerge/ReadThread/CircularScanList.h [hunk 1]
```diff
@@ -97,6 +96,12 @@ class CircularScanList
         }
     }
 
+    bool needScheduled(Iter itr)
+    {
+        // If other components hold this SegmentReadTaskPool, schedule it for read blocks or clean MergedTaskPool if necessary.
+        return (*itr)->valid() || itr->use_count() > 1;
+    }
```
Comment (JaySon-Huang) [inline dbms/src/Storages/DeltaMerge/ReadThread/CircularScanList.h:103]: Will a shared pointer of SegmentReadTaskPool only be held in `SegmentReadTaskScheduler::SegmentReadTaskPoolList` (so that the use_count() == 1) with valid() == false?

**Review by JaySon-Huang — APPROVED** [review]
lgtm
