### PR TITLE
Fix potential receiver blocked in deconstruction

### LINKED ISSUE #8019: MPPTask blocked when destructing exchange receivers
Detected by RandomFailpoint tests. The whole story is like this:
 MPPTaskA contains several exchange receviers, and currently we use a [local tem variable](https://github.com/pingcap/tiflash/blob/c97d6989d552b6d337ca2c6da0c57f90732b2049/dbms/src/Flash/Mpp/MPPTask.cpp#L260) to store the initialized ones. However, when the last exchange receiver failed in construction process, exception will be thrown and the local tem variable will be destruct. Besides, there are several exchange receivers already in the local receiver set, these receivers will be destruct sequentially. These can be dependancy between these to-be-destruct receivers, and cause receiver destruction be blocked by unfinished connections. Then the MPPTask can't abort tunnels and other resources now.

### PR DESCRIPTION
**Pull request by yibin87**
### What problem does this PR solve?

Issue Number: close #8019 ref #7177 

Problem Summary: 
1. When ExchangeReceiverSet destruction, first close each receiver, then wait for all connection done.
2. Delay local exchange receiver set destruction until handle error is done.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
RandomFailpoint tests
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/Flash/Mpp/MPPTask.cpp [hunk 1]
```diff
@@ -258,35 +258,46 @@ void MPPTask::registerTunnels(const mpp::DispatchTaskRequest & task_request)
...
+            }
+            return true;
+        });
+    }
+    catch (...)
+    {
+        std::unique_lock lock(mtx);
+        if (status != RUNNING)
+            throw Exception("exchange receiver map can not be initialized, because the task is not in running state");
+        receiver_set = std::move(receiver_set_local);
```
Comment (SeaRise) [inline dbms/src/Flash/Mpp/MPPTask.cpp:298]: Why not just remove `receiver_set_local` and use `receiver_set` directly

Comment (SeaRise) [reply dbms/src/Flash/Mpp/MPPTask.cpp:298]: make `MPPReceiveSet` thread safe

Comment (yibin87) [reply dbms/src/Flash/Mpp/MPPTask.cpp:298]: keep MPPReceiverSet atomic

File: dbms/src/Flash/Mpp/MPPTask.cpp [hunk 2]
```diff
@@ -258,35 +258,46 @@ void MPPTask::registerTunnels(const mpp::DispatchTaskRequest & task_request)
...
+                if (status != RUNNING)
+                    throw Exception(
+                        "exchange receiver map can not be initialized, because the task is not in running state");
+            }
+            return true;
+        });
+    }
+    catch (...)
+    {
+        std::unique_lock lock(mtx);
```
Comment (xzhangxian1008) [inline dbms/src/Flash/Mpp/MPPTask.cpp:295]: `std::lock_guard` is better

**Review by xzhangxian1008 — APPROVED** [review]
Other LGTM

File: dbms/src/Flash/Mpp/MPPTask.cpp (hunk 1 above)
Comment (SeaRise) [reply dbms/src/Flash/Mpp/MPPTask.cpp:298]: But it doesn't matter if it's not atomic.
- The mpp task will not execute until initExchangeReceiver is completed
- When canceling, MPPReceiverSet can be incomplete

Comment (yibin87) [reply dbms/src/Flash/Mpp/MPPTask.cpp:298]: IMO, when canceling, MPPTaskManager is responsible for release MPPReceiverSet resources. If new exchange receiver added after MPPTaskManager released work done, it will be problematic.

Comment (SeaRise) [reply dbms/src/Flash/Mpp/MPPTask.cpp:298]: But MPPReceveSet will be destructed and then eventually be closed

Comment (yibin87) [reply dbms/src/Flash/Mpp/MPPTask.cpp:298]: I think here both ways can work "correctly" if details are handled correctly. And we can distiguish "release resource" and destruct, mpp manager is responsible for release resource when canceling.

Comment (SeaRise) [reply dbms/src/Flash/Mpp/MPPTask.cpp:298]: ok

**Review by SeaRise — APPROVED** [review]
