### PR TITLE
Fix crash by using alignedAlloc rather than alloc

### LINKED ISSUE #10553: group_concat with spill may crash
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Use tpch 10g data and SET TIFLASH REPLICA for two tables below.
```
mysql> set sql_mode = 'ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
Query OK, 0 rows affected (0.00 sec)
mysql> set tidb_enforce_mpp=on;set session tidb_max_tiflash_threads = 4;
Query OK, 0 rows affected (0.00 sec)
Query OK, 0 rows affected (0.00 sec)
mysql> set tiflash_query_spill_ratio=0.01;
Query OK, 0 rows affected (0.00 sec)
mysql> set tiflash_mem_quota_query_per_node=1000000000;
Query OK, 0 rows affected (0.00 sec)
mysql> SELECT
        o_custkey AS customer_id,
        o_orderpriority AS day_part,
        o_orderstatus AS be_type,
        l_partkey AS product_code,
        GROUP_CONCAT(DISTINCT l_shipmode) AS store_code,
        MAX(order_time) AS last_order_time,
        MAX(order_id) AS last_order_id
    FROM (
        SELECT
            o_custkey,
            o_orderpriority,
            o_orderstatus,
            l_partkey,
            l_shipmode,
            l_orderkey AS order_id,
            o_orderdate AS order_time
        FROM lineitem
        LEFT JOIN orders ON l_orderkey = o_orderkey
    ) order_detail
    GROUP BY customer_id, day_part, be_type, product_code;
```
### 2. What did you expect to see? (Required)
query success.
### 3. What did you see instead (Required)
query failed and tiflash crash
### 4. What is your TiFlash version? (Required)
nightly

### PR DESCRIPTION
**Pull request by ChangRui-Ryan**
### What problem does this PR solve?

Issue Number: close #10553

Problem Summary:

### What is changed and how it works?

```commit-message
need to use alignedAlloc for Complex Type
```

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: dbms/src/AggregateFunctions/AggregateFunctionGroupUniqArray.h [hunk 1]
```diff
@@ -152,6 +152,7 @@ class AggregateFunctionGroupUniqArrayGeneric
 
     void deserialize(AggregateDataPtr __restrict place, ReadBuffer & buf, Arena * arena) const override
     {
+        LOG_INFO(Logger::get(), "Deserialize groupUniqArray with PLACE {}", static_cast<void *>(place));
```
Comment (windtalker) [inline dbms/src/AggregateFunctions/AggregateFunctionGroupUniqArray.h]: maybe use debug level?

File: dbms/src/Interpreters/AggregationCommon.h [hunk 2]
```diff
@@ -237,100 +237,6 @@ static inline UInt128 ALWAYS_INLINE hash128(
     return key;
 }
 
-
```
Comment (windtalker) [inline dbms/src/Interpreters/AggregationCommon.h:240]: these are deleted because they are not used?

File: dbms/src/AggregateFunctions/AggregateFunctionGroupUniqArray.h (hunk 1 above)
Comment (ChangRui-Ryan) [reply dbms/src/AggregateFunctions/AggregateFunctionGroupUniqArray.h]: I forgot to delete this line of code after finishing debugging – it can be deleted.

File: dbms/src/Interpreters/AggregationCommon.h (hunk 2 above)
Comment (ChangRui-Ryan) [reply dbms/src/Interpreters/AggregationCommon.h:240]: Yes, initially I noticed that the alloc method was used here and wanted to analyze whether it should be replaced with alignedAlloc, but found that it wasn’t being called at all—so I simply deleted the entire section.

**Review by windtalker — APPROVED** [review]
lgtm

**Review by gengliqi — APPROVED** [review]
